import crypto from "node:crypto";import{mkdir,readFile,rename,writeFile}from"node:fs/promises";import{dirname,resolve}from"node:path";import{validateHistoricalComparabilityReassessment}from"./HistoricalComparabilityReassessment.js";
const stable=v=>Array.isArray(v)?`[${v.map(stable).join(",")}]`:v&&typeof v==="object"?`{${Object.keys(v).sort().map(k=>`${JSON.stringify(k)}:${stable(v[k])}`).join(",")}}`:JSON.stringify(v),clone=structuredClone,freeze=v=>Object.freeze(clone(v));
const empty=()=>({version:"1.0",plans:{},authorizations:{},reassessments:{}});
export class FileHistoricalComparabilityReassessmentRepository{
 constructor({statePath}={}){if(!statePath)throw new TypeError("HISTORICAL_COMPARABILITY_STATE_PATH_REQUIRED");this.statePath=resolve(statePath);this.q=Promise.resolve()}
 async _read(){try{const s=JSON.parse(await readFile(this.statePath,"utf8"));if(s?.version!=="1.0"||[s.plans,s.authorizations,s.reassessments].some(x=>!x||typeof x!=="object"||Array.isArray(x)))throw new Error("HISTORICAL_COMPARABILITY_STATE_INVALID");for(const x of Object.values(s.reassessments))validateHistoricalComparabilityReassessment(x);return s}catch(e){if(e.code==="ENOENT")return empty();throw e}}
 async _write(s){await mkdir(dirname(this.statePath),{recursive:true});const t=`${this.statePath}.${process.pid}.${crypto.randomUUID()}.tmp`;await writeFile(t,`${JSON.stringify(s,null,2)}\n`);await rename(t,this.statePath)}
 async _mutate(fn){const run=async()=>{const s=await this._read(),out=await fn(s);await this._write(s);return freeze(out)};const x=this.q.then(run,run);this.q=x.catch(()=>{});return x}
 async recordPlan(value){return this._mutate(s=>{const prior=s.plans[value.planId];if(prior){if(prior.bindingDigest!==value.bindingDigest)throw new Error("HISTORICAL_COMPARABILITY_PLAN_CONFLICT");return prior}s.plans[value.planId]=clone(value);return value})}
 async getPlan(id){const x=(await this._read()).plans[id];return x?freeze(x):null}
 async recordAuthorization(value){return this._mutate(s=>{if(!s.plans[value.planId]||s.plans[value.planId].bindingDigest!==value.planBindingDigest)throw new Error("HISTORICAL_COMPARABILITY_AUTHORIZATION_PLAN_INVALID");const prior=s.authorizations[value.authorizationId];if(prior){if(stable(prior)!==stable(value))throw new Error("HISTORICAL_COMPARABILITY_AUTHORIZATION_CONFLICT");return prior}s.authorizations[value.authorizationId]=clone(value);return value})}
 async getAuthorization(id){const x=(await this._read()).authorizations[id];return x?freeze(x):null}
 async recordReassessments(values){for(const x of values)validateHistoricalComparabilityReassessment(x);return this._mutate(s=>{for(const x of values){const prior=s.reassessments[x.reassessmentId],same=Object.values(s.reassessments).find(y=>y.observationId===x.observationId&&y.migrationVersion===x.migrationVersion);if(prior&&stable(prior)!==stable(x)||same&&same.reassessmentId!==x.reassessmentId)throw new Error("HISTORICAL_COMPARABILITY_REASSESSMENT_CONFLICT")}let added=0;for(const x of values)if(!s.reassessments[x.reassessmentId]){s.reassessments[x.reassessmentId]=clone(x);added++}return{status:added?"RECORDED":"DUPLICATE",added,total:Object.keys(s.reassessments).length}})}
 async getAllReassessments(){return freeze(Object.values((await this._read()).reassessments))}
}

