import {mkdir,readFile,rename,writeFile} from "node:fs/promises";
import {dirname,resolve} from "node:path";
import {FileSingleWriterRunLock,SINGLE_WRITER_LOCK_STATUSES} from "../runtime/FileSingleWriterRunLock.js";
import {validateHistoricalFactReplayAuthorization} from "./HistoricalFactReplayAuthorization.js";
const initial=()=>({version:"1.0",authorizations:{},byPlan:{},consumptions:{}}),clone=structuredClone,freeze=Object.freeze;
export class FileHistoricalFactReplayAuthorizationRepository{
  constructor({statePath,now=()=>new Date().toISOString(),runLock}={}){if(!statePath)throw new TypeError("statePath is required.");this.statePath=resolve(statePath);this.now=now;this.queue=Promise.resolve();this.runLock=runLock??new FileSingleWriterRunLock({lockPath:`${this.statePath}.lock`,now});}
  async _lock(fn){const run=async()=>{const result=await this.runLock.runExclusive(fn);if(result.status!==SINGLE_WRITER_LOCK_STATUSES.COMPLETED)throw new Error("HISTORICAL_FACT_REPLAY_AUTHORIZATION_REPOSITORY_BUSY");return result.result;},task=this.queue.then(run,run);this.queue=task.catch(()=>{});return task;}
  async _read(){try{const state=JSON.parse(await readFile(this.statePath,"utf8"));if(state?.version!=="1.0"||!state.authorizations||!state.byPlan||!state.consumptions)throw new Error("HISTORICAL_FACT_REPLAY_AUTHORIZATION_STATE_INVALID");for(const[id,value]of Object.entries(state.authorizations))if(id!==value.authorizationId||!validateHistoricalFactReplayAuthorization(value).valid)throw new Error("HISTORICAL_FACT_REPLAY_AUTHORIZATION_STATE_INVALID");for(const[plan,id]of Object.entries(state.byPlan))if(state.authorizations[id]?.replayPlanId!==plan)throw new Error("HISTORICAL_FACT_REPLAY_AUTHORIZATION_STATE_INVALID");return state;}catch(error){if(error?.code==="ENOENT")return initial();if(error?.message==="HISTORICAL_FACT_REPLAY_AUTHORIZATION_STATE_INVALID")throw error;throw new Error("HISTORICAL_FACT_REPLAY_AUTHORIZATION_STATE_INVALID");}}
  async _commit(state){await mkdir(dirname(this.statePath),{recursive:true});const temp=`${this.statePath}.tmp-${process.pid}-${Date.now()}`;await writeFile(temp,`${JSON.stringify(state,null,2)}\n`);await rename(temp,this.statePath);}
  async record(value){if(!validateHistoricalFactReplayAuthorization(value).valid)throw new Error("HISTORICAL_FACT_REPLAY_AUTHORIZATION_INVALID");return this._lock(async()=>{const state=await this._read(),id=state.byPlan[value.replayPlanId];if(id){const existing=state.authorizations[id];if(existing.authorizationId===value.authorizationId&&existing.authorizationDigest===value.authorizationDigest)return freeze(clone(existing));throw new Error("HISTORICAL_FACT_REPLAY_AUTHORIZATION_CONFLICT");}state.authorizations[value.authorizationId]=clone(value);state.byPlan[value.replayPlanId]=value.authorizationId;await this._commit(state);return freeze(clone(value));});}
  async getById(id){const value=(await this._read()).authorizations[id];return value?freeze(clone(value)):null;}
  async getConsumption(id){const value=(await this._read()).consumptions[id];return value?freeze(clone(value)):null;}
  async consume({authorizationId,planBindingDigest,resultsDigest,admitted,duplicates}){return this._lock(async()=>{const state=await this._read(),authorization=state.authorizations[authorizationId];if(!authorization)throw new Error("HISTORICAL_FACT_REPLAY_AUTHORIZATION_NOT_FOUND");if(authorization.planBindingDigest!==planBindingDigest)throw new Error("HISTORICAL_FACT_REPLAY_CONSUMPTION_CONFLICT");const material={schemaVersion:"1.0",authorizationId,planBindingDigest,resultsDigest,admitted,duplicates};const existing=state.consumptions[authorizationId];if(existing){for(const key of Object.keys(material))if(existing[key]!==material[key])throw new Error("HISTORICAL_FACT_REPLAY_CONSUMPTION_CONFLICT");return freeze({status:"ALREADY_CONSUMED",consumption:clone(existing)});}state.consumptions[authorizationId]={...material,consumedAt:this.now()};await this._commit(state);return freeze({status:"CONSUMED",consumption:clone(state.consumptions[authorizationId])});});}
}
