import {mkdir,readFile,rename,writeFile} from "node:fs/promises";
import {dirname,resolve} from "node:path";
import {validateHistoricalAdmissionAuthorization} from "./HistoricalAdmissionAuthorization.js";
const initial=()=>({version:"1.0",authorizations:{},byEvidence:{},consumptions:{}}),clone=structuredClone,freeze=value=>Object.freeze(value);
export class FileHistoricalAdmissionAuthorizationRepository{
  constructor({statePath,now=()=>new Date().toISOString()}={}){if(!statePath)throw new TypeError("statePath is required.");this.statePath=resolve(statePath);this.now=now;this.queue=Promise.resolve();}
  async _lock(fn){const task=this.queue.then(fn,fn);this.queue=task.catch(()=>{});return task;}
  async _read(){try{const state=JSON.parse(await readFile(this.statePath,"utf8"));if(state?.version!=="1.0"||!state.authorizations||!state.byEvidence||!state.consumptions)throw new Error("HISTORICAL_AUTHORIZATION_STATE_INVALID");for(const [id,value] of Object.entries(state.authorizations))if(id!==value.authorizationId||!validateHistoricalAdmissionAuthorization(value).valid)throw new Error("HISTORICAL_AUTHORIZATION_STATE_INVALID");return state;}catch(error){if(error?.code==="ENOENT")return initial();if(error?.message==="HISTORICAL_AUTHORIZATION_STATE_INVALID")throw error;throw new Error("HISTORICAL_AUTHORIZATION_STATE_INVALID");}}
  async _commit(state){await mkdir(dirname(this.statePath),{recursive:true});const temp=`${this.statePath}.tmp-${process.pid}-${Date.now()}`;await writeFile(temp,`${JSON.stringify(state,null,2)}\n`);await rename(temp,this.statePath);}
  async record(value){if(!validateHistoricalAdmissionAuthorization(value).valid)throw new TypeError("HISTORICAL_AUTHORIZATION_INVALID");return this._lock(async()=>{const state=await this._read(),existingId=state.byEvidence[value.evidenceId];if(existingId){const existing=state.authorizations[existingId];if(existing.authorizationId===value.authorizationId&&existing.candidateBindingDigest===value.candidateBindingDigest)return freeze(clone(existing));throw new Error("HISTORICAL_AUTHORIZATION_CONFLICT");}state.authorizations[value.authorizationId]=clone(value);state.byEvidence[value.evidenceId]=value.authorizationId;await this._commit(state);return freeze(clone(value));});}
  async getById(id){const value=(await this._read()).authorizations[id];return value?freeze(clone(value)):null;}
  async getConsumption(id){const value=(await this._read()).consumptions[id];return value?freeze(clone(value)):null;}
  async consume({authorizationId,candidateBindingDigest,observationId,status}){return this._lock(async()=>{const state=await this._read(),authorization=state.authorizations[authorizationId];if(!authorization)throw new Error("HISTORICAL_AUTHORIZATION_NOT_FOUND");if(authorization.candidateBindingDigest!==candidateBindingDigest)throw new Error("HISTORICAL_AUTHORIZATION_CONSUMPTION_CONFLICT");const existing=state.consumptions[authorizationId];if(existing){if(existing.candidateBindingDigest!==candidateBindingDigest||existing.observationId!==observationId)throw new Error("HISTORICAL_AUTHORIZATION_CONSUMPTION_CONFLICT");return freeze({status:"ALREADY_CONSUMED",consumption:clone(existing)});}const consumption={schemaVersion:"1.0",authorizationId,candidateBindingDigest,observationId,status,consumedAt:this.now()};state.consumptions[authorizationId]=consumption;await this._commit(state);return freeze({status:"CONSUMED",consumption:clone(consumption)});});}
}
