import {assessDataForSeoEvidencePromotion} from "../market/dataforseo/DataForSeoEvidencePromotionAssessment.js";
import {createHistoricalObservation,createHistoricalObservationId} from "./HistoricalObservation.js";
import {defaultSourceRightsRegistry} from "../rights/SourceRightsRegistry.js";
import {RIGHTS_STATES} from "../rights/SourceRightsPolicy.js";
import crypto from "node:crypto";

function nonBlank(value,code){if(typeof value!=="string"||value.trim()==="")throw new TypeError(code);return value.trim();}
const stable=value=>{if(Array.isArray(value))return `[${value.map(stable).join(",")}]`;if(value&&typeof value==="object")return `{${Object.keys(value).sort().map(key=>`${JSON.stringify(key)}:${stable(value[key])}`).join(",")}}`;return JSON.stringify(value);};
const hash=value=>crypto.createHash("sha256").update(stable(value)).digest("hex");
const freeze=value=>{if(value&&typeof value==="object"&&!Object.isFrozen(value)){Object.freeze(value);for(const child of Object.values(value))freeze(child);}return value;};
const requiredRights=["acquisition.api","retention.historical","retention.durableAuditMetadata","derivation.historicalAnalytics"];
const at=(value,path)=>path.split(".").reduce((current,key)=>current?.[key],value);

export class HistoricalObservationAdmissionService{
  constructor({evidenceRepository,decisionRepository,productRepository,retailerRepository,historicalRepository,acquisitionChainResolver,refreshGovernanceResolver=null,initialAcquisitionCompositionResolver=null,rightsRegistry=defaultSourceRightsRegistry,now=()=>new Date().toISOString()}={}){
    if(!evidenceRepository?.getById)throw new TypeError("evidenceRepository is required.");if(!decisionRepository?.getAll||!decisionRepository?.getAllRemediations)throw new TypeError("decisionRepository is required.");if(!productRepository?.getById)throw new TypeError("productRepository is required.");if(!retailerRepository?.getAll)throw new TypeError("retailerRepository is required.");if(!historicalRepository?.accept||!historicalRepository?.getAll)throw new TypeError("historicalRepository is required.");if(typeof acquisitionChainResolver!=="function")throw new TypeError("acquisitionChainResolver is required.");
    if(refreshGovernanceResolver!==null&&typeof refreshGovernanceResolver!=="function")throw new TypeError("refreshGovernanceResolver must be a function.");if(initialAcquisitionCompositionResolver!==null&&typeof initialAcquisitionCompositionResolver!=="function")throw new TypeError("initialAcquisitionCompositionResolver must be a function.");if(!rightsRegistry?.require)throw new TypeError("rightsRegistry is required.");Object.assign(this,{evidenceRepository,decisionRepository,productRepository,retailerRepository,historicalRepository,acquisitionChainResolver,refreshGovernanceResolver,initialAcquisitionCompositionResolver,rightsRegistry,now});
  }
  async assess({evidenceId}={}){
    nonBlank(evidenceId,"EVIDENCE_ID_REQUIRED");
    const record=await this.evidenceRepository.getById(evidenceId);if(!record)throw new Error(`HISTORICAL_EVIDENCE_NOT_FOUND:${evidenceId}`);const retainedBefore=structuredClone(record);
    const [decisions,remediations,retailers,evidenceRecords,historicalObservations]=await Promise.all([this.decisionRepository.getAll(),this.decisionRepository.getAllRemediations(),this.retailerRepository.getAll(),this.evidenceRepository.getAll?this.evidenceRepository.getAll():[record],this.historicalRepository.getAll()]);const refreshGovernance=this.refreshGovernanceResolver?await this.refreshGovernanceResolver(record):null;const identityReuseAssessments=refreshGovernance?.identityReuseAssessments??[];
    const initialComposition=!refreshGovernance&&this.initialAcquisitionCompositionResolver?await this.initialAcquisitionCompositionResolver({record,evidenceRecords}):null,initialAcquisitionIdentityProjections=initialComposition?.initialAcquisitionIdentityProjections??[];
    const assessment=assessDataForSeoEvidencePromotion({records:[record],identityReviewDecisions:decisions,identityReviewRemediations:remediations,identityReuseAssessments,initialAcquisitionIdentityProjections,identityLineageEvidenceRecords:evidenceRecords,historicalObservations,atlasRetailers:retailers});
    if(assessment.state!=="HISTORICAL_ELIGIBLE"||assessment.historicalEligible!==true)throw new Error(`HISTORICAL_ADMISSION_NOT_ELIGIBLE:${assessment.state}`);
    if(assessment.canonicalEligible!==false||assessment.publicationEligible!==false)throw new Error("HISTORICAL_ADMISSION_GOVERNANCE_BOUNDARY_INVALID");
    const projection=assessment.identityProjections?.find(value=>value.evidenceId===record.evidenceId);if(!projection)throw new Error("HISTORICAL_ADMISSION_GOVERNED_PROJECTION_MISSING");
    if(projection.product.state!=="VERIFIED"||projection.merchant.state!=="REGISTERED"||projection.merchant.atlasResolution?.outcome!=="RESOLVED")throw new Error("HISTORICAL_ADMISSION_IDENTITY_NOT_RESOLVED");
    const atlasProduct=await this.productRepository.getById(projection.product.atlasProductId);if(atlasProduct?.identity?.atlasProductId!==projection.product.atlasProductId)throw new Error("HISTORICAL_ADMISSION_ATLAS_PRODUCT_MISMATCH");
    const retailer=retailers.find(x=>x.id===projection.merchant.merchantId);if(!retailer)throw new Error("HISTORICAL_ADMISSION_ATLAS_RETAILER_MISSING");
    let acquisition;if(refreshGovernance){const reuse=refreshGovernance.reuse;if(reuse.targetEvidenceId!==record.evidenceId||reuse.atlasProductId!==projection.product.atlasProductId||reuse.retailerId!==projection.merchant.merchantId||reuse.providerTaskId!==record.candidate?.marketEvidence?.provenance?.sourceTaskId)throw new Error("HISTORICAL_REFRESH_ADMISSION_BINDING_INVALID");acquisition={type:"HISTORICAL_REFRESH",sellersTaskId:reuse.providerTaskId,refreshPlanId:reuse.refreshPlanId,authorizationId:reuse.authorizationId,identityReuseAssessmentId:reuse.reuseAssessmentId,sourceEvidenceId:reuse.sourceEvidenceId,providerIdentity:structuredClone(reuse.providerIdentity)};}else{const chain=initialComposition?.acquisitionChain??await this.acquisitionChainResolver(record);for(const key of ["productsTaskId","sellersTaskId"])nonBlank(chain?.[key],`HISTORICAL_${key.toUpperCase()}_REQUIRED`);const direct=chain.identityLineageType==="DIRECT_PRODUCTS_STRONG_IDENTITY";if(!direct)nonBlank(chain?.productInfoTaskId,"HISTORICAL_PRODUCTINFOTASKID_REQUIRED");if(chain.sellersTaskId!==record.candidate?.marketEvidence?.provenance?.sourceTaskId)throw new Error("HISTORICAL_ACQUISITION_CHAIN_MISMATCH");acquisition=direct?{identityLineageType:"DIRECT_PRODUCTS_STRONG_IDENTITY",productsTaskId:chain.productsTaskId,productInfoTaskId:null,sellersTaskId:chain.sellersTaskId}:{productsTaskId:chain.productsTaskId,productInfoTaskId:chain.productInfoTaskId,sellersTaskId:chain.sellersTaskId};}
    const evidence=record.candidate.marketEvidence;if(evidence.provider!=="DATAFORSEO"||evidence.source!=="DATAFORSEO_GOOGLE_SHOPPING")throw new Error("HISTORICAL_SOURCE_RIGHTS_SOURCE_MISMATCH");let rightsProfile;try{rightsProfile=this.rightsRegistry.require(evidence.source);}catch{throw new Error("HISTORICAL_SOURCE_RIGHTS_MISSING");}if(requiredRights.some(capability=>at(rightsProfile,capability)!==RIGHTS_STATES.ALLOWED))throw new Error("HISTORICAL_SOURCE_RIGHTS_DENIED");
    const expectedObservation={observationId:createHistoricalObservationId(record.evidenceId),atlasProductId:projection.product.atlasProductId,retailerId:projection.merchant.merchantId,marketplace:projection.merchant.canonicalDomain,observationTime:evidence.provenance.observedAt,market:{sellerName:retailer.name,sourceUrl:evidence.seller.url,basePrice:evidence.pricing.basePrice,totalPrice:evidence.pricing.totalPrice,shipping:evidence.pricing.shippingPrice,tax:evidence.pricing.tax,currency:evidence.pricing.currency,condition:evidence.offer.condition,availability:evidence.offer.availability},provenance:{retainedEvidenceId:record.evidenceId,provider:evidence.provider,source:evidence.source,rawPayloadReference:evidence.provenance.rawPayloadReference,acquisition,identityReview:{productDecisionId:projection.product.decisionId,productRemediationId:projection.product.remediationId,merchantDecisionId:projection.merchant.decisionId,merchantRemediationId:projection.merchant.remediationId}}};
    const candidateBinding={evidenceId:record.evidenceId,evidenceFingerprint:record.materialEvidenceFingerprint??hash(record.candidate),atlasProductId:projection.product.atlasProductId,productProjectionId:projection.product.governedAcquisitionProjectionId??null,retailerId:projection.merchant.merchantId,merchantDecisionId:projection.merchant.decisionId,historicalObservationId:expectedObservation.observationId,acquisition:structuredClone(acquisition),rightsSourceId:rightsProfile.sourceId,rightsProfileHash:hash(rightsProfile),expectedObservationHash:hash(expectedObservation)};const result={schemaVersion:"1.0",assessmentType:"HISTORICAL_OBSERVATION_ADMISSION",assessmentId:`mer_histassess_${hash(candidateBinding).slice(0,24)}`,policyVersion:"DF004-E2J-2.0",promotionAssessment:assessment,candidateBinding,expectedObservation,historicalEligible:true,canonicalEligible:false,publicationEligible:false,networkOperation:"NONE",paidTaskCreated:false,actualSpendUsd:0};if(JSON.stringify(record)!==JSON.stringify(retainedBefore))throw new Error("RETAINED_EVIDENCE_MUTATED_DURING_ASSESSMENT");return freeze(result);
  }
  async admit({evidenceId,admittedBy,authorizedAssessment=null}={}){
    nonBlank(evidenceId,"EVIDENCE_ID_REQUIRED");nonBlank(admittedBy,"ADMITTED_BY_REQUIRED");const governed=await this.assess({evidenceId});if(authorizedAssessment&&(authorizedAssessment.assessmentId!==governed.assessmentId||stable(authorizedAssessment.candidateBinding)!==stable(governed.candidateBinding)))throw new Error("HISTORICAL_ADMISSION_AUTHORIZATION_BINDING_MISMATCH");const {promotionAssessment:assessment,expectedObservation,candidateBinding}=governed;const record=await this.evidenceRepository.getById(evidenceId);const retainedBefore=structuredClone(record);
    const idempotencyKey=`E2J_HISTORICAL_ADMISSION:${record.evidenceId}`;const existing=await this.historicalRepository.findByIdempotencyKey(idempotencyKey);if(existing)return Object.freeze({status:"DUPLICATE",evidenceId,observationId:existing.observationId,observation:existing,assessment});
    const observationId=candidateBinding.historicalObservationId;const observation=createHistoricalObservation({...expectedObservation,admittedAt:this.now(),admittedBy:admittedBy.trim(),idempotencyKey});
    const accepted=await this.historicalRepository.accept(observation,idempotencyKey);if(JSON.stringify(record)!==JSON.stringify(retainedBefore))throw new Error("RETAINED_EVIDENCE_MUTATED_DURING_ADMISSION");
    return Object.freeze({status:accepted.status,evidenceId,observationId:accepted.observationId,observation,assessment});
  }
}
export default HistoricalObservationAdmissionService;
