import crypto from "node:crypto";
import {assessHistoricalOfferComparability,HISTORICAL_OFFER_COMPARABILITY} from "./HistoricalOfferComparabilityAssessment.js";
import {createHistoricalComparabilityReassessment,HISTORICAL_COMPARABILITY_REASSESSMENT_VERSION} from "./HistoricalComparabilityReassessment.js";
import {sourceRightsProfileDigest} from "../rights/SourceRightsRegistry.js";

export const HISTORICAL_COMPARABILITY_RECOVERY_AUTHORIZE_CONFIRMATION="AUTHORIZE-DATAFORSEO-AMAZON-HISTORICAL-COMPARABILITY-RECOVERY";
export const HISTORICAL_COMPARABILITY_RECOVERY_EXECUTE_CONFIRMATION="EXECUTE-DATAFORSEO-AMAZON-HISTORICAL-COMPARABILITY-RECOVERY";
const stable=v=>Array.isArray(v)?`[${v.map(stable).join(",")}]`:v&&typeof v==="object"?`{${Object.keys(v).sort().map(k=>`${JSON.stringify(k)}:${stable(v[k])}`).join(",")}}`:JSON.stringify(v);
const digest=v=>crypto.createHash("sha256").update(stable(v)).digest("hex"),text=v=>typeof v==="string"&&v.trim()?v.trim():null,freeze=v=>{if(v&&typeof v==="object"&&!Object.isFrozen(v)){Object.freeze(v);for(const x of Object.values(v))freeze(x)}return v};
const exactToken=(value,token)=>new RegExp(`(^|[^A-Z0-9])${token.replace(/[.*+?^${}()|[\]\\]/g,"\\$&")}([^A-Z0-9]|$)`,"i").test(value);
const resultId=o=>o.provenance?.acquisition?.immutableSellersResultId??o.provenance?.acquisition?.canonicalResultId;
const resultDigest=o=>o.provenance?.acquisition?.immutableSellersResultDigest??o.provenance?.acquisition?.canonicalResultDigest;
const asin=o=>o.provenance?.acquisition?.governedAsin??o.provenance?.acquisition?.providerIdentity?.asin;
const planMaterial=p=>({version:HISTORICAL_COMPARABILITY_REASSESSMENT_VERSION,entries:p.entries,summary:p.summary});

export class HistoricalComparabilityRecoveryService{
 constructor({historicalRepository,evidenceRepository,resultResolver,productRepository,reassessmentRepository,rightsRegistry,now=()=>new Date().toISOString()}={}){if(!historicalRepository?.getAll||!evidenceRepository?.getById||!resultResolver?.getCanonicalResultById||!productRepository?.loadProduct||!reassessmentRepository?.recordPlan||!rightsRegistry?.require)throw new TypeError("HISTORICAL_COMPARABILITY_RECOVERY_DEPENDENCIES_REQUIRED");Object.assign(this,{historicalRepository,evidenceRepository,resultResolver,productRepository,reassessmentRepository,rightsRegistry,now})}
 async _entry(observation){
  const fail=reason=>({observationId:observation.observationId,atlasProductId:observation.atlasProductId,status:"BLOCKED",reason});
  try{
   if(observation.provenance?.source!=="DATAFORSEO_AMAZON"||observation.comparability?.classification!==HISTORICAL_OFFER_COMPARABILITY.UNKNOWN_COMPARABILITY)return null;
   const retainedEvidenceId=observation.provenance.retainedEvidenceId,evidence=await this.evidenceRepository.getById(retainedEvidenceId);if(!evidence||evidence.candidate?.identity?.atlasProductId!==observation.atlasProductId) return fail("RETAINED_EVIDENCE_LINEAGE_INVALID");
   const canonicalResultId=resultId(observation),canonicalResult=canonicalResultId&&await this.resultResolver.getCanonicalResultById(canonicalResultId);if(!canonicalResult||canonicalResult.canonicalResultId!==canonicalResultId||canonicalResult.atlasProductId!==observation.atlasProductId||canonicalResult.sourceId!=="DATAFORSEO_AMAZON"||canonicalResult.operation!=="AMAZON_SELLERS")return fail("IMMUTABLE_RESULT_LINEAGE_INVALID");
   if(canonicalResult.resultDigest!==resultDigest(observation)||canonicalResult.resultDigest!==evidence.candidate.marketEvidence.provenance?.immutableProviderResultDigest||canonicalResult.resultDigest!==digest(canonicalResult.operationResult))return fail("IMMUTABLE_RESULT_DIGEST_INVALID");
   const expectedRights=observation.provenance.acquisition?.sourceRightsProfileDigest,rights=this.rightsRegistry.require("DATAFORSEO_AMAZON");if(sourceRightsProfileDigest(rights)!==expectedRights||observation.provenance.rights?.profileHash!==expectedRights||canonicalResult.sourceRightsProfileDigest!==expectedRights||evidence.candidate.marketEvidence.provenance?.sourceRightsProfileDigest!==expectedRights)return fail("SOURCE_RIGHTS_LINEAGE_INVALID");
   const rows=canonicalResult.operationResult?.result,governedAsin=text(asin(observation))?.toUpperCase();if(!Array.isArray(rows)||rows.length!==1||text(rows[0]?.asin)?.toUpperCase()!==governedAsin||text(evidence.candidate.marketEvidence.providerIdentity?.asin)?.toUpperCase()!==governedAsin)return fail("ASIN_LINEAGE_INVALID");
   const title=text(rows[0]?.title),product=await this.productRepository.loadProduct(observation.atlasProductId),mpn=text(product?.identity?.manufacturerPartNumber);if(!title||!mpn||!exactToken(title,mpn))return fail("EXACT_MPN_TITLE_EVIDENCE_INVALID");
   const enriched=structuredClone(evidence);enriched.candidate.marketEvidence.productEvidence={...(enriched.candidate.marketEvidence.productEvidence??{}),title};const assessment=assessHistoricalOfferComparability({record:enriched});
   if(assessment.classification!==HISTORICAL_OFFER_COMPARABILITY.STANDALONE_COMPARABLE)return fail("REASSESSMENT_NOT_STANDALONE_COMPARABLE");
   return{observationId:observation.observationId,retainedEvidenceId,immutableProviderResultId:canonicalResultId,immutableProviderResultDigest:canonicalResult.resultDigest,atlasProductId:observation.atlasProductId,governedAsin,priorClassification:observation.comparability.classification,newAssessment:assessment,titleDigest:digest(title),rightsProfileDigest:expectedRights,status:"READY"};
  }catch(error){return fail(String(error?.message??error))}
 }
 async prepare(){const observations=await this.historicalRepository.getAll(),entries=[];for(const observation of observations){const entry=await this._entry(observation);if(entry)entries.push(entry)}entries.sort((a,b)=>a.observationId.localeCompare(b.observationId));const summary={candidates:entries.length,ready:entries.filter(x=>x.status==="READY").length,blocked:entries.filter(x=>x.status==="BLOCKED").length,providerCalls:0,paidTasks:0,actualSpendUsd:0},bindingDigest=digest(planMaterial({entries,summary})),plan={schemaVersion:"1.0",planId:`mer_histcomparerecovery_${bindingDigest.slice(0,24)}`,bindingDigest,preparedAt:this.now(),status:summary.candidates>0&&summary.blocked===0?"READY":"BLOCKED",entries,summary,authority:{provider:false,current:false,historyMutation:false,publication:false,release:false}};return this.reassessmentRepository.recordPlan(freeze(plan))}
 async inspect({planId}={}){const plan=await this.reassessmentRepository.getPlan(planId);if(!plan)throw new Error("HISTORICAL_COMPARABILITY_RECOVERY_PLAN_NOT_FOUND");return plan}
 async authorize({planId,operator,reason,confirmation}={}){if(confirmation!==HISTORICAL_COMPARABILITY_RECOVERY_AUTHORIZE_CONFIRMATION||!text(operator)||!text(reason))throw new Error("HISTORICAL_COMPARABILITY_RECOVERY_AUTHORIZATION_INVALID");const plan=await this.inspect({planId});if(plan.status!=="READY")throw new Error("HISTORICAL_COMPARABILITY_RECOVERY_PLAN_BLOCKED");const material={planId,planBindingDigest:plan.bindingDigest,operator:text(operator),reason:text(reason),confirmation},bindingDigest=digest(material),authorization={schemaVersion:"1.0",authorizationId:`mer_histcompareauth_${bindingDigest.slice(0,24)}`,...material,bindingDigest,authorizedAt:this.now(),providerSpendAuthorized:false,currentMutationAuthorized:false,appendOnlyReassessmentAuthorized:true};return this.reassessmentRepository.recordAuthorization(freeze(authorization))}
 async execute({planId,authorizationId,confirmation}={}){if(confirmation!==HISTORICAL_COMPARABILITY_RECOVERY_EXECUTE_CONFIRMATION)throw new Error("HISTORICAL_COMPARABILITY_RECOVERY_EXECUTION_INVALID");const stored=await this.inspect({planId}),fresh=await this.prepare();if(fresh.planId!==stored.planId||fresh.bindingDigest!==stored.bindingDigest)throw new Error("HISTORICAL_COMPARABILITY_RECOVERY_PLAN_STALE");const authorization=await this.reassessmentRepository.getAuthorization(authorizationId);if(!authorization||authorization.planId!==planId||authorization.planBindingDigest!==stored.bindingDigest)throw new Error("HISTORICAL_COMPARABILITY_RECOVERY_AUTHORIZATION_INVALID");const values=stored.entries.map(entry=>createHistoricalComparabilityReassessment({...entry,recordedAt:authorization.authorizedAt})),result=await this.reassessmentRepository.recordReassessments(values);return freeze({...result,planId,authorizationId,providerCalls:0,paidTasks:0,actualSpendUsd:0,currentChanged:false,historyChanged:false})}
}
