import crypto from "node:crypto";
import {assertHistoricalFactReplayAuthorization,historicalFactReplayAuthorizationConfirmation,historicalFactReplayExecutionConfirmation} from "./HistoricalFactReplayAuthorization.js";
import {validateHistoricalFactReplayPlan} from "./HistoricalFactReplayPreparationService.js";
const stable=value=>Array.isArray(value)?`[${value.map(stable).join(",")}]`:value&&typeof value==="object"?`{${Object.keys(value).sort().map(key=>`${JSON.stringify(key)}:${stable(value[key])}`).join(",")}}`:JSON.stringify(value);
const hash=value=>crypto.createHash("sha256").update(stable(value)).digest("hex");
const exact=(input,keys)=>{for(const key of Object.keys(input??{}))if(!keys.includes(key))throw new Error(`HISTORICAL_FACT_REPLAY_CALLER_SUBSTITUTION_FORBIDDEN:${key}`);};
const separation={currentPriceEligible:false,cheapestEligible:false,pickEligible:false,publicationEligible:false,currentDisplayProjection:false,canonicalRetailerCreated:false,affiliateAuthority:false,providerCalls:0,paidTasks:0,retrievals:0,providerSpendUsd:0};
export class HistoricalFactReplayAuthorizationService{constructor({planLoader,authorizationRepository,now=()=>new Date().toISOString()}={}){if(typeof planLoader!=="function"||!authorizationRepository?.record)throw new TypeError("HISTORICAL_FACT_REPLAY_AUTHORIZATION_DEPENDENCY_REQUIRED");Object.assign(this,{planLoader,authorizationRepository,now});}async authorize(input={}){exact(input,["planId","operator","reason","expiresAt","confirmation"]);if(input.confirmation!==historicalFactReplayAuthorizationConfirmation(input.planId))throw new Error("HISTORICAL_FACT_REPLAY_AUTHORIZATION_CONFIRMATION_INVALID");const plan=await this.planLoader(input.planId);if(!validateHistoricalFactReplayPlan(plan).valid)throw new Error("HISTORICAL_FACT_REPLAY_PLAN_INVALID");const {createHistoricalFactReplayAuthorization}=await import("./HistoricalFactReplayAuthorization.js");return this.authorizationRepository.record(createHistoricalFactReplayAuthorization({plan,operator:input.operator,reason:input.reason,preparedAt:this.now(),expiresAt:input.expiresAt}));}}
export class HistoricalFactReplayExecutionService{
  constructor({planLoader,authorizationRepository,assessmentResolver,admissionService,executionLock,now=()=>new Date().toISOString()}={}){if(typeof planLoader!=="function"||!authorizationRepository?.getById||!authorizationRepository?.getConsumption||!authorizationRepository?.consume||typeof assessmentResolver!=="function"||!admissionService?.admit||!executionLock?.runExclusive)throw new TypeError("HISTORICAL_FACT_REPLAY_EXECUTION_DEPENDENCY_REQUIRED");Object.assign(this,{planLoader,authorizationRepository,assessmentResolver,admissionService,executionLock,now});}
  async execute(input={}){exact(input,["authorizationId","confirmation","executedBy"]);if(input.confirmation!==historicalFactReplayExecutionConfirmation(input.authorizationId))throw new Error("HISTORICAL_FACT_REPLAY_EXECUTION_CONFIRMATION_INVALID");if(typeof input.executedBy!=="string"||!input.executedBy.trim())throw new Error("HISTORICAL_FACT_REPLAY_EXECUTED_BY_REQUIRED");const outcome=await this.executionLock.runExclusive(async()=>this._execute(input));if(outcome.status!=="COMPLETED")throw new Error("HISTORICAL_FACT_REPLAY_EXECUTION_BUSY");return outcome.result;}
  async _execute(input){const authorization=await this.authorizationRepository.getById(input.authorizationId);if(!authorization)throw new Error("HISTORICAL_FACT_REPLAY_AUTHORIZATION_NOT_FOUND");const previous=await this.authorizationRepository.getConsumption(input.authorizationId);if(previous)return Object.freeze({status:"ALREADY_CONSUMED",authorizationId:input.authorizationId,admitted:previous.admitted,duplicates:previous.duplicates,...separation});const plan=await this.planLoader(authorization.replayPlanId),report=validateHistoricalFactReplayPlan(plan);if(!report.valid)throw new Error(`HISTORICAL_FACT_REPLAY_PLAN_INVALID:${report.errors.join(",")}`);assertHistoricalFactReplayAuthorization({authorization,plan,now:this.now()});
    const assessments=[];for(const bound of plan.newFacts){const assessment=await this.assessmentResolver({evidenceId:bound.evidenceId});const digest=hash(assessment.candidateBinding);if(assessment.factLevelHistoricalEligible!==true||assessment.canonicalEligible!==false||assessment.currentPriceEligible!==false||assessment.cheapestEligible!==false||assessment.pickEligible!==false||assessment.publicationEligible!==false)throw new Error(`HISTORICAL_FACT_REPLAY_CANDIDATE_INELIGIBLE:${bound.evidenceId}`);if(assessment.candidateBinding?.historicalObservationId!==bound.expectedHistoricalObservationId||assessment.candidateBinding?.expectedObservationHash!==bound.expectedObservationHash||digest!==bound.candidateBindingDigest||assessment.candidateBinding?.atlasProductId!==bound.atlasProductId)throw new Error(`HISTORICAL_FACT_REPLAY_CANDIDATE_BINDING_CHANGED:${bound.evidenceId}`);assessments.push({bound,assessment});}
    const results=[];for(const {bound,assessment}of assessments)results.push(await this.admissionService.admit({evidenceId:bound.evidenceId,admittedBy:input.executedBy.trim(),authorizedAssessment:assessment}));const admitted=results.filter(value=>value.status==="ADMITTED").length,duplicates=results.filter(value=>value.status==="DUPLICATE").length,resultsDigest=hash(results.map(value=>({evidenceId:value.evidenceId,observationId:value.observationId,status:value.status}))),consumed=await this.authorizationRepository.consume({authorizationId:authorization.authorizationId,planBindingDigest:plan.bindingDigest,resultsDigest,admitted,duplicates});return Object.freeze({status:consumed.status==="ALREADY_CONSUMED"?"ALREADY_CONSUMED":"EXECUTED",authorizationId:authorization.authorizationId,replayPlanId:plan.replayPlanId,admitted,duplicates,results:Object.freeze(results),...separation});}
}
