import crypto from "node:crypto";

export const HISTORICAL_ADMISSION_CONFIRMATION="ADMIT-HISTORICAL-OBSERVATION";
const stable=value=>{if(Array.isArray(value))return `[${value.map(stable).join(",")}]`;if(value&&typeof value==="object")return `{${Object.keys(value).sort().map(key=>`${JSON.stringify(key)}:${stable(value[key])}`).join(",")}}`;return JSON.stringify(value);};
const hash=value=>crypto.createHash("sha256").update(stable(value)).digest("hex");
const freeze=value=>{if(value&&typeof value==="object"&&!Object.isFrozen(value)){Object.freeze(value);for(const child of Object.values(value))freeze(child);}return value;};
const required=(value,code)=>{if(typeof value!=="string"||!value.trim())throw new TypeError(code);return value.trim();};
export const historicalAdmissionCandidateBindingDigest=binding=>hash(binding);

export function validateHistoricalAdmissionAuthorization(value){const errors=[];if(value?.schemaVersion!=="1.0"||value?.authorizationType!=="HISTORICAL_OBSERVATION_ADMISSION"||value?.status!=="PENDING_OPERATOR_APPROVAL")errors.push("HISTORICAL_AUTHORIZATION_SCHEMA_INVALID");for(const key of ["authorizationId","evidenceId","assessmentId","policyVersion","candidateBindingDigest","requestedBy","reason"])if(typeof value?.[key]!=="string"||!value[key].trim())errors.push(`HISTORICAL_AUTHORIZATION_${key.toUpperCase()}_REQUIRED`);if(!Number.isFinite(Date.parse(value?.preparedAt))||!Number.isFinite(Date.parse(value?.expiresAt))||Date.parse(value.expiresAt)<=Date.parse(value.preparedAt))errors.push("HISTORICAL_AUTHORIZATION_TIME_INVALID");if(!value?.candidateBinding||historicalAdmissionCandidateBindingDigest(value.candidateBinding)!==value?.candidateBindingDigest||value.candidateBinding.evidenceId!==value.evidenceId)errors.push("HISTORICAL_AUTHORIZATION_BINDING_INVALID");if(value?.singleUse!==true||value?.historicalAdmissionAuthorized!==true||value?.canonicalEligible!==false||value?.publicationEligible!==false||value?.publicationAuthority!==false||value?.currentPriceAuthority!==false||value?.networkOperation!=="NONE"||value?.paidTaskCreated!==false||value?.actualSpendUsd!==0)errors.push("HISTORICAL_AUTHORIZATION_SCOPE_INVALID");return freeze({valid:errors.length===0,errors});}

export function createHistoricalAdmissionAuthorization({assessment,requestedBy,reason,preparedAt=new Date().toISOString(),ttlMinutes=15}={}){if(assessment?.assessmentType!=="HISTORICAL_OBSERVATION_ADMISSION"||assessment?.historicalEligible!==true||assessment?.canonicalEligible!==false||assessment?.publicationEligible!==false)throw new Error("HISTORICAL_ASSESSMENT_NOT_AUTHORIZABLE");if(!Number.isInteger(ttlMinutes)||ttlMinutes<1)throw new TypeError("HISTORICAL_AUTHORIZATION_TTL_INVALID");const candidateBinding=structuredClone(assessment.candidateBinding),candidateBindingDigest=historicalAdmissionCandidateBindingDigest(candidateBinding),intent={evidenceId:candidateBinding.evidenceId,assessmentId:assessment.assessmentId,policyVersion:assessment.policyVersion,candidateBindingDigest,requestedBy:required(requestedBy,"HISTORICAL_AUTHORIZATION_REQUESTED_BY_REQUIRED"),reason:required(reason,"HISTORICAL_AUTHORIZATION_REASON_REQUIRED")},record={schemaVersion:"1.0",authorizationType:"HISTORICAL_OBSERVATION_ADMISSION",authorizationId:`mer_histauth_${hash(intent).slice(0,24)}`,...intent,candidateBinding,expectedObservation:structuredClone(assessment.expectedObservation),preparedAt,expiresAt:new Date(Date.parse(preparedAt)+ttlMinutes*60000).toISOString(),status:"PENDING_OPERATOR_APPROVAL",singleUse:true,historicalAdmissionAuthorized:true,canonicalEligible:false,publicationEligible:false,publicationAuthority:false,currentPriceAuthority:false,livePriceAuthority:false,publicPriceAuthority:false,networkOperation:"NONE",paidTaskCreated:false,actualSpendUsd:0};const report=validateHistoricalAdmissionAuthorization(record);if(!report.valid)throw new TypeError(report.errors.join(","));return freeze(record);}
export function assertHistoricalAdmissionConfirmation(value){if(value!==HISTORICAL_ADMISSION_CONFIRMATION)throw new Error(`EXPLICIT_CONFIRMATION_REQUIRED:--confirm=${HISTORICAL_ADMISSION_CONFIRMATION}`);return true;}
export function assertHistoricalAdmissionAuthorization({authorization,assessment,now=new Date().toISOString()}={}){const report=validateHistoricalAdmissionAuthorization(authorization);if(!report.valid)throw new Error(`HISTORICAL_AUTHORIZATION_INVALID:${report.errors.join(",")}`);if(Date.parse(now)>=Date.parse(authorization.expiresAt))throw new Error("HISTORICAL_AUTHORIZATION_EXPIRED");if(assessment?.historicalEligible!==true||assessment?.canonicalEligible!==false||authorization.assessmentId!==assessment.assessmentId||authorization.policyVersion!==assessment.policyVersion||authorization.candidateBindingDigest!==historicalAdmissionCandidateBindingDigest(assessment.candidateBinding)||stable(authorization.candidateBinding)!==stable(assessment.candidateBinding))throw new Error("HISTORICAL_AUTHORIZATION_BINDING_MISMATCH");return true;}
