import {validateHistoricalObservation} from "./HistoricalObservation.js";

export const HISTORICAL_TREND_STATES=Object.freeze({NO_DATA:"NO_DATA",INSUFFICIENT_HISTORY:"INSUFFICIENT_HISTORY",UP:"UP",DOWN:"DOWN",FLAT:"FLAT",NON_COMPARABLE:"NON_COMPARABLE"});
function freeze(value){if(value&&typeof value==="object"&&!Object.isFrozen(value)){Object.freeze(value);for(const child of Object.values(value))freeze(child);}return value;}
function nonBlank(value){return typeof value==="string"&&value.trim()!=="";}
function normalized(value){return value.trim().toLowerCase();}
function validIso(value){return nonBlank(value)&&Number.isFinite(Date.parse(value));}
function validateQuery(query){const errors=[];if(!query||typeof query!=="object"||Array.isArray(query))errors.push("QUERY_MUST_BE_OBJECT");else{if(!nonBlank(query.atlasProductId))errors.push("ATLAS_PRODUCT_ID_REQUIRED");if(query.retailerId!=null&&!/^RETAILER-[0-9]{4}$/.test(query.retailerId))errors.push("RETAILER_ID_INVALID");for(const field of ["from","to"])if(query[field]!=null&&!validIso(query[field]))errors.push(`${field.toUpperCase()}_INVALID`);if(validIso(query.from)&&validIso(query.to)&&Date.parse(query.from)>Date.parse(query.to))errors.push("DATE_RANGE_INVALID");}if(errors.length)throw new TypeError(`INVALID_HISTORICAL_INTELLIGENCE_QUERY:${errors.join(",")}`);}
function point(record){return {observationId:record.observationId,observationTime:record.observationTime,admittedAt:record.admittedAt,atlasProductId:record.atlasProductId,retailerId:record.retailerId,marketplace:record.marketplace,currency:record.market.currency,basePrice:record.market.basePrice,totalPrice:record.market.totalPrice,shipping:record.market.shipping,tax:record.market.tax,condition:record.market.condition,availability:record.market.availability,retainedEvidenceId:record.provenance.retainedEvidenceId};}
function percentage(change,from){return from>0?(change/from)*100:null;}
function changes(first,previous,latest){if(!first||!previous||!latest||first.observationId===latest.observationId)return {fromFirst:null,fromPrevious:null};const metric=(from,to)=>{const basePrice=to.basePrice-from.basePrice,totalPrice=to.totalPrice-from.totalPrice;return {fromObservationId:from.observationId,toObservationId:to.observationId,basePrice,totalPrice,basePricePercentage:percentage(basePrice,from.basePrice),totalPricePercentage:percentage(totalPrice,from.totalPrice)};};return {fromFirst:metric(first,latest),fromPrevious:metric(previous,latest)};}
function currencySummary(currency,rows){const first=rows[0]??null,latest=rows.at(-1)??null,previous=rows.length>1?rows.at(-2):null;const movement=changes(first,previous,latest);let trendState=HISTORICAL_TREND_STATES.NO_DATA;if(rows.length===1)trendState=HISTORICAL_TREND_STATES.INSUFFICIENT_HISTORY;else if(rows.length>1)trendState=latest.basePrice>first.basePrice?HISTORICAL_TREND_STATES.UP:latest.basePrice<first.basePrice?HISTORICAL_TREND_STATES.DOWN:HISTORICAL_TREND_STATES.FLAT;return {currency,observationCount:rows.length,firstObservationId:first?.observationId??null,latestObservationId:latest?.observationId??null,latestBasePrice:latest?.basePrice??null,latestTotalPrice:latest?.totalPrice??null,lowestBasePrice:rows.length?Math.min(...rows.map(x=>x.basePrice)):null,highestBasePrice:rows.length?Math.max(...rows.map(x=>x.basePrice)):null,lowestTotalPrice:rows.length?Math.min(...rows.map(x=>x.totalPrice)):null,highestTotalPrice:rows.length?Math.max(...rows.map(x=>x.totalPrice)):null,changeFromFirst:movement.fromFirst,changeFromPrevious:movement.fromPrevious,trendState,priceChangeAvailable:rows.length>1};}

export class HistoricalObservationIntelligence{
  constructor({repository}={}){if(!repository?.getAll)throw new TypeError("historical repository is required.");this.repository=repository;}
  async query(query={}){validateQuery(query);const records=await this.repository.getAll();if(!Array.isArray(records))throw new Error("HISTORICAL_REPOSITORY_RESULT_INVALID");const seen=new Set();for(const record of records){const report=validateHistoricalObservation(record);if(!report.valid)throw new Error("HISTORICAL_REPOSITORY_STATE_INVALID");if(seen.has(record.observationId))throw new Error("DUPLICATE_HISTORICAL_OBSERVATION_ID");seen.add(record.observationId);}
    const from=query.from==null?null:Date.parse(query.from),to=query.to==null?null:Date.parse(query.to);const timeline=records.filter(x=>normalized(x.atlasProductId)===normalized(query.atlasProductId)).filter(x=>query.retailerId==null||x.retailerId===query.retailerId).filter(x=>from==null||Date.parse(x.observationTime)>=from).filter(x=>to==null||Date.parse(x.observationTime)<=to).sort((a,b)=>Date.parse(a.observationTime)-Date.parse(b.observationTime)||a.observationId.localeCompare(b.observationId)).map(point);const first=timeline[0]??null,latest=timeline.at(-1)??null;const retailerIds=[...new Set(timeline.map(x=>x.retailerId))].sort();const currencies=[...new Set(timeline.map(x=>x.currency))].sort();const perCurrency=currencies.map(currency=>currencySummary(currency,timeline.filter(x=>x.currency===currency)));const comparable=perCurrency.length===1?perCurrency[0]:null;const result={query:{atlasProductId:query.atlasProductId,retailerId:query.retailerId??null,from:query.from??null,to:query.to??null},observationCount:timeline.length,firstObservationTime:first?.observationTime??null,latestObservationTime:latest?.observationTime??null,latestObservationId:latest?.observationId??null,latestRetailerId:latest?.retailerId??null,retailerCount:retailerIds.length,retailerIds,currencies,latestCurrency:latest?.currency??null,latestBasePrice:latest?.basePrice??null,latestTotalPrice:latest?.totalPrice??null,lowestBasePrice:comparable?.lowestBasePrice??null,highestBasePrice:comparable?.highestBasePrice??null,lowestTotalPrice:comparable?.lowestTotalPrice??null,highestTotalPrice:comparable?.highestTotalPrice??null,changeFromFirst:comparable?.changeFromFirst??null,changeFromPrevious:comparable?.changeFromPrevious??null,trendState:timeline.length===0?HISTORICAL_TREND_STATES.NO_DATA:currencies.length>1?HISTORICAL_TREND_STATES.NON_COMPARABLE:comparable.trendState,trendDimension:"BASE_PRICE",priceChangeAvailable:Boolean(comparable?.priceChangeAvailable),chronologicalObservations:timeline,perCurrency};return freeze(result);
  }
}
export default HistoricalObservationIntelligence;
