import crypto from "node:crypto";

export const HISTORICAL_BOOTSTRAP_POLICY_VERSION="MERCURY-HISTORY-019-1.0";
const stable=value=>Array.isArray(value)?`[${value.map(stable).join(",")}]`:value&&typeof value==="object"?`{${Object.keys(value).sort().map(k=>`${JSON.stringify(k)}:${stable(value[k])}`).join(",")}}`:JSON.stringify(value);
const hash=value=>crypto.createHash("sha256").update(stable(value)).digest("hex");
const freeze=value=>{if(value&&typeof value==="object"&&!Object.isFrozen(value)){Object.freeze(value);for(const child of Object.values(value))freeze(child);}return value;};
const money=value=>Math.round((Number(value)+Number.EPSILON)*1e9)/1e9;
const category=p=>{const c=p?.extension?.data?.classification;if(c?.formFactor==="SO_DIMM")return"SODIMM";if(c?.memoryType==="DDR5"&&c?.formFactor==="DIMM")return"DDR5_DIMM";if(c?.memoryType==="DDR4"&&c?.formFactor==="DIMM")return"DDR4_DIMM";return null;};
const productId=p=>p?.identity?.atlasProductId;
const bindingOf=value=>({policyVersion:value.policyVersion,asOf:value.asOf,sourceId:value.sourceId,acquisitionPortfolioCycleId:value.acquisitionPortfolioCycleId,acquisitionPortfolioBindingDigest:value.acquisitionPortfolioBindingDigest,selected:value.selected,stopConditions:value.stopConditions,costEnvelope:value.costEnvelope,rightsStatus:value.rightsStatus});
export const historicalBootstrapBindingDigest=value=>hash(bindingOf(value));
export function validateHistoricalBootstrapPreparation(value){if(value?.schemaVersion!=="1.0"||value?.preparationType!=="ATLAS_HISTORICAL_BOOTSTRAP"||value.authorizationState!=="NOT_AUTHORIZED"||value.executionAuthorized!==false||value.providerSpendAuthorized!==false||value.networkOperation!=="NONE"||value.paidTaskCreated!==false||value.actualSpendUsd!==0||value.sourceId!=="DATAFORSEO_GOOGLE_SHOPPING"||!Array.isArray(value.selected)||value.selected.length!==3||new Set(value.selected.map(x=>x.atlasProductId)).size!==3||value.costEnvelope?.maximumPaidTasks!==9||value.costEnvelope?.maximumProviderSpendUsd!==.009||value.bindingDigest!==historicalBootstrapBindingDigest(value)||value.bootstrapPreparationId!==`mer_histbootstrap_${hash({bindingDigest:value.bindingDigest}).slice(0,24)}`)throw new Error("HISTORICAL_BOOTSTRAP_ARTIFACT_INVALID");return true;}

export function prepareHistoricalBootstrap({asOf,atlasProducts,acquisitionPortfolio,destinations,historicalObservations,evidenceRecords,rightsProfile}={}){
 if(typeof asOf!=="string"||!Number.isFinite(Date.parse(asOf))||![atlasProducts,acquisitionPortfolio?.eligibleProducts,destinations,historicalObservations,evidenceRecords].every(Array.isArray))throw new TypeError("HISTORICAL_BOOTSTRAP_PREPARE_INPUT_INVALID");
 const historicalRights=rightsProfile?.retention?.historical==="ALLOWED"&&rightsProfile?.retention?.durableAuditMetadata==="ALLOWED"&&rightsProfile?.derivation?.historicalAnalytics==="ALLOWED";
 if(acquisitionPortfolio.provider!=="DATAFORSEO"||acquisitionPortfolio.sourceId!=="DATAFORSEO_GOOGLE_SHOPPING"||acquisitionPortfolio.authorizationState!=="NOT_AUTHORIZED"||acquisitionPortfolio.providerSpendAuthorized!==false||!historicalRights)throw new Error("HISTORICAL_BOOTSTRAP_RIGHTS_OR_PORTFOLIO_INVALID");
 const ids=new Set(atlasProducts.map(productId));if(ids.size!==atlasProducts.length||ids.has(undefined))throw new Error("HISTORICAL_BOOTSTRAP_ATLAS_INVALID");
 const historyCounts=new Map(),evidenceBindings=new Map();for(const row of historicalObservations)historyCounts.set(row.atlasProductId,(historyCounts.get(row.atlasProductId)??0)+1);for(const row of evidenceRecords){const bound=[row?.candidate?.identity?.atlasProductId,...(row?.candidate?.identity?.candidateAtlasProductIds??[])].filter(Boolean);for(const id of new Set(bound))evidenceBindings.set(id,(evidenceBindings.get(id)??0)+1);}
 const superseded=new Set(destinations.map(x=>x.supersedesDestinationId).filter(Boolean)),effective=destinations.filter(x=>x.status==="ACTIVE"&&!superseded.has(x.destinationId));const destinationCounts=new Map();for(const row of effective)destinationCounts.set(row.atlasProductId,(destinationCounts.get(row.atlasProductId)??0)+1);
 const acquisition=new Map(acquisitionPortfolio.eligibleProducts.map(x=>[x.atlasProductId,x])),rows=atlasProducts.map(product=>{const id=productId(product),work=acquisition.get(id),historyCount=historyCounts.get(id)??0,destinationCount=destinationCounts.get(id)??0,blockers=[];if(product.governance?.lifecycleStatus!=="ACTIVE"||product.governance?.publicationStatus!=="READY")blockers.push("ATLAS_PRODUCT_NOT_ACTIVE_READY");if(historyCount)blockers.push("HISTORY_ALREADY_EXISTS");if(!destinationCount)blockers.push("EFFECTIVE_RETAILER_DESTINATION_MISSING");if(!work)blockers.push("ACQUISITION_PATH_UNAVAILABLE");if(work?.providerIdentityState==="REVIEW_REQUIRED")blockers.push("PROVIDER_IDENTITY_REVIEW_REQUIRED");return{atlasProductId:id,category:category(product),brand:product.identity.brand,manufacturerPartNumber:product.identity.manufacturerPartNumber,effectiveRetailerDestinationCount:destinationCount,retainedEvidenceCount:evidenceBindings.get(id)??0,historyCount,providerIdentityState:work?.providerIdentityState??"UNAVAILABLE",historicalLifecycleState:historyCount?"HISTORY_EXISTS":"INITIAL_BOOTSTRAP",cadenceState:historyCount?"EXISTING_E2O_GOVERNANCE":"NOT_APPLICABLE_BEFORE_FIRST_OBSERVATION",blockers,work};}).sort((a,b)=>a.atlasProductId.localeCompare(b.atlasProductId));
 const eligible=rows.filter(x=>x.blockers.length===0&&x.category),selected=["DDR5_DIMM","DDR4_DIMM","SODIMM"].map(kind=>eligible.find(x=>x.category===kind)).filter(Boolean).map(x=>({atlasProductId:x.atlasProductId,category:x.category,brand:x.brand,manufacturerPartNumber:x.manufacturerPartNumber,effectiveRetailerDestinationCount:x.effectiveRetailerDestinationCount,retainedEvidenceCount:x.retainedEvidenceCount,historyCount:x.historyCount,providerIdentityState:x.providerIdentityState,historicalLifecycleState:x.historicalLifecycleState,cadenceState:x.cadenceState,blockers:[],providerWorkPlan:x.work.plannedStagePath.map((operation,index)=>({operation,paid:true,required:index===0||operation==="SELLERS",conditional:operation==="PRODUCT_INFO"})),maximumPaidTasks:x.work.maximumRemainingPaidTasks,maximumSpendUsd:x.work.maximumRemainingSpendUsd,zeroCostRetrievalOperations:[]}));
 if(selected.length!==3)throw new Error("HISTORICAL_BOOTSTRAP_CATEGORY_COHORT_INCOMPLETE");
 const maximumPaidTasks=selected.reduce((n,x)=>n+x.maximumPaidTasks,0),maximumProviderSpendUsd=money(selected.reduce((n,x)=>n+x.maximumSpendUsd,0)),binding={policyVersion:HISTORICAL_BOOTSTRAP_POLICY_VERSION,asOf,sourceId:acquisitionPortfolio.sourceId,acquisitionPortfolioCycleId:acquisitionPortfolio.portfolioCycleId,acquisitionPortfolioBindingDigest:acquisitionPortfolio.bindingDigest,selected,stopConditions:["RIGHTS_FAILURE","BUDGET_AUTHORIZATION_FAILURE","PROVIDER_IDENTITY_AMBIGUITY","RETAILER_IDENTITY_AMBIGUITY","RETAINED_EVIDENCE_CONFLICT","HISTORICAL_OFFER_BUNDLE_NOT_COMPARABLE","HISTORICAL_OFFER_CONDITIONAL_NOT_COMPARABLE","HISTORICAL_OFFER_COMPARABILITY_UNKNOWN","UNSUPPORTED_CURRENCY","MALFORMED_PROVIDER_RESULT","PROVENANCE_BREAK","TASK_OR_PROVIDER_FAILURE","REPOSITORY_WRITE_CONFLICT"],costEnvelope:{perTaskCostCeilingUsd:acquisitionPortfolio.costEnvelope.perTaskCostCeilingUsd,maximumPaidTasks,maximumProviderSpendUsd,utcDaySpendCeilingUsd:acquisitionPortfolio.costEnvelope.utcDaySpendCeilingUsd},rightsStatus:"ALLOWED"};const bindingDigest=hash(binding);
 const result={schemaVersion:"1.0",preparationType:"ATLAS_HISTORICAL_BOOTSTRAP",bootstrapPreparationId:`mer_histbootstrap_${hash({bindingDigest}).slice(0,24)}`,preparedAt:asOf,...binding,bindingDigest,authorizationState:"NOT_AUTHORIZED",executionAuthorized:false,providerSpendAuthorized:false,networkOperation:"NONE",paidTaskCreated:false,actualSpendUsd:0,counts:{atlasProducts:rows.length,productsWithHistory:rows.filter(x=>x.historyCount).length,productsWithoutHistory:rows.filter(x=>!x.historyCount).length,productsWithRetainedEvidence:rows.filter(x=>x.retainedEvidenceCount).length,productsWithCanonicalProviderIdentity:rows.filter(x=>x.providerIdentityState==="REUSABLE").length,eligibleBootstrapProducts:eligible.length,blockedByIdentity:rows.filter(x=>x.blockers.includes("PROVIDER_IDENTITY_REVIEW_REQUIRED")).length,blockedByRights:0,blockedByMissingDestination:rows.filter(x=>x.blockers.includes("EFFECTIVE_RETAILER_DESTINATION_MISSING")).length,blockedByComparability:0},blocked:rows.filter(x=>x.blockers.length).map(x=>({atlasProductId:x.atlasProductId,reasons:x.blockers}))};validateHistoricalBootstrapPreparation(result);return freeze(result);
}
