import {HistoricalObservationIntelligence} from "../historical-admission/HistoricalObservationIntelligence.js";
import {assessHistoricalRefreshCycleStatus} from "../historical-refresh/HistoricalRefreshCycleStatusService.js";
import {evaluateHistoricalRefreshCadence} from "../historical-refresh/HistoricalRefreshCadencePolicy.js";

const freeze=value=>{if(value&&typeof value==="object"&&!Object.isFrozen(value)){Object.freeze(value);for(const child of Object.values(value))freeze(child);}return value;};const validDate=value=>typeof value==="string"&&Number.isFinite(Date.parse(value));
export class HistoricalObservationPortfolio{
 constructor({productRepository,historicalRepository,evidenceRepository,cadencePolicyRepository}={}){if(!productRepository?.getAll||!historicalRepository?.getAll||!evidenceRepository?.getAll||!cadencePolicyRepository?.getAllPolicies)throw new TypeError("HISTORICAL_OBSERVATION_PORTFOLIO_DEPENDENCIES_REQUIRED");if(!cadencePolicyRepository.resolveApplicablePolicy)cadencePolicyRepository={getAllPolicies:cadencePolicyRepository.getAllPolicies,resolveApplicablePolicy:async id=>{const matches=(await cadencePolicyRepository.getAllPolicies()).filter(x=>x.atlasProductIds?.includes(id));if(matches.length>1)throw new Error(`HISTORICAL_REFRESH_CADENCE_POLICY_AMBIGUOUS:${id}`);return matches[0]??null;}};Object.assign(this,{productRepository,historicalRepository,evidenceRepository,cadencePolicyRepository});}
 query(input={}){if(!validDate(input.asOf)||![input.refreshPlans??[],input.authorizations??[],input.executionRuns??[],input.refreshResults??[],input.promotionAssessments??[]].every(Array.isArray))throw new TypeError("HISTORICAL_OBSERVATION_PORTFOLIO_INPUT_INVALID");return this._query(input);}
 async _query({asOf,refreshPlans=[],authorizations=[],executionRuns=[],consumptionState={schemaVersion:"1.0",consumed:[]},refreshResults=[],promotionAssessments=[]}={}){
  if(!validDate(asOf)||![refreshPlans,authorizations,executionRuns,refreshResults,promotionAssessments].every(Array.isArray))throw new TypeError("HISTORICAL_OBSERVATION_PORTFOLIO_INPUT_INVALID");const [products,history,evidence,policies]=await Promise.all([this.productRepository.getAll(),this.historicalRepository.getAll(),this.evidenceRepository.getAll(),this.cadencePolicyRepository.getAllPolicies()]);if(!Array.isArray(products)||!Array.isArray(history)||!Array.isArray(evidence)||!Array.isArray(policies))throw new Error("HISTORICAL_OBSERVATION_PORTFOLIO_SOURCE_INVALID");const productIds=products.map(x=>x?.identity?.atlasProductId);if(productIds.some(x=>typeof x!=="string"||!x)||new Set(productIds).size!==productIds.length)throw new Error("HISTORICAL_OBSERVATION_PORTFOLIO_ATLAS_INVALID");const intelligence=new HistoricalObservationIntelligence({repository:{getAll:async()=>history}}),entries=[];
  for(const atlasProductId of [...productIds].sort()){const historical=await intelligence.query({atlasProductId}),cycle=assessHistoricalRefreshCycleStatus({atlasProductId,asOf,historicalObservations:history,evidenceRecords:evidence,refreshPlans,authorizations,executionRuns,consumptionState,refreshResults,promotionAssessments}),policy=await this.cadencePolicyRepository.resolveApplicablePolicy(atlasProductId),cadence=evaluateHistoricalRefreshCadence({atlasProductId,cycleStatus:cycle,policy,asOf}),humanReviewRequired=cycle.nextAction?.humanReviewRequired===true||cycle.stage==="REVIEW_REQUIRED"||cycle.stage==="BLOCKED",due=cadence.dueState==="DUE",governedPaidPath=historical.observationCount>0&&due&&cycle.nextAction?.potentialPaidOperation==="SELLERS";entries.push({atlasProductId,history:{observationCount:historical.observationCount,firstObservationTime:historical.firstObservationTime,latestObservationTime:historical.latestObservationTime,latestObservationId:historical.latestObservationId,retailerIds:[...historical.retailerIds],currencies:[...historical.currencies],latestCurrency:historical.latestCurrency,latestBasePrice:historical.latestBasePrice,latestTotalPrice:historical.latestTotalPrice,trendState:historical.trendState},cadence:{configured:policy!==null,policyId:cadence.policyId,enabled:policy?.enabled??false,minimumIntervalMs:policy?.minimumIntervalMs??null,automaticExecution:policy?.automaticExecution??false,dueState:cadence.dueState,due:cadence.due,nextEligibleRefreshTime:cadence.nextEligibleRefreshTime,reasons:[...cadence.reasons]},cycle:{stage:cycle.stage,status:cycle.status,nextAction:cycle.nextAction?.name??null,blockingReasons:[...(cycle.blockingReasons??[])]},acquisition:{nextPaidOperationPossible:governedPaidPath,potentialOperation:historical.observationCount>0?cycle.nextAction?.potentialPaidOperation??null:null,maximumPotentialSpendUsd:historical.observationCount>0?cycle.nextAction?.maximumFutureSpendUsd??null:null,explicitAuthorizationRequired:governedPaidPath,unattendedLiveEnabled:false,committedSpendUsd:0,actionExecuted:false},attention:{humanReviewRequired,reasons:[...new Set([...(cycle.blockingReasons??[]),...(humanReviewRequired?cadence.reasons:[])])]},semantics:{authoritative:false,adaptiveCadence:false,currentPrice:false,publicFreshness:false}});}
  const count=state=>entries.filter(x=>x.cadence.dueState===state).length,withHistory=entries.filter(x=>x.history.observationCount>0),dueEntries=entries.filter(x=>x.cadence.dueState==="DUE"&&x.acquisition.nextPaidOperationPossible);const summary={atlasProductCount:entries.length,productsWithHistory:withHistory.length,productsWithoutHistory:entries.length-withHistory.length,totalHistoricalObservations:entries.reduce((n,x)=>n+x.history.observationCount,0),productsWithCadenceConfigured:entries.filter(x=>x.cadence.configured).length,productsWithoutCadenceConfigured:entries.filter(x=>!x.cadence.configured).length,dueProductCount:count("DUE"),notDueProductCount:count("NOT_DUE"),blockedProductCount:count("BLOCKED"),policyNotConfiguredProductCount:count("POLICY_NOT_CONFIGURED"),disabledProductCount:count("DISABLED"),reviewRequiredProductCount:entries.filter(x=>x.attention.humanReviewRequired).length,configuredAutomaticExecutionCount:entries.filter(x=>x.cadence.automaticExecution).length,unattendedLiveEnabledCount:entries.filter(x=>x.acquisition.unattendedLiveEnabled).length,maximumPotentialNextCycleSpendUsd:dueEntries.reduce((sum,x)=>sum+Number(x.acquisition.maximumPotentialSpendUsd??0),0),committedSpendUsd:0};return freeze({schemaVersion:"1.0",readModelType:"HISTORICAL_OBSERVATION_PORTFOLIO",asOf,summary,products:entries,authoritative:false,actionExecuted:false,paidTaskCreated:false,actualSpendUsd:0});
 }
}
export default HistoricalObservationPortfolio;
