import crypto from "node:crypto";
import {createHistoricalBootstrapProviderResult} from "./FileHistoricalBootstrapProviderResultRepository.js";
import {projectHistoricalBootstrapCheckpoint} from "./HistoricalBootstrapCheckpoint.js";

const stable=v=>Array.isArray(v)?`[${v.map(stable).join(",")}]`:v&&typeof v==="object"?`{${Object.keys(v).sort().map(k=>`${JSON.stringify(k)}:${stable(v[k])}`).join(",")}}`:JSON.stringify(v),digest=v=>crypto.createHash("sha256").update(stable(v)).digest("hex");
const freeze=v=>Object.freeze(structuredClone(v));
const taskFor=(checkpoint,operation)=>[...checkpoint.events].reverse().find(x=>x.type==="TASK_CREATED"&&x.operation===operation);
async function exact(repository,reference,checkpoint,projection){const result=await repository.getCanonicalResultById(reference.canonicalResultId),task=taskFor(checkpoint,reference.operation);if(!result||result.resultDigest!==reference.resultDigest||result.operation!==reference.operation||result.providerTaskId!==reference.providerTaskId||result.paidActionIntentId!==reference.paidActionIntentId||result.sourceId!==checkpoint.binding.sourceId||result.checkpointId!==projection.checkpointId||result.atlasProductId!==projection.atlasProductId||result.productIndex!==projection.productIndex||task?.providerTaskId!==result.providerTaskId||task?.paidActionIntentId!==result.paidActionIntentId)throw new Error("RESULT_LINEAGE_CONFLICT");return result}
async function progression(repository,resultReference,status,value){const saved=await repository.recordProgression({resultReferenceId:resultReference.resultReferenceId,status,progression:value});return freeze({status,nextStageReference:{artifactId:saved.progressionId,digest:saved.progressionDigest}})}

export class ProductionHistoricalBootstrapResultBridge{
 constructor({resultRepository,retrievalOwners,now=()=>new Date().toISOString()}={}){if(!resultRepository?.record||!retrievalOwners)throw new TypeError("HISTORY_034_RESULT_BRIDGE_DEPENDENCIES_REQUIRED");Object.assign(this,{resultRepository,retrievalOwners,now})}
 async retrieve({checkpoint}={}){const projection=projectHistoricalBootstrapCheckpoint({checkpoint}),task=taskFor(checkpoint,projection.currentStage),owner=this.retrievalOwners[projection.currentStage];if(projection.cohortState!=="WAITING_FOR_RESULT"||!task||typeof owner?.retrieve!=="function")throw new Error("RESULT_LINEAGE_CONFLICT");let outcome;try{outcome=await owner.retrieve({providerTaskId:task.providerTaskId})}catch(error){if(/^DATAFORSEO_TASK_ERROR:40/.test(String(error?.message)))return freeze({status:"PENDING",providerCalls:1,paidTaskCreated:false,actualSpendUsd:0});throw error}if(["PENDING","PROVIDER_PENDING"].includes(outcome?.status)||Array.isArray(outcome?.result)&&outcome.result.length===0)return freeze({status:"PENDING",providerCalls:1,paidTaskCreated:false,actualSpendUsd:0});if(["FAILED","PROVIDER_FAILED"].includes(outcome?.status))return freeze({status:"FAILED",providerCalls:1,paidTaskCreated:false,actualSpendUsd:0});if(outcome?.id&&outcome.id!==task.providerTaskId)throw new Error("RESULT_LINEAGE_CONFLICT");const prior=await this.resultRepository.getByTaskIntent?.(task.providerTaskId,task.paidActionIntentId);if(prior){if(prior.operation!==projection.currentStage||prior.sourceId!==checkpoint.binding.sourceId||prior.checkpointId!==projection.checkpointId||prior.atlasProductId!==projection.atlasProductId||prior.productIndex!==projection.productIndex||prior.resultDigest!==digest(outcome))throw new Error("BOOTSTRAP_PROVIDER_RESULT_CONFLICT");return freeze({status:"AVAILABLE",resultReference:prior.resultReference.resultReferenceId,resultDigest:prior.resultDigest,canonicalResultId:prior.canonicalResultId,providerCalls:1,paidTaskCreated:false,actualSpendUsd:0})}const record=await this.resultRepository.record(createHistoricalBootstrapProviderResult({operation:projection.currentStage,providerTaskId:task.providerTaskId,paidActionIntentId:task.paidActionIntentId,checkpointId:projection.checkpointId,atlasProductId:projection.atlasProductId,productIndex:projection.productIndex,providerStatus:"AVAILABLE",operationResult:outcome,retrievedAt:this.now()}));return freeze({status:"AVAILABLE",resultReference:record.resultReference.resultReferenceId,resultDigest:record.resultDigest,canonicalResultId:record.canonicalResultId,providerCalls:1,paidTaskCreated:false,actualSpendUsd:0})}
}

export function createHistoricalBootstrapProductsResultAdapter({resultRepository,atlasProducts,progressionOwner}={}){if(!resultRepository?.getCanonicalResultById||!atlasProducts||typeof progressionOwner?.resolve!=="function")throw new TypeError("HISTORY_034_PRODUCTS_ADAPTER_DEPENDENCIES_REQUIRED");return Object.freeze({async process({checkpoint,projection,resultReference}){const result=await exact(resultRepository,resultReference,checkpoint,projection),atlasProduct=await (atlasProducts.getById?.(projection.atlasProductId)??atlasProducts.loadProduct?.(projection.atlasProductId));if(!atlasProduct)throw new Error("RESULT_LINEAGE_CONFLICT");const value=await progressionOwner.resolve({atlasProduct,providerTaskId:result.providerTaskId,providerResult:result.operationResult});return progression(resultRepository,resultReference,value.status,value)}})}
export function createHistoricalBootstrapProductInfoResultAdapter({resultRepository,progressionOwner}={}){if(!resultRepository?.getCanonicalResultById||typeof progressionOwner?.resolve!=="function")throw new TypeError("HISTORY_034_PRODUCT_INFO_ADAPTER_DEPENDENCIES_REQUIRED");return Object.freeze({async process({checkpoint,projection,resultReference}){const result=await exact(resultRepository,resultReference,checkpoint,projection),value=await progressionOwner.resolve({retrievalOutcome:result.operationResult});return progression(resultRepository,resultReference,value.status,value)}})}
export function createHistoricalBootstrapSellersResultAdapter({resultRepository,processingOwner,historicalOwner=null,admittedBy="operator:historical-bootstrap"}={}){if(!resultRepository?.getCanonicalResultById||!resultRepository?.findByTask||typeof processingOwner?.process!=="function")throw new TypeError("HISTORY_034_SELLERS_ADAPTER_DEPENDENCIES_REQUIRED");return Object.freeze({async process({checkpoint,projection,resultReference}){const sellers=await exact(resultRepository,resultReference,checkpoint,projection),productInfoTask=taskFor(checkpoint,"PRODUCT_INFO"),productInfo=productInfoTask?await resultRepository.findByTask(productInfoTask.providerTaskId):null;if(productInfoTask&&!productInfo||productInfo&&productInfo.atlasProductId!==projection.atlasProductId)throw new Error("RESULT_LINEAGE_CONFLICT");const processed=await processingOwner.process({sellersTaskId:sellers.providerTaskId,productInfoTaskId:productInfoTask?.providerTaskId??null,sellersResult:sellers.operationResult,productInfoResult:productInfo?.operationResult??null}),evidenceId=processed?.result?.integrations?.find(x=>x?.evidenceId)?.evidenceId??processed?.result?.evidenceId??null;if(!evidenceId)return progression(resultRepository,resultReference,processed?.result?.status??"RETENTION_FAILED",processed);if(!historicalOwner)return progression(resultRepository,resultReference,"RETENTION_COMPLETE",processed);const finalized=await historicalOwner.process({evidenceId,admittedBy});return progression(resultRepository,resultReference,finalized.status,{processed,finalized})}})}
