import crypto from "node:crypto";
import {mkdir,readFile,readdir,rename,writeFile} from "node:fs/promises";
import path from "node:path";
import {createAcquisitionBudgetPolicy} from "../planning/AcquisitionBudgetPolicy.js";
import {createAcquisitionPlan} from "../planning/AcquisitionPlan.js";
import {createManualLiveAuthorizationRequest} from "../authorization/ManualLiveAuthorizationRequest.js";
import {calculateGovernedSpendForUtcDay} from "../planning/GovernedDailySpend.js";
import {classifyDefaultAcquisitionRoute} from "../enrichment/DefaultAcquisitionRouting.js";
import {ACQUISITION_FAILURE_CLASSES,ACQUISITION_FAILURE_RETRYABILITY,ACQUISITION_FAILURE_STAGES,createAcquisitionFailureDiagnostic} from "../execution/AcquisitionFailureDiagnostic.js";

const stable=v=>Array.isArray(v)?`[${v.map(stable).join(",")}]`:v&&typeof v==="object"?`{${Object.keys(v).sort().map(k=>`${JSON.stringify(k)}:${stable(v[k])}`).join(",")}}`:JSON.stringify(v);
const hash=v=>crypto.createHash("sha256").update(stable(v)).digest("hex"),clone=v=>structuredClone(v),money=v=>Math.round((Number(v)+Number.EPSILON)*1e9)/1e9;
const freeze=v=>{if(v&&typeof v==="object"&&!Object.isFrozen(v)){Object.freeze(v);for(const x of Object.values(v))freeze(x);}return v;};
const validIso=v=>typeof v==="string"&&Number.isFinite(Date.parse(v));
const segment=(v,name)=>{if(typeof v!=="string"||!/^[A-Za-z0-9_-]+$/.test(v))throw new Error(`${name}_INVALID`);return v;};
export const CHECKPOINT_STAGE="PRODUCTS_DISCOVERY",CHECKPOINT_POLICY_VERSION="MERCURY-ACTIVATION-002C-1.0",CHECKPOINT_CONFIRMATION="SPEND-0.001";

export function createProductsDiscoveryCheckpoint({portfolio,asOf,maximumSpendUsd=.009}={}){
 if(!portfolio?.portfolioCycleId||!validIso(asOf)||maximumSpendUsd!==.009||portfolio.costEnvelope?.maximumProgramSpendUsd!==.029)throw new Error("ACQUISITION_CHECKPOINT_INPUT_INVALID");
 const products=portfolio.eligibleProducts.filter(x=>x.initialState==="READY_FOR_PRODUCTS").map(x=>({atlasProductId:x.atlasProductId,query:x.query,atlasProductDigest:x.atlasProductDigest}));
 const binding={policyVersion:CHECKPOINT_POLICY_VERSION,portfolioCycleId:portfolio.portfolioCycleId,portfolioBindingDigest:portfolio.bindingDigest,stage:CHECKPOINT_STAGE,maximumSpendUsd,programMaximumSpendUsd:portfolio.costEnvelope.maximumProgramSpendUsd,perTaskMaximumSpendUsd:portfolio.costEnvelope.perTaskCostCeilingUsd,utcDayMaximumSpendUsd:portfolio.costEnvelope.utcDaySpendCeilingUsd,sourceRightsDigest:portfolio.sourceRightsProfileDigest,products};
 return freeze({schemaVersion:"1.0",checkpointId:`mer_acqcheckpoint_${hash(binding).slice(0,24)}`,createdAt:asOf,...binding,providerSpendAuthorized:false,paidTaskAuthorized:false,actualSpendUsd:0});
}

export class FileAcquisitionCheckpointRepository{
 constructor({rootPath}={}){if(!rootPath)throw new TypeError("checkpoint root required");this.root=path.resolve(rootPath);}
 base(portfolioId,checkpointId){if(!/^mer_acqportfolio_[a-f0-9]{24}$/.test(portfolioId)||!/^mer_acqcheckpoint_[a-f0-9]{24}$/.test(checkpointId))throw new Error("CHECKPOINT_ID_INVALID");return path.join(this.root,portfolioId,"checkpoints",checkpointId);}
 async read(file){try{return JSON.parse(await readFile(file,"utf8"));}catch(e){if(e?.code==="ENOENT")return null;throw e;}}
 async immutable(file,value,conflict){const prior=await this.read(file);if(prior){if(stable(prior)!==stable(value))throw new Error(conflict);return freeze({status:"DUPLICATE",value:freeze(prior),path:file});}await mkdir(path.dirname(file),{recursive:true});const tmp=`${file}.${process.pid}.tmp`;await writeFile(tmp,`${JSON.stringify(value,null,2)}\n`);await rename(tmp,file);return freeze({status:"RECORDED",value:freeze(clone(value)),path:file});}
 persistCheckpoint(value){return this.immutable(path.join(this.base(value.portfolioCycleId,value.checkpointId),"checkpoint.json"),value,"ACQUISITION_CHECKPOINT_CONFLICT");}
 getCheckpoint(portfolioId,checkpointId){return this.read(path.join(this.base(portfolioId,checkpointId),"checkpoint.json"));}
  persistTask(value){return this.immutable(path.join(this.base(value.portfolioCycleId,value.checkpointId),"tasks",segment(value.atlasProductId,"ATLAS_PRODUCT_ID"),"prepare.json"),value,"CHECKPOINT_TASK_PREPARE_CONFLICT");}
  getTask(portfolioId,checkpointId,productId){return this.read(path.join(this.base(portfolioId,checkpointId),"tasks",segment(productId,"ATLAS_PRODUCT_ID"),"prepare.json"));}
  async getTasks(portfolioId,checkpointId){const root=path.join(this.base(portfolioId,checkpointId),"tasks");try{const ids=await readdir(root);return (await Promise.all(ids.map(id=>this.read(path.join(root,id,"prepare.json"))))).filter(Boolean);}catch(e){if(e?.code==="ENOENT")return[];throw e;}}
  persistReview(value){return this.immutable(path.join(this.base(value.portfolioCycleId,value.checkpointId),"products",segment(value.atlasProductId,"ATLAS_PRODUCT_ID"),segment(value.providerTaskId,"PROVIDER_TASK_ID"),"review.json"),value,"PRODUCTS_REVIEW_MATERIAL_CONFLICT");}
  getReview(portfolioId,checkpointId,productId,taskId){return this.read(path.join(this.base(portfolioId,checkpointId),"products",segment(productId,"ATLAS_PRODUCT_ID"),segment(taskId,"PROVIDER_TASK_ID"),"review.json"));}
  async getReviews(portfolioId,checkpointId){const root=path.join(this.base(portfolioId,checkpointId),"products"),out=[];try{for(const product of await readdir(root))for(const task of await readdir(path.join(root,product))){const value=await this.read(path.join(root,product,task,"review.json"));if(value)out.push(value);}return out;}catch(e){if(e?.code==="ENOENT")return[];throw e;}}
  async events(portfolioId,checkpointId){return (await this.read(path.join(this.base(portfolioId,checkpointId),"events.json")))?.events??[];}
  async portfolioEvents(portfolioId){const root=path.join(this.root,portfolioId,"checkpoints"),out=[];try{for(const checkpointId of await readdir(root))out.push(...await this.events(portfolioId,checkpointId));return out;}catch(e){if(e?.code==="ENOENT")return[];throw e;}}
 async appendEvent(value){const file=path.join(this.base(value.portfolioCycleId,value.checkpointId),"events.json"),state=await this.read(file)??{schemaVersion:"1.0",events:[]},prior=state.events.find(x=>x.eventId===value.eventId);if(prior){if(stable(prior)!==stable(value))throw new Error("CHECKPOINT_EVENT_REPLAY_CONFLICT");return freeze({status:"DUPLICATE",event:prior});}state.events.push(clone(value));await mkdir(path.dirname(file),{recursive:true});const tmp=`${file}.${process.pid}.tmp`;await writeFile(tmp,`${JSON.stringify(state,null,2)}\n`);await rename(tmp,file);return freeze({status:"APPENDED",event:clone(value)});}
}

export function checkpointSpendProjection({checkpoint,executionRuns=[],events=[],portfolioEvents=events,asOf}={}){
 if(!checkpoint||!validIso(asOf)||!Array.isArray(executionRuns)||!Array.isArray(events)||!Array.isArray(portfolioEvents))throw new Error("CHECKPOINT_SPEND_INPUT_INVALID");
 const monetaryEvent=x=>x.type==="TASK_FAILED"||x.type?.endsWith("_POSTED");
 const checkpointRunIds=new Set(events.filter(x=>x.checkpointId===checkpoint.checkpointId&&monetaryEvent(x)).map(x=>x.runId)),programRunIds=new Set(portfolioEvents.filter(x=>x.portfolioCycleId===checkpoint.portfolioCycleId&&monetaryEvent(x)).map(x=>x.runId));let checkpointSpend=0,portfolioSpend=0;for(const run of executionRuns){if(checkpointRunIds.has(run.runId)||programRunIds.has(run.runId)){if(!["COMPLETED","FAILED","PARTIAL"].includes(run.status)||!Number.isFinite(run.actualSpendUsd))throw new Error("CHECKPOINT_EXECUTION_LEDGER_INVALID");if(checkpointRunIds.has(run.runId))checkpointSpend=money(checkpointSpend+run.actualSpendUsd);if(programRunIds.has(run.runId))portfolioSpend=money(portfolioSpend+run.actualSpendUsd);}}
 const currentDay=calculateGovernedSpendForUtcDay(executionRuns,asOf),task=checkpoint.perTaskMaximumSpendUsd;
 const remaining={checkpoint:money(checkpoint.maximumSpendUsd-checkpointSpend),program:money(checkpoint.programMaximumSpendUsd-portfolioSpend),utcDay:money(checkpoint.utcDayMaximumSpendUsd-currentDay)};
 return freeze({checkpointSpendUsd:checkpointSpend,programSpendUsd:portfolioSpend,currentUtcDaySpendUsd:currentDay,remaining,maximumExecutableTasks:Math.max(0,Math.floor(Math.min(...Object.values(remaining))/task+1e-9))});
}

export function projectProductsCheckpoint({checkpoint,tasks=[],events=[],reviews=[],providerSelections=[]}={}){
 const byProduct=new Map(checkpoint.products.map(x=>[x.atlasProductId,{atlasProductId:x.atlasProductId,state:"READY_FOR_PRODUCTS",providerTaskId:null}]));
 for(const task of tasks){const p=byProduct.get(task.atlasProductId);if(!p||task.checkpointId!==checkpoint.checkpointId)throw new Error("CHECKPOINT_TASK_BINDING_INVALID");p.state="PRODUCTS_PREPARED";}
 for(const event of events){const p=byProduct.get(event.atlasProductId);if(!p||event.checkpointId!==checkpoint.checkpointId)throw new Error("CHECKPOINT_EVENT_BINDING_INVALID");if(event.type==="TASK_AUTHORIZED")p.state="PRODUCTS_AUTHORIZED";if(event.type==="PRODUCTS_POSTED"){p.state="PRODUCTS_PENDING";p.providerTaskId=event.providerTaskId;}if(event.type==="RESULT_PENDING")p.state="PRODUCTS_PENDING";if(event.type==="FAILED"||event.type==="TASK_FAILED"){p.state="FAILED";p.failure=event.failure??null;p.executionRunId=event.runId??null;}}
 for(const review of reviews){const p=byProduct.get(review.atlasProductId);if(!p||review.checkpointId!==checkpoint.checkpointId)throw new Error("CHECKPOINT_REVIEW_BINDING_INVALID");const direct=review.identityState==="EXACT_OR_GOVERNED_MATCH"&&classifyDefaultAcquisitionRoute({resolution:review.resultIdentity,directSellersLineageCertified:true}).executableRoute==="READY_FOR_SELLERS";p.state=review.identityState==="EXACT_OR_GOVERNED_MATCH"?(direct?"READY_FOR_SELLERS":"READY_FOR_PRODUCT_INFO"):review.identityState==="AMBIGUOUS_REVIEW_REQUIRED"||review.identityState==="CONTRADICTED"?"PRODUCTS_REVIEW_REQUIRED":review.identityState==="NO_RESULT"?"NO_RESULT":review.identityState==="PROVIDER_PENDING"?"PRODUCTS_PENDING":"FAILED";}
 for(const selection of providerSelections){const p=byProduct.get(selection.atlasProductId),review=reviews.find(value=>value.reviewId===selection.sourceProductsReviewId);if(!p||!review||selection.sourceProductsTaskId!==review.providerTaskId||selection.decision!=="SELECTED_PROVIDER_IDENTITY_FOR_DOWNSTREAM_LINEAGE")throw new Error("CHECKPOINT_PROVIDER_SELECTION_BINDING_INVALID");p.state="READY_FOR_PRODUCT_INFO";p.providerSelectionDecisionId=selection.selectionDecisionId;p.selectedProviderIdentity=clone(selection.selectedProviderIdentity);}
 const products=[...byProduct.values()],terminal=products.filter(x=>["READY_FOR_SELLERS","READY_FOR_PRODUCT_INFO","PRODUCTS_REVIEW_REQUIRED","NO_RESULT","FAILED"].includes(x.state)).length;
 return freeze({status:terminal===products.length?"CHECKPOINT_COMPLETE":products.some(x=>x.state!=="READY_FOR_PRODUCTS")?"IN_PROGRESS":"NOT_STARTED",complete:terminal===products.length,counts:Object.fromEntries([...new Set(products.map(x=>x.state))].map(s=>[s,products.filter(x=>x.state===s).length])),products,nextProduct:products.find(x=>x.state==="READY_FOR_PRODUCTS")??null});
}

export class ProductsCheckpointPrepareService{
 constructor({portfolio,checkpoint,repository,executionRepository}={}){if(!portfolio||!checkpoint||!repository?.persistTask||!executionRepository?.getAll)throw new Error("CHECKPOINT_PREPARE_OWNER_REQUIRED");this.portfolio=portfolio;this.checkpoint=checkpoint;this.repo=repository;this.executions=executionRepository;}
  async prepareNext({asOf,tasks=[],events=[],portfolioEvents=events,reviews=[]}={}){const projection=projectProductsCheckpoint({checkpoint:this.checkpoint,tasks,events,reviews}),next=projection.nextProduct;if(!next)return freeze({status:"NO_PRODUCTS_READY",projection});const spend=checkpointSpendProjection({checkpoint:this.checkpoint,executionRuns:await this.executions.getAll(),events,portfolioEvents,asOf});if(spend.maximumExecutableTasks<1)throw new Error("CHECKPOINT_BUDGET_EXHAUSTED");const product=this.portfolio.eligibleProducts.find(x=>x.atlasProductId===next.atlasProductId);const candidate={candidateId:`${product.atlasProductId}:products`,priority:"NORMAL",estimatedCostUsd:.001,execution:{kind:"PRODUCTS",provider:"DATAFORSEO",source:"DATAFORSEO_GOOGLE_SHOPPING",keyword:product.query,locationName:this.portfolio.locationName,languageName:this.portfolio.languageName}};const policy=createAcquisitionBudgetPolicy({enabled:true,maxPaidTasksPerRun:1,maxSpendPerRunUsd:.001,maxSpendPerDayUsd:.01,automaticPaidRetries:0}),plan=createAcquisitionPlan({candidates:[candidate],policy,spentTodayUsd:spend.currentUtcDaySpendUsd,plannedAt:asOf}),authorization=createManualLiveAuthorizationRequest({plan,createdAt:asOf});const binding={schemaVersion:"1.0",portfolioCycleId:this.portfolio.portfolioCycleId,portfolioBindingDigest:this.portfolio.bindingDigest,checkpointId:this.checkpoint.checkpointId,checkpointStage:this.checkpoint.stage,checkpointMaximumSpendUsd:this.checkpoint.maximumSpendUsd,programMaximumSpendUsd:this.checkpoint.programMaximumSpendUsd,sourceRightsDigest:this.checkpoint.sourceRightsDigest,atlasProductId:product.atlasProductId,atlasProductDigest:product.atlasProductDigest,query:product.query,preparedAt:asOf,plan,authorization,providerSpendAuthorized:false,confirmationRequired:CHECKPOINT_CONFIRMATION,bindingDigest:null};binding.bindingDigest=hash({...binding,bindingDigest:undefined});const result=await this.repo.persistTask(freeze(binding));return freeze({...result,spend});}
}

export function assertCheckpointTaskExecutionEligible({portfolio,checkpoint,task,executionRuns,events,portfolioEvents=events,asOf}={}){if(task?.portfolioCycleId!==portfolio?.portfolioCycleId||task.portfolioBindingDigest!==portfolio.bindingDigest)throw new Error("CHECKPOINT_TASK_PORTFOLIO_INVALID");if(task.checkpointId!==checkpoint?.checkpointId||task.checkpointStage!==CHECKPOINT_STAGE)throw new Error("CHECKPOINT_TASK_CHECKPOINT_INVALID");const product=checkpoint.products.find(x=>x.atlasProductId===task.atlasProductId);if(!product||product.query!==task.query||product.atlasProductDigest!==task.atlasProductDigest)throw new Error("CHECKPOINT_TASK_PRODUCT_INVALID");if(task.sourceRightsDigest!==portfolio.sourceRightsProfileDigest)throw new Error("CHECKPOINT_TASK_RIGHTS_INVALID");const spend=checkpointSpendProjection({checkpoint,executionRuns,events,portfolioEvents,asOf});if(spend.maximumExecutableTasks<1)throw new Error("CHECKPOINT_TASK_BUDGET_EXCEEDED");return freeze({eligible:true,spend});}

export class CheckpointBoundProductsExecutor{
 constructor({singleUseExecutor,executionRepository,checkpointRepository,now=()=>new Date().toISOString()}={}){if(!singleUseExecutor?.execute||!executionRepository?.getAll||!checkpointRepository?.appendEvent)throw new Error("CHECKPOINT_EXECUTION_OWNER_REQUIRED");this.executor=singleUseExecutor;this.executions=executionRepository;this.repo=checkpointRepository;this.now=now;}
 async execute({portfolio,checkpoint,task,authorization,confirmation}={}){const asOf=this.now(),events=await this.repo.events(portfolio.portfolioCycleId,checkpoint.checkpointId),portfolioEvents=await this.repo.portfolioEvents(portfolio.portfolioCycleId);if(confirmation!==CHECKPOINT_CONFIRMATION)throw new Error("CHECKPOINT_EXPLICIT_CONFIRMATION_REQUIRED");if(authorization?.authorizationId!==task.authorization?.requestId||authorization?.planId!==task.plan?.planId)throw new Error("CHECKPOINT_TASK_AUTHORIZATION_INVALID");const eligibility=assertCheckpointTaskExecutionEligible({portfolio,checkpoint,task,executionRuns:await this.executions.getAll(),events,portfolioEvents,asOf});if(eligibility.spend.maximumExecutableTasks<1)throw new Error("CHECKPOINT_TASK_BUDGET_EXCEEDED");const eventBase={portfolioCycleId:portfolio.portfolioCycleId,checkpointId:checkpoint.checkpointId,atlasProductId:task.atlasProductId,stage:CHECKPOINT_STAGE,recordedAt:asOf};await this.repo.appendEvent({...eventBase,eventId:`mer_acqevent_${hash({...eventBase,type:"TASK_AUTHORIZED",authorizationId:authorization.authorizationId}).slice(0,24)}`,type:"TASK_AUTHORIZED",operation:"PRODUCTS",authorizationId:authorization.authorizationId});const result=await this.executor.execute({plan:task.plan,authorization});if(result.status!=="COMPLETED"){const run=result.execution?.run;if(run?.status==="FAILED")await this.repo.appendEvent(createCheckpointTaskFailureEvent({portfolio,checkpoint,task,authorizationId:authorization.authorizationId,run}));return freeze({...result,checkpointBound:true,checkpointId:checkpoint.checkpointId});}const run=result.execution?.run;if(!run?.runId||run.actualSpendUsd>checkpoint.perTaskMaximumSpendUsd)throw new Error("CHECKPOINT_EXECUTION_RESULT_INVALID");const providerTaskId=run.tasks?.[0]?.providerTaskId;if(!providerTaskId)throw new Error("CHECKPOINT_PROVIDER_TASK_ID_MISSING");await this.repo.appendEvent({...eventBase,eventId:`mer_acqevent_${hash({...eventBase,type:"PRODUCTS_POSTED",runId:run.runId,providerTaskId}).slice(0,24)}`,type:"PRODUCTS_POSTED",operation:"PRODUCTS",authorizationId:authorization.authorizationId,runId:run.runId,providerTaskId,actualSpendUsd:run.actualSpendUsd});return freeze({...result,checkpointBound:true,checkpointId:checkpoint.checkpointId});}
}

export function createCheckpointTaskFailureEvent({portfolio,checkpoint,task,authorizationId,run}={}){
 const failed=run?.tasks?.filter(x=>x.outcome==="FAILED")??[];
 if(portfolio?.portfolioCycleId!==task?.portfolioCycleId||checkpoint?.checkpointId!==task?.checkpointId||run?.planId!==task?.plan?.planId||run?.status!=="FAILED"||failed.length!==1||!validIso(run.finishedAt)||!Number.isFinite(run.actualSpendUsd)||run.actualSpendUsd<0||run.actualSpendUsd>checkpoint.perTaskMaximumSpendUsd)throw new Error("CHECKPOINT_FAILED_EXECUTION_BINDING_INVALID");
 const item=failed[0];if(item.candidateId!==`${task.atlasProductId}:products`||authorizationId!==task.authorization?.requestId||!Number.isFinite(item.actualCostUsd)||money(item.actualCostUsd)!==money(run.actualSpendUsd))throw new Error("CHECKPOINT_FAILED_TASK_BINDING_INVALID");
 const source=item.failure??{};
 const failure=createAcquisitionFailureDiagnostic({error:{safeErrorCode:source.safeErrorCode??item.errorCode??"UNAVAILABLE",safeErrorMessage:source.safeErrorMessage??item.errorCode??"Failure detail unavailable.",failureStage:source.failureStage??ACQUISITION_FAILURE_STAGES.DURING_PROVIDER_REQUEST,failureClass:source.failureClass??ACQUISITION_FAILURE_CLASSES.UNKNOWN,retryability:source.retryability??ACQUISITION_FAILURE_RETRYABILITY.REVIEW_REQUIRED},provider:source.provider??"DATAFORSEO",operation:source.operation??"PRODUCTS",occurredAt:source.occurredAt??run.finishedAt,executionRunId:run.runId,authorizationId,candidateId:item.candidateId,providerTaskId:item.providerTaskId??null,actualSpendUsd:item.actualCostUsd});
 const material={portfolioCycleId:portfolio.portfolioCycleId,checkpointId:checkpoint.checkpointId,atlasProductId:task.atlasProductId,stage:CHECKPOINT_STAGE,type:"TASK_FAILED",operation:"PRODUCTS",authorizationId,runId:run.runId,providerTaskId:item.providerTaskId??null,actualSpendUsd:run.actualSpendUsd,recordedAt:run.finishedAt,failure};
 return freeze({...material,eventId:`mer_acqevent_${hash(material).slice(0,24)}`});
}

export class CheckpointFailedExecutionReconciliationService{
 constructor({checkpointRepository,executionRepository}={}){if(!checkpointRepository?.appendEvent||!checkpointRepository?.events||!executionRepository?.findByPlanId)throw new Error("CHECKPOINT_FAILURE_RECONCILIATION_OWNER_REQUIRED");this.repo=checkpointRepository;this.executions=executionRepository;}
 async reconcile({portfolio,checkpoint,task,authorizationId}={}){const run=await this.executions.findByPlanId(task?.plan?.planId);if(!run)throw new Error("CHECKPOINT_FAILED_EXECUTION_NOT_FOUND");const event=createCheckpointTaskFailureEvent({portfolio,checkpoint,task,authorizationId,run}),events=await this.repo.events(portfolio.portfolioCycleId,checkpoint.checkpointId),prior=events.find(value=>value.type==="TASK_FAILED"&&value.atlasProductId===task.atlasProductId&&value.runId===run.runId);if(prior){if(stable(prior)!==stable(event))throw new Error("CHECKPOINT_FAILURE_RECONCILIATION_CONFLICT");return freeze({status:"DUPLICATE",event:prior});}const stored=await this.repo.appendEvent(event);return freeze({...stored,event});}
}

export function createDurableProductsReview({task,result,assessment,retrievedAt}={}){if(!task?.checkpointId||!result?.id||result.id!==assessment?.providerTaskId||!validIso(retrievedAt))throw new Error("PRODUCTS_REVIEW_INPUT_INVALID");const state=assessment.identityState;if(!["EXACT_OR_GOVERNED_MATCH","AMBIGUOUS_REVIEW_REQUIRED","CONTRADICTED","NO_RESULT","PROVIDER_PENDING","PROVIDER_FAILURE","MALFORMED_RESULT","TASK_BINDING_FAILURE"].includes(state))throw new Error("PRODUCTS_REVIEW_STATE_INVALID");const material={portfolioCycleId:task.portfolioCycleId,checkpointId:task.checkpointId,atlasProductId:task.atlasProductId,query:task.query,providerTaskId:result.id,retrievedAt,sourceRightsDigest:task.sourceRightsDigest,resultIdentity:assessment.resultIdentity??null,identityState:state,reasons:assessment.reasons??[]};return freeze({schemaVersion:"1.0",reviewId:`mer_productsreview_${hash(material).slice(0,24)}`,...material,materialDigest:hash({result,assessment}),productInfoEligible:state==="EXACT_OR_GOVERNED_MATCH",paidTaskCreated:false,actualSpendUsd:0});}

export class ProductsCheckpointReviewService{
 constructor({repository,now=()=>new Date().toISOString()}={}){if(!repository?.persistReview||!repository?.appendEvent)throw new Error("PRODUCTS_REVIEW_OWNER_REQUIRED");this.repo=repository;this.now=now;}
 async record({task,result,assessment}={}){const prior=await this.repo.getReview(task.portfolioCycleId,task.checkpointId,task.atlasProductId,result?.id),materialDigest=hash({result,assessment});if(prior){if(prior.materialDigest!==materialDigest)throw new Error("PRODUCTS_REVIEW_MATERIAL_CONFLICT");return freeze({status:"DUPLICATE",value:prior,review:prior});}const review=createDurableProductsReview({task,result,assessment,retrievedAt:this.now()}),stored=await this.repo.persistReview(review),eventBase={portfolioCycleId:task.portfolioCycleId,checkpointId:task.checkpointId,atlasProductId:task.atlasProductId,stage:CHECKPOINT_STAGE,providerTaskId:result.id,recordedAt:review.retrievedAt},type=review.identityState==="PROVIDER_PENDING"?"RESULT_PENDING":review.identityState==="NO_RESULT"?"NO_RESULT":review.identityState==="EXACT_OR_GOVERNED_MATCH"?"IDENTITY_MATCHED":review.identityState==="AMBIGUOUS_REVIEW_REQUIRED"||review.identityState==="CONTRADICTED"?"IDENTITY_REVIEW_REQUIRED":"FAILED";await this.repo.appendEvent({...eventBase,type,eventId:`mer_acqevent_${hash({...eventBase,type,reviewId:review.reviewId}).slice(0,24)}`,reviewId:review.reviewId});return freeze({...stored,review});}
}
