import { AMAZON_ACCEPTANCE_ACTION_CONFIRMATIONS, createAmazonAcceptanceActionAuthorization, validateAmazonAcceptanceActionAuthorization, amazonAcceptanceAuthorizationRequest, processAmazonAcceptanceProducts } from "./AmazonAcceptanceExecution.js";
import { amazonAcceptanceDigest, validateAmazonHistoricalAcceptance } from "./AmazonHistoricalAcceptancePreparation.js";
const freeze=v=>{if(v&&typeof v==="object"&&!Object.isFrozen(v)){Object.freeze(v);for(const x of Object.values(v))freeze(x);}return v;};
export class AmazonAcceptanceExecutionService{
 constructor({artifactRepository,actionRepository,productRepository,rightsRegistry,spendResolver,taskOwners,retrievalServices,resultRepository,taskLedger,sellersProcessor=null,now=()=>new Date().toISOString()}={}){if(!artifactRepository?.getById||!actionRepository?.recordAuthorization||!productRepository?.getById||!rightsRegistry?.require||typeof spendResolver!=="function"||!resultRepository?.findByTask||!taskLedger?.getAll)throw new Error("AMAZON_ACCEPTANCE_EXECUTION_DEPENDENCIES_REQUIRED");Object.assign(this,{artifactRepository,actionRepository,productRepository,rightsRegistry,spendResolver,taskOwners,retrievalServices,resultRepository,taskLedger,sellersProcessor,now});}
 async artifact(id){const value=await this.artifactRepository.getById(id);if(!value)throw new Error("AMAZON_ACCEPTANCE_ARTIFACT_NOT_FOUND");validateAmazonHistoricalAcceptance(value);const current=this.rightsRegistry.require("DATAFORSEO_AMAZON");if(amazonAcceptanceDigest(current)!==value.sourceRightsProfileDigest)throw new Error("AMAZON_ACCEPTANCE_RIGHTS_CHANGED");return value;}
 async authorize({artifactId,operation,operator,reason,expiresAt,confirmation}){const expected=operation==="AMAZON_PRODUCTS"?AMAZON_ACCEPTANCE_ACTION_CONFIRMATIONS.AUTHORIZE_PRODUCTS:AMAZON_ACCEPTANCE_ACTION_CONFIRMATIONS.AUTHORIZE_SELLERS;if(confirmation!==expected)throw new Error("AMAZON_ACCEPTANCE_AUTHORIZE_CONFIRMATION_REQUIRED");const artifact=await this.artifact(artifactId),product=await this.productRepository.getById(artifact.atlasProductId),outcome=operation==="AMAZON_SELLERS"?await this.actionRepository.getOutcomeForArtifact(artifactId):null,authorization=createAmazonAcceptanceActionAuthorization({artifact,operation,atlasProduct:product,productsOutcome:outcome,operator,reason,authorizedAt:this.now(),expiresAt,currentUtcDaySpendUsd:await this.spendResolver(this.now())});return this.actionRepository.recordAuthorization(authorization);}
 async execute({artifactId,authorizationId,operation,confirmation}){const expected=operation==="AMAZON_PRODUCTS"?AMAZON_ACCEPTANCE_ACTION_CONFIRMATIONS.EXECUTE_PRODUCTS:AMAZON_ACCEPTANCE_ACTION_CONFIRMATIONS.EXECUTE_SELLERS;if(confirmation!==expected)throw new Error("AMAZON_ACCEPTANCE_EXECUTE_CONFIRMATION_REQUIRED");const artifact=await this.artifact(artifactId),authorization=await this.actionRepository.getAuthorization(authorizationId);validateAmazonAcceptanceActionAuthorization(authorization,artifact);if(authorization.operation!==operation||Date.parse(this.now())>=Date.parse(authorization.expiresAt))throw new Error("AMAZON_ACCEPTANCE_EXECUTION_NOT_AUTHORIZED");const current=await this.spendResolver(this.now());if(current!==authorization.plan.spentTodayUsd||current+.0015>.01)throw new Error("AMAZON_ACCEPTANCE_SPEND_RACE");return this.taskOwners[operation].execute({request:amazonAcceptanceAuthorizationRequest(authorization),authorizedAt:authorization.authorizedAt});}
 async task(artifactId,operation){const rows=(await this.taskLedger.getAll()).filter(x=>x.checkpointId===artifactId&&x.kind===operation);if(rows.length!==1)throw new Error("AMAZON_ACCEPTANCE_TASK_LINEAGE_INVALID");return rows[0];}
 async retrieve({artifactId,operation}){await this.artifact(artifactId);const task=await this.task(artifactId,operation);return this.retrievalServices[operation].retrieve({providerTaskId:task.taskId});}
 async processProducts({artifactId,authorizationId}){const artifact=await this.artifact(artifactId),authorization=await this.actionRepository.getAuthorization(authorizationId),task=await this.task(artifactId,"AMAZON_PRODUCTS"),result=await this.resultRepository.findByTask(task.taskId),product=await this.productRepository.getById(artifact.atlasProductId);if(!result)throw new Error("AMAZON_ACCEPTANCE_PRODUCTS_RESULT_NOT_AVAILABLE");const outcome=processAmazonAcceptanceProducts({artifact,authorization,canonicalResult:result,atlasProduct:product,corroboratingDestinationAsins:artifact.corroboratingDestinationAsins});await this.actionRepository.recordOutcome(outcome);return outcome;}
 async processSellers({artifactId,authorizationId}){if(!this.sellersProcessor?.process)throw new Error("AMAZON_ACCEPTANCE_SELLERS_PROCESSOR_REQUIRED");const artifact=await this.artifact(artifactId),authorization=await this.actionRepository.getAuthorization(authorizationId),task=await this.task(artifactId,"AMAZON_SELLERS"),result=await this.resultRepository.findByTask(task.taskId);validateAmazonAcceptanceActionAuthorization(authorization,artifact);if(!result)throw new Error("AMAZON_ACCEPTANCE_SELLERS_RESULT_NOT_AVAILABLE");return freeze(await this.sellersProcessor.process({artifact,authorization,canonicalResult:result}));}
}
