import {validateAmazonPilot} from "./AmazonPilotPreparation.js";
import {DATAFORSEO_DEFAULT_UTC_DAY_SPEND_CEILING_USD} from "../acquisition/planning/AcquisitionBudgetPolicy.js";

const freeze=v=>{if(v&&typeof v==="object"&&!Object.isFrozen(v)){Object.freeze(v);for(const child of Object.values(v))freeze(child);}return v;};
const sourceTask=e=>e?.candidate?.marketEvidence?.provenance?.sourceTaskId;

export class AmazonPilotProjectionService{
  constructor({actionRepository,taskLedger,resultRepository,evidenceRepository,historicalRepository,spendResolver,dailySpendCeilingUsd=DATAFORSEO_DEFAULT_UTC_DAY_SPEND_CEILING_USD}={}){if(!actionRepository?.getAuthorizationsForAction||!actionRepository?.getEffectiveOutcomeForArtifact||!taskLedger?.getAll||!resultRepository?.findByTask||!evidenceRepository?.getAll||!historicalRepository?.getAll||typeof spendResolver!=="function"||!Number.isFinite(dailySpendCeilingUsd)||dailySpendCeilingUsd<=0)throw new TypeError("AMAZON_PILOT_PROJECTION_DEPENDENCY_INVALID");Object.assign(this,{actionRepository,taskLedger,resultRepository,evidenceRepository,historicalRepository,spendResolver,dailySpendCeilingUsd});}
  async project({artifact,evaluationTime}={}){validateAmazonPilot(artifact);if(typeof evaluationTime!=="string"||!Number.isFinite(Date.parse(evaluationTime)))throw new TypeError("AMAZON_PILOT_PROJECTION_TIME_INVALID");const [tasks,evidence,history,utcDaySpendUsd]=await Promise.all([this.taskLedger.getAll(),this.evidenceRepository.getAll(),this.historicalRepository.getAll(),this.spendResolver(evaluationTime)]),childIds=new Set(artifact.perProductAcceptanceArtifacts.map(x=>x.acceptanceArtifactId)),pilotTasks=tasks.filter(x=>childIds.has(x.checkpointId));
    const duplicate=pilotTasks.find((x,i)=>pilotTasks.some((y,j)=>j!==i&&y.checkpointId===x.checkpointId&&y.kind===x.kind));if(duplicate)throw new Error("AMAZON_PILOT_PROJECTION_TASK_CONFLICT");
    const products=[];for(const child of artifact.perProductAcceptanceArtifacts)products.push(await this._product({child,tasks:pilotTasks,evidence,history}));const counts={AMAZON_PRODUCTS:pilotTasks.filter(x=>x.kind==="AMAZON_PRODUCTS").length,AMAZON_SELLERS:pilotTasks.filter(x=>x.kind==="AMAZON_SELLERS").length,AMAZON_ASIN:pilotTasks.filter(x=>x.kind==="AMAZON_ASIN").length},pilotSpendUsd=Number(pilotTasks.reduce((n,x)=>n+(Number(x.costUsd)||0),0).toFixed(4)),terminal=new Set(["COMPLETED_RETAINED_ONLY","COMPLETED_ADMITTED","PRODUCT_STOPPED"]),status=products.every(x=>terminal.has(x.state))?"PILOT_COMPLETE":"PILOT_IN_PROGRESS",remaining=Math.max(0,Number((this.dailySpendCeilingUsd-utcDaySpendUsd).toFixed(4))),next=remaining<artifact.costEnvelope.perTaskCostCeilingUsd?"WAIT_FOR_SPEND_CAPACITY":products.find(x=>x.state==="NOT_STARTED")?`AUTHORIZE_PRODUCTS:${products.find(x=>x.state==="NOT_STARTED").atlasProductId}`:"OPERATOR_REVIEW";return freeze({policyVersion:"MERCURY-HISTORY-057-1.0",pilotPreparationId:artifact.pilotPreparationId,evaluationTime,status,products,paidTasksUsed:pilotTasks.length,taskCounts:counts,pilotSpendUsd,configuredUtcDaySpendCeilingUsd:this.dailySpendCeilingUsd,utcDaySpendUsd,remainingUtcDayCapacityUsd:remaining,nextOperatorAction:next,writesPerformed:0});}
  async _product({child,tasks,evidence,history}){const id=child.acceptanceArtifactId,pTask=tasks.find(x=>x.checkpointId===id&&x.kind==="AMAZON_PRODUCTS"),sTask=tasks.find(x=>x.checkpointId===id&&x.kind==="AMAZON_SELLERS"),[pAuth,sAuth,effective,pResult,sResult]=await Promise.all([this.actionRepository.getAuthorizationsForAction(id,"AMAZON_PRODUCTS"),this.actionRepository.getAuthorizationsForAction(id,"AMAZON_SELLERS"),this.actionRepository.getEffectiveOutcomeForArtifact(id),pTask?this.resultRepository.findByTask(pTask.taskId):null,sTask?this.resultRepository.findByTask(sTask.taskId):null]);const sellerEvidence=sTask?evidence.filter(x=>sourceTask(x)===sTask.taskId):[],evidenceIds=new Set(sellerEvidence.map(x=>x.evidenceId)),admitted=history.filter(x=>evidenceIds.has(x?.provenance?.retainedEvidenceId));let state="NOT_STARTED",blocker=null;if(sellerEvidence.length)state=admitted.length?"COMPLETED_ADMITTED":"COMPLETED_RETAINED_ONLY";else if(sResult)state="SELLERS_RESULT_AVAILABLE";else if(sTask)state="SELLERS_RESULT_PENDING";else if(sAuth.length)state="SELLERS_AUTHORIZED";else if(effective?.state==="STRONG_UNIQUE_ASIN")state="SELLERS_REVIEW_REQUIRED";else if(effective){state="PRODUCTS_IDENTITY_BLOCKED";blocker=effective.state;}else if(pResult)state="PRODUCTS_RESULT_AVAILABLE";else if(pTask)state="PRODUCTS_RESULT_PENDING";else if(pAuth.length)state="PRODUCTS_AUTHORIZED";return{atlasProductId:child.atlasProductId,acceptanceArtifactId:id,state,governedAsin:effective?.governedAsin??null,productsTaskId:pTask?.taskId??null,sellersTaskId:sTask?.taskId??null,evidenceIds:[...evidenceIds].sort(),historicalObservationIds:admitted.map(x=>x.observationId).sort(),blocker};}
}
