import crypto from "node:crypto";
import { buildAmazonProductsRequest, buildAmazonSellersRequest } from "./DataForSeoAmazonRequests.js";
import { createAmazonProductsIdentityAdapter, normalizeAmazonCanonicalResult } from "./DataForSeoAmazonResults.js";
import { validateAmazonHistoricalAcceptance } from "./AmazonHistoricalAcceptancePreparation.js";

export const AMAZON_ACCEPTANCE_EXECUTION_POLICY_VERSION="MERCURY-HISTORY-050-1.0";
export const AMAZON_ACCEPTANCE_ACTION_CONFIRMATIONS=Object.freeze({AUTHORIZE_PRODUCTS:"AUTHORIZE-DATAFORSEO-AMAZON-PRODUCTS",EXECUTE_PRODUCTS:"EXECUTE-DATAFORSEO-AMAZON-PRODUCTS",AUTHORIZE_SELLERS:"AUTHORIZE-DATAFORSEO-AMAZON-SELLERS",EXECUTE_SELLERS:"EXECUTE-DATAFORSEO-AMAZON-SELLERS",RECOVER_PRODUCTS:"RECOVER-DATAFORSEO-AMAZON-PRODUCTS",RECOVER_SELLERS:"RECOVER-DATAFORSEO-AMAZON-SELLERS"});
const stable=v=>Array.isArray(v)?`[${v.map(stable).join(",")}]`:v&&typeof v==="object"?`{${Object.keys(v).sort().map(k=>`${JSON.stringify(k)}:${stable(v[k])}`).join(",")}}`:JSON.stringify(v),hash=v=>crypto.createHash("sha256").update(stable(v)).digest("hex");
const freeze=v=>{if(v&&typeof v==="object"&&!Object.isFrozen(v)){Object.freeze(v);for(const x of Object.values(v))freeze(x);}return v;},required=(v,c)=>{if(typeof v!=="string"||!v.trim())throw new Error(c);return v.trim();};
const intent=(artifactId,operation)=>`mer_histbootintent_${hash({artifactId,operation}).slice(0,24)}`;
function plan({artifact,operation,request,asOf,currentSpend}){const execution={kind:operation,provider:"DATAFORSEO",source:"DATAFORSEO_AMAZON",atlasProduct:operation==="AMAZON_PRODUCTS"?structuredClone(request.atlasProduct):undefined,atlasProductId:artifact.atlasProductId,dataAsin:request.dataAsin,locationName:"United States",languageName:"English (United States)",paidActionIntentId:intent(artifact.acceptanceArtifactId,operation),checkpointId:artifact.acceptanceArtifactId,productIndex:0,sourceRightsProfileDigest:artifact.sourceRightsProfileDigest};for(const k of Object.keys(execution))if(execution[k]===undefined)delete execution[k];const material={artifactId:artifact.acceptanceArtifactId,artifactBindingDigest:artifact.bindingDigest,operation,requestDigest:request.requestDigest,execution};const planId=`mer_amzplan_${hash(material).slice(0,24)}`;return freeze({schemaVersion:"1.0",planId,plannedAt:asOf,policy:{enabled:true,maxPaidTasksPerRun:1,maxSpendPerRunUsd:.0015,maxSpendPerDayUsd:.01,automaticPaidRetries:0},spentTodayUsd:currentSpend,approvedTaskCount:1,estimatedApprovedSpendUsd:.0015,decisions:[{candidateId:`${artifact.atlasProductId}:${operation}`,estimatedCostUsd:.0015,decision:"APPROVED",execution}]});}
export function createAmazonAcceptanceActionAuthorization({artifact,operation,atlasProduct,productsOutcome=null,operator,reason,authorizedAt,expiresAt,currentUtcDaySpendUsd,predecessorAuthorizationId=null,recovery=null}={}){validateAmazonHistoricalAcceptance(artifact);required(operator,"AMAZON_ACCEPTANCE_OPERATOR_REQUIRED");required(reason,"AMAZON_ACCEPTANCE_REASON_REQUIRED");if(predecessorAuthorizationId!==null)required(predecessorAuthorizationId,"AMAZON_ACCEPTANCE_PREDECESSOR_REQUIRED");if(!["AMAZON_PRODUCTS","AMAZON_SELLERS"].includes(operation)||!Number.isFinite(Date.parse(authorizedAt))||!Number.isFinite(Date.parse(expiresAt))||Date.parse(expiresAt)<=Date.parse(authorizedAt))throw new Error("AMAZON_ACCEPTANCE_AUTHORIZATION_INPUT_INVALID");if(!Number.isFinite(currentUtcDaySpendUsd)||currentUtcDaySpendUsd+.0015>.01)throw new Error("AMAZON_ACCEPTANCE_UTC_DAY_BUDGET_BLOCKED");let request;if(operation==="AMAZON_PRODUCTS"){if(atlasProduct?.identity?.atlasProductId!==artifact.atlasProductId)throw new Error("AMAZON_ACCEPTANCE_ATLAS_BINDING_INVALID");request={...buildAmazonProductsRequest({atlasProduct}),atlasProduct};}else{if(productsOutcome?.state!=="STRONG_UNIQUE_ASIN"||productsOutcome?.artifactId!==artifact.acceptanceArtifactId)throw new Error("AMAZON_ACCEPTANCE_SELLERS_IDENTITY_NOT_STRONG");request={...buildAmazonSellersRequest({atlasProductId:artifact.atlasProductId,dataAsin:productsOutcome.governedAsin}),dataAsin:productsOutcome.governedAsin};}const acquisitionPlan=plan({artifact,operation,request,asOf:authorizedAt,currentSpend:currentUtcDaySpendUsd}),material={policyVersion:AMAZON_ACCEPTANCE_EXECUTION_POLICY_VERSION,artifactId:artifact.acceptanceArtifactId,artifactBindingDigest:artifact.bindingDigest,operation,atlasProductId:artifact.atlasProductId,requestDigest:request.requestDigest,plan:acquisitionPlan,operator:operator.trim(),reason:reason.trim(),authorizedAt,expiresAt,sourceRightsProfileDigest:artifact.sourceRightsProfileDigest,predecessorAuthorizationId,...(recovery?{recovery:structuredClone(recovery)}:{})};return freeze({schemaVersion:"1.0",authorizationId:`mer_amzactauth_${hash(material).slice(0,24)}`,...material,status:"AUTHORIZED",maxTaskPriceUsd:.0015,singleUse:true,automaticPaidRetries:0,providerCallPerformed:false,actualSpendUsd:0});}
export function validateAmazonAcceptanceActionAuthorization(value,artifact){validateAmazonHistoricalAcceptance(artifact);if(value?.policyVersion!==AMAZON_ACCEPTANCE_EXECUTION_POLICY_VERSION||value?.artifactId!==artifact.acceptanceArtifactId||value?.artifactBindingDigest!==artifact.bindingDigest||value?.atlasProductId!==artifact.atlasProductId||value?.sourceRightsProfileDigest!==artifact.sourceRightsProfileDigest||value?.status!=="AUTHORIZED"||value?.maxTaskPriceUsd!==.0015||value?.singleUse!==true||value?.automaticPaidRetries!==0||value?.plan?.approvedTaskCount!==1||value.plan?.decisions?.[0]?.execution?.kind!==value.operation||value.plan?.decisions?.[0]?.execution?.source!=="DATAFORSEO_AMAZON")throw new Error("AMAZON_ACCEPTANCE_AUTHORIZATION_INVALID");return true;}
export function amazonAcceptanceAuthorizationRequest(value){return freeze({requestId:value.authorizationId,planId:value.plan.planId,plan:value.plan,expiresAt:value.expiresAt,maxSpendUsd:.0015,maxPaidTasks:1});}
export function processAmazonAcceptanceProducts({artifact,authorization,canonicalResult,atlasProduct,brandAliases=[],corroboratingDestinationAsins=[]}={}){validateAmazonAcceptanceActionAuthorization(authorization,artifact);if(authorization.operation!=="AMAZON_PRODUCTS"||canonicalResult?.checkpointId!==artifact.acceptanceArtifactId||canonicalResult?.atlasProductId!==artifact.atlasProductId||canonicalResult?.operation!=="AMAZON_PRODUCTS"||canonicalResult?.sourceId!=="DATAFORSEO_AMAZON")throw new Error("AMAZON_ACCEPTANCE_PRODUCTS_LINEAGE_INVALID");const output=createAmazonProductsIdentityAdapter().process({canonicalResult,atlasProduct,brandAliases,corroboratingDestinationAsins}),strong=output.status==="STRONG_UNIQUE_ASIN",material={artifactId:artifact.acceptanceArtifactId,authorizationId:authorization.authorizationId,canonicalResultId:canonicalResult.canonicalResultId,resultDigest:canonicalResult.resultDigest,state:output.status,assessmentId:output.assessment.assessmentId,governedAsin:strong?output.governedAsinAnchor.asin:null};return freeze({schemaVersion:"1.0",outcomeId:`mer_amzoutcome_${hash(material).slice(0,24)}`,...material,nextPermittedAction:strong?"OPERATOR_REVIEW_FOR_SELLERS":"STOP",sellersAuthorizationEligible:strong,asinEnrichmentAuthorized:false,providerCallPerformed:false,actualSpendUsd:0});}
export function projectAmazonAcceptanceSellerResult(canonicalResult){if(canonicalResult?.operation!=="AMAZON_SELLERS"||canonicalResult?.sourceId!=="DATAFORSEO_AMAZON")throw new Error("AMAZON_ACCEPTANCE_SELLERS_RESULT_INVALID");return normalizeAmazonCanonicalResult(canonicalResult);}
