import crypto from "node:crypto";
import { createHistoricalBootstrapProviderResult } from "../portfolio/FileHistoricalBootstrapProviderResultRepository.js";
import { createAmazonProductsEvidence, createAmazonAsinEvidence, createAmazonSellersEvidence, DATAFORSEO_AMAZON_OPERATIONS, DATAFORSEO_AMAZON_SOURCE_ID } from "./DataForSeoAmazonContracts.js";
import { assessAtlasAmazonAsinIdentity, AMAZON_ASIN_IDENTITY_STATES } from "./AmazonAsinIdentityAssessment.js";

const stable=value=>Array.isArray(value)?`[${value.map(stable).join(",")}]`:value&&typeof value==="object"?`{${Object.keys(value).sort().map(key=>`${JSON.stringify(key)}:${stable(value[key])}`).join(",")}}`:JSON.stringify(value);
const digest=value=>crypto.createHash("sha256").update(stable(value)).digest("hex");
const freeze=value=>{const copy=structuredClone(value);const deep=v=>{if(v&&typeof v==="object"&&!Object.isFrozen(v)){Object.freeze(v);for(const child of Object.values(v))deep(child);}return v;};return deep(copy);};
const inheritAsin=(item,row)=>{const itemAsin=item?.data_asin??item?.asin??null,rowAsin=row?.asin??null;if(itemAsin&&rowAsin&&String(itemAsin).toUpperCase()!==String(rowAsin).toUpperCase())throw new Error("DATAFORSEO_AMAZON_SELLERS_ASIN_CONFLICT");return{...item,data_asin:itemAsin??rowAsin};};
const items=result=>Array.isArray(result?.result)?result.result.flatMap(row=>Array.isArray(row?.items)?row.items.map(item=>inheritAsin(item,row)):[]):[];

export function createDataForSeoAmazonProviderResult({operation,providerTaskId,paidActionIntentId,checkpointId,atlasProductId,productIndex=0,sourceRightsProfileDigest,requestDigest,operationResult,retrievedAt}={}){
 if(!Object.values(DATAFORSEO_AMAZON_OPERATIONS).includes(operation)||!/^[a-f0-9]{64}$/.test(requestDigest??""))throw new Error("DATAFORSEO_AMAZON_PROVIDER_RESULT_INVALID");
 const result=createHistoricalBootstrapProviderResult({operation,sourceId:DATAFORSEO_AMAZON_SOURCE_ID,providerTaskId,paidActionIntentId,checkpointId,atlasProductId,productIndex,sourceRightsProfileDigest,requestIdentityDigest:requestDigest,operationResult,retrievedAt});
 return freeze({...result,policyVersion:"MERCURY-HISTORY-047-1.0",requestDigest,materialResultDigest:digest(operationResult)});
}

export function createAmazonProductsIdentityAdapter(){return Object.freeze({process({canonicalResult,atlasProduct,brandAliases=[],corroboratingDestinationAsins=[]}={}){if(canonicalResult?.sourceId!==DATAFORSEO_AMAZON_SOURCE_ID||canonicalResult?.operation!==DATAFORSEO_AMAZON_OPERATIONS.PRODUCTS)throw new Error("DATAFORSEO_AMAZON_PRODUCTS_RESULT_REQUIRED");const candidates=items(canonicalResult.operationResult).map(createAmazonProductsEvidence);const assessment=assessAtlasAmazonAsinIdentity({atlasProduct,candidates,brandAliases,corroboratingDestinationAsins});return freeze({status:assessment.state,assessment,sellersReadiness:assessment.state===AMAZON_ASIN_IDENTITY_STATES.STRONG_UNIQUE_ASIN?"SELLERS_READY":"NOT_ESTABLISHED",governedAsinAnchor:assessment.providerAnchor,paidTaskCreated:false,actualSpendUsd:0});}});}
export function normalizeAmazonSellersResultRows(record){if(record?.sourceId!==DATAFORSEO_AMAZON_SOURCE_ID||record?.operation!==DATAFORSEO_AMAZON_OPERATIONS.SELLERS)throw new Error("DATAFORSEO_AMAZON_SELLERS_RESULT_REQUIRED");const rows=Array.isArray(record.operationResult?.result)?record.operationResult.result:[];let itemIndex=0;return freeze(rows.flatMap(row=>Array.isArray(row?.items)?row.items.map(item=>({itemIndex:itemIndex++,observedAt:row?.datetime??record.retrievedAt,sellerItem:createAmazonSellersEvidence(inheritAsin(item,row))})):[]));}
export function normalizeAmazonCanonicalResult(record){if(record?.sourceId!==DATAFORSEO_AMAZON_SOURCE_ID)throw new Error("DATAFORSEO_AMAZON_RESULT_SOURCE_MISMATCH");const map={[DATAFORSEO_AMAZON_OPERATIONS.PRODUCTS]:createAmazonProductsEvidence,[DATAFORSEO_AMAZON_OPERATIONS.ASIN]:createAmazonAsinEvidence,[DATAFORSEO_AMAZON_OPERATIONS.SELLERS]:createAmazonSellersEvidence},fn=map[record.operation];if(!fn)throw new Error("DATAFORSEO_AMAZON_RESULT_OPERATION_INVALID");return freeze(items(record.operationResult).map(fn));}

export class DataForSeoAmazonResultRetrievalService{
 constructor({taskLedger,acquisitionService,resultRepository,now=()=>new Date().toISOString()}={}){if(!taskLedger?.getAll||!acquisitionService||!resultRepository?.record)throw new TypeError("DATAFORSEO_AMAZON_RETRIEVAL_DEPENDENCIES_REQUIRED");Object.assign(this,{taskLedger,acquisitionService,resultRepository,now});}
 async retrieve({providerTaskId}={}){const matches=(await this.taskLedger.getAll()).filter(entry=>entry.taskId===providerTaskId);if(matches.length!==1)throw new Error("DATAFORSEO_AMAZON_TASK_LINEAGE_INVALID");const task=matches[0];if(task.sourceId!==DATAFORSEO_AMAZON_SOURCE_ID||!Object.values(DATAFORSEO_AMAZON_OPERATIONS).includes(task.kind))throw new Error("DATAFORSEO_AMAZON_TASK_SOURCE_MISMATCH");if(typeof task.checkpointId!=="string"||!task.checkpointId||!Number.isInteger(task.productIndex)||typeof task.sourceRightsProfileDigest!=="string"||!/^[a-f0-9]{64}$/.test(task.sourceRightsProfileDigest)||typeof task.paidActionIntentId!=="string"||!task.paidActionIntentId)throw new Error("DATAFORSEO_AMAZON_TASK_LINEAGE_INVALID");const method={[DATAFORSEO_AMAZON_OPERATIONS.PRODUCTS]:"getAmazonProductsResult",[DATAFORSEO_AMAZON_OPERATIONS.ASIN]:"getAmazonAsinResult",[DATAFORSEO_AMAZON_OPERATIONS.SELLERS]:"getAmazonSellersResult"}[task.kind];let outcome;try{outcome=await this.acquisitionService[method](providerTaskId);}catch(error){if(/^DATAFORSEO_TASK_ERROR:40/.test(String(error?.message)))return freeze({status:"PENDING",paidTaskCreated:false,actualSpendUsd:0});throw error;}if(outcome?.status==="PROVIDER_FAILED")return freeze({status:"FAILED",paidTaskCreated:false,actualSpendUsd:0});if(!Array.isArray(outcome?.result)||outcome.result.length===0)return freeze({status:"PENDING",paidTaskCreated:false,actualSpendUsd:0});const prior=await this.resultRepository.findByTask?.(providerTaskId);if(prior){if(prior.sourceId!==task.sourceId||prior.operation!==task.kind||prior.requestDigest!==task.requestDigest||prior.resultDigest!==digest(outcome))throw new Error("BOOTSTRAP_PROVIDER_RESULT_CONFLICT");return freeze({status:"AVAILABLE",canonicalResult:prior,paidTaskCreated:false,actualSpendUsd:0});}const canonicalResult=await this.resultRepository.record(createDataForSeoAmazonProviderResult({operation:task.kind,providerTaskId,paidActionIntentId:task.paidActionIntentId,checkpointId:task.checkpointId,atlasProductId:task.atlasProductId,productIndex:task.productIndex,sourceRightsProfileDigest:task.sourceRightsProfileDigest,requestDigest:task.requestDigest,operationResult:outcome,retrievedAt:this.now()}));return freeze({status:"AVAILABLE",canonicalResult,paidTaskCreated:false,actualSpendUsd:0});}
}
