import crypto from "node:crypto";
import { mkdir, readFile, rename, writeFile } from "node:fs/promises";
import { dirname } from "node:path";
import { projectEffectiveAmazonProductsOutcome, validateAmazonProductsIdentityReassessment } from "./AmazonProductsIdentityReassessment.js";
import { projectOperatorConfirmedAmazonProductsOutcome, validateAmazonOperatorIdentityConfirmation } from "./AmazonOperatorIdentityConfirmation.js";

const stable = value => JSON.stringify(value), clone = value => structuredClone(value);
const freeze = value => { const copy = clone(value); const deep = item => { if (item && typeof item === "object" && !Object.isFrozen(item)) { Object.freeze(item); for (const child of Object.values(item)) deep(child); } return item; }; return deep(copy); };
const empty = () => ({ schemaVersion: "1.0", authorizations: [], outcomes: [], reassessments: [], identityConfirmations: [] });
export class FileAmazonAcceptanceActionRepository {
  constructor({ statePath } = {}) { if (!statePath) throw new Error("AMAZON_ACCEPTANCE_ACTION_STATE_REQUIRED"); this.statePath = statePath; this.q = Promise.resolve(); }
  async _read() { try { const state = JSON.parse(await readFile(this.statePath, "utf8")); if (state?.schemaVersion !== "1.0" || !Array.isArray(state.authorizations) || !Array.isArray(state.outcomes) || (state.reassessments !== undefined && !Array.isArray(state.reassessments)) || (state.identityConfirmations !== undefined && !Array.isArray(state.identityConfirmations))) throw new Error("AMAZON_ACCEPTANCE_ACTION_STATE_INVALID"); return { ...state, reassessments: state.reassessments ?? [], identityConfirmations: state.identityConfirmations ?? [] }; } catch (error) { if (error?.code === "ENOENT") return empty(); throw error; } }
  async _write(state) { await mkdir(dirname(this.statePath), { recursive: true }); const temporary = `${this.statePath}.${process.pid}.${crypto.randomUUID()}.tmp`; await writeFile(temporary, `${JSON.stringify(state, null, 2)}\n`); await rename(temporary, this.statePath); }
  _locked(operation) { const result = this.q.then(operation, operation); this.q = result.catch(() => {}); return result; }
  async getAuthorization(id) { return freeze((await this._read()).authorizations.find(value => value.authorizationId === id) ?? null); }
  async getAuthorizationsForAction(artifactId, operation) { return freeze((await this._read()).authorizations.filter(value => value.artifactId === artifactId && value.operation === operation)); }
  async getOutcomeById(id) { return freeze((await this._read()).outcomes.find(value => value.outcomeId === id) ?? null); }
  async getOutcomeForArtifact(id) { const rows = (await this._read()).outcomes.filter(value => value.artifactId === id); if (rows.length > 1 && new Set(rows.map(value => value.outcomeId)).size !== 1) throw new Error("AMAZON_ACCEPTANCE_OUTCOME_CONFLICT"); return freeze(rows.at(-1) ?? null); }
  async getReassessmentsForOutcome(id) { return freeze((await this._read()).reassessments.filter(value => value.originalOutcomeId === id)); }
  async getIdentityConfirmationsForOutcome(id) { return freeze((await this._read()).identityConfirmations.filter(value => value.originalOutcomeId === id)); }
  async getEffectiveOutcomeForArtifact(id) { const original = await this.getOutcomeForArtifact(id); if (!original) return null; const reassessments = await this.getReassessmentsForOutcome(original.outcomeId), confirmations = await this.getIdentityConfirmationsForOutcome(original.outcomeId); if (reassessments.length && confirmations.length) throw new Error("AMAZON_PRODUCTS_EFFECTIVE_IDENTITY_CONFLICT"); if (confirmations.length) { if (confirmations.length !== 1) throw new Error("AMAZON_OPERATOR_IDENTITY_CONFIRMATION_CONFLICT"); return projectOperatorConfirmedAmazonProductsOutcome(original, confirmations[0]); } return projectEffectiveAmazonProductsOutcome(original, reassessments); }
  async recordReassessment(value) { validateAmazonProductsIdentityReassessment(value); return this._locked(async () => { const state = await this._read(), original = state.outcomes.find(item => item.outcomeId === value.originalOutcomeId); if (!original) throw new Error("AMAZON_PRODUCTS_REASSESSMENT_ORIGINAL_NOT_FOUND"); validateAmazonProductsIdentityReassessment(value, { originalOutcome: original }); const prior = state.reassessments.find(item => item.reassessmentId === value.reassessmentId), same = state.reassessments.filter(item => item.originalOutcomeId === value.originalOutcomeId); if (prior) { if (stable(prior) !== stable(value)) throw new Error("AMAZON_PRODUCTS_REASSESSMENT_CONFLICT"); return { status: "DUPLICATE", value: freeze(prior) }; } if (same.length || state.identityConfirmations.some(item => item.originalOutcomeId === value.originalOutcomeId)) throw new Error("AMAZON_PRODUCTS_REASSESSMENT_CONFLICT"); state.reassessments.push(clone(value)); await this._write(state); return { status: "RECORDED", value: freeze(value) }; }); }
  async recordIdentityConfirmation(value) { validateAmazonOperatorIdentityConfirmation(value); return this._locked(async () => { const state = await this._read(), original = state.outcomes.find(item => item.outcomeId === value.originalOutcomeId); if (!original) throw new Error("AMAZON_OPERATOR_IDENTITY_ORIGINAL_NOT_FOUND"); validateAmazonOperatorIdentityConfirmation(value, { originalOutcome: original }); const prior = state.identityConfirmations.find(item => item.confirmationId === value.confirmationId), same = state.identityConfirmations.filter(item => item.originalOutcomeId === value.originalOutcomeId); if (prior) { if (stable(prior) !== stable(value)) throw new Error("AMAZON_OPERATOR_IDENTITY_CONFIRMATION_CONFLICT"); return { status: "DUPLICATE", value: freeze(prior) }; } if (same.length || state.reassessments.some(item => item.originalOutcomeId === value.originalOutcomeId)) throw new Error("AMAZON_OPERATOR_IDENTITY_CONFIRMATION_CONFLICT"); state.identityConfirmations.push(clone(value)); await this._write(state); return { status: "RECORDED", value: freeze(value) }; }); }
  async recordAuthorization(value, { asOf = value.authorizedAt, expectedPredecessorIds = [], consumedAuthorizationIds = [] } = {}) { return this._locked(async () => { const state = await this._read(), prior = state.authorizations.find(item => item.authorizationId === value.authorizationId); if (prior) { if (stable(prior) !== stable(value)) throw new Error("AMAZON_ACCEPTANCE_AUTHORIZATION_CONFLICT"); return { status: "DUPLICATE", value: freeze(prior) }; } const sameAction = state.authorizations.filter(item => item.artifactId === value.artifactId && item.operation === value.operation), actualIds = sameAction.map(item => item.authorizationId), consumed = new Set(consumedAuthorizationIds); if ([...consumed].some(id => !actualIds.includes(id))) throw new Error("AMAZON_ACCEPTANCE_AUTHORIZATION_CONSUMPTION_LINEAGE_INVALID"); if (stable(actualIds) !== stable(expectedPredecessorIds)) throw new Error("AMAZON_ACCEPTANCE_AUTHORIZATION_CONFLICT"); if (sameAction.some(item => !consumed.has(item.authorizationId) && Date.parse(asOf) < Date.parse(item.expiresAt))) throw new Error("AMAZON_ACCEPTANCE_AUTHORIZATION_ACTIVE"); if (sameAction.length && value.predecessorAuthorizationId !== sameAction.at(-1).authorizationId) throw new Error("AMAZON_ACCEPTANCE_AUTHORIZATION_CONFLICT"); state.authorizations.push(clone(value)); await this._write(state); return { status: "RECORDED", value: freeze(value) }; }); }
  async recordOutcome(value) { return this._record("outcomes", "outcomeId", value, "AMAZON_ACCEPTANCE_OUTCOME_CONFLICT"); }
  async _record(bucket, key, value, code) { return this._locked(async () => { const state = await this._read(), prior = state[bucket].find(item => item[key] === value[key]); if (prior) { if (stable(prior) !== stable(value)) throw new Error(code); return { status: "DUPLICATE", value: freeze(prior) }; } state[bucket].push(clone(value)); await this._write(state); return { status: "RECORDED", value: freeze(value) }; }); }
}
