const text=(value,fallback="Unavailable")=>value===null||value===undefined||value===""?fallback:String(value);
const decimalPlaces=value=>{const [coefficient,exponentText]=String(value).toLowerCase().split("e"),exponent=Number(exponentText??0),fraction=(coefficient.split(".")[1]??"").length;return Math.max(0,fraction-exponent);};
export const formatOperationalMoney=(currency,value)=>Number.isFinite(value)&&value>=0?`${currency??""} ${value.toFixed(Math.max(4,decimalPlaces(value)))}`.trim():"Unavailable";
const historicalMoney=(currency,value)=>Number.isFinite(value)?`${currency??""} ${value.toFixed(2)}`.trim():"No historical value";

export class CertifiedMercuryOperationsPanel{
 constructor(root){this.root=root;this.file=root.querySelector("#certifiedMercuryProjectionFile");this.badge=root.querySelector("#certifiedMercuryProjectionStatus");this.summary=root.querySelector("#certifiedMercuryProjectionSummary");this.cohortStatus=root.querySelector("#certifiedMercuryProjectionCohortStatus");this.cohorts=root.querySelector("#certifiedMercuryProjectionCohorts");this.products=root.querySelector("#certifiedMercuryProjectionProducts");this.details=root.querySelector("#certifiedMercuryProjectionDetails");this.file.addEventListener("change",()=>this.load());this.reset();}
 reset(){this.badge.textContent="NO PROJECTION";this.badge.className="status-badge pending";this.summary.textContent="Load a local certified Mercury operations projection. No repository or provider operation is performed.";if(this.cohortStatus)this.cohortStatus.textContent="No certified projection loaded. Select a certified Mercury operations projection to view cohort operations.";this.cohorts?.replaceChildren();this.products.replaceChildren();this.details.textContent="{}";}
 async load(){const file=this.file.files?.[0];if(!file)return this.reset();try{this.render(JSON.parse(await file.text()));}catch(error){this.reset();this.badge.textContent="UNAVAILABLE";this.badge.className="status-badge blocked";this.summary.textContent=`Certified projection unavailable: ${error.message}`;}}
 render(model){if(!model||!["1.0","1.1"].includes(model.schemaVersion)||model.projectionType!=="CERTIFIED_MERCURY_OPERATIONS_PROJECTION"||model.readOnly!==true||model.mutationAuthorized!==false||model.networkOperation!=="NONE"||model.semantics?.canonicalOperationalView!==true||model.semantics?.historicalValueSemantics!=="HISTORICAL_OBSERVATION"||model.semantics?.currentPrice!==false||model.semantics?.livePrice!==false||model.semantics?.publicPrice!==false||model.semantics?.publicationAuthority!==false||!Array.isArray(model.products))throw new TypeError("Not a certified Mercury operations projection.");const cohortCapable=model.schemaVersion==="1.1"&&model.cohortOperations?.projectionType==="CERTIFIED_MERCURY_COHORT_OPERATIONS"&&Array.isArray(model.cohortOperations.cohorts),cohorts=cohortCapable?model.cohortOperations.cohorts:[];this.badge.textContent="CERTIFIED READ-ONLY";this.badge.className="status-badge ready";this.summary.textContent=`As of ${model.asOf} · ${model.products.length} Atlas products · ${model.summary?.retainedEvidenceCount??0} retained evidence · ${model.summary?.totalHistoricalObservations??0} historical observations`;if(this.cohortStatus)this.cohortStatus.textContent=!cohortCapable?"Cohort operations unavailable. This certified projection does not contain cohort operations; generate and select a current schema-1.1 projection.":cohorts.length===0?"No bounded Mercury cohorts are present in this certified projection.":`${cohorts.length} certified bounded Mercury cohort${cohorts.length===1?"":"s"}.`;this.cohorts?.replaceChildren(...cohorts.map(cohort=>this.cohort(cohort)));this.products.replaceChildren(...model.products.map(product=>this.card(product)));this.details.textContent=JSON.stringify(model,null,2);}
 cohort(cohort){const node=document.createElement("article");node.className="certified-mercury-cohort";const members=cohort.members.map(member=>{const repeat=member.repeatObservation,reprocessed=repeat?.reprocessing,status=reprocessed?` | Original ${text(member.originalException,member.state)} | Reprocessing ${reprocessed.status} | Effective evidence/history ${reprocessed.effectiveEvidenceCount}/${reprocessed.effectiveHistoricalObservationCount}${reprocessed.skippedHistoricalCount?` (${reprocessed.skippedHistoricalCount} history-ineligible)`:""}`:member.originalException?` | Original exception ${member.originalException}`:"";return `${text(member.atlasProduct.displayName,member.atlasProduct.atlasProductId)} — ${member.classification}${member.review.eligible?` (${member.review.type})`:""}${status}`;}).join(" | ");node.textContent=`${cohort.cohortType} | Plan ${cohort.identity.planId} | Run ${text(cohort.identity.runId)} | Requested ${cohort.membership.requested} | Completed ${cohort.membership.completed} | Pending ${cohort.membership.pending} | Exceptions ${cohort.membership.exceptions} | Spend ${formatOperationalMoney("USD",cohort.cost.actualSpendUsd)} / ${formatOperationalMoney("USD",cohort.cost.authorizedMaximumSpendUsd)} | Systemic ${cohort.safety.systemicFailure?"YES":"NO"} | No downstream authority | ${members}`;return node;}
 card(product){const node=document.createElement("article");node.className="certified-mercury-product";const latest=historicalMoney(product.history.latestCurrency,product.history.latestTotalPrice),reasons=product.blockers.map(x=>x.code).join(", ")||"None";node.textContent=`${text(product.atlasProduct.displayName,product.atlasProduct.atlasProductId)} | ${product.atlasProduct.atlasProductId} | Evidence ${product.evidence.retainedCount} | History ${product.history.observationCount} | Latest historical observation ${latest} | Identity ${product.identityReview.state} | Promotion ${product.promotion.state} | Cadence ${product.cadence.dueState} | Review/publication ${product.durableWorkflow.state} | Blockers ${reasons} | Next action ${text(product.nextAction)}`;return node;}
}
