const value = (input, fallback = "Not specified") => input === null || input === undefined || input === "" ? fallback : String(input);
const element = (tag, className, text) => { const node = document.createElement(tag); if (className) node.className = className; if (text !== undefined) node.textContent = text; return node; };
const timing = specs => specs?.performance?.primaryTimings ?? ([specs?.performance?.casLatency, specs?.performance?.tRcd, specs?.performance?.tRp, specs?.performance?.tRas].filter(Number.isFinite).join("-") || null);
// Consequential controls remain disabled until the authenticated trusted operator runtime is connected.

export function filterForgeProducts(products, { query = "", memory = "", formFactor = "", capacity = "", lifecycle = "", retailer = "" } = {}) {
    const normalized = query.trim().toLowerCase();
    return products.filter(product => {
        const haystack = [product.brand, product.manufacturerPartNumber, product.displayName, product.atlasProductId].join(" ").toLowerCase();
        return (!normalized || haystack.includes(normalized)) && (!memory || product.facets.memoryType === memory) && (!formFactor || product.facets.formFactor === formFactor) && (!capacity || String(product.facets.capacityGb) === String(capacity)) && (!lifecycle || product.lifecycleStatus === lifecycle) && (!retailer || (retailer === "MISSING" ? product.destinations.length === 0 : product.retailerCoverage.includes(retailer)));
    });
}

export function sortForgeProducts(products, sort = "brand") {
    const selectors = { brand: product => `${product.brand} ${product.displayName}`, name: product => product.displayName, capacity: product => Number(product.facets.capacityGb) || 0, current: product => product.current.available ? 1 : 0, history: product => Number(product.history.observationCount) || 0 };
    const select = selectors[sort] ?? selectors.brand;
    return [...products].sort((left, right) => typeof select(left) === "number" ? select(right) - select(left) : String(select(left)).localeCompare(String(select(right)), undefined, { numeric: true, sensitivity: "base" }));
}

export class ProductManagerPanel {
    constructor(root, { defaultUrl = "/operator-data/product-manager.json", pageSize = 25 } = {}) {
        this.root = root; this.products = []; this.model = null; this.selected = null; this.page = 1; this.pageSize = pageSize; this.sort = "brand";
        this.file = document.getElementById("productManagerFile"); this.badge = root.querySelector("#productManagerBadge"); this.summary = root.querySelector("#productManagerSummary"); this.results = root.querySelector("#productManagerResults"); this.details = root.querySelector("#productManagerDetails");
        this.sortControl = root.querySelector("#productManagerSort"); this.previous = root.querySelector("#productManagerPrevious"); this.next = root.querySelector("#productManagerNext"); this.pageStatus = root.querySelector("#productManagerPageStatus");
        this.filters = { search: root.querySelector("#productManagerSearch"), memory: root.querySelector("#productManagerMemory"), formFactor: root.querySelector("#productManagerFormFactor"), capacity: root.querySelector("#productManagerCapacity"), lifecycle: root.querySelector("#productManagerLifecycle"), retailer: root.querySelector("#productManagerRetailer") };
        this.addButton=root.querySelector("#productManagerAdd");this.dialog=root.querySelector("#forgeProductDialog");this.dialogForm=root.querySelector("#forgeProductDialogForm");this.dialogStatus=root.querySelector("#forgeProductDialogStatus");this.csrf=null;
        this.addButton?.addEventListener("click",()=>this.dialog?.showModal());this.dialogForm?.addEventListener("submit",event=>this.saveProduct(event));void this.connectRuntime();
        this.file?.addEventListener("change", () => this.load());
        Object.values(this.filters).forEach(control => control?.addEventListener("input", () => { this.page = 1; this.renderResults(); }));
        this.sortControl?.addEventListener("change", () => { this.sort = this.sortControl.value; this.renderResults(); });
        this.previous?.addEventListener("click", () => { if (this.page > 1) { this.page -= 1; this.renderResults(); } });
        this.next?.addEventListener("click", () => { this.page += 1; this.renderResults(); });
        root.querySelector("#productManagerReset")?.addEventListener("click", () => this.resetFilters());
        this.showLoading(); void this.loadUrl(defaultUrl);
    }
    async connectRuntime(){try{const token=new URL(location.href).hash.match(/forge-bootstrap=([^&]+)/)?.[1];if(token){const response=await fetch("/operator-api/bootstrap",{method:"POST",headers:{"X-Forge-Bootstrap":decodeURIComponent(token)}});history.replaceState(null,"",location.pathname);if(!response.ok)throw new Error();this.csrf=(await response.json()).csrf;}else{const response=await fetch("/operator-api/session");if(response.ok)this.csrf=(await response.json()).csrf;}if(this.csrf){this.addButton.disabled=false;this.root.querySelector(".product-manager-security").innerHTML="<strong>Trusted operator runtime connected.</strong> Changes require explicit confirmation, canonical validation, and durable audit.";}}catch{this.csrf=null;}}
    buildDraft(data){const now=new Date().toISOString(),manufacturer=String(data.get("manufacturer")).trim(),mpn=String(data.get("mpn")).trim(),name=String(data.get("productName")).trim(),memoryType=String(data.get("memoryType")),formFactor=String(data.get("formFactor")),capacityGb=Number(data.get("capacityGb")),moduleCount=Number(data.get("moduleCount")),capacityPerModuleGb=Number(data.get("capacityPerModuleGb")),dataRateMtps=Number(data.get("dataRateMtps")),timings=String(data.get("primaryTimings")||"").trim()||null,evidenceUrl=String(data.get("evidenceUrl")).trim(),key=`${manufacturer}_${mpn}`.toLowerCase().replace(/[^a-z0-9]+/g,"_").replace(/^_|_$/g,""),slug=`${manufacturer}-${name}-${mpn}`.toLowerCase().replace(/[^a-z0-9]+/g,"-").replace(/^-|-$/g,"");const source={sourceId:`SRC-MFG-${mpn}`,sourceType:"MANUFACTURER_PRODUCT_PAGE",sourceLocator:evidenceUrl,retrievedAt:now,verifiedBy:"forge:trusted-operator",verificationStatus:"VERIFIED"};return{identity:{atlasProductId:`ram_${key}`,schemaVersion:"1.0",productType:"ram",recordRevision:1,createdAt:now,updatedAt:now,createdBy:"forge:trusted-operator",updatedBy:"forge:trusted-operator",brand:manufacturer,manufacturer,modelName:name,manufacturerPartNumber:mpn,displayName:name,slug},governance:{publicationStatus:"PENDING",lifecycleStatus:"DRAFT",engineeringValidationStatus:"PASS",humanReviewRequired:true},provenance:{fieldSources:{"identity.manufacturerPartNumber":[source]}},validation:{errors:[],warnings:[],validatedAt:now,validatorVersion:"atlas-product-validator/1.0.0"},extension:{extensionType:"ram",schemaVersion:"1.0",data:{classification:{memoryType,formFactor,applicationClass:formFactor==="SO_DIMM"?"LAPTOP":"DESKTOP",moduleType:formFactor==="SO_DIMM"?"SO_DIMM":"UDIMM",buffering:"UNBUFFERED",eccType:"NONE",isKit:moduleCount>1},capacity:{capacityGb,moduleCount,capacityPerModuleGb},performance:{dataRateMtps,speedLabel:`${memoryType}-${dataRateMtps}`,primaryTimings:timings,xmpSupport:"UNKNOWN",expoSupport:"UNKNOWN"},electrical:{ratedVoltage:Number(data.get("ratedVoltage"))||null},physical:{heatSpreader:false,rgbLighting:false},compatibility:{}}}};}
    async saveProduct(event){event.preventDefault();if(!this.csrf)return;const product=this.buildDraft(new FormData(this.dialogForm)),c=product.extension.data.capacity;if(c.capacityGb!==c.moduleCount*c.capacityPerModuleGb){this.dialogStatus.textContent="Capacity must equal module count × capacity per module.";return;}this.dialogStatus.textContent="Validating and saving…";try{const response=await fetch("/operator-api/product/create",{method:"POST",headers:{"Content-Type":"application/json","X-Forge-Csrf":this.csrf},body:JSON.stringify({requestId:crypto.randomUUID().replaceAll("-",""),confirmation:"CONFIRM CREATE_PRODUCT",payload:product})}),result=await response.json();if(!response.ok)throw new Error(result.error);this.dialogStatus.textContent=`Saved ${result.result.atlasProductId}. Audit ${result.auditId}.`;await this.loadUrl("/operator-data/product-manager.json");}catch(error){this.dialogStatus.textContent=`Not saved: ${error.message}`;}}
    async operatorRequest(path,action,payload){const response=await fetch(path,{method:"POST",headers:{"Content-Type":"application/json","X-Forge-Csrf":this.csrf},body:JSON.stringify({action,requestId:crypto.randomUUID().replaceAll("-",""),confirmation:`CONFIRM ${action}`,payload})}),result=await response.json();if(!response.ok)throw new Error(result.error);return result;}
    async checkDestination(product){const destination=product.destinations[0];if(!destination)return alert("No governed destination is available to check.");try{const result=await this.operatorRequest("/operator-api/link/verify","VERIFY_LINK",{url:destination.url,expectedRetailerHost:destination.marketplace,expectedListingId:destination.listingId});alert(`Link result: ${result.result.status}\nAudit: ${result.auditId}`);}catch(error){alert(`Link was not changed: ${error.message}`);}}
    async addDestination(product){const retailer=prompt("Retailer: AMAZON or NEWEGG","AMAZON")?.trim().toUpperCase();if(!retailer)return;const url=prompt("Exact product URL (HTTPS)");if(!url)return;const listingId=prompt(retailer==="AMAZON"?"ASIN":"Newegg listing ID");if(!listingId)return;const configuration=retailer==="AMAZON"?{retailerId:"RETAILER-0001",marketplace:"amazon.com"}:{retailerId:"RETAILER-0004",marketplace:"newegg.com"};try{const result=await this.operatorRequest("/operator-api/destination","ADD_DESTINATION",{atlasProductId:product.atlasProductId,...configuration,destinationType:"PRODUCT_PAGE",destinationUrl:url,retailerListingId:listingId,binding:{manufacturerPartNumber:product.manufacturerPartNumber,method:"OPERATOR_EXACT_PRODUCT_REVIEW",scope:"EXACT_STANDALONE_PRODUCT",evidenceReferences:[url]},provenance:{sourceType:"OPERATOR_INSPECTED_PUBLIC_PAGE"},reviewedBy:"forge:trusted-operator",reviewedAt:new Date().toISOString(),status:"ACTIVE",supersedesDestinationId:null,retirementReason:null,createdAt:new Date().toISOString(),createdBy:"forge:trusted-operator"});alert(`Destination saved. Audit: ${result.auditId}`);}catch(error){alert(`Destination was not saved: ${error.message}`);}}
    async editProduct(product){try{const response=await fetch(`/operator-api/product/${encodeURIComponent(product.atlasProductId)}`,{headers:{"X-Forge-Csrf":this.csrf}}),canonical=await response.json();if(!response.ok)throw new Error(canonical.error);const speed=prompt("Speed (MT/s)",canonical.extension.data.performance.dataRateMtps);if(speed===null)return;const voltage=prompt("Rated voltage",canonical.extension.data.electrical.ratedVoltage??"");if(voltage===null)return;canonical.extension.data.performance.dataRateMtps=Number(speed);canonical.extension.data.performance.speedLabel=`${canonical.extension.data.classification.memoryType}-${Number(speed)}`;canonical.extension.data.electrical.ratedVoltage=voltage===""?null:Number(voltage);const expectedRevision=canonical.identity.recordRevision;canonical.identity.recordRevision+=1;canonical.identity.updatedAt=new Date().toISOString();canonical.identity.updatedBy="forge:trusted-operator";const result=await this.operatorRequest("/operator-api/product/edit","EDIT_PRODUCT",{product:canonical,expectedRevision});alert(`Product updated. Audit: ${result.auditId}`);}catch(error){alert(`Product was not changed: ${error.message}`);}}
    validate(model) {
        if (model?.schemaVersion !== "1.0" || model?.projectionType !== "FORGE_PRODUCT_MANAGER" || model?.readOnly !== true || model?.mutationAuthorized !== false || model?.networkOperation !== "NONE" || !Array.isArray(model.products) || model.semantics?.atlasCanonical !== true || model.semantics?.browserMutationProhibited !== true) throw new Error("Not a certified read-only Product Manager projection.");
        return model;
    }
    showLoading() { this.badge.textContent = "LOADING"; this.badge.className = "status-badge pending"; this.summary.textContent = "Loading the certified local product catalog…"; }
    async loadUrl(url) {
        try { const response = await fetch(url, { cache: "no-store" }); if (!response.ok) throw new Error(`Local projection returned HTTP ${response.status}.`); this.apply(this.validate(await response.json())); }
        catch (error) { this.products = []; this.badge.textContent = "LOCAL DATA UNAVAILABLE"; this.badge.className = "status-badge blocked"; this.summary.textContent = `${error.message} Use the manual projection fallback under Settings / Diagnostics.`; this.renderResults(); }
    }
    async load() {
        const file = this.file?.files?.[0]; if (!file) return;
        try { this.apply(this.validate(JSON.parse(await file.text()))); }
        catch (error) { this.products = []; this.badge.textContent = "UNAVAILABLE"; this.badge.className = "status-badge blocked"; this.summary.textContent = error.message; this.renderResults(); }
    }
    apply(model) {
        this.model = model; this.products = model.products; this.page = 1;
        const capacities = [...new Set(this.products.map(product => product.facets.capacityGb).filter(Number.isFinite))].sort((a, b) => a - b);
        const allCapacities = element("option", "", "All capacities"); allCapacities.value = "";
        this.filters.capacity?.replaceChildren(allCapacities, ...capacities.map(capacity => { const option = element("option", "", `${capacity} GB`); option.value = String(capacity); return option; }));
        this.badge.textContent = "CERTIFIED READ-ONLY"; this.badge.className = "status-badge ready";
        this.summary.textContent = `Updated ${new Date(model.asOf).toLocaleString()} · ${model.summary.productCount} products · ${model.summary.destinationCount} destinations · ${model.summary.productsWithCurrent} with Current · ${model.summary.productsWithHistory} with History`;
        this.renderResults(); window.dispatchEvent(new CustomEvent("forge:product-manager-loaded", { detail: model }));
    }
    filtered() { return sortForgeProducts(filterForgeProducts(this.products, { query: this.filters.search?.value ?? "", memory: this.filters.memory?.value ?? "", formFactor: this.filters.formFactor?.value ?? "", capacity: this.filters.capacity?.value ?? "", lifecycle: this.filters.lifecycle?.value ?? "", retailer: this.filters.retailer?.value ?? "" }), this.sort); }
    resetFilters() { Object.values(this.filters).forEach(control => { if (control) control.value = ""; }); this.page = 1; this.renderResults(); }
    renderResults() {
        const products = this.filtered(); this.results.replaceChildren();
        const pages = Math.max(1, Math.ceil(products.length / this.pageSize)); this.page = Math.min(this.page, pages); const start = (this.page - 1) * this.pageSize; const visible = products.slice(start, start + this.pageSize);
        this.results.append(element("p", "product-manager-count", `${products.length} product${products.length === 1 ? "" : "s"}`));
        if (!products.length) { const empty = element("div", "operator-empty-state"); empty.innerHTML = `<strong>No products match these filters</strong><p>The catalog was not changed. Clear filters to search all certified Atlas products.</p>`; const reset = element("button", "secondary-button", "Reset filters"); reset.type = "button"; reset.addEventListener("click", () => this.resetFilters()); empty.append(reset); this.results.append(empty); }
        for (const product of visible) {
            const button = element("button", `product-manager-row${this.selected === product.atlasProductId ? " selected" : ""}`); button.type = "button";
            const title = element("span", "product-row-title"); title.append(element("strong", "", product.displayName), element("small", "", `${product.brand} · ${product.manufacturerPartNumber}`));
            button.append(title, element("span", "product-row-specs", `${value(product.facets.memoryType)} · ${value(product.facets.formFactor)} · ${value(product.facets.capacityGb)} GB`), element("span", "product-row-coverage", `${product.destinations.length} retailer link${product.destinations.length === 1 ? "" : "s"} · ${product.current.available ? "Current available" : "No Current"}`));
            if (product.issues.length) button.append(element("span", "product-manager-warning", product.issues.map(issue => issue === "RETAILER_DESTINATION_MISSING" ? "Retailer destination missing" : issue).join(" · ")));
            button.addEventListener("click", () => { this.selected = product.atlasProductId; this.renderDetails(product); this.renderResults(); window.dispatchEvent(new CustomEvent("forge:product-selected", { detail: product })); }); this.results.append(button);
        }
        if (this.pageStatus) this.pageStatus.textContent = `${products.length ? start + 1 : 0}–${Math.min(start + this.pageSize, products.length)} of ${products.length} · Page ${this.page} of ${pages}`;
        if (this.previous) this.previous.disabled = this.page <= 1; if (this.next) this.next.disabled = this.page >= pages;
    }
    field(label, content, className = "") { const row = element("div", `product-manager-field ${className}`.trim()); row.append(element("strong", "", label), element("span", "", value(content))); return row; }
    coverageCard(title, state, description, positive) { const card = element("article", "coverage-card"); card.append(element("span", "", title), element("strong", positive ? "state-positive" : "state-attention", state), element("small", "", description)); return card; }
    renderDetails(product) {
        this.details.replaceChildren();
        const header = element("header", "product-detail-header"); const title = element("div"); title.append(element("span", "product-brand", product.brand), element("h2", "", product.displayName), element("p", "", `${product.manufacturerPartNumber} · ${product.atlasProductId}`)); header.append(title, element("span", "status-badge ready", product.lifecycleStatus));
        const actions = element("div", "context-actions");
        for (const [label, explanation,handler] of [["Add Product", "Create a validated Atlas draft.",()=>this.dialog?.showModal()], ["Edit Product", "Edit permitted performance fields; stable identity is protected.",()=>this.editProduct(product)], ["Manage Links", "Add a governed canonical destination.",()=>this.addDestination(product)], ["Check Link", "Run bounded server-side verification.",()=>this.checkDestination(product)]]) { const group = element("span", "unavailable-action"); const button = element("button", "secondary-button", label); button.type = "button"; button.disabled = !this.csrf; button.addEventListener("click",handler); const reason = element("small", "", this.csrf?explanation:"Trusted operator runtime is not connected."); group.append(button, reason); actions.append(group); }
        const snapshot = element("section", "product-detail-grid"); snapshot.append(this.field("Capacity", `${product.facets.moduleCount} × ${product.facets.capacityPerModuleGb} GB = ${product.facets.capacityGb} GB`), this.field("Generation", product.facets.memoryType), this.field("Form factor", product.facets.formFactor === "SO_DIMM" ? "SO-DIMM" : product.facets.formFactor), this.field("Speed", product.specifications?.performance?.dataRateMtps ? `${product.specifications.performance.dataRateMtps} MT/s` : null), this.field("Timings", timing(product.specifications)), this.field("Publication", product.publicationStatus));
        const market = element("section", "product-market-grid"); market.append(this.coverageCard("Current price coverage", product.current.available ? "Available" : "Not available", product.current.available ? "Governed Current state is present." : "No qualified Current offer is available.", product.current.available), this.coverageCard("Historical coverage", product.history.available ? `${product.history.observationCount} observations` : "Insufficient history", product.history.available ? "Durable Mercury historical evidence is available." : "No admitted historical observations are available.", product.history.available));
        const links = element("section", "product-manager-detail-section"); const linksTitle = element("div", "section-title"); linksTitle.append(element("h3", "", "Retailer destinations")); links.append(linksTitle);
        if (!product.destinations.length) links.append(element("div", "operator-empty-state", "No active governed retailer destination. This product needs link review before retailer actions can be shown."));
        for (const destination of product.destinations) {
            const card = element("article", "product-manager-link"); const destinationLink = element("a", "destination-link", `Open ${destination.marketplace}`); destinationLink.href = destination.url; destinationLink.target = "_blank"; destinationLink.rel = "noopener noreferrer";
            card.append(this.field("Retailer", destination.marketplace), this.field("Canonical listing", destination.listingId), destinationLink, this.field("Last reviewed", destination.reviewedAt), this.field("Link verification", destination.linkHealth.status));
            const affiliate = element("div", "affiliate-separation"); affiliate.append(element("strong", "", "Affiliate routing")); if (destination.affiliate.url) { const affiliateLink = element("a", "", "Open operator-supplied affiliate link"); affiliateLink.href = destination.affiliate.url; affiliateLink.target = "_blank"; affiliateLink.rel = "noopener noreferrer"; affiliate.append(element("span", "", `${destination.affiliate.status}${destination.affiliate.publicActionPrecedence ? " · public-action precedence" : ""}`), affiliateLink); } else affiliate.append(element("span", "", "No affiliate URL is recorded.")); card.append(affiliate); links.append(card);
        }
        const specifications = element("details", "product-manager-specs"); specifications.append(element("summary", "", "Audit and complete canonical specifications"), element("pre", "", JSON.stringify({ recordRevision: product.recordRevision, capacityInvariantValid: product.capacityInvariantValid, specifications: product.specifications }, null, 2)));
        this.details.append(header, actions, snapshot, market, links, specifications); this.details.scrollIntoView({ behavior: "smooth", block: "start" });
    }
}

export default ProductManagerPanel;
