import crypto from "node:crypto";
import {validateObservation} from "../ObservationValidator.js";
import {validateCanonicalAdmissionAuthorization,canonicalAdmissionCandidateBindingDigest} from "../canonical-admission/CanonicalAdmissionAuthorization.js";
import {canonicalAdmissionMaterialHash} from "../canonical-admission/CanonicalObservationAdmissionPolicy.js";
import {REVIEW_DECISIONS} from "./ObservationReviewDecision.js";

export const CANONICAL_OBSERVATION_REVIEW_POLICY_VERSION="DF004-E2R-1.0";
export const CANONICAL_OBSERVATION_REVIEWED_MEANING="The canonical observation has been examined under Hardware Radar's governed observation-review policy and is acceptable to proceed to independent publication evaluation.";
const stable=value=>{if(Array.isArray(value))return `[${value.map(stable).join(",")}]`;if(value&&typeof value==="object")return `{${Object.keys(value).sort().map(key=>`${JSON.stringify(key)}:${stable(value[key])}`).join(",")}}`;return JSON.stringify(value);};
const hash=value=>crypto.createHash("sha256").update(stable(value)).digest("hex");
const freeze=value=>{if(value&&typeof value==="object"&&!Object.isFrozen(value)){Object.freeze(value);for(const child of Object.values(value))freeze(child);}return value;};
export const canonicalObservationReviewBindingDigest=binding=>hash(binding);

const result=({observationId,decision,binding=null,anomalies=[],blockers=[]}={})=>{const decisionEligible=blockers.length===0&&(decision!==REVIEW_DECISIONS.REVIEWED||anomalies.length===0),reasons=[...blockers,...(decision===REVIEW_DECISIONS.REVIEWED?anomalies:[])];return freeze({schemaVersion:"1.0",assessmentType:"CANONICAL_OBSERVATION_REVIEW",assessmentId:`mer_revassess_${hash({policyVersion:CANONICAL_OBSERVATION_REVIEW_POLICY_VERSION,binding,decision,reasons}).slice(0,24)}`,policyVersion:CANONICAL_OBSERVATION_REVIEW_POLICY_VERSION,reviewedMeaning:CANONICAL_OBSERVATION_REVIEWED_MEANING,observationId,proposedDecision:decision,reviewable:blockers.length===0,decisionEligible,binding,anomalies:[...anomalies],blockers:decisionEligible?[]:reasons,reviewApproved:false,publicationEligible:false,publicationAuthority:false,currentPriceAuthority:false,livePriceAuthority:false,publicPriceAuthority:false,cheapestAuthority:false,pickAuthority:false,mutationAuthorized:false,networkOperation:"NONE",paidTaskCreated:false,actualSpendUsd:0});};

export class CanonicalObservationReviewAssessmentService{
  constructor({acceptanceRepository,reviewService,reviewRepository,canonicalAdmissionService,canonicalAuthorizationRepository}={}){if(!acceptanceRepository?.getById||!acceptanceRepository?.getAuditById||!reviewService?.getReviewItem||!reviewRepository?.getEffectiveDecision||!canonicalAdmissionService?.assess||!canonicalAuthorizationRepository?.getAll||!canonicalAuthorizationRepository?.getAllConsumptions)throw new TypeError("CANONICAL_REVIEW_ASSESSMENT_DEPENDENCY_REQUIRED");Object.assign(this,{acceptanceRepository,reviewService,reviewRepository,canonicalAdmissionService,canonicalAuthorizationRepository});}
  async assess({observationId,decision,asOf=new Date().toISOString()}={}){
    if(typeof observationId!=="string"||!observationId.trim()||!Object.values(REVIEW_DECISIONS).includes(decision)||!Number.isFinite(Date.parse(asOf)))return result({observationId,decision,blockers:["CANONICAL_REVIEW_INPUT_INVALID"]});
    const [observation,audit,reviewItem,effective,authorizations,consumptions]=await Promise.all([this.acceptanceRepository.getById(observationId,{asOf}),this.acceptanceRepository.getAuditById(observationId),this.reviewService.getReviewItem(observationId,{asOf}),this.reviewRepository.getEffectiveDecision(observationId),this.canonicalAuthorizationRepository.getAll(),this.canonicalAuthorizationRepository.getAllConsumptions()]);
    const blockers=[],anomalies=[];if(!observation||!audit||reviewItem?.status!=="AVAILABLE"||reviewItem?.reviewable!==true)blockers.push("CANONICAL_REVIEW_OBSERVATION_NOT_REVIEWABLE");
    const matchingConsumptions=consumptions.filter(item=>item?.observationId===observationId),consumption=matchingConsumptions[0]??null,authorization=consumption?authorizations.find(item=>item.authorizationId===consumption.authorizationId):null;
    if(matchingConsumptions.length!==1||!authorization||!validateCanonicalAdmissionAuthorization(authorization).valid||consumption?.status!=="CANONICAL_ADMITTED")blockers.push("CANONICAL_REVIEW_E2Q_CONSUMPTION_INVALID");
    const evidenceId=authorization?.evidenceId??null,e2p=evidenceId?await this.canonicalAdmissionService.assess({evidenceId}):null;
    if(!e2p||e2p.assessmentType!=="CANONICAL_OBSERVATION_ADMISSION")blockers.push("CANONICAL_REVIEW_E2P_ASSESSMENT_MISSING");
    else if(e2p.canonicalEligible!==true)anomalies.push(...(e2p.blockers?.length?e2p.blockers:["CANONICAL_REVIEW_E2P_NOT_ELIGIBLE"]));
    if(observation&&!validateObservation(observation).valid)anomalies.push("CANONICAL_REVIEW_OBSERVATION_INVALID");if(audit?.storage?.storageClass!=="DURABLE"||audit?.storage?.payloadStatus!=="ACTIVE")anomalies.push("CANONICAL_REVIEW_DURABLE_PAYLOAD_INVALID");
    const certified=e2p?.candidateBinding,authBinding=authorization?.candidateBinding;if(certified&&authorization&&(authorization.assessmentId!==e2p.assessmentId||authorization.policyVersion!==e2p.policyVersion||authorization.candidateBindingDigest!==canonicalAdmissionCandidateBindingDigest(certified)||stable(authBinding)!==stable(certified)))anomalies.push("CANONICAL_REVIEW_E2P_E2Q_BINDING_MISMATCH");
    if(observation&&certified&&(observation.atlasProductId!==certified.atlasProductId||observation.retailerId!==certified.retailerId))anomalies.push("CANONICAL_REVIEW_IDENTITY_SUBSTITUTION");
    if(observation&&certified&&(observation.compliance?.licenseContext!==certified.source||observation.provenance?.acquisition?.requestId!==certified.providerTaskId||observation.provenance?.acquisition?.rawPayloadReference!==certified.rawPayloadReference))anomalies.push("CANONICAL_REVIEW_PROVENANCE_SUBSTITUTION");
    const binding=authorization&&e2p&&observation&&audit?freeze({observationId,canonicalIdempotencyKey:`E2P_CANONICAL_ADMISSION:${evidenceId}`,evidenceId,atlasProductId:certified?.atlasProductId??null,retailerId:certified?.retailerId??null,provider:certified?.provider??null,source:certified?.source??null,providerTaskId:certified?.providerTaskId??null,rawPayloadReference:certified?.rawPayloadReference??null,observationDigest:canonicalAdmissionMaterialHash(observation),auditDigest:canonicalAdmissionMaterialHash(audit),evidenceHash:certified?.evidenceHash??null,historicalObservationId:certified?.historicalObservationId??null,historicalObservationHash:certified?.historicalObservationHash??null,rightsProfileHash:certified?.rightsProfileHash??null,e2pAssessmentId:e2p.assessmentId,e2pPolicyVersion:e2p.policyVersion,e2qAuthorizationId:authorization.authorizationId,e2qAuthorizationDigest:canonicalAdmissionMaterialHash(authorization),e2qConsumptionDigest:canonicalAdmissionMaterialHash(consumption),proposedDecision:decision,effectiveReviewDecisionId:effective?.reviewDecisionId??null,effectiveReviewDecisionDigest:effective?canonicalAdmissionMaterialHash(effective):null,e2rPolicyVersion:CANONICAL_OBSERVATION_REVIEW_POLICY_VERSION}):null;
    if(!binding)blockers.push("CANONICAL_REVIEW_BINDING_INCOMPLETE");return result({observationId,decision,binding,anomalies:[...new Set(anomalies)],blockers:[...new Set(blockers)]});
  }
}
