import {assertCanonicalObservationReviewAuthorization,assertCanonicalObservationReviewConfirmation,createCanonicalObservationReviewAuthorization} from "./CanonicalObservationReviewAuthorization.js";
const exact=(input,allowed,code)=>{for(const key of Object.keys(input??{}))if(!allowed.includes(key))throw new Error(`${code}:${key}`);return input??{};};
const required=(value,code)=>{if(typeof value!=="string"||!value.trim())throw new TypeError(code);return value.trim();};
const separation={canonicalObservationModified:false,reviewDecisionRecorded:true,publicationEligible:false,publicationAuthority:false,currentPriceAuthority:false,livePriceAuthority:false,publicPriceAuthority:false,cheapestAuthority:false,pickAuthority:false,networkOperation:"NONE",paidTaskCreated:false,actualSpendUsd:0};

export class CanonicalObservationReviewPrepareService{
  constructor({assessmentService,authorizationRepository,now=()=>new Date().toISOString()}={}){if(!assessmentService?.assess||!authorizationRepository?.record)throw new TypeError("CANONICAL_REVIEW_PREPARE_DEPENDENCY_REQUIRED");Object.assign(this,{assessmentService,authorizationRepository,now});}
  async prepare(input={}){exact(input,["observationId","decision","reviewedBy","reason","reasonCodes","notes","ttlMinutes"],"CANONICAL_REVIEW_PREPARE_CALLER_SUBSTITUTION_FORBIDDEN");const preparedAt=this.now(),assessment=await this.assessmentService.assess({observationId:required(input.observationId,"CANONICAL_REVIEW_OBSERVATION_ID_REQUIRED"),decision:input.decision,asOf:preparedAt}),authorization=createCanonicalObservationReviewAuthorization({assessment,reviewedBy:input.reviewedBy,reason:input.reason,reasonCodes:input.reasonCodes??[],notes:input.notes??"",preparedAt,ttlMinutes:input.ttlMinutes??15});return this.authorizationRepository.record(authorization);}
}

export class CanonicalObservationReviewExecutor{
  constructor({assessmentService,authorizationRepository,reviewWorkflowService,now=()=>new Date().toISOString()}={}){if(!assessmentService?.assess||!authorizationRepository?.getById||!authorizationRepository?.getConsumption||!authorizationRepository?.consume||!reviewWorkflowService?.record)throw new TypeError("CANONICAL_REVIEW_EXECUTOR_DEPENDENCY_REQUIRED");Object.assign(this,{assessmentService,authorizationRepository,reviewWorkflowService,now});}
  async execute(input={}){exact(input,["authorizationId","confirmation","executedBy"],"CANONICAL_REVIEW_EXECUTE_CALLER_SUBSTITUTION_FORBIDDEN");assertCanonicalObservationReviewConfirmation(input.confirmation);const id=required(input.authorizationId,"CANONICAL_REVIEW_AUTHORIZATION_ID_REQUIRED"),operator=required(input.executedBy,"CANONICAL_REVIEW_EXECUTED_BY_REQUIRED"),authorization=await this.authorizationRepository.getById(id);if(!authorization)throw new Error("CANONICAL_REVIEW_AUTHORIZATION_NOT_FOUND");if(operator!==authorization.reviewedBy)throw new Error("CANONICAL_REVIEW_OPERATOR_SUBSTITUTION_BLOCKED");const consumed=await this.authorizationRepository.getConsumption(id);if(consumed)return Object.freeze({status:"ALREADY_CONSUMED",authorizationId:id,reviewDecisionId:consumed.reviewDecisionId,observationId:authorization.observationId,decision:authorization.decision,...separation});const reviewedAt=this.now(),assessment=await this.assessmentService.assess({observationId:authorization.observationId,decision:authorization.decision,asOf:reviewedAt});assertCanonicalObservationReviewAuthorization({authorization,assessment,now:reviewedAt});const decision=await this.reviewWorkflowService.record({observationId:authorization.observationId,decision:authorization.decision,reviewedBy:authorization.reviewedBy,reviewedAt,reasonCodes:authorization.reasonCodes,notes:authorization.notes,governance:{policyVersion:authorization.policyVersion,authorizationId:id,candidateBindingDigest:authorization.candidateBindingDigest,predecessorReviewDecisionId:authorization.candidateBinding.effectiveReviewDecisionId}}),recorded=await this.authorizationRepository.consume({authorizationId:id,candidateBindingDigest:authorization.candidateBindingDigest,reviewDecisionId:decision.reviewDecisionId});return Object.freeze({status:recorded.status==="ALREADY_CONSUMED"?"ALREADY_CONSUMED":"REVIEW_DECISION_RECORDED",authorizationId:id,reviewDecisionId:decision.reviewDecisionId,observationId:authorization.observationId,decision:authorization.decision,...separation});}
}
