import {projectIdentityReviewState} from "./IdentityReviewProjection.js";

const freeze=value=>{if(value&&typeof value==="object"&&!Object.isFrozen(value)){Object.freeze(value);for(const child of Object.values(value))freeze(child);}return value;};
const identity=value=>({productId:value?.productId??null,dataDocId:value?.dataDocId??null,gid:value?.gid??null});
const same=(left,right)=>JSON.stringify(left)===JSON.stringify(right);

export function resolveGovernedIdentityReuseLineage({record,reuse,historicalObservations=[],evidenceRecords=[],decisions=[],remediations=[],atlasRetailers=[]}={}){
 if(!record?.evidenceId||!reuse||!Array.isArray(historicalObservations)||!Array.isArray(evidenceRecords)||!Array.isArray(decisions)||!Array.isArray(remediations)||!Array.isArray(atlasRetailers))throw new TypeError("GOVERNED_IDENTITY_REUSE_LINEAGE_INPUT_INVALID");
 if(reuse.status!=="APPLICABLE"||reuse.targetEvidenceId!==record.evidenceId||reuse.atlasProductId!==record.candidate?.identity?.atlasProductId||reuse.compatibility?.product!==true||reuse.compatibility?.merchant!==true||reuse.compatibility?.providerIdentity!==true)throw new Error("GOVERNED_IDENTITY_REUSE_TARGET_INVALID");
 if(!same(identity(reuse.providerIdentity),identity(record.candidate?.marketEvidence?.productEvidence)))throw new Error("GOVERNED_IDENTITY_REUSE_PROVIDER_DRIFT");
 const visited=new Set(),lineage=[];let sourceEvidenceId=reuse.sourceEvidenceId;
 while(sourceEvidenceId){if(visited.has(sourceEvidenceId))throw new Error("GOVERNED_IDENTITY_REUSE_LINEAGE_CYCLE");visited.add(sourceEvidenceId);const matches=evidenceRecords.filter(value=>value?.evidenceId===sourceEvidenceId);if(matches.length!==1)throw new Error(matches.length?"GOVERNED_IDENTITY_REUSE_SOURCE_AMBIGUOUS":"GOVERNED_IDENTITY_REUSE_SOURCE_MISSING");const source=matches[0],direct=projectIdentityReviewState({record:source,decisions,remediations,atlasRetailers});
  if(source.candidate?.identity?.atlasProductId!==record.candidate?.identity?.atlasProductId)throw new Error("GOVERNED_IDENTITY_REUSE_PRODUCT_MISMATCH");
  if(direct.product?.state==="VERIFIED"&&direct.merchant?.state==="REGISTERED"){
   if(direct.product.decisionId!==reuse.product?.decisionId||(direct.product.remediationId??null)!==(reuse.product?.remediationId??null))throw new Error("GOVERNED_IDENTITY_REUSE_PRODUCT_DECISION_MISMATCH");if(direct.merchant.decisionId!==reuse.merchant?.decisionId||direct.merchant.merchantId!==reuse.merchant?.retailerId)throw new Error("GOVERNED_IDENTITY_REUSE_MERCHANT_DECISION_MISMATCH");lineage.push({kind:"DIRECT_REVIEW",evidenceId:sourceEvidenceId,productDecisionId:direct.product.decisionId,productRemediationId:direct.product.remediationId??null,merchantDecisionId:direct.merchant.decisionId,retailerId:direct.merchant.merchantId});return freeze({projection:{projectionVersion:"1.0",evidenceId:record.evidenceId,product:{...direct.product,atlasProductId:record.candidate.identity.atlasProductId},merchant:{...direct.merchant,atlasResolution:reuse.merchant.atlasResolution},retainedEvidenceModified:false},lineage});
  }
  const observations=historicalObservations.filter(value=>value?.provenance?.retainedEvidenceId===sourceEvidenceId);if(observations.length!==1)throw new Error(observations.length?"GOVERNED_IDENTITY_REUSE_LINEAGE_BRANCH":"GOVERNED_IDENTITY_REUSE_LINEAGE_MISSING");const observation=observations[0],acquisition=observation.provenance?.acquisition,review=observation.provenance?.identityReview??{};if(acquisition?.type!=="HISTORICAL_REFRESH"||!acquisition.sourceEvidenceId||!acquisition.identityReuseAssessmentId)throw new Error(direct.product?.state!=="VERIFIED"?"GOVERNED_IDENTITY_REUSE_PRODUCT_DECISION_INEFFECTIVE":"GOVERNED_IDENTITY_REUSE_MERCHANT_DECISION_INEFFECTIVE");if(observation.atlasProductId!==record.candidate.identity.atlasProductId||observation.retailerId!==reuse.merchant?.retailerId)throw new Error("GOVERNED_IDENTITY_REUSE_LINEAGE_SUBJECT_MISMATCH");if(review.productDecisionId!==reuse.product?.decisionId||(review.productRemediationId??null)!==(reuse.product?.remediationId??null)||review.merchantDecisionId!==reuse.merchant?.decisionId)throw new Error("GOVERNED_IDENTITY_REUSE_LINEAGE_DECISION_MISMATCH");if(!same(identity(acquisition.providerIdentity),identity(source.candidate?.marketEvidence?.productEvidence)))throw new Error("GOVERNED_IDENTITY_REUSE_PROVIDER_DRIFT");lineage.push({kind:"HISTORICAL_REFRESH_REUSE",evidenceId:sourceEvidenceId,sourceEvidenceId:acquisition.sourceEvidenceId,reuseAssessmentId:acquisition.identityReuseAssessmentId,productDecisionId:review.productDecisionId,productRemediationId:review.productRemediationId??null,merchantDecisionId:review.merchantDecisionId,retailerId:observation.retailerId});sourceEvidenceId=acquisition.sourceEvidenceId;
 }
 throw new Error("GOVERNED_IDENTITY_REUSE_LINEAGE_MISSING");
}

export default resolveGovernedIdentityReuseLineage;
