import assert from "node:assert/strict";
import {execFileSync} from "node:child_process";
import {createHash} from "node:crypto";
import {inspect} from "node:util";
import {mkdtemp, readFile, readdir} from "node:fs/promises";
import {tmpdir} from "node:os";
import path from "node:path";
import {CloudflareEmailServiceProviderConfigurationRepository,createGatewayCloudflareVerificationOperatorInput,FileGatewayAlertRecipientVerificationAuthorizationRepository,GatewayAlertOperatorRecipientApprovalRepository,GatewayAlertRecipientVerificationExecutor,GatewayAlertRecipientVerificationPrepareService} from "../index.js";

const accountId="fixture_account_df005t_0123456789",apiToken="fixture-token-df005t-0123456789-abcdefghijklmnopqrstuvwxyz",recipient="df005t.approved.fixture@example.test",runtimeValues={CLOUDFLARE_ACCOUNT_ID:accountId,CLOUDFLARE_API_TOKEN:apiToken,BEACON_ALERT_RECIPIENT:recipient};
const input=createGatewayCloudflareVerificationOperatorInput(runtimeValues);assert.equal(input.accountIdentifierSource,"EPHEMERAL_OPERATOR_INPUT");assert.equal(input.apiTokenSource,"EPHEMERAL_OPERATOR_SECRET");assert.equal(input.recipientSource,"SERVER_SIDE_RUNTIME");assert.equal(input.accountIdentifierConfigured,true);assert.equal(input.apiTokenConfigured,true);assert.equal(input.recipientConfigured,true);assert.deepEqual(input.withRuntimeConfiguration(value=>value),runtimeValues);for(const rendered of [JSON.stringify(input),inspect(input),JSON.stringify(structuredClone(input))])for(const value of [accountId,apiToken,recipient])assert.equal(rendered.includes(value),false);for(const invalid of [{...runtimeValues,unknown:"value"},{...runtimeValues,CLOUDFLARE_ACCOUNT_ID:"bad account"},{...runtimeValues,CLOUDFLARE_API_TOKEN:"short"},{...runtimeValues,BEACON_ALERT_RECIPIENT:"invalid"}])assert.throws(()=>createGatewayCloudflareVerificationOperatorInput(invalid),/INVALID/);

const root=await mkdtemp(path.join(tmpdir(),"hr-df005t-")),repository=new FileGatewayAlertRecipientVerificationAuthorizationRepository({filePath:path.join(root,"authorizations.json")}),approvalRepository=new GatewayAlertOperatorRecipientApprovalRepository(),providerConfigurationRepository=new CloudflareEmailServiceProviderConfigurationRepository(),[approval,providerConfiguration]=await Promise.all([approvalRepository.getApproval(),providerConfigurationRepository.getConfiguration()]),service=new GatewayAlertRecipientVerificationPrepareService({approvalRepository,providerConfigurationRepository,authorizationRepository:repository,now:()=>"2026-08-25T15:00:00.000Z"}),prepared=await input.withRuntimeConfiguration(runtimeConfiguration=>service.prepare({runtimeConfiguration}));assert.equal(prepared.status,"PREPARED");assert.equal(prepared.verificationRuntimeReady,true);assert.equal(prepared.currentVerification,"PENDING_VERIFICATION");assert.equal(prepared.sendingEnabled,false);assert.match(prepared.authorization.accountIdentifierDigest,/^[a-f0-9]{64}$/);assert.match(prepared.authorization.destinationDigest,/^[a-f0-9]{64}$/);const serializedAuthorization=JSON.stringify(prepared.authorization);for(const value of [accountId,apiToken,recipient])assert.equal(serializedAuthorization.includes(value),false);
for(const missing of [{CLOUDFLARE_API_TOKEN:apiToken,BEACON_ALERT_RECIPIENT:recipient},{CLOUDFLARE_ACCOUNT_ID:accountId,BEACON_ALERT_RECIPIENT:recipient},{CLOUDFLARE_ACCOUNT_ID:accountId,CLOUDFLARE_API_TOKEN:apiToken}]){const result=await service.prepare({runtimeConfiguration:missing});assert.equal(result.status,"BLOCKED");assert.equal(result.authorization,null);}

let credentialLoads=0,clientConstructions=0,providerCalls=0;const executor=new GatewayAlertRecipientVerificationExecutor({authorizationRepository:repository,now:()=>"2026-08-25T15:01:00.000Z",credentialLoader:async()=>{credentialLoads+=1;return {accountId,apiToken};},clientFactory:credentials=>{clientConstructions+=1;assert.deepEqual(credentials,{accountId,apiToken});return {requestDestinationVerification:async({recipientAddress})=>{providerCalls+=1;assert.equal(recipientAddress,recipient);return {status:"FIXTURE_VERIFICATION_REQUESTED",providerDestinationReference:"fixture-only",providerVerifiedAt:null};}};}});await assert.rejects(()=>executor.execute({authorization:prepared.authorization,confirmationToken:"incorrect",approval,providerConfiguration,runtimeConfiguration:runtimeValues}),/EXPLICIT_CONFIRMATION_REQUIRED/);assert.equal(credentialLoads,0);assert.equal(clientConstructions,0);assert.equal(providerCalls,0);for(const substituted of [{...runtimeValues,BEACON_ALERT_RECIPIENT:"df005t.substitute.fixture@example.test"},{...runtimeValues,CLOUDFLARE_ACCOUNT_ID:"fixture_account_substitute_012345"}])await assert.rejects(()=>executor.execute({authorization:prepared.authorization,confirmationToken:"VERIFY-ALERT-RECIPIENT",approval,providerConfiguration,runtimeConfiguration:substituted}),/BINDING_INVALID/);assert.equal(credentialLoads,0);assert.equal(clientConstructions,0);assert.equal(providerCalls,0);const executed=await executor.execute({authorization:prepared.authorization,confirmationToken:"VERIFY-ALERT-RECIPIENT",approval,providerConfiguration,runtimeConfiguration:runtimeValues});assert.equal(executed.status,"FIXTURE_VERIFICATION_REQUESTED");assert.equal(executed.recipientVerified,false);assert.equal(executed.sendingEnabled,false);assert.equal(executed.automaticRetry,false);assert.equal(credentialLoads,1);assert.equal(clientConstructions,1);assert.equal(providerCalls,1);

const diagnostic=execFileSync(process.execPath,["scripts/beacon-gateway-cloudflare-verification-credential-status.mjs"],{cwd:process.cwd(),encoding:"utf8",env:{}});assert.match(diagnostic,/Account identifier source:\s+EPHEMERAL_OPERATOR_INPUT/);assert.match(diagnostic,/API token source:\s+EPHEMERAL_OPERATOR_SECRET/);assert.match(diagnostic,/Verification runtime ready:\s+NO/);assert.match(diagnostic,/Secrets displayed:\s+NO/);assert.match(diagnostic,/Network request:\s+NONE/);assert.match(diagnostic,/Actual spend:\s+\$0\.000/);for(const value of [accountId,apiToken,recipient])assert.equal(diagnostic.includes(value),false);
const sources=await Promise.all([readFile(new URL("../GatewayCloudflareVerificationOperatorInput.js",import.meta.url),"utf8"),readFile(new URL("../../../scripts/beacon-gateway-alert-recipient-verification-operator.ps1",import.meta.url),"utf8"),readFile(new URL("../../../scripts/beacon-gateway-alert-recipient-verification-execute.mjs",import.meta.url),"utf8")]);assert.equal(sources.some(source=>source.includes("--api-token")),false);assert.equal(sources.some(source=>source.includes("--env-file")||source.includes("dotenv")),false);assert.match(sources[1],/Read-Host[^\n]+-AsSecureString/);assert.match(sources[1],/STOP: review the authorization/);
async function publicText(directory){let result="";for(const entry of await readdir(directory,{withFileTypes:true})){const url=new URL(entry.name+(entry.isDirectory()?"/":""),directory);result+=entry.isDirectory()?await publicText(url):await readFile(url,"utf8").catch(()=>"");}return result;}const publicOutput=await publicText(new URL("../../../public/",import.meta.url));for(const value of [accountId,apiToken,recipient])assert.equal(publicOutput.includes(value),false);
const protectedFiles=new Map([["../../beacon/retention/policies/first-party-product-interest-90-day-policy.json","eef0df6f74e53d2537e49795778643436a69c63ddb17fdaba6e580480973029b"],["../policies/beacon-product-interest-abuse-control-policy.json","2ff1b0a35e8455961bf62176384aebc26ac991a2562ef2a5e00bdd8b6dada52a"],["../policies/beacon-gateway-operational-monitoring-policy.json","9a68f613f7eac5018352623a79ab1d8b3547778ef84f09c8bf348e940b3ea975"],["../policies/cloudflare-workers-logs-monitoring-destination.json","3598bb5492b32e9d98d3365aaa0eceff6860e33fdfa6603f330bf8a4625cd194"],["../policies/beacon-gateway-operational-alert-policy.json","87e524129ab9085d8c1ceb3c7fc7e2e9783c105a9e2596009f94d658636f5fd2"],["../policies/beacon-gateway-alert-notification-policy.json","e822605f1886cf167dcee595e05d29b28e51ab036d0011828ea09fe2b6099573"],["../policies/cloudflare-email-service-provider.json","755b0c26a55ad43a08cd9183e39752d4b529853a675524133a5dd3706b5957b6"],["../policies/gateway-alert-operator-recipient.json","7386f4bb9a649166ca033f78cad601f5744ac4acb54e901b0d55f52eb62456e3"],["../policies/gateway-alert-operator-recipient-approval.json","1a1bae1278850c2416a00b06f83f12e1654ec30e9cfd10fca4cc14bd21a988df"],["../../mercury/historical-refresh/policies/initial-production-policy.json","a99900fc9e30fd6c31beb721b078163be463efe4fecc84cf9a3e1654ead3d1f2"]]);for(const [file,expected] of protectedFiles)assert.equal(createHash("sha256").update(await readFile(new URL(file,import.meta.url))).digest("hex"),expected);console.log("Gateway Cloudflare verification operator-input tests passed.");
