import { mkdir, readFile, rename, writeFile } from "node:fs/promises";
import { dirname, resolve } from "node:path";
import { FileSingleWriterRunLock, SINGLE_WRITER_LOCK_STATUSES } from "../../runtime/FileSingleWriterRunLock.js";
import { validatePublicationAuthorization } from "../PublicationOperatorAuthorization.js";
const initial = () => ({ version: "1.0", authorizations: {}, byIntent: {}, consumptions: {} }), clone = structuredClone, freeze = Object.freeze;
const intentKey = value => `${value.observationId}:${value.decision}:${value.candidateBinding.predecessorPublicationDecisionId ?? "NONE"}`;
export class FilePublicationAuthorizationRepository {
  constructor({ statePath, now = () => new Date().toISOString(), runLock } = {}) { if (!statePath) throw new TypeError("statePath is required."); this.statePath = resolve(statePath); this.now = now; this.queue = Promise.resolve(); this.runLock = runLock ?? new FileSingleWriterRunLock({ lockPath: `${this.statePath}.lock`, now }); }
  async _locked(fn) { const run = async () => { const result = await this.runLock.runExclusive(fn); if (result.status !== SINGLE_WRITER_LOCK_STATUSES.COMPLETED) throw new Error("PUBLICATION_AUTHORIZATION_REPOSITORY_BUSY"); return result.result; }, task = this.queue.then(run, run); this.queue = task.catch(() => {}); return task; }
  async _read() { try { const state = JSON.parse(await readFile(this.statePath, "utf8")); if (state?.version !== "1.0" || !state.authorizations || !state.byIntent || !state.consumptions) throw new Error(); for (const [id, value] of Object.entries(state.authorizations)) if (id !== value.authorizationId || !validatePublicationAuthorization(value).valid) throw new Error(); return state; } catch (error) { if (error?.code === "ENOENT") return initial(); throw new Error("PUBLICATION_AUTHORIZATION_STATE_INVALID"); } }
  async _commit(state) { await mkdir(dirname(this.statePath), { recursive: true }); const temp = `${this.statePath}.tmp-${process.pid}-${Date.now()}`; await writeFile(temp, `${JSON.stringify(state, null, 2)}\n`); await rename(temp, this.statePath); }
  async record(authorization) { const report = validatePublicationAuthorization(authorization); if (!report.valid) throw new TypeError(report.errors.join(",")); return this._locked(async () => { const state = await this._read(), key = intentKey(authorization), prior = state.byIntent[key]; if (prior) { const existing = state.authorizations[prior]; if (existing.authorizationId === authorization.authorizationId) return freeze(clone(existing)); throw new Error("PUBLICATION_AUTHORIZATION_CONFLICT"); } state.authorizations[authorization.authorizationId] = clone(authorization); state.byIntent[key] = authorization.authorizationId; await this._commit(state); return freeze(clone(authorization)); }); }
  async getById(id) { const value = (await this._read()).authorizations[id]; return value ? freeze(clone(value)) : null; }
  async getConsumption(id) { const value = (await this._read()).consumptions[id]; return value ? freeze(clone(value)) : null; }
  async consume({ authorizationId, candidateBindingDigest, publicationDecisionId }) { return this._locked(async () => { const state = await this._read(), auth = state.authorizations[authorizationId]; if (!auth) throw new Error("PUBLICATION_AUTHORIZATION_NOT_FOUND"); if (auth.candidateBindingDigest !== candidateBindingDigest) throw new Error("PUBLICATION_AUTHORIZATION_CONSUMPTION_CONFLICT"); const prior = state.consumptions[authorizationId]; if (prior) { if (prior.publicationDecisionId !== publicationDecisionId || prior.candidateBindingDigest !== candidateBindingDigest) throw new Error("PUBLICATION_AUTHORIZATION_CONSUMPTION_CONFLICT"); return freeze({ status: "ALREADY_CONSUMED", consumption: clone(prior) }); } const consumption = { schemaVersion: "1.0", authorizationId, candidateBindingDigest, publicationDecisionId, consumedAt: this.now() }; state.consumptions[authorizationId] = consumption; await this._commit(state); return freeze({ status: "CONSUMED", consumption: clone(consumption) }); }); }
}
