import crypto from "node:crypto";

export const EXISTING_TASK_SUPERVISION_POLICY_VERSION="MERCURY-EXISTING-TASK-SUPERVISION-1.0";
export const EXISTING_TASK_POLL_INTERVAL_MS=15*60*1000;
export const EXISTING_TASK_REVIEW_THRESHOLD_MS=6*60*60*1000;
export const EXISTING_TASK_RESULT_RETENTION_DAYS=30;
export const EXISTING_TASK_SUPERVISION_STATES=Object.freeze({PENDING:"PENDING_PROVIDER",DUE:"CHECK_DUE",WAITING:"WAITING_UNTIL_NEXT_CHECK",REVIEW:"OPERATOR_REVIEW_REQUIRED",TERMINAL:"PROVIDER_TERMINAL_FAILURE",AVAILABLE:"RESULT_AVAILABLE",COMPLETED:"COMPLETED"});
const freeze=value=>Object.freeze(structuredClone(value));
const need=(value,code)=>{if(typeof value!=="string"||!value.trim())throw new Error(code);return value.trim();};
const time=(value,code)=>{const result=need(value,code);if(!Number.isFinite(Date.parse(result)))throw new Error(code);return result;};
const plus=(value,ms)=>new Date(Date.parse(value)+ms).toISOString();
const supervisionId=taskId=>`mer_tasksupervision_${crypto.createHash("sha256").update(taskId).digest("hex").slice(0,24)}`;

export class ExistingProviderTaskSupervisionService{
 constructor({repository,checkExistingTask=null,now=()=>new Date().toISOString(),pollIntervalMs=EXISTING_TASK_POLL_INTERVAL_MS,reviewThresholdMs=EXISTING_TASK_REVIEW_THRESHOLD_MS}={}){for(const method of["getRun","recordTaskSupervision","listTaskSupervisions","claimDueTaskSupervisions","completeTaskSupervisionAttempt"])if(typeof repository?.[method]!=="function")throw new Error("EXISTING_TASK_SUPERVISION_REPOSITORY_REQUIRED");if(checkExistingTask!==null&&typeof checkExistingTask!=="function")throw new Error("EXISTING_TASK_SUPERVISION_CHECK_INVALID");if(!Number.isInteger(pollIntervalMs)||pollIntervalMs<60000||!Number.isInteger(reviewThresholdMs)||reviewThresholdMs<=pollIntervalMs)throw new Error("EXISTING_TASK_SUPERVISION_POLICY_INVALID");Object.assign(this,{repository,checkExistingTask,now,pollIntervalMs,reviewThresholdMs});}
 bootstrap({runId}={}){const run=this.repository.getRun(need(runId,"EXISTING_TASK_SUPERVISION_RUN_REQUIRED"));if(!run)throw new Error("EXISTING_TASK_SUPERVISION_RUN_NOT_FOUND");const at=time(this.now(),"EXISTING_TASK_SUPERVISION_TIME_INVALID"),records=[];for(const member of run.members.filter(value=>value.state==="WAITING_FOR_PROVIDER")){if(member.paidTaskCreated!==true||!member.providerTaskId)throw new Error("EXISTING_TASK_SUPERVISION_LINEAGE_INVALID");const record={schemaVersion:"1.0",policyVersion:EXISTING_TASK_SUPERVISION_POLICY_VERSION,supervisionId:supervisionId(member.providerTaskId),providerTaskId:member.providerTaskId,source:member.source,operation:member.operation,runId:run.runId,memberKey:member.memberKey,domainMemberId:member.domainMemberId,atlasProductId:member.atlasProductId,firstKnownAt:at,providerCreatedAt:null,supervisionStartedAt:at,historicalAttemptsKnown:false,attemptCountSinceSupervision:0,lastRetrievalAttemptAt:null,latestProviderStatus:null,latestProviderStatusCode:null,latestProviderStatusMessage:null,nextEligibleCheckAt:at,supervisionState:EXISTING_TASK_SUPERVISION_STATES.DUE,operatorReviewState:"NOT_REQUIRED",operatorReviewReason:null,terminalReason:null,lease:null,paidTaskCreated:false,actualSpendUsd:0};records.push(this.repository.recordTaskSupervision(record).value);}return freeze({runId:run.runId,records,providerCalls:0,newPaidTasks:0,actualSpendUsd:0});}
 inspect({runId}={}){const at=time(this.now(),"EXISTING_TASK_SUPERVISION_TIME_INVALID"),records=this.repository.listTaskSupervisions(need(runId,"EXISTING_TASK_SUPERVISION_RUN_REQUIRED")).map(record=>this.#project(record,at));return freeze({runId,asOf:at,pending:records.filter(x=>["PENDING_PROVIDER","CHECK_DUE","WAITING_UNTIL_NEXT_CHECK"].includes(x.supervisionState)).length,due:records.filter(x=>x.supervisionState==="CHECK_DUE").length,reviewRequired:records.filter(x=>x.supervisionState==="OPERATOR_REVIEW_REQUIRED").length,terminalFailures:records.filter(x=>x.supervisionState==="PROVIDER_TERMINAL_FAILURE").length,records,readOnly:true,networkOperation:"NONE"});}
 async supervise({runId,maxChecks}={}){if(!this.checkExistingTask)throw new Error("EXISTING_TASK_SUPERVISION_CHECK_REQUIRED");if(!Number.isInteger(maxChecks)||maxChecks<1)throw new Error("EXISTING_TASK_SUPERVISION_MAX_CHECKS_INVALID");const at=time(this.now(),"EXISTING_TASK_SUPERVISION_TIME_INVALID"),leaseId=crypto.randomUUID(),claimed=this.repository.claimDueTaskSupervisions({runId,asOf:at,limit:maxChecks,leaseId,leaseExpiresAt:plus(at,5*60*1000)});let checks=0;for(const record of claimed){let outcome;try{outcome=await this.checkExistingTask({runId,memberKey:record.memberKey,providerTaskId:record.providerTaskId});}catch(error){outcome={classification:"OTHER_REVIEW_REQUIRED",statusCode:error?.providerStatusCode??null,statusMessage:error?.providerStatusMessage??null,reason:String(error?.message??error)};}const attemptedAt=time(this.now(),"EXISTING_TASK_SUPERVISION_TIME_INVALID"),classification=outcome?.classification??"OTHER_REVIEW_REQUIRED",old=Date.parse(attemptedAt)-Date.parse(record.firstKnownAt)>=this.reviewThresholdMs,state=classification==="RETRYABLE_PENDING"?(old?EXISTING_TASK_SUPERVISION_STATES.REVIEW:EXISTING_TASK_SUPERVISION_STATES.WAITING):["RESULT_AVAILABLE","COMPLETED_NO_RESULTS"].includes(classification)?EXISTING_TASK_SUPERVISION_STATES.AVAILABLE:["PROVIDER_TERMINAL_FAILURE","TASK_NOT_FOUND"].includes(classification)?EXISTING_TASK_SUPERVISION_STATES.TERMINAL:EXISTING_TASK_SUPERVISION_STATES.REVIEW;this.repository.completeTaskSupervisionAttempt({providerTaskId:record.providerTaskId,leaseId,attemptedAt,classification,statusCode:outcome?.statusCode??null,statusMessage:outcome?.statusMessage??null,reason:outcome?.reason??null,nextEligibleCheckAt:state===EXISTING_TASK_SUPERVISION_STATES.WAITING?plus(attemptedAt,this.pollIntervalMs):null,supervisionState:state,operatorReviewReason:state===EXISTING_TASK_SUPERVISION_STATES.REVIEW?(old?"HARDWARE_RADAR_OPERATIONAL_REVIEW_THRESHOLD_EXCEEDED":outcome?.reason??"PROVIDER_STATUS_REVIEW_REQUIRED"):null,terminalReason:state===EXISTING_TASK_SUPERVISION_STATES.TERMINAL?outcome?.reason??classification:null});checks++;}return freeze({...this.inspect({runId}),checks,providerCalls:checks,newPaidTasks:0,actualSpendUsd:0,automaticPaidRetries:0});}
 #project(record,at){if([EXISTING_TASK_SUPERVISION_STATES.PENDING,EXISTING_TASK_SUPERVISION_STATES.WAITING].includes(record.supervisionState)&&record.nextEligibleCheckAt&&Date.parse(at)>=Date.parse(record.nextEligibleCheckAt))return freeze({...record,supervisionState:EXISTING_TASK_SUPERVISION_STATES.DUE});return freeze(record);}
}
