import crypto from "node:crypto";
import {mkdir,readFile,rename,writeFile} from "node:fs/promises";
import {dirname} from "node:path";

export const EXISTING_TASK_SUPERVISION_SCHEDULER_POLICY_VERSION="MERCURY-EXISTING-TASK-SUPERVISION-SCHEDULER-1.0";
export const EXISTING_TASK_SUPERVISION_SCHEDULER_HEALTH=Object.freeze({HEALTHY:"HEALTHY",IDLE:"IDLE_NO_DUE_WORK",REVIEW:"DEGRADED_REVIEW_REQUIRED",PROVIDER_FAILURE:"DEGRADED_PROVIDER_FAILURE",SYSTEMIC_FAILURE:"SYSTEMIC_FAILURE",DISABLED:"DISABLED",NOT_CONFIGURED:"NOT_CONFIGURED"});
const freeze=value=>Object.freeze(structuredClone(value));
const validTime=value=>typeof value==="string"&&Number.isFinite(Date.parse(value));
const digest=value=>crypto.createHash("sha256").update(JSON.stringify(value)).digest("hex");

export class FileExistingTaskSupervisionSchedulerReceiptRepository{
 constructor({statePath}={}){if(!statePath)throw new Error("EXISTING_TASK_SUPERVISION_SCHEDULER_STATE_REQUIRED");this.statePath=statePath;}
 async getLatest(){try{return freeze(JSON.parse(await readFile(this.statePath,"utf8")));}catch(error){if(error?.code==="ENOENT")return null;throw error;}}
 async record(value){const prior=await this.getLatest();if(prior?.invocationId===value.invocationId){if(JSON.stringify(prior)!==JSON.stringify(value))throw new Error("EXISTING_TASK_SUPERVISION_SCHEDULER_RECEIPT_CONFLICT");return{status:"DUPLICATE",value:prior};}await mkdir(dirname(this.statePath),{recursive:true});const temporary=`${this.statePath}.${process.pid}.${crypto.randomUUID()}.tmp`;await writeFile(temporary,`${JSON.stringify(value,null,2)}\n`);await rename(temporary,this.statePath);return{status:"RECORDED",value:freeze(value)};}
}

export class ExistingTaskSupervisionScheduler{
 constructor({repository,superviseRun,receiptRepository,now=()=>new Date().toISOString(),maximumChecksPerInvocation=50,configured=true}={}){if(typeof repository?.listAllTaskSupervisions!=="function"||typeof repository?.listDueTaskSupervisions!=="function"||typeof superviseRun!=="function"||typeof receiptRepository?.record!=="function"||!Number.isInteger(maximumChecksPerInvocation)||maximumChecksPerInvocation<1||maximumChecksPerInvocation>200)throw new Error("EXISTING_TASK_SUPERVISION_SCHEDULER_DEPENDENCIES_INVALID");Object.assign(this,{repository,superviseRun,receiptRepository,now,maximumChecksPerInvocation,configured});}
 inspect({asOf=this.now(),enabled=false}={}){if(!validTime(asOf))throw new Error("EXISTING_TASK_SUPERVISION_SCHEDULER_TIME_INVALID");const records=this.repository.listAllTaskSupervisions(),active=records.filter(value=>["PENDING_PROVIDER","CHECK_DUE","WAITING_UNTIL_NEXT_CHECK"].includes(value.supervisionState)),due=active.filter(value=>!value.nextEligibleCheckAt||Date.parse(value.nextEligibleCheckAt)<=Date.parse(asOf)),review=records.filter(value=>value.supervisionState==="OPERATOR_REVIEW_REQUIRED"),terminal=records.filter(value=>value.supervisionState==="PROVIDER_TERMINAL_FAILURE"),nextDue=active.map(value=>value.nextEligibleCheckAt).filter(Boolean).sort()[0]??null,oldest=active.map(value=>value.firstKnownAt).filter(validTime).sort()[0]??null,health=!this.configured?EXISTING_TASK_SUPERVISION_SCHEDULER_HEALTH.NOT_CONFIGURED:!enabled?EXISTING_TASK_SUPERVISION_SCHEDULER_HEALTH.DISABLED:terminal.length?EXISTING_TASK_SUPERVISION_SCHEDULER_HEALTH.PROVIDER_FAILURE:review.length?EXISTING_TASK_SUPERVISION_SCHEDULER_HEALTH.REVIEW:due.length?EXISTING_TASK_SUPERVISION_SCHEDULER_HEALTH.HEALTHY:EXISTING_TASK_SUPERVISION_SCHEDULER_HEALTH.IDLE;return freeze({asOf,health,configured:this.configured,enabled,tracked:records.length,pending:active.length,due:due.length,reviewRequired:review.length,providerTerminalFailures:terminal.length,taskNotFound:terminal.filter(value=>value.latestProviderStatus==="TASK_NOT_FOUND").length,oldestPendingFirstKnownAt:oldest,nextDueCheckAt:nextDue,maximumChecksPerInvocation:this.maximumChecksPerInvocation,readOnly:true,paidTaskCreated:false,replacementTasks:0,additionalSpendUsd:0});}
 async run({maxChecks=this.maximumChecksPerInvocation,scheduled=true}={}){if(!Number.isInteger(maxChecks)||maxChecks<1||maxChecks>this.maximumChecksPerInvocation)throw new Error("EXISTING_TASK_SUPERVISION_SCHEDULER_BOUND_INVALID");const startedAt=this.now(),due=this.repository.listDueTaskSupervisions({asOf:startedAt,limit:maxChecks}),runIds=[...new Set(due.map(value=>value.runId))],results=[];let remaining=maxChecks,systemicFailure=null;try{for(const runId of runIds){if(remaining===0)break;const eligible=due.filter(value=>value.runId===runId).length,result=await this.superviseRun({runId,maxChecks:Math.min(eligible,remaining)});results.push({runId,checks:result.checks,pending:result.pending,due:result.due,reviewRequired:result.reviewRequired,terminalFailures:result.terminalFailures});remaining-=result.checks;}}catch(error){systemicFailure=String(error?.message??error);}const completedAt=this.now(),state=this.inspect({asOf:completedAt,enabled:scheduled}),checksPerformed=results.reduce((sum,value)=>sum+value.checks,0),health=systemicFailure?EXISTING_TASK_SUPERVISION_SCHEDULER_HEALTH.SYSTEMIC_FAILURE:state.health,material={policyVersion:EXISTING_TASK_SUPERVISION_SCHEDULER_POLICY_VERSION,startedAt,completedAt,scheduled,maximumChecks:maxChecks,eligibleDueBefore:due.length,checksPerformed,runResults:results,health,systemicFailure,state};const receipt=freeze({schemaVersion:"1.0",projectionType:"EXISTING_TASK_SUPERVISION_SCHEDULER_OPERATIONS",invocationId:`mer_tasksupervisionrun_${digest(material).slice(0,24)}`,...material,networkOperation:checksPerformed?"EXISTING_TASK_RESULT_RETRIEVAL":"NONE",readOnly:true,mutationAuthorized:false,newPaidTasks:0,replacementTasks:0,additionalSpendUsd:0,automaticPaidRetries:0});await this.receiptRepository.record(receipt);if(systemicFailure)throw Object.assign(new Error(systemicFailure),{receipt});return receipt;}
}
