import crypto from "node:crypto";
import {DATAFORSEO_DEFAULT_UTC_DAY_SPEND_CEILING_USD} from "../acquisition/planning/AcquisitionBudgetPolicy.js";

const stable=value=>Array.isArray(value)?`[${value.map(stable).join(",")}]`:value&&typeof value==="object"?`{${Object.keys(value).sort().map(key=>`${JSON.stringify(key)}:${stable(value[key])}`).join(",")}}`:JSON.stringify(value);
const digest=value=>crypto.createHash("sha256").update(stable(value)).digest("hex");
const freeze=value=>Object.freeze(structuredClone(value));
const required=(value,code)=>{if(typeof value!=="string"||!value.trim())throw new Error(code);return value.trim();};
const iso=(value,code)=>{const result=required(value,code);if(!Number.isFinite(Date.parse(result)))throw new Error(code);return result;};
const validatePlan=value=>{if(!value)return value;const material={policyVersion:value.policyVersion,cycle:value.cycle,requested:value.requested,ready:value.ready,blocked:value.blocked,automaticPaidRetries:value.automaticPaidRetries,dailySpendCeilingUsd:value.dailySpendCeilingUsd,...(value.selectionProvenance?{selectionProvenance:value.selectionProvenance}:{})};if(value.bindingDigest!==digest(material)||value.planId!==`${value.planId.slice(0,value.planId.lastIndexOf("_"))}_${value.bindingDigest.slice(0,24)}`)throw new Error("BOUNDED_PLAN_INTEGRITY_INVALID");return value;};

export const BOUNDED_MEMBER_STATES=Object.freeze({READY:"READY",AUTHORIZED:"AUTHORIZED",WAITING:"WAITING_FOR_PROVIDER",COMPLETED:"COMPLETED",EXCEPTION:"EXCEPTION"});
export const BOUNDED_FAILURE_CLASSES=Object.freeze({MEMBER_LOCAL:"MEMBER_LOCAL_FAILURE",SYSTEMIC:"SYSTEMIC_FAILURE"});

export function createBoundedChildAuthorityBinding({parentAuthorization,member,childAuthorizationId,childAuthorizationDigest,expiresAt}={}){
  const expiry=iso(expiresAt,"BOUNDED_CHILD_EXPIRY_INVALID");
  const material={parentAuthorizationId:required(parentAuthorization?.authorizationId,"BOUNDED_CHILD_PARENT_INVALID"),parentAuthorizationDigest:required(parentAuthorization?.bindingDigest,"BOUNDED_CHILD_PARENT_INVALID"),planId:required(parentAuthorization?.planId,"BOUNDED_CHILD_PARENT_INVALID"),memberKey:required(member?.memberKey,"BOUNDED_CHILD_MEMBER_INVALID"),domainMemberId:required(member?.domainMemberId,"BOUNDED_CHILD_MEMBER_INVALID"),source:required(member?.source,"BOUNDED_CHILD_SOURCE_INVALID"),operation:required(member?.operation,"BOUNDED_CHILD_OPERATION_INVALID"),maximumTaskCostUsd:member?.taskCeilingUsd,childAuthorizationId:required(childAuthorizationId,"BOUNDED_CHILD_AUTHORIZATION_INVALID"),childAuthorizationDigest:required(childAuthorizationDigest,"BOUNDED_CHILD_AUTHORIZATION_INVALID"),automaticPaidRetries:0,expiresAt:expiry};
  if(!/^[a-f0-9]{64}$/.test(material.parentAuthorizationDigest)||!/^[a-f0-9]{64}$/.test(material.childAuthorizationDigest)||!Number.isFinite(material.maximumTaskCostUsd)||material.maximumTaskCostUsd<0||Date.parse(expiry)>Date.parse(parentAuthorization.expiresAt))throw new Error("BOUNDED_CHILD_AUTHORITY_INVALID");
  return freeze({...material,bindingDigest:digest(material)});
}

export class NeutralBoundedPaidActionCoordinator{
  constructor({repository,domainAdapter,spendResolver=async()=>0,now=()=>new Date().toISOString(),dailySpendCeilingUsd=DATAFORSEO_DEFAULT_UTC_DAY_SPEND_CEILING_USD,policyVersion,idPrefixes={plan:"mer_boundedplan",authorization:"mer_boundedauth",run:"mer_boundedrun"}}={}){
    for(const method of["recordPlan","getPlan","recordAuthorization","getAuthorization","findAuthorizationsByPlan","startRun","getRun","findRunByPlan","updateMember","updateRun"])if(typeof repository?.[method]!=="function")throw new Error("BOUNDED_COORDINATOR_REPOSITORY_REQUIRED");
    for(const method of["prepareMember","revalidateMember","advanceMember","classifyFailure","summarize"])if(typeof domainAdapter?.[method]!=="function")throw new Error("BOUNDED_COORDINATOR_DOMAIN_ADAPTER_REQUIRED");
    for(const key of["plan","authorization","run"])required(idPrefixes?.[key],"BOUNDED_ID_PREFIX_REQUIRED");Object.assign(this,{repository,domainAdapter,spendResolver,now,dailySpendCeilingUsd,policyVersion:required(policyVersion,"BOUNDED_POLICY_REQUIRED"),idPrefixes:freeze(idPrefixes)});
  }
  async prepare({cycle,cohort,selectionProvenance=null}){
    const observationCycle=iso(cycle,"BOUNDED_PLAN_CYCLE_INVALID");if(!Array.isArray(cohort)||cohort.length===0)throw new Error("BOUNDED_PLAN_COHORT_REQUIRED");
    const requested=cohort.map(value=>freeze(value)).sort((a,b)=>stable(a).localeCompare(stable(b)));if(new Set(requested.map(stable)).size!==requested.length)throw new Error("BOUNDED_PLAN_COHORT_DUPLICATE");
    const ready=[],blocked=[];for(const request of requested)try{const member=await this.domainAdapter.prepareMember({request,cycle:observationCycle});for(const [value,code] of[[member?.memberKey,"BOUNDED_MEMBER_KEY_REQUIRED"],[member?.domainMemberId,"BOUNDED_DOMAIN_MEMBER_ID_REQUIRED"],[member?.source,"BOUNDED_MEMBER_SOURCE_REQUIRED"],[member?.operation,"BOUNDED_MEMBER_OPERATION_REQUIRED"]])required(value,code);if(!Number.isFinite(member.taskCeilingUsd)||member.taskCeilingUsd<0)throw new Error("BOUNDED_MEMBER_TASK_CEILING_INVALID");ready.push(freeze(member));}catch(error){blocked.push(freeze({...request,...this.domainAdapter.classifyFailure(error)}));}
    const provenance=selectionProvenance==null?null:freeze(selectionProvenance),hex=value=>typeof value==="string"&&/^[a-f0-9]{64}$/.test(value);if(provenance!==null&&(!["proposalId","proposalSchemaVersion","proposalArtifactType","stagePolicyId","stagePolicyVersion","stageId","selectorPolicyId","selectorPolicyVersion","source","operation"].every(key=>typeof provenance[key]==="string"&&provenance[key])||provenance.selectionInputType!=="SELECTOR_PROPOSAL"||![provenance.proposalDigest,provenance.selectedMemberDigest,provenance.candidatePoolDigest,provenance.stageCohortDigest].every(hex)||!Number.isInteger(provenance.candidateCount)||!Number.isInteger(provenance.requestedSelectorSize)||!Array.isArray(provenance.selectedAtlasProductIds)||provenance.selectedAtlasProductIds.length!==requested.length||provenance.requestedSelectorSize!==requested.length||new Set(provenance.selectedAtlasProductIds).size!==requested.length||provenance.selectedAtlasProductIds.some(id=>!requested.some(row=>row.atlasProductId===id))))throw new Error("BOUNDED_SELECTION_PROVENANCE_INCOMPLETE");
    if(provenance?.selectedOperations){const identities=provenance.selectedOperations.map(value=>stable(value));if(provenance.observationCycle!==observationCycle||provenance.selectedOperations.length!==requested.length||new Set(identities).size!==requested.length||provenance.selectedOperations.some(value=>value?.source!==provenance.source||value?.operation!==provenance.operation||value?.observationCycle!==observationCycle||!requested.some(row=>row.atlasProductId===value.atlasProductId&&(row.source??row.sourceId)===value.source)))throw new Error("BOUNDED_SELECTION_OPERATION_MISMATCH");}
    const material={policyVersion:this.policyVersion,cycle:observationCycle,requested,ready,blocked,automaticPaidRetries:0,dailySpendCeilingUsd:this.dailySpendCeilingUsd,...(provenance?{selectionProvenance:provenance}:{})},bindingDigest=digest(material),plan=freeze({schemaVersion:"1.0",planId:`${this.idPrefixes.plan}_${bindingDigest.slice(0,24)}`,bindingDigest,...material,selectionInputType:provenance?"SELECTOR_PROPOSAL":"LEGACY_COHORT_INPUT",cohortDigest:digest(requested),maximumPaidTasks:ready.length,maximumSpendUsd:Number(ready.reduce((sum,member)=>sum+member.taskCeilingUsd,0).toFixed(4)),preparedAt:observationCycle,authorizationState:"NOT_AUTHORIZED",providerSpendAuthorized:false});return this.repository.recordPlan(plan);
  }
  async authorize({planId,operator,reason,expiresAt}){
    const plan=validatePlan(this.repository.getPlan(required(planId,"BOUNDED_PLAN_ID_REQUIRED")));if(!plan)throw new Error("BOUNDED_PLAN_NOT_FOUND");const authorizedAt=this.now(),expiry=iso(expiresAt,"BOUNDED_AUTHORIZATION_EXPIRY_INVALID"),currentSpend=await this.spendResolver(authorizedAt);if(Date.parse(expiry)<=Date.parse(authorizedAt)||currentSpend+plan.maximumSpendUsd>this.dailySpendCeilingUsd)throw new Error("BOUNDED_AGGREGATE_BUDGET_INVALID");
    const material={policyVersion:this.policyVersion,planId:plan.planId,planBindingDigest:plan.bindingDigest,memberSetDigest:plan.cohortDigest,operator:required(operator,"BOUNDED_OPERATOR_REQUIRED"),reason:required(reason,"BOUNDED_REASON_REQUIRED"),authorizedAt,expiresAt:expiry,maximumPaidTasks:plan.maximumPaidTasks,maximumSpendUsd:plan.maximumSpendUsd,memberCeilings:plan.ready.map(member=>({memberKey:member.memberKey,maximumTaskCostUsd:member.taskCeilingUsd})),currentUtcDaySpendUsd:currentSpend,dailySpendCeilingUsd:this.dailySpendCeilingUsd,automaticPaidRetries:0},bindingDigest=digest(material),authorization=freeze({schemaVersion:"1.0",authorizationId:`${this.idPrefixes.authorization}_${bindingDigest.slice(0,24)}`,bindingDigest,...material,singleUseStart:true,state:"AUTHORIZED"});return this.repository.recordAuthorization(authorization);
  }
  async start({authorizationId,startedBy}){
    required(startedBy,"BOUNDED_START_OPERATOR_REQUIRED");const authorization=this.repository.getAuthorization(required(authorizationId,"BOUNDED_AUTHORIZATION_ID_REQUIRED"));if(!authorization)throw new Error("BOUNDED_AUTHORIZATION_NOT_FOUND");const plan=validatePlan(this.repository.getPlan(authorization.planId)),at=this.now();if(!plan||plan.bindingDigest!==authorization.planBindingDigest||Date.parse(at)>=Date.parse(authorization.expiresAt))throw new Error("BOUNDED_AUTHORIZATION_INVALID");for(const member of plan.ready)await this.domainAdapter.revalidateMember({member,plan,authorization});if((await this.spendResolver(at))+plan.maximumSpendUsd>this.dailySpendCeilingUsd)throw new Error("BOUNDED_AGGREGATE_BUDGET_INVALID");
    const runId=`${this.idPrefixes.run}_${digest({authorizationId}).slice(0,24)}`,members=plan.ready.map(member=>({...member,state:BOUNDED_MEMBER_STATES.READY,childAuthorityBinding:null,exception:null})),created=this.repository.startRun(freeze({schemaVersion:"1.0",runId,planId:plan.planId,authorizationId,cycle:plan.cycle,state:"RUNNING",startedAt:at,members}));if(created.status==="DUPLICATE")return this.inspect({runId});return this._advance(runId,authorization);
  }
  async resume({runId,resumedBy}){
    required(resumedBy,"BOUNDED_RESUME_OPERATOR_REQUIRED");let run=this.repository.getRun(required(runId,"BOUNDED_RUN_ID_REQUIRED"));if(!run)throw new Error("BOUNDED_RUN_NOT_FOUND");const authorization=this.repository.getAuthorization(run.authorizationId);if(typeof this.domainAdapter.recoverPreExecutionMember==="function")for(const member of run.members.filter(value=>[BOUNDED_MEMBER_STATES.READY,BOUNDED_MEMBER_STATES.AUTHORIZED].includes(value.state))){const recovered=await this.domainAdapter.recoverPreExecutionMember({member,run,authorization});if(recovered)this.repository.updateMember(runId,{...member,...recovered});}run=this.repository.getRun(runId);if(run.members.some(member=>[BOUNDED_MEMBER_STATES.READY,BOUNDED_MEMBER_STATES.AUTHORIZED].includes(member.state)))throw new Error("BOUNDED_RESUME_NEW_PAID_TASK_FORBIDDEN");if(typeof this.domainAdapter.recoverMember==="function")for(const member of run.members.filter(value=>value.state===BOUNDED_MEMBER_STATES.EXCEPTION)){const recovered=await this.domainAdapter.recoverMember({member,run});if(recovered)this.repository.updateMember(runId,{...member,...recovered});}const current=this.repository.getRun(runId);return this._advance(runId,this.repository.getAuthorization(current.authorizationId));
  }
  async progressExistingTasks({runId}={}){
    const id=required(runId,"BOUNDED_RUN_ID_REQUIRED"),run=this.repository.getRun(id);if(!run)throw new Error("BOUNDED_RUN_NOT_FOUND");
    if(run.state==="FAILED"||!["RUNNING","WAITING_FOR_PROVIDER"].includes(run.state))return this.domainAdapter.summarize(run);
    const active=run.members.filter(member=>![BOUNDED_MEMBER_STATES.COMPLETED,BOUNDED_MEMBER_STATES.EXCEPTION].includes(member.state));
    const stop=reason=>{this.repository.updateRun({...run,state:"FAILED",systemicFailure:reason});return this.domainAdapter.summarize(this.repository.getRun(id));};
    if(active.some(member=>member.state!==BOUNDED_MEMBER_STATES.WAITING))return stop("BOUNDED_PENDING_NEW_PAID_TASK_FORBIDDEN");
    if(active.some(member=>member.paidTaskCreated!==true||typeof member.providerTaskId!=="string"||!member.providerTaskId.trim()))return stop("BOUNDED_PENDING_TASK_LINEAGE_INVALID");
    return this._advance(id,this.repository.getAuthorization(run.authorizationId));
  }
  async inspect({runId=null,planId=null}){if(Boolean(runId)===Boolean(planId))throw new Error("BOUNDED_INSPECT_ID_REQUIRED");const spend=await this.spendResolver(this.now());if(runId){const run=this.repository.getRun(runId);if(!run)throw new Error("BOUNDED_RUN_NOT_FOUND");return freeze({...this.domainAdapter.summarize(run),currentUtcDaySpendUsd:spend,dailySpendCeilingUsd:this.dailySpendCeilingUsd,remainingUtcDayCapacityUsd:Number((this.dailySpendCeilingUsd-spend).toFixed(4))});}const plan=validatePlan(this.repository.getPlan(planId));if(!plan)throw new Error("BOUNDED_PLAN_NOT_FOUND");const selectionProvenance=plan.selectionProvenance??null,selectorMembershipEquivalent=selectionProvenance?(selectionProvenance.selectedOperations?selectionProvenance.selectedOperations.length===plan.requested.length&&selectionProvenance.selectedOperations.every(operation=>operation.observationCycle===plan.cycle&&plan.requested.some(row=>row.atlasProductId===operation.atlasProductId&&(row.source??row.sourceId)===operation.source)):selectionProvenance.selectedAtlasProductIds.length===plan.requested.length&&selectionProvenance.selectedAtlasProductIds.every(id=>plan.requested.some(row=>row.atlasProductId===id))):null;return freeze({planId:plan.planId,cycle:plan.cycle,selectionInputType:selectionProvenance?"SELECTOR_PROPOSAL":"LEGACY_COHORT_INPUT",selectionProvenance,selectorMembershipEquivalent,requested:plan.requested,ready:plan.ready,blocked:plan.blocked,maximumPaidTasks:plan.maximumPaidTasks,maximumSpendUsd:plan.maximumSpendUsd,automaticPaidRetries:0,currentUtcDaySpendUsd:spend,dailySpendCeilingUsd:this.dailySpendCeilingUsd,remainingUtcDayCapacityUsd:Number((this.dailySpendCeilingUsd-spend).toFixed(4)),authorizationState:this.repository.findAuthorizationsByPlan(planId).at(-1)?.state??"NOT_AUTHORIZED",runState:this.repository.findRunByPlan(planId)?.state??"NOT_STARTED"});}
  async _advance(runId,authorization){let run=this.repository.getRun(runId);for(let member of run.members){if([BOUNDED_MEMBER_STATES.COMPLETED,BOUNDED_MEMBER_STATES.EXCEPTION].includes(member.state))continue;try{const checkpoint=next=>{member={...member,...next};this.repository.updateMember(runId,member);return member;};member={...member,...await this.domainAdapter.advanceMember({member,run,authorization,createChildBinding:createBoundedChildAuthorityBinding,checkpoint})};this.repository.updateMember(runId,member);}catch(error){const failure=this.domainAdapter.classifyFailure(error);if(failure.classification===BOUNDED_FAILURE_CLASSES.SYSTEMIC){this.repository.updateRun({...run,state:"FAILED",systemicFailure:String(error.message)});return this.domainAdapter.summarize(this.repository.getRun(runId));}this.repository.updateMember(runId,{...member,state:BOUNDED_MEMBER_STATES.EXCEPTION,exception:String(error.message)});}}run=this.repository.getRun(runId);const state=run.members.some(member=>member.state===BOUNDED_MEMBER_STATES.WAITING)?"WAITING_FOR_PROVIDER":run.members.some(member=>member.state===BOUNDED_MEMBER_STATES.EXCEPTION)?"COMPLETED_WITH_EXCEPTIONS":"COMPLETED";this.repository.updateRun({...run,state,completedAt:state==="WAITING_FOR_PROVIDER"?null:this.now()});return this.domainAdapter.summarize(this.repository.getRun(runId));}
}

export const neutralBoundedDigest=digest;
