import {DatabaseSync} from "node:sqlite";
import {dirname,resolve} from "node:path";
import {mkdirSync} from "node:fs";

const stable=value=>JSON.stringify(value,Object.keys(value??{}).sort());
const freeze=value=>value==null?null:Object.freeze(structuredClone(value));
const parse=row=>row?freeze(JSON.parse(row.payload_json)):null;
const required=(value,code)=>{if(typeof value!=="string"||!value)throw new Error(code);return value;};

export class SqliteNeutralBoundedRepository{
  constructor({databasePath}={}){if(!databasePath)throw new Error("BOUNDED_DATABASE_PATH_REQUIRED");this.databasePath=resolve(databasePath);mkdirSync(dirname(this.databasePath),{recursive:true});this.db=new DatabaseSync(this.databasePath);this.db.exec("PRAGMA journal_mode=WAL; PRAGMA synchronous=FULL; PRAGMA foreign_keys=ON; PRAGMA busy_timeout=5000;");this.db.exec(`CREATE TABLE IF NOT EXISTS bounded_plans(plan_id TEXT PRIMARY KEY,binding_digest TEXT NOT NULL,cycle TEXT NOT NULL,payload_json TEXT NOT NULL); CREATE TABLE IF NOT EXISTS bounded_plan_members(plan_id TEXT NOT NULL REFERENCES bounded_plans(plan_id),member_key TEXT NOT NULL,domain_member_id TEXT NOT NULL,source_id TEXT NOT NULL,operation TEXT NOT NULL,task_ceiling_usd REAL NOT NULL,state TEXT NOT NULL,payload_json TEXT NOT NULL,PRIMARY KEY(plan_id,member_key)); CREATE INDEX IF NOT EXISTS bounded_plan_member_domain_idx ON bounded_plan_members(plan_id,domain_member_id); CREATE TABLE IF NOT EXISTS bounded_authorizations(authorization_id TEXT PRIMARY KEY,plan_id TEXT NOT NULL REFERENCES bounded_plans(plan_id),authorized_at TEXT NOT NULL,expires_at TEXT NOT NULL,binding_digest TEXT NOT NULL,payload_json TEXT NOT NULL); CREATE INDEX IF NOT EXISTS bounded_auth_plan_idx ON bounded_authorizations(plan_id,expires_at); CREATE TABLE IF NOT EXISTS bounded_runs(run_id TEXT PRIMARY KEY,plan_id TEXT NOT NULL UNIQUE REFERENCES bounded_plans(plan_id),authorization_id TEXT NOT NULL UNIQUE REFERENCES bounded_authorizations(authorization_id),state TEXT NOT NULL,payload_json TEXT NOT NULL); CREATE TABLE IF NOT EXISTS bounded_run_members(run_id TEXT NOT NULL REFERENCES bounded_runs(run_id),member_key TEXT NOT NULL,domain_member_id TEXT NOT NULL,state TEXT NOT NULL,payload_json TEXT NOT NULL,PRIMARY KEY(run_id,member_key)); CREATE INDEX IF NOT EXISTS bounded_run_member_domain_idx ON bounded_run_members(run_id,domain_member_id); CREATE TABLE IF NOT EXISTS bounded_child_authorities(parent_authorization_id TEXT NOT NULL REFERENCES bounded_authorizations(authorization_id),member_key TEXT NOT NULL,child_authorization_id TEXT NOT NULL UNIQUE,binding_digest TEXT NOT NULL,payload_json TEXT NOT NULL,PRIMARY KEY(parent_authorization_id,member_key)); CREATE TABLE IF NOT EXISTS bounded_task_supervisions(provider_task_id TEXT PRIMARY KEY,run_id TEXT NOT NULL REFERENCES bounded_runs(run_id),member_key TEXT NOT NULL,state TEXT NOT NULL,next_eligible_check_at TEXT,lease_id TEXT,lease_expires_at TEXT,payload_json TEXT NOT NULL,UNIQUE(run_id,member_key)); CREATE INDEX IF NOT EXISTS bounded_task_supervision_due_idx ON bounded_task_supervisions(run_id,state,next_eligible_check_at);`);}
  close(){this.db.close();}
  _record(table,idColumn,id,value,status,conflict,columns=[],params=[]){const prior=parse(this.db.prepare(`SELECT payload_json FROM ${table} WHERE ${idColumn}=?`).get(id));if(prior){if(JSON.stringify(prior)!==JSON.stringify(value))throw new Error(conflict);return{status:"DUPLICATE",value:prior};}try{this.db.prepare(`INSERT INTO ${table}(${idColumn},${columns.join(",")},payload_json) VALUES (?${columns.map(()=>",?").join("")},?)`).run(id,...params,JSON.stringify(value));return{status,value:freeze(value)};}catch(error){if(String(error.message).includes("UNIQUE"))throw new Error(conflict);throw error;}}
  recordPlan(value){required(value?.planId,"BOUNDED_PLAN_INVALID");this.db.exec("BEGIN IMMEDIATE");try{const prior=this.getPlan(value.planId);if(prior){if(JSON.stringify(prior)!==JSON.stringify(value))throw new Error("BOUNDED_PLAN_CONFLICT");this.db.exec("COMMIT");return{status:"DUPLICATE",value:prior};}this.db.prepare("INSERT INTO bounded_plans VALUES (?,?,?,?)").run(value.planId,value.bindingDigest,value.cycle,JSON.stringify({...value,ready:undefined,blocked:undefined,requested:undefined}));for(const member of value.ready??[])this.db.prepare("INSERT INTO bounded_plan_members VALUES (?,?,?,?,?,?,?,?)").run(value.planId,member.memberKey,member.domainMemberId,member.source,member.operation,member.taskCeilingUsd,"READY",JSON.stringify(member));this.db.prepare("UPDATE bounded_plans SET payload_json=? WHERE plan_id=?").run(JSON.stringify(value),value.planId);this.db.exec("COMMIT");return{status:"PREPARED",value:freeze(value)};}catch(error){this.db.exec("ROLLBACK");throw error;}}
  getPlan(id){return parse(this.db.prepare("SELECT payload_json FROM bounded_plans WHERE plan_id=?").get(id));}
  getPlanMember(planId,memberKey){return parse(this.db.prepare("SELECT payload_json FROM bounded_plan_members WHERE plan_id=? AND member_key=?").get(planId,memberKey));}
  recordAuthorization(value){const prior=this.getAuthorization(value.authorizationId);if(prior)return JSON.stringify(prior)===JSON.stringify(value)?{status:"DUPLICATE",value:prior}:(()=>{throw new Error("BOUNDED_AUTHORIZATION_CONFLICT")})();this.db.exec("BEGIN IMMEDIATE");try{if(this.db.prepare("SELECT 1 FROM bounded_authorizations WHERE plan_id=? AND expires_at>?").get(value.planId,value.authorizedAt))throw new Error("BOUNDED_AUTHORIZATION_ACTIVE");this.db.prepare("INSERT INTO bounded_authorizations VALUES (?,?,?,?,?,?)").run(value.authorizationId,value.planId,value.authorizedAt,value.expiresAt,value.bindingDigest,JSON.stringify(value));this.db.exec("COMMIT");return{status:"AUTHORIZED",value:freeze(value)};}catch(error){this.db.exec("ROLLBACK");throw error;}}
  getAuthorization(id){return parse(this.db.prepare("SELECT payload_json FROM bounded_authorizations WHERE authorization_id=?").get(id));}
  findAuthorizationsByPlan(id){return this.db.prepare("SELECT payload_json FROM bounded_authorizations WHERE plan_id=? ORDER BY authorized_at,authorization_id").all(id).map(parse);}
  recordChildAuthority(value){return this._record("bounded_child_authorities","child_authorization_id",required(value?.childAuthorizationId,"BOUNDED_CHILD_INVALID"),value,"RECORDED","BOUNDED_CHILD_AUTHORITY_CONFLICT",["parent_authorization_id","member_key","binding_digest"],[value.parentAuthorizationId,value.memberKey,value.bindingDigest]);}
  getChildAuthority(parentId,memberKey){return parse(this.db.prepare("SELECT payload_json FROM bounded_child_authorities WHERE parent_authorization_id=? AND member_key=?").get(parentId,memberKey));}
  getChildDisposition(childAuthorizationId){if(!this.db.prepare("SELECT 1 FROM sqlite_master WHERE type='table' AND name='bounded_child_dispositions'").get())return null;return parse(this.db.prepare("SELECT payload_json FROM bounded_child_dispositions WHERE child_authorization_id=?").get(childAuthorizationId));}
  recordChildDisposition(value){required(value?.dispositionId,"BOUNDED_CHILD_DISPOSITION_INVALID");required(value?.childAuthorizationId,"BOUNDED_CHILD_DISPOSITION_INVALID");this.db.exec("BEGIN IMMEDIATE");try{this.db.exec("CREATE TABLE IF NOT EXISTS bounded_child_dispositions(disposition_id TEXT PRIMARY KEY,child_authorization_id TEXT NOT NULL UNIQUE REFERENCES bounded_child_authorities(child_authorization_id),binding_digest TEXT NOT NULL,payload_json TEXT NOT NULL)");const prior=this.getChildDisposition(value.childAuthorizationId);if(prior){if(JSON.stringify(prior)!==JSON.stringify(value))throw new Error("BOUNDED_CHILD_DISPOSITION_CONFLICT");this.db.exec("COMMIT");return{status:"DUPLICATE",value:prior};}this.db.prepare("INSERT INTO bounded_child_dispositions VALUES (?,?,?,?)").run(value.dispositionId,value.childAuthorizationId,value.bindingDigest,JSON.stringify(value));this.db.exec("COMMIT");return{status:"RECORDED",value:freeze(value)};}catch(error){this.db.exec("ROLLBACK");if(String(error.message).includes("UNIQUE"))throw new Error("BOUNDED_CHILD_DISPOSITION_CONFLICT");throw error;}}
  startRun(value){this.db.exec("BEGIN IMMEDIATE");try{const prior=this.findRunByPlan(value.planId);if(prior){if(prior.authorizationId!==value.authorizationId)throw new Error("BOUNDED_RUN_START_CONFLICT");this.db.exec("COMMIT");return{status:"DUPLICATE",value:prior};}this.db.prepare("INSERT INTO bounded_runs VALUES (?,?,?,?,?)").run(value.runId,value.planId,value.authorizationId,value.state,JSON.stringify({...value,members:undefined}));for(const member of value.members)this.db.prepare("INSERT INTO bounded_run_members VALUES (?,?,?,?,?)").run(value.runId,member.memberKey,member.domainMemberId,member.state,JSON.stringify(member));this.db.exec("COMMIT");return{status:"STARTED",value:freeze(value)};}catch(error){this.db.exec("ROLLBACK");throw error;}}
  getRun(id){const run=parse(this.db.prepare("SELECT payload_json FROM bounded_runs WHERE run_id=?").get(id));return run?freeze({...run,members:this.db.prepare("SELECT payload_json FROM bounded_run_members WHERE run_id=? ORDER BY member_key").all(id).map(parse)}):null;}
  findRunByPlan(id){const row=this.db.prepare("SELECT run_id FROM bounded_runs WHERE plan_id=?").get(id);return row?this.getRun(row.run_id):null;}
  getRunMember(runId,memberKey){return parse(this.db.prepare("SELECT payload_json FROM bounded_run_members WHERE run_id=? AND member_key=?").get(runId,memberKey));}
  updateMember(runId,value){const result=this.db.prepare("UPDATE bounded_run_members SET state=?,payload_json=? WHERE run_id=? AND member_key=?").run(value.state,JSON.stringify(value),runId,value.memberKey);if(result.changes!==1)throw new Error("BOUNDED_MEMBER_NOT_FOUND");return freeze(value);}
  updateRun(value){const result=this.db.prepare("UPDATE bounded_runs SET state=?,payload_json=? WHERE run_id=?").run(value.state,JSON.stringify({...value,members:undefined}),value.runId);if(result.changes!==1)throw new Error("BOUNDED_RUN_NOT_FOUND");return this.getRun(value.runId);}
  recordTaskSupervision(value){required(value?.providerTaskId,"BOUNDED_TASK_SUPERVISION_INVALID");this.db.exec("BEGIN IMMEDIATE");try{const prior=this.getTaskSupervision(value.providerTaskId);if(prior){if(prior.runId!==value.runId||prior.memberKey!==value.memberKey)throw new Error("BOUNDED_TASK_SUPERVISION_CONFLICT");this.db.exec("COMMIT");return{status:"DUPLICATE",value:prior};}this.db.prepare("INSERT INTO bounded_task_supervisions VALUES (?,?,?,?,?,?,?,?)").run(value.providerTaskId,value.runId,value.memberKey,value.supervisionState,value.nextEligibleCheckAt,null,null,JSON.stringify(value));this.db.exec("COMMIT");return{status:"RECORDED",value:freeze(value)};}catch(error){this.db.exec("ROLLBACK");throw error;}}
  getTaskSupervision(providerTaskId){return parse(this.db.prepare("SELECT payload_json FROM bounded_task_supervisions WHERE provider_task_id=?").get(providerTaskId));}
  listTaskSupervisions(runId){return this.db.prepare("SELECT payload_json FROM bounded_task_supervisions WHERE run_id=? ORDER BY member_key").all(runId).map(parse);}
  listAllTaskSupervisions(){return this.db.prepare("SELECT payload_json FROM bounded_task_supervisions ORDER BY run_id,member_key").all().map(parse);}
  listDueTaskSupervisions({asOf,limit}){if(typeof asOf!=="string"||!Number.isFinite(Date.parse(asOf))||!Number.isInteger(limit)||limit<1)throw new Error("BOUNDED_TASK_SUPERVISION_DUE_QUERY_INVALID");return this.db.prepare("SELECT payload_json FROM bounded_task_supervisions WHERE state IN ('PENDING_PROVIDER','CHECK_DUE','WAITING_UNTIL_NEXT_CHECK') AND (next_eligible_check_at IS NULL OR next_eligible_check_at<=?) AND (lease_id IS NULL OR lease_expires_at<=?) ORDER BY next_eligible_check_at,provider_task_id LIMIT ?").all(asOf,asOf,limit).map(parse);}
  claimDueTaskSupervisions({runId,asOf,limit,leaseId,leaseExpiresAt}){this.db.exec("BEGIN IMMEDIATE");try{const rows=this.db.prepare("SELECT provider_task_id,payload_json FROM bounded_task_supervisions WHERE run_id=? AND state IN ('PENDING_PROVIDER','CHECK_DUE','WAITING_UNTIL_NEXT_CHECK') AND (next_eligible_check_at IS NULL OR next_eligible_check_at<=?) AND (lease_id IS NULL OR lease_expires_at<=?) ORDER BY next_eligible_check_at,provider_task_id LIMIT ?").all(runId,asOf,asOf,limit);for(const row of rows)this.db.prepare("UPDATE bounded_task_supervisions SET lease_id=?,lease_expires_at=? WHERE provider_task_id=?").run(leaseId,leaseExpiresAt,row.provider_task_id);this.db.exec("COMMIT");return rows.map(row=>freeze(JSON.parse(row.payload_json)));}catch(error){this.db.exec("ROLLBACK");throw error;}}
  completeTaskSupervisionAttempt(value){this.db.exec("BEGIN IMMEDIATE");try{const row=this.db.prepare("SELECT lease_id,payload_json FROM bounded_task_supervisions WHERE provider_task_id=?").get(value.providerTaskId);if(!row||row.lease_id!==value.leaseId)throw new Error("BOUNDED_TASK_SUPERVISION_LEASE_INVALID");const prior=JSON.parse(row.payload_json),next={...prior,attemptCountSinceSupervision:prior.attemptCountSinceSupervision+1,lastRetrievalAttemptAt:value.attemptedAt,latestProviderStatus:value.classification,latestProviderStatusCode:value.statusCode,latestProviderStatusMessage:value.statusMessage,nextEligibleCheckAt:value.nextEligibleCheckAt,supervisionState:value.supervisionState,operatorReviewState:value.supervisionState==="OPERATOR_REVIEW_REQUIRED"?"REQUIRED":"NOT_REQUIRED",operatorReviewReason:value.operatorReviewReason,terminalReason:value.terminalReason,lease:null};this.db.prepare("UPDATE bounded_task_supervisions SET state=?,next_eligible_check_at=?,lease_id=NULL,lease_expires_at=NULL,payload_json=? WHERE provider_task_id=?").run(next.supervisionState,next.nextEligibleCheckAt,JSON.stringify(next),value.providerTaskId);this.db.exec("COMMIT");return freeze(next);}catch(error){this.db.exec("ROLLBACK");throw error;}}
}
