import crypto from "node:crypto";
import { RIGHTS_STATES } from "../rights/SourceRightsPolicy.js";
import { assessCurrentDisplayItemPriceEligibility } from "../current-display/CurrentDisplayEligibility.js";
import { createPublicCurrentRetailProjection, PUBLIC_CURRENT_RETAIL_POLICY } from "../current-display/PublicCurrentRetailProjection.js";

export const CURRENT_DISPLAY_PUBLICATION_POLICY_VERSION = "CURRENT-DISPLAY-PUBLICATION-CANDIDATE-AUTHORIZATION-P1-1.0";
export const CURRENT_DISPLAY_PUBLICATION_CLAIM_CLASS = "CURRENT_ITEM_PRICE_COMPARISON";
export const CURRENT_DISPLAY_PUBLICATION_CONFIRMATION = "AUTHORIZE-CURRENT-DISPLAY-PUBLICATION";
export const CURRENT_DISPLAY_EXCLUDED_CLAIMS = Object.freeze(["DELIVERED_TOTAL","SHIPPING_INCLUDED","TAX_INCLUDED","FEES_INCLUDED","SELLER_QUALITY","CONDITION","RECOMMENDATION","PICK"]);
const stable=v=>Array.isArray(v)?`[${v.map(stable).join(",")}]`:v&&typeof v==="object"?`{${Object.keys(v).sort().map(k=>`${JSON.stringify(k)}:${stable(v[k])}`).join(",")}}`:JSON.stringify(v);
export const currentDisplayPublicationDigest=v=>crypto.createHash("sha256").update(stable(v)).digest("hex");
const freeze=v=>{if(v&&typeof v==="object"&&!Object.isFrozen(v)){Object.freeze(v);for(const x of Object.values(v))freeze(x);}return v;};
const scopedProjection=(projection,id)=>{const product=projection.products.find(x=>x.atlasProductId===id);if(!product)throw new Error("CURRENT_DISPLAY_PUBLICATION_NO_ELIGIBLE_PRODUCT");const offers=product.offers, lower=product.lowerCurrentItemPrice;return freeze({...projection,counts:{sourceOffers:offers.length,publicCurrentEligibleOffers:offers.length,staleOffers:projection.counts.staleOffers},winners:{overall:lower,ddr5:null,ddr4:null,laptop:null},products:[product]});};

export function deriveCurrentDisplayPublicationFacts({snapshot,products,retailers,destinations,rightsRegistry,atlasProductId,evaluatedAt}={}){
  if(snapshot?.snapshotId==null||!atlasProductId||!rightsRegistry?.require)throw new TypeError("CURRENT_DISPLAY_PUBLICATION_INPUT_INVALID");
  const target=snapshot.offers.filter(x=>x.atlasProductId===atlasProductId), seen=new Set(), adjusted=[];
  for(const offer of target){const key=offer.retailerId;if(seen.has(key))throw new Error("CURRENT_SOURCE_CONFLICT_REVIEW_REQUIRED");seen.add(key);const rights=rightsRegistry.require(offer.sourceIdentity?.sourceId);const eligibility=assessCurrentDisplayItemPriceEligibility({condition:offer.condition,conditionReasons:offer.condition==null?["CONDITION_UNKNOWN"]:[],availability:offer.availability,destinationId:offer.destinationId,publicDisplayAllowed:rights.live?.publicDisplay===RIGHTS_STATES.ALLOWED,comparisonAllowed:rights.live?.comparison===RIGHTS_STATES.ALLOWED,weakItemPriceAllowed:true});adjusted.push({...offer,itemPriceEligible:eligibility.itemPriceEligible,comparisonEligible:eligibility.comparisonEligible,comparisonReasons:eligibility.comparisonReasons,deliveredCostEligible:false,deliveredCostReasons:eligibility.deliveredCostReasons});}
  const projection=scopedProjection(createPublicCurrentRetailProjection({products,retailers,destinations,currentSnapshot:{...snapshot,offers:adjusted},asOf:evaluatedAt}),atlasProductId);
  const product=projection.products[0], expiresAt=new Date(Math.min(...product.offers.map(x=>Date.parse(x.observedAt)+PUBLIC_CURRENT_RETAIL_POLICY.maxAgeHours*3600000))).toISOString();
  const publicFacts={atlasProductId,offers:product.offers.map(x=>({retailerId:x.retailerId,retailerName:x.retailerName,destinationId:x.destinationId,destinationUrl:x.destinationUrl,itemPriceUsd:x.itemPriceUsd,currency:x.currency,observedAt:x.observedAt,comparisonEligible:x.comparisonEligible})),lowerCurrentItemPrice:product.lowerCurrentItemPrice?{retailerId:product.lowerCurrentItemPrice.retailerId,retailerName:product.lowerCurrentItemPrice.retailerName,destinationId:product.lowerCurrentItemPrice.destinationId,itemPriceUsd:product.lowerCurrentItemPrice.itemPriceUsd,currency:product.lowerCurrentItemPrice.currency}:null,disclosure:projection.disclosure};
  return freeze({snapshotDigest:currentDisplayPublicationDigest(snapshot),projection,projectionDigest:currentDisplayPublicationDigest(projection),publicFacts,publicFactsDigest:currentDisplayPublicationDigest(publicFacts),expiresAt});
}

export function createCurrentDisplayPublicationCandidate({snapshot,products,retailers,destinations,rightsRegistry,atlasProductId,publicationScope="PRODUCT_CURRENT_RETAIL",preparedBy,createdAt}={}){
  const d=deriveCurrentDisplayPublicationFacts({snapshot,products,retailers,destinations,rightsRegistry,atlasProductId,evaluatedAt:createdAt});
  const binding={policyVersion:CURRENT_DISPLAY_PUBLICATION_POLICY_VERSION,snapshotId:snapshot.snapshotId,snapshotDigest:d.snapshotDigest,projectionDigest:d.projectionDigest,publicFactsDigest:d.publicFactsDigest,atlasProductId,publicationScope,claimClass:CURRENT_DISPLAY_PUBLICATION_CLAIM_CLASS,publicFacts:d.publicFacts,excludedClaims:[...CURRENT_DISPLAY_EXCLUDED_CLAIMS],evaluationTime:createdAt,freshnessBoundary:d.expiresAt};
  const candidateDigest=currentDisplayPublicationDigest(binding);return freeze({schemaVersion:"1.0",candidateType:"CURRENT_DISPLAY_PUBLICATION",candidateId:`mer_displaypubcand_${candidateDigest.slice(0,24)}`,candidateDigest,binding,projection:d.projection,preparedBy,createdAt,status:"PREPARED",publicationAuthorized:false,artifactAuthority:false,releaseAuthority:false,deploymentAuthority:false});
}

export function authorizeCurrentDisplayPublication({candidate,snapshot,products,retailers,destinations,rightsRegistry,authorizedBy,reason,authorizedAt,confirmation}={}){
  if(confirmation!==CURRENT_DISPLAY_PUBLICATION_CONFIRMATION)throw new Error("CURRENT_DISPLAY_PUBLICATION_CONFIRMATION_REQUIRED");
  const d=deriveCurrentDisplayPublicationFacts({snapshot,products,retailers,destinations,rightsRegistry,atlasProductId:candidate?.binding?.atlasProductId,evaluatedAt:authorizedAt});
  if(candidate?.candidateDigest!==currentDisplayPublicationDigest(candidate.binding)||snapshot.snapshotId!==candidate.binding.snapshotId||d.snapshotDigest!==candidate.binding.snapshotDigest||d.publicFactsDigest!==candidate.binding.publicFactsDigest)throw new Error("CURRENT_DISPLAY_PUBLICATION_REPREPARE_REQUIRED");
  const binding={candidateId:candidate.candidateId,candidateDigest:candidate.candidateDigest,snapshotId:candidate.binding.snapshotId,snapshotDigest:candidate.binding.snapshotDigest,projectionDigest:candidate.binding.projectionDigest,publicFactsDigest:candidate.binding.publicFactsDigest,atlasProductId:candidate.binding.atlasProductId,publicationScope:candidate.binding.publicationScope,claimClass:candidate.binding.claimClass,publicFacts:candidate.binding.publicFacts,excludedClaims:candidate.binding.excludedClaims,expiresAt:d.expiresAt};const digest=currentDisplayPublicationDigest(binding),intent={binding,authorizedBy,reason,authorizedAt};
  return freeze({schemaVersion:"1.0",authorizationType:"CURRENT_DISPLAY_PUBLICATION",authorizationId:`mer_displaypubauth_${currentDisplayPublicationDigest(intent).slice(0,24)}`,authorizationDigest:digest,binding,authorizedBy,reason,authorizedAt,status:"AUTHORIZED",singleUse:true,publicationAuthority:true,artifactAuthority:true,releaseAuthority:false,deploymentAuthority:false,networkOperation:"NONE",paidTaskCreated:false,actualSpendUsd:0});
}

export function verifyCurrentDisplayArtifactAuthority({authorization,artifactProjection,evaluatedAt}={}){try{if(authorization?.authorizationType!=="CURRENT_DISPLAY_PUBLICATION"||authorization.status!=="AUTHORIZED"||authorization.authorizationDigest!==currentDisplayPublicationDigest(authorization.binding)||Date.parse(evaluatedAt)>Date.parse(authorization.binding.expiresAt))return false;const p=artifactProjection.products?.find(x=>x.atlasProductId===authorization.binding.atlasProductId);if(!p||artifactProjection.products.length!==1)return false;const facts={atlasProductId:p.atlasProductId,offers:p.offers.map(x=>({retailerId:x.retailerId,retailerName:x.retailerName,destinationId:x.destinationId,destinationUrl:x.destinationUrl,itemPriceUsd:x.itemPriceUsd,currency:x.currency,observedAt:x.observedAt,comparisonEligible:x.comparisonEligible})),lowerCurrentItemPrice:p.lowerCurrentItemPrice?{retailerId:p.lowerCurrentItemPrice.retailerId,retailerName:p.lowerCurrentItemPrice.retailerName,destinationId:p.lowerCurrentItemPrice.destinationId,itemPriceUsd:p.lowerCurrentItemPrice.itemPriceUsd,currency:p.lowerCurrentItemPrice.currency}:null,disclosure:artifactProjection.disclosure};return currentDisplayPublicationDigest(facts)===authorization.binding.publicFactsDigest;}catch{return false;}}
