import { createPublicationAuthorization, assertPublicationAuthorization, PUBLICATION_CONFIRMATIONS } from "./PublicationOperatorAuthorization.js";
const exact = (input, allowed, code) => { for (const key of Object.keys(input ?? {})) if (!allowed.includes(key)) throw new Error(`${code}:${key}`); };
const required = (value, code) => { if (typeof value !== "string" || !value.trim()) throw new TypeError(code); return value.trim(); };
const separation = { currentPriceAuthority: false, livePriceAuthority: false, publicPriceAuthority: false, cheapestAuthority: false, pickAuthority: false, rankingAuthority: false, recommendationAuthority: false, networkOperation: "NONE", paidTaskCreated: false, actualSpendUsd: 0 };
export class PublicationPrepareService {
  constructor({ assessmentService, authorizationRepository, now = () => new Date().toISOString() } = {}) { if (!assessmentService?.assess || !authorizationRepository?.record) throw new TypeError("PUBLICATION_PREPARE_DEPENDENCY_REQUIRED"); Object.assign(this, { assessmentService, authorizationRepository, now }); }
  async prepare(input = {}) { exact(input, ["observationId", "decision", "requestedBy", "reason", "ttlMinutes"], "PUBLICATION_PREPARE_CALLER_SUBSTITUTION_FORBIDDEN"); const preparedAt = this.now(), assessment = await this.assessmentService.assess({ observationId: required(input.observationId, "PUBLICATION_OBSERVATION_ID_REQUIRED"), decision: input.decision, asOf: preparedAt }); return this.authorizationRepository.record(createPublicationAuthorization({ assessment, requestedBy: input.requestedBy, reason: input.reason, preparedAt, ttlMinutes: input.ttlMinutes ?? 15 })); }
}
export class PublicationExecutor {
  constructor({ assessmentService, authorizationRepository, publicationWorkflowService, now = () => new Date().toISOString() } = {}) { if (!assessmentService?.assess || !authorizationRepository?.getById || !authorizationRepository?.getConsumption || !authorizationRepository?.consume || !publicationWorkflowService) throw new TypeError("PUBLICATION_EXECUTOR_DEPENDENCY_REQUIRED"); Object.assign(this, { assessmentService, authorizationRepository, publicationWorkflowService, now }); }
  async execute(input = {}) { exact(input, ["authorizationId", "confirmation", "executedBy"], "PUBLICATION_EXECUTE_CALLER_SUBSTITUTION_FORBIDDEN"); const id = required(input.authorizationId, "PUBLICATION_AUTHORIZATION_ID_REQUIRED"), operator = required(input.executedBy, "PUBLICATION_EXECUTED_BY_REQUIRED"), auth = await this.authorizationRepository.getById(id); if (!auth) throw new Error("PUBLICATION_AUTHORIZATION_NOT_FOUND"); if (input.confirmation !== PUBLICATION_CONFIRMATIONS[auth.decision]) throw new Error(`PUBLICATION_EXPLICIT_CONFIRMATION_REQUIRED:${PUBLICATION_CONFIRMATIONS[auth.decision]}`); if (operator !== auth.requestedBy) throw new Error("PUBLICATION_OPERATOR_SUBSTITUTION_BLOCKED"); const consumed = await this.authorizationRepository.getConsumption(id); if (consumed) return Object.freeze({ status: "ALREADY_CONSUMED", authorizationId: id, publicationDecisionId: consumed.publicationDecisionId, observationId: auth.observationId, decision: auth.decision, ...separation }); const executedAt = this.now(), assessment = await this.assessmentService.assess({ observationId: auth.observationId, decision: auth.decision, asOf: executedAt }); assertPublicationAuthorization({ authorization: auth, assessment, now: executedAt }); const args = { observationId: auth.observationId, authorizedBy: operator, authorizedAt: executedAt, reasonCodes: ["CONTROLLED_OPERATOR_AUTHORIZATION"], notes: auth.reason, governance: { authorizationId: id, candidateBindingDigest: auth.candidateBindingDigest, policyVersion: auth.policyVersion } }; const decision = auth.decision === "PUBLISH" ? await this.publicationWorkflowService.authorizePublish(args) : await this.publicationWorkflowService.withdraw(args); const record = await this.authorizationRepository.consume({ authorizationId: id, candidateBindingDigest: auth.candidateBindingDigest, publicationDecisionId: decision.publicationDecisionId }); return Object.freeze({ status: record.status === "ALREADY_CONSUMED" ? "ALREADY_CONSUMED" : "PUBLICATION_DECISION_RECORDED", authorizationId: id, publicationDecisionId: decision.publicationDecisionId, observationId: auth.observationId, decision: auth.decision, ...separation }); }
}
