import {scaleRampCanaryDigest,SCALE_RAMP_CANARY_SELECTION_POLICY_ID,SCALE_RAMP_CANARY_SELECTION_POLICY_VERSION} from "./DeterministicCanarySelector.js";

const hex=value=>typeof value==="string"&&/^[a-f0-9]{64}$/.test(value);
const text=(value,code)=>{if(typeof value!=="string"||!value.trim())throw new Error(code);return value.trim();};
const integer=(value,code)=>{if(!Number.isInteger(value)||value<=0)throw new Error(code);return value;};
const freeze=value=>Object.freeze(structuredClone(value));
const allowed=new Set(["schemaVersion","artifactType","status","stagePolicyId","stagePolicyVersion","policyId","policyVersion","stageId","stageCohortDigest","source","operation","requestedCanarySize","candidateCount","candidatePoolDigest","selectedMembers","selectedMemberDigest","strataSummary","diversitySummary","stableAtlasAttributes","selectionRationale","authority","providerCalls","paidTasks","actualSpendUsd","prepareAuthorized","executionAuthorized"]);
const member=value=>{if(!value||Object.keys(value).some(key=>!["atlasProductId","manufacturer","memoryGeneration","formFactor","capacityGb","moduleCount"].includes(key)))throw new Error("SCALE_RAMP_SELECTOR_PROPOSAL_MEMBER_INVALID");return{atlasProductId:text(value.atlasProductId,"SCALE_RAMP_SELECTOR_PROPOSAL_MEMBER_INVALID"),manufacturer:text(value.manufacturer,"SCALE_RAMP_SELECTOR_PROPOSAL_MEMBER_INVALID").normalize("NFC"),memoryGeneration:text(value.memoryGeneration,"SCALE_RAMP_SELECTOR_PROPOSAL_MEMBER_INVALID").toUpperCase(),formFactor:text(value.formFactor,"SCALE_RAMP_SELECTOR_PROPOSAL_MEMBER_INVALID").toUpperCase(),capacityGb:integer(value.capacityGb,"SCALE_RAMP_SELECTOR_PROPOSAL_MEMBER_INVALID"),moduleCount:integer(value.moduleCount,"SCALE_RAMP_SELECTOR_PROPOSAL_MEMBER_INVALID")};};

export function validateScaleRampSelectorProposal(value,{reference:ignoredReference=null}={}){
  if(!value||Object.keys(value).some(key=>!allowed.has(key)))throw new Error("SCALE_RAMP_SELECTOR_PROPOSAL_SCHEMA_INVALID");
  if(value.schemaVersion!=="1.0"||value.artifactType!=="MERCURY_SCALE_RAMP_CANARY_REVIEW"||value.status!=="REVIEW_ONLY")throw new Error("SCALE_RAMP_SELECTOR_PROPOSAL_SCHEMA_INVALID");
  if(value.policyId!==SCALE_RAMP_CANARY_SELECTION_POLICY_ID||value.policyVersion!==SCALE_RAMP_CANARY_SELECTION_POLICY_VERSION)throw new Error("SCALE_RAMP_SELECTOR_PROPOSAL_POLICY_UNSUPPORTED");
  if(value.authority!=="NONE"||value.prepareAuthorized!==false||value.executionAuthorized!==false||value.providerCalls!==0||value.paidTasks!==0||value.actualSpendUsd!==0)throw new Error("SCALE_RAMP_SELECTOR_PROPOSAL_AUTHORITY_INVALID");
  const selectedMembers=(Array.isArray(value.selectedMembers)?value.selectedMembers:[]).map(member),requestedCanarySize=integer(value.requestedCanarySize,"SCALE_RAMP_SELECTOR_PROPOSAL_SIZE_INVALID"),candidateCount=integer(value.candidateCount,"SCALE_RAMP_SELECTOR_PROPOSAL_CANDIDATE_COUNT_INVALID");
  if(selectedMembers.length!==requestedCanarySize||candidateCount<requestedCanarySize||new Set(selectedMembers.map(item=>item.atlasProductId)).size!==selectedMembers.length)throw new Error("SCALE_RAMP_SELECTOR_PROPOSAL_MEMBERSHIP_INVALID");
  const base={policyId:value.policyId,policyVersion:value.policyVersion,stageId:text(value.stageId,"SCALE_RAMP_SELECTOR_PROPOSAL_STAGE_INVALID"),stageCohortDigest:text(value.stageCohortDigest,"SCALE_RAMP_SELECTOR_PROPOSAL_STAGE_INVALID"),source:text(value.source,"SCALE_RAMP_SELECTOR_PROPOSAL_SOURCE_INVALID").toUpperCase(),operation:text(value.operation,"SCALE_RAMP_SELECTOR_PROPOSAL_OPERATION_INVALID").toUpperCase()};
  if(!hex(base.stageCohortDigest)||!hex(value.candidatePoolDigest)||!hex(value.selectedMemberDigest))throw new Error("SCALE_RAMP_SELECTOR_PROPOSAL_DIGEST_INVALID");
  if(scaleRampCanaryDigest({...base,candidatePoolDigest:value.candidatePoolDigest,requestedCanarySize,selectedMembers})!==value.selectedMemberDigest)throw new Error("SCALE_RAMP_SELECTOR_PROPOSAL_SELECTED_DIGEST_MISMATCH");
  const contract={schemaVersion:value.schemaVersion,artifactType:value.artifactType,status:value.status,stagePolicyId:text(value.stagePolicyId,"SCALE_RAMP_SELECTOR_PROPOSAL_STAGE_POLICY_INVALID"),stagePolicyVersion:text(value.stagePolicyVersion,"SCALE_RAMP_SELECTOR_PROPOSAL_STAGE_POLICY_INVALID"),...base,requestedCanarySize,candidateCount,candidatePoolDigest:value.candidatePoolDigest,selectedMembers,selectedMemberDigest:value.selectedMemberDigest,selectionRationale:text(value.selectionRationale,"SCALE_RAMP_SELECTOR_PROPOSAL_RATIONALE_INVALID"),authority:value.authority,prepareAuthorized:value.prepareAuthorized,executionAuthorized:value.executionAuthorized};
  const proposalDigest=scaleRampCanaryDigest(contract),proposalId=`mer_scaleproposal_${proposalDigest.slice(0,24)}`;
  void ignoredReference;return freeze({proposalId,proposalDigest,selectionInputType:"SELECTOR_PROPOSAL",proposalSchemaVersion:value.schemaVersion,proposalArtifactType:value.artifactType,stagePolicyId:contract.stagePolicyId,stagePolicyVersion:contract.stagePolicyVersion,stageId:base.stageId,stageCohortDigest:base.stageCohortDigest,selectorPolicyId:base.policyId,selectorPolicyVersion:base.policyVersion,candidateCount,candidatePoolDigest:value.candidatePoolDigest,selectedMemberDigest:value.selectedMemberDigest,requestedSelectorSize:requestedCanarySize,source:base.source,operation:base.operation,selectedAtlasProductIds:selectedMembers.map(item=>item.atlasProductId)});
}

export function selectorProposalCohort(provenance){
  if(provenance?.selectionInputType!=="SELECTOR_PROPOSAL"||!hex(provenance.proposalDigest)||!hex(provenance.stageCohortDigest)||!hex(provenance.candidatePoolDigest)||!hex(provenance.selectedMemberDigest)||!Array.isArray(provenance.selectedAtlasProductIds)||provenance.selectedAtlasProductIds.length!==provenance.requestedSelectorSize)throw new Error("SCALE_RAMP_SELECTOR_PROVENANCE_INCOMPLETE");
  const operationBySource={DATAFORSEO_AMAZON:"AMAZON_PRODUCTS",DATAFORSEO_GOOGLE_SHOPPING:"PRODUCTS"};
  if(operationBySource[provenance.source]!==provenance.operation)throw new Error("SCALE_RAMP_SELECTOR_PROPOSAL_OPERATION_UNSUPPORTED");
  return freeze(provenance.selectedAtlasProductIds.map(atlasProductId=>({atlasProductId,sourceId:provenance.source})));
}
