import {assessCanonicalObservationAdmission} from "./CanonicalObservationAdmissionPolicy.js";
import {projectIdentityReviewState} from "../identity-review/IdentityReviewProjection.js";
import {createDataForSeoMarketObservationCandidate} from "../market/dataforseo/DataForSeoMarketObservationCandidate.js";
import {createDataForSeoCanonicalObservation} from "../market/dataforseo/DataForSeoCanonicalObservation.js";
import {validateObservation} from "../ObservationValidator.js";

const required=(value,code)=>{if(typeof value!=="string"||!value.trim())throw new TypeError(code);return value.trim();};
export class CanonicalObservationAdmissionService{
 constructor({evidenceRepository,historicalRepository,decisionRepository,productRepository,retailerRepository,observationRepository,rightsRegistry,now=()=>new Date().toISOString()}={}){if(!observationRepository?.allocateObservationId||!observationRepository?.findByIdempotencyKey||!observationRepository?.getById||!observationRepository?.accept)throw new TypeError("CANONICAL_OBSERVATION_REPOSITORY_REQUIRED");Object.assign(this,{evidenceRepository,historicalRepository,decisionRepository,productRepository,retailerRepository,observationRepository,rightsRegistry,now});}
 async assess({evidenceId,identityReuseAssessments=[],policy}={}){return assessCanonicalObservationAdmission({evidenceId,evidenceRepository:this.evidenceRepository,historicalRepository:this.historicalRepository,decisionRepository:this.decisionRepository,productRepository:this.productRepository,retailerRepository:this.retailerRepository,identityReuseAssessments,rightsRegistry:this.rightsRegistry,policy});}
 async admit({evidenceId,admittedBy,identityReuseAssessments=[],policy}={}){required(evidenceId,"CANONICAL_EVIDENCE_ID_REQUIRED");required(admittedBy,"CANONICAL_ADMITTED_BY_REQUIRED");const assessment=await this.assess({evidenceId,identityReuseAssessments,policy});if(assessment.canonicalEligible!==true)throw new Error(`CANONICAL_ADMISSION_NOT_ELIGIBLE:${assessment.blockers.join(",")}`);
  const key=`E2P_CANONICAL_ADMISSION:${evidenceId}`,existing=await this.observationRepository.findByIdempotencyKey(key);if(existing){const [stored,record]=await Promise.all([this.observationRepository.getById(existing.observationId),this.evidenceRepository.getById(evidenceId)]),evidence=record?.candidate?.marketEvidence,materialMatches=stored&&stored.atlasProductId===assessment.candidateBinding.atlasProductId&&stored.retailerId===assessment.candidateBinding.retailerId&&stored.observationTime===evidence?.provenance?.observedAt&&stored.compliance?.licenseContext===assessment.candidateBinding.source&&stored.provenance?.acquisition?.requestId===assessment.candidateBinding.providerTaskId&&stored.provenance?.acquisition?.rawPayloadReference===assessment.candidateBinding.rawPayloadReference&&stored.offer?.price===evidence?.pricing?.basePrice&&stored.offer?.currency===evidence?.pricing?.currency&&stored.offer?.sourceUrl===evidence?.seller?.url;if(!materialMatches)throw new Error("CANONICAL_ADMISSION_REPLAY_CONFLICT");return Object.freeze({status:"DUPLICATE",evidenceId,observationId:existing.observationId,assessment});}
  const [record,decisions,remediations,retailers]=await Promise.all([this.evidenceRepository.getById(evidenceId),this.decisionRepository.getAll(),this.decisionRepository.getAllRemediations(),this.retailerRepository.getAll()]),projection=projectIdentityReviewState({record,decisions,remediations,identityReuseAssessments,atlasRetailers:retailers}),candidate=createDataForSeoMarketObservationCandidate({marketEvidence:record.candidate.marketEvidence,atlasResolution:{outcome:"CONFIRMED",atlasProductId:projection.product.atlasProductId,externalProductId:record.candidate.identity.externalProductId,evidence:record.candidate.identity.evidence,automaticMercuryEligible:true}}),merchantResolution=projection.merchant.atlasResolution,observationId=await this.observationRepository.allocateObservationId(),createdAt=this.now(),observation=createDataForSeoCanonicalObservation({observationId,candidate,merchantResolution,createdAt,createdBy:admittedBy.trim(),normalizedAt:createdAt}),validation=validateObservation(observation);if(!validation.valid)throw new Error(`CANONICAL_ADMISSION_OBSERVATION_INVALID:${validation.errors.map(item=>item.code).join(",")}`);
  const accepted=await this.observationRepository.accept(observation,key);return Object.freeze({status:accepted.status==="DUPLICATE"?"DUPLICATE":"CANONICAL_ADMITTED",evidenceId,observationId:accepted.observationId,observation,assessment:Object.freeze({...assessment,canonicalAdmitted:true,reviewEligible:true,publicationEligible:false,publicationAuthority:false})});
 }
}
export default CanonicalObservationAdmissionService;
