import crypto from "node:crypto";
import {canonicalAdmissionCandidateBindingDigest,validateCanonicalAdmissionAuthorization} from "./CanonicalAdmissionAuthorization.js";

const stable=value=>{if(Array.isArray(value))return `[${value.map(stable).join(",")}]`;if(value&&typeof value==="object")return `{${Object.keys(value).sort().map(key=>`${JSON.stringify(key)}:${stable(value[key])}`).join(",")}}`;return JSON.stringify(value);};
const hash=value=>crypto.createHash("sha256").update(stable(value)).digest("hex");
const freeze=value=>{if(value&&typeof value==="object"&&!Object.isFrozen(value)){Object.freeze(value);for(const child of Object.values(value))freeze(child);}return value;};

export function validateCanonicalAdmissionAuthorizationSupersession(value){const errors=[];if(value?.schemaVersion!=="1.0"||value?.eventType!=="CANONICAL_AUTHORIZATION_SUPERSESSION")errors.push("CANONICAL_SUPERSESSION_SCHEMA_INVALID");for(const field of ["supersessionId","intentKey","evidenceId","lineageRootAuthorizationId","predecessorAuthorizationId","successorAuthorizationId","predecessorAssessmentId","successorAssessmentId","predecessorBindingDigest","successorBindingDigest","supersededAt","supersededBy","reason"])if(typeof value?.[field]!=="string"||!value[field].trim())errors.push(`CANONICAL_SUPERSESSION_${field.toUpperCase()}_REQUIRED`);if(!Number.isFinite(Date.parse(value?.supersededAt))||!Number.isFinite(Date.parse(value?.predecessorExpiresAt)))errors.push("CANONICAL_SUPERSESSION_TIME_INVALID");if(!Number.isInteger(value?.generation)||value.generation<1||!["EXACT_BINDING","CHANGED_BINDING"].includes(value?.bindingChange)||!/^[a-f0-9]{64}$/.test(value?.predecessorBindingDigest??"")||!/^[a-f0-9]{64}$/.test(value?.successorBindingDigest??""))errors.push("CANONICAL_SUPERSESSION_LINEAGE_INVALID");const material={intentKey:value?.intentKey,evidenceId:value?.evidenceId,lineageRootAuthorizationId:value?.lineageRootAuthorizationId,predecessorAuthorizationId:value?.predecessorAuthorizationId,successorAuthorizationId:value?.successorAuthorizationId,predecessorAssessmentId:value?.predecessorAssessmentId,successorAssessmentId:value?.successorAssessmentId,predecessorBindingDigest:value?.predecessorBindingDigest,successorBindingDigest:value?.successorBindingDigest,generation:value?.generation,bindingChange:value?.bindingChange,supersededBy:value?.supersededBy,reason:value?.reason};if(value?.supersessionId!==`mer_cansup_${hash(material).slice(0,24)}`)errors.push("CANONICAL_SUPERSESSION_ID_INVALID");return freeze({valid:errors.length===0,errors});}

export function createCanonicalAdmissionAuthorizationSupersession({predecessor,successor,supersededAt=new Date().toISOString()}={}){if(!validateCanonicalAdmissionAuthorization(predecessor).valid||!validateCanonicalAdmissionAuthorization(successor).valid)throw new Error("CANONICAL_SUPERSESSION_AUTHORIZATION_INVALID");const lineage=successor.lineage;if(successor.evidenceId!==predecessor.evidenceId||lineage?.predecessorAuthorizationId!==predecessor.authorizationId||lineage?.predecessorAssessmentId!==predecessor.assessmentId||lineage?.predecessorCandidateBindingDigest!==predecessor.candidateBindingDigest||canonicalAdmissionCandidateBindingDigest(successor.candidateBinding)!==successor.candidateBindingDigest)throw new Error("CANONICAL_SUPERSESSION_BINDING_INVALID");const material={intentKey:`CANONICAL_OBSERVATION_ADMISSION:${predecessor.evidenceId}`,evidenceId:predecessor.evidenceId,lineageRootAuthorizationId:lineage.rootAuthorizationId,predecessorAuthorizationId:predecessor.authorizationId,successorAuthorizationId:successor.authorizationId,predecessorAssessmentId:predecessor.assessmentId,successorAssessmentId:successor.assessmentId,predecessorBindingDigest:predecessor.candidateBindingDigest,successorBindingDigest:successor.candidateBindingDigest,generation:lineage.generation,bindingChange:lineage.bindingChange,supersededBy:successor.requestedBy,reason:successor.reason},event={schemaVersion:"1.0",eventType:"CANONICAL_AUTHORIZATION_SUPERSESSION",...material,predecessorExpiresAt:predecessor.expiresAt,supersededAt,supersessionId:`mer_cansup_${hash(material).slice(0,24)}`};const report=validateCanonicalAdmissionAuthorizationSupersession(event);if(!report.valid)throw new TypeError(report.errors.join(","));return freeze(event);}

export function effectiveCanonicalAdmissionAuthorizationLifecycle({authorization,consumption=null,supersession=null,asOf=new Date().toISOString()}={}){if(!validateCanonicalAdmissionAuthorization(authorization).valid||!Number.isFinite(Date.parse(asOf)))throw new Error("CANONICAL_AUTHORIZATION_LIFECYCLE_INPUT_INVALID");if(consumption)return "CONSUMED";if(supersession)return "SUPERSEDED";return Date.parse(asOf)>=Date.parse(authorization.expiresAt)?"EXPIRED":"PENDING_OPERATOR_APPROVAL";}
