import crypto from "node:crypto";

export const CANONICAL_ADMISSION_CONFIRMATION="ADMIT-CANONICAL-OBSERVATION";
export const CANONICAL_ADMISSION_SUPERSESSION_CONFIRMATION="SUPERSEDE-EXPIRED-CANONICAL-AUTHORIZATION";
const stable=value=>{if(Array.isArray(value))return `[${value.map(stable).join(",")}]`;if(value&&typeof value==="object")return `{${Object.keys(value).sort().map(key=>`${JSON.stringify(key)}:${stable(value[key])}`).join(",")}}`;return JSON.stringify(value);};
const hash=value=>crypto.createHash("sha256").update(stable(value)).digest("hex");
const freeze=value=>{if(value&&typeof value==="object"&&!Object.isFrozen(value)){Object.freeze(value);for(const child of Object.values(value))freeze(child);}return value;};
const required=(value,code)=>{if(typeof value!=="string"||!value.trim())throw new TypeError(code);return value.trim();};
const iso=(value,code)=>{if(typeof value!=="string"||!Number.isFinite(Date.parse(value)))throw new TypeError(code);return value;};
export const canonicalAdmissionCandidateBindingDigest=binding=>hash(binding);

export function validateCanonicalAdmissionAuthorization(value){const errors=[];if(!["1.0","1.1"].includes(value?.schemaVersion)||value?.authorizationType!=="CANONICAL_OBSERVATION_ADMISSION"||value?.status!=="PENDING_OPERATOR_APPROVAL")errors.push("CANONICAL_AUTHORIZATION_SCHEMA_INVALID");for(const field of ["authorizationId","evidenceId","assessmentId","policyVersion","candidateBindingDigest","requestedBy","reason"])if(typeof value?.[field]!=="string"||!value[field].trim())errors.push(`CANONICAL_AUTHORIZATION_${field.toUpperCase()}_REQUIRED`);if(!Number.isFinite(Date.parse(value?.preparedAt))||!Number.isFinite(Date.parse(value?.expiresAt))||Date.parse(value?.expiresAt)<=Date.parse(value?.preparedAt))errors.push("CANONICAL_AUTHORIZATION_TIME_INVALID");if(!value?.candidateBinding||canonicalAdmissionCandidateBindingDigest(value.candidateBinding)!==value?.candidateBindingDigest||value?.candidateBinding?.evidenceId!==value?.evidenceId)errors.push("CANONICAL_AUTHORIZATION_BINDING_INVALID");if(value?.schemaVersion==="1.1"){const lineage=value.lineage;if(!lineage||typeof lineage.rootAuthorizationId!=="string"||!lineage.rootAuthorizationId||typeof lineage.predecessorAuthorizationId!=="string"||!lineage.predecessorAuthorizationId||!Number.isInteger(lineage.generation)||lineage.generation<1||!["EXACT_BINDING","CHANGED_BINDING"].includes(lineage.bindingChange)||typeof lineage.predecessorAssessmentId!=="string"||!lineage.predecessorAssessmentId||!/^[a-f0-9]{64}$/.test(lineage.predecessorCandidateBindingDigest??""))errors.push("CANONICAL_AUTHORIZATION_LINEAGE_INVALID");}else if(value?.lineage!=null)errors.push("CANONICAL_AUTHORIZATION_LINEAGE_INVALID");if(value?.singleUse!==true||value?.networkOperation!=="NONE"||value?.paidTaskCreated!==false||value?.actualSpendUsd!==0||value?.reviewApproved!==false||value?.publicationEligible!==false||value?.publicationAuthority!==false||value?.currentPriceAuthority!==false||value?.livePriceAuthority!==false||value?.publicPriceAuthority!==false)errors.push("CANONICAL_AUTHORIZATION_SCOPE_INVALID");return freeze({valid:errors.length===0,errors});}

export function createCanonicalAdmissionAuthorization({assessment,requestedBy,reason,preparedAt=new Date().toISOString(),ttlMinutes=15}={}){if(assessment?.assessmentType!=="CANONICAL_OBSERVATION_ADMISSION"||assessment?.canonicalEligible!==true||assessment?.historicalAdmitted!==true||assessment?.publicationEligible!==false||assessment?.publicationAuthority!==false)throw new Error("CANONICAL_ASSESSMENT_NOT_AUTHORIZABLE");const candidateBinding=structuredClone(assessment.candidateBinding),candidateBindingDigest=canonicalAdmissionCandidateBindingDigest(candidateBinding);iso(preparedAt,"CANONICAL_AUTHORIZATION_TIME_INVALID");if(!Number.isInteger(ttlMinutes)||ttlMinutes<1)throw new TypeError("CANONICAL_AUTHORIZATION_TTL_INVALID");const intent={evidenceId:candidateBinding.evidenceId,assessmentId:assessment.assessmentId,policyVersion:assessment.policyVersion,candidateBindingDigest,requestedBy:required(requestedBy,"CANONICAL_AUTHORIZATION_REQUESTED_BY_REQUIRED"),reason:required(reason,"CANONICAL_AUTHORIZATION_REASON_REQUIRED")},record={schemaVersion:"1.0",authorizationType:"CANONICAL_OBSERVATION_ADMISSION",authorizationId:`mer_canauth_${hash(intent).slice(0,24)}`,...intent,candidateBinding,preparedAt,expiresAt:new Date(Date.parse(preparedAt)+ttlMinutes*60000).toISOString(),status:"PENDING_OPERATOR_APPROVAL",singleUse:true,canonicalAdmissionAuthorized:true,reviewApproved:false,publicationEligible:false,publicationAuthority:false,currentPriceAuthority:false,livePriceAuthority:false,publicPriceAuthority:false,networkOperation:"NONE",paidTaskCreated:false,actualSpendUsd:0};const report=validateCanonicalAdmissionAuthorization(record);if(!report.valid)throw new TypeError(report.errors.join(","));return freeze(record);}

export function createCanonicalAdmissionSuccessorAuthorization({predecessor,assessment,requestedBy,reason,preparedAt=new Date().toISOString(),ttlMinutes=15}={}){const predecessorReport=validateCanonicalAdmissionAuthorization(predecessor);if(!predecessorReport.valid)throw new Error(`CANONICAL_PREDECESSOR_INVALID:${predecessorReport.errors.join(",")}`);if(assessment?.assessmentType!=="CANONICAL_OBSERVATION_ADMISSION"||assessment?.canonicalEligible!==true||assessment?.historicalAdmitted!==true||assessment?.publicationEligible!==false||assessment?.publicationAuthority!==false)throw new Error("CANONICAL_ASSESSMENT_NOT_AUTHORIZABLE");const candidateBinding=structuredClone(assessment.candidateBinding),candidateBindingDigest=canonicalAdmissionCandidateBindingDigest(candidateBinding);if(candidateBinding?.evidenceId!==predecessor.evidenceId)throw new Error("CANONICAL_SUCCESSOR_EVIDENCE_MISMATCH");iso(preparedAt,"CANONICAL_AUTHORIZATION_TIME_INVALID");if(!Number.isInteger(ttlMinutes)||ttlMinutes<1)throw new TypeError("CANONICAL_AUTHORIZATION_TTL_INVALID");const operator=required(requestedBy,"CANONICAL_AUTHORIZATION_REQUESTED_BY_REQUIRED"),explanation=required(reason,"CANONICAL_AUTHORIZATION_REASON_REQUIRED"),generation=(predecessor.lineage?.generation??0)+1,rootAuthorizationId=predecessor.lineage?.rootAuthorizationId??predecessor.authorizationId,bindingChange=candidateBindingDigest===predecessor.candidateBindingDigest?"EXACT_BINDING":"CHANGED_BINDING",intent={predecessorAuthorizationId:predecessor.authorizationId,evidenceId:predecessor.evidenceId,assessmentId:assessment.assessmentId,policyVersion:assessment.policyVersion,candidateBindingDigest,requestedBy:operator,reason:explanation},record={schemaVersion:"1.1",authorizationType:"CANONICAL_OBSERVATION_ADMISSION",authorizationId:`mer_canauth_${hash(intent).slice(0,24)}`,evidenceId:predecessor.evidenceId,assessmentId:assessment.assessmentId,policyVersion:assessment.policyVersion,candidateBindingDigest,requestedBy:operator,reason:explanation,candidateBinding,preparedAt,expiresAt:new Date(Date.parse(preparedAt)+ttlMinutes*60000).toISOString(),status:"PENDING_OPERATOR_APPROVAL",lineage:{rootAuthorizationId,predecessorAuthorizationId:predecessor.authorizationId,generation,bindingChange,predecessorAssessmentId:predecessor.assessmentId,predecessorCandidateBindingDigest:predecessor.candidateBindingDigest},singleUse:true,canonicalAdmissionAuthorized:true,reviewApproved:false,publicationEligible:false,publicationAuthority:false,currentPriceAuthority:false,livePriceAuthority:false,publicPriceAuthority:false,networkOperation:"NONE",paidTaskCreated:false,actualSpendUsd:0};const report=validateCanonicalAdmissionAuthorization(record);if(!report.valid)throw new TypeError(report.errors.join(","));return freeze(record);}

export function assertCanonicalAdmissionConfirmation(value){if(value!==CANONICAL_ADMISSION_CONFIRMATION)throw new Error(`EXPLICIT_CONFIRMATION_REQUIRED:--confirm=${CANONICAL_ADMISSION_CONFIRMATION}`);return true;}
export function assertCanonicalAdmissionSupersessionConfirmation(value){if(value!==CANONICAL_ADMISSION_SUPERSESSION_CONFIRMATION)throw new Error(`EXPLICIT_CONFIRMATION_REQUIRED:--confirm=${CANONICAL_ADMISSION_SUPERSESSION_CONFIRMATION}`);return true;}
export function assertCanonicalAdmissionAuthorization({authorization,assessment,now=new Date().toISOString()}={}){const report=validateCanonicalAdmissionAuthorization(authorization);if(!report.valid)throw new Error(`CANONICAL_AUTHORIZATION_INVALID:${report.errors.join(",")}`);iso(now,"CANONICAL_AUTHORIZATION_NOW_INVALID");if(Date.parse(now)>=Date.parse(authorization.expiresAt))throw new Error("CANONICAL_AUTHORIZATION_EXPIRED");if(assessment?.canonicalEligible!==true||authorization.assessmentId!==assessment.assessmentId||authorization.policyVersion!==assessment.policyVersion||authorization.evidenceId!==assessment.candidateBinding?.evidenceId||authorization.candidateBindingDigest!==canonicalAdmissionCandidateBindingDigest(assessment.candidateBinding)||stable(authorization.candidateBinding)!==stable(assessment.candidateBinding))throw new Error("CANONICAL_AUTHORIZATION_BINDING_MISMATCH");return true;}
