import crypto from "node:crypto";
import {assessDataForSeoEvidencePromotion} from "../market/dataforseo/DataForSeoEvidencePromotionAssessment.js";
import {defaultSourceRightsRegistry} from "../rights/SourceRightsRegistry.js";
import {RIGHTS_STATES} from "../rights/SourceRightsPolicy.js";
import {createHistoricalObservationId} from "../historical-admission/HistoricalObservation.js";

export const CANONICAL_OBSERVATION_ADMISSION_POLICY_VERSION="DF004-E2P-1.0";
const stable=value=>{if(Array.isArray(value))return `[${value.map(stable).join(",")}]`;if(value&&typeof value==="object")return `{${Object.keys(value).sort().map(key=>`${JSON.stringify(key)}:${stable(value[key])}`).join(",")}}`;return JSON.stringify(value);};
const hash=value=>crypto.createHash("sha256").update(stable(value)).digest("hex");
const freeze=value=>{if(value&&typeof value==="object"&&!Object.isFrozen(value)){Object.freeze(value);for(const child of Object.values(value))freeze(child);}return value;};
const canonicalRightsProfile=defaultSourceRightsRegistry.require("DATAFORSEO_GOOGLE_SHOPPING");
export const canonicalObservationAdmissionPolicy=freeze({policyVersion:CANONICAL_OBSERVATION_ADMISSION_POLICY_VERSION,sourceId:"DATAFORSEO_GOOGLE_SHOPPING",rightsProfileHash:hash(canonicalRightsProfile),requiredRights:["acquisition.api","live.currentObservation","retention.historical","retention.durableAuditMetadata"],historicalAdmissionRequired:true,publicationEligible:false});
const stateAt=(profile,path)=>path.split(".").reduce((value,key)=>value?.[key],profile);
const result=({eligible=false,reasons=[],binding=null,policy=canonicalObservationAdmissionPolicy,historicalAssessment=null,identityProjection=null}={})=>freeze({schemaVersion:"1.0",assessmentType:"CANONICAL_OBSERVATION_ADMISSION",assessmentId:`mer_canassess_${hash({policyVersion:policy?.policyVersion??null,binding,reasons}).slice(0,24)}`,policyVersion:policy?.policyVersion??null,candidateBinding:binding,identityProjection,historicalEligible:historicalAssessment?.historicalEligible===true,historicalAdmitted:Boolean(binding?.historicalObservationId),canonicalEligible:eligible,canonicalAdmitted:false,reviewEligible:false,publicationEligible:false,publicationAuthority:false,reasons:[...reasons],blockers:eligible?[]:[...reasons],mutationAuthorized:false,networkOperation:"NONE",paidTaskCreated:false,actualSpendUsd:0});

export async function assessCanonicalObservationAdmission({evidenceId,evidenceRepository,historicalRepository,decisionRepository,productRepository,retailerRepository,identityReuseAssessments=[],rightsRegistry=defaultSourceRightsRegistry,policy=canonicalObservationAdmissionPolicy}={}){
 const reasons=[];if(typeof evidenceId!=="string"||!evidenceId.trim())return result({reasons:["CANONICAL_CANDIDATE_EVIDENCE_ID_REQUIRED"],policy});
 if(!evidenceRepository?.getById||!historicalRepository?.getAll||!decisionRepository?.getAll||!decisionRepository?.getAllRemediations||!productRepository?.getById||!retailerRepository?.getAll||!rightsRegistry?.get)return result({reasons:["CANONICAL_GOVERNED_OWNER_MISSING"],policy});
 if(!policy||policy.policyVersion!==CANONICAL_OBSERVATION_ADMISSION_POLICY_VERSION||policy.sourceId!==canonicalObservationAdmissionPolicy.sourceId||policy.rightsProfileHash!==canonicalObservationAdmissionPolicy.rightsProfileHash)reasons.push("CANONICAL_POLICY_MISSING_OR_UNSUPPORTED");
 const record=await evidenceRepository.getById(evidenceId);if(!record)return result({reasons:[...reasons,"CANONICAL_CANDIDATE_EVIDENCE_NOT_FOUND"],policy});
 const retainedBefore=structuredClone(record),[history,decisions,remediations,retailers,evidenceRecords]=await Promise.all([historicalRepository.getAll(),decisionRepository.getAll(),decisionRepository.getAllRemediations(),retailerRepository.getAll(),evidenceRepository.getAll?evidenceRepository.getAll():[record]]);
 if(![history,decisions,remediations,retailers,evidenceRecords].every(Array.isArray))return result({reasons:[...reasons,"CANONICAL_GOVERNED_STATE_MALFORMED"],policy});
 const historicalMatches=history.filter(item=>item?.provenance?.retainedEvidenceId===evidenceId);if(historicalMatches.length!==1)reasons.push(historicalMatches.length?"CANONICAL_HISTORICAL_ADMISSION_CONFLICT":"CANONICAL_HISTORICAL_ADMISSION_MISSING");
 const historical=historicalMatches[0]??null,assessment=assessDataForSeoEvidencePromotion({records:[record],identityReviewDecisions:decisions,identityReviewRemediations:remediations,identityReuseAssessments,identityLineageEvidenceRecords:evidenceRecords,historicalObservations:history,atlasRetailers:retailers}),projection=assessment.identityProjections?.find(value=>value.evidenceId===record.evidenceId)??null;if(!projection)reasons.push("CANONICAL_IDENTITY_PROJECTION_INVALID");
 if(assessment.state!=="HISTORICAL_ELIGIBLE"||assessment.historicalEligible!==true)reasons.push("CANONICAL_HISTORICAL_ELIGIBILITY_REQUIRED");
 if(projection?.product?.state!=="VERIFIED")reasons.push("CANONICAL_PRODUCT_IDENTITY_NOT_VERIFIED");if(projection?.merchant?.state!=="REGISTERED"||projection?.merchant?.atlasResolution?.outcome!=="RESOLVED")reasons.push("CANONICAL_RETAILER_IDENTITY_NOT_REGISTERED");
 const product=projection?.product?.atlasProductId?await productRepository.getById(projection.product.atlasProductId):null,retailer=retailers.find(item=>item?.id===projection?.merchant?.merchantId);if(product?.identity?.atlasProductId!==projection?.product?.atlasProductId)reasons.push("CANONICAL_ATLAS_PRODUCT_MISSING_OR_CONFLICTING");if(!retailer)reasons.push("CANONICAL_ATLAS_RETAILER_MISSING_OR_CONFLICTING");
 const evidence=record.candidate?.marketEvidence,profile=rightsRegistry.get(evidence?.source);if(!profile||profile.sourceId!==policy?.sourceId||hash(profile)!==policy?.rightsProfileHash)reasons.push("CANONICAL_RIGHTS_PROFILE_MISSING_OR_SUBSTITUTED");else for(const capability of policy.requiredRights??[])if(stateAt(profile,capability)!==RIGHTS_STATES.ALLOWED)reasons.push(`CANONICAL_RIGHT_${capability.replaceAll(".","_").toUpperCase()}_NOT_ALLOWED`);
 const binding=freeze({evidenceId:record.evidenceId,historicalObservationId:historical?.observationId??null,atlasProductId:projection?.product?.atlasProductId??null,retailerId:projection?.merchant?.merchantId??null,provider:evidence?.provider??null,source:evidence?.source??null,providerTaskId:evidence?.provenance?.sourceTaskId??null,rawPayloadReference:evidence?.provenance?.rawPayloadReference??null,rightsProfileHash:profile?hash(profile):null,evidenceHash:hash(record),historicalObservationHash:historical?hash(historical):null});
 if(historical&&historical.observationId!==createHistoricalObservationId(evidenceId))reasons.push("CANONICAL_HISTORICAL_OBSERVATION_ID_SUBSTITUTION");
 if(historical&&(historical.atlasProductId!==binding.atlasProductId||historical.retailerId!==binding.retailerId))reasons.push("CANONICAL_HISTORICAL_IDENTITY_SUBSTITUTION");if(historical&&(historical.provenance?.rawPayloadReference!==binding.rawPayloadReference||historical.provenance?.acquisition?.sellersTaskId!==binding.providerTaskId))reasons.push("CANONICAL_PROVENANCE_SUBSTITUTION");if(evidence?.provider!=="DATAFORSEO"||evidence?.source!==policy?.sourceId)reasons.push("CANONICAL_PROVIDER_SOURCE_BINDING_INVALID");
 if(JSON.stringify(record)!==JSON.stringify(retainedBefore))throw new Error("CANONICAL_ASSESSMENT_MUTATED_EVIDENCE");return result({eligible:reasons.length===0,reasons,binding,policy,historicalAssessment:assessment,identityProjection:projection});
}

export const canonicalAdmissionMaterialHash=hash;
