import {assessCanonicalObservationAdmission} from "./CanonicalObservationAdmissionPolicy.js";
import {createDataForSeoMarketObservationCandidate} from "../market/dataforseo/DataForSeoMarketObservationCandidate.js";
import {createDataForSeoCanonicalObservation} from "../market/dataforseo/DataForSeoCanonicalObservation.js";
import {validateObservation} from "../ObservationValidator.js";

const required=(value,code)=>{if(typeof value!=="string"||!value.trim())throw new TypeError(code);return value.trim();};
export class CanonicalObservationAdmissionService{
 constructor({evidenceRepository,historicalRepository,decisionRepository,productRepository,retailerRepository,observationRepository,identityReuseResolver=null,initialAcquisitionCompositionResolver=null,rightsRegistry,now=()=>new Date().toISOString()}={}){if(!observationRepository?.allocateObservationId||!observationRepository?.findByIdempotencyKey||!observationRepository?.getById||!observationRepository?.accept)throw new TypeError("CANONICAL_OBSERVATION_REPOSITORY_REQUIRED");if(identityReuseResolver!==null&&typeof identityReuseResolver!=="function")throw new TypeError("CANONICAL_IDENTITY_REUSE_RESOLVER_INVALID");if(initialAcquisitionCompositionResolver!==null&&typeof initialAcquisitionCompositionResolver!=="function")throw new TypeError("CANONICAL_INITIAL_ACQUISITION_RESOLVER_INVALID");Object.assign(this,{evidenceRepository,historicalRepository,decisionRepository,productRepository,retailerRepository,observationRepository,identityReuseResolver,initialAcquisitionCompositionResolver,rightsRegistry,now});}
 async _identityReuse(evidenceId,provided){if(provided!==null)return provided;if(!this.identityReuseResolver)return [];const record=await this.evidenceRepository.getById(evidenceId),governance=record?await this.identityReuseResolver(record):null;return governance?.identityReuseAssessments??[];}
 async _initial(evidenceId){if(!this.initialAcquisitionCompositionResolver)return [];const record=await this.evidenceRepository.getById(evidenceId);if(!record)return [];const evidenceRecords=this.evidenceRepository.getAll?await this.evidenceRepository.getAll():[record],context=await this.initialAcquisitionCompositionResolver({record,evidenceRecords});return context?.initialAcquisitionIdentityProjections??[];}
 async assess({evidenceId,identityReuseAssessments=null,policy}={}){const [reuse,initial]=await Promise.all([this._identityReuse(evidenceId,identityReuseAssessments),this._initial(evidenceId)]);return assessCanonicalObservationAdmission({evidenceId,evidenceRepository:this.evidenceRepository,historicalRepository:this.historicalRepository,decisionRepository:this.decisionRepository,productRepository:this.productRepository,retailerRepository:this.retailerRepository,identityReuseAssessments:reuse,initialAcquisitionIdentityProjections:initial,rightsRegistry:this.rightsRegistry,policy});}
 async admit({evidenceId,admittedBy,identityReuseAssessments=null,policy}={}){required(evidenceId,"CANONICAL_EVIDENCE_ID_REQUIRED");required(admittedBy,"CANONICAL_ADMITTED_BY_REQUIRED");const assessment=await this.assess({evidenceId,identityReuseAssessments,policy});if(assessment.canonicalEligible!==true)throw new Error(`CANONICAL_ADMISSION_NOT_ELIGIBLE:${assessment.blockers.join(",")}`);
  const key=`E2P_CANONICAL_ADMISSION:${evidenceId}`,record=await this.evidenceRepository.getById(evidenceId),projection=assessment.identityProjection;if(!projection)throw new Error("CANONICAL_ADMISSION_GOVERNED_PROJECTION_MISSING");const evidence=record?.candidate?.marketEvidence,candidate=createDataForSeoMarketObservationCandidate({marketEvidence:evidence,atlasResolution:{outcome:"CONFIRMED",atlasProductId:projection.product.atlasProductId,externalProductId:record.candidate.identity.externalProductId,evidence:record.candidate.identity.evidence,automaticMercuryEligible:true}}),merchantResolution=projection.merchant.atlasResolution,existing=await this.observationRepository.findByIdempotencyKey(key);if(existing){const stored=await this.observationRepository.getById(existing.observationId),storedTime=Date.parse(stored?.observationTime),evidenceTime=Date.parse(evidence?.provenance?.observedAt),materialMatches=stored&&Number.isFinite(storedTime)&&Number.isFinite(evidenceTime)&&storedTime===evidenceTime&&stored.atlasProductId===assessment.candidateBinding.atlasProductId&&stored.retailerId===assessment.candidateBinding.retailerId&&stored.compliance?.licenseContext===assessment.candidateBinding.source&&stored.provenance?.acquisition?.requestId===assessment.candidateBinding.providerTaskId&&stored.provenance?.acquisition?.rawPayloadReference===assessment.candidateBinding.rawPayloadReference&&stored.offer?.price===evidence?.pricing?.basePrice&&stored.offer?.currency===evidence?.pricing?.currency&&stored.offer?.sourceUrl===evidence?.seller?.url;if(!materialMatches)throw new Error("CANONICAL_ADMISSION_REPLAY_CONFLICT");return Object.freeze({status:"DUPLICATE",evidenceId,observationId:existing.observationId,assessment});}
  const createdAt=this.now(),build=observationId=>createDataForSeoCanonicalObservation({observationId,candidate,merchantResolution,createdAt,createdBy:admittedBy.trim(),normalizedAt:createdAt}),provisional=build("mer_obs_000000000"),provisionalValidation=validateObservation(provisional);if(!provisionalValidation.valid)throw new Error(`CANONICAL_ADMISSION_OBSERVATION_INVALID:${provisionalValidation.errors.map(item=>item.code).join(",")}`);const observationId=await this.observationRepository.allocateObservationId(),observation=build(observationId),validation=validateObservation(observation);if(!validation.valid)throw new Error(`CANONICAL_ADMISSION_OBSERVATION_INVALID:${validation.errors.map(item=>item.code).join(",")}`);
  const accepted=await this.observationRepository.accept(observation,key);return Object.freeze({status:accepted.status==="DUPLICATE"?"DUPLICATE":"CANONICAL_ADMITTED",evidenceId,observationId:accepted.observationId,observation,assessment:Object.freeze({...assessment,canonicalAdmitted:true,reviewEligible:true,publicationEligible:false,publicationAuthority:false})});
 }
}
export default CanonicalObservationAdmissionService;
