import {mkdir,readFile,rename,writeFile} from "node:fs/promises";
import {dirname,resolve} from "node:path";
import {validateCanonicalAdmissionAuthorization} from "./CanonicalAdmissionAuthorization.js";
import {effectiveCanonicalAdmissionAuthorizationLifecycle,validateCanonicalAdmissionAuthorizationSupersession} from "./CanonicalAdmissionAuthorizationSupersession.js";
import {FileSingleWriterRunLock,SINGLE_WRITER_LOCK_STATUSES} from "../runtime/FileSingleWriterRunLock.js";

const initial=()=>({version:"1.1",authorizations:{},byEvidence:{},activeAuthorizationByIntent:{},supersessions:{},consumptions:{}}),clone=structuredClone,freeze=value=>Object.freeze(value),intentKey=evidenceId=>`CANONICAL_OBSERVATION_ADMISSION:${evidenceId}`;

export class FileCanonicalAdmissionAuthorizationRepository{
  constructor({statePath,now=()=>new Date().toISOString(),runLock}={}){if(!statePath)throw new TypeError("statePath is required.");this.statePath=resolve(statePath);this.now=now;this.queue=Promise.resolve();this.runLock=runLock??new FileSingleWriterRunLock({lockPath:`${this.statePath}.lock`,now});}
  async _lock(fn){const run=async()=>{const outcome=await this.runLock.runExclusive(fn);if(outcome.status!==SINGLE_WRITER_LOCK_STATUSES.COMPLETED)throw new Error("CANONICAL_AUTHORIZATION_REPOSITORY_BUSY");return outcome.result;},task=this.queue.then(run,run);this.queue=task.catch(()=>{});return task;}
  _validateState(state){
    if(!["1.0","1.1"].includes(state?.version)||!state.authorizations||!state.byEvidence||!state.consumptions)throw new Error("CANONICAL_AUTHORIZATION_STATE_INVALID");
    for(const [id,record] of Object.entries(state.authorizations))if(id!==record.authorizationId||!validateCanonicalAdmissionAuthorization(record).valid)throw new Error("CANONICAL_AUTHORIZATION_STATE_INVALID");
    for(const [evidenceId,id] of Object.entries(state.byEvidence))if(state.authorizations[id]?.evidenceId!==evidenceId)throw new Error("CANONICAL_AUTHORIZATION_STATE_INVALID");
    if(state.version==="1.0")return {...state,version:"1.1",activeAuthorizationByIntent:Object.fromEntries(Object.entries(state.byEvidence).map(([evidenceId,id])=>[intentKey(evidenceId),id])),supersessions:{}};
    if(!state.activeAuthorizationByIntent||!state.supersessions)throw new Error("CANONICAL_AUTHORIZATION_STATE_INVALID");
    const predecessorIds=new Set(),successorIds=new Set();
    for(const [id,event] of Object.entries(state.supersessions)){
      if(id!==event.supersessionId||!validateCanonicalAdmissionAuthorizationSupersession(event).valid||predecessorIds.has(event.predecessorAuthorizationId)||successorIds.has(event.successorAuthorizationId))throw new Error("CANONICAL_AUTHORIZATION_STATE_INVALID");
      const predecessor=state.authorizations[event.predecessorAuthorizationId],successor=state.authorizations[event.successorAuthorizationId];
      if(!predecessor||!successor||predecessor.evidenceId!==event.evidenceId||successor.evidenceId!==event.evidenceId||successor.lineage?.predecessorAuthorizationId!==predecessor.authorizationId||successor.lineage?.rootAuthorizationId!==event.lineageRootAuthorizationId||successor.lineage?.generation!==(predecessor.lineage?.generation??0)+1||successor.lineage?.generation!==event.generation||successor.lineage?.bindingChange!==event.bindingChange||successor.assessmentId!==event.successorAssessmentId||predecessor.assessmentId!==event.predecessorAssessmentId||successor.candidateBindingDigest!==event.successorBindingDigest||predecessor.candidateBindingDigest!==event.predecessorBindingDigest||predecessor.expiresAt!==event.predecessorExpiresAt)throw new Error("CANONICAL_AUTHORIZATION_STATE_INVALID");
      predecessorIds.add(event.predecessorAuthorizationId);successorIds.add(event.successorAuthorizationId);
    }
    for(const [key,id] of Object.entries(state.activeAuthorizationByIntent)){const authorization=state.authorizations[id];if(!authorization||key!==intentKey(authorization.evidenceId)||predecessorIds.has(id))throw new Error("CANONICAL_AUTHORIZATION_STATE_INVALID");}
    for(const [evidenceId,rootId] of Object.entries(state.byEvidence)){let id=rootId,seen=new Set();while(true){if(seen.has(id))throw new Error("CANONICAL_AUTHORIZATION_STATE_INVALID");seen.add(id);const outgoing=Object.values(state.supersessions).find(event=>event.predecessorAuthorizationId===id);if(!outgoing)break;id=outgoing.successorAuthorizationId;}if(state.activeAuthorizationByIntent[intentKey(evidenceId)]!==id)throw new Error("CANONICAL_AUTHORIZATION_STATE_INVALID");const all=Object.values(state.authorizations).filter(value=>value.evidenceId===evidenceId);if(all.length!==seen.size||all.some(value=>!seen.has(value.authorizationId)))throw new Error("CANONICAL_AUTHORIZATION_STATE_INVALID");}
    if(Object.values(state.authorizations).some(value=>!state.byEvidence[value.evidenceId]))throw new Error("CANONICAL_AUTHORIZATION_STATE_INVALID");
    return state;
  }
  async _read(){try{return this._validateState(JSON.parse(await readFile(this.statePath,"utf8")));}catch(error){if(error?.code==="ENOENT")return initial();if(error?.message==="CANONICAL_AUTHORIZATION_STATE_INVALID")throw error;throw new Error("CANONICAL_AUTHORIZATION_STATE_INVALID");}}
  async _commit(state){await mkdir(dirname(this.statePath),{recursive:true});const temp=`${this.statePath}.tmp-${process.pid}-${Date.now()}`;await writeFile(temp,`${JSON.stringify(state,null,2)}\n`);await rename(temp,this.statePath);}
  async record(authorization){const report=validateCanonicalAdmissionAuthorization(authorization);if(!report.valid)throw new TypeError(report.errors.join(","));if(authorization.schemaVersion!=="1.0")throw new Error("CANONICAL_SUCCESSOR_REQUIRES_SUPERSESSION_OPERATION");return this._lock(async()=>{const state=await this._read(),existingId=state.byEvidence[authorization.evidenceId];if(existingId){const existing=state.authorizations[existingId];if(existing.authorizationId===authorization.authorizationId&&existing.candidateBindingDigest===authorization.candidateBindingDigest)return freeze(clone(existing));throw new Error("CANONICAL_AUTHORIZATION_CONFLICT");}state.authorizations[authorization.authorizationId]=clone(authorization);state.byEvidence[authorization.evidenceId]=authorization.authorizationId;state.activeAuthorizationByIntent[intentKey(authorization.evidenceId)]=authorization.authorizationId;await this._commit(state);return freeze(clone(authorization));});}
  async supersede({predecessorAuthorizationId,successor,supersession}){if(!validateCanonicalAdmissionAuthorization(successor).valid||successor.schemaVersion!=="1.1"||!validateCanonicalAdmissionAuthorizationSupersession(supersession).valid)throw new TypeError("CANONICAL_SUPERSESSION_INPUT_INVALID");return this._lock(async()=>{const state=await this._read(),predecessor=state.authorizations[predecessorAuthorizationId];if(!predecessor)throw new Error("CANONICAL_PREDECESSOR_NOT_FOUND");const key=intentKey(predecessor.evidenceId),existingEvent=Object.values(state.supersessions).find(event=>event.predecessorAuthorizationId===predecessorAuthorizationId);if(existingEvent){if(existingEvent.successorAuthorizationId===successor.authorizationId&&existingEvent.supersessionId===supersession.supersessionId)return freeze({status:"ALREADY_SUPERSEDED",authorization:clone(state.authorizations[existingEvent.successorAuthorizationId]),supersession:clone(existingEvent)});throw new Error("CANONICAL_SUPERSESSION_CONFLICT");}if(state.activeAuthorizationByIntent[key]!==predecessorAuthorizationId)throw new Error("CANONICAL_SUPERSESSION_PREDECESSOR_NOT_ACTIVE");if(state.consumptions[predecessorAuthorizationId])throw new Error("CANONICAL_SUPERSESSION_PREDECESSOR_CONSUMED");if(effectiveCanonicalAdmissionAuthorizationLifecycle({authorization:predecessor,asOf:this.now()})!=="EXPIRED")throw new Error("CANONICAL_SUPERSESSION_PREDECESSOR_NOT_EXPIRED");if(successor.lineage?.predecessorAuthorizationId!==predecessorAuthorizationId||successor.evidenceId!==predecessor.evidenceId||supersession.predecessorAuthorizationId!==predecessorAuthorizationId||supersession.successorAuthorizationId!==successor.authorizationId)throw new Error("CANONICAL_SUPERSESSION_BINDING_INVALID");if(state.authorizations[successor.authorizationId]||state.supersessions[supersession.supersessionId])throw new Error("CANONICAL_SUPERSESSION_CONFLICT");state.authorizations[successor.authorizationId]=clone(successor);state.supersessions[supersession.supersessionId]=clone(supersession);state.activeAuthorizationByIntent[key]=successor.authorizationId;await this._commit(state);return freeze({status:"SUPERSEDED",authorization:clone(successor),supersession:clone(supersession)});});}
  async getById(id){const value=(await this._read()).authorizations[id];return value?freeze(clone(value)):null;}
  async getAll(){return freeze(Object.values((await this._read()).authorizations).map(value=>freeze(clone(value))));}
  async getAllConsumptions(){return freeze(Object.values((await this._read()).consumptions).map(value=>freeze(clone(value))));}
  async getSupersessionByPredecessor(id){const value=Object.values((await this._read()).supersessions).find(event=>event.predecessorAuthorizationId===id);return value?freeze(clone(value)):null;}
  async getActiveByEvidence(evidenceId){const state=await this._read(),value=state.authorizations[state.activeAuthorizationByIntent[intentKey(evidenceId)]];return value?freeze(clone(value)):null;}
  async getConsumption(id){const value=(await this._read()).consumptions[id];return value?freeze(clone(value)):null;}
  async consume({authorizationId,candidateBindingDigest,observationId,status}){return this._lock(async()=>{const state=await this._read(),authorization=state.authorizations[authorizationId];if(!authorization)throw new Error("CANONICAL_AUTHORIZATION_NOT_FOUND");if(authorization.candidateBindingDigest!==candidateBindingDigest)throw new Error("CANONICAL_AUTHORIZATION_CONSUMPTION_CONFLICT");const existing=state.consumptions[authorizationId];if(existing){if(existing.candidateBindingDigest!==candidateBindingDigest||existing.observationId!==observationId)throw new Error("CANONICAL_AUTHORIZATION_CONSUMPTION_CONFLICT");return freeze({status:"ALREADY_CONSUMED",consumption:clone(existing)});}const consumption={schemaVersion:"1.0",authorizationId,candidateBindingDigest,observationId,status,consumedAt:this.now()};state.consumptions[authorizationId]=consumption;await this._commit(state);return freeze({status:"CONSUMED",consumption:clone(consumption)});});}
}
export default FileCanonicalAdmissionAuthorizationRepository;
