import * as nodeFileSystem from "node:fs/promises";
import {randomUUID} from "node:crypto";
import {dirname,resolve} from "node:path";
import {createProductInterestSignal} from "./ProductInterestSignal.js";
import {validateFirstPartyProductInterestEvent} from "./FirstPartyProductInterestEvent.js";
import {createFirstPartyInterestSignalId,firstPartyInterestEventFingerprint} from "./FirstPartyProductInterestCollectionRepository.js";
const VERSION="1.0",initial=()=>({schemaVersion:VERSION,repositoryType:"BEACON_FIRST_PARTY_PRODUCT_INTEREST",sequence:0,records:{}}),freeze=value=>{if(value&&typeof value==="object"&&!Object.isFrozen(value)){Object.freeze(value);for(const child of Object.values(value))freeze(child);}return value;},clone=structuredClone;
export class FileFirstPartyProductInterestCollectionRepository{
 constructor({statePath,fileSystem=nodeFileSystem}={}){if(!statePath||!["readFile","mkdir","writeFile","rename"].every(name=>typeof fileSystem?.[name]==="function"))throw new TypeError("FIRST_PARTY_INTEREST_DURABLE_REPOSITORY_DEPENDENCIES_REQUIRED");this.statePath=resolve(statePath);this.fs=fileSystem;this.queue=Promise.resolve();}
 #validateRecord(record){try{if(!record||typeof record!=="object"||Array.isArray(record)||Object.keys(record).some(key=>!["event","materialFingerprint","signal"].includes(key)))throw new Error();const event=validateFirstPartyProductInterestEvent(record.event),signal=createProductInterestSignal(record.signal),expected=firstPartyInterestEventFingerprint(event);if(JSON.stringify(signal)!==JSON.stringify(record.signal)||record.materialFingerprint!==expected||signal.signalId!==createFirstPartyInterestSignalId(event.eventId)||signal.provenance?.eventId!==event.eventId||signal.atlasProductId!==event.atlasProductId||signal.signalType!==event.signalType||signal.observedAt!==event.occurredAt||signal.provenance?.retailerId!==event.retailerId||signal.metadata?.recordedAt==null||Date.parse(signal.metadata.recordedAt)<Date.parse(event.occurredAt))throw new Error();return freeze({event,materialFingerprint:expected,signal});}catch{throw new Error("FIRST_PARTY_INTEREST_DURABLE_STATE_INVALID");}}
 async #read(){let parsed;try{parsed=JSON.parse(await this.fs.readFile(this.statePath,"utf8"));}catch(error){if(error?.code==="ENOENT")return initial();throw new Error("FIRST_PARTY_INTEREST_DURABLE_STATE_INVALID");}if(parsed?.schemaVersion!==VERSION||parsed?.repositoryType!=="BEACON_FIRST_PARTY_PRODUCT_INTEREST"||!Number.isSafeInteger(parsed.sequence)||parsed.sequence<0||!parsed.records||typeof parsed.records!=="object"||Array.isArray(parsed.records))throw new Error("FIRST_PARTY_INTEREST_DURABLE_STATE_INVALID");const records={};for(const [eventId,raw] of Object.entries(parsed.records)){const record=this.#validateRecord(raw);if(eventId!==record.event.eventId||records[eventId]||Object.values(records).some(x=>x.signal.signalId===record.signal.signalId))throw new Error("FIRST_PARTY_INTEREST_DURABLE_STATE_INVALID");records[eventId]=record;}if(parsed.sequence!==Object.keys(records).length)throw new Error("FIRST_PARTY_INTEREST_DURABLE_STATE_INVALID");return {schemaVersion:VERSION,repositoryType:"BEACON_FIRST_PARTY_PRODUCT_INTEREST",sequence:parsed.sequence,records};}
 async #commit(state){await this.fs.mkdir(dirname(this.statePath),{recursive:true});const temporary=`${this.statePath}.${process.pid}.${randomUUID()}.tmp`;await this.fs.writeFile(temporary,`${JSON.stringify(state,null,2)}\n`,"utf8");await this.fs.rename(temporary,this.statePath);}
 #locked(operation){const task=this.queue.then(operation,operation);this.queue=task.catch(()=>{});return task;}
 accept({event,signal}={}){return this.#locked(async()=>{const record=this.#validateRecord({event,materialFingerprint:firstPartyInterestEventFingerprint(event),signal}),state=await this.#read(),existing=state.records[event.eventId];if(existing){if(existing.materialFingerprint!==record.materialFingerprint)throw new Error("FIRST_PARTY_INTEREST_EVENT_CONFLICT");return freeze({status:"DUPLICATE",signal:clone(existing.signal)});}if(Object.values(state.records).some(x=>x.signal.signalId===record.signal.signalId))throw new Error("FIRST_PARTY_INTEREST_SIGNAL_ID_CONFLICT");const next={...state,sequence:state.sequence+1,records:{...state.records,[event.eventId]:record}};await this.#commit(next);return freeze({status:"ACCEPTED",signal:clone(record.signal)});});}
 async getSignals(){const state=await this.#read();return freeze(Object.values(state.records).map(x=>freeze(clone(x.signal))).sort((a,b)=>a.signalId.localeCompare(b.signalId)));}
 async getRecords(){const state=await this.#read();return freeze(Object.values(state.records).map(x=>freeze(clone(x))).sort((a,b)=>a.event.eventId.localeCompare(b.event.eventId)));}
}
export default FileFirstPartyProductInterestCollectionRepository;
