const JSON_CONTENT_TYPE=/^application\/json(?:\s*;\s*charset=utf-8)?$/i,freeze=value=>{if(value&&typeof value==="object"&&!Object.isFrozen(value)){Object.freeze(value);for(const child of Object.values(value))freeze(child);}return value;},response=(statusCode,body)=>freeze({statusCode,headers:{"content-type":"application/json","cache-control":"no-store"},body:freeze(body)});
export class GovernedProductInterestHttpHandler{
 static route="/api/beacon/product-interest";
 constructor({collectionService,maximumPayloadBytes=2048}={}){if(!collectionService?.collect||!Number.isSafeInteger(maximumPayloadBytes)||maximumPayloadBytes<=0)throw new TypeError("BEACON_HTTP_HANDLER_DEPENDENCIES_REQUIRED");this.collectionService=collectionService;this.maximumPayloadBytes=maximumPayloadBytes;}
 async handle({path=GovernedProductInterestHttpHandler.route,method,headers={},rawBody,recordedAt}={}){
  if(path!==GovernedProductInterestHttpHandler.route)return response(404,{error:"NOT_FOUND"});if(method!=="POST")return response(405,{error:"METHOD_NOT_ALLOWED"});const contentType=Object.entries(headers).find(([key])=>key.toLowerCase()==="content-type")?.[1];if(typeof contentType!=="string"||!JSON_CONTENT_TYPE.test(contentType))return response(415,{error:"UNSUPPORTED_MEDIA_TYPE"});if(typeof rawBody!=="string")return response(400,{error:"INVALID_REQUEST_BODY"});if(Buffer.byteLength(rawBody,"utf8")>this.maximumPayloadBytes)return response(413,{error:"PAYLOAD_TOO_LARGE"});let event;try{event=JSON.parse(rawBody);}catch{return response(400,{error:"INVALID_JSON"});}
  try{const result=await this.collectionService.collect({event,recordedAt});return response(result.status==="ACCEPTED"?202:200,{status:result.status,signalId:result.signal.signalId});}catch(error){const message=String(error?.message??"");if(message.includes("EVENT_CONFLICT"))return response(409,{error:"EVENT_CONFLICT"});if(message.includes("ATLAS_PRODUCT_UNKNOWN")||message.includes("ATLAS_RETAILER_UNKNOWN"))return response(404,{error:"IDENTITY_NOT_FOUND"});if(message.includes("EVENT_INVALID")||message.includes("RECORDED_AT_INVALID"))return response(400,{error:"INVALID_EVENT"});return response(503,{error:"COLLECTION_UNAVAILABLE"});}
 }
}
export default GovernedProductInterestHttpHandler;
