import crypto from "node:crypto";
import {mkdir,readFile,writeFile} from "node:fs/promises";
import {dirname} from "node:path";
import {buildOperationalAcquisitionCandidates} from "./OperationalAcquisitionState.js";
import {selectProductScopedInitialAcquisitionCandidate} from "./ProductScopedInitialAcquisition.js";
import {createAcquisitionBudgetPolicy} from "../planning/AcquisitionBudgetPolicy.js";
import {createAcquisitionPlan} from "../planning/AcquisitionPlan.js";
import {createManualLiveAuthorizationRequest} from "../authorization/ManualLiveAuthorizationRequest.js";
import {createProductInfoEnrichmentAuthorizationRequest} from "../enrichment/ProductInfoEnrichmentAuthorization.js";
import {extractReviewedProductEnrichmentProposal} from "../enrichment/ProductEnrichmentProposalEnvelope.js";
import {createSellersEnrichmentAuthorizationRequest} from "../enrichment/SellersEnrichmentAuthorization.js";
import {readGovernedSpendForUtcDay} from "../planning/GovernedDailySpend.js";

const stable=v=>Array.isArray(v)?`[${v.map(stable).join(",")}]`:v&&typeof v==="object"?`{${Object.keys(v).sort().map(k=>`${JSON.stringify(k)}:${stable(v[k])}`).join(",")}}`:JSON.stringify(v);
const digest=v=>crypto.createHash("sha256").update(stable(v)).digest("hex");
const freeze=v=>{if(v&&typeof v==="object"&&!Object.isFrozen(v)){Object.freeze(v);for(const x of Object.values(v))freeze(x)}return v};
const clone=structuredClone;
const allowed=new Set(["paidActionIntentId","bootstrapCheckpointId","bootstrapArtifactId"]);
function metadata(value){if(value==null)return null;for(const key of Object.keys(value))if(!allowed.has(key))throw new Error(`PREPARE_TRUSTED_METADATA_INVALID:${key}`);for(const key of allowed)if(typeof value[key]!=="string"||!value[key].trim())throw new Error(`PREPARE_TRUSTED_METADATA_INVALID:${key}`);if(!/^mer_histbootintent_[a-f0-9]{24}$/.test(value.paidActionIntentId))throw new Error("PAID_ACTION_INTENT_INVALID");return freeze(clone(value));}
async function persist(path,value){if(!path)return;await mkdir(dirname(path),{recursive:true});await writeFile(path,`${JSON.stringify(value,null,2)}\n`,`utf8`)}
function result(operation,request,proposal=null,trustedMetadata=null){const candidateId=request.plan?.decisions?.[0]?.candidateId??null,atlasProductId=request.atlasProductId??(operation==="PRODUCTS"&&candidateId?.startsWith("atlas:")?candidateId.slice(6,-9):candidateId),binding={operation,atlasProductId,prepareArtifactId:proposal?.proposalId??request.requestId,authorizationRequestId:request.requestId,proposalDigest:request.proposalDigest??digest(request.plan),paidActionIntentId:trustedMetadata?.paidActionIntentId??null,bootstrapCheckpointId:trustedMetadata?.bootstrapCheckpointId??null,bootstrapArtifactId:trustedMetadata?.bootstrapArtifactId??null};return freeze({operation,prepareArtifact:proposal??request,authorizationRequest:request,reference:{...binding,prepareArtifactBindingDigest:digest(binding),preparedAt:request.createdAt},providerCalls:0,paidTaskCreated:false,actualSpendUsd:0})}

export function createProductionProductsPrepareOwner({atlas,acceptanceRepository=null,evidenceRepository=null,executionRepository,authorizationRequestPath=null,now=()=>new Date().toISOString()}={}){if(!atlas?.products?.getById||!executionRepository?.getAll)throw new TypeError("PRODUCTS_PREPARE_OWNER_DEPENDENCIES_REQUIRED");return{async prepare({atlasProductId=null,trustedMetadata=null}={}){const tm=metadata(trustedMetadata),candidates=await buildOperationalAcquisitionCandidates({atlas,acceptanceRepository,evidenceRepository}),selected=atlasProductId?selectProductScopedInitialAcquisitionCandidate({atlasProductId,product:await atlas.products.getById(atlasProductId),candidates}):null,planning=selected?[selected]:candidates,createdAt=now(),spentTodayUsd=await readGovernedSpendForUtcDay({executionRepository,evaluationTime:createdAt}),policy=createAcquisitionBudgetPolicy({enabled:true,maxPaidTasksPerRun:1,maxSpendPerRunUsd:.001,maxSpendPerDayUsd:.01,automaticPaidRetries:0,defaultRefreshCooldownMs:21600000});if(tm&&(!selected||atlasProductId==null))throw new Error("BOOTSTRAP_PRODUCT_SCOPE_REQUIRED");const scoped=tm?planning.map(c=>({...c,execution:{...c.execution,paidActionIntentId:tm.paidActionIntentId,bootstrapCheckpointId:tm.bootstrapCheckpointId,bootstrapArtifactId:tm.bootstrapArtifactId}})):planning,plan=createAcquisitionPlan({candidates:scoped,policy,spentTodayUsd,plannedAt:createdAt}),request=createManualLiveAuthorizationRequest({plan,createdAt});await persist(authorizationRequestPath,request);return result("PRODUCTS",request,null,tm)}}}

export function createProductionProductInfoPrepareOwner({proposalEnvelopePath,executionRepository,authorizationRequestPath=null,now=()=>new Date().toISOString()}={}){if(!proposalEnvelopePath||!executionRepository?.getAll)throw new TypeError("PRODUCT_INFO_PREPARE_OWNER_DEPENDENCIES_REQUIRED");return{async prepare({trustedMetadata=null}={}){const tm=metadata(trustedMetadata),envelope=JSON.parse(await readFile(proposalEnvelopePath,"utf8")),base=extractReviewedProductEnrichmentProposal(envelope),proposal=tm?freeze({...clone(base),paidActionIntentId:tm.paidActionIntentId,bootstrapBinding:{checkpointId:tm.bootstrapCheckpointId,artifactId:tm.bootstrapArtifactId}}):base,createdAt=now(),spentTodayUsd=await readGovernedSpendForUtcDay({executionRepository,evaluationTime:createdAt}),request=createProductInfoEnrichmentAuthorizationRequest({proposal,createdAt,spentTodayUsd});await persist(authorizationRequestPath,request);return result("PRODUCT_INFO",request,proposal,tm)}}}

export function createProductionSellersPrepareOwner({proposalEnvelopePath,executionRepository,authorizationRequestPath=null,now=()=>new Date().toISOString()}={}){if(!proposalEnvelopePath||!executionRepository?.getAll)throw new TypeError("SELLERS_PREPARE_OWNER_DEPENDENCIES_REQUIRED");return{async prepare({trustedMetadata=null}={}){const tm=metadata(trustedMetadata),envelope=JSON.parse(await readFile(proposalEnvelopePath,"utf8"));if(envelope?.paidTaskCreated!==false||Number(envelope?.actualSpendUsd)!==0)throw new Error("SELLERS_PROPOSAL_ENVELOPE_NOT_ZERO_SPEND");if(!envelope?.proposal)throw new Error("SELLERS_PROPOSAL_MISSING");const proposal=tm?freeze({...clone(envelope.proposal),paidActionIntentId:tm.paidActionIntentId,bootstrapBinding:{checkpointId:tm.bootstrapCheckpointId,artifactId:tm.bootstrapArtifactId}}):envelope.proposal,createdAt=now(),spentTodayUsd=await readGovernedSpendForUtcDay({executionRepository,evaluationTime:createdAt}),request=createSellersEnrichmentAuthorizationRequest({proposal,createdAt,spentTodayUsd});await persist(authorizationRequestPath,request);return result("SELLERS",request,proposal,tm)}}}
