import crypto from "node:crypto";
import {REPEAT_OBSERVATION_AUTHORIZE_CONFIRMATION,REPEAT_OBSERVATION_EXECUTE_CONFIRMATION} from "./RepeatObservationBoundary.js";

export const BOUNDED_REPEAT_RUN_POLICY_VERSION="MERCURY-BOUNDED-REPEAT-RUN-1.0";
export const BOUNDED_REPEAT_RUN_AUTHORIZE_CONFIRMATION="AUTHORIZE-BOUNDED-REPEAT-RUN";
export const BOUNDED_REPEAT_RUN_START_CONFIRMATION="START-BOUNDED-REPEAT-RUN";
export const BOUNDED_REPEAT_RUN_RESUME_CONFIRMATION="RESUME-BOUNDED-REPEAT-RUN";
const stable=v=>Array.isArray(v)?`[${v.map(stable).join(",")}]`:v&&typeof v==="object"?`{${Object.keys(v).sort().map(k=>`${JSON.stringify(k)}:${stable(v[k])}`).join(",")}}`:JSON.stringify(v),hash=v=>crypto.createHash("sha256").update(stable(v)).digest("hex"),freeze=v=>Object.freeze(structuredClone(v)),iso=(v,c)=>{if(typeof v!=="string"||!Number.isFinite(Date.parse(v)))throw new Error(c);return v;},exact=(v,k,c)=>{if(!v||Object.keys(v).some(x=>!k.includes(x)))throw new Error(c);};
const required=(value,code)=>{if(typeof value!=="string"||!value.trim())throw new Error(code);return value.trim();};
const reason=error=>{const text=String(error?.message??error);if(/IDENTITY.*REVIEW|NOT_REUSABLE/.test(text))return"IDENTITY_REVIEW_REQUIRED";if(/DISCOVERY|LINEAGE/.test(text))return"DISCOVERY_REQUIRED";if(/RIGHTS/.test(text))return"RIGHTS_BLOCKED";if(/SOURCE_UNSUPPORTED|RESOLVER_REQUIRED/.test(text))return"UNSUPPORTED";return"BLOCKED";};
const systemic=error=>/RIGHTS_CHANGED|DAILY_BUDGET|LEDGER|BINDING_CONFLICT|REPOSITORY|SQLITE|TASK_OWNER|TASK_PERSISTENCE|AUTHORIZATION.*INVALID|CONFLICT/.test(String(error?.message??error));

export class BoundedRepeatObservationRunService{
 constructor({repeatService,repository,spendResolver=async()=>0,now=()=>new Date().toISOString(),dailySpendCeilingUsd=.025}={}){if(!repeatService||!repository?.recordRunPlan||!repository?.recordRunAuthorization||!repository?.startRun)throw new Error("REPEAT_RUN_DEPENDENCIES_REQUIRED");Object.assign(this,{repeatService,repository,spendResolver,now,dailySpendCeilingUsd});}
 async prepareRun(input={}){exact(input,["observationCycle","cohort"],"REPEAT_RUN_PREPARE_INPUT_INVALID");const cycle=iso(input.observationCycle,"REPEAT_RUN_CYCLE_INVALID");if(!Array.isArray(input.cohort)||!input.cohort.length)throw new Error("REPEAT_RUN_COHORT_REQUIRED");const requested=input.cohort.map(x=>{exact(x,["atlasProductId","source"],"REPEAT_RUN_COHORT_MEMBER_INVALID");if(typeof x.atlasProductId!=="string"||typeof x.source!=="string")throw new Error("REPEAT_RUN_COHORT_MEMBER_INVALID");return{atlasProductId:x.atlasProductId,source:x.source};}).sort((a,b)=>stable(a).localeCompare(stable(b)));if(new Set(requested.map(stable)).size!==requested.length)throw new Error("REPEAT_RUN_COHORT_DUPLICATE");const ready=[],blocked=[];for(const pair of requested)try{const prepared=await this.repeatService.prepare({...pair,observationCycle:cycle});ready.push({atlasProductId:pair.atlasProductId,source:pair.source,preparedObservationId:prepared.value.preparedObservationId,operation:prepared.value.operation,taskCeilingUsd:prepared.value.taskCostUsd,identityDigest:prepared.value.reusableIdentity.identityDigest,rightsDigest:prepared.value.sourceRightsProfileDigest});}catch(error){blocked.push({...pair,state:reason(error),reason:String(error.message)});}const material={policyVersion:BOUNDED_REPEAT_RUN_POLICY_VERSION,observationCycle:cycle,requested,ready,blocked,automaticPaidRetries:0,dailySpendCeilingUsd:this.dailySpendCeilingUsd},bindingDigest=hash(material),plan={schemaVersion:"1.0",runPlanId:`mer_repeatrunplan_${bindingDigest.slice(0,24)}`,bindingDigest,...material,cohortDigest:hash(requested),maximumPaidTasks:ready.length,maximumSpendUsd:Number(ready.reduce((n,x)=>n+x.taskCeilingUsd,0).toFixed(4)),preparedAt:cycle,authorizationState:"NOT_AUTHORIZED",providerSpendAuthorized:false};return this.repository.recordRunPlan(plan);}
 async authorizeRun(input={}){exact(input,["runPlanId","operator","reason","expiresAt","confirmation"],"REPEAT_RUN_AUTHORIZE_INPUT_INVALID");if(input.confirmation!==BOUNDED_REPEAT_RUN_AUTHORIZE_CONFIRMATION)throw new Error("REPEAT_RUN_AUTHORIZE_CONFIRMATION_REQUIRED");const operator=required(input.operator,"REPEAT_RUN_OPERATOR_REQUIRED"),reasonText=required(input.reason,"REPEAT_RUN_REASON_REQUIRED"),plan=this.repository.getRunPlan(input.runPlanId);if(!plan)throw new Error("REPEAT_RUN_PLAN_NOT_FOUND");const at=this.now(),expiry=iso(input.expiresAt,"REPEAT_RUN_AUTHORIZATION_EXPIRY_INVALID"),spend=await this.spendResolver(at);if(Date.parse(expiry)<=Date.parse(at)||spend+plan.maximumSpendUsd>this.dailySpendCeilingUsd)throw new Error("REPEAT_RUN_AGGREGATE_BUDGET_INVALID");const material={policyVersion:BOUNDED_REPEAT_RUN_POLICY_VERSION,runPlanId:plan.runPlanId,planBindingDigest:plan.bindingDigest,operator,reason:reasonText,authorizedAt:at,expiresAt:expiry,maximumPaidTasks:plan.maximumPaidTasks,maximumSpendUsd:plan.maximumSpendUsd,currentUtcDaySpendUsd:spend,dailySpendCeilingUsd:this.dailySpendCeilingUsd,automaticPaidRetries:0,historicalFactAdmissionAuthorized:true},bindingDigest=hash(material),value={schemaVersion:"1.0",runAuthorizationId:`mer_repeatrunauth_${bindingDigest.slice(0,24)}`,bindingDigest,...material,singleUseStart:true,state:"AUTHORIZED"};return this.repository.recordRunAuthorization(value);}
 async startRun(input={}){exact(input,["runAuthorizationId","startedBy","confirmation"],"REPEAT_RUN_START_INPUT_INVALID");if(input.confirmation!==BOUNDED_REPEAT_RUN_START_CONFIRMATION)throw new Error("REPEAT_RUN_START_CONFIRMATION_REQUIRED");const auth=this.repository.getRunAuthorization(input.runAuthorizationId);if(!auth)throw new Error("REPEAT_RUN_AUTHORIZATION_NOT_FOUND");const plan=this.repository.getRunPlan(auth.runPlanId),at=this.now();if(!plan||plan.bindingDigest!==auth.planBindingDigest||Date.parse(at)>=Date.parse(auth.expiresAt))throw new Error("REPEAT_RUN_AUTHORIZATION_INVALID");for(const member of plan.ready)await this.repeatService.validateCurrent({preparedObservationId:member.preparedObservationId});if((await this.spendResolver(at))+plan.maximumSpendUsd>this.dailySpendCeilingUsd)throw new Error("REPEAT_RUN_AGGREGATE_BUDGET_INVALID");const runId=`mer_repeatrun_${hash({runAuthorizationId:auth.runAuthorizationId}).slice(0,24)}`,members=plan.ready.map(x=>({...x,state:"READY",paidTaskCreated:false,evidenceIds:[],historicalObservationIds:[],exception:null})),created=this.repository.startRun({schemaVersion:"1.0",runId,runPlanId:plan.runPlanId,runAuthorizationId:auth.runAuthorizationId,observationCycle:plan.observationCycle,state:"RUNNING",startedAt:at,members});if(created.status==="DUPLICATE")return this.inspectRun({runId});return this._advance(runId,auth);}
 async resumeRun(input={}){exact(input,["runId","resumedBy","confirmation"],"REPEAT_RUN_RESUME_INPUT_INVALID");if(input.confirmation!==BOUNDED_REPEAT_RUN_RESUME_CONFIRMATION||typeof input.resumedBy!=="string"||!input.resumedBy.trim())throw new Error("REPEAT_RUN_RESUME_CONFIRMATION_REQUIRED");let run=this.repository.getRun(input.runId);if(!run)throw new Error("REPEAT_RUN_NOT_FOUND");if(run.members.some(member=>["READY","AUTHORIZED"].includes(member.state)))throw new Error("REPEAT_RUN_RESUME_NEW_PAID_TASK_FORBIDDEN");for(const member of run.members.filter(value=>value.state==="EXCEPTION"&&value.exception==="REPEAT_OBSERVATION_PROVIDER_TASK_NOT_FOUND")){const task=await this.repeatService.resolveTask({preparedObservationId:member.preparedObservationId,recover:true});this.repository.updateRunMember(run.runId,{...member,state:"EXECUTED",exception:null,paidTaskCreated:true,providerTaskId:task.taskId,actualSpendUsd:task.costUsd});}run=this.repository.getRun(run.runId);const auth=this.repository.getRunAuthorization(run.runAuthorizationId);return this._advance(run.runId,auth);}
 async inspectRun(input={}){exact(input,["runId","runPlanId"],"REPEAT_RUN_INSPECT_INPUT_INVALID");if(Boolean(input.runId)===Boolean(input.runPlanId))throw new Error("REPEAT_RUN_INSPECT_ID_REQUIRED");const spend=await this.spendResolver(this.now());if(input.runId){const run=this.repository.getRun(input.runId);if(!run)throw new Error("REPEAT_RUN_NOT_FOUND");return freeze({...this._summary(run),currentUtcDaySpendUsd:spend,dailySpendCeilingUsd:this.dailySpendCeilingUsd,remainingUtcDayCapacityUsd:Number((this.dailySpendCeilingUsd-spend).toFixed(4)),downstreamAuthority:false});}const plan=this.repository.getRunPlan(input.runPlanId);if(!plan)throw new Error("REPEAT_RUN_PLAN_NOT_FOUND");const authorizations=this.repository.findRunAuthorizationsByPlan?.(plan.runPlanId)??[],run=this.repository.findRunByPlan?.(plan.runPlanId)??null;return freeze({runPlanId:plan.runPlanId,observationCycle:plan.observationCycle,requested:plan.requested,ready:plan.ready,blocked:plan.blocked,maximumPaidTasks:plan.maximumPaidTasks,maximumSpendUsd:plan.maximumSpendUsd,automaticPaidRetries:0,currentUtcDaySpendUsd:spend,dailySpendCeilingUsd:this.dailySpendCeilingUsd,remainingUtcDayCapacityUsd:Number((this.dailySpendCeilingUsd-spend).toFixed(4)),authorizationState:authorizations.at(-1)?.state??"NOT_AUTHORIZED",runState:run?.state??"NOT_STARTED",downstreamAuthority:false});}
 async _advance(runId,auth){
  let run=this.repository.getRun(runId);
  for(let member of run.members){
   if(["COMPLETED","EXCEPTION"].includes(member.state))continue;
   try{
    if(member.state==="READY"){
     const a=await this.repeatService.authorize({preparedObservationId:member.preparedObservationId,operator:`machine:${auth.runAuthorizationId}`,reason:`Derived exact-task authority for ${auth.runPlanId}`,expiresAt:auth.expiresAt,confirmation:REPEAT_OBSERVATION_AUTHORIZE_CONFIRMATION,parentRunAuthorizationId:auth.runAuthorizationId});
     member={...member,state:"AUTHORIZED",authorizationId:a.value.authorizationId};this.repository.updateRunMember(runId,member);
    }
    if(member.state==="AUTHORIZED"){
     const result=await this.repeatService.execute({authorizationId:member.authorizationId,executedBy:`machine:${auth.runAuthorizationId}`,confirmation:REPEAT_OBSERVATION_EXECUTE_CONFIRMATION});
     if(!["COMPLETED","LIVE_AUTHORIZATION_ALREADY_CONSUMED"].includes(result.status))throw new Error("PRODUCT_PROVIDER_EXECUTION_FAILED");
     const task=await this.repeatService.resolveTask({preparedObservationId:member.preparedObservationId,recover:false});
     member={...member,state:"EXECUTED",paidTaskCreated:true,providerTaskId:task.taskId,actualSpendUsd:task.costUsd};this.repository.updateRunMember(runId,member);
    }
    const retrieved=await this.repeatService.retrieve({preparedObservationId:member.preparedObservationId});
    if(["PENDING","WAITING_FOR_PROVIDER"].includes(retrieved?.status)){member={...member,state:"WAITING_FOR_PROVIDER"};this.repository.updateRunMember(runId,member);continue;}
    if(retrieved?.status==="FAILED")throw new Error(`PRODUCT_PROVIDER_FAILED:${retrieved.reason??"UNKNOWN"}`);
    const processed=await this.repeatService.processRetain({preparedObservationId:member.preparedObservationId,canonicalResultId:retrieved.canonicalResultId}),evidenceIds=processed.evidenceIds??[],history=[];
    for(const evidenceId of evidenceIds){const assessed=await this.repeatService.assessAdmitFact({evidenceId,action:"ASSESS",admittedBy:null});if(assessed.historicalEligible!==true)throw new Error(`PRODUCT_FACT_NOT_ELIGIBLE:${evidenceId}`);const admitted=await this.repeatService.assessAdmitFact({evidenceId,action:"ADMIT",admittedBy:`machine:${auth.runAuthorizationId}`});if(admitted.observationId)history.push(admitted.observationId);}
    member={...member,state:"COMPLETED",evidenceIds,historicalObservationIds:history,duplicates:processed.duplicates??0};this.repository.updateRunMember(runId,member);
   }catch(error){if(systemic(error)){run={...run,state:"FAILED",systemicFailure:String(error.message)};this.repository.updateRun(run);return this._summary(this.repository.getRun(runId));}member={...member,state:"EXCEPTION",exception:String(error.message)};this.repository.updateRunMember(runId,member);}
  }
 run=this.repository.getRun(runId);const waiting=run.members.some(x=>x.state==="WAITING_FOR_PROVIDER"),exceptions=run.members.some(x=>x.state==="EXCEPTION"),state=waiting?"WAITING_FOR_PROVIDER":exceptions?"COMPLETED_WITH_EXCEPTIONS":"COMPLETED";this.repository.updateRun({...run,state,completedAt:waiting?null:this.now()});return this._summary(this.repository.getRun(runId));}
 _summary(run){const members=run.members??[];return freeze({runId:run.runId,runPlanId:run.runPlanId,observationCycle:run.observationCycle,state:run.state,paidTasksCreated:members.filter(x=>x.providerTaskId).length,actualSpendUsd:Number(members.reduce((n,x)=>n+(Number(x.actualSpendUsd)||0),0).toFixed(4)),completed:members.filter(x=>x.state==="COMPLETED").length,pending:members.filter(x=>x.state==="WAITING_FOR_PROVIDER").length,failed:members.filter(x=>x.state==="EXCEPTION").length,evidenceRetained:members.reduce((n,x)=>n+(x.evidenceIds?.length??0),0),historicalFactsAdmitted:members.reduce((n,x)=>n+(x.historicalObservationIds?.length??0),0),duplicates:members.reduce((n,x)=>n+(x.duplicates??0),0),productLocalExceptions:members.filter(x=>x.exception).map(x=>({atlasProductId:x.atlasProductId,source:x.source,reason:x.exception})),systemicFailure:run.systemicFailure??null,currentPriceWrites:0,currentDisplayWrites:0,cheapestWrites:0,pickWrites:0,publicationWrites:0});}
}
