import crypto from "node:crypto";

export const IMMUTABLE_RESULT_REPROCESSING_POLICY_VERSION="MERCURY-IMMUTABLE-RESULT-REPROCESSING-1.0";
export const IMMUTABLE_RESULT_REPROCESSING_CONFIRMATION_PREFIX="REPROCESS-IMMUTABLE-PROVIDER-RESULT-";
const stable=value=>Array.isArray(value)?`[${value.map(stable).join(",")}]`:value&&typeof value==="object"?`{${Object.keys(value).sort().map(key=>`${JSON.stringify(key)}:${stable(value[key])}`).join(",")}}`:JSON.stringify(value);
const hash=value=>crypto.createHash("sha256").update(stable(value)).digest("hex");
const freeze=value=>{const copy=structuredClone(value);const deep=item=>{if(item&&typeof item==="object"&&!Object.isFrozen(item)){Object.freeze(item);for(const child of Object.values(item))deep(child);}return item;};return deep(copy);};
const text=(value,code)=>{if(typeof value!=="string"||!value.trim())throw new Error(code);return value.trim();};
const one=(values,empty,many)=>{if(values.length===0)throw new Error(empty);if(values.length!==1)throw new Error(many);return values[0];};

export class ImmutableProviderResultReprocessingService{
 constructor({repeatService,resultRepository,repository,processors,now=()=>new Date().toISOString()}={}){if(!repeatService?.resolveResultContext||!repeatService?.validateCurrent||!repeatService?.processRetain||!repeatService?.assessAdmitFact||!resultRepository?.getCanonicalResultById||!repository?.findRunsByPreparedObservationId||!repository?.recordReprocessingAction||!repository?.appendReprocessingEvent||!repository?.getReprocessingActionByResult||!processors)throw new TypeError("IMMUTABLE_RESULT_REPROCESSING_DEPENDENCIES_REQUIRED");Object.assign(this,{repeatService,resultRepository,repository,processors,now});this.queue=Promise.resolve();}
 _lock(fn){const task=this.queue.then(fn,fn);this.queue=task.catch(()=>{});return task;}
 async assess({canonicalResultId}={}){
  const resultId=text(canonicalResultId,"IMMUTABLE_RESULT_REPROCESSING_RESULT_ID_REQUIRED"),result=await this.resultRepository.getCanonicalResultById(resultId);if(!result)throw new Error("IMMUTABLE_RESULT_REPROCESSING_RESULT_NOT_FOUND");
  const preparedObservationId=text(result.acquisitionReferenceId,"IMMUTABLE_RESULT_REPROCESSING_PREPARATION_REQUIRED"),context=await this.repeatService.resolveResultContext({preparedObservationId,canonicalResultId:resultId});
  const runs=this.repository.findRunsByPreparedObservationId(preparedObservationId),run=one(runs,"IMMUTABLE_RESULT_REPROCESSING_ORIGINAL_RUN_NOT_FOUND","IMMUTABLE_RESULT_REPROCESSING_ORIGINAL_RUN_AMBIGUOUS"),member=one(run.members.filter(value=>value.preparedObservationId===preparedObservationId),"IMMUTABLE_RESULT_REPROCESSING_ORIGINAL_MEMBER_NOT_FOUND","IMMUTABLE_RESULT_REPROCESSING_ORIGINAL_MEMBER_AMBIGUOUS");
  if(member.state!=="EXCEPTION"||typeof member.exception!=="string")throw new Error("IMMUTABLE_RESULT_REPROCESSING_ORIGINAL_OUTCOME_INELIGIBLE");
  const key=`${result.sourceId}:${result.operation}`,processor=this.processors[key];if(!processor||processor.sourceId!==result.sourceId||processor.operation!==result.operation||!processor.eligibleExceptions?.includes(member.exception)||typeof processor.process!=="function")throw new Error("IMMUTABLE_RESULT_REPROCESSING_PROCESSOR_INELIGIBLE");
  await this.repeatService.validateCurrent({preparedObservationId});
  const material={policyVersion:IMMUTABLE_RESULT_REPROCESSING_POLICY_VERSION,canonicalResultId:resultId,resultDigest:result.resultDigest,providerTaskId:result.providerTaskId,preparedObservationId,runId:run.runId,memberKey:member.memberKey,atlasProductId:result.atlasProductId,sourceId:result.sourceId,operation:result.operation,originalException:member.exception,processorVersion:processor.version,sourceRightsProfileDigest:result.sourceRightsProfileDigest},bindingDigest=hash(material),existing=this.repository.getReprocessingActionByResult(resultId);
  return freeze({...material,bindingDigest,actionId:`mer_resultreprocess_${bindingDigest.slice(0,24)}`,eligible:true,existingAction:existing,providerCalls:0,paidTasks:0,actualSpendUsd:0,originalRunState:run.state,originalMemberState:member.state});
 }
 async reprocess(input={}){return this._lock(async()=>{
  const canonicalResultId=text(input.canonicalResultId,"IMMUTABLE_RESULT_REPROCESSING_RESULT_ID_REQUIRED"),operator=text(input.operator,"IMMUTABLE_RESULT_REPROCESSING_OPERATOR_REQUIRED"),reason=text(input.reason,"IMMUTABLE_RESULT_REPROCESSING_REASON_REQUIRED");if(input.confirmation!==`${IMMUTABLE_RESULT_REPROCESSING_CONFIRMATION_PREFIX}${canonicalResultId}`)throw new Error("IMMUTABLE_RESULT_REPROCESSING_CONFIRMATION_REQUIRED");
  const assessment=await this.assess({canonicalResultId});if(assessment.existingAction&&(assessment.existingAction.operator!==operator||assessment.existingAction.reason!==reason))throw new Error("IMMUTABLE_RESULT_REPROCESSING_ACTION_CONFLICT");const terminal=assessment.existingAction?.events?.find(value=>value.type==="SUCCEEDED");if(terminal)return freeze({status:"ALREADY_EFFECTIVE",action:assessment.existingAction,evidenceIds:terminal.evidenceIds,historicalObservationIds:terminal.historicalObservationIds,providerCalls:0,paidTasks:0,actualSpendUsd:0,downstreamAuthority:false});
  const requestedAt=this.now(),fresh={schemaVersion:"1.0",actionId:assessment.actionId,bindingDigest:assessment.bindingDigest,policyVersion:assessment.policyVersion,canonicalResultId,providerTaskId:assessment.providerTaskId,preparedObservationId:assessment.preparedObservationId,runId:assessment.runId,memberKey:assessment.memberKey,atlasProductId:assessment.atlasProductId,sourceId:assessment.sourceId,operation:assessment.operation,originalException:assessment.originalException,processorVersion:assessment.processorVersion,sourceRightsProfileDigest:assessment.sourceRightsProfileDigest,operator,reason,requestedAt},action=assessment.existingAction?Object.fromEntries(Object.entries(assessment.existingAction).filter(([key])=>key!=="events")):fresh;if(action.operator!==operator||action.reason!==reason)throw new Error("IMMUTABLE_RESULT_REPROCESSING_ACTION_CONFLICT");this.repository.recordReprocessingAction(action);this.repository.appendReprocessingEvent(action.actionId,{eventId:`${action.actionId}:STARTED`,type:"STARTED",at:action.requestedAt});
  const processor=this.processors[`${assessment.sourceId}:${assessment.operation}`];try{const processed=await processor.process({assessment}),evidenceIds=[...new Set(processed?.evidenceIds??[])];if(evidenceIds.some(value=>typeof value!=="string"||!value))throw new Error("IMMUTABLE_RESULT_REPROCESSING_EVIDENCE_INVALID");const eligibleEvidenceIds=[],skippedEvidence=[];for(const evidenceId of evidenceIds)try{const value=await this.repeatService.assessAdmitFact({evidenceId,action:"ASSESS",admittedBy:null});if(value.historicalEligible===true)eligibleEvidenceIds.push(evidenceId);else skippedEvidence.push({evidenceId,reason:"HISTORICAL_ADMISSION_NOT_ELIGIBLE"});}catch(error){const reason=String(error?.message??error);if(reason.startsWith("HISTORICAL_ADMISSION_NOT_ELIGIBLE:"))skippedEvidence.push({evidenceId,reason});else throw error;}if(!eligibleEvidenceIds.length)throw new Error("IMMUTABLE_RESULT_REPROCESSING_NO_ELIGIBLE_HISTORY");const admissions=[];for(const evidenceId of eligibleEvidenceIds)admissions.push(await this.repeatService.assessAdmitFact({evidenceId,action:"ADMIT",admittedBy:`reprocessing:${action.actionId}:${operator}`}));const historicalObservationIds=admissions.map(value=>value.observationId).filter(Boolean),event=this.repository.appendReprocessingEvent(action.actionId,{eventId:`${action.actionId}:SUCCEEDED`,type:"SUCCEEDED",at:this.now(),evidenceIds,historicalObservationIds,skippedEvidence,evidenceRetained:evidenceIds.length,historyAdmitted:historicalObservationIds.length,duplicates:Number(processed?.duplicates??0)}),saved=this.repository.getReprocessingActionByResult(canonicalResultId);return freeze({status:"REPROCESSED",action:saved,event,evidenceIds,historicalObservationIds,skippedEvidence,providerCalls:0,paidTasks:0,actualSpendUsd:0,downstreamAuthority:false});}catch(error){const message=String(error?.message??error),type=/CONFLICT|AMBIGUOUS|LINEAGE/.test(message)?"CONFLICT":/MONEY|UNPROCESSABLE|INVALID|NO_ELIGIBLE/.test(message)?"STILL_UNPROCESSABLE":"SYSTEMIC_FAILURE";this.repository.appendReprocessingEvent(action.actionId,{eventId:`${action.actionId}:${type}:${hash(message).slice(0,16)}`,type,at:this.now(),reason:message});throw error;}
 });}
}
