import path from "node:path";
import {readFile} from "node:fs/promises";
import {ProductRepository} from "../../atlas/index.js";
import {FileAcquisitionExecutionLedgerRepository} from "../acquisition/execution/FileAcquisitionExecutionLedgerRepository.js";
import {FileLiveAuthorizationConsumptionRepository} from "../acquisition/authorization/FileLiveAuthorizationConsumptionRepository.js";
import {createProductionDataForSeoTaskOwner} from "../acquisition/operations/ProductionDataForSeoTaskOwner.js";
import {readGovernedSpendForUtcDay} from "../acquisition/planning/GovernedDailySpend.js";
import {defaultSourceRightsRegistry} from "../rights/SourceRightsRegistry.js";
import {RepeatObservationService,createAmazonRepeatObservationIdentity,createGoogleRepeatObservationIdentity} from "./RepeatObservationBoundary.js";
import {SqliteRepeatObservationRepository} from "./SqliteRepeatObservationRepository.js";

const freeze=value=>Object.freeze(structuredClone(value));
const exact=(value,keys,code)=>{if(!value||Object.keys(value).some(key=>!keys.includes(key)))throw new Error(code);};

export function createProductionRepeatObservationIdentityResolvers({amazonArtifactRepository,amazonActionRepository,evidenceRepository,historicalRepository}={}){
 return Object.freeze({
  DATAFORSEO_AMAZON:{async resolve({atlasProduct}){if(!amazonArtifactRepository?.getAll||!amazonActionRepository?.getEffectiveOutcomeForArtifact)throw new Error("REPEAT_OBSERVATION_AMAZON_IDENTITY_OWNER_REQUIRED");const artifacts=(await amazonArtifactRepository.getAll()).filter(x=>x.atlasProductId===atlasProduct.identity.atlasProductId),outcomes=(await Promise.all(artifacts.map(x=>amazonActionRepository.getEffectiveOutcomeForArtifact(x.acceptanceArtifactId)))).filter(Boolean),valid=outcomes.filter(x=>["STRONG_UNIQUE_ASIN","STRONG_OPERATOR_CONFIRMED_ASIN"].includes(x.state));if(valid.length!==1)throw new Error(valid.length?"REPEAT_OBSERVATION_AMAZON_IDENTITY_CONFLICT":"REPEAT_OBSERVATION_AMAZON_IDENTITY_NOT_REUSABLE");return createAmazonRepeatObservationIdentity({...valid[0],atlasProductId:atlasProduct.identity.atlasProductId});}},
  DATAFORSEO_GOOGLE_SHOPPING:{async resolve({atlasProduct}){if(!evidenceRepository?.getAll||!historicalRepository?.getAll)throw new Error("REPEAT_OBSERVATION_GOOGLE_IDENTITY_OWNER_REQUIRED");const history=(await historicalRepository.getAll()).filter(x=>x.atlasProductId===atlasProduct.identity.atlasProductId&&x.provenance?.source==="DATAFORSEO_GOOGLE_SHOPPING").sort((a,b)=>Date.parse(b.observationTime)-Date.parse(a.observationTime));if(!history.length)throw new Error("REPEAT_OBSERVATION_GOOGLE_IDENTITY_DISCOVERY_REQUIRED");const evidence=(await evidenceRepository.getAll()).filter(x=>x.evidenceId===history[0].provenance.retainedEvidenceId);if(evidence.length!==1)throw new Error("REPEAT_OBSERVATION_GOOGLE_IDENTITY_LINEAGE_INVALID");const providerIdentity=evidence[0].candidate?.marketEvidence?.productEvidence??{};return createGoogleRepeatObservationIdentity({atlasProductId:atlasProduct.identity.atlasProductId,state:"REUSED",providerIdentity,identityReuseAssessmentId:history[0].provenance?.acquisition?.identityReuseAssessmentId,sourceEvidenceId:evidence[0].evidenceId,contradictionStatus:"NONE"});}}
 });
}

export function createProductionRepeatObservationService({stateRoot=path.resolve(".forge-review/acquisition"),databasePath=path.join(stateRoot,"repeat-observations.sqlite"),productRepository=new ProductRepository({readJson:async resource=>JSON.parse(await readFile(resource,"utf8"))}),identityResolvers,rightsRegistry=defaultSourceRightsRegistry,executionRepository=new FileAcquisitionExecutionLedgerRepository({filePath:path.join(stateRoot,"execution-ledger.json")}),consumptionRepository=new FileLiveAuthorizationConsumptionRepository({filePath:path.join(stateRoot,"live-authorization-consumptions.json")}),taskOwners,retrievalOwners={},processingOwners={},historicalAdmissionOwner=null,taskResolver=null,resultPipeline=null,repository:providedRepository=null,now=()=>new Date().toISOString(),credentialLoader,httpTransport}={}){
 if(!identityResolvers)throw new Error("REPEAT_OBSERVATION_PRODUCTION_IDENTITY_RESOLVERS_REQUIRED");
 const repository=providedRepository??new SqliteRepeatObservationRepository({databasePath,consumptionRepository});
 const owners=taskOwners??Object.fromEntries(["SELLERS","AMAZON_SELLERS"].map(operation=>[operation,createProductionDataForSeoTaskOwner({operation,stateRoot,executionRepository,consumptionRepository,now,credentialLoader,httpTransport})]));
 const spendResolver=evaluationTime=>readGovernedSpendForUtcDay({executionRepository,evaluationTime}),domain=new RepeatObservationService({productRepository,identityResolvers,rightsRegistry,repository,spendResolver,taskOwners:owners,now});
 return Object.freeze({databasePath,repository,spendResolver,prepare:input=>domain.prepare(input),validateCurrent:input=>domain.validateCurrent(input),authorize:input=>domain.authorize(input),execute:input=>domain.execute(input),async resolveTask(input={}){exact(input,["preparedObservationId","recover"],"REPEAT_OBSERVATION_TASK_RESOLVE_INPUT_INVALID");const preparation=await repository.getPreparation(input.preparedObservationId);if(!preparation||!resultPipeline)throw new Error("REPEAT_OBSERVATION_TASK_RESOLUTION_UNAVAILABLE");return input.recover===true?resultPipeline.recoverTask(preparation):resultPipeline.resolveTask(preparation);},async retrieve(input={}){exact(input,["preparedObservationId"],"REPEAT_OBSERVATION_RETRIEVE_INPUT_INVALID");if(resultPipeline)return resultPipeline.retrieveMember(input);const preparation=await repository.getPreparation(input.preparedObservationId);if(!preparation)throw new Error("REPEAT_OBSERVATION_PREPARATION_NOT_FOUND");const task=await taskResolver?.(preparation);if(!task?.providerTaskId)throw new Error("REPEAT_OBSERVATION_PROVIDER_TASK_NOT_FOUND");const owner=retrievalOwners[preparation.operation];if(!owner?.retrieve)throw new Error("REPEAT_OBSERVATION_RETRIEVAL_OWNER_REQUIRED");return owner.retrieve({providerTaskId:task.providerTaskId});},async processRetain(input={}){exact(input,["preparedObservationId","canonicalResultId"],"REPEAT_OBSERVATION_PROCESS_INPUT_INVALID");if(resultPipeline)return resultPipeline.processRetainMember(input);const preparation=await repository.getPreparation(input.preparedObservationId),owner=processingOwners[preparation?.operation];if(!preparation||!owner?.process)throw new Error("REPEAT_OBSERVATION_PROCESS_OWNER_REQUIRED");return owner.process({preparedObservationId:input.preparedObservationId,canonicalResultId:input.canonicalResultId});},async assessAdmitFact(input={}){exact(input,["evidenceId","action","admittedBy"],"REPEAT_OBSERVATION_FACT_INPUT_INVALID");if(!historicalAdmissionOwner?.assess||!historicalAdmissionOwner?.admit)throw new Error("REPEAT_OBSERVATION_H058_OWNER_REQUIRED");if(input.action==="ASSESS")return historicalAdmissionOwner.assess({evidenceId:input.evidenceId});if(input.action==="ADMIT")return historicalAdmissionOwner.admit({evidenceId:input.evidenceId,admittedBy:input.admittedBy});throw new Error("REPEAT_OBSERVATION_FACT_ACTION_INVALID");},close(){repository.close();}});
}
