import path from "node:path";
import crypto from "node:crypto";
import {FileDataForSeoTaskLedger} from "../acquisition/dataforseo/FileDataForSeoTaskLedger.js";
import {FileHistoricalBootstrapProviderResultRepository,createHistoricalBootstrapProviderResult} from "../portfolio/FileHistoricalBootstrapProviderResultRepository.js";
import {createProductionDataForSeoRetrievalOwner} from "../acquisition/operations/ProductionDataForSeoRetrievalOwner.js";
import {createProductionSellersDf003ProcessingOwner} from "../acquisition/operations/ProductionSellersDf003ProcessingOwner.js";
import {FileDataForSeoMarketEvidenceRepository} from "../market/dataforseo/persistence/FileDataForSeoMarketEvidenceRepository.js";
import {DataForSeoAmazonHistoricalRetentionService} from "../amazon-dataforseo/DataForSeoAmazonHistoricalRetention.js";
import {normalizeAmazonSellersResultRows} from "../amazon-dataforseo/DataForSeoAmazonResults.js";
import {createReusableIdentityAcquisitionLineage,createGovernedReusableIdentityProjection} from "./ReusableIdentityAcquisitionLineage.js";
import {FileAcquisitionExecutionLedgerRepository} from "../acquisition/execution/FileAcquisitionExecutionLedgerRepository.js";

const freeze=v=>Object.freeze(structuredClone(v));
const one=(rows,empty,many)=>{if(rows.length===0)throw new Error(empty);if(rows.length!==1)throw new Error(many);return rows[0];};
const value=x=>typeof x?.then==="function"?x:Promise.resolve(x);
const digest=x=>crypto.createHash("sha256").update(JSON.stringify(x)).digest("hex");

export class ProductionRepeatObservationResultPipeline{
 constructor({repeatRepository,taskLedger,resultRepository,retrievalOwners,processingOwners,executionRepository,now=()=>new Date().toISOString()}={}){if(!repeatRepository?.getPreparation||!repeatRepository?.getAuthorization||!taskLedger?.getAll||!resultRepository?.findByTask||!resultRepository?.record||!retrievalOwners||!processingOwners)throw new TypeError("REPEAT_RESULT_PIPELINE_DEPENDENCIES_REQUIRED");Object.assign(this,{repeatRepository,taskLedger,resultRepository,retrievalOwners,processingOwners,executionRepository,now});}
 async resolveTask(preparation){const rows=await value(this.taskLedger.getByPaidActionIntentId?.(preparation.paidActionIntentId)??(await value(this.taskLedger.getAll())).filter(x=>x.paidActionIntentId===preparation.paidActionIntentId)),task=one(rows,"REPEAT_OBSERVATION_PROVIDER_TASK_NOT_FOUND","REPEAT_OBSERVATION_PROVIDER_TASK_AMBIGUOUS"),authorization=await this.repeatRepository.getAuthorization(task.repeatAuthorizationId);for(const [field,expected] of [["kind",preparation.operation],["sourceId",preparation.source],["atlasProductId",preparation.atlasProductId],["acquisitionCycleId",preparation.acquisitionCycleId],["preparedObservationId",preparation.preparedObservationId],["reusableIdentityDigest",preparation.reusableIdentity.identityDigest],["sourceRightsProfileDigest",preparation.sourceRightsProfileDigest]])if(task[field]!==expected)throw new Error("REPEAT_OBSERVATION_TASK_LINEAGE_CONFLICT");if(!authorization||authorization.preparedObservationId!==preparation.preparedObservationId||task.repeatAuthorizationId!==authorization.authorizationId||(task.parentRunAuthorizationId??null)!==(authorization.parentRunAuthorizationId??null))throw new Error("REPEAT_OBSERVATION_TASK_AUTHORIZATION_LINEAGE_CONFLICT");return task;}
 async recoverTask(preparation){try{return await this.resolveTask(preparation);}catch(error){if(String(error.message)!=="REPEAT_OBSERVATION_PROVIDER_TASK_NOT_FOUND")throw error;}if(!this.executionRepository?.getAll||typeof this.taskLedger.record!=="function")throw new Error("REPEAT_OBSERVATION_TASK_RECOVERY_OWNER_REQUIRED");const authorizationRows=await this.repeatRepository.findAuthorizationsByPreparation(preparation.preparedObservationId),authorization=one(authorizationRows,"REPEAT_OBSERVATION_AUTHORIZATION_LINEAGE_INVALID","REPEAT_OBSERVATION_AUTHORIZATION_LINEAGE_AMBIGUOUS"),runs=(await this.executionRepository.getAll()).filter(run=>run.planId===authorization.planId&&run.paidActionIntentId===preparation.paidActionIntentId&&run.status==="COMPLETED"&&(run.tasks??[]).some(task=>task.candidateId===preparation.preparedObservationId&&task.paidActionIntentId===preparation.paidActionIntentId&&task.outcome==="COMPLETED"&&task.providerTaskId));const run=one(runs,"REPEAT_OBSERVATION_COMPLETED_EXECUTION_NOT_FOUND","REPEAT_OBSERVATION_COMPLETED_EXECUTION_AMBIGUOUS"),entry=one(run.tasks.filter(task=>task.candidateId===preparation.preparedObservationId&&task.paidActionIntentId===preparation.paidActionIntentId&&task.outcome==="COMPLETED"&&task.providerTaskId),"REPEAT_OBSERVATION_COMPLETED_TASK_NOT_FOUND","REPEAT_OBSERVATION_COMPLETED_TASK_AMBIGUOUS"),record={kind:preparation.operation,taskId:entry.providerTaskId,costUsd:entry.actualCostUsd,createdStatus:entry.providerStatus,sourceId:preparation.source,atlasProductId:preparation.atlasProductId,paidActionIntentId:preparation.paidActionIntentId,acquisitionCycleId:preparation.acquisitionCycleId,preparedObservationId:preparation.preparedObservationId,reusableIdentityDigest:preparation.reusableIdentity.identityDigest,sourceRightsProfileDigest:preparation.sourceRightsProfileDigest,repeatAuthorizationId:authorization.authorizationId,parentRunAuthorizationId:authorization.parentRunAuthorizationId,requestDigest:null,recoveredFromExecutionRunId:run.runId};this.taskLedger.record(`repeat-recovery:${digest(record)}`,record);return this.resolveTask(preparation);}
 async context(preparedObservationId,canonicalResultId=null){const preparation=await this.repeatRepository.getPreparation(preparedObservationId);if(!preparation)throw new Error("REPEAT_OBSERVATION_PREPARATION_NOT_FOUND");const task=await this.resolveTask(preparation),authorization=await this.repeatRepository.getAuthorization(task.repeatAuthorizationId);if(!authorization||authorization.preparedObservationId!==preparedObservationId)throw new Error("REPEAT_OBSERVATION_AUTHORIZATION_LINEAGE_INVALID");let canonicalResult=null;if(canonicalResultId){canonicalResult=await this.resultRepository.getCanonicalResultById(canonicalResultId);if(!canonicalResult)throw new Error("REPEAT_OBSERVATION_CANONICAL_RESULT_NOT_FOUND");}return{preparation,task,authorization,canonicalResult};}
 async retrieveMember({preparedObservationId}={}){const {preparation,task}=await this.context(preparedObservationId),prior=await this.resultRepository.findByTask(task.taskId);if(prior){await this._validateResult(preparation,task,prior);return freeze({status:"AVAILABLE",canonicalResultId:prior.canonicalResultId,providerCalls:0,paidTaskCreated:false,actualSpendUsd:0});}const owner=this.retrievalOwners[preparation.operation];if(typeof owner?.retrieve!=="function")throw new Error("REPEAT_OBSERVATION_RETRIEVAL_OWNER_REQUIRED");let outcome;try{outcome=await owner.retrieve({providerTaskId:task.taskId});}catch(error){if(/^DATAFORSEO_TASK_ERROR:40/.test(String(error?.message)))return freeze({status:"PENDING",providerCalls:1,paidTaskCreated:false,actualSpendUsd:0});throw error;}if(["PENDING","PROVIDER_PENDING"].includes(outcome?.status)||Array.isArray(outcome?.result)&&outcome.result.length===0)return freeze({status:"PENDING",providerCalls:1,paidTaskCreated:false,actualSpendUsd:0});if(["FAILED","PROVIDER_FAILED"].includes(outcome?.status))return freeze({status:"FAILED",reason:outcome?.reason??"PROVIDER_FAILED",providerCalls:1,paidTaskCreated:false,actualSpendUsd:0});if(outcome?.id&&outcome.id!==task.taskId)throw new Error("REPEAT_OBSERVATION_RESULT_TASK_MISMATCH");const record=createHistoricalBootstrapProviderResult({operation:task.kind,sourceId:task.sourceId,providerTaskId:task.taskId,paidActionIntentId:task.paidActionIntentId,acquisitionReferenceId:preparation.preparedObservationId,atlasProductId:task.atlasProductId,sourceRightsProfileDigest:task.sourceRightsProfileDigest,requestIdentityDigest:task.requestDigest??null,operationResult:outcome,retrievedAt:this.now()}),saved=await this.resultRepository.record(record);await this._validateResult(preparation,task,saved);return freeze({status:"AVAILABLE",canonicalResultId:saved.canonicalResultId,providerCalls:1,paidTaskCreated:false,actualSpendUsd:0});}
 async _validateResult(preparation,task,result){if(result.acquisitionReferenceId!==preparation.preparedObservationId||result.providerTaskId!==task.taskId||result.operation!==task.kind||result.sourceId!==task.sourceId||result.paidActionIntentId!==task.paidActionIntentId||result.atlasProductId!==task.atlasProductId||result.sourceRightsProfileDigest!==task.sourceRightsProfileDigest)throw new Error("REPEAT_OBSERVATION_RESULT_LINEAGE_CONFLICT");return true;}
 async processRetainMember({preparedObservationId,canonicalResultId}={}){const context=await this.context(preparedObservationId,canonicalResultId);await this._validateResult(context.preparation,context.task,context.canonicalResult);const lineage=createReusableIdentityAcquisitionLineage({...context,parentRunAuthorizationId:context.authorization.parentRunAuthorizationId});const owner=this.processingOwners[context.preparation.operation];if(typeof owner?.process!=="function")throw new Error("REPEAT_OBSERVATION_PROCESS_OWNER_REQUIRED");const processed=await owner.process({...context,lineage}),evidenceIds=processed?.evidenceIds??[];if(!Array.isArray(evidenceIds)||evidenceIds.some(x=>typeof x!=="string"||!x))throw new Error("REPEAT_OBSERVATION_EVIDENCE_IDS_INVALID");return freeze({...processed,evidenceIds});}
 async governanceForEvidence({record}={}){const taskId=record?.candidate?.marketEvidence?.provenance?.sourceTaskId,raw=record?.candidate?.marketEvidence?.provenance?.rawPayloadReference;if(!taskId||!raw)return null;const tasks=(await value(this.taskLedger.getAll())).filter(x=>x.taskId===taskId&&/^mer_repeatintent_/.test(x.paidActionIntentId??""));if(!tasks.length)return null;const task=one(tasks,"REPEAT_OBSERVATION_PROVIDER_TASK_NOT_FOUND","REPEAT_OBSERVATION_PROVIDER_TASK_AMBIGUOUS"),preparation=await this.repeatRepository.getPreparation(task.preparedObservationId),authorization=await this.repeatRepository.getAuthorization(task.repeatAuthorizationId),canonicalResult=await this.resultRepository.findByTask(task.taskId);if(!preparation||!authorization||!canonicalResult)throw new Error("REPEAT_OBSERVATION_GOVERNANCE_LINEAGE_INCOMPLETE");const lineage=createReusableIdentityAcquisitionLineage({preparation,authorization,task,canonicalResult,parentRunAuthorizationId:authorization.parentRunAuthorizationId}),projection=createGovernedReusableIdentityProjection({lineage,evidenceId:record.evidenceId,rawPayloadReference:raw});return freeze({acquisitionChain:lineage,reusableIdentityAcquisitionProjections:[projection]});}
}

export function createProductionRepeatObservationResultPipeline({repeatRepository,stateRoot=path.resolve(".forge-review/acquisition"),resultStatePath=path.join(stateRoot,"historical-bootstrap-provider-results.json"),evidenceStatePath=path.join(stateRoot,"dataforseo-market-evidence.json"),taskLedger=new FileDataForSeoTaskLedger(path.join(stateRoot,"dataforseo-task-ledger.json")),resultRepository=new FileHistoricalBootstrapProviderResultRepository({statePath:resultStatePath}),executionRepository=new FileAcquisitionExecutionLedgerRepository({filePath:path.join(stateRoot,"execution-ledger.json")}),retrievalOwners,processingOwners,credentialLoader,httpTransport,readJson,now=()=>new Date().toISOString()}={}){
 const retrieval=retrievalOwners??Object.fromEntries(["SELLERS","AMAZON_SELLERS"].map(operation=>[operation,createProductionDataForSeoRetrievalOwner({operation,credentialLoader,httpTransport})]));
 let processing=processingOwners;if(!processing){const evidenceRepository=new FileDataForSeoMarketEvidenceRepository({statePath:evidenceStatePath}),amazonRetention=new DataForSeoAmazonHistoricalRetentionService({evidenceRepository}),google=createProductionSellersDf003ProcessingOwner({stateRoot,evidencePath:evidenceStatePath,readJson});processing={SELLERS:{async process({task,canonicalResult,lineage}){const output=await google.process({sellersTaskId:task.taskId,sellersResult:canonicalResult.operationResult,reusableIdentityLineage:lineage}),integrations=output.result.integrations??[];return{evidenceIds:integrations.map(x=>x.evidenceId).filter(Boolean),duplicates:integrations.filter(x=>x.evidenceOutcome==="DUPLICATE").length,result:output};}},AMAZON_SELLERS:{async process({preparation,task,canonicalResult,lineage}){const rows=normalizeAmazonSellersResultRows(canonicalResult),results=[];for(const row of rows)results.push(await amazonRetention.retain({sellerItem:row.sellerItem,atlasProductId:preparation.atlasProductId,identityAssessment:null,sellersTaskId:task.taskId,immutableResult:canonicalResult,observedAt:row.observedAt,rawPayloadReference:`dataforseo:amazon:sellers:${task.taskId}:item:${row.itemIndex}`,reusableIdentityLineage:lineage}));return{evidenceIds:results.map(x=>x.evidenceId).filter(Boolean),duplicates:results.filter(x=>x.status==="DUPLICATE").length,results};}}};}
 return new ProductionRepeatObservationResultPipeline({repeatRepository,taskLedger,resultRepository,executionRepository,retrievalOwners:retrieval,processingOwners:processing,now});
}
