import crypto from "node:crypto";
import { DATAFORSEO_DEFAULT_UTC_DAY_SPEND_CEILING_USD } from "../acquisition/planning/AcquisitionBudgetPolicy.js";

export const REPEAT_OBSERVATION_POLICY_VERSION = "MERCURY-REPEAT-OBSERVATION-1.0";
export const REPEAT_OBSERVATION_AUTHORIZE_CONFIRMATION = "AUTHORIZE-REPEAT-OBSERVATION";
export const REPEAT_OBSERVATION_EXECUTE_CONFIRMATION = "EXECUTE-REPEAT-OBSERVATION";
export const REPEAT_OBSERVATION_SOURCES = Object.freeze({ AMAZON: "DATAFORSEO_AMAZON", GOOGLE: "DATAFORSEO_GOOGLE_SHOPPING" });
const sourcePolicy = Object.freeze({
  DATAFORSEO_AMAZON: Object.freeze({ operation: "AMAZON_SELLERS", taskCostUsd: 0.0015 }),
  DATAFORSEO_GOOGLE_SHOPPING: Object.freeze({ operation: "SELLERS", taskCostUsd: 0.001 })
});
const stable = value => Array.isArray(value) ? `[${value.map(stable).join(",")}]` : value && typeof value === "object" ? `{${Object.keys(value).sort().map(key => `${JSON.stringify(key)}:${stable(value[key])}`).join(",")}}` : JSON.stringify(value);
const hash = value => crypto.createHash("sha256").update(stable(value)).digest("hex");
const clone = value => structuredClone(value);
const freeze = value => { if (value && typeof value === "object" && !Object.isFrozen(value)) { Object.freeze(value); for (const child of Object.values(value)) freeze(child); } return value; };
const required = (value, code) => { if (typeof value !== "string" || !value.trim()) throw new Error(code); return value.trim(); };
const iso = (value, code) => { const result = required(value, code); if (!Number.isFinite(Date.parse(result))) throw new Error(code); return result; };
const rightsAllowed = profile => profile?.acquisition?.api === "ALLOWED" && profile?.retention?.historical === "ALLOWED" && profile?.retention?.durableAuditMetadata === "ALLOWED" && profile?.derivation?.historicalAnalytics === "ALLOWED";
const exactKeys=(value,allowed,code)=>{if(!value||Object.keys(value).some(key=>!allowed.includes(key)))throw new Error(code);};

export function createAmazonRepeatObservationIdentity(effectiveOutcome) {
  if (!effectiveOutcome || !["STRONG_UNIQUE_ASIN", "STRONG_OPERATOR_CONFIRMED_ASIN"].includes(effectiveOutcome.state) || !/^[A-Z0-9]{10}$/.test(effectiveOutcome.governedAsin ?? "") || effectiveOutcome.sellersAuthorizationEligible !== true) throw new Error("REPEAT_OBSERVATION_AMAZON_IDENTITY_NOT_REUSABLE");
  const material = { source: REPEAT_OBSERVATION_SOURCES.AMAZON, atlasProductId: required(effectiveOutcome.atlasProductId ?? effectiveOutcome.productId, "REPEAT_OBSERVATION_PRODUCT_BINDING_REQUIRED"), asin: effectiveOutcome.governedAsin, identityState: effectiveOutcome.state, identityRecordId: effectiveOutcome.confirmationId ?? effectiveOutcome.reassessmentId ?? effectiveOutcome.outcomeId, identityPolicyVersion: effectiveOutcome.identityPolicyVersion ?? "MERCURY-HISTORY-046-1.0" };
  return freeze({ ...material, identityDigest: hash(material), executionIdentity: { dataAsin: material.asin } });
}

export function createGoogleRepeatObservationIdentity(value) {
  const providerIdentity = { productId: value?.providerIdentity?.productId ?? null, dataDocId: value?.providerIdentity?.dataDocId ?? null, gid: value?.providerIdentity?.gid ?? null };
  if (!value || !["APPLICABLE", "VERIFIED", "REUSED"].includes(value.state) || !value.atlasProductId || !Object.values(providerIdentity).some(Boolean) || value.contradictionStatus && value.contradictionStatus !== "NONE") throw new Error("REPEAT_OBSERVATION_GOOGLE_IDENTITY_NOT_REUSABLE");
  const material = { source: REPEAT_OBSERVATION_SOURCES.GOOGLE, atlasProductId: value.atlasProductId, providerIdentity, identityState: value.state, identityRecordId: value.identityReuseAssessmentId ?? value.sourceEvidenceId ?? value.identityRecordId, identityPolicyVersion: value.identityPolicyVersion ?? "DF004-E2L-1.0" };
  return freeze({ ...material, identityDigest: hash(material), executionIdentity: providerIdentity });
}

export function validateRepeatObservationPreparation(value) {
  const policy = sourcePolicy[value?.source], material = { policyVersion: value?.policyVersion, atlasProductId: value?.atlasProductId, source: value?.source, operation: value?.operation, observationCycle: value?.observationCycle, preparedAt:value?.preparedAt, reusableIdentity: value?.reusableIdentity, sourceRightsProfileDigest: value?.sourceRightsProfileDigest, taskCostUsd: value?.taskCostUsd, maximumSpendUsd:value?.maximumSpendUsd, paidActionIntentId: value?.paidActionIntentId, acquisitionCycleId: value?.acquisitionCycleId, automaticPaidRetries: value?.automaticPaidRetries };
  if (value?.schemaVersion !== "1.0" || value?.preparationType !== "REPEAT_OBSERVATION" || value?.policyVersion !== REPEAT_OBSERVATION_POLICY_VERSION || !policy || value.operation !== policy.operation || value.taskCostUsd !== policy.taskCostUsd || value.maximumSpendUsd!==policy.taskCostUsd || value.preparedAt!==value.observationCycle || value.automaticPaidRetries !== 0 || value.authorizationState !== "NOT_AUTHORIZED" || value.providerSpendAuthorized !== false || value.networkOperation !== "NONE" || value.paidTaskCreated !== false || value.actualSpendUsd !== 0 || value.bindingDigest !== hash(material) || value.preparedObservationId !== `mer_repeatprep_${value.bindingDigest.slice(0,24)}` || value.paidActionIntentId !== `mer_repeatintent_${hash({ atlasProductId:value.atlasProductId, source:value.source, observationCycle:value.observationCycle }).slice(0,24)}` || value.acquisitionCycleId !== `mer_repeatcycle_${hash({ source:value.source, observationCycle:value.observationCycle }).slice(0,24)}` || value.reusableIdentity?.atlasProductId !== value.atlasProductId || value.reusableIdentity?.source !== value.source) throw new Error("REPEAT_OBSERVATION_PREPARATION_INVALID");
  return true;
}

export function createRepeatObservationPreparation({ atlasProductId, source, observationCycle, reusableIdentity, rightsProfile } = {}) {
  const product = required(atlasProductId, "REPEAT_OBSERVATION_PRODUCT_REQUIRED"), cycle = iso(observationCycle, "REPEAT_OBSERVATION_CYCLE_INVALID"), policy = sourcePolicy[source];
  if (!policy) throw new Error("REPEAT_OBSERVATION_SOURCE_UNSUPPORTED");
  if (reusableIdentity?.atlasProductId !== product || reusableIdentity?.source !== source || !reusableIdentity?.identityDigest) throw new Error("REPEAT_OBSERVATION_IDENTITY_BINDING_INVALID");
  if (rightsProfile?.sourceId !== source || !rightsAllowed(rightsProfile)) throw new Error("REPEAT_OBSERVATION_RIGHTS_BLOCKED");
  const paidActionIntentId = `mer_repeatintent_${hash({ atlasProductId:product, source, observationCycle:cycle }).slice(0,24)}`, acquisitionCycleId = `mer_repeatcycle_${hash({ source, observationCycle:cycle }).slice(0,24)}`;
  const material = { policyVersion:REPEAT_OBSERVATION_POLICY_VERSION, atlasProductId:product, source, operation:policy.operation, observationCycle:cycle, preparedAt:cycle, reusableIdentity:clone(reusableIdentity), sourceRightsProfileDigest:hash(rightsProfile), taskCostUsd:policy.taskCostUsd, maximumSpendUsd:policy.taskCostUsd, paidActionIntentId, acquisitionCycleId, automaticPaidRetries:0 }, bindingDigest=hash(material);
  const value={schemaVersion:"1.0",preparationType:"REPEAT_OBSERVATION",preparedObservationId:`mer_repeatprep_${bindingDigest.slice(0,24)}`,bindingDigest,...material,authorizationState:"NOT_AUTHORIZED",providerSpendAuthorized:false,networkOperation:"NONE",paidTaskCreated:false,actualSpendUsd:0}; validateRepeatObservationPreparation(value); return freeze(value);
}

export function createRepeatObservationAuthorization({ preparation, operator, reason, authorizedAt, expiresAt, currentUtcDaySpendUsd, dailySpendCeilingUsd=DATAFORSEO_DEFAULT_UTC_DAY_SPEND_CEILING_USD }={}) {
  validateRepeatObservationPreparation(preparation); const by=required(operator,"REPEAT_OBSERVATION_OPERATOR_REQUIRED"), why=required(reason,"REPEAT_OBSERVATION_REASON_REQUIRED"), at=iso(authorizedAt,"REPEAT_OBSERVATION_AUTHORIZATION_TIME_INVALID"), expiry=iso(expiresAt,"REPEAT_OBSERVATION_AUTHORIZATION_EXPIRY_INVALID");
  if(Date.parse(expiry)<=Date.parse(at))throw new Error("REPEAT_OBSERVATION_AUTHORIZATION_EXPIRY_INVALID"); if(!Number.isFinite(currentUtcDaySpendUsd)||currentUtcDaySpendUsd<0||currentUtcDaySpendUsd+preparation.taskCostUsd>dailySpendCeilingUsd)throw new Error("REPEAT_OBSERVATION_DAILY_BUDGET_EXCEEDED");
  const material={policyVersion:REPEAT_OBSERVATION_POLICY_VERSION,preparedObservationId:preparation.preparedObservationId,preparationBindingDigest:preparation.bindingDigest,operator:by,reason:why,authorizedAt:at,expiresAt:expiry,currentUtcDaySpendUsd,dailySpendCeilingUsd,maxSpendUsd:preparation.taskCostUsd,maxPaidTasks:1,automaticPaidRetries:0},authorizationId=`mer_repeatauth_${hash(material).slice(0,24)}`;
  const execution={kind:preparation.operation,...preparation.reusableIdentity.executionIdentity,atlasProductId:preparation.atlasProductId,acquisitionCycleId:preparation.acquisitionCycleId,paidActionIntentId:preparation.paidActionIntentId}; const plan={schemaVersion:"1.0",planId:`mer_repeatplan_${hash({authorizationId,execution}).slice(0,24)}`,plannedAt:at,policy:{schemaVersion:"1.0",enabled:true,maxPaidTasksPerRun:1,maxSpendPerRunUsd:preparation.taskCostUsd,maxSpendPerDayUsd:dailySpendCeilingUsd,automaticPaidRetries:0},spentTodayUsd:currentUtcDaySpendUsd,approvedTaskCount:1,estimatedApprovedSpendUsd:preparation.taskCostUsd,decisions:[{candidateId:preparation.preparedObservationId,priority:"NORMAL",estimatedCostUsd:preparation.taskCostUsd,decision:"APPROVED",reason:null,rationale:"Governed reusable product-source identity; fresh SELLERS observation.",execution}]};
  return freeze({schemaVersion:"1.0",authorizationType:"REPEAT_OBSERVATION",authorizationId,requestId:authorizationId,status:"AUTHORIZED",singleUse:true,...material,authorizationBindingDigest:hash(material),sourceRightsProfileDigest:preparation.sourceRightsProfileDigest,consumptionState:"NOT_CONSUMED",planId:plan.planId,plan});
}

export class InMemoryRepeatObservationRepository {
  constructor(){this.preparations=[];this.authorizations=[];}
  async recordPreparation(value){validateRepeatObservationPreparation(value);return this._record(this.preparations,"preparedObservationId",value,"REPEAT_OBSERVATION_PREPARATION_CONFLICT","PREPARED");}
  async getPreparation(id){return freeze(clone(this.preparations.find(x=>x.preparedObservationId===id)??null));}
  async recordAuthorization(value){const existing=this.authorizations.find(x=>x.authorizationId===value.authorizationId);if(existing)return stable(existing)===stable(value)?{status:"DUPLICATE",value:freeze(clone(existing))}:Promise.reject(new Error("REPEAT_OBSERVATION_AUTHORIZATION_CONFLICT"));const active=this.authorizations.find(x=>x.preparedObservationId===value.preparedObservationId&&Date.parse(value.authorizedAt)<Date.parse(x.expiresAt));if(active)throw new Error("REPEAT_OBSERVATION_AUTHORIZATION_ACTIVE");this.authorizations.push(clone(value));return{status:"AUTHORIZED",value:freeze(clone(value))};}
  async getAuthorization(id){return freeze(clone(this.authorizations.find(x=>x.authorizationId===id)??null));}
  async _record(rows,key,value,code,status){const existing=rows.find(x=>x[key]===value[key]);if(existing){if(stable(existing)!==stable(value))throw new Error(code);return{status:"DUPLICATE",value:freeze(clone(existing))};}rows.push(clone(value));return{status,value:freeze(clone(value))};}
}

export class RepeatObservationService {
  constructor({productRepository,identityResolvers,rightsRegistry,repository,spendResolver=async()=>0,taskOwners={},now=()=>new Date().toISOString()}={}){if(!productRepository?.getById||!rightsRegistry?.require||!repository?.recordPreparation||!repository?.recordAuthorization)throw new Error("REPEAT_OBSERVATION_DEPENDENCIES_REQUIRED");Object.assign(this,{productRepository,identityResolvers,rightsRegistry,repository,spendResolver,taskOwners,now});}
  async prepare(input={}){exactKeys(input,["atlasProductId","source","observationCycle"],"REPEAT_OBSERVATION_PREPARE_INPUT_INVALID");const{atlasProductId,source,observationCycle}=input,product=await this.productRepository.getById(atlasProductId);if(product?.identity?.atlasProductId!==atlasProductId)throw new Error("REPEAT_OBSERVATION_ATLAS_PRODUCT_INVALID");const resolver=this.identityResolvers?.[source];if(!resolver?.resolve)throw new Error("REPEAT_OBSERVATION_IDENTITY_RESOLVER_REQUIRED");const reusableIdentity=await resolver.resolve({atlasProduct:product,source});const preparation=createRepeatObservationPreparation({atlasProductId,source,observationCycle,reusableIdentity,rightsProfile:this.rightsRegistry.require(source)});return this.repository.recordPreparation(preparation);}
  async authorize(input={}){exactKeys(input,["preparedObservationId","operator","reason","expiresAt","confirmation"],"REPEAT_OBSERVATION_AUTHORIZE_INPUT_INVALID");const{preparedObservationId,operator,reason,expiresAt,confirmation}=input;if(confirmation!==REPEAT_OBSERVATION_AUTHORIZE_CONFIRMATION)throw new Error("REPEAT_OBSERVATION_AUTHORIZE_CONFIRMATION_REQUIRED");const preparation=await this.repository.getPreparation(preparedObservationId);if(!preparation)throw new Error("REPEAT_OBSERVATION_PREPARATION_NOT_FOUND");const authorizedAt=this.now(),authorization=createRepeatObservationAuthorization({preparation,operator,reason,authorizedAt,expiresAt,currentUtcDaySpendUsd:await this.spendResolver(authorizedAt)});return this.repository.recordAuthorization(authorization);}
  async execute(input={}){exactKeys(input,["authorizationId","confirmation","executedBy"],"REPEAT_OBSERVATION_EXECUTE_INPUT_INVALID");const{authorizationId,confirmation,executedBy}=input;if(confirmation!==REPEAT_OBSERVATION_EXECUTE_CONFIRMATION)throw new Error("REPEAT_OBSERVATION_EXECUTE_CONFIRMATION_REQUIRED");required(executedBy,"REPEAT_OBSERVATION_EXECUTOR_REQUIRED");const authorization=await this.repository.getAuthorization(authorizationId);if(!authorization)throw new Error("REPEAT_OBSERVATION_AUTHORIZATION_NOT_FOUND");const executionTime=this.now();if(Date.parse(executionTime)>=Date.parse(authorization.expiresAt))throw new Error("REPEAT_OBSERVATION_AUTHORIZATION_EXPIRED");const preparation=await this.repository.getPreparation(authorization.preparedObservationId);validateRepeatObservationPreparation(preparation);if(preparation.bindingDigest!==authorization.preparationBindingDigest)throw new Error("REPEAT_OBSERVATION_BINDING_CONFLICT");const product=await this.productRepository.getById(preparation.atlasProductId),resolver=this.identityResolvers?.[preparation.source];if(product?.identity?.atlasProductId!==preparation.atlasProductId||!resolver?.resolve)throw new Error("REPEAT_OBSERVATION_IDENTITY_RESOLVER_REQUIRED");const currentIdentity=await resolver.resolve({atlasProduct:product,source:preparation.source});if(currentIdentity?.identityDigest!==preparation.reusableIdentity.identityDigest)throw new Error("REPEAT_OBSERVATION_IDENTITY_CHANGED");const rights=this.rightsRegistry.require(preparation.source);if(!rightsAllowed(rights)||hash(rights)!==preparation.sourceRightsProfileDigest)throw new Error("REPEAT_OBSERVATION_RIGHTS_CHANGED");if((await this.spendResolver(executionTime))+preparation.taskCostUsd>DATAFORSEO_DEFAULT_UTC_DAY_SPEND_CEILING_USD)throw new Error("REPEAT_OBSERVATION_DAILY_BUDGET_EXCEEDED");const owner=this.taskOwners[preparation.operation];if(!owner?.execute)throw new Error("REPEAT_OBSERVATION_TASK_OWNER_REQUIRED");return owner.execute({request:authorization,authorizedAt:authorization.authorizedAt});}
}

export function calculateRepeatObservationCohortBound(rows=[]){if(!Array.isArray(rows))throw new Error("REPEAT_OBSERVATION_COHORT_INVALID");const sourceCounts={DATAFORSEO_AMAZON:0,DATAFORSEO_GOOGLE_SHOPPING:0};let maximumSpendUsd=0;for(const row of rows){const policy=sourcePolicy[row?.source];if(!policy)throw new Error("REPEAT_OBSERVATION_SOURCE_UNSUPPORTED");sourceCounts[row.source]++;maximumSpendUsd+=policy.taskCostUsd;}return freeze({taskCount:rows.length,sourceCounts,maximumSpendUsd:Number(maximumSpendUsd.toFixed(4))});}
