import crypto from "node:crypto";

export const REUSABLE_IDENTITY_LINEAGE_VERSION="MERCURY-REPEAT-LINEAGE-1.0";
export const REUSABLE_IDENTITY_LINEAGE_TYPE="REUSABLE_IDENTITY_REPEAT_LINEAGE";
const stable=v=>Array.isArray(v)?`[${v.map(stable).join(",")}]`:v&&typeof v==="object"?`{${Object.keys(v).sort().map(k=>`${JSON.stringify(k)}:${stable(v[k])}`).join(",")}}`:JSON.stringify(v);
const hash=v=>crypto.createHash("sha256").update(stable(v)).digest("hex");
const freeze=v=>{if(v&&typeof v==="object"&&!Object.isFrozen(v)){Object.freeze(v);for(const child of Object.values(v))freeze(child);}return v;};
const text=v=>typeof v==="string"&&v.trim()?v.trim():null;
const identity=v=>({productId:v?.productId??null,dataDocId:v?.dataDocId??null,gid:v?.gid??null});
const material=value=>({policyVersion:value.policyVersion,lineageType:value.lineageType,atlasProductId:value.atlasProductId,sourceId:value.sourceId,operation:value.operation,reusableIdentityType:value.reusableIdentityType,reusableIdentityRecordId:value.reusableIdentityRecordId,reusableIdentityDigest:value.reusableIdentityDigest,sourceRightsProfileDigest:value.sourceRightsProfileDigest,preparedObservationId:value.preparedObservationId,repeatAuthorizationId:value.repeatAuthorizationId,parentRunAuthorizationId:value.parentRunAuthorizationId,paidActionIntentId:value.paidActionIntentId,acquisitionCycleId:value.acquisitionCycleId,observationCycle:value.observationCycle,providerTaskId:value.providerTaskId,canonicalResultId:value.canonicalResultId,canonicalResultDigest:value.canonicalResultDigest,providerIdentity:value.providerIdentity});

export function validateReusableIdentityAcquisitionLineage(value){
 const errors=[],providerIdentity=identity(value?.providerIdentity);
 if(value?.schemaVersion!=="1.0"||value?.policyVersion!==REUSABLE_IDENTITY_LINEAGE_VERSION||value?.lineageType!==REUSABLE_IDENTITY_LINEAGE_TYPE)errors.push("REPEAT_LINEAGE_TYPE_INVALID");
 for(const key of ["atlasProductId","sourceId","operation","reusableIdentityType","reusableIdentityRecordId","reusableIdentityDigest","sourceRightsProfileDigest","preparedObservationId","repeatAuthorizationId","paidActionIntentId","acquisitionCycleId","observationCycle","providerTaskId","canonicalResultId","canonicalResultDigest"])if(!text(value?.[key]))errors.push(`REPEAT_LINEAGE_${key.toUpperCase()}_INVALID`);
 if(!["SELLERS","AMAZON_SELLERS"].includes(value?.operation)||![["DATAFORSEO_GOOGLE_SHOPPING","SELLERS"],["DATAFORSEO_AMAZON","AMAZON_SELLERS"]].some(([s,o])=>s===value?.sourceId&&o===value?.operation))errors.push("REPEAT_LINEAGE_SOURCE_OPERATION_INVALID");
 if(!/^mer_repeatprep_[a-f0-9]{24}$/.test(value?.preparedObservationId??"")||!/^mer_repeatauth_[a-f0-9]{24}$/.test(value?.repeatAuthorizationId??"")||!/^mer_repeatintent_[a-f0-9]{24}$/.test(value?.paidActionIntentId??"")||!/^mer_repeatcycle_[a-f0-9]{24}$/.test(value?.acquisitionCycleId??"")||![value?.reusableIdentityDigest,value?.sourceRightsProfileDigest,value?.canonicalResultDigest].every(x=>/^[a-f0-9]{64}$/.test(x??""))||!Number.isFinite(Date.parse(value?.observationCycle??"")))errors.push("REPEAT_LINEAGE_BINDING_INVALID");
 if(value?.sourceId==="DATAFORSEO_AMAZON"&&!/^[A-Z0-9]{10}$/.test(value?.providerIdentity?.asin??""))errors.push("REPEAT_LINEAGE_AMAZON_IDENTITY_INVALID");
 if(value?.sourceId==="DATAFORSEO_AMAZON"&&!['STRONG_UNIQUE_ASIN','STRONG_OPERATOR_CONFIRMED_ASIN'].includes(value?.reusableIdentityType))errors.push("REPEAT_LINEAGE_AMAZON_AUTHORITY_INVALID");
 if(value?.sourceId==="DATAFORSEO_GOOGLE_SHOPPING"&&!Object.values(providerIdentity).some(text))errors.push("REPEAT_LINEAGE_GOOGLE_IDENTITY_INVALID");
 if(value?.sourceId==="DATAFORSEO_GOOGLE_SHOPPING"&&!['APPLICABLE','VERIFIED','REUSED'].includes(value?.reusableIdentityType))errors.push("REPEAT_LINEAGE_GOOGLE_AUTHORITY_INVALID");
 if(value?.lineageBindingDigest!==hash(material(value)))errors.push("REPEAT_LINEAGE_DIGEST_INVALID");
 return freeze({valid:errors.length===0,errors});
}

export function createReusableIdentityAcquisitionLineage({preparation,authorization,task,canonicalResult,parentRunAuthorizationId=null}={}){
 if(!preparation||!authorization||!task||!canonicalResult)throw new Error("REPEAT_LINEAGE_INPUT_REQUIRED");
 if(authorization.preparedObservationId!==preparation.preparedObservationId||authorization.preparationBindingDigest!==preparation.bindingDigest||task.paidActionIntentId!==preparation.paidActionIntentId||task.acquisitionCycleId!==preparation.acquisitionCycleId||task.preparedObservationId!==preparation.preparedObservationId||task.repeatAuthorizationId!==authorization.authorizationId||task.kind!==preparation.operation||task.sourceId!==preparation.source||task.atlasProductId!==preparation.atlasProductId||task.sourceRightsProfileDigest!==preparation.sourceRightsProfileDigest||task.reusableIdentityDigest!==preparation.reusableIdentity.identityDigest)throw new Error("REPEAT_LINEAGE_TASK_BINDING_CONFLICT");
 if(canonicalResult.providerTaskId!==task.taskId||canonicalResult.operation!==task.kind||canonicalResult.sourceId!==task.sourceId||canonicalResult.paidActionIntentId!==task.paidActionIntentId||canonicalResult.atlasProductId!==task.atlasProductId||canonicalResult.sourceRightsProfileDigest!==task.sourceRightsProfileDigest)throw new Error("REPEAT_LINEAGE_RESULT_BINDING_CONFLICT");
 const reusable=preparation.reusableIdentity,providerIdentity=preparation.source==="DATAFORSEO_AMAZON"?{asin:reusable.asin}:{...identity(reusable.providerIdentity)};
 const base={schemaVersion:"1.0",policyVersion:REUSABLE_IDENTITY_LINEAGE_VERSION,lineageType:REUSABLE_IDENTITY_LINEAGE_TYPE,atlasProductId:preparation.atlasProductId,sourceId:preparation.source,operation:preparation.operation,reusableIdentityType:reusable.identityState,reusableIdentityRecordId:reusable.identityRecordId,reusableIdentityDigest:reusable.identityDigest,sourceRightsProfileDigest:preparation.sourceRightsProfileDigest,preparedObservationId:preparation.preparedObservationId,repeatAuthorizationId:authorization.authorizationId,parentRunAuthorizationId:parentRunAuthorizationId??authorization.parentRunAuthorizationId??null,paidActionIntentId:preparation.paidActionIntentId,acquisitionCycleId:preparation.acquisitionCycleId,observationCycle:preparation.observationCycle,providerTaskId:task.taskId,canonicalResultId:canonicalResult.canonicalResultId,canonicalResultDigest:canonicalResult.resultDigest,providerIdentity};
 const value=freeze({...base,lineageBindingDigest:hash(material(base))}),report=validateReusableIdentityAcquisitionLineage(value);if(!report.valid)throw new Error(`REPEAT_LINEAGE_INVALID:${report.errors.join(",")}`);return value;
}

export function createGovernedReusableIdentityProjection({lineage,evidenceId,rawPayloadReference}={}){
 const report=validateReusableIdentityAcquisitionLineage(lineage);if(!report.valid)throw new Error(`REPEAT_LINEAGE_INVALID:${report.errors.join(",")}`);
 if((evidenceId!==null&&!text(evidenceId))||!text(rawPayloadReference)||!rawPayloadReference.startsWith(lineage.sourceId==="DATAFORSEO_AMAZON"?`dataforseo:amazon:sellers:${lineage.providerTaskId}:item:`:`dataforseo:sellers:${lineage.providerTaskId}:item:`))throw new Error("REPEAT_LINEAGE_EVIDENCE_BINDING_INVALID");
 const base={schemaVersion:"1.0",projectionType:"GOVERNED_REUSABLE_IDENTITY_ACQUISITION_BINDING",status:"APPLICABLE",evidenceId,rawPayloadReference,atlasProductId:lineage.atlasProductId,sellersTaskId:lineage.providerTaskId,sourceId:lineage.sourceId,reusableIdentityType:lineage.reusableIdentityType,reusableIdentityRecordId:lineage.reusableIdentityRecordId,reusableIdentityDigest:lineage.reusableIdentityDigest,lineageBindingDigest:lineage.lineageBindingDigest,providerIdentity:structuredClone(lineage.providerIdentity),effectiveProductState:"VERIFIED",atlasResolution:{outcome:"CONFIRMED",atlasProductId:lineage.atlasProductId,externalProductId:lineage.providerIdentity.productId??lineage.providerIdentity.asin??null,candidateAtlasProductIds:[],evidence:[{field:"governedReusableIdentity",status:"MATCH",external:lineage.reusableIdentityRecordId,atlas:lineage.atlasProductId}],automaticMercuryEligible:true}};
 return freeze({...base,projectionId:`mer_repeatid_${hash(base).slice(0,24)}`});
}

export function validateGovernedReusableIdentityProjection(value){
 const base={schemaVersion:value?.schemaVersion,projectionType:value?.projectionType,status:value?.status,evidenceId:value?.evidenceId,rawPayloadReference:value?.rawPayloadReference,atlasProductId:value?.atlasProductId,sellersTaskId:value?.sellersTaskId,sourceId:value?.sourceId,reusableIdentityType:value?.reusableIdentityType,reusableIdentityRecordId:value?.reusableIdentityRecordId,reusableIdentityDigest:value?.reusableIdentityDigest,lineageBindingDigest:value?.lineageBindingDigest,providerIdentity:value?.providerIdentity,effectiveProductState:value?.effectiveProductState,atlasResolution:value?.atlasResolution};
 const valid=value?.schemaVersion==="1.0"&&value?.projectionType==="GOVERNED_REUSABLE_IDENTITY_ACQUISITION_BINDING"&&value?.status==="APPLICABLE"&&(value.evidenceId===null||text(value.evidenceId))&&[value.rawPayloadReference,value.atlasProductId,value.sellersTaskId,value.sourceId,value.reusableIdentityRecordId].every(text)&&value.effectiveProductState==="VERIFIED"&&value.atlasResolution?.outcome==="CONFIRMED"&&value.atlasResolution?.atlasProductId===value.atlasProductId&&value.atlasResolution?.automaticMercuryEligible===true&&value.projectionId===`mer_repeatid_${hash(base).slice(0,24)}`;
 return freeze({valid,errors:valid?[]:["REUSABLE_IDENTITY_PROJECTION_INVALID"]});
}
