import {DatabaseSync} from "node:sqlite";
import {dirname,resolve} from "node:path";
import {mkdirSync} from "node:fs";
import {validateRepeatObservationPreparation} from "./RepeatObservationBoundary.js";

const stable=value=>Array.isArray(value)?`[${value.map(stable).join(",")}]`:value&&typeof value==="object"?`{${Object.keys(value).sort().map(key=>`${JSON.stringify(key)}:${stable(value[key])}`).join(",")}}`:JSON.stringify(value);
const freeze=value=>{const copy=structuredClone(value);const deep=item=>{if(item&&typeof item==="object"&&!Object.isFrozen(item)){Object.freeze(item);for(const child of Object.values(item))deep(child);}return item;};return deep(copy);};
const parse=row=>row?freeze(JSON.parse(row.payload_json)):null;
const required=(value,code)=>{if(typeof value!=="string"||!value)throw new Error(code);return value;};

export const REPEAT_OBSERVATION_SQLITE_SCHEMA_VERSION="1";

export class SqliteRepeatObservationRepository{
 constructor({databasePath,consumptionRepository=null}={}){if(!databasePath)throw new TypeError("REPEAT_OBSERVATION_DATABASE_PATH_REQUIRED");this.databasePath=resolve(databasePath);this.consumptionRepository=consumptionRepository;mkdirSync(dirname(this.databasePath),{recursive:true});this.db=new DatabaseSync(this.databasePath);this.db.exec("PRAGMA journal_mode=WAL; PRAGMA synchronous=FULL; PRAGMA foreign_keys=ON; PRAGMA busy_timeout=5000;");this._schema();}
 _schema(){this.db.exec(`CREATE TABLE IF NOT EXISTS repeat_schema(version TEXT PRIMARY KEY); INSERT OR IGNORE INTO repeat_schema(version) VALUES ('1'); CREATE TABLE IF NOT EXISTS repeat_preparations(prepared_observation_id TEXT PRIMARY KEY, paid_action_intent_id TEXT NOT NULL UNIQUE, acquisition_cycle_id TEXT NOT NULL, atlas_product_id TEXT NOT NULL, source_id TEXT NOT NULL, operation TEXT NOT NULL CHECK(operation IN ('SELLERS','AMAZON_SELLERS')), observation_cycle TEXT NOT NULL, binding_digest TEXT NOT NULL, payload_json TEXT NOT NULL, UNIQUE(atlas_product_id,source_id,observation_cycle)); CREATE INDEX IF NOT EXISTS repeat_preparation_cycle_idx ON repeat_preparations(acquisition_cycle_id); CREATE INDEX IF NOT EXISTS repeat_preparation_product_source_idx ON repeat_preparations(atlas_product_id,source_id,observation_cycle); CREATE TABLE IF NOT EXISTS repeat_authorizations(authorization_id TEXT PRIMARY KEY, prepared_observation_id TEXT NOT NULL REFERENCES repeat_preparations(prepared_observation_id), authorized_at TEXT NOT NULL, expires_at TEXT NOT NULL, binding_digest TEXT NOT NULL, payload_json TEXT NOT NULL); CREATE INDEX IF NOT EXISTS repeat_authorization_preparation_idx ON repeat_authorizations(prepared_observation_id,expires_at);`);const versions=this.db.prepare("SELECT version FROM repeat_schema").all();if(versions.length!==1||versions[0].version!==REPEAT_OBSERVATION_SQLITE_SCHEMA_VERSION)throw new Error("REPEAT_OBSERVATION_SCHEMA_VERSION_UNSUPPORTED");}
 close(){this.db.close();}
 async recordPreparation(value){validateRepeatObservationPreparation(value);const prior=this.findPreparationById(value.preparedObservationId);if(prior){if(stable(prior)!==stable(value))throw new Error("REPEAT_OBSERVATION_PREPARATION_CONFLICT");return{status:"DUPLICATE",value:prior};}try{this.db.prepare("INSERT INTO repeat_preparations VALUES (?,?,?,?,?,?,?,?,?)").run(value.preparedObservationId,value.paidActionIntentId,value.acquisitionCycleId,value.atlasProductId,value.source,value.operation,value.observationCycle,value.bindingDigest,JSON.stringify(value));return{status:"PREPARED",value:freeze(value)};}catch(error){if(String(error.message).includes("UNIQUE")){const concurrent=this.findPreparationById(value.preparedObservationId);if(concurrent&&stable(concurrent)===stable(value))return{status:"DUPLICATE",value:concurrent};throw new Error("REPEAT_OBSERVATION_PREPARATION_CONFLICT");}throw error;}}
 findPreparationById(id){return parse(this.db.prepare("SELECT payload_json FROM repeat_preparations WHERE prepared_observation_id=?").get(id));}
 async getPreparation(id){return this.findPreparationById(id);}
 findPreparationByPaidActionIntent(id){return parse(this.db.prepare("SELECT payload_json FROM repeat_preparations WHERE paid_action_intent_id=?").get(id));}
 findPreparationsByAcquisitionCycle(id){return freeze(this.db.prepare("SELECT payload_json FROM repeat_preparations WHERE acquisition_cycle_id=? ORDER BY prepared_observation_id").all(id).map(parse));}
 async _consumedIds(){if(!this.consumptionRepository?.getAll)return new Set();return new Set((await this.consumptionRepository.getAll()).map(value=>value.authorizationId));}
 async recordAuthorization(value){required(value?.authorizationId,"REPEAT_OBSERVATION_AUTHORIZATION_INVALID");const preparation=this.findPreparationById(value.preparedObservationId);if(!preparation||value.preparationBindingDigest!==preparation.bindingDigest||value.sourceRightsProfileDigest!==preparation.sourceRightsProfileDigest||value.maxSpendUsd!==preparation.maximumSpendUsd||value.singleUse!==true||value.automaticPaidRetries!==0||value.consumptionState!=="NOT_CONSUMED")throw new Error("REPEAT_OBSERVATION_AUTHORIZATION_BINDING_INVALID");const prior=this.findAuthorizationById(value.authorizationId);if(prior){if(stable(prior)!==stable(value))throw new Error("REPEAT_OBSERVATION_AUTHORIZATION_CONFLICT");return{status:"DUPLICATE",value:prior};}const consumed=await this._consumedIds();this.db.exec("BEGIN IMMEDIATE");try{const rows=this.db.prepare("SELECT authorization_id,payload_json FROM repeat_authorizations WHERE prepared_observation_id=? AND expires_at>?").all(value.preparedObservationId,value.authorizedAt);if(rows.some(row=>!consumed.has(row.authorization_id)))throw new Error("REPEAT_OBSERVATION_AUTHORIZATION_ACTIVE");this.db.prepare("INSERT INTO repeat_authorizations VALUES (?,?,?,?,?,?)").run(value.authorizationId,value.preparedObservationId,value.authorizedAt,value.expiresAt,value.authorizationBindingDigest,JSON.stringify(value));this.db.exec("COMMIT");return{status:"AUTHORIZED",value:freeze(value)};}catch(error){this.db.exec("ROLLBACK");if(String(error.message).includes("UNIQUE"))throw new Error("REPEAT_OBSERVATION_AUTHORIZATION_CONFLICT");throw error;}}
 findAuthorizationById(id){return parse(this.db.prepare("SELECT payload_json FROM repeat_authorizations WHERE authorization_id=?").get(id));}
 async getAuthorization(id){return this.findAuthorizationById(id);}
 findAuthorizationsByPreparation(id){return freeze(this.db.prepare("SELECT payload_json FROM repeat_authorizations WHERE prepared_observation_id=? ORDER BY authorized_at,authorization_id").all(id).map(parse));}
 async findActiveAuthorizationForPreparation(id,asOf){const consumed=await this._consumedIds();return this.findAuthorizationsByPreparation(id).find(value=>Date.parse(asOf)<Date.parse(value.expiresAt)&&!consumed.has(value.authorizationId))??null;}
 counts(){return this.db.prepare("SELECT (SELECT COUNT(*) FROM repeat_preparations) preparations,(SELECT COUNT(*) FROM repeat_authorizations) authorizations").get();}
}
