import {mkdir,readFile,rename,writeFile} from "node:fs/promises";
import {dirname,resolve} from "node:path";
import {FileSingleWriterRunLock,SINGLE_WRITER_LOCK_STATUSES} from "../../runtime/FileSingleWriterRunLock.js";
import {validateCanonicalObservationReviewAuthorization} from "../CanonicalObservationReviewAuthorization.js";

const initial=()=>({version:"1.0",authorizations:{},byIntent:{},consumptions:{}}),clone=structuredClone,freeze=value=>Object.freeze(value),intentKey=authorization=>`${authorization.observationId}:${authorization.candidateBinding.effectiveReviewDecisionId??"NONE"}`;
export class FileCanonicalObservationReviewAuthorizationRepository{
  constructor({statePath,now=()=>new Date().toISOString(),runLock}={}){if(!statePath)throw new TypeError("statePath is required.");this.statePath=resolve(statePath);this.now=now;this.queue=Promise.resolve();this.runLock=runLock??new FileSingleWriterRunLock({lockPath:`${this.statePath}.lock`,now});}
  async _locked(fn){const run=async()=>{const outcome=await this.runLock.runExclusive(fn);if(outcome.status!==SINGLE_WRITER_LOCK_STATUSES.COMPLETED)throw new Error("CANONICAL_REVIEW_AUTHORIZATION_REPOSITORY_BUSY");return outcome.result;},task=this.queue.then(run,run);this.queue=task.catch(()=>{});return task;}
  async _read(){try{const state=JSON.parse(await readFile(this.statePath,"utf8"));if(state?.version!=="1.0"||!state.authorizations||!state.byIntent||!state.consumptions)throw new Error();for(const [id,value] of Object.entries(state.authorizations))if(id!==value.authorizationId||!validateCanonicalObservationReviewAuthorization(value).valid)throw new Error();for(const [key,id] of Object.entries(state.byIntent))if(!state.authorizations[id]||key!==intentKey(state.authorizations[id]))throw new Error();for(const [id,value] of Object.entries(state.consumptions))if(id!==value.authorizationId||!state.authorizations[id]||typeof value.reviewDecisionId!=="string")throw new Error();return state;}catch(error){if(error?.code==="ENOENT")return initial();throw new Error("CANONICAL_REVIEW_AUTHORIZATION_STATE_INVALID");}}
  async _commit(state){await mkdir(dirname(this.statePath),{recursive:true});const temp=`${this.statePath}.tmp-${process.pid}-${Date.now()}`;await writeFile(temp,`${JSON.stringify(state,null,2)}\n`);await rename(temp,this.statePath);}
  async record(authorization){const report=validateCanonicalObservationReviewAuthorization(authorization);if(!report.valid)throw new TypeError(report.errors.join(","));return this._locked(async()=>{const state=await this._read(),key=intentKey(authorization),existingId=state.byIntent[key];if(existingId){const existing=state.authorizations[existingId];if(existing.authorizationId===authorization.authorizationId)return freeze(clone(existing));throw new Error("CANONICAL_REVIEW_AUTHORIZATION_CONFLICT");}state.authorizations[authorization.authorizationId]=clone(authorization);state.byIntent[key]=authorization.authorizationId;await this._commit(state);return freeze(clone(authorization));});}
  async getById(id){const value=(await this._read()).authorizations[id];return value?freeze(clone(value)):null;}
  async getConsumption(id){const value=(await this._read()).consumptions[id];return value?freeze(clone(value)):null;}
  async consume({authorizationId,candidateBindingDigest,reviewDecisionId}){return this._locked(async()=>{const state=await this._read(),authorization=state.authorizations[authorizationId];if(!authorization)throw new Error("CANONICAL_REVIEW_AUTHORIZATION_NOT_FOUND");if(authorization.candidateBindingDigest!==candidateBindingDigest)throw new Error("CANONICAL_REVIEW_AUTHORIZATION_CONSUMPTION_CONFLICT");const existing=state.consumptions[authorizationId];if(existing){if(existing.candidateBindingDigest!==candidateBindingDigest||existing.reviewDecisionId!==reviewDecisionId)throw new Error("CANONICAL_REVIEW_AUTHORIZATION_CONSUMPTION_CONFLICT");return freeze({status:"ALREADY_CONSUMED",consumption:clone(existing)});}const consumption={schemaVersion:"1.0",authorizationId,candidateBindingDigest,reviewDecisionId,consumedAt:this.now()};state.consumptions[authorizationId]=consumption;await this._commit(state);return freeze({status:"CONSUMED",consumption:clone(consumption)});});}
}
export default FileCanonicalObservationReviewAuthorizationRepository;
