import {mkdir,readFile,rename,writeFile} from "node:fs/promises";
import {dirname,resolve} from "node:path";

const initial=()=>({schemaVersion:"1.0",reviews:[]}),clone=structuredClone,stable=value=>JSON.stringify(value);
const freeze=value=>{if(value&&typeof value==="object"&&!Object.isFrozen(value)){Object.freeze(value);for(const child of Object.values(value))freeze(child);}return value;};
function validate(review){const rejectionReasons=["WRONG_PRODUCT","VARIANT_CONFLICT","NON_ACTIONABLE_PAGE","REDIRECT_OR_TRACKING_CONCERN","PAGE_UNAVAILABLE","OTHER_REVIEW_REQUIRED"],policies=["MERCURY-AMAZON-DESTINATION-PROGRESSION-1.0","MERCURY-AMAZON-DESTINATION-PROGRESSION-1.1"],base=review?.schemaVersion==="1.0"&&policies.includes(review?.policyVersion)&&review.reviewId&&review.preparationId&&review.preparationBindingDigest&&review.atlasProductId&&review.asin&&review.candidateUrl&&["APPROVE","REJECT"].includes(review.decision)&&review.reviewedBy&&Number.isFinite(Date.parse(review.reviewedAt))&&review.reviewMethod==="OPERATOR_EXACT_PRODUCT_REVIEW",decisionValid=review?.decision==="APPROVE"?review.approvalAttestation==="I-ATTEST-EXACT-AMAZON-PRODUCT-PAGE-REVIEW"&&review.approvedPublicPageUrl===review.candidateUrl&&review.rejectionReason===null:rejectionReasons.includes(review?.rejectionReason)&&review.approvalAttestation===null&&review.approvedPublicPageUrl===null;if(!base||!decisionValid)throw new Error("AMAZON_DESTINATION_REVIEW_RECORD_INVALID");}
export class FileAmazonDestinationReviewRepository{
 constructor({statePath}={}){if(!statePath)throw new TypeError("AMAZON_DESTINATION_REVIEW_STATE_REQUIRED");this.statePath=resolve(statePath);this.queue=Promise.resolve();}
 async _read(){try{const state=JSON.parse(await readFile(this.statePath,"utf8"));if(state?.schemaVersion!=="1.0"||!Array.isArray(state.reviews))throw new Error();for(const review of state.reviews)validate(review);return state;}catch(error){if(error?.code==="ENOENT")return initial();throw new Error("AMAZON_DESTINATION_REVIEW_STATE_INVALID");}}
 async _commit(state){await mkdir(dirname(this.statePath),{recursive:true});const temporary=`${this.statePath}.${process.pid}.${Date.now()}.tmp`;await writeFile(temporary,`${JSON.stringify(state,null,2)}\n`);await rename(temporary,this.statePath);}
 _locked(operation){const task=this.queue.then(operation,operation);this.queue=task.catch(()=>{});return task;}
 async record(review){validate(review);return this._locked(async()=>{const state=await this._read(),byId=state.reviews.find(value=>value.reviewId===review.reviewId),byPreparation=state.reviews.find(value=>value.preparationId===review.preparationId);if(byId){if(stable(byId)!==stable(review))throw new Error("AMAZON_DESTINATION_REVIEW_REPLAY_CONFLICT");return freeze({status:"DUPLICATE",value:clone(byId)});}if(byPreparation)throw new Error("AMAZON_DESTINATION_REVIEW_DECISION_CONFLICT");state.reviews.push(clone(review));await this._commit(state);return freeze({status:"RECORDED",value:clone(review)});});}
 async getById(reviewId){const value=(await this._read()).reviews.find(review=>review.reviewId===reviewId);return value?freeze(clone(value)):null;}
 async getByPreparationId(preparationId){const values=(await this._read()).reviews.filter(review=>review.preparationId===preparationId);if(values.length>1)throw new Error("AMAZON_DESTINATION_REVIEW_DECISION_CONFLICT");return values[0]?freeze(clone(values[0])):null;}
 async getAll(){return freeze((await this._read()).reviews.map(value=>clone(value)));}
}
