import crypto from "node:crypto";
import {mkdir,readFile,rename,rm,writeFile} from "node:fs/promises";
import {dirname,resolve} from "node:path";
import {FileSingleWriterRunLock,SINGLE_WRITER_LOCK_STATUSES} from "../runtime/FileSingleWriterRunLock.js";
import {assessRetailerDestinationBinding,retailerDestinationKey,validateRetailerDestination} from "./RetailerDestination.js";
import {loadRetailerDestinationSource} from "./RetailerDestinationSource.js";

const clone=structuredClone,freeze=value=>{if(value&&typeof value==="object"&&!Object.isFrozen(value)){Object.freeze(value);for(const child of Object.values(value))freeze(child);}return value;},digest=value=>crypto.createHash("sha256").update(value).digest("hex");

export class ProductionFlatRetailerDestinationRepository{
 constructor({statePath,productRepository,retailerRepository,runLock,fileOperations={readFile,writeFile,rename,rm,mkdir}}={}){if(!statePath||!productRepository?.getById||!productRepository?.getAll||!retailerRepository?.getById||!retailerRepository?.getAll)throw new TypeError("PRODUCTION_RETAILER_DESTINATION_REPOSITORY_DEPENDENCIES_REQUIRED");this.statePath=resolve(statePath);this.products=productRepository;this.retailers=retailerRepository;this.runLock=runLock??new FileSingleWriterRunLock({lockPath:`${this.statePath}.lock`});this.files=fileOperations;this.queue=Promise.resolve();}
 async _read(){try{const before=await this.files.readFile(this.statePath,"utf8"),beforeDigest=digest(before),[products,retailers]=await Promise.all([this.products.getAll(),this.retailers.getAll()]),validated=await loadRetailerDestinationSource({sourcePath:this.statePath,products,retailers}),after=await this.files.readFile(this.statePath,"utf8");if(digest(after)!==beforeDigest)throw new Error("RETAILER_DESTINATION_CONCURRENT_MUTATION");const document=JSON.parse(after);return{document,validated,contentDigest:beforeDigest};}catch(error){if(error?.message==="RETAILER_DESTINATION_CONCURRENT_MUTATION")throw error;if(String(error?.message??"").startsWith("RETAILER_DESTINATION_SOURCE_INVALID:"))throw error;throw new Error("RETAILER_DESTINATION_SOURCE_INVALID:MALFORMED_JSON");}}
 async _commit(document,expectedDigest){const current=await this.files.readFile(this.statePath,"utf8");if(digest(current)!==expectedDigest)throw new Error("RETAILER_DESTINATION_CONCURRENT_MUTATION");await this.files.mkdir(dirname(this.statePath),{recursive:true});const temporary=`${this.statePath}.tmp-${process.pid}-${crypto.randomUUID()}`;try{await this.files.writeFile(temporary,`${JSON.stringify(document,null,2)}\n`,{encoding:"utf8",flag:"wx"});const recheck=await this.files.readFile(this.statePath,"utf8");if(digest(recheck)!==expectedDigest)throw new Error("RETAILER_DESTINATION_CONCURRENT_MUTATION");await this.files.rename(temporary,this.statePath);}finally{await this.files.rm(temporary,{force:true}).catch(()=>{});}}
 async _locked(operation){const run=async()=>{const outcome=await this.runLock.runExclusive(operation);if(outcome.status!==SINGLE_WRITER_LOCK_STATUSES.COMPLETED)throw new Error("RETAILER_DESTINATION_REPOSITORY_BUSY");return outcome.result;},task=this.queue.then(run,run);this.queue=task.catch(()=>{});return task;}
 async getAll(){const state=await this._read();return freeze(state.validated.effective.map(value=>clone(value)));}
 async retain(destination){const report=validateRetailerDestination(destination);if(!report.valid)throw new TypeError(report.errors.join(","));const [product,retailer]=await Promise.all([this.products.getById(destination.atlasProductId),this.retailers.getById(destination.retailerId)]),binding=assessRetailerDestinationBinding({destination,product,retailer}),bindingErrors=binding.reasons.filter(reason=>!["RETAILER_DESTINATION_RETIRED","RETAILER_DESTINATION_ATLAS_PRODUCT_DRAFT_NOT_PUBLIC"].includes(reason));if(bindingErrors.length)throw new Error(bindingErrors.join(","));return this._locked(async()=>{const state=await this._read(),byId=state.document.records.find(value=>value.destinationId===destination.destinationId);if(byId){if(byId.materialFingerprint!==destination.materialFingerprint)throw new Error("RETAILER_DESTINATION_REPLAY_CONFLICT");return freeze({status:"DUPLICATE",destinationId:destination.destinationId});}const crossProduct=state.validated.effective.find(value=>value.status==="ACTIVE"&&value.retailerId===destination.retailerId&&value.marketplace===destination.marketplace&&value.atlasProductId!==destination.atlasProductId&&(value.retailerListingId===destination.retailerListingId||value.destinationUrl===destination.destinationUrl));if(crossProduct)throw new Error("RETAILER_DESTINATION_CROSS_PRODUCT_COLLISION");const key=retailerDestinationKey(destination),records=state.document.records.filter(value=>retailerDestinationKey(value)===key),superseded=new Set(records.map(value=>value.supersedesDestinationId).filter(Boolean)),heads=records.filter(value=>!superseded.has(value.destinationId));if(heads.length>1)throw new Error("RETAILER_DESTINATION_ACTIVE_HEAD_CONFLICT");if(destination.supersedesDestinationId){const predecessor=state.document.records.find(value=>value.destinationId===destination.supersedesDestinationId);if(!predecessor)throw new Error("RETAILER_DESTINATION_PREDECESSOR_NOT_FOUND");if(retailerDestinationKey(predecessor)!==key)throw new Error("RETAILER_DESTINATION_SUPERSESSION_BINDING_MISMATCH");if(predecessor.status!=="ACTIVE"||heads.length!==1||heads[0].destinationId!==predecessor.destinationId)throw new Error("RETAILER_DESTINATION_SUPERSESSION_PREDECESSOR_NOT_EFFECTIVE");}else if(heads.length)throw new Error("RETAILER_DESTINATION_PARALLEL_ACTIVE_CONFLICT");const next={schemaVersion:"1.0",records:[...state.document.records,clone(destination)]};await this._commit(next,state.contentDigest);return freeze({status:"RETAINED",destinationId:destination.destinationId});});}
}

export default ProductionFlatRetailerDestinationRepository;
