import crypto from "node:crypto";
import { mkdir, readFile, rename, rm, writeFile } from "node:fs/promises";
import { dirname, join, resolve } from "node:path";
import { validateBrand, validateBrandRepository } from "./BrandValidator.js";
import { validateProduct, validateRepository } from "./ProductValidator.js";
import { FileSingleWriterRunLock, SINGLE_WRITER_LOCK_STATUSES } from "../mercury/runtime/FileSingleWriterRunLock.js";
const sha=value=>crypto.createHash("sha256").update(value).digest("hex"),json=value=>`${JSON.stringify(value,null,2)}\n`,slug=value=>String(value).trim().toLowerCase().replace(/[^a-z0-9]+/g,"-").replace(/^-|-$/g,"");
export class FileAtlasCatalogAdministrationRepository{
 constructor({atlasRoot,runLock,files={mkdir,readFile,rename,rm,writeFile}}={}){if(!atlasRoot)throw new TypeError("ATLAS_ADMINISTRATION_ROOT_REQUIRED");this.root=resolve(atlasRoot);this.manifestPath=join(this.root,"atlas-manifest.json");this.files=files;this.lock=runLock??new FileSingleWriterRunLock({lockPath:`${this.manifestPath}.operator.lock`});}
 async _read(){const raw=await this.files.readFile(this.manifestPath,"utf8"),manifest=JSON.parse(raw);if(!Array.isArray(manifest.products)||!Array.isArray(manifest.brands))throw new Error("ATLAS_MANIFEST_INVALID");const load=async entry=>JSON.parse(await this.files.readFile(join(this.root,entry.path),"utf8"));return{raw,digest:sha(raw),manifest,products:await Promise.all(manifest.products.map(load)),brands:await Promise.all(manifest.brands.map(load))};}
 async getAll(){return structuredClone((await this._read()).products);}async getBrands(){return structuredClone((await this._read()).brands);}async getById(id){return(await this.getAll()).find(x=>x.identity.atlasProductId===id)??null;}
 async _atomic(target,content){await this.files.mkdir(dirname(target),{recursive:true});const temporary=`${target}.tmp-${process.pid}-${crypto.randomUUID()}`;try{await this.files.writeFile(temporary,content,{encoding:"utf8",flag:"wx"});await this.files.rename(temporary,target);}finally{await this.files.rm(temporary,{force:true}).catch(()=>{});}}
 async _exclusive(operation){const outcome=await this.lock.runExclusive(operation);if(outcome.status!==SINGLE_WRITER_LOCK_STATUSES.COMPLETED)throw new Error("ATLAS_ADMINISTRATION_BUSY");return outcome.result;}
 async registerBrand(brand){const report=validateBrand(brand);if(!report.valid)throw new Error(report.errors.map(x=>x.code).join(","));return this._exclusive(async()=>{const state=await this._read(),existing=state.brands.find(x=>x.brandId===brand.brandId||x.slug===brand.slug);if(existing){if(sha(json(existing))!==sha(json(brand)))throw new Error("ATLAS_BRAND_REPLAY_CONFLICT");return{status:"ALREADY_REGISTERED",brandId:brand.brandId};}if(!validateBrandRepository([...state.brands,brand]).valid)throw new Error("ATLAS_BRAND_REPOSITORY_INVALID");const path=`brands/${brand.slug}.json`,next={...state.manifest,generatedAt:brand.metadata.updatedAt,brands:[...state.manifest.brands,{brandId:brand.brandId,path}].sort((a,b)=>a.brandId.localeCompare(b.brandId))};if(sha(await this.files.readFile(this.manifestPath,"utf8"))!==state.digest)throw new Error("ATLAS_CONCURRENT_MUTATION");await this._atomic(join(this.root,path),json(brand));await this._atomic(this.manifestPath,json(next));return{status:"REGISTERED",brandId:brand.brandId};});}
 async createProduct(product){const report=validateProduct(product);if(!report.valid)throw new Error(report.errors.map(x=>x.code).join(","));return this._exclusive(async()=>{const state=await this._read(),id=product.identity.atlasProductId,existing=state.products.find(x=>x.identity.atlasProductId===id);if(existing){if(sha(json(existing))!==sha(json(product)))throw new Error("ATLAS_PRODUCT_REPLAY_CONFLICT");return{status:"ALREADY_CREATED",atlasProductId:id};}const validation=validateRepository([...state.products,product]);if(!validation.valid)throw new Error(validation.errors.map(x=>x.code).join(","));const family=product.extension.data.classification.formFactor==="SO_DIMM"?"sodimm":product.extension.data.classification.memoryType.toLowerCase(),path=`products/ram/${family}/${id}-${slug(product.identity.displayName)}.json`,next={...state.manifest,generatedAt:product.identity.updatedAt,products:[...state.manifest.products,{atlasProductId:id,productType:"ram",path}].sort((a,b)=>a.atlasProductId.localeCompare(b.atlasProductId))};if(sha(await this.files.readFile(this.manifestPath,"utf8"))!==state.digest)throw new Error("ATLAS_CONCURRENT_MUTATION");await this._atomic(join(this.root,path),json(product));await this._atomic(this.manifestPath,json(next));return{status:"CREATED",atlasProductId:id};});}
 async updateProduct(product,{expectedRevision}={}){const report=validateProduct(product);if(!report.valid)throw new Error(report.errors.map(x=>x.code).join(","));return this._exclusive(async()=>{const state=await this._read(),entry=state.manifest.products.find(x=>x.atlasProductId===product.identity.atlasProductId),prior=state.products.find(x=>x.identity.atlasProductId===product.identity.atlasProductId);if(!entry||!prior)throw new Error("ATLAS_PRODUCT_NOT_FOUND");if(prior.identity.recordRevision!==expectedRevision)throw new Error("ATLAS_PRODUCT_STALE_REVISION");for(const key of["atlasProductId","manufacturer","manufacturerPartNumber","createdAt"])if(product.identity[key]!==prior.identity[key])throw new Error("ATLAS_PRODUCT_STABLE_IDENTITY_CHANGE_PROHIBITED");if(product.identity.recordRevision!==expectedRevision+1)throw new Error("ATLAS_PRODUCT_REVISION_INVALID");if(!validateRepository(state.products.map(x=>x.identity.atlasProductId===product.identity.atlasProductId?product:x)).valid)throw new Error("ATLAS_PRODUCT_REPOSITORY_INVALID");await this._atomic(join(this.root,entry.path),json(product));return{status:"UPDATED",atlasProductId:product.identity.atlasProductId,recordRevision:product.identity.recordRevision};});}
}
