import crypto from 'node:crypto';
const stable=value=>Array.isArray(value)?`[${value.map(stable).join(',')}]`:value&&typeof value==='object'?`{${Object.keys(value).sort().map(key=>`${JSON.stringify(key)}:${stable(value[key])}`).join(',')}}`:JSON.stringify(value);
const atlasDigest=product=>crypto.createHash('sha256').update(stable({atlasProductId:product?.identity?.atlasProductId,manufacturerPartNumber:product?.identity?.manufacturerPartNumber,recordRevision:product?.identity?.recordRevision,lifecycleStatus:product?.governance?.lifecycleStatus,publicationStatus:product?.governance?.publicationStatus,engineeringValidationStatus:product?.governance?.engineeringValidationStatus})).digest('hex');
export function createProductEnrichmentProposal({resolution,sourceTaskId,createdAt=new Date().toISOString(),estimatedCostUsd=.001}={}){
  if(!resolution?.atlasProductId) throw new TypeError('resolution is required.');
  if(!sourceTaskId) throw new TypeError('sourceTaskId is required.');
  if(resolution.recommendationStatus!=='RECOMMENDED'||!resolution.recommendedCandidate) throw new Error('ENRICHMENT_REQUIRES_SAFE_RECOMMENDATION');
  const c=resolution.recommendedCandidate.item;
  if(!c.dataDocId&&!c.productId&&!c.gid) throw new Error('ENRICHMENT_REQUIRES_PROVIDER_IDENTIFIER');
  const proposalId=`enrich_${crypto.createHash('sha256').update(`${resolution.atlasProductId}|${sourceTaskId}|${c.dataDocId??c.productId??c.gid}`).digest('hex').slice(0,24)}`;
  return Object.freeze({schemaVersion:'1.0',proposalId,status:'PENDING_OPERATOR_REVIEW',createdAt,sourceTaskId,atlasProductId:resolution.atlasProductId,operation:'PRODUCT_INFO',estimatedCostUsd,maxPaidTasks:1,automaticPaidRetries:0,providerIdentity:Object.freeze({productId:c.productId,dataDocId:c.dataDocId,gid:c.gid}),candidate:Object.freeze({title:c.title,price:c.price,currency:c.currency,score:resolution.recommendedCandidate.score,exactMpnMatch:resolution.recommendedCandidate.exactMpnMatch}),authorizationCreated:false});
}

export function createGovernedSelectedProductEnrichmentProposal({atlasProduct,productsReview,equivalenceAssessment,selectionDecision,checkpointProduct,sourceRightsDigest,provider='DATAFORSEO',source='DATAFORSEO_GOOGLE_SHOPPING',locationName='United States',languageName='English',spend=null,createdAt=new Date().toISOString(),estimatedCostUsd=.001}={}){
  if(atlasProduct?.identity?.atlasProductId!==productsReview?.atlasProductId||selectionDecision?.atlasProductId!==atlasProduct.identity.atlasProductId) throw new Error('PRODUCT_INFO_PROVIDER_SELECTION_ATLAS_BINDING_INVALID');
  if(selectionDecision.sourceProductsReviewId!==productsReview.reviewId||selectionDecision.sourceProductsTaskId!==productsReview.providerTaskId||selectionDecision.equivalenceAssessmentId!==equivalenceAssessment?.equivalenceAssessmentId||selectionDecision.equivalenceGroupDigest!==equivalenceAssessment.groups?.find(group=>group.members.some(member=>JSON.stringify(member.providerIdentity)===JSON.stringify(selectionDecision.selectedProviderIdentity)))?.groupDigest) throw new Error('PRODUCT_INFO_PROVIDER_SELECTION_LINEAGE_INVALID');
  if(checkpointProduct?.atlasProductId!==atlasProduct.identity.atlasProductId||checkpointProduct.manufacturerPartNumber!==atlasProduct.identity.manufacturerPartNumber||checkpointProduct.atlasProductDigest!==atlasDigest(atlasProduct)||atlasProduct?.governance?.lifecycleStatus!=='ACTIVE'||atlasProduct?.governance?.publicationStatus!=='READY'||sourceRightsDigest!==productsReview.sourceRightsDigest||provider!=='DATAFORSEO'||source!=='DATAFORSEO_GOOGLE_SHOPPING'||typeof locationName!=='string'||!locationName||typeof languageName!=='string'||!languageName||!Number.isFinite(spend?.currentUtcDaySpendUsd)||!Number.isFinite(spend?.programSpendUsd)||!Number.isFinite(spend?.remainingUtcDayCapacityUsd)||!Number.isFinite(spend?.remainingProgramCapacityUsd)) throw new Error('PRODUCT_INFO_GOVERNANCE_BINDING_INVALID');
  const c=equivalenceAssessment.groups.flatMap(group=>group.members).find(member=>JSON.stringify(member.providerIdentity)===JSON.stringify(selectionDecision.selectedProviderIdentity));if(!c)throw new Error('PRODUCT_INFO_SELECTED_PROVIDER_IDENTITY_MISSING');
  const lineage=Object.freeze({equivalenceAssessmentId:equivalenceAssessment.equivalenceAssessmentId,equivalenceGroupDigest:selectionDecision.equivalenceGroupDigest,selectionDecisionId:selectionDecision.selectionDecisionId,sourceProductsReviewId:productsReview.reviewId});
  const governanceBinding=Object.freeze({canonicalMpn:atlasProduct.identity.manufacturerPartNumber,atlasProductDigest:checkpointProduct.atlasProductDigest,sourceRightsDigest,provider,source,providerRequest:Object.freeze({operation:'PRODUCT_INFO',...c.providerIdentity,locationName,languageName}),spend:Object.freeze({...spend})});
  const material=Object.freeze({atlasProductId:atlasProduct.identity.atlasProductId,sourceTaskId:productsReview.providerTaskId,providerIdentity:c.providerIdentity,providerSelectionLineage:lineage,governanceBinding}),materialDigest=crypto.createHash('sha256').update(JSON.stringify(material)).digest('hex'),proposalId=`enrich_${materialDigest.slice(0,24)}`;
  return Object.freeze({schemaVersion:'1.1',proposalId,status:'PENDING_OPERATOR_REVIEW',createdAt,sourceTaskId:productsReview.providerTaskId,atlasProductId:atlasProduct.identity.atlasProductId,operation:'PRODUCT_INFO',estimatedCostUsd,maxPaidTasks:1,automaticPaidRetries:0,providerIdentity:c.providerIdentity,candidate:Object.freeze({title:c.title,score:c.score,exactMpnMatch:c.exactMpnMatch}),providerSelectionLineage:lineage,governanceBinding,materialDigest,authorizationCreated:false,paidExecutionAuthority:false});
}
