import crypto from "node:crypto";
import { assessDataForSeoProductEvidenceAgainstAtlas } from "../../resolution/dataforseo/DataForSeoAtlasResolver.js";
import { validateProductInfoProviderIdentity } from "./ProductInfoResultBoundary.js";
const stable=value=>Array.isArray(value)?`[${value.map(stable).join(",")}]`:value&&typeof value==="object"?`{${Object.keys(value).sort().map(key=>`${JSON.stringify(key)}:${stable(value[key])}`).join(",")}}`:JSON.stringify(value),digest=value=>crypto.createHash("sha256").update(stable(value)).digest("hex"),freeze=value=>{if(value&&typeof value==="object"&&!Object.isFrozen(value)){Object.freeze(value);for(const child of Object.values(value))freeze(child);}return value;};
export const PRODUCT_INFO_BRAND_ALIAS_POLICY_VERSION="MERCURY-ACTIVATION-005G-1.0";
export function reassessProductInfoResult({priorResult,atlasProduct,brandRecord,assessedAt}={}){
 if(priorResult?.status!=="PRODUCT_INFO_REVIEW_REQUIRED"||!priorResult?.materialDigest||atlasProduct?.identity?.atlasProductId!==priorResult.atlasProductId||brandRecord?.displayName!==atlasProduct.identity.brand||!Array.isArray(brandRecord.aliases)||!Number.isFinite(Date.parse(assessedAt)))throw new Error("PRODUCT_INFO_REASSESSMENT_INPUT_INVALID");
 const e=priorResult.retrievedEvidence??{},rawItem={title:e.title,brand:e.brand,product_id:e.productId,data_docid:e.dataDocId,gid:e.gid,specifications:e.specifications},providerIdentity=validateProductInfoProviderIdentity({authorizedIdentity:priorResult.providerIdentity,resultIdentity:{productId:e.productId,dataDocId:e.dataDocId,gid:e.gid}}),atlas=assessDataForSeoProductEvidenceAgainstAtlas(rawItem,atlasProduct,{brandAliases:brandRecord.aliases}),validated=atlas.status!=="CONTRADICTION";
 const material={providerTaskId:priorResult.providerTaskId,priorResultId:priorResult.resultId,priorResultMaterialDigest:priorResult.materialDigest,atlasProductId:priorResult.atlasProductId,selectedProviderIdentity:priorResult.providerIdentity,brandPolicyVersion:PRODUCT_INFO_BRAND_ALIAS_POLICY_VERSION,canonicalBrand:brandRecord.displayName,brandAliases:[...brandRecord.aliases],providerIdentityValidation:providerIdentity,atlasValidation:atlas,resultStatus:validated?"PRODUCT_INFO_VALIDATED":"PRODUCT_INFO_REVIEW_REQUIRED",sellersReadiness:validated?"READY_FOR_SELLERS":"NOT_ESTABLISHED"},materialDigest=digest(material);
 return freeze({schemaVersion:"1.0",reassessmentId:`mer_productinforeassess_${materialDigest.slice(0,24)}`,...material,assessedAt,materialDigest,downstreamAuthority:{sellersExecution:false,retention:false,historical:false,canonical:false,review:false,publication:false,currentPrice:false,cheapest:false,pick:false},actualSpendUsd:0});
}
