import crypto from "node:crypto";
import {mkdir,readFile,rename,writeFile} from "node:fs/promises";
import path from "node:path";

export const PROVIDER_EQUIVALENCE_POLICY_VERSION="MERCURY-ACTIVATION-004D-1.0";
export const PROVIDER_SELECTION_POLICY_VERSION="MERCURY-ACTIVATION-004D-1.0";
const stable=value=>Array.isArray(value)?`[${value.map(stable).join(",")}]`:value&&typeof value==="object"?`{${Object.keys(value).sort().map(key=>`${JSON.stringify(key)}:${stable(value[key])}`).join(",")}}`:JSON.stringify(value);
const digest=value=>crypto.createHash("sha256").update(stable(value)).digest("hex");
const freeze=value=>{if(value&&typeof value==="object"&&!Object.isFrozen(value)){Object.freeze(value);for(const child of Object.values(value))freeze(child);}return value;};
const clone=value=>structuredClone(value);
const normalize=value=>String(value??"").toUpperCase().replace(/[^A-Z0-9]/g,"");
const validIso=value=>typeof value==="string"&&Number.isFinite(Date.parse(value));
const identity=item=>freeze({dataDocId:item?.dataDocId??null,productId:item?.productId??null,gid:item?.gid??null});
const identityKey=value=>stable([value.dataDocId,value.productId,value.gid]);
const validIdentity=value=>Boolean(value?.dataDocId||value?.productId||value?.gid);
const firstNumber=(text,patterns)=>{for(const pattern of patterns){const match=text.match(pattern);if(match)return Number(match[1]);}return null;};

function observedEvidence(title,atlasProduct,item={}){
 const text=String(title??""),upper=text.toUpperCase(),data=atlasProduct.extension?.data??{},moduleMatch=upper.match(/\b(\d+)\s*[X×]\s*(\d+)\s*GB\b/);
 return freeze({
  mpn:normalize(atlasProduct.identity?.manufacturerPartNumber)&&normalize(text).includes(normalize(atlasProduct.identity.manufacturerPartNumber))?normalize(atlasProduct.identity.manufacturerPartNumber):null,
  brand:(item.brand??item.providerBrand)?normalize(item.brand??item.providerBrand):normalize(text).includes(normalize(atlasProduct.identity?.brand))?normalize(atlasProduct.identity.brand):null,
  memoryType:/\bDDR5\b/.test(upper)?"DDR5":/\bDDR4\b/.test(upper)?"DDR4":null,
  capacityGb:firstNumber(upper,[/\b(\d+)\s*GB\b/]),moduleCount:moduleMatch?Number(moduleMatch[1]):null,capacityPerModuleGb:moduleMatch?Number(moduleMatch[2]):null,
  formFactor:/\bSO[- ]?DIMM\b/.test(upper)?"SODIMM":/\b(?:U[- ]?DIMM|DIMM)\b/.test(upper)?"DIMM":null,moduleType:/\bU[- ]?DIMM\b/.test(upper)?"UDIMM":null,
  dataRateMtps:firstNumber(upper,[/\bDDR[45][-_ ]?(\d{4,5})\b/,/\b(\d{4,5})\s*(?:MHZ|MT\/S|MTPS)\b/]),casLatency:firstNumber(upper,[/\bCL\s*(\d{1,3})\b/]),
  rgb:/\bRGB\b/.test(upper)?true:null,color:/\bBLACK\b/.test(upper)?"BLACK":/\bWHITE\b/.test(upper)?"WHITE":/\bGR(?:A|E)Y\b/.test(upper)?"GREY":null,
  condition:/\bOPEN[- ]?BOX\b/.test(upper)?"OPEN_BOX":/\bREFURB(?:ISHED)?\b/.test(upper)?"REFURBISHED":/\bUSED\b/.test(upper)?"USED":/\bNEW\b/.test(upper)?"NEW":null,
  bundle:/\b(?:BUNDLE|COMBO|WITH\s+(?:COOLER|MOTHERBOARD|CPU))\b/.test(upper)?true:null,replacement:/\b(?:REPLACEMENT\s+FOR|COMPATIBLE\s+WITH|REPLACEMENT-COMPATIBLE)\b/.test(upper)
 });
}
function atlasEvidence(product){const data=product.extension?.data??{};return {mpn:normalize(product.identity?.manufacturerPartNumber),brand:normalize(product.identity?.brand),memoryType:data.classification?.memoryType??null,capacityGb:data.capacity?.capacityGb??null,moduleCount:data.capacity?.moduleCount??null,capacityPerModuleGb:data.capacity?.capacityPerModuleGb??null,formFactor:data.classification?.formFactor??null,moduleType:data.classification?.moduleType??null,dataRateMtps:data.performance?.dataRateMtps??null,casLatency:data.performance?.casLatency??null,rgb:data.physical?.rgbLighting??null,color:data.physical?.color??null};}
const significant=["mpn","brand","memoryType","capacityGb","moduleCount","capacityPerModuleGb","formFactor","moduleType","dataRateMtps","casLatency","rgb","color","condition","bundle"];

export function assessProviderDocumentCandidate({atlasProduct,candidate,minimumScore=78}={}){
 if(!atlasProduct?.identity?.atlasProductId||!candidate?.item)throw new Error("PROVIDER_EQUIVALENCE_INPUT_INVALID");
 const evidence=observedEvidence(candidate.item.title,atlasProduct,candidate.item),atlas=atlasEvidence(atlasProduct),reasons=[];
 if(!candidate.exactMpnMatch||evidence.mpn!==atlas.mpn)reasons.push("EXACT_NORMALIZED_MPN_REQUIRED");
 if(!Number.isFinite(candidate.score)||candidate.score<minimumScore)reasons.push("RECOMMENDATION_THRESHOLD_NOT_MET");
 if(candidate.contradictions?.length)reasons.push(...candidate.contradictions.map(value=>`RESOLVER_CONTRADICTION:${value}`));
 if(evidence.replacement)reasons.push("REPLACEMENT_OR_COMPATIBILITY_MERCHANDISE");if(evidence.bundle)reasons.push("BUNDLE_OR_CONDITIONAL_VARIANT");if(evidence.condition&&evidence.condition!=="NEW")reasons.push(`CONDITION_CONFLICT:${evidence.condition}`);
 for(const field of Object.keys(atlas))if(evidence[field]!=null&&atlas[field]!=null&&evidence[field]!==atlas[field])reasons.push(`ATLAS_FIELD_CONTRADICTION:${field}`);
 return freeze({eligible:reasons.length===0,reasons,evidence,candidate});
}

export function deriveProviderDocumentEquivalenceGroups({atlasProduct,candidates,minimumScore=78}={}){
 if(!Array.isArray(candidates))throw new Error("PROVIDER_EQUIVALENCE_CANDIDATES_REQUIRED");const assessed=candidates.map(candidate=>assessProviderDocumentCandidate({atlasProduct,candidate,minimumScore})),groups=[];
 for(const member of assessed.filter(value=>value.eligible)){const group=groups.find(existing=>existing.every(prior=>!significant.some(field=>prior.evidence[field]!=null&&member.evidence[field]!=null&&prior.evidence[field]!==member.evidence[field])));if(group)group.push(member);else groups.push([member]);}
 return freeze({groups:groups.map(group=>freeze(group)),excluded:assessed.filter(value=>!value.eligible),assessed});
}

export function createProviderDocumentEquivalenceAssessment({atlasProduct,productsReview,assessedAt}={}){
 if(!validIso(assessedAt)||productsReview?.atlasProductId!==atlasProduct?.identity?.atlasProductId||productsReview?.identityState!=="CONTRADICTED"&&productsReview?.identityState!=="AMBIGUOUS_REVIEW_REQUIRED"||productsReview?.resultIdentity?.recommendationStatus!=="AMBIGUOUS")throw new Error("PROVIDER_EQUIVALENCE_SOURCE_REVIEW_INVALID");
 const derived=deriveProviderDocumentEquivalenceGroups({atlasProduct,candidates:productsReview.resultIdentity.candidates}),eligible=derived.groups.filter(group=>group.length>1);
 const groups=eligible.map(group=>{const members=group.map(member=>{const providerIdentity=identity(member.candidate.item);if(!validIdentity(providerIdentity))throw new Error("PROVIDER_EQUIVALENCE_MEMBER_IDENTITY_REQUIRED");const material={providerIdentity,title:member.candidate.item.title??null,score:member.candidate.score,exactMpnMatch:member.candidate.exactMpnMatch,evidence:member.evidence};return freeze({...material,evidenceDigest:digest(material)});}).sort((a,b)=>identityKey(a.providerIdentity).localeCompare(identityKey(b.providerIdentity)));const material={atlasProductId:atlasProduct.identity.atlasProductId,canonicalMpn:atlasProduct.identity.manufacturerPartNumber,sourceProductsTaskId:productsReview.providerTaskId,sourceProductsReviewId:productsReview.reviewId,members};return freeze({...material,groupDigest:digest(material)});});
 const binding={atlasProductId:atlasProduct.identity.atlasProductId,canonicalMpn:atlasProduct.identity.manufacturerPartNumber,sourceProductsTaskId:productsReview.providerTaskId,sourceProductsReviewId:productsReview.reviewId,sourceProductsReviewMaterialDigest:productsReview.materialDigest,groups};const materialFingerprint=digest(binding);
 return freeze({schemaVersion:"1.0",equivalenceAssessmentId:`mer_proveq_${materialFingerprint.slice(0,24)}`,...binding,assessmentResult:groups.length?"EQUIVALENCE_GROUPS_ESTABLISHED":"NO_EQUIVALENCE_GROUP",assessmentReasons:groups.length?["EXACT_MPN_NON_CONFLICTING_PROVIDER_DOCUMENTS"]:["NO_MULTI_MEMBER_EQUIVALENCE_GROUP"],assessedAt,assessorPolicyVersion:PROVIDER_EQUIVALENCE_POLICY_VERSION,materialFingerprint,selectedProviderIdentity:null,grantsMarketAuthority:false,grantsPublicationAuthority:false,actualSpendUsd:0});
}

export function selectionConfirmation({assessment,selectedProviderIdentity}={}){const member=assessment?.groups?.flatMap(group=>group.members).find(value=>identityKey(value.providerIdentity)===identityKey(selectedProviderIdentity));if(!member)throw new Error("MANUAL_PROVIDER_SELECTION_OUTSIDE_EQUIVALENCE_GROUP");return `SELECT-PROVIDER-${digest([assessment.atlasProductId,assessment.equivalenceAssessmentId,member.providerIdentity]).slice(0,16).toUpperCase()}`;}
export function prepareManualProviderSelection({assessment,selectedProviderIdentity,preparedAt}={}){
 if(assessment?.assessmentResult!=="EQUIVALENCE_GROUPS_ESTABLISHED"||assessment.assessorPolicyVersion!==PROVIDER_EQUIVALENCE_POLICY_VERSION)throw new Error("MANUAL_PROVIDER_SELECTION_ASSESSMENT_INVALID");if(!validIso(preparedAt))throw new Error("MANUAL_PROVIDER_SELECTION_PREPARED_AT_INVALID");const confirmationRequired=selectionConfirmation({assessment,selectedProviderIdentity}),material={equivalenceAssessmentId:assessment.equivalenceAssessmentId,equivalenceGroupDigest:assessment.groups.find(group=>group.members.some(member=>identityKey(member.providerIdentity)===identityKey(selectedProviderIdentity)))?.groupDigest,atlasProductId:assessment.atlasProductId,canonicalMpn:assessment.canonicalMpn,sourceProductsTaskId:assessment.sourceProductsTaskId,sourceProductsReviewId:assessment.sourceProductsReviewId,eligibleProviderIdentities:assessment.groups.flatMap(group=>group.members.map(member=>member.providerIdentity)),selectedProviderIdentity:identity(selectedProviderIdentity)};const fingerprint=digest(material);return freeze({schemaVersion:"1.0",selectionRequestId:`mer_provselreq_${fingerprint.slice(0,24)}`,...material,preparedAt,status:"PENDING_OPERATOR_CONFIRMATION",confirmationRequired,policyVersion:PROVIDER_SELECTION_POLICY_VERSION,fingerprint,paidTaskCreated:false,actualSpendUsd:0});
}
export function createManualProviderSelectionDecision({assessment,request,confirmation,operator,reason,selectedAt}={}){
 if(request?.equivalenceAssessmentId!==assessment?.equivalenceAssessmentId||request?.fingerprint!==digest({equivalenceAssessmentId:request.equivalenceAssessmentId,equivalenceGroupDigest:request.equivalenceGroupDigest,atlasProductId:request.atlasProductId,canonicalMpn:request.canonicalMpn,sourceProductsTaskId:request.sourceProductsTaskId,sourceProductsReviewId:request.sourceProductsReviewId,eligibleProviderIdentities:request.eligibleProviderIdentities,selectedProviderIdentity:request.selectedProviderIdentity}))throw new Error("MANUAL_PROVIDER_SELECTION_REQUEST_BINDING_INVALID");
 if(confirmation!==request.confirmationRequired)throw new Error("MANUAL_PROVIDER_SELECTION_CONFIRMATION_REQUIRED");if(typeof operator!=="string"||!operator.trim()||/^<[^>]+>$/.test(operator.trim()))throw new Error("MANUAL_PROVIDER_SELECTION_OPERATOR_REQUIRED");if(typeof reason!=="string"||!reason.trim())throw new Error("MANUAL_PROVIDER_SELECTION_REASON_REQUIRED");if(!validIso(selectedAt))throw new Error("MANUAL_PROVIDER_SELECTION_TIME_REQUIRED");selectionConfirmation({assessment,selectedProviderIdentity:request.selectedProviderIdentity});
 const material={selectionRequestId:request.selectionRequestId,equivalenceAssessmentId:request.equivalenceAssessmentId,equivalenceGroupDigest:request.equivalenceGroupDigest,atlasProductId:request.atlasProductId,canonicalMpn:request.canonicalMpn,sourceProductsTaskId:request.sourceProductsTaskId,sourceProductsReviewId:request.sourceProductsReviewId,eligibleProviderIdentities:request.eligibleProviderIdentities,selectedProviderIdentity:request.selectedProviderIdentity,operator:operator.trim(),reason:reason.trim(),selectedAt,policyVersion:PROVIDER_SELECTION_POLICY_VERSION};const fingerprint=digest(material);return freeze({schemaVersion:"1.0",selectionDecisionId:`mer_provsel_${fingerprint.slice(0,24)}`,...material,decision:"SELECTED_PROVIDER_IDENTITY_FOR_DOWNSTREAM_LINEAGE",fingerprint,grantsAtlasIdentity:false,grantsMarketAuthority:false,grantsHistoricalAuthority:false,grantsPublicationAuthority:false,grantsRankingAuthority:false,grantsRecommendationAuthority:false,actualSpendUsd:0});
}

const empty=()=>({schemaVersion:"1.0",assessments:{},assessmentByReview:{},requests:{},requestByAssessment:{},decisions:{},decisionByAssessment:{}});
function validateStoredAssessment(value){for(const group of value?.groups??[]){for(const member of group.members??[]){const {evidenceDigest,...material}=member;if(evidenceDigest!==digest(material)||!validIdentity(member.providerIdentity))throw new Error("PROVIDER_IDENTITY_GOVERNANCE_STATE_INVALID");}const {groupDigest,...material}=group;if(groupDigest!==digest(material))throw new Error("PROVIDER_IDENTITY_GOVERNANCE_STATE_INVALID");}const binding={atlasProductId:value?.atlasProductId,canonicalMpn:value?.canonicalMpn,sourceProductsTaskId:value?.sourceProductsTaskId,sourceProductsReviewId:value?.sourceProductsReviewId,sourceProductsReviewMaterialDigest:value?.sourceProductsReviewMaterialDigest,groups:value?.groups};const fingerprint=digest(binding);if(!validIso(value?.assessedAt)||value.assessorPolicyVersion!==PROVIDER_EQUIVALENCE_POLICY_VERSION||value.materialFingerprint!==fingerprint||value.equivalenceAssessmentId!==`mer_proveq_${fingerprint.slice(0,24)}`)throw new Error("PROVIDER_IDENTITY_GOVERNANCE_STATE_INVALID");}
function validateStoredRequest(value){const material={equivalenceAssessmentId:value?.equivalenceAssessmentId,equivalenceGroupDigest:value?.equivalenceGroupDigest,atlasProductId:value?.atlasProductId,canonicalMpn:value?.canonicalMpn,sourceProductsTaskId:value?.sourceProductsTaskId,sourceProductsReviewId:value?.sourceProductsReviewId,eligibleProviderIdentities:value?.eligibleProviderIdentities,selectedProviderIdentity:value?.selectedProviderIdentity},fingerprint=digest(material);if(!validIso(value?.preparedAt)||value.status!=="PENDING_OPERATOR_CONFIRMATION"||value.policyVersion!==PROVIDER_SELECTION_POLICY_VERSION||value.fingerprint!==fingerprint||value.selectionRequestId!==`mer_provselreq_${fingerprint.slice(0,24)}`)throw new Error("PROVIDER_IDENTITY_GOVERNANCE_STATE_INVALID");}
function validateStoredDecision(value){const material={selectionRequestId:value?.selectionRequestId,equivalenceAssessmentId:value?.equivalenceAssessmentId,equivalenceGroupDigest:value?.equivalenceGroupDigest,atlasProductId:value?.atlasProductId,canonicalMpn:value?.canonicalMpn,sourceProductsTaskId:value?.sourceProductsTaskId,sourceProductsReviewId:value?.sourceProductsReviewId,eligibleProviderIdentities:value?.eligibleProviderIdentities,selectedProviderIdentity:value?.selectedProviderIdentity,operator:value?.operator,reason:value?.reason,selectedAt:value?.selectedAt,policyVersion:value?.policyVersion},fingerprint=digest(material);if(!validIso(value?.selectedAt)||value.decision!=="SELECTED_PROVIDER_IDENTITY_FOR_DOWNSTREAM_LINEAGE"||value.policyVersion!==PROVIDER_SELECTION_POLICY_VERSION||value.fingerprint!==fingerprint||value.selectionDecisionId!==`mer_provsel_${fingerprint.slice(0,24)}`)throw new Error("PROVIDER_IDENTITY_GOVERNANCE_STATE_INVALID");}
export class FileProviderIdentityGovernanceRepository{
 constructor({statePath}={}){if(!statePath)throw new Error("PROVIDER_IDENTITY_GOVERNANCE_STATE_PATH_REQUIRED");this.statePath=path.resolve(statePath);this.queue=Promise.resolve();}
 async read(){try{const state=JSON.parse(await readFile(this.statePath,"utf8"));for(const key of ["assessments","assessmentByReview","requests","requestByAssessment","decisions","decisionByAssessment"])if(!state?.[key]||Array.isArray(state[key]))throw new Error("PROVIDER_IDENTITY_GOVERNANCE_STATE_INVALID");for(const [id,value] of Object.entries(state.assessments)){validateStoredAssessment(value);if(value.equivalenceAssessmentId!==id||state.assessmentByReview[value.sourceProductsReviewId]!==id)throw new Error("PROVIDER_IDENTITY_GOVERNANCE_STATE_INVALID");}for(const [id,value] of Object.entries(state.requests)){validateStoredRequest(value);if(value.selectionRequestId!==id||state.requestByAssessment[value.equivalenceAssessmentId]!==id||!state.assessments[value.equivalenceAssessmentId])throw new Error("PROVIDER_IDENTITY_GOVERNANCE_STATE_INVALID");}for(const [id,value] of Object.entries(state.decisions)){validateStoredDecision(value);if(value.selectionDecisionId!==id||state.decisionByAssessment[value.equivalenceAssessmentId]!==id||!state.requests[value.selectionRequestId])throw new Error("PROVIDER_IDENTITY_GOVERNANCE_STATE_INVALID");}return state;}catch(error){if(error?.code==="ENOENT")return empty();throw error;}}
 async commit(state){await mkdir(path.dirname(this.statePath),{recursive:true});const temp=`${this.statePath}.${process.pid}.tmp`;await writeFile(temp,`${JSON.stringify(state,null,2)}\n`);await rename(temp,this.statePath);}
 async locked(fn){const next=this.queue.then(fn,fn);this.queue=next.catch(()=>{});return next;}
 async persist(kind,indexKind,indexKey,id,value,conflict){return this.locked(async()=>{const state=await this.read(),existingId=state[indexKind][indexKey];if(existingId){const existing=state[kind][existingId],sameMaterial=value.materialFingerprint!=null&&existing?.materialFingerprint===value.materialFingerprint,sameFingerprint=value.fingerprint!=null&&existing?.fingerprint===value.fingerprint;if(sameMaterial||sameFingerprint)return freeze({status:"DUPLICATE",value:freeze(clone(existing))});throw new Error(conflict);}state[kind][id]=clone(value);state[indexKind][indexKey]=id;await this.commit(state);return freeze({status:"RECORDED",value});});}
 persistAssessment(value){return this.persist("assessments","assessmentByReview",value.sourceProductsReviewId,value.equivalenceAssessmentId,value,"PROVIDER_EQUIVALENCE_ASSESSMENT_CONFLICT");}
 persistRequest(value){return this.persist("requests","requestByAssessment",value.equivalenceAssessmentId,value.selectionRequestId,value,"MANUAL_PROVIDER_SELECTION_PREPARE_CONFLICT");}
 persistDecision(value){return this.persist("decisions","decisionByAssessment",value.equivalenceAssessmentId,value.selectionDecisionId,value,"MANUAL_PROVIDER_SELECTION_CONFLICT");}
 async getAssessment(id){return freeze(clone((await this.read()).assessments[id]??null));}async getRequest(id){return freeze(clone((await this.read()).requests[id]??null));}async getDecisionForAssessment(id){const state=await this.read(),decisionId=state.decisionByAssessment[id];return freeze(clone(decisionId?state.decisions[decisionId]:null));}
}
