import { mkdir, readFile, rename, writeFile } from "node:fs/promises";
import path from "node:path";
import { validateManualSnapshotExecutionAuthorization } from "./ManualCurrentPriceSnapshotExecution.js";

const empty = () => ({ schemaVersion: "1.0", authorizations: [], executions: [] });
const freeze = value => { if (value && typeof value === "object" && !Object.isFrozen(value)) { Object.freeze(value); for (const child of Object.values(value)) freeze(child); } return value; };

export class FileManualCurrentPriceSnapshotExecutionRepository {
  constructor({ filePath } = {}) { if (!filePath) throw new TypeError("MANUAL_CURRENT_DISPLAY_EXECUTION_REPOSITORY_PATH_REQUIRED"); this.filePath = path.resolve(filePath); this.queue = Promise.resolve(); }
  async #read() { try { const value = JSON.parse(await readFile(this.filePath, "utf8")); if (value?.schemaVersion !== "1.0" || !Array.isArray(value.authorizations) || !Array.isArray(value.executions)) throw new Error(); value.authorizations.forEach(validateManualSnapshotExecutionAuthorization); return value; } catch (error) { if (error?.code === "ENOENT") return empty(); throw new Error("MANUAL_CURRENT_DISPLAY_EXECUTION_REPOSITORY_INVALID"); } }
  async #write(value) { await mkdir(path.dirname(this.filePath), { recursive: true }); const temporary = `${this.filePath}.tmp-${process.pid}-${Date.now()}`; await writeFile(temporary, `${JSON.stringify(value, null, 2)}\n`, "utf8"); await rename(temporary, this.filePath); }
  async #locked(operation) { const task = this.queue.then(operation, operation); this.queue = task.catch(() => {}); return task; }
  async recordAuthorization(value) { validateManualSnapshotExecutionAuthorization(value); return this.#locked(async()=>{const state=await this.#read(),prior=state.authorizations.find(row=>row.authorizationId===value.authorizationId);if(prior){if(JSON.stringify(prior)!==JSON.stringify(value))throw new Error("MANUAL_CURRENT_DISPLAY_AUTHORIZATION_CONFLICT");return freeze({status:"EXISTING",value:structuredClone(prior)});}state.authorizations.push(structuredClone(value));state.authorizations.sort((a,b)=>a.authorizationId.localeCompare(b.authorizationId));await this.#write(state);return freeze({status:"CREATED",value:structuredClone(value)});}); }
  async recordExecution(value) { return this.#locked(async()=>{const state=await this.#read();if(!state.authorizations.some(row=>row.authorizationId===value?.authorizationId))throw new Error("MANUAL_CURRENT_DISPLAY_AUTHORIZATION_NOT_FOUND");const byAuthorization=state.executions.find(row=>row.authorizationId===value.authorizationId);if(byAuthorization){if(JSON.stringify(byAuthorization)!==JSON.stringify(value))throw new Error("MANUAL_CURRENT_DISPLAY_EXECUTION_CONFLICT");return freeze({status:"EXISTING",value:structuredClone(byAuthorization)});}if(state.executions.some(row=>row.preparationId===value.preparationId))throw new Error("MANUAL_CURRENT_DISPLAY_PREPARATION_ALREADY_EXECUTED");state.executions.push(structuredClone(value));state.executions.sort((a,b)=>a.executionId.localeCompare(b.executionId));await this.#write(state);return freeze({status:"CREATED",value:structuredClone(value)});}); }
  async getAuthorization(id) { const value=(await this.#read()).authorizations.find(row=>row.authorizationId===id);if(!value)throw new Error("MANUAL_CURRENT_DISPLAY_AUTHORIZATION_NOT_FOUND");return freeze(structuredClone(value)); }
  async getExecutionByAuthorization(id) { const value=(await this.#read()).executions.find(row=>row.authorizationId===id);return value?freeze(structuredClone(value)):null; }
  async findForPreparation(preparationId) { const state=await this.#read(),authorizations=state.authorizations.filter(row=>row.binding.preparationId===preparationId),ids=new Set(state.executions.map(row=>row.authorizationId));return freeze({authorizations:structuredClone(authorizations),executionAuthorizationIds:[...ids],executed:state.executions.some(row=>row.preparationId===preparationId)}); }
  async getExecutionByPreparation(preparationId) { const value=(await this.#read()).executions.find(row=>row.preparationId===preparationId);return value?freeze(structuredClone(value)):null; }
  async getState() { return freeze(structuredClone(await this.#read())); }
}
