import { validateSupplementalConditionEvidence, supplementalConditionStableHash } from "./SupplementalConditionEvidence.js";
import { validateSupplementalOfferBinding } from "./OfferConditionBinding.js";
import { evaluateConditionTemporalCompatibility, CONDITION_TEMPORAL_POLICY_VERSION } from "./ConditionTemporalPolicy.js";
import { RIGHTS_STATES, SOURCE_RIGHTS_CAPABILITIES } from "../rights/SourceRightsPolicy.js";
export const EFFECTIVE_CONDITION_POLICY_VERSION = "B-017A-1.0";
export const EFFECTIVE_CONDITION_OUTCOMES = Object.freeze({ CONFIRMED_NEW: "CONFIRMED_NEW", CONFIRMED_NON_NEW: "CONFIRMED_NON_NEW", UNKNOWN: "UNKNOWN", CONFLICT: "CONFLICT" });
const freeze = value => { if (value && typeof value === "object" && !Object.isFrozen(value)) { Object.freeze(value); for (const child of Object.values(value)) freeze(child); } return value; };
const result = ({ canonicalObservation, primaryEvidence, evaluatedAt, outcome, effectiveCondition = "UNKNOWN", considered = [], qualifying = [], reasons = [], bindings = [], rights = [], temporal = [] }) => { const binding = { canonicalObservationId: canonicalObservation?.observationId ?? null, primaryEvidenceId: primaryEvidence?.evidenceId ?? null, evaluatedAt, consideredSupplementalEvidenceIds: considered, qualifyingSupplementalEvidenceIds: qualifying, bindingDigests: bindings, rightsResults: rights, temporalResults: temporal }; const bindingDigest = supplementalConditionStableHash(binding); return freeze({ schemaVersion: "1.0", assessmentType: "EFFECTIVE_OFFER_CONDITION", assessmentId: `mer_condassess_${supplementalConditionStableHash({ policyVersion: EFFECTIVE_CONDITION_POLICY_VERSION, bindingDigest, outcome, effectiveCondition, reasons }).slice(0,24)}`, policyVersion: EFFECTIVE_CONDITION_POLICY_VERSION, temporalPolicyFrameworkVersion: CONDITION_TEMPORAL_POLICY_VERSION, canonicalObservationId: binding.canonicalObservationId, primaryEvidenceId: binding.primaryEvidenceId, evaluatedAt, outcome, effectiveCondition, consideredSupplementalEvidenceIds: considered, qualifyingSupplementalEvidenceIds: qualifying, reasons: [...new Set(reasons)], blockers: [EFFECTIVE_CONDITION_OUTCOMES.CONFIRMED_NEW, EFFECTIVE_CONDITION_OUTCOMES.CONFIRMED_NON_NEW].includes(outcome) ? [] : [...new Set(reasons)], binding, bindingDigest, rightsResults: rights, temporalResults: temporal, contradiction: outcome === EFFECTIVE_CONDITION_OUTCOMES.CONFLICT, mutationAuthorized: false, publicationAuthority: false, currentPriceAuthority: false, cheapestAuthority: false, pickAuthority: false, networkOperation: "NONE", paidTaskCreated: false, actualSpendUsd: 0 }); };
export class EffectiveConditionAssessmentService {
    constructor({ evidenceRepository, rightsRegistry, temporalPolicyRepository } = {}) { if (!evidenceRepository?.getByCanonicalObservation || !rightsRegistry?.get || !temporalPolicyRepository?.resolve) throw new TypeError("EFFECTIVE_CONDITION_DEPENDENCY_REQUIRED"); Object.assign(this, { evidenceRepository, rightsRegistry, temporalPolicyRepository }); }
    async assess({ canonicalObservation, primaryEvidence, atlasProduct, primaryOfferIdentity, evaluatedAt } = {}) {
        if (!canonicalObservation || !primaryEvidence || !atlasProduct || !primaryOfferIdentity || !Number.isFinite(Date.parse(evaluatedAt))) return result({ canonicalObservation, primaryEvidence, evaluatedAt, outcome: EFFECTIVE_CONDITION_OUTCOMES.UNKNOWN, reasons: ["EFFECTIVE_CONDITION_INPUT_INVALID"] });
        const records = await this.evidenceRepository.getByCanonicalObservation(canonicalObservation.observationId), considered = records.map(record => record.supplementalEvidenceId), reasons = [], candidates = [], bindings = [], rightsResults = [], temporalResults = [];
        const superseded = new Set(records.map(record => record.lifecycle?.supersedesEvidenceId).filter(Boolean));
        for (const record of records) {
            if (superseded.has(record.supplementalEvidenceId)) { reasons.push("SUPPLEMENTAL_CONDITION_EVIDENCE_SUPERSEDED"); continue; }
            const validation = validateSupplementalConditionEvidence(record); if (!validation.valid) { reasons.push("SUPPLEMENTAL_CONDITION_RECORD_INVALID"); continue; }
            const binding = validateSupplementalOfferBinding({ record, canonicalObservation, primaryEvidence, atlasProduct, primaryOfferIdentity }); bindings.push(binding.bindingDigest); if (!binding.valid) { reasons.push(...binding.reasons); continue; }
            const profile = this.rightsRegistry.get(record.rights.sourceRightsId), state = profile?.derivation?.offerCondition ?? null, profileHash = profile ? supplementalConditionStableHash(profile) : null, rights = { supplementalEvidenceId: record.supplementalEvidenceId, sourceRightsId: record.rights.sourceRightsId, capability: SOURCE_RIGHTS_CAPABILITIES.OFFER_CONDITION, state: state ?? "UNKNOWN", profileHash, allowed: state === RIGHTS_STATES.ALLOWED && profileHash === record.rights.profileHash }; rightsResults.push(rights); if (!rights.allowed) { reasons.push(state === RIGHTS_STATES.ALLOWED ? "SUPPLEMENTAL_CONDITION_RIGHTS_BINDING_MISMATCH" : "SUPPLEMENTAL_CONDITION_RIGHTS_NOT_ALLOWED"); continue; }
            const resolution = this.temporalPolicyRepository.resolve({ sourceId: record.source.sourceId, retailerId: record.merchant.retailerId, marketplace: record.merchant.marketplace }); if (resolution.status !== "RESOLVED") { reasons.push(...resolution.reasons); continue; }
            const temporal = evaluateConditionTemporalCompatibility({ primaryObservedAt: canonicalObservation.observationTime, supplementalObservedAt: record.temporal.observedAt, evaluatedAt, policy: resolution.policy }); temporalResults.push({ supplementalEvidenceId: record.supplementalEvidenceId, ...temporal }); if (!temporal.compatible) { reasons.push(...temporal.reasons); continue; }
            if (record.condition.normalized === "UNKNOWN") { reasons.push("SUPPLEMENTAL_CONDITION_ASSERTION_UNKNOWN"); continue; }
            candidates.push(record);
        }
        if (!candidates.length) return result({ canonicalObservation, primaryEvidence, evaluatedAt, outcome: EFFECTIVE_CONDITION_OUTCOMES.UNKNOWN, considered, reasons: reasons.length ? reasons : ["SUPPLEMENTAL_CONDITION_EVIDENCE_MISSING"], bindings, rights: rightsResults, temporal: temporalResults });
        const conditions = [...new Set(candidates.map(record => record.condition.normalized))], qualifying = candidates.map(record => record.supplementalEvidenceId);
        if (conditions.length > 1) return result({ canonicalObservation, primaryEvidence, evaluatedAt, outcome: EFFECTIVE_CONDITION_OUTCOMES.CONFLICT, considered, qualifying, reasons: [...reasons, "SUPPLEMENTAL_CONDITION_CONFLICT"], bindings, rights: rightsResults, temporal: temporalResults });
        const effectiveCondition = conditions[0], outcome = effectiveCondition === "NEW" ? EFFECTIVE_CONDITION_OUTCOMES.CONFIRMED_NEW : EFFECTIVE_CONDITION_OUTCOMES.CONFIRMED_NON_NEW;
        return result({ canonicalObservation, primaryEvidence, evaluatedAt, outcome, effectiveCondition, considered, qualifying, reasons, bindings, rights: rightsResults, temporal: temporalResults });
    }
}
