import {assessBeaconGatewayRuntime,BEACON_GATEWAY_ATLAS_READ_STRATEGY} from "./BeaconGatewayRuntimeContract.js";
import {assessBeaconProductionStorage} from "./BeaconProductionStorageContract.js";
import {assessBeaconGatewayAbuseControl} from "./BeaconGatewayAbuseControlPolicy.js";
export const BEACON_GATEWAY_CONNECTION_STATES=Object.freeze(["NOT_CONNECTED","RUNTIME_SELECTED","BACKEND_READY_NOT_DEPLOYED","DEPLOYED_NOT_BROWSER_CONNECTED","CONNECTED"]);
const freeze=value=>{if(value&&typeof value==="object"&&!Object.isFrozen(value)){Object.freeze(value);for(const child of Object.values(value))freeze(child);}return value;};
export function assessBeaconGatewayReadiness({runtime=null,storage=null,retentionPolicyConfigured=false,rateLimitingConfigured=false,abuseControlPolicy=null,monitoringConfigured=false,atlasReadConfigured=false,deploymentConfigured=false,deployed=false,browserConnected=false}={}){
 const runtimeAssessment=assessBeaconGatewayRuntime(runtime),storageAssessment=assessBeaconProductionStorage(storage),abuseControlAssessment=abuseControlPolicy===null?null:assessBeaconGatewayAbuseControl(abuseControlPolicy),rateLimitMechanismSelected=abuseControlAssessment?.mechanismSelected??rateLimitingConfigured,rateLimitThresholdConfigured=abuseControlAssessment?.thresholdConfigured??rateLimitingConfigured;
 if([retentionPolicyConfigured,rateLimitingConfigured,monitoringConfigured,atlasReadConfigured,deploymentConfigured,deployed,browserConnected].some(x=>typeof x!=="boolean")||browserConnected&&!deployed||deployed&&!deploymentConfigured)throw new TypeError("BEACON_GATEWAY_READINESS_INPUT_INVALID");
 const prerequisites=runtimeAssessment.ready&&storageAssessment.ready&&retentionPolicyConfigured&&rateLimitThresholdConfigured&&monitoringConfigured&&atlasReadConfigured,backendReady=prerequisites&&deploymentConfigured;let state="NOT_CONNECTED";if(runtimeAssessment.selected)state="RUNTIME_SELECTED";if(backendReady&&!deployed)state="BACKEND_READY_NOT_DEPLOYED";if(backendReady&&deployed)state=browserConnected?"CONNECTED":"DEPLOYED_NOT_BROWSER_CONNECTED";
 const reasons=[];if(!runtimeAssessment.selected)reasons.push("RUNTIME_PROVIDER_NOT_SELECTED");else if(!runtimeAssessment.ready)reasons.push("RUNTIME_REQUIREMENTS_INCOMPLETE");if(!storageAssessment.configured)reasons.push("PRODUCTION_STORAGE_NOT_SELECTED");else if(!storageAssessment.ready)reasons.push("PRODUCTION_STORAGE_REQUIREMENTS_INCOMPLETE");if(!retentionPolicyConfigured)reasons.push("RETENTION_POLICY_NOT_CONFIGURED");if(!rateLimitMechanismSelected)reasons.push("RATE_LIMITING_NOT_CONFIGURED","RATE_LIMIT_MECHANISM_NOT_SELECTED");else if(!rateLimitThresholdConfigured)reasons.push("RATE_LIMIT_THRESHOLD_NOT_CONFIGURED");if(!monitoringConfigured)reasons.push("MONITORING_NOT_CONFIGURED");if(!atlasReadConfigured)reasons.push("ATLAS_READ_MODEL_NOT_CONFIGURED");if(!deploymentConfigured)reasons.push("DEPLOYMENT_NOT_CONFIGURED");if(!deployed)reasons.push("BACKEND_NOT_DEPLOYED");if(!browserConnected)reasons.push("BROWSER_NOT_CONNECTED");
 return freeze({schemaVersion:"1.0",statusType:"BEACON_GATEWAY_PRODUCTION_READINESS",state,runtime:runtimeAssessment,storage:storageAssessment,retentionPolicyConfigured,rateLimitingConfigured:rateLimitThresholdConfigured,rateLimitMechanismSelected,rateLimitThresholdConfigured,abuseControlPolicyId:abuseControlAssessment?.policyId??null,abuseControlMechanism:abuseControlAssessment?.mechanism??null,monitoringConfigured,atlasReadConfigured,atlasReadStrategy:BEACON_GATEWAY_ATLAS_READ_STRATEGY,deploymentConfigured,deployed,browserConnected,handlerReady:true,cadenceInfluence:"NONE",automaticExecution:false,unattendedLive:false,analyticsRecordsExposed:false,reasons,actualSpendUsd:0});
}
