const keys=["schemaVersion","evidenceType","verificationAuthority","verificationStatus","configurationKey","recipientAddress","providerDestinationReference","verifiedAt"],validAddress=value=>typeof value==="string"&&value===value.trim()&&value.length<=254&&/^[^\s<>(),;:@]+@[^\s<>(),;:@]+\.[^\s<>(),;:@]+$/.test(value)&&!value.includes(",")&&!value.includes(";"),nonBlank=value=>typeof value==="string"&&value.trim()!=="",validTime=value=>typeof value==="string"&&Number.isFinite(Date.parse(value));
export class CloudflareDestinationVerificationEvidence{
 #recipientAddress;
 constructor(input={}){if(!input||typeof input!=="object"||Array.isArray(input)||input.schemaVersion!=="1.0"||input.evidenceType!=="CLOUDFLARE_EMAIL_DESTINATION_VERIFICATION"||input.verificationAuthority!=="CLOUDFLARE_EMAIL_DESTINATION_VERIFICATION"||input.verificationStatus!=="VERIFIED"||input.configurationKey!=="BEACON_ALERT_RECIPIENT"||!validAddress(input.recipientAddress)||!nonBlank(input.providerDestinationReference)||!validTime(input.verifiedAt)||Object.keys(input).some(key=>!keys.includes(key)))throw new TypeError("CLOUDFLARE_DESTINATION_VERIFICATION_EVIDENCE_INVALID");this.schemaVersion=input.schemaVersion;this.evidenceType=input.evidenceType;this.verificationAuthority=input.verificationAuthority;this.verificationStatus=input.verificationStatus;this.configurationKey=input.configurationKey;this.providerDestinationReference=input.providerDestinationReference;this.verifiedAt=new Date(input.verifiedAt).toISOString();this.#recipientAddress=input.recipientAddress;Object.freeze(this);}
 matches({configurationKey,recipientAddress}){return configurationKey===this.configurationKey&&recipientAddress===this.#recipientAddress;}
 get evidenceReference(){return `${this.evidenceType}:${this.providerDestinationReference}:${this.verifiedAt}`;}
}
export function createCloudflareDestinationVerificationEvidence(input={}){return input instanceof CloudflareDestinationVerificationEvidence?input:new CloudflareDestinationVerificationEvidence(input);}
export default createCloudflareDestinationVerificationEvidence;
