import {createGatewayAlertOperatorRecipientConfiguration} from "./GatewayAlertOperatorRecipientConfiguration.js";
import {createCloudflareDestinationVerificationEvidence} from "./CloudflareDestinationVerificationEvidence.js";
export const GATEWAY_ALERT_RECIPIENT_RUNTIME_CONFIGURATION_KEY="BEACON_ALERT_RECIPIENT";
export const GATEWAY_ALERT_RECIPIENT_RUNTIME_CONFIGURATION_SOURCE="SERVER_SIDE_RUNTIME";
const validAddress=value=>typeof value==="string"&&value===value.trim()&&value.length<=254&&/^[^\s<>(),;:@]+@[^\s<>(),;:@]+\.[^\s<>(),;:@]+$/.test(value)&&!value.includes(",")&&!value.includes(";");
export class GatewayOperatorRecipientRuntimeConfiguration{
 #recipientAddress;
 constructor(input={}){if(!input||typeof input!=="object"||Array.isArray(input)||Object.keys(input).some(key=>key!==GATEWAY_ALERT_RECIPIENT_RUNTIME_CONFIGURATION_KEY))throw new TypeError("RECIPIENT_CONFIGURATION_INVALID");const present=Object.hasOwn(input,GATEWAY_ALERT_RECIPIENT_RUNTIME_CONFIGURATION_KEY);if(present&&!validAddress(input[GATEWAY_ALERT_RECIPIENT_RUNTIME_CONFIGURATION_KEY]))throw new TypeError("RECIPIENT_CONFIGURATION_INVALID");this.schemaVersion="1.0";this.configurationType="GATEWAY_OPERATOR_RECIPIENT_RUNTIME_CONFIGURATION";this.configurationKey=GATEWAY_ALERT_RECIPIENT_RUNTIME_CONFIGURATION_KEY;this.configurationSource=GATEWAY_ALERT_RECIPIENT_RUNTIME_CONFIGURATION_SOURCE;this.recipientValuePresent=present;this.recipientConfigured=present;this.verificationState=present?"PENDING_VERIFICATION":"NOT_CONFIGURED";this.recipientVerified=false;this.#recipientAddress=present?input[GATEWAY_ALERT_RECIPIENT_RUNTIME_CONFIGURATION_KEY]:null;Object.freeze(this);}
 project(governanceConfiguration,verificationEvidence=null){const governance=createGatewayAlertOperatorRecipientConfiguration(governanceConfiguration);if(governance.verificationState!=="NOT_CONFIGURED"||governance.recipientAddress!==null||governance.verificationEvidenceReference!==null||governance.enabled!==false)throw new TypeError("RECIPIENT_CONFIGURATION_INVALID");if(!this.recipientValuePresent){if(verificationEvidence===null)return governance;const evidence=createCloudflareDestinationVerificationEvidence(verificationEvidence);return createGatewayAlertOperatorRecipientConfiguration({...governance,verificationState:"VERIFIED",verificationEvidenceReference:evidence.evidenceReference,enabled:true});}if(verificationEvidence===null)return createGatewayAlertOperatorRecipientConfiguration({...governance,recipientAddress:this.#recipientAddress,verificationState:"PENDING_VERIFICATION"});const evidence=createCloudflareDestinationVerificationEvidence(verificationEvidence);if(!evidence.matches({configurationKey:this.configurationKey,recipientAddress:this.#recipientAddress}))throw new TypeError("RECIPIENT_VERIFICATION_EVIDENCE_MISMATCH");return createGatewayAlertOperatorRecipientConfiguration({...governance,recipientAddress:this.#recipientAddress,verificationState:"VERIFIED",verificationEvidenceReference:evidence.evidenceReference,enabled:true});}
}
export function createGatewayOperatorRecipientRuntimeConfiguration(input={}){return new GatewayOperatorRecipientRuntimeConfiguration(input);}
export default createGatewayOperatorRecipientRuntimeConfiguration;
