import {createProductInterestSignal} from "../beacon/ProductInterestSignal.js";
import {validateFirstPartyProductInterestEvent} from "../beacon/FirstPartyProductInterestEvent.js";
import {createFirstPartyInterestSignalId,firstPartyInterestEventFingerprint} from "../beacon/FirstPartyProductInterestCollectionRepository.js";
const freeze=value=>{if(value&&typeof value==="object"&&!Object.isFrozen(value)){Object.freeze(value);for(const child of Object.values(value))freeze(child);}return value;},clone=structuredClone;
function validateRecord(raw){try{const event=validateFirstPartyProductInterestEvent(raw.event),signal=createProductInterestSignal(raw.signal),materialFingerprint=firstPartyInterestEventFingerprint(event);if(Object.keys(raw).some(key=>!["event","signal","materialFingerprint"].includes(key))||JSON.stringify(signal)!==JSON.stringify(raw.signal)||raw.materialFingerprint!==materialFingerprint||signal.signalId!==createFirstPartyInterestSignalId(event.eventId)||signal.provenance?.eventId!==event.eventId||signal.provenance?.retailerId!==event.retailerId||signal.atlasProductId!==event.atlasProductId||signal.observedAt!==event.occurredAt)throw new Error();return freeze({event,signal,materialFingerprint});}catch{throw new Error("BEACON_TRANSACTIONAL_STORAGE_RECORD_INVALID");}}
export class TransactionalFirstPartyProductInterestCollectionRepository{
 constructor({transactionalStore}={}){if(!transactionalStore?.compareAndInsert||!transactionalStore?.listRecords)throw new TypeError("BEACON_TRANSACTIONAL_STORE_REQUIRED");this.store=transactionalStore;}
 async accept({event,signal}={}){const record=validateRecord({event,signal,materialFingerprint:firstPartyInterestEventFingerprint(event)}),result=await this.store.compareAndInsert(event.eventId,record);if(result?.status==="INSERTED")return freeze({status:"ACCEPTED",signal:clone(record.signal)});if(result?.status!=="EXISTING")throw new Error("BEACON_TRANSACTIONAL_STORAGE_FAILURE");const existing=validateRecord(result.record);if(existing.materialFingerprint!==record.materialFingerprint)throw new Error("FIRST_PARTY_INTEREST_EVENT_CONFLICT");return freeze({status:"DUPLICATE",signal:clone(existing.signal)});}
 async getSignals(){const records=await this.store.listRecords(),seen=new Set(),signals=[];if(!Array.isArray(records))throw new Error("BEACON_TRANSACTIONAL_STORAGE_FAILURE");for(const raw of records){const record=validateRecord(raw);if(seen.has(record.event.eventId))throw new Error("BEACON_TRANSACTIONAL_STORAGE_UNIQUENESS_VIOLATION");seen.add(record.event.eventId);signals.push(clone(record.signal));}return freeze(signals.sort((a,b)=>a.signalId.localeCompare(b.signalId)));}
}
export default TransactionalFirstPartyProductInterestCollectionRepository;
