import assert from "node:assert/strict";
import * as fs from "node:fs/promises";
import {createHash} from "node:crypto";
import {join} from "node:path";
import {tmpdir} from "node:os";
import {FileFirstPartyProductInterestCollectionRepository,FirstPartyProductInterestCollectionService,GovernedProductInterestHttpHandler,ProductInterestSignalRepository,ProductInterestSummaryService,getFirstPartyProductInterestCollectionStatus} from "../index.js";
const root=await fs.mkdtemp(join(tmpdir(),"hardware-radar-df005e-")),statePath=join(root,"beacon-interest.json"),productId="ram_corsair_cmk32gx5m2b6000z30",retailerId="RETAILER-0002",products=[{identity:{atlasProductId:productId}}],retailers=[{id:retailerId}],productRepository={getAll:async()=>structuredClone(products),getById:async id=>structuredClone(products.find(x=>x.identity.atlasProductId===id)??null)},retailerRepository={getById:async id=>structuredClone(retailers.find(x=>x.id===id)??null)},event=(overrides={})=>({schemaVersion:"1.0",eventId:"gateway-event-0001",atlasProductId:productId,signalType:"OUTBOUND_RETAILER_CLICK",sourceSurface:"OVERALL",occurredAt:"2026-08-25T10:00:00Z",retailerId,...overrides}),request=(body,overrides={})=>({path:"/api/beacon/product-interest",method:"POST",headers:{"content-type":"application/json","user-agent":"transient","x-forwarded-for":"192.0.2.1"},rawBody:JSON.stringify(body),recordedAt:"2026-08-25T10:00:01Z",...overrides}),cadenceUrl=new URL("../../mercury/historical-refresh/policies/initial-production-policy.json",import.meta.url),cadenceBefore=await fs.readFile(cadenceUrl),cadenceHash=createHash("sha256").update(cadenceBefore).digest("hex"),atlasBefore=structuredClone({products,retailers});
try{
 const repository=new FileFirstPartyProductInterestCollectionRepository({statePath}),service=new FirstPartyProductInterestCollectionService({productRepository,retailerRepository,collectionRepository:repository}),handler=new GovernedProductInterestHttpHandler({collectionService:service}),accepted=await handler.handle(request(event()));assert.equal(accepted.statusCode,202);assert.deepEqual(Object.keys(accepted.body).sort(),["signalId","status"]);assert.equal(accepted.body.status,"ACCEPTED");assert.match(accepted.body.signalId,/^beacon_interest_[a-f0-9]{24}$/);assert.equal("repository" in accepted.body,false);assert.equal("atlasProductId" in accepted.body,false);
 assert.equal((await handler.handle(request(event(),{path:"/api/other"}))).statusCode,404);assert.equal((await handler.handle(request(event(),{method:"GET"}))).statusCode,405);assert.equal((await handler.handle(request(event(),{headers:{"content-type":"text/plain"}}))).statusCode,415);assert.equal((await handler.handle({...request(event()),rawBody:"{"})).statusCode,400);assert.equal((await handler.handle({...request(event()),rawBody:"x".repeat(2049)})).statusCode,413);
 for(const invalid of [{unknown:true},{metadata:{unknown:true}},{atlasProductId:"unknown"},{retailerId:"RETAILER-9999"},{signalType:"PRODUCT_PAGE_VIEW"},{occurredAt:"invalid"},{name:"Person"},{email:"person@example.com"},{ipAddress:"127.0.0.1"},{userAgent:"agent"},{sessionId:"session"},{visitorId:"visitor"},{advertisingId:"ad"},{fingerprint:"hash"},{cookieId:"cookie"},{__protoPollution:"unsafe"}]){const result=await handler.handle(request(event(invalid)));assert.ok([400,404].includes(result.statusCode),JSON.stringify(invalid));}
 const replay=await handler.handle(request(event(),{recordedAt:"2026-08-25T10:00:02Z"}));assert.equal(replay.statusCode,200);assert.equal(replay.body.status,"DUPLICATE");assert.equal(replay.body.signalId,accepted.body.signalId);assert.equal((await repository.getSignals()).length,1);const conflict=await handler.handle(request(event({sourceSurface:"CATEGORY_DDR5"})));assert.equal(conflict.statusCode,409);assert.deepEqual(conflict.body,{error:"EVENT_CONFLICT"});const second=await handler.handle(request(event({eventId:"gateway-event-0002"})));assert.equal(second.statusCode,202);assert.notEqual(second.body.signalId,accepted.body.signalId);assert.equal((await repository.getSignals()).length,2);
 const reloaded=new FileFirstPartyProductInterestCollectionRepository({statePath}),signals=await reloaded.getSignals();assert.equal(signals.length,2);assert.deepEqual(signals.map(x=>x.signalId),[...signals.map(x=>x.signalId)].sort());assert.equal(Object.isFrozen(signals),true);assert.equal(Object.isFrozen(signals[0]),true);assert.equal(signals[0].observedAt,"2026-08-25T10:00:00Z");assert.notEqual(signals[0].observedAt,signals[0].metadata.recordedAt);for(const key of ["userAgent","ipAddress","sessionId"])assert.equal(key in signals[0],false);
 const signalRepository=new ProductInterestSignalRepository({signals,productRepository}),summary=await new ProductInterestSummaryService({signalRepository,productRepository}).query({atlasProductId:productId,asOf:"2026-08-26T00:00:00Z"});assert.equal(summary.interestState,"OBSERVED");assert.equal(summary.signalCount,2);assert.equal(summary.perType.OUTBOUND_RETAILER_CLICK.count,2);for(const key of ["score","rank","popularityScore","tier"])assert.equal(key in summary,false);
 const atomicPath=join(root,"atomic.json"),atomicRepo=new FileFirstPartyProductInterestCollectionRepository({statePath:atomicPath}),atomicService=new FirstPartyProductInterestCollectionService({productRepository,retailerRepository,collectionRepository:atomicRepo});await atomicService.collect({event:event({eventId:"atomic-event-0001"}),recordedAt:"2026-08-25T10:00:01Z"});const beforeFailure=await fs.readFile(atomicPath),failingFs={...fs,rename:async()=>{throw new Error("SIMULATED_RENAME_FAILURE");}},failingRepo=new FileFirstPartyProductInterestCollectionRepository({statePath:atomicPath,fileSystem:failingFs}),failingService=new FirstPartyProductInterestCollectionService({productRepository,retailerRepository,collectionRepository:failingRepo});await assert.rejects(()=>failingService.collect({event:event({eventId:"atomic-event-0002"}),recordedAt:"2026-08-25T10:00:01Z"}),/SIMULATED_RENAME_FAILURE/);assert.deepEqual(await fs.readFile(atomicPath),beforeFailure);assert.equal((await atomicRepo.getSignals()).length,1);
 for(const corrupt of ["not-json",JSON.stringify({schemaVersion:"1.0",repositoryType:"BEACON_FIRST_PARTY_PRODUCT_INTEREST",sequence:1,records:{}})]){const corruptPath=join(root,`corrupt-${createHash("sha256").update(corrupt).digest("hex").slice(0,8)}.json`);await fs.writeFile(corruptPath,corrupt);await assert.rejects(()=>new FileFirstPartyProductInterestCollectionRepository({statePath:corruptPath}).getSignals(),/DURABLE_STATE_INVALID/);}
 assert.deepEqual({products,retailers},atlasBefore);assert.deepEqual(await fs.readFile(cadenceUrl),cadenceBefore);assert.equal(createHash("sha256").update(await fs.readFile(cadenceUrl)).digest("hex"),cadenceHash);const cadence=JSON.parse(cadenceBefore);assert.equal(cadence.minimumIntervalMs,86400000);assert.equal(cadence.automaticExecution,false);const publicRenderer=await fs.readFile(new URL("../../../public/js/modules/renderRecommendation.js",import.meta.url),"utf8");assert.equal(publicRenderer.includes("/api/beacon/product-interest"),false);const status=getFirstPartyProductInterestCollectionStatus();assert.equal(status.applicationBoundary,"READY");assert.equal(status.productionTransport,"NOT_CONNECTED");assert.equal(status.persistence,"DURABLE_FILE_ADAPTER_AVAILABLE_NOT_CONFIGURED");assert.equal(status.automaticExecution,false);assert.equal(status.unattendedLive,false);assert.equal(status.actualSpendUsd,0);
}finally{await fs.rm(root,{recursive:true,force:true});}
console.log("Governed Beacon write boundary tests passed.");
