import assert from "node:assert/strict";
import {access,readFile} from "node:fs/promises";
import path from "node:path";

const root=path.resolve("."),registryPath=path.join(root,"config/operations/operator-command-registry.json"),runbookPath=path.join(root,"docs/operations/HARDWARE-RADAR-OPERATOR-RUNBOOK.md"),registry=JSON.parse(await readFile(registryPath,"utf8")),pkg=JSON.parse(await readFile(path.join(root,"package.json"),"utf8")),allowedClassifications=new Set(["ROUTINE_OPERATOR","EXCEPTION_REVIEW","PAID_OPERATOR","SCHEDULER_CONTROL","RELEASE_OPERATOR","READ_ONLY_INSPECTION","ENGINEERING_DIAGNOSTIC","TEST_DEVELOPMENT","DEPRECATED_DO_NOT_USE"]),allowedStatuses=new Set(["ACTIVE","AUTOMATED","EXCEPTION_ONLY","ENGINEERING_ONLY","DEPRECATED"]),ids=registry.commands.map(value=>value.id);
assert.equal(registry.schemaVersion,"1.0");assert.equal(new Set(ids).size,ids.length,"operator command IDs must be unique");assert.equal(registry.inventory.operatorEligibleEntries,registry.commands.length,"operator entry count drift");assert.equal(registry.inventory.packageScriptDeclarations,Object.keys(pkg.scripts).length,"package script inventory drift");
const mjs=(await import("node:fs/promises")).readdir(path.join(root,"scripts"),{withFileTypes:true}).then(values=>values.filter(value=>value.isFile()&&value.name.endsWith(".mjs")).length),ps1=(await import("node:fs/promises")).readdir(path.join(root,"scripts/windows"),{withFileTypes:true}).then(values=>values.filter(value=>value.isFile()&&value.name.endsWith(".ps1")).length);assert.equal(registry.inventory.topLevelMjsFiles,await mjs,"MJS inventory drift");assert.equal(registry.inventory.windowsPowerShellFiles,await ps1,"PowerShell inventory drift");
for(const entry of registry.commands){for(const field of ["id","system","operation","classification","status","command","authority","mutationScope","network","cost","safeReplay","failureHandling","forbiddenFollowUp","canonicalOwner","implementation","documentation"])assert.notEqual(entry[field],undefined,`${entry.id} missing ${field}`);assert(allowedClassifications.has(entry.classification),`${entry.id} classification invalid`);assert(allowedStatuses.has(entry.status),`${entry.id} status invalid`);assert.equal(entry.operatorEligible,true,`${entry.id} must be operator eligible`);if(entry.packageScript)assert(pkg.scripts[entry.packageScript],`${entry.id} package script missing`);if(entry.script)await access(path.join(root,entry.script));await access(path.join(root,entry.implementation));await access(path.join(root,entry.documentation));if(entry.confirmationToken&&entry.confirmationToken!=="implementation-defined release confirmation"&&entry.confirmationToken!=="repository command supplies governed confirmation when required"){const implementation=await readFile(path.join(root,entry.implementation),"utf8");assert(implementation.includes(entry.confirmationToken)||pkg.scripts[entry.packageScript]?.includes(entry.confirmationToken)||entry.command.includes(entry.confirmationToken),`${entry.id} confirmation drift`);}if(entry.classification==="DEPRECATED_DO_NOT_USE")assert(ids.includes(entry.replacementId),`${entry.id} replacement missing`);}
const serialized=JSON.stringify(registry).toLowerCase();for(const forbidden of ["passwordvalue","clientsecret","access_token","privatekey","dataforseo_login","dataforseo_password","rakuten_sftp_username","rakuten_sftp_password"])assert.equal(serialized.includes(forbidden),false,`credential-like material forbidden: ${forbidden}`);
const runbook=await readFile(runbookPath,"utf8");assert.match(runbook,/Any increment adding, changing, deprecating, superseding, or removing an operator-facing command must update both this runbook and the registry/);assert.match(runbook,/REVIEW DOES NOT PERSIST|Review does \*\*not\*\* persist/i);assert.match(runbook,/HardwareRadar-Mercury-ExistingTaskSupervision.*normal automated path/i);assert.match(await readFile(path.join(root,"docs/handoff/CURRENT-STATE.md"),"utf8"),/HARDWARE-RADAR-OPERATOR-RUNBOOK/);assert.match(await readFile(path.join(root,"docs/handoff/HARDWARE-RADAR-HANDOFF.md"),"utf8"),/operator-command-registry/);
console.log(`Operator command registry passed: ${registry.commands.length} operator entries; ${registry.inventory.packageScriptDeclarations} package declarations; ${registry.inventory.topLevelMjsFiles} MJS files; ${registry.inventory.windowsPowerShellFiles} PowerShell files.`);
