import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";
import { validateRamTerminalPublicIntelligence } from "../packages/mercury/historical-admission/RamTerminalPublicIntelligence.js";
import { formatHistorySpan, formatMarketDate, formatMovement, formatProductName, renderTerminalRow, sortTerminalRows } from "../public/js/modules/ramTerminal.js";

const read = path => readFile(path, "utf8");
const artifact = JSON.parse(await read("public/data/ram-terminal.json"));
const [html, script, styles, sitemap, footer] = await Promise.all([read("public/ram/terminal/index.html"), read("public/js/modules/ramTerminal.js"), read("public/css/styles.css"), read("public/sitemap.xml"), read("public/js/modules/renderFooter.js")]);
assert.equal(validateRamTerminalPublicIntelligence(artifact).valid, true);
assert.equal(artifact.lenses.ALL_RAM.coverage.productsTracked, 103);
assert.equal((html.match(/<h1>/g) ?? []).length, 1);
assert.match(html, /<h1>RAM Market Terminal<\/h1>/);
assert.match(html, /role="tablist"/);
assert.equal((html.match(/role="tab"/g) ?? []).length, 4);
assert.match(html, /role="tab" aria-selected="true" tabindex="0"/);
assert.equal(html.indexOf("RAM market pulse") < html.indexOf("Current market"), true);
assert.equal(html.indexOf("Current market") < html.indexOf("Evidence supporting this view"), true);
assert.equal(html.indexOf("Evidence supporting this view") < html.indexOf("Product intelligence"), true);
assert.match(html, /Current price coverage/);
assert.match(html, /Market data as of<br><strong>September 30, 2026<\/strong>/);
assert.match(html, /RAM historical market pulse/);
assert.match(html, /Latest comparable/);
assert.match(html, /Historical movement/);
assert.match(html, /Comparable history range/);
assert.match(html, /<table>/);
assert.match(html, /aria-sort="ascending"/);
assert.match(html, /class="terminal-sort" data-sort="current"/);
assert.match(html, /aria-live="polite"/);
assert.match(html, /Prices exclude applicable shipping, taxes, and fees/);
assert.match(html, /Lowest Hardware Radar-observed price/);
assert.doesNotMatch(html, /all-time low|lowest price ever|best time to buy|deal score|buy now/i);
assert.match(script, /renderRamTerminalLens/);
assert.doesNotMatch(script, /HistoricalObservation|createRamTerminalPublicIntelligence/i);
assert.match(styles, /\.ram-terminal-table-wrap\{overflow-x:auto/);
assert.match(styles, /\.ram-terminal-lenses button:focus-visible/);
assert.match(styles, /\.terminal-pulse-grid/);
assert.match(styles, /\.terminal-signal--insufficient/);
assert.match(styles, /@media\(max-width:600px\)/);
assert.match(sitemap, /<loc>https:\/\/cheapestram\.com\/ram\/terminal\/<\/loc>/);
assert.match(footer, /ram\/terminal\/">RAM Market Terminal/);

assert.equal(formatHistorySpan(null), "Insufficient history");
assert.equal(formatHistorySpan(0.5), "Less than 1 day");
assert.equal(formatHistorySpan(1), "1 day");
assert.equal(formatHistorySpan(1.99), "1 day");
assert.equal(formatHistorySpan(39.26), "39 days");
assert.equal(formatMarketDate("2026-09-30T23:59:59.000Z"), "September 30, 2026");
assert.deepEqual(formatMovement({ movement: "DOWN", changeFromPreviousAmount: -1.95 }), { symbol: "↓", visible: "↓ $1.95", accessible: "Latest comparable observation down $1.95 from previous comparable observation", state: "down" });
assert.deepEqual(formatMovement({ movement: "UP", changeFromPreviousAmount: 2 }), { symbol: "↑", visible: "↑ $2.00", accessible: "Latest comparable observation up $2.00 from previous comparable observation", state: "up" });
assert.equal(formatMovement({ movement: "FLAT", changeFromPreviousAmount: 0 }).visible, "— Unchanged");
assert.equal(formatProductName("Crucial", "Crucial Crucial Pro 32GB"), "Crucial Pro 32GB");
assert.equal(formatProductName("G.Skill", "G.Skill Ripjaws Ripjaws S5"), "G.Skill Ripjaws Ripjaws S5");

const fixture = (name, current, change, observations, span) => ({ brand: "Test", productName: name, current: current == null ? null : { itemPriceUsd: current, retailerCount: 1 }, history: { movement: change == null ? "INSUFFICIENT_HISTORY" : change === 0 ? "FLAT" : change < 0 ? "DOWN" : "UP", changeFromPreviousAmount: change, comparableObservationCount: observations, distinctComparableTimestampCount: observations, historySpanDays: span, previousComparableObservation: null, observedMinimumItemPrice: null, observedMaximumItemPrice: null, atObservedLow: false }, publicPath: "/ram/test/", memoryType: "DDR5", formFactor: "DIMM", capacityGb: 32, moduleCount: 2, capacityPerModuleGb: 16, dataRateMtps: 6000 });
const rows = [fixture("Zulu", null, null, 1, null), fixture("Alpha", 100, -5, 3, 8), fixture("Bravo", 80, 2, 2, 4)];
assert.deepEqual(sortTerminalRows(rows, "product", "ascending").map(row => row.productName), ["Alpha", "Bravo", "Zulu"]);
assert.deepEqual(sortTerminalRows(rows, "current", "ascending").map(row => row.productName), ["Bravo", "Alpha", "Zulu"]);
assert.deepEqual(sortTerminalRows(rows, "current", "descending").map(row => row.productName), ["Alpha", "Bravo", "Zulu"]);
assert.deepEqual(sortTerminalRows(rows, "observations", "descending").map(row => row.productName), ["Alpha", "Bravo", "Zulu"]);
const sparseRow = renderTerminalRow(rows[0]);
assert.match(sparseRow, /aria-label="No previous comparable observation">—<\/span>/);
assert.match(sparseRow, /aria-label="No latest comparable observation">—<\/span>/);
assert.match(sparseRow, /Insufficient history/);
assert.doesNotMatch(sparseRow, /Unavailable/);
console.log("RAM Market Terminal static route and public artifact contract passed.");
