import RetailerAdapter from "../adapters/interfaces/RetailerAdapter.js";
import { createProvenance } from "../Provenance.js";
export const CURATED_RAM_ADAPTER_ID = "mer_adapter_operator_curated_ram_offer", CURATED_RAM_ADAPTER_VERSION = "1.0.0";
export class CuratedRamOfferAdapter extends RetailerAdapter {
  constructor({ retailerId, retailerName, marketplace } = {}) { super(); this.manifest = Object.freeze({ adapterId: CURATED_RAM_ADAPTER_ID, version: CURATED_RAM_ADAPTER_VERSION, compatibleNormalizationVersions: [CURATED_RAM_ADAPTER_VERSION], retailerId, retailerName, marketplaces: [marketplace], sourceMethods: ["MANUAL"], capabilities: ["NORMALIZE_OFFER"], status: "ACTIVE" }); }
  getMetadata() { return this.manifest; }
  supportsMarketplace(value) { return value === this.manifest.marketplaces[0]; }
  supportsSourceMethod(value) { return String(value).toUpperCase() === "MANUAL"; }
  normalize(input, context = {}) {
    const condition = typeof input.condition === "string" && input.condition.trim() ? input.condition.trim().toUpperCase() : "UNKNOWN";
    return { observationId: context.observationId, schemaVersion: "1.1", atlasProductId: context.atlasProductId, retailerId: this.manifest.retailerId, marketplace: context.marketplace, observationTime: context.observationTime, sourceMethod: "MANUAL", lifecycleStatus: "RETRIEVED", validationStatus: "PASS", supersedesObservationId: null, expiresAt: null, offer: { price: input.listedPrice, currency: input.currency, availability: input.availability, condition, sellerType: "RETAILER", sourceUrl: input.sourceUrl, shipping: { costKnown: input.shipping.known, cost: input.shipping.known ? input.shipping.amount : null, currency: input.shipping.known ? input.shipping.currency : null, notes: null }, discount: null, affiliate: { isAffiliateLink: false, network: null, trackingCodePresent: false }, bundle: { status: input.offerClass === "BUNDLE" ? "BUNDLE" : "STANDALONE", isBundle: input.offerClass === "BUNDLE" }, conditionalPrice: { status: input.priceClass === "CONDITIONAL" ? "CONDITIONAL" : "UNCONDITIONAL", isConditional: input.priceClass === "CONDITIONAL" } }, provenance: createProvenance({ source: { name: "Operator-curated approved external RAM offer", uri: input.sourceUrl, marketplace: context.marketplace }, acquisition: { method: "MANUAL", retrievedAt: context.observationTime, retrievedBy: context.retrievedBy, requestId: context.requestId, rawPayloadReference: context.rawPayloadReference }, transformation: { adapterId: CURATED_RAM_ADAPTER_ID, adapterVersion: CURATED_RAM_ADAPTER_VERSION, normalizedAt: context.createdAt }, validation: { validatorVersion: "mercury-observation-validator-1.0.0", complianceRuleSetVersion: "mvp-002-curated-ram-1.0" } }), compliance: { licenseContext: context.licenseContext, requiredDisclosureShown: false, requiredPriceDisclaimerShown: false, retailerContentDisclaimerShown: false }, metadata: { createdAt: context.createdAt, createdBy: "mercury:curated-ram-offer", observationHash: null, notes: "Governed operator-curated RAM offer." } };
  }
}
