import crypto from "node:crypto";
import { validateObservation } from "../ObservationValidator.js";
import { RIGHTS_STATES } from "../rights/SourceRightsPolicy.js";
import { CURATED_RAM_ADAPTER_VERSION, CuratedRamOfferAdapter } from "./CuratedRamOfferAdapter.js";
export const CURATED_RAM_OFFER_POLICY_VERSION = "MVP-002-4.0", CURATED_RAM_OFFER_CONFIRMATION = "RECORD-CURATED-RAM-OFFER";
const stable = value => Array.isArray(value) ? `[${value.map(stable).join(",")}]` : value && typeof value === "object" ? `{${Object.keys(value).sort().map(key => `${JSON.stringify(key)}:${stable(value[key])}`).join(",")}}` : JSON.stringify(value), hash = value => crypto.createHash("sha256").update(stable(value)).digest("hex"), freeze = value => { if (value && typeof value === "object" && !Object.isFrozen(value)) { Object.freeze(value); for (const child of Object.values(value)) freeze(child); } return value; };
const required = (value, code) => { if (typeof value !== "string" || !value.trim()) throw new TypeError(code); return value.trim(); }, allowedConditions = new Set(["NEW", "OPEN_BOX", "MANUFACTURER_REFURBISHED", "SELLER_REFURBISHED", "USED", "UNKNOWN"]), allowedAvailability = new Set(["IN_STOCK", "LOW_STOCK", "OUT_OF_STOCK", "PREORDER", "BACKORDER", "DISCONTINUED", "UNKNOWN"]);
export const curatedRamOfferBindingDigest = value => hash(value);
export class CuratedRamOfferAssessmentService {
  constructor({ productRepository, retailerRepository, rightsRegistry, now = () => new Date().toISOString() } = {}) { if (!productRepository?.getById || !retailerRepository?.getById || !rightsRegistry?.get) throw new TypeError("CURATED_RAM_ASSESSMENT_DEPENDENCY_REQUIRED"); Object.assign(this, { productRepository, retailerRepository, rightsRegistry, now }); }
  async assess(candidate) {
    const blockers = [], normalized = structuredClone(candidate ?? {}), condition = typeof normalized.condition === "string" && normalized.condition.trim() ? normalized.condition.trim().toUpperCase() : "UNKNOWN"; normalized.condition = condition;
    for (const key of ["atlasProductId", "retailerId", "sourceRightsProfileId", "sourceUrl", "marketplace", "observedAt", "currency", "availability", "offerClass", "priceClass", "operatorSourceReference", "requestedBy"]) if (typeof normalized[key] !== "string" || !normalized[key].trim()) blockers.push(`CURATED_RAM_${key.toUpperCase()}_REQUIRED`);
    if (!Number.isFinite(Date.parse(normalized.observedAt))) blockers.push("CURATED_RAM_OBSERVED_AT_INVALID"); if (!Number.isFinite(normalized.listedPrice) || normalized.listedPrice <= 0) blockers.push("CURATED_RAM_LISTED_PRICE_INVALID"); if (!/^[A-Z]{3}$/.test(normalized.currency ?? "")) blockers.push("CURATED_RAM_CURRENCY_INVALID"); if (!allowedConditions.has(condition)) blockers.push("CURATED_RAM_CONDITION_INVALID"); if (!allowedAvailability.has(normalized.availability)) blockers.push("CURATED_RAM_AVAILABILITY_INVALID"); if (!["STANDALONE", "BUNDLE"].includes(normalized.offerClass)) blockers.push("CURATED_RAM_OFFER_CLASS_INVALID"); if (!["UNCONDITIONAL", "CONDITIONAL"].includes(normalized.priceClass)) blockers.push("CURATED_RAM_PRICE_CLASS_INVALID");
    if (!normalized.shipping || typeof normalized.shipping.known !== "boolean") blockers.push("CURATED_RAM_SHIPPING_STATE_INVALID"); else if (normalized.shipping.known && (!Number.isFinite(normalized.shipping.amount) || normalized.shipping.amount < 0 || !/^[A-Z]{3}$/.test(normalized.shipping.currency ?? ""))) blockers.push("CURATED_RAM_SHIPPING_VALUE_INVALID"); else if (!normalized.shipping.known && (normalized.shipping.amount != null || normalized.shipping.currency != null)) blockers.push("CURATED_RAM_UNKNOWN_SHIPPING_MUST_REMAIN_NULL");
    let product = null, retailer = null; try { [product, retailer] = await Promise.all([this.productRepository.getById(normalized.atlasProductId), this.retailerRepository.getById(normalized.retailerId)]); } catch { /* fail closed */ }
    if (product?.identity?.atlasProductId !== normalized.atlasProductId || product?.identity?.productType !== "ram") blockers.push("CURATED_RAM_ATLAS_PRODUCT_INVALID"); if (retailer?.id !== normalized.retailerId || retailer?.status !== "active") blockers.push("CURATED_RAM_RETAILER_INVALID"); if (!retailer?.regions?.includes("US")) blockers.push("CURATED_RAM_REGION_UNSUPPORTED"); if (!retailer?.supportedCurrencies?.includes(normalized.currency)) blockers.push("CURATED_RAM_RETAILER_CURRENCY_UNSUPPORTED");
    try { const sourceHost = new URL(normalized.sourceUrl).hostname.replace(/^www\./, ""), retailerHost = new URL(retailer?.websiteUrl).hostname.replace(/^www\./, ""); if (sourceHost !== retailerHost || normalized.marketplace !== retailerHost) blockers.push("CURATED_RAM_RETAILER_SOURCE_MISMATCH"); } catch { blockers.push("CURATED_RAM_SOURCE_URL_INVALID"); }
    const rights = this.rightsRegistry.get(normalized.sourceRightsProfileId), paths = [rights?.acquisition?.manual, rights?.live?.currentObservation, rights?.live?.comparison, rights?.live?.publicDisplay, rights?.retention?.historical, rights?.retention?.durableAuditMetadata]; if (!rights) blockers.push("CURATED_RAM_RIGHTS_PROFILE_MISSING"); else if (paths.some(value => value !== RIGHTS_STATES.ALLOWED)) blockers.push("CURATED_RAM_RIGHTS_NOT_EXPLICITLY_ALLOWED");
    const binding = blockers.length ? null : freeze({ ...normalized, shipping: structuredClone(normalized.shipping), atlasProductDigest: hash(product), retailerDigest: hash(retailer), rightsProfileDigest: hash(rights), normalizationVersion: CURATED_RAM_ADAPTER_VERSION });
    return freeze({ assessmentId: `mer_curassess_${hash({ policy: CURATED_RAM_OFFER_POLICY_VERSION, binding, blockers }).slice(0,24)}`, policyVersion: CURATED_RAM_OFFER_POLICY_VERSION, eligible: blockers.length === 0, blockers: [...new Set(blockers)], binding, bindingDigest: binding ? hash(binding) : null, networkOperation: "NONE", paidTaskCreated: false, actualSpendUsd: 0 });
  }
}
export function createCuratedRamOfferAuthorization({ assessment, preparedAt, ttlMinutes = 15 } = {}) { if (assessment?.eligible !== true || !assessment.binding) throw new Error(`CURATED_RAM_OFFER_NOT_ELIGIBLE:${assessment?.blockers?.join(",")}`); const intent = { assessmentId: assessment.assessmentId, bindingDigest: assessment.bindingDigest, requestedBy: assessment.binding.requestedBy, preparedAt, expiresAt: new Date(Date.parse(preparedAt) + ttlMinutes * 60000).toISOString() }, value = { schemaVersion: "1.0", authorizationType: "CURATED_RAM_OFFER", authorizationId: `mer_curauth_${hash(intent).slice(0,24)}`, policyVersion: CURATED_RAM_OFFER_POLICY_VERSION, ...intent, candidateBinding: structuredClone(assessment.binding), status: "PENDING_OPERATOR_APPROVAL", confirmationRequired: CURATED_RAM_OFFER_CONFIRMATION, singleUse: true, networkOperation: "NONE", paidTaskCreated: false, actualSpendUsd: 0 }; return freeze(value); }
export function validateCuratedAuthorization(value) { const valid = value?.schemaVersion === "1.0" && value?.authorizationType === "CURATED_RAM_OFFER" && value?.policyVersion === CURATED_RAM_OFFER_POLICY_VERSION && value?.status === "PENDING_OPERATOR_APPROVAL" && value?.singleUse === true && value?.bindingDigest === curatedRamOfferBindingDigest(value?.candidateBinding) && Number.isFinite(Date.parse(value?.preparedAt)) && Number.isFinite(Date.parse(value?.expiresAt)) && value?.networkOperation === "NONE" && value?.actualSpendUsd === 0; return freeze({ valid, errors: valid ? [] : ["CURATED_RAM_AUTHORIZATION_INVALID"] }); }
export function createCuratedAdapter(binding, retailer) { return new CuratedRamOfferAdapter({ retailerId: binding.retailerId, retailerName: retailer.name, marketplace: binding.marketplace }); }
export function provisionalObservation(binding, retailer, now) { return createCuratedAdapter(binding, retailer).normalize({ listedPrice: binding.listedPrice, currency: binding.currency, availability: binding.availability, condition: binding.condition, sourceUrl: binding.sourceUrl, shipping: binding.shipping, offerClass: binding.offerClass, priceClass: binding.priceClass }, { observationId: "mer_obs_000000000", atlasProductId: binding.atlasProductId, marketplace: binding.marketplace, observationTime: binding.observedAt, retrievedBy: binding.requestedBy, requestId: binding.operatorSourceReference, rawPayloadReference: binding.operatorSourceReference, licenseContext: binding.sourceRightsProfileId, createdAt: now }); }
export function assertCuratedObservationValid(value) { const report = validateObservation(value); if (!report.valid) throw new Error(`CURATED_RAM_OBSERVATION_INVALID:${report.errors.map(item => item.code).join(",")}`); }
