import { mkdir, readFile, rename, writeFile } from "node:fs/promises";
import { dirname, resolve } from "node:path";
import { FileSingleWriterRunLock, SINGLE_WRITER_LOCK_STATUSES } from "../runtime/FileSingleWriterRunLock.js";
import { validateCuratedAuthorization } from "./CuratedRamOfferGovernance.js";
const initial = () => ({ version: "1.0", authorizations: {}, byIntent: {}, consumptions: {} }), clone = structuredClone, freeze = Object.freeze, key = value => `${value.candidateBinding.operatorSourceReference}:${value.candidateBinding.atlasProductId}:${value.candidateBinding.retailerId}`;
export class FileCuratedRamOfferAuthorizationRepository {
  constructor({ statePath, now = () => new Date().toISOString(), runLock } = {}) { if (!statePath) throw new TypeError("statePath is required"); this.statePath = resolve(statePath); this.now = now; this.queue = Promise.resolve(); this.runLock = runLock ?? new FileSingleWriterRunLock({ lockPath: `${this.statePath}.lock`, now }); }
  async _locked(fn) { const run = async () => { const outcome = await this.runLock.runExclusive(fn); if (outcome.status !== SINGLE_WRITER_LOCK_STATUSES.COMPLETED) throw new Error("CURATED_RAM_AUTHORIZATION_REPOSITORY_BUSY"); return outcome.result; }, task = this.queue.then(run, run); this.queue = task.catch(() => {}); return task; }
  async _read() { try { const state = JSON.parse(await readFile(this.statePath, "utf8")); if (state?.version !== "1.0" || !state.authorizations || !state.byIntent || !state.consumptions) throw new Error(); for (const value of Object.values(state.authorizations)) if (!validateCuratedAuthorization(value).valid) throw new Error(); return state; } catch (error) { if (error?.code === "ENOENT") return initial(); throw new Error("CURATED_RAM_AUTHORIZATION_STATE_INVALID"); } }
  async _commit(state) { await mkdir(dirname(this.statePath), { recursive: true }); const temp = `${this.statePath}.tmp-${process.pid}-${Date.now()}`; await writeFile(temp, `${JSON.stringify(state, null, 2)}\n`); await rename(temp, this.statePath); }
  async record(auth) { if (!validateCuratedAuthorization(auth).valid) throw new TypeError("CURATED_RAM_AUTHORIZATION_INVALID"); return this._locked(async () => { const state = await this._read(), intent = key(auth), priorId = state.byIntent[intent]; if (priorId) { const prior = state.authorizations[priorId]; if (prior.authorizationId === auth.authorizationId) return freeze(clone(prior)); throw new Error("CURATED_RAM_AUTHORIZATION_CONFLICT"); } state.authorizations[auth.authorizationId] = clone(auth); state.byIntent[intent] = auth.authorizationId; await this._commit(state); return freeze(clone(auth)); }); }
  async getById(id) { const value = (await this._read()).authorizations[id]; return value ? freeze(clone(value)) : null; }
  async getConsumption(id) { const value = (await this._read()).consumptions[id]; return value ? freeze(clone(value)) : null; }
  async consume({ authorizationId, bindingDigest, observationId }) { return this._locked(async () => { const state = await this._read(), auth = state.authorizations[authorizationId]; if (!auth || auth.bindingDigest !== bindingDigest) throw new Error("CURATED_RAM_AUTHORIZATION_CONSUMPTION_CONFLICT"); const prior = state.consumptions[authorizationId]; if (prior) { if (prior.observationId !== observationId) throw new Error("CURATED_RAM_AUTHORIZATION_CONSUMPTION_CONFLICT"); return freeze({ status: "ALREADY_CONSUMED", consumption: clone(prior) }); } const consumption = { schemaVersion: "1.0", authorizationId, bindingDigest, observationId, consumedAt: this.now() }; state.consumptions[authorizationId] = consumption; await this._commit(state); return freeze({ status: "CONSUMED", consumption: clone(consumption) }); }); }
}
