import {mkdir,rename,rm,writeFile} from "node:fs/promises";
import {dirname,resolve} from "node:path";
import {projectIdentityReviewState} from "../identity-review/IdentityReviewProjection.js";
import {assessDataForSeoEvidencePromotion} from "../market/dataforseo/DataForSeoEvidencePromotionAssessment.js";
import {HistoricalObservationPortfolio} from "../portfolio/HistoricalObservationPortfolio.js";
import {createCertifiedMercuryOperationsProjection} from "./CertifiedMercuryOperationsProjection.js";

const required=(value,method,code)=>{if(!value||typeof value[method]!=="function")throw new TypeError(code);return value;};
const validDate=value=>typeof value==="string"&&Number.isFinite(Date.parse(value));
const snapshotRepository=records=>({getAll:async()=>structuredClone(records)});
const cadenceSnapshot=policies=>({getAllPolicies:async()=>structuredClone(policies),resolveApplicablePolicy:async atlasProductId=>{const matches=policies.filter(policy=>policy.atlasProductIds?.includes(atlasProductId));if(matches.length>1)throw new Error(`HISTORICAL_REFRESH_CADENCE_POLICY_AMBIGUOUS:${atlasProductId}`);return structuredClone(matches[0]??null);}});

export async function writeCertifiedMercuryOperationsArtifact(outputPath,projection,{fileSystem={mkdir,rename,rm,writeFile},processId=process.pid}={}){
 if(typeof outputPath!=="string"||!outputPath.trim())throw new TypeError("CERTIFIED_MERCURY_EXPORT_OUTPUT_REQUIRED");
 const target=resolve(outputPath),temporary=`${target}.tmp-${processId}`;
 try{await fileSystem.mkdir(dirname(target),{recursive:true});await fileSystem.writeFile(temporary,`${JSON.stringify(projection,null,2)}\n`,"utf8");await fileSystem.rename(temporary,target);return target;}
 catch(error){await fileSystem.rm(temporary,{force:true}).catch(()=>{});throw error;}
}

export class CertifiedMercuryOperationsExporter{
 constructor({productRepository,retailerRepository,evidenceRepository,historicalRepository,identityDecisionRepository,canonicalObservationRepository,reviewRepository,publicationRepository,cadencePolicyRepository,operationalContextProvider,artifactWriter=writeCertifiedMercuryOperationsArtifact}={}){
  this.productRepository=required(productRepository,"getAll","CERTIFIED_MERCURY_EXPORT_PRODUCT_OWNER_REQUIRED");this.retailerRepository=required(retailerRepository,"getAll","CERTIFIED_MERCURY_EXPORT_RETAILER_OWNER_REQUIRED");this.evidenceRepository=required(evidenceRepository,"getAll","CERTIFIED_MERCURY_EXPORT_EVIDENCE_OWNER_REQUIRED");this.historicalRepository=required(historicalRepository,"getAll","CERTIFIED_MERCURY_EXPORT_HISTORY_OWNER_REQUIRED");this.identityDecisionRepository=required(identityDecisionRepository,"getAll","CERTIFIED_MERCURY_EXPORT_IDENTITY_OWNER_REQUIRED");required(identityDecisionRepository,"getAllRemediations","CERTIFIED_MERCURY_EXPORT_IDENTITY_OWNER_REQUIRED");this.canonicalObservationRepository=required(canonicalObservationRepository,"getAll","CERTIFIED_MERCURY_EXPORT_OBSERVATION_OWNER_REQUIRED");this.reviewRepository=required(reviewRepository,"getEffectiveDecision","CERTIFIED_MERCURY_EXPORT_REVIEW_OWNER_REQUIRED");this.publicationRepository=required(publicationRepository,"getEffectiveDecision","CERTIFIED_MERCURY_EXPORT_PUBLICATION_OWNER_REQUIRED");this.cadencePolicyRepository=required(cadencePolicyRepository,"getAllPolicies","CERTIFIED_MERCURY_EXPORT_CADENCE_OWNER_REQUIRED");this.operationalContextProvider=required(operationalContextProvider,"load","CERTIFIED_MERCURY_EXPORT_CONTEXT_OWNER_REQUIRED");if(typeof artifactWriter!=="function")throw new TypeError("CERTIFIED_MERCURY_EXPORT_WRITER_REQUIRED");this.artifactWriter=artifactWriter;
 }
 async export({asOf,outputPath}={}){
  if(!validDate(asOf))throw new TypeError("CERTIFIED_MERCURY_EXPORT_AS_OF_REQUIRED");
  let [atlasProducts,atlasRetailers,evidenceRecords,historicalObservations,identityReviewDecisions,identityReviewRemediations,canonicalObservations,cadencePolicies]=await Promise.all([this.productRepository.getAll(),this.retailerRepository.getAll(),this.evidenceRepository.getAll(),this.historicalRepository.getAll(),this.identityDecisionRepository.getAll(),this.identityDecisionRepository.getAllRemediations(),this.canonicalObservationRepository.getAll(),this.cadencePolicyRepository.getAllPolicies()]);
  if(![atlasProducts,atlasRetailers,evidenceRecords,historicalObservations,identityReviewDecisions,identityReviewRemediations,canonicalObservations,cadencePolicies].every(Array.isArray))throw new Error("CERTIFIED_MERCURY_EXPORT_OWNER_STATE_INVALID");
  const compare=(left,right)=>left<right?-1:left>right?1:0,ordered=(values,key)=>[...values].sort((left,right)=>compare(String(key(left)??""),String(key(right)??"")));atlasProducts=ordered(atlasProducts,x=>x?.identity?.atlasProductId);atlasRetailers=ordered(atlasRetailers,x=>x?.id);evidenceRecords=ordered(evidenceRecords,x=>x?.evidenceId);historicalObservations=ordered(historicalObservations,x=>x?.observationId);identityReviewDecisions=ordered(identityReviewDecisions,x=>`${String(x?.sequence??0).padStart(12,"0")}:${x?.identityReviewDecisionId}`);identityReviewRemediations=ordered(identityReviewRemediations,x=>`${String(x?.sequence??0).padStart(12,"0")}:${x?.identityReviewRemediationId}`);canonicalObservations=ordered(canonicalObservations,x=>x?.observationId);cadencePolicies=ordered(cadencePolicies,x=>x?.policyId);
  const loadedContext=await this.operationalContextProvider.load({asOf,evidenceRecords:structuredClone(evidenceRecords)});if(!loadedContext||typeof loadedContext!=="object"||![loadedContext.refreshPlans,loadedContext.authorizations,loadedContext.executionRuns,loadedContext.refreshResults,loadedContext.identityReuseAssessments].every(Array.isArray)||!loadedContext.consumptionState||typeof loadedContext.consumptionState!=="object")throw new Error("CERTIFIED_MERCURY_EXPORT_CONTEXT_STATE_INVALID");const context=structuredClone(loadedContext);
  context.refreshPlans=ordered(context.refreshPlans,x=>x?.refreshPlanId);context.authorizations=ordered(context.authorizations,x=>x?.authorizationId??x?.requestId);context.executionRuns=ordered(context.executionRuns,x=>x?.runId);context.refreshResults=ordered(context.refreshResults,x=>x?.providerTaskId);context.identityReuseAssessments=ordered(context.identityReuseAssessments,x=>x?.targetEvidenceId);
  const identityProjections=evidenceRecords.map(record=>projectIdentityReviewState({record,decisions:identityReviewDecisions,remediations:identityReviewRemediations,atlasRetailers,identityReuseAssessments:context.identityReuseAssessments}));
  const productIds=[...new Set(atlasProducts.map(product=>product?.identity?.atlasProductId))].sort(),promotionAssessments=productIds.flatMap(atlasProductId=>{const records=evidenceRecords.filter(record=>record.candidate?.identity?.atlasProductId===atlasProductId);return records.length?[assessDataForSeoEvidencePromotion({records,identityReviewDecisions,identityReviewRemediations,atlasRetailers,identityReuseAssessments:context.identityReuseAssessments})]:[];});
  const historicalPortfolio=await new HistoricalObservationPortfolio({productRepository:snapshotRepository(atlasProducts),historicalRepository:snapshotRepository(historicalObservations),evidenceRepository:snapshotRepository(evidenceRecords),cadencePolicyRepository:cadenceSnapshot(cadencePolicies)}).query({asOf,refreshPlans:context.refreshPlans,authorizations:context.authorizations,executionRuns:context.executionRuns,consumptionState:context.consumptionState,refreshResults:context.refreshResults,promotionAssessments});
  const effectiveReviewDecisions=[],effectivePublicationDecisions=[];for(const observation of canonicalObservations){const [review,publication]=await Promise.all([this.reviewRepository.getEffectiveDecision(observation.observationId),this.publicationRepository.getEffectiveDecision(observation.observationId)]);if(review)effectiveReviewDecisions.push(review);if(publication)effectivePublicationDecisions.push(publication);}
  const projection=createCertifiedMercuryOperationsProjection({asOf,atlasProducts,evidenceRecords,identityProjections,promotionAssessments,historicalPortfolio,canonicalObservations,effectiveReviewDecisions,effectivePublicationDecisions});
  const artifactPath=await this.artifactWriter(outputPath,projection);return Object.freeze({schemaVersion:"1.0",status:"EXPORTED",artifactPath,projection,sourceStateModified:false,networkOperation:"NONE",paidTaskCreated:false,actualSpendUsd:0});
 }
}

export default CertifiedMercuryOperationsExporter;
