import crypto from "node:crypto";
import { validateProduct, validateRepository } from "../../atlas/ProductValidator.js";
import { validateBrand, validateBrandRepository } from "../../atlas/BrandValidator.js";
import { createRetailerDestination } from "../destinations/RetailerDestination.js";
const ACTIONS=new Set(["REGISTER_BRAND","CREATE_PRODUCT","EDIT_PRODUCT","ACTIVATE_PRODUCT","ADD_DESTINATION","REPLACE_DESTINATION","RETIRE_DESTINATION","ADD_AFFILIATE","REPLACE_AFFILIATE","DISABLE_AFFILIATE","VERIFY_LINK"]),hash=value=>crypto.createHash("sha256").update(JSON.stringify(value)).digest("hex"),slug=value=>String(value).trim().toLowerCase().replace(/[^a-z0-9]+/g,"-").replace(/^-|-$/g,"");
export class ForgeTrustedOperatorService{
 constructor({catalogRepository,destinationRepository,affiliateOwner,linkVerifier,auditRepository,now=()=>new Date().toISOString()}={}){if(!catalogRepository||!destinationRepository||!affiliateOwner||!linkVerifier||!auditRepository)throw new TypeError("FORGE_TRUSTED_RUNTIME_OWNERS_REQUIRED");Object.assign(this,{catalogRepository,destinationRepository,affiliateOwner,linkVerifier,auditRepository,now});}
 _auth(context,action,request){if(!context?.authenticated||!context.operatorId)throw new Error("FORGE_OPERATOR_UNAUTHORIZED");if(!ACTIONS.has(action)||(context.allowedActions&&!context.allowedActions.includes(action)))throw new Error("FORGE_OPERATOR_ACTION_FORBIDDEN");if(request?.confirmation!==`CONFIRM ${action}`)throw new Error("FORGE_OPERATOR_CONFIRMATION_REQUIRED");if(!/^[a-zA-Z0-9_-]{12,128}$/.test(request?.requestId??""))throw new Error("FORGE_OPERATOR_REQUEST_ID_INVALID");}
 async _run(context,action,request,operation){this._auth(context,action,request);const requestDigest=hash({action,requestId:request.requestId,operatorId:context.operatorId,payload:request.payload}),prior=(await this.auditRepository.getAll()).find(x=>x.requestId===request.requestId);if(prior){if(prior.requestDigest!==requestDigest)throw new Error("FORGE_OPERATOR_REPLAY_CONFLICT");return Object.freeze({status:"ALREADY_COMPLETED",auditId:prior.auditId,result:prior.result});}const result=await operation(request.payload),audit=await this.auditRepository.record({requestId:request.requestId,requestDigest,action,operatorId:context.operatorId,occurredAt:this.now(),result});return Object.freeze({status:"COMPLETED",auditId:audit.record.auditId,result});}
 async registerBrand(context,request){return this._run(context,"REGISTER_BRAND",request,async input=>{const at=this.now(),name=input.displayName?.trim(),brand=input.brandId?input:{brandId:`BRAND-${slug(name).toUpperCase()}`,schemaVersion:"1.0.0",slug:slug(name),displayName:name,legalName:(input.legalName||name).trim(),country:input.country.trim(),website:input.website.trim(),manufacturerType:"HARDWARE_MANUFACTURER",status:"ACTIVE",aliases:(input.aliases??[]).map(x=>x.trim()).filter(Boolean),supportedCategories:["CAT-RAM"],provenance:{sourceUrl:input.evidenceUrl.trim(),retrievedAt:at,verifiedBy:context.operatorId,verificationStatus:"VERIFIED"},metadata:{createdAt:at,updatedAt:at}};const report=validateBrand(brand);if(!report.valid)throw new Error(report.errors.map(x=>x.code).join(","));if(this.catalogRepository.getBrands&&!validateBrandRepository([...(await this.catalogRepository.getBrands()),brand]).valid)throw new Error("ATLAS_BRAND_DUPLICATE_NAME_OR_ALIAS");return this.catalogRepository.registerBrand(brand);});}
 async createProduct(context,request){return this._run(context,"CREATE_PRODUCT",request,async product=>{const report=validateProduct(product);if(!report.valid)throw new Error(report.errors.map(x=>x.code).join(","));const brands=this.catalogRepository.getBrands?await this.catalogRepository.getBrands():null,known=!brands||brands.some(x=>[x.displayName,...(x.aliases??[])].some(name=>name.toLowerCase()===product.identity.manufacturer.toLowerCase()));if(!known)throw new Error("ATLAS_MANUFACTURER_NOT_REGISTERED");const c=product.extension.data.capacity;if(c.capacityGb!==c.moduleCount*c.capacityPerModuleGb)throw new Error("ATLAS_CAPACITY_INVARIANT_FAILED");if(!validateRepository([...(await this.catalogRepository.getAll()),product]).valid)throw new Error("ATLAS_PRODUCT_DUPLICATE_OR_INVALID");return this.catalogRepository.createProduct(product);});}
 async editProduct(context,request){return this._run(context,"EDIT_PRODUCT",request,p=>this.catalogRepository.updateProduct(p.product,{expectedRevision:p.expectedRevision}));}
 async destination(context,request){return this._run(context,request.action,request,p=>this.destinationRepository.retain(createRetailerDestination(p)));}
 async affiliate(context,request){return this._run(context,request.action,request,p=>this.affiliateOwner.apply({...p,action:request.action,reviewedBy:context.operatorId,reviewedAt:this.now()}));}
 async affiliateInspect(context,id){if(!context?.authenticated)throw new Error("FORGE_OPERATOR_UNAUTHORIZED");const state=await this.affiliateOwner.inspect(id),history=(await this.auditRepository.getAll()).filter(x=>["ADD_AFFILIATE","REPLACE_AFFILIATE","DISABLE_AFFILIATE"].includes(x.action)&&x.result?.atlasProductId===id).map(x=>({action:x.action,occurredAt:x.occurredAt,operatorId:x.operatorId,status:x.result?.status}));return{...state,history};}
 async verifyLink(context,request){return this._run(context,"VERIFY_LINK",request,p=>this.linkVerifier.verify(p));}
}
