import crypto from "node:crypto";
import {projectIdentityReviewState} from "../identity-review/IdentityReviewProjection.js";

const freeze=value=>{if(value&&typeof value==="object"&&!Object.isFrozen(value)){Object.freeze(value);for(const child of Object.values(value))freeze(child);}return value;};const hash=value=>crypto.createHash("sha256").update(JSON.stringify(value)).digest("hex");
function identity(value){return {productId:value?.productId??null,dataDocId:value?.dataDocId??null,gid:value?.gid??null};}
export class HistoricalRefreshPrepareService{
 constructor({productRepository,retailerRepository,evidenceRepository,historicalRepository,decisionRepository}={}){for(const [name,repo,method] of [["productRepository",productRepository,"getById"],["retailerRepository",retailerRepository,"getAll"],["evidenceRepository",evidenceRepository,"getAll"],["historicalRepository",historicalRepository,"getAll"],["decisionRepository",decisionRepository,"getAll"]])if(!repo?.[method])throw new TypeError(`${name} is required.`);Object.assign(this,{productRepository,retailerRepository,evidenceRepository,historicalRepository,decisionRepository});}
 async prepare({atlasProductId,sellersAuthorization,executionRuns=[]}={}){if(typeof atlasProductId!=="string"||atlasProductId.trim()==="")throw new TypeError("atlasProductId is required.");if(sellersAuthorization?.authorizationType!=="SELLERS_ENRICHMENT"||sellersAuthorization.atlasProductId!==atlasProductId)throw new Error("GOVERNED_SELLERS_AUTHORIZATION_REQUIRED");const providerIdentity=identity(sellersAuthorization.providerIdentity);if(!providerIdentity.productId&&!providerIdentity.dataDocId&&!providerIdentity.gid)throw new Error("GOVERNED_PROVIDER_IDENTITY_REQUIRED");const execution=sellersAuthorization.plan?.decisions?.find(x=>x.decision==="APPROVED")?.execution;if(execution?.kind!=="SELLERS"||JSON.stringify(identity(execution))!==JSON.stringify(providerIdentity))throw new Error("GOVERNED_PROVIDER_IDENTITY_BINDING_INVALID");const priorRun=executionRuns.find(run=>run.planId===sellersAuthorization.planId&&run.status==="COMPLETED");const priorTask=priorRun?.tasks?.find(task=>task.outcome==="COMPLETED");if(!priorTask?.providerTaskId)throw new Error("GOVERNED_SELLERS_EXECUTION_NOT_FOUND");
  const product=await this.productRepository.getById(atlasProductId);if(product?.identity?.atlasProductId!==atlasProductId)throw new Error("ATLAS_PRODUCT_BINDING_INVALID");const retailers=await this.retailerRepository.getAll();const evidence=(await this.evidenceRepository.getAll()).filter(x=>x.candidate?.identity?.atlasProductId===atlasProductId);const history=(await this.historicalRepository.getAll()).filter(x=>x.atlasProductId===atlasProductId).sort((a,b)=>Date.parse(a.observationTime)-Date.parse(b.observationTime)||a.observationId.localeCompare(b.observationId));const latestHistory=history.at(-1);if(!latestHistory)throw new Error("HISTORICAL_REFRESH_PRIOR_OBSERVATION_REQUIRED");const priorEvidence=evidence.find(x=>x.evidenceId===latestHistory.provenance?.retainedEvidenceId);if(!priorEvidence)throw new Error("HISTORICAL_REFRESH_PRIOR_EVIDENCE_MISSING");if(priorEvidence.candidate.marketEvidence.provenance.sourceTaskId!==priorTask.providerTaskId)throw new Error("HISTORICAL_REFRESH_PRIOR_TASK_BINDING_INVALID");const priorProvider=identity(priorEvidence.candidate.marketEvidence.productEvidence);if(JSON.stringify(priorProvider)!==JSON.stringify(providerIdentity))throw new Error("HISTORICAL_REFRESH_PROVIDER_IDENTITY_DRIFT");const decisions=await this.decisionRepository.getAll();const remediations=await this.decisionRepository.getAllRemediations();const projection=projectIdentityReviewState({record:priorEvidence,decisions,remediations,atlasRetailers:retailers});if(projection.product.state!=="VERIFIED"||projection.merchant.state!=="REGISTERED")throw new Error("HISTORICAL_REFRESH_GOVERNED_IDENTITY_REQUIRED");const binding={atlasProductId,providerIdentity,previousObservationId:latestHistory.observationId,previousEvidenceId:priorEvidence.evidenceId,previousProviderTaskId:priorTask.providerTaskId,productDecisionId:projection.product.decisionId,merchantDecisionId:projection.merchant.decisionId};return freeze({schemaVersion:"1.0",refreshPlanId:`histrefresh_${hash(binding).slice(0,24)}`,operation:"SELLERS",status:"PENDING_OPERATOR_REVIEW",atlasProductId,providerIdentity,existingIdentity:{productState:"VERIFIED",productDecisionId:projection.product.decisionId,merchantState:"REGISTERED",merchantDecisionId:projection.merchant.decisionId,retailerId:projection.merchant.merchantId},minimumSafePath:{productsRequired:false,productInfoPaidTaskRequired:false,governedProductInfoProvenanceReused:true,sellersPaidTaskRequired:true,directSellersEligible:true},previous:{observationId:latestHistory.observationId,observationTime:latestHistory.observationTime,evidenceId:priorEvidence.evidenceId,providerTaskId:priorTask.providerTaskId},spendPolicy:{maxPaidTasks:1,maxSpendUsd:0.001,maxSpendPerDayUsd:0.01,automaticPaidRetries:0,singleUseAuthorizationRequired:true,newAuthorizationRequired:true},paidTaskCreated:false,actualSpendUsd:0,historicalAdmissionPerformed:false,canonicalPromotionAuthorized:false,publicationAuthorized:false});
 }
}
export default HistoricalRefreshPrepareService;
