export const HISTORICAL_REFRESH_DUE_STATES=Object.freeze({POLICY_NOT_CONFIGURED:"POLICY_NOT_CONFIGURED",DISABLED:"DISABLED",NOT_DUE:"NOT_DUE",DUE:"DUE",BLOCKED:"BLOCKED"});
const freeze=value=>{if(value&&typeof value==="object"&&!Object.isFrozen(value)){Object.freeze(value);for(const child of Object.values(value))freeze(child);}return value;};const nonBlank=value=>typeof value==="string"&&value.trim()!=="";const validDate=value=>nonBlank(value)&&Number.isFinite(Date.parse(value));

export function createHistoricalRefreshCadencePolicy({policyId,enabled=false,minimumIntervalMs=null,atlasProductIds=[],retailerIds=null,rationale=null,metadata=null}={}){
 if(!nonBlank(policyId)||typeof enabled!=="boolean"||!Array.isArray(atlasProductIds)||atlasProductIds.some(x=>!nonBlank(x))||new Set(atlasProductIds).size!==atlasProductIds.length)throw new TypeError("HISTORICAL_REFRESH_CADENCE_POLICY_INVALID");
 if(enabled&&(!Number.isSafeInteger(minimumIntervalMs)||minimumIntervalMs<=0))throw new TypeError("HISTORICAL_REFRESH_CADENCE_INTERVAL_REQUIRED");if(!enabled&&minimumIntervalMs!==null&&(!Number.isSafeInteger(minimumIntervalMs)||minimumIntervalMs<=0))throw new TypeError("HISTORICAL_REFRESH_CADENCE_INTERVAL_INVALID");
 if(retailerIds!==null&&(!Array.isArray(retailerIds)||retailerIds.some(x=>!/^RETAILER-[0-9]{4}$/.test(x))||new Set(retailerIds).size!==retailerIds.length))throw new TypeError("HISTORICAL_REFRESH_CADENCE_RETAILER_SCOPE_INVALID");
 return freeze({schemaVersion:"1.0",policyType:"HISTORICAL_REFRESH_CADENCE",policyId:policyId.trim(),enabled,minimumIntervalMs,atlasProductIds:[...atlasProductIds],retailerIds:retailerIds===null?null:[...retailerIds],rationale:rationale??null,metadata:metadata==null?null:structuredClone(metadata),automaticExecution:false});
}

function result({atlasProductId,policy=null,cycleStatus,asOf,dueState,due,reasons,elapsed=null,nextEligible=null}){return freeze({schemaVersion:"1.0",evaluationType:"HISTORICAL_REFRESH_CADENCE_STATUS",atlasProductId,policyId:policy?.policyId??null,policyState:policy==null?"NOT_CONFIGURED":policy.enabled?"ENABLED":"DISABLED",latestObservationId:cycleStatus?.latestHistoricalObservation?.observationId??null,latestObservationTime:cycleStatus?.latestHistoricalObservation?.observationTime??null,asOf,elapsedSinceObservationMs:elapsed,nextEligibleRefreshTime:nextEligible,dueState,due,e2nCycleStage:cycleStatus?.stage??null,e2nNextAction:cycleStatus?.nextAction?.name??null,potentialFutureTask:cycleStatus?.nextAction?.potentialPaidOperation??"SELLERS",maximumFutureSpendUsd:cycleStatus?.nextAction?.maximumFutureSpendUsd??.001,automaticExecution:false,unattendedLive:false,paidActionExecuted:false,paidTaskCreated:false,actualSpendUsd:0,reasons});}

export function evaluateHistoricalRefreshCadence({atlasProductId,cycleStatus,policy=null,asOf,historicalIntelligence=null}={}){
 if(!nonBlank(atlasProductId)||!cycleStatus||cycleStatus.atlasProductId!==atlasProductId||!validDate(asOf))throw new TypeError("HISTORICAL_REFRESH_CADENCE_INPUT_INVALID");
 if(policy==null)return result({atlasProductId,cycleStatus,asOf,dueState:"POLICY_NOT_CONFIGURED",due:null,reasons:["REFRESH_POLICY_NOT_CONFIGURED"]});
 if(policy.schemaVersion!=="1.0"||policy.policyType!=="HISTORICAL_REFRESH_CADENCE"||!nonBlank(policy.policyId)||policy.automaticExecution!==false)return result({atlasProductId,policy,cycleStatus,asOf,dueState:"BLOCKED",due:false,reasons:["REFRESH_POLICY_INVALID"]});
 if(!policy.atlasProductIds.includes(atlasProductId))return result({atlasProductId,policy,cycleStatus,asOf,dueState:"BLOCKED",due:false,reasons:["REFRESH_POLICY_PRODUCT_SCOPE_MISMATCH"]});
 const retailerId=cycleStatus.latestHistoricalObservation?.retailerId??null;if(policy.retailerIds!==null&&!policy.retailerIds.includes(retailerId))return result({atlasProductId,policy,cycleStatus,asOf,dueState:"BLOCKED",due:false,reasons:["REFRESH_POLICY_RETAILER_SCOPE_MISMATCH"]});
 if(!policy.enabled)return result({atlasProductId,policy,cycleStatus,asOf,dueState:"DISABLED",due:false,reasons:["REFRESH_POLICY_DISABLED"]});
 if(!Number.isSafeInteger(policy.minimumIntervalMs)||policy.minimumIntervalMs<=0)return result({atlasProductId,policy,cycleStatus,asOf,dueState:"BLOCKED",due:false,reasons:["REFRESH_POLICY_INTERVAL_INVALID"]});
 const terminal=new Set(["COMPLETE","READY_FOR_PREPARE","NO_SELLER_OBSERVATIONS"]);if(!terminal.has(cycleStatus.stage)){const map={REVIEW_REQUIRED:"IDENTITY_REVIEW_REQUIRED",BLOCKED:"CYCLE_BLOCKED",PAID_EXECUTION_FAILED:"PAID_EXECUTION_FAILED",AWAITING_RESULT_RETRIEVAL:"PREVIOUS_CYCLE_INCOMPLETE",HISTORICAL_ELIGIBLE:"PREVIOUS_CYCLE_INCOMPLETE",HISTORICAL_ADMITTED:"PREVIOUS_CYCLE_INCOMPLETE"};return result({atlasProductId,policy,cycleStatus,asOf,dueState:"BLOCKED",due:false,reasons:[map[cycleStatus.stage]??"PREVIOUS_CYCLE_INCOMPLETE"]});}
 const observationTime=cycleStatus.latestHistoricalObservation?.observationTime;if(!validDate(observationTime))return result({atlasProductId,policy,cycleStatus,asOf,dueState:"BLOCKED",due:false,reasons:["LATEST_OBSERVATION_TIME_INVALID"]});const observed=Date.parse(observationTime),evaluated=Date.parse(asOf),elapsed=evaluated-observed,nextEligibleMs=observed+policy.minimumIntervalMs,nextEligible=new Date(nextEligibleMs).toISOString();if(elapsed<0)return result({atlasProductId,policy,cycleStatus,asOf,dueState:"BLOCKED",due:false,reasons:["CADENCE_AS_OF_PRECEDES_OBSERVATION"],elapsed,nextEligible});
 const due=elapsed>=policy.minimumIntervalMs;return result({atlasProductId,policy,cycleStatus,asOf,dueState:due?"DUE":"NOT_DUE",due,reasons:[due?"REFRESH_INTERVAL_ELAPSED":"REFRESH_INTERVAL_NOT_ELAPSED"],elapsed,nextEligible});
}

export class HistoricalRefreshCadencePolicyService{evaluate(input){return evaluateHistoricalRefreshCadence(input);}}
export default HistoricalRefreshCadencePolicyService;
