import {readFile} from "node:fs/promises";
import {fileURLToPath} from "node:url";
import {createHistoricalRefreshCadencePolicy} from "./HistoricalRefreshCadencePolicy.js";

const defaultReadJson=async resource=>JSON.parse(await readFile(resource instanceof URL?fileURLToPath(resource):resource,"utf8"));
const freeze=value=>{if(value&&typeof value==="object"&&!Object.isFrozen(value)){Object.freeze(value);for(const child of Object.values(value))freeze(child);}return value;};
const nonBlank=value=>typeof value==="string"&&value.trim()!=="";
export const INITIAL_PRODUCTION_HISTORICAL_REFRESH_CADENCE_POLICY_URL=new URL("./policies/initial-production-policy.json",import.meta.url);

export class HistoricalRefreshCadencePolicyRepository{
 constructor({policyUrl,policyUrls,readJson=defaultReadJson,atlasProductRepository=null}={}){if(policyUrl!==undefined&&policyUrls!==undefined)throw new TypeError("HISTORICAL_REFRESH_CADENCE_POLICY_LOCATIONS_AMBIGUOUS");const locations=policyUrls??(policyUrl!==undefined?[policyUrl]:[INITIAL_PRODUCTION_HISTORICAL_REFRESH_CADENCE_POLICY_URL]);if(!Array.isArray(locations)||locations.some(x=>!(x instanceof URL)&&typeof x!=="string"))throw new TypeError("HISTORICAL_REFRESH_CADENCE_POLICY_LOCATION_REQUIRED");if(typeof readJson!=="function")throw new TypeError("HISTORICAL_REFRESH_CADENCE_POLICY_READER_REQUIRED");if(atlasProductRepository!==null&&!atlasProductRepository?.getAll)throw new TypeError("HISTORICAL_REFRESH_CADENCE_ATLAS_REPOSITORY_INVALID");this.policyUrls=Object.freeze([...locations]);this.readJson=readJson;this.atlasProductRepository=atlasProductRepository;this.policiesPromise=null;}
 async #load(location){const raw=await this.readJson(location);if(raw?.schemaVersion!=="1.0"||raw?.policyType!=="HISTORICAL_REFRESH_CADENCE"||raw?.automaticExecution!==false)throw new Error("HISTORICAL_REFRESH_CADENCE_POLICY_STATE_INVALID");const policy=createHistoricalRefreshCadencePolicy(raw);if(JSON.stringify(policy)!==JSON.stringify(raw))throw new Error("HISTORICAL_REFRESH_CADENCE_POLICY_STATE_INVALID");return policy;}
 async getAllPolicies(){this.policiesPromise??=(async()=>{const policies=await Promise.all(this.policyUrls.map(x=>this.#load(x))),ids=policies.map(x=>x.policyId);if(new Set(ids).size!==ids.length)throw new Error("HISTORICAL_REFRESH_CADENCE_POLICY_ID_DUPLICATE");const ordered=[...policies].sort((a,b)=>a.policyId.localeCompare(b.policyId));if(this.atlasProductRepository){const products=await this.atlasProductRepository.getAll(),known=new Set(products.map(x=>x?.identity?.atlasProductId));if(ordered.some(policy=>policy.atlasProductIds.some(id=>!known.has(id))))throw new Error("HISTORICAL_REFRESH_CADENCE_POLICY_ATLAS_PRODUCT_UNKNOWN");}return freeze(ordered);})();return this.policiesPromise;}
 async getPolicy(policyId=null){const policies=await this.getAllPolicies();if(policyId===null){if(policies.length!==1)throw new Error("HISTORICAL_REFRESH_CADENCE_POLICY_SINGLE_REQUIRED");return policies[0];}if(!nonBlank(policyId))throw new TypeError("HISTORICAL_REFRESH_CADENCE_POLICY_ID_REQUIRED");return policies.find(x=>x.policyId===policyId)??null;}
 async resolveApplicablePolicy(atlasProductId){if(!nonBlank(atlasProductId))throw new TypeError("HISTORICAL_REFRESH_CADENCE_ATLAS_PRODUCT_REQUIRED");const matches=(await this.getAllPolicies()).filter(x=>x.atlasProductIds.includes(atlasProductId));if(matches.length>1)throw new Error(`HISTORICAL_REFRESH_CADENCE_POLICY_AMBIGUOUS:${atlasProductId}`);return matches[0]??null;}
 async getInventory(){const policies=await this.getAllPolicies(),assignments=new Map();for(const policy of policies)for(const id of policy.atlasProductIds)assignments.set(id,[...(assignments.get(id)??[]),policy.policyId]);const ambiguousProducts=[...assignments].filter(([,ids])=>ids.length>1).map(([id])=>id).sort();return freeze({schemaVersion:"1.0",inventoryType:"HISTORICAL_REFRESH_CADENCE_POLICY_INVENTORY",policyCount:policies.length,enabledCount:policies.filter(x=>x.enabled).length,disabledCount:policies.filter(x=>!x.enabled).length,explicitProductScopeCount:assignments.size,ambiguousProducts,automaticExecutionCount:policies.filter(x=>x.automaticExecution).length,policies});}
}
export default HistoricalRefreshCadencePolicyRepository;
