import crypto from "node:crypto";

export const HISTORICAL_REFRESH_CYCLE_STAGES=Object.freeze({READY_FOR_PREPARE:"READY_FOR_PREPARE",PLAN_PREPARED:"PLAN_PREPARED",AUTHORIZATION_PREPARED:"AUTHORIZATION_PREPARED",AWAITING_PAID_EXECUTION:"AWAITING_PAID_EXECUTION",PAID_EXECUTION_FAILED:"PAID_EXECUTION_FAILED",AWAITING_RESULT_RETRIEVAL:"AWAITING_RESULT_RETRIEVAL",RESULT_RETRIEVED:"RESULT_RETRIEVED",AWAITING_PROMOTION_ASSESSMENT:"AWAITING_PROMOTION_ASSESSMENT",HISTORICAL_ELIGIBLE:"HISTORICAL_ELIGIBLE",REVIEW_REQUIRED:"REVIEW_REQUIRED",BLOCKED:"BLOCKED",NO_SELLER_OBSERVATIONS:"NO_SELLER_OBSERVATIONS",HISTORICAL_ADMITTED:"HISTORICAL_ADMITTED",COMPLETE:"COMPLETE"});
export const HISTORICAL_REFRESH_NEXT_ACTIONS=Object.freeze({PREPARE_NEW_REFRESH:"PREPARE_NEW_REFRESH",PREPARE_AUTHORIZATION:"PREPARE_AUTHORIZATION",PREPARE_NEW_AUTHORIZATION:"PREPARE_NEW_AUTHORIZATION",EXECUTE_AUTHORIZED_SELLERS:"EXECUTE_AUTHORIZED_SELLERS",RETRIEVE_RESULT:"RETRIEVE_RESULT",RETAIN_EVIDENCE:"RETAIN_EVIDENCE",ASSESS_PROMOTION:"ASSESS_PROMOTION",ADMIT_HISTORICAL_EVIDENCE:"ADMIT_HISTORICAL_EVIDENCE",OPERATOR_REVIEW_REQUIRED:"OPERATOR_REVIEW_REQUIRED",AWAIT_RECURRENCE_POLICY:"AWAIT_RECURRENCE_POLICY",NONE:"NONE"});
const freeze=value=>{if(value&&typeof value==="object"&&!Object.isFrozen(value)){Object.freeze(value);for(const child of Object.values(value))freeze(child);}return value;};const validDate=value=>typeof value==="string"&&Number.isFinite(Date.parse(value));const provider=value=>({productId:value?.productId??null,dataDocId:value?.dataDocId??null,gid:value?.gid??null});const same=(a,b)=>JSON.stringify(a)===JSON.stringify(b);const cycleId=value=>`histcycle_${crypto.createHash("sha256").update(value).digest("hex").slice(0,24)}`;
function action(name,{paid=false,authorization=false,humanReview=false}={}){return {name,zeroSpend:!paid,paid,requiresExplicitSpendAuthorization:authorization,humanReviewRequired:humanReview,potentialPaidOperation:"SELLERS",maximumFutureSpendUsd:.001,executesAction:false,paidTaskCreated:false,actualSpendUsd:0};}
function latestHistory(records,atlasProductId){return records.filter(x=>x?.atlasProductId===atlasProductId&&validDate(x.observationTime)).sort((a,b)=>Date.parse(a.observationTime)-Date.parse(b.observationTime)||String(a.observationId).localeCompare(String(b.observationId))).at(-1)??null;}
function event(stage,artifactType,artifactId,occurredAt=null,details={}){return {stage,artifactType,artifactId,occurredAt:validDate(occurredAt)?occurredAt:null,...details};}
function blocked(base,reasons){return freeze({...base,stage:HISTORICAL_REFRESH_CYCLE_STAGES.BLOCKED,status:"BLOCKED",nextAction:action(HISTORICAL_REFRESH_NEXT_ACTIONS.OPERATOR_REVIEW_REQUIRED,{humanReview:true}),blockingReasons:reasons});}

export function assessHistoricalRefreshCycleStatus(input={}){
 const atlasProductId=input.atlasProductId;if(typeof atlasProductId!=="string"||!atlasProductId||!Array.isArray(input.historicalObservations)||!Array.isArray(input.evidenceRecords)||!Array.isArray(input.refreshPlans)||!Array.isArray(input.authorizations)||!Array.isArray(input.executionRuns)||!Array.isArray(input.refreshResults))throw new TypeError("HISTORICAL_REFRESH_CYCLE_INPUT_INVALID");if(input.asOf!=null&&!validDate(input.asOf))throw new TypeError("HISTORICAL_REFRESH_CYCLE_AS_OF_INVALID");
 const history=input.historicalObservations,latest=latestHistory(history,atlasProductId),elapsed=latest&&input.asOf!=null?Date.parse(input.asOf)-Date.parse(latest.observationTime):null;const base={schemaVersion:"1.0",modelType:"HISTORICAL_REFRESH_CYCLE_STATUS",atlasProductId,asOf:input.asOf??null,recurrence:{policyDefined:false,canPrepareFutureRefresh:Boolean(latest),latestObservationTime:latest?.observationTime??null,elapsedSinceLatestObservationMs:elapsed,observationCount:history.filter(x=>x?.atlasProductId===atlasProductId).length,automaticCadence:null,freshnessThreshold:null,currentPriceSemantics:false},latestHistoricalObservation:latest?{observationId:latest.observationId,observationTime:latest.observationTime,retailerId:latest.retailerId,basePrice:latest.market?.basePrice??null,totalPrice:latest.market?.totalPrice??null,retainedEvidenceId:latest.provenance?.retainedEvidenceId??null,providerTaskId:latest.provenance?.acquisition?.sellersTaskId??null}:null,unattendedLive:"DISABLED",paidTaskCreated:false,actualSpendUsd:0,blockingReasons:[],events:[]};
 const plans=input.refreshPlans.filter(x=>x?.atlasProductId===atlasProductId);if(plans.length===0)return freeze({...base,refreshCycleId:cycleId(`${atlasProductId}|${latest?.observationId??"none"}|READY`),stage:"READY_FOR_PREPARE",status:"READY",cycle:null,nextAction:action("PREPARE_NEW_REFRESH")});
 const plan=plans.at(-1),planProvider=provider(plan?.providerIdentity);if(plan?.schemaVersion!=="1.0"||plan.operation!=="SELLERS"||!plan.refreshPlanId||!plan.previous?.evidenceId||!plan.previous?.observationId||!plan.previous?.providerTaskId||![planProvider.productId,planProvider.dataDocId,planProvider.gid].some(x=>typeof x==="string"&&x))return blocked({...base,refreshCycleId:cycleId(String(plan?.refreshPlanId??"invalid")),cycle:null},["REFRESH_PLAN_INVALID"]);
 const cycle={refreshPlanId:plan.refreshPlanId,atlasProductId,retailerId:plan.existingIdentity?.retailerId??null,providerIdentity:provider(plan.providerIdentity),previousHistoricalObservationId:plan.previous.observationId,previousRetainedEvidenceId:plan.previous.evidenceId,previousProviderTaskId:plan.previous.providerTaskId,authorizationId:null,providerTaskId:null,retainedEvidenceIds:[],reuseAssessmentIds:[],promotionAssessmentState:null,admittedHistoricalObservationIds:[]};const events=[event("PLAN_PREPARED","REFRESH_PLAN",plan.refreshPlanId,plan.createdAt??plan.preparedAt??null)];const common={...base,refreshCycleId:cycleId(plan.refreshPlanId),cycle,events};
 const auths=input.authorizations.filter(x=>x?.refreshPlanId===plan.refreshPlanId);if(auths.length>1)return blocked(common,["CONFLICTING_REFRESH_AUTHORIZATIONS"]);const authorization=auths[0]??null;if(!authorization)return freeze({...common,stage:"PLAN_PREPARED",status:"AWAITING_OPERATOR_ACTION",nextAction:action("PREPARE_AUTHORIZATION",{humanReview:true})});if(authorization.authorizationType!=="HISTORICAL_REFRESH_SELLERS"||authorization.atlasProductId!==atlasProductId||authorization.planId!==authorization.plan?.planId||authorization.retailerId!==cycle.retailerId||!same(provider(authorization.providerIdentity),cycle.providerIdentity))return blocked(common,["REFRESH_AUTHORIZATION_BINDING_INVALID"]);cycle.authorizationId=authorization.requestId;events.push(event("AUTHORIZATION_PREPARED","AUTHORIZATION",authorization.requestId,authorization.createdAt,{expiresAt:authorization.expiresAt}));
 const consumed=(input.consumptionState?.consumed??[]).filter(x=>x.authorizationId===authorization.requestId);if(consumed.length>1)return blocked(common,["AUTHORIZATION_CONSUMPTION_CONFLICT"]);const runs=input.executionRuns.filter(x=>x?.planId===authorization.planId);if(runs.length>1)return blocked(common,["CONFLICTING_REFRESH_EXECUTIONS"]);const run=runs[0]??null;const expired=input.asOf!=null&&validDate(authorization.expiresAt)&&Date.parse(input.asOf)>=Date.parse(authorization.expiresAt);if(!run){if(consumed.length)return blocked(common,["AUTHORIZATION_CONSUMED_WITHOUT_EXECUTION"]);if(expired)return freeze({...common,stage:"AUTHORIZATION_PREPARED",status:"AUTHORIZATION_EXPIRED",authorizationState:"EXPIRED",nextAction:action("PREPARE_NEW_AUTHORIZATION",{humanReview:true})});return freeze({...common,stage:"AWAITING_PAID_EXECUTION",status:"AWAITING_OPERATOR_AUTHORIZATION",authorizationState:input.asOf==null?"EXPIRY_NOT_EVALUATED":"AVAILABLE",nextAction:action("EXECUTE_AUTHORIZED_SELLERS",{paid:true,authorization:true,humanReview:true})});}
 if(consumed.length!==1||consumed[0].planId!==authorization.planId)return blocked(common,["EXECUTION_WITHOUT_SINGLE_USE_CONSUMPTION"]);events.push(event(run.status==="COMPLETED"?"PAID_TASK_COMPLETED":"PAID_EXECUTION_FAILED","EXECUTION_RUN",run.runId,run.finishedAt,{status:run.status}));if(run.status!=="COMPLETED"){return freeze({...common,stage:"PAID_EXECUTION_FAILED",status:"BLOCKED",authorizationState:"CONSUMED",nextAction:action("OPERATOR_REVIEW_REQUIRED",{humanReview:true}),blockingReasons:["PAID_EXECUTION_FAILED_NO_AUTOMATIC_RETRY"]});}const tasks=(run.tasks??[]).filter(x=>x.outcome==="COMPLETED");if(tasks.length!==1||!tasks[0].providerTaskId)return blocked(common,["COMPLETED_PROVIDER_TASK_INVALID"]);cycle.providerTaskId=tasks[0].providerTaskId;events.push(event("PAID_TASK_COMPLETED","PROVIDER_TASK",cycle.providerTaskId,run.finishedAt));
 const taskCollision=input.refreshResults.filter(x=>x?.providerTaskId===cycle.providerTaskId&&x.refreshPlanId!==plan.refreshPlanId);if(taskCollision.length)return blocked(common,["PROVIDER_TASK_REUSED_ACROSS_CYCLES"]);const results=input.refreshResults.filter(x=>x?.refreshPlanId===plan.refreshPlanId);if(results.length>1)return blocked(common,["CONFLICTING_REFRESH_RESULTS"]);const result=results[0]??null;if(!result)return freeze({...common,stage:"AWAITING_RESULT_RETRIEVAL",status:"AWAITING_OPERATOR_ACTION",authorizationState:"CONSUMED",nextAction:action("RETRIEVE_RESULT")});if(result.authorizationId!==authorization.requestId||result.providerTaskId!==cycle.providerTaskId||result.retrievalStatus!=="COMPLETED")return blocked(common,["REFRESH_RESULT_BINDING_INVALID"]);events.push(event("RESULT_RETRIEVED","REFRESH_RESULT",`${result.refreshPlanId}:${result.providerTaskId}`,result.retrievedAt??run.finishedAt));if(result.acquisitionOutcome==="NO_SELLER_OBSERVATIONS"){if((result.evidence??[]).length||result.retained!==0)return blocked(common,["NO_SELLER_OBSERVATIONS_CONTRADICTION"]);return freeze({...common,stage:"NO_SELLER_OBSERVATIONS",status:"COMPLETE_WITHOUT_OBSERVATION",authorizationState:"CONSUMED",nextAction:action("AWAIT_RECURRENCE_POLICY")});}
 const evidenceIds=(result.evidence??[]).map(x=>x.evidenceId).filter(Boolean);cycle.retainedEvidenceIds=evidenceIds;if(evidenceIds.length===0)return freeze({...common,stage:"RESULT_RETRIEVED",status:"AWAITING_OPERATOR_ACTION",authorizationState:"CONSUMED",nextAction:action("RETAIN_EVIDENCE")});const retained=evidenceIds.map(id=>input.evidenceRecords.find(x=>x.evidenceId===id));if(retained.some(x=>!x))return blocked(common,["RETAINED_EVIDENCE_REFERENCE_MISSING"]);events.push(...retained.map(x=>event("EVIDENCE_RETAINED","RETAINED_EVIDENCE",x.evidenceId,x.retainedAt)));
 const reuse=result.identityReuse??[];if(reuse.some(x=>x.status==="BLOCKED"))return freeze({...common,stage:"BLOCKED",status:"BLOCKED",authorizationState:"CONSUMED",nextAction:action("OPERATOR_REVIEW_REQUIRED",{humanReview:true}),blockingReasons:["IDENTITY_REUSE_BLOCKED"]});if(reuse.some(x=>x.status==="REVIEW_REQUIRED")||reuse.length===0)return freeze({...common,stage:"REVIEW_REQUIRED",status:"REVIEW_REQUIRED",authorizationState:"CONSUMED",nextAction:action("OPERATOR_REVIEW_REQUIRED",{humanReview:true}),blockingReasons:[reuse.length?"IDENTITY_REUSE_REVIEW_REQUIRED":"IDENTITY_REUSE_MISSING"]});if(reuse.some(x=>x.status!=="APPLICABLE"||!x.reuseAssessmentId))return blocked(common,["IDENTITY_REUSE_INVALID"]);cycle.reuseAssessmentIds=reuse.map(x=>x.reuseAssessmentId);events.push(...reuse.map(x=>event("IDENTITY_REUSE_APPLIED","IDENTITY_REUSE",x.reuseAssessmentId,x.assessedAt)));
 const admitted=history.filter(x=>evidenceIds.includes(x.provenance?.retainedEvidenceId));if(admitted.length){for(const observation of admitted){if(observation.provenance?.acquisition?.refreshPlanId!==plan.refreshPlanId||observation.provenance?.acquisition?.sellersTaskId!==cycle.providerTaskId)return blocked(common,["HISTORICAL_ADMISSION_BINDING_INVALID"]);}cycle.admittedHistoricalObservationIds=admitted.map(x=>x.observationId);cycle.promotionAssessmentState="HISTORICAL_ELIGIBLE";events.push(...admitted.map(x=>event("HISTORICAL_ADMITTED","HISTORICAL_OBSERVATION",x.observationId,x.admittedAt)));return freeze({...common,stage:"COMPLETE",status:"COMPLETE",authorizationState:"CONSUMED",nextAction:action("PREPARE_NEW_REFRESH")});}
 const promotion=(input.promotionAssessments??[]).find(x=>x.refreshPlanId===plan.refreshPlanId||evidenceIds.every(id=>x.evidenceIds?.includes(id)))??null;if(!promotion)return freeze({...common,stage:"AWAITING_PROMOTION_ASSESSMENT",status:"AWAITING_OPERATOR_ACTION",authorizationState:"CONSUMED",nextAction:action("ASSESS_PROMOTION")});cycle.promotionAssessmentState=promotion.state;if(promotion.state==="HISTORICAL_ELIGIBLE"&&promotion.historicalEligible===true&&promotion.canonicalEligible===false&&promotion.publicationEligible===false){events.push(event("HISTORICAL_ELIGIBLE","PROMOTION_ASSESSMENT",promotion.assessmentId??plan.refreshPlanId,promotion.assessedAt));return freeze({...common,stage:"HISTORICAL_ELIGIBLE",status:"AWAITING_OPERATOR_ACTION",authorizationState:"CONSUMED",nextAction:action("ADMIT_HISTORICAL_EVIDENCE",{humanReview:true})});}if(promotion.state==="BLOCKED")return blocked(common,["PROMOTION_ASSESSMENT_BLOCKED"]);return freeze({...common,stage:"REVIEW_REQUIRED",status:"REVIEW_REQUIRED",authorizationState:"CONSUMED",nextAction:action("OPERATOR_REVIEW_REQUIRED",{humanReview:true}),blockingReasons:["PROMOTION_NOT_HISTORICAL_ELIGIBLE"]});
}

export class HistoricalRefreshCycleStatusService{assess(input){return assessHistoricalRefreshCycleStatus(input);}}
export default HistoricalRefreshCycleStatusService;
