import {resolveDataForSeoMerchantIdentity} from "../market/dataforseo/DataForSeoMerchantIdentity.js";

function freeze(value){if(value&&typeof value==="object"&&!Object.isFrozen(value)){Object.freeze(value);for(const child of Object.values(value))freeze(child);}return value;}
function providerIdentity(record){const product=record?.candidate?.marketEvidence?.productEvidence??{};return {productId:product.productId??null,dataDocId:product.dataDocId??null,gid:product.gid??null};}
function compatibleProviderIdentity(left,right){return ["productId","dataDocId","gid"].some(key=>left[key]!=null&&left[key]===right[key]);}
export function validateHistoricalRefreshIdentityReuse(value){const errors=[];if(!value||value.schemaVersion!=="1.0"||value.assessmentType!=="HISTORICAL_REFRESH_IDENTITY_REUSE")errors.push("IDENTITY_REUSE_SCHEMA_INVALID");if(typeof value?.sourceEvidenceId!=="string"||typeof value?.targetEvidenceId!=="string"||value.sourceEvidenceId===value.targetEvidenceId)errors.push("IDENTITY_REUSE_EVIDENCE_BINDING_INVALID");if(!["APPLICABLE","REVIEW_REQUIRED","BLOCKED"].includes(value?.status))errors.push("IDENTITY_REUSE_STATUS_INVALID");if(value?.status==="APPLICABLE"&&(value.product?.state!=="VERIFIED"||!value.product.decisionId))errors.push("IDENTITY_REUSE_PRODUCT_INVALID");if(value?.merchant?.state==="REGISTERED"&&(!value.merchant.decisionId||!/^RETAILER-[0-9]{4}$/.test(value.merchant.retailerId??"")))errors.push("IDENTITY_REUSE_MERCHANT_INVALID");return freeze({valid:errors.length===0,errors});}
export function assessHistoricalRefreshIdentityReuse({priorRecord,newRecord,priorProjection,atlasRetailers=[]}={}){
 if(!priorRecord||!newRecord||!priorProjection||!Array.isArray(atlasRetailers))throw new TypeError("priorRecord, newRecord, priorProjection, and atlasRetailers are required.");const reasons=[];let blocked=false;
 if(priorRecord.evidenceId===newRecord.evidenceId){blocked=true;reasons.push("SAME_RETAINED_EVIDENCE_NOT_NEW_CYCLE");}
 const priorProvider=providerIdentity(priorRecord),nextProvider=providerIdentity(newRecord);if(!compatibleProviderIdentity(priorProvider,nextProvider)){blocked=true;reasons.push("PROVIDER_PRODUCT_IDENTITY_CHANGED");}
 if(priorProjection.product?.state!=="VERIFIED"||!priorProjection.product.decisionId){blocked=true;reasons.push("PRIOR_PRODUCT_VERIFICATION_UNAVAILABLE");}
 if(newRecord.candidate?.identity?.atlasProductId!==priorProjection.product?.atlasProductId){blocked=true;reasons.push("ATLAS_PRODUCT_BINDING_CHANGED");}
 if(["AMBIGUOUS","REJECTED"].includes(newRecord.candidate?.identity?.outcome)||newRecord.candidate?.identity?.evidence?.some(x=>["CONFLICT","MISMATCH","CONTRADICTION"].includes(x.status))){blocked=true;reasons.push("PRODUCT_IDENTITY_CONTRADICTION");}
 let merchantResolution;try{merchantResolution=resolveDataForSeoMerchantIdentity({marketEvidence:newRecord.candidate?.marketEvidence,retailers:atlasRetailers});}catch{blocked=true;reasons.push("MERCHANT_RESOLUTION_INVALID");merchantResolution=null;}
 let merchant={state:merchantResolution?.outcome??"DISCOVERED",decisionId:null,retailerId:null,canonicalDomain:merchantResolution?.canonicalDomain??null};if(merchantResolution?.outcome==="RESOLVED"&&priorProjection.merchant?.state==="REGISTERED"&&merchantResolution.retailerId===priorProjection.merchant.merchantId){merchant={state:"REGISTERED",decisionId:priorProjection.merchant.decisionId,retailerId:merchantResolution.retailerId,canonicalDomain:merchantResolution.canonicalDomain,atlasResolution:merchantResolution};}else if(merchantResolution?.outcome==="RESOLVED"){reasons.push("MERCHANT_IDENTITY_REVIEW_REQUIRED");}else if(merchantResolution?.outcome==="DISCOVERED"){reasons.push("MERCHANT_DISCOVERED_REVIEW_REQUIRED");}else if(merchantResolution?.outcome==="CONFLICT"){blocked=true;reasons.push("MERCHANT_IDENTITY_CONTRADICTION");}
 const status=blocked?"BLOCKED":merchant.state==="REGISTERED"?"APPLICABLE":"REVIEW_REQUIRED";const result={schemaVersion:"1.0",assessmentType:"HISTORICAL_REFRESH_IDENTITY_REUSE",sourceEvidenceId:priorRecord.evidenceId,targetEvidenceId:newRecord.evidenceId,status,product:{state:blocked?"REVIEW_REQUIRED":"VERIFIED",decisionId:blocked?null:priorProjection.product.decisionId,remediationId:blocked?null:priorProjection.product.remediationId,atlasProductId:priorProjection.product.atlasProductId},merchant,reasons,retainedEvidenceModified:false,promotionAuthorized:false};const report=validateHistoricalRefreshIdentityReuse(result);if(!report.valid)throw new Error(report.errors.join(","));return freeze(result);
}
