import {assertHistoricalRefreshAuthorizationBinding} from "./HistoricalRefreshAuthorization.js";
import {assessHistoricalRefreshIdentityReuse} from "./HistoricalRefreshIdentityReuse.js";
import {projectIdentityReviewState} from "../identity-review/IdentityReviewProjection.js";
import {governHistoricalRefreshIdentityReuse} from "./GovernedHistoricalRefreshIdentityReuse.js";

const freeze=value=>{if(value&&typeof value==="object"&&!Object.isFrozen(value)){Object.freeze(value);for(const child of Object.values(value))freeze(child);}return value;};
const identity=value=>({productId:value?.productId??null,dataDocId:value?.dataDocId??null,gid:value?.gid??null});
const same=(a,b)=>JSON.stringify(identity(a))===JSON.stringify(identity(b));
function required(value,code){if(typeof value!=="string"||!value)throw new Error(code);return value;}

export class HistoricalRefreshResultRetrievalService{
 constructor({acquisitionService,retentionService,evidenceRepository,decisionRepository,retailerRepository}={}){if(!acquisitionService?.getSellersResult)throw new TypeError("acquisitionService is required.");if(!retentionService?.retain)throw new TypeError("retentionService is required.");if(!evidenceRepository?.getById)throw new TypeError("evidenceRepository is required.");if(!decisionRepository?.getAll||!decisionRepository?.getAllRemediations)throw new TypeError("decisionRepository is required.");if(!retailerRepository?.getAll)throw new TypeError("retailerRepository is required.");Object.assign(this,{acquisitionService,retentionService,evidenceRepository,decisionRepository,retailerRepository});}
 async retrieve({refreshPlan,authorization,refreshPlanId,authorizationId,providerTaskId,taskLedger,executionLedger,consumptionState}={}){
  required(refreshPlanId,"REFRESH_PLAN_ID_REQUIRED");required(authorizationId,"AUTHORIZATION_ID_REQUIRED");required(providerTaskId,"PROVIDER_TASK_ID_REQUIRED");assertHistoricalRefreshAuthorizationBinding({request:authorization,refreshPlan});
  if(refreshPlan.refreshPlanId!==refreshPlanId)throw new Error("REFRESH_PLAN_BINDING_MISMATCH");if(authorization.requestId!==authorizationId)throw new Error("REFRESH_AUTHORIZATION_BINDING_MISMATCH");if(refreshPlan.operation!=="SELLERS"||authorization.operation!=="SELLERS")throw new Error("REFRESH_RETRIEVAL_ONLY_SELLERS_ALLOWED");if(authorization.atlasProductId!==refreshPlan.atlasProductId||authorization.retailerId!==refreshPlan.existingIdentity.retailerId||!same(authorization.providerIdentity,refreshPlan.providerIdentity))throw new Error("REFRESH_SUBJECT_BINDING_MISMATCH");
  if(!Array.isArray(executionLedger?.runs))throw new Error("INVALID_ACQUISITION_EXECUTION_LEDGER");const runs=executionLedger.runs.filter(x=>x.planId===authorization.planId);if(runs.length!==1)throw new Error("REFRESH_EXECUTION_RUN_BINDING_INVALID");const run=runs[0];if(run.status!=="COMPLETED"||run.attemptedTasks!==1||run.completedTasks!==1||run.failedTasks!==0||run.plannedTasks!==1)throw new Error("REFRESH_EXECUTION_NOT_SINGLE_COMPLETED_TASK");const completed=run.tasks?.filter(x=>x.outcome==="COMPLETED")??[];if(completed.length!==1||completed[0].providerTaskId!==providerTaskId)throw new Error("REFRESH_PROVIDER_TASK_EXECUTION_MISMATCH");
  if(!Array.isArray(taskLedger))throw new Error("INVALID_DATAFORSEO_TASK_LEDGER");const taskEntries=taskLedger.filter(x=>x.taskId===providerTaskId);if(taskEntries.length!==1||taskEntries[0].kind!=="SELLERS")throw new Error("REFRESH_PROVIDER_TASK_LEDGER_MISMATCH");
  if(consumptionState?.schemaVersion!=="1.0"||!Array.isArray(consumptionState.consumed))throw new Error("INVALID_LIVE_AUTHORIZATION_CONSUMPTION_STATE");const consumed=consumptionState.consumed.filter(x=>x.authorizationId===authorizationId);if(consumed.length!==1||consumed[0].planId!==authorization.planId)throw new Error("REFRESH_AUTHORIZATION_NOT_CONSUMED");
  const priorRecord=await this.evidenceRepository.getById(refreshPlan.previous.evidenceId);if(!priorRecord)throw new Error("REFRESH_PRIOR_EVIDENCE_MISSING");const decisions=await this.decisionRepository.getAll(),remediations=await this.decisionRepository.getAllRemediations(),retailers=await this.retailerRepository.getAll();const priorProjection=projectIdentityReviewState({record:priorRecord,decisions,remediations,atlasRetailers:retailers});if(priorProjection.product?.state!=="VERIFIED"||priorProjection.product?.atlasProductId!==refreshPlan.atlasProductId)throw new Error("REFRESH_PRODUCT_IDENTITY_NO_LONGER_VERIFIED");if(priorProjection.merchant?.state!=="REGISTERED"||priorProjection.merchant?.merchantId!==refreshPlan.existingIdentity.retailerId)throw new Error("REFRESH_MERCHANT_IDENTITY_NO_LONGER_REGISTERED");
  const sellersResult=await this.acquisitionService.getSellersResult(providerTaskId);if(sellersResult?.id!==providerTaskId)throw new Error("REFRESH_PROVIDER_RESULT_TASK_MISMATCH");if(Number(sellersResult?.cost??0)!==0)throw new Error("REFRESH_RESULT_RETRIEVAL_MUST_BE_ZERO_COST");
  const observedAt=sellersResult?.result?.[0]?.datetime??sellersResult?.result?.[0]?.timestamp??run.finishedAt;const provider=identity(refreshPlan.providerIdentity);const productInfoItem={product_id:provider.productId,data_docid:provider.dataDocId,gid:provider.gid,title:sellersResult?.result?.[0]?.title??null};const retention=await this.retentionService.retain({sellersResult,productInfoResult:{cost:0,result:[{items:[productInfoItem]}]},sellersTaskId:providerTaskId,productInfoTaskId:`governed-provider-identity:${refreshPlan.refreshPlanId}`,observedAt,providerIdentity:provider,candidateId:`history-refresh-result:${refreshPlanId}`});
  const reuseAssessments=[];for(const integration of retention.integrations??[]){if(!integration.evidenceId)continue;const record=await this.evidenceRepository.getById(integration.evidenceId);reuseAssessments.push(assessHistoricalRefreshIdentityReuse({priorRecord,newRecord:record,priorProjection,atlasRetailers:retailers}));}const envelope={schemaVersion:"1.0",operation:"HISTORICAL_REFRESH_RESULT_RETRIEVAL",refreshPlanId,authorizationId,providerTaskId,retrievalStatus:"COMPLETED",sellerResultCount:retention.sellerItems,retained:retention.retained,duplicates:retention.duplicates,conflicts:0,acquisitionOutcome:retention.acquisitionOutcome??"SELLER_OBSERVATIONS_PROCESSED",absenceDoesNotImplyOutOfStock:retention.absenceDoesNotImplyOutOfStock??false,evidence:retention.integrations??[],historicalAdmissionPerformed:false,canonicalPromotionPerformed:false,publicationPerformed:false,paidTaskCreated:false,additionalSpendUsd:0};const identityReuse=[];for(const assessment of reuseAssessments){const targetRecord=await this.evidenceRepository.getById(assessment.targetEvidenceId);identityReuse.push(governHistoricalRefreshIdentityReuse({assessment,refreshResult:envelope,refreshPlan,sourceRecord:priorRecord,targetRecord}));}
  return freeze({...envelope,identityReuse});
 }
}
export default HistoricalRefreshResultRetrievalService;
