import crypto from "node:crypto";
import {projectIdentityReviewState} from "../identity-review/IdentityReviewProjection.js";
import {resolveHistoricalRefreshPriorContext} from "./HistoricalRefreshPriorContext.js";

const freeze=value=>{if(value&&typeof value==="object"&&!Object.isFrozen(value)){Object.freeze(value);for(const child of Object.values(value))freeze(child);}return value;};const hash=value=>crypto.createHash("sha256").update(JSON.stringify(value)).digest("hex");
function identity(value){return {productId:value?.productId??null,dataDocId:value?.dataDocId??null,gid:value?.gid??null};}
export class HistoricalRefreshPrepareService{
 constructor({productRepository,retailerRepository,evidenceRepository,historicalRepository,decisionRepository}={}){for(const [name,repo,method] of [["productRepository",productRepository,"getById"],["retailerRepository",retailerRepository,"getAll"],["evidenceRepository",evidenceRepository,"getAll"],["historicalRepository",historicalRepository,"getAll"],["decisionRepository",decisionRepository,"getAll"]])if(!repo?.[method])throw new TypeError(`${name} is required.`);Object.assign(this,{productRepository,retailerRepository,evidenceRepository,historicalRepository,decisionRepository});}
 async prepare({atlasProductId,sellersAuthorization,executionRuns=[],refreshPlan=null,refreshAuthorization=null,refreshResult=null}={}){if(typeof atlasProductId!=="string"||atlasProductId.trim()==="")throw new TypeError("atlasProductId is required.");
  const product=await this.productRepository.getById(atlasProductId);if(product?.identity?.atlasProductId!==atlasProductId)throw new Error("ATLAS_PRODUCT_BINDING_INVALID");const retailers=await this.retailerRepository.getAll(),evidenceRecords=await this.evidenceRepository.getAll(),historicalObservations=await this.historicalRepository.getAll();const prior=await resolveHistoricalRefreshPriorContext({atlasProductId,historicalObservations,evidenceRecords,evidenceRepository:this.evidenceRepository,sellersAuthorization,executionRuns,refreshPlan,refreshAuthorization,refreshResult}),providerIdentity=identity(prior.providerIdentity);if(!providerIdentity.productId&&!providerIdentity.dataDocId&&!providerIdentity.gid)throw new Error("GOVERNED_PROVIDER_IDENTITY_REQUIRED");const priorEvidence=prior.evidence,latestHistory=prior.observation;const decisions=await this.decisionRepository.getAll();const remediations=await this.decisionRepository.getAllRemediations();const projection=prior.identityProjection??projectIdentityReviewState({record:priorEvidence,decisions,remediations,atlasRetailers:retailers});if(projection.product.state!=="VERIFIED"||projection.merchant.state!=="REGISTERED")throw new Error("HISTORICAL_REFRESH_GOVERNED_IDENTITY_REQUIRED");const binding={atlasProductId,providerIdentity,previousObservationId:latestHistory.observationId,previousEvidenceId:priorEvidence.evidenceId,previousProviderTaskId:prior.providerTaskId,productDecisionId:projection.product.decisionId,merchantDecisionId:projection.merchant.decisionId};return freeze({schemaVersion:"1.0",refreshPlanId:`histrefresh_${hash(binding).slice(0,24)}`,operation:"SELLERS",status:"PENDING_OPERATOR_REVIEW",atlasProductId,providerIdentity,existingIdentity:{productState:"VERIFIED",productDecisionId:projection.product.decisionId,merchantState:"REGISTERED",merchantDecisionId:projection.merchant.decisionId,retailerId:projection.merchant.merchantId},minimumSafePath:{productsRequired:false,productInfoPaidTaskRequired:false,governedProductInfoProvenanceReused:true,sellersPaidTaskRequired:true,directSellersEligible:true},previous:{observationId:latestHistory.observationId,observationTime:latestHistory.observationTime,evidenceId:priorEvidence.evidenceId,providerTaskId:prior.providerTaskId},spendPolicy:{maxPaidTasks:1,maxSpendUsd:0.001,maxSpendPerDayUsd:0.01,automaticPaidRetries:0,singleUseAuthorizationRequired:true,newAuthorizationRequired:true},paidTaskCreated:false,actualSpendUsd:0,historicalAdmissionPerformed:false,canonicalPromotionAuthorized:false,publicationAuthorized:false});
 }
}
export default HistoricalRefreshPrepareService;
