import assert from "node:assert/strict";
import {mkdtemp,rm} from "node:fs/promises";
import {join} from "node:path";
import {tmpdir} from "node:os";
import {ACQUISITION_FAILURE_CLASSES,ACQUISITION_FAILURE_STAGES,CheckpointBoundProductsExecutor,CheckpointFailedExecutionReconciliationService,ControlledAcquisitionExecutor,FileAcquisitionExecutionLedgerRepository,FileLiveAuthorizationConsumptionRepository,FileSingleWriterRunLock,SingleUseAuthorizedLiveAcquisitionExecutor,checkpointSpendProjection,createAcquisitionBudgetPolicy,createAcquisitionFailureDiagnostic,createAcquisitionPlan,createLiveAcquisitionAuthorization,projectProductsCheckpoint,sanitizeAcquisitionFailureText} from "../index.js";

let cases=0;
const at="2026-09-03T23:33:21.273Z";
const policy=createAcquisitionBudgetPolicy({enabled:true,maxPaidTasksPerRun:1,maxSpendPerRunUsd:.001,maxSpendPerDayUsd:.01,automaticPaidRetries:0});
const plan=(id="failure")=>createAcquisitionPlan({policy,plannedAt:at,spentTodayUsd:0,candidates:[{candidateId:`${id}:products`,priority:"NORMAL",estimatedCostUsd:.001,execution:{kind:"PRODUCTS",provider:"DATAFORSEO",keyword:id}}]});
const root=await mkdtemp(join(tmpdir(),"hr-acq-failure-"));
try{
  const executeFailure=async({id,error})=>{const ledger=new FileAcquisitionExecutionLedgerRepository({filePath:join(root,`${id}.json`)}),executor=new ControlledAcquisitionExecutor({runLock:new FileSingleWriterRunLock({lockPath:join(root,`${id}.lock`)}),ledgerRepository:ledger,transport:{execute:async()=>{throw error;}},currentDaySpendResolver:async()=>0,now:()=>at,runId:()=>`run-${id}`});return {result:await executor.execute(plan(id)),ledger};};
  let error=new TypeError("fetch failed",{cause:Object.assign(new Error("socket"),{code:"ECONNRESET"})});let x=await executeFailure({id:"network",error});assert.equal(x.result.status,"FAILED");assert.equal(x.result.run.tasks[0].failure.failureStage,ACQUISITION_FAILURE_STAGES.DURING_PROVIDER_REQUEST);assert.equal(x.result.run.tasks[0].failure.failureClass,ACQUISITION_FAILURE_CLASSES.NETWORK_FAILURE);assert.equal(x.result.run.tasks[0].providerTaskId,null);cases++;
  error=Object.assign(new Error("DATAFORSEO_TASK_ERROR:40501"),{failureStage:"PROVIDER_REJECTED",failureClass:"PROVIDER_REJECTION",retryability:"REVIEW_REQUIRED",providerStatus:40501});x=await executeFailure({id:"rejected",error});assert.equal(x.result.run.tasks[0].failure.failureClass,"PROVIDER_REJECTION");assert.equal(x.result.run.tasks[0].providerStatus,40501);cases++;
  error=Object.assign(new Error("disk write failed"),{failureStage:"AFTER_PROVIDER_RESPONSE_BEFORE_TASK_PERSISTENCE",failureClass:"LOCAL_PERSISTENCE_FAILURE",retryability:"REVIEW_REQUIRED",providerTaskId:"provider-created",costUsd:.001});x=await executeFailure({id:"persist",error});assert.equal(x.result.run.tasks[0].failure.failureStage,"AFTER_PROVIDER_RESPONSE_BEFORE_TASK_PERSISTENCE");assert.equal(x.result.run.actualSpendUsd,.001);assert.equal(x.result.run.tasks[0].providerTaskId,"provider-created");cases++;
  error=Object.assign(new Error("Authorization: Basic dXNlcjpwYXNz password=hunter2"),{costUsd:0});x=await executeFailure({id:"secret",error});const serialized=JSON.stringify(x.result);assert(!serialized.includes("dXNlcjpwYXNz"));assert(!serialized.includes("hunter2"));assert(serialized.includes("REDACTED"));cases++;
  assert(!sanitizeAcquisitionFailureText("Bearer abc password=xyz").includes("abc"));cases++;
  const exact=await x.ledger.append(x.result.run);assert.equal(exact.status,"DUPLICATE");const conflict=structuredClone(x.result.run);conflict.tasks[0].failure.safeErrorMessage="different";await assert.rejects(()=>x.ledger.append(conflict),/REPLAY_CONFLICT/);cases++;

  const portfolio={portfolioCycleId:"portfolio-1",bindingDigest:"portfolio-digest",sourceRightsProfileDigest:"rights"},checkpoint={checkpointId:"checkpoint-1",portfolioCycleId:"portfolio-1",perTaskMaximumSpendUsd:.001,maximumSpendUsd:.009,programMaximumSpendUsd:.029,utcDayMaximumSpendUsd:.01,products:[{atlasProductId:"product-1",query:"product-1",atlasProductDigest:"a"},{atlasProductId:"product-2",query:"product-2",atlasProductDigest:"b"}]},task={portfolioCycleId:"portfolio-1",portfolioBindingDigest:"portfolio-digest",checkpointId:"checkpoint-1",checkpointStage:"PRODUCTS_DISCOVERY",atlasProductId:"product-1",query:"product-1",atlasProductDigest:"a",sourceRightsDigest:"rights",plan:plan("product-1"),authorization:{requestId:"auth-1"}};
  const failedRun={...x.result.run,runId:"failed-run",planId:task.plan.planId,actualSpendUsd:0,tasks:[{...x.result.run.tasks[0],candidateId:"product-1:products",actualCostUsd:0,providerTaskId:null,failure:createAcquisitionFailureDiagnostic({error:{message:"legacy unavailable",failureStage:"DURING_PROVIDER_REQUEST",failureClass:"UNKNOWN",retryability:"REVIEW_REQUIRED"},provider:"DATAFORSEO",operation:"PRODUCTS",occurredAt:at,executionRunId:"failed-run",authorizationId:"auth-1",candidateId:"product-1:products",actualSpendUsd:0})}]};
  const events=[],repo={events:async()=>structuredClone(events),portfolioEvents:async()=>structuredClone(events),appendEvent:async event=>{const prior=events.find(value=>value.eventId===event.eventId);if(prior){if(JSON.stringify(prior)!==JSON.stringify(event))throw new Error("CHECKPOINT_EVENT_REPLAY_CONFLICT");return{status:"DUPLICATE",event:prior};}events.push(structuredClone(event));return{status:"APPENDED",event};}},executionRepo={getAll:async()=>[structuredClone(failedRun)],findByPlanId:async id=>id===failedRun.planId?structuredClone(failedRun):null};
  let calls=0;const bound=new CheckpointBoundProductsExecutor({singleUseExecutor:{execute:async()=>{calls++;return{status:"FAILED",authorizationConsumed:true,execution:{run:structuredClone(failedRun)}};}},executionRepository:executionRepo,checkpointRepository:repo,now:()=>at});const result=await bound.execute({portfolio,checkpoint,task,authorization:{authorizationId:"auth-1",planId:task.plan.planId},confirmation:"SPEND-0.001"});assert.equal(result.status,"FAILED");assert.equal(calls,1);assert.equal(events[0].type,"TASK_AUTHORIZED");assert.equal(events[1].type,"TASK_FAILED");cases++;
  let projection=projectProductsCheckpoint({checkpoint,tasks:[task],events,reviews:[]});assert.equal(projection.products[0].state,"FAILED");assert.equal(projection.products[1].state,"READY_FOR_PRODUCTS");assert.equal(projection.nextProduct.atlasProductId,"product-2");assert.equal(projection.products[0].failure.retryability,"REVIEW_REQUIRED");cases++;
  assert.equal(checkpointSpendProjection({checkpoint,executionRuns:[failedRun],events,portfolioEvents:events,asOf:at}).remaining.checkpoint,.009);cases++;
  const charged={...failedRun,runId:"charged-run",actualSpendUsd:.001,tasks:[{...failedRun.tasks[0],actualCostUsd:.001}]},chargedEvent={...events[1],eventId:"charged-event",runId:"charged-run",actualSpendUsd:.001};assert.equal(checkpointSpendProjection({checkpoint,executionRuns:[charged],events:[chargedEvent],portfolioEvents:[chargedEvent],asOf:at}).remaining.checkpoint,.008);cases++;
  const reconcileEvents=[events[0]],reconcileRepo={...repo,events:async()=>structuredClone(reconcileEvents),portfolioEvents:async()=>structuredClone(reconcileEvents),appendEvent:async event=>{const prior=reconcileEvents.find(value=>value.eventId===event.eventId);if(prior){if(JSON.stringify(prior)!==JSON.stringify(event))throw new Error("CHECKPOINT_EVENT_REPLAY_CONFLICT");return{status:"DUPLICATE",event:prior};}reconcileEvents.push(structuredClone(event));return{status:"APPENDED",event};}};const service=new CheckpointFailedExecutionReconciliationService({checkpointRepository:reconcileRepo,executionRepository:executionRepo});let reconciled=await service.reconcile({portfolio,checkpoint,task,authorizationId:"auth-1"});assert.equal(reconciled.status,"APPENDED");assert.equal(reconcileEvents[0].type,"TASK_AUTHORIZED");assert.equal(reconcileEvents[1].type,"TASK_FAILED");cases++;
  reconciled=await service.reconcile({portfolio,checkpoint,task,authorizationId:"auth-1"});assert.equal(reconciled.status,"DUPLICATE");assert.equal(reconcileEvents.length,2);cases++;
  await assert.rejects(()=>service.reconcile({portfolio,checkpoint,task,authorizationId:"different"}),/BINDING_INVALID/);cases++;
  const malformed={...failedRun,tasks:[{...failedRun.tasks[0],providerTaskId:"invented"}]};const malformedService=new CheckpointFailedExecutionReconciliationService({checkpointRepository:reconcileRepo,executionRepository:{findByPlanId:async()=>malformed}});await assert.rejects(()=>malformedService.reconcile({portfolio,checkpoint,task,authorizationId:"auth-1"}),/RECONCILIATION_CONFLICT/);cases++;
  assert.equal(reconcileEvents.filter(event=>event.type==="TASK_AUTHORIZED").length,1);assert.equal(reconcileEvents.filter(event=>event.type==="TASK_FAILED").length,1);cases++;
  assert.equal(failedRun.actualSpendUsd,0);assert.equal(failedRun.tasks[0].providerTaskId,null);cases++;
  let delegated=0;const consumption=new FileLiveAuthorizationConsumptionRepository({filePath:join(root,"consumption.json")}),singleUse=new SingleUseAuthorizedLiveAcquisitionExecutor({executor:{execute:async()=>{delegated++;return{status:"FAILED",run:failedRun};}},consumptionRepository:consumption,now:()=>at}),liveAuthorization=createLiveAcquisitionAuthorization({authorizationId:"single-use-auth",authorized:true,planId:task.plan.planId,authorizedAt:"2026-09-03T23:30:00.000Z",expiresAt:"2026-09-03T23:59:00.000Z",maxSpendUsd:.001,maxPaidTasks:1});assert.equal((await singleUse.execute({plan:task.plan,authorization:liveAuthorization})).status,"FAILED");assert.equal((await singleUse.execute({plan:task.plan,authorization:liveAuthorization})).status,"LIVE_AUTHORIZATION_ALREADY_CONSUMED");assert.equal(delegated,1);assert.equal((await consumption.getAll()).length,1);cases++;
}finally{await rm(root,{recursive:true,force:true});}
console.log(`Acquisition failure reconciliation tests passed: ${cases} cases.`);
