import assert from "node:assert/strict";
import {AmazonDestinationProgressionService} from "../destinations/index.js";

const rightsDigest="r".repeat(64),destinations=[],products=new Map(),identities=new Map(),results=new Map();
const add=(id,index)=>{const assessmentId=`assessment-${index}`,canonicalResultId=`result-${index}`,resultDigest=String(index).padStart(64,"0");products.set(id,{identity:{atlasProductId:id,manufacturerPartNumber:`MPN-${index}`},governance:{lifecycleStatus:"ACTIVE",publicationStatus:"READY"}});identities.set(assessmentId,{assessmentId,outcomeId:`outcome-${index}`,atlasProductId:id,state:"STRONG_UNIQUE_ASIN",governedAsin:`B${String(index).padStart(9,"0")}`,canonicalResultId,resultDigest});results.set(canonicalResultId,{canonicalResultId,sourceId:"DATAFORSEO_AMAZON",operation:"AMAZON_PRODUCTS",atlasProductId:id,resultDigest,providerTaskId:`task-${index}`,sourceRightsProfileDigest:rightsDigest});return{atlasProductId:id,assessmentId};};
let rightsValid=true;const service=new AmazonDestinationProgressionService({productRepository:{getById:async id=>structuredClone(products.get(id))},retailerRepository:{getById:async()=>({name:"Amazon",status:"active"})},identityRepository:{getEffectiveOutcomeByAssessmentId:async id=>structuredClone(identities.get(id))},resultRepository:{getCanonicalResultById:async id=>structuredClone(results.get(id))},rightsRegistry:{verifyLineage:()=>({verified:rightsValid})},destinationRepository:{getAll:async()=>structuredClone(destinations)}});
const a=add("ram-a",1),b=add("ram-b",2),c=add("ram-c",3),preparedA=await service.prepare(a),preparedB=await service.prepare(b);
destinations.push({destinationId:"unrelated",atlasProductId:"ram-c",retailerId:"RETAILER-0004",marketplace:"newegg.com",retailerListingId:"SKU-C",destinationUrl:"https://newegg.com/p/c",materialFingerprint:"u".repeat(64),status:"ACTIVE",supersedesDestinationId:null});
assert.equal((await service.prepare(b)).bindingDigest,preparedB.bindingDigest);assert.equal((await service.revalidatePreparation(preparedB)).status,"CURRENT");
destinations.reverse();assert.equal((await service.prepare(b)).bindingDigest,preparedB.bindingDigest);destinations.reverse();
const sameProduct={destinationId:"same-product",atlasProductId:"ram-b",retailerId:"RETAILER-0004",marketplace:"newegg.com",retailerListingId:"SKU-B",destinationUrl:"https://newegg.com/p/b",materialFingerprint:"s".repeat(64),status:"ACTIVE",supersedesDestinationId:null};destinations.push(sameProduct);await assert.rejects(()=>service.revalidatePreparation(preparedB),/PREPARATION_STALE/);sameProduct.status="RETIRED";await assert.rejects(()=>service.revalidatePreparation(preparedB),/PREPARATION_STALE/);destinations.splice(destinations.indexOf(sameProduct),1,{...sameProduct,destinationId:"same-product-successor",status:"ACTIVE",materialFingerprint:"t".repeat(64),supersedesDestinationId:"same-product"});await assert.rejects(()=>service.revalidatePreparation(preparedB),/PREPARATION_STALE/);destinations.pop();
const identityB=identities.get(b.assessmentId),candidateUrl=`https://amazon.com/dp/${identityB.governedAsin}`;destinations.push({destinationId:"asin-collision",atlasProductId:c.atlasProductId,retailerId:"RETAILER-0001",marketplace:"amazon.com",retailerListingId:identityB.governedAsin,destinationUrl:"https://amazon.com/dp/B888888888",materialFingerprint:"c".repeat(64),status:"ACTIVE",supersedesDestinationId:null});await assert.rejects(()=>service.revalidatePreparation(preparedB),/CROSS_PRODUCT_COLLISION/);destinations.pop();destinations.push({destinationId:"url-collision",atlasProductId:c.atlasProductId,retailerId:"RETAILER-0001",marketplace:"amazon.com",retailerListingId:"B777777777",destinationUrl:candidateUrl,materialFingerprint:"d".repeat(64),status:"ACTIVE",supersedesDestinationId:null});await assert.rejects(()=>service.revalidatePreparation(preparedB),/CROSS_PRODUCT_COLLISION/);destinations.pop();
const productB=products.get(b.atlasProductId),mpn=productB.identity.manufacturerPartNumber;productB.identity.manufacturerPartNumber="CHANGED";await assert.rejects(()=>service.revalidatePreparation(preparedB),/PREPARATION_STALE/);productB.identity.manufacturerPartNumber=mpn;productB.governance.lifecycleStatus="DRAFT";await assert.rejects(()=>service.revalidatePreparation(preparedB),/NOT_ACTIVE_READY/);productB.governance.lifecycleStatus="ACTIVE";
const outcome=identityB.outcomeId;identityB.outcomeId="changed";await assert.rejects(()=>service.revalidatePreparation(preparedB),/PREPARATION_STALE/);identityB.outcomeId=outcome;
const oldDigest=identityB.resultDigest,newDigest="f".repeat(64);identityB.resultDigest=newDigest;results.get(identityB.canonicalResultId).resultDigest=newDigest;await assert.rejects(()=>service.revalidatePreparation(preparedB),/PREPARATION_STALE/);identityB.resultDigest=oldDigest;results.get(identityB.canonicalResultId).resultDigest=oldDigest;
rightsValid=false;await assert.rejects(()=>service.revalidatePreparation(preparedB),/RIGHTS_LINEAGE_INVALID/);rightsValid=true;
const asin=identityB.governedAsin;identityB.governedAsin="B999999999";await assert.rejects(()=>service.revalidatePreparation(preparedB),/PREPARATION_STALE/);identityB.governedAsin=asin;
await assert.rejects(()=>service.revalidatePreparation({...preparedA,bindingDigest:"0".repeat(64)}),/BINDING_INVALID/);await assert.rejects(()=>service.revalidatePreparation({}),/PREPARATION_INVALID/);
console.log("Amazon destination relevant-state binding tests passed (determinism, sibling independence, relevant mutation, collision, Atlas, identity, result, rights, URL, malformed binding). ");
