import assert from "node:assert/strict";
import {mkdtemp,rm} from "node:fs/promises";
import os from "node:os";
import path from "node:path";
import {AmazonDestinationProgressionService,AmazonDestinationReviewWorkflowService,FileAmazonDestinationReviewRepository,AMAZON_DESTINATION_APPROVAL_ATTESTATION,AMAZON_DESTINATION_REVIEW_CONFIRMATION,AMAZON_DESTINATION_PERSIST_CONFIRMATION} from "../destinations/index.js";
import {sourceRightsProfileDigest} from "../rights/SourceRightsRegistry.js";

const root=await mkdtemp(path.join(os.tmpdir(),"amazon-destination-review-")),statePath=path.join(root,"reviews.json"),rights={sourceId:"DATAFORSEO_AMAZON"},rightsDigest=sourceRightsProfileDigest(rights),products=new Map(),identities=new Map(),results=new Map(),destinations=[];
const add=index=>{const atlasProductId=`ram_fixture_${index}`,assessmentId=`assessment-${index}`,resultId=`result-${index}`,product={identity:{atlasProductId,manufacturerPartNumber:`MPN-${index}`},governance:{lifecycleStatus:"ACTIVE",publicationStatus:"READY"}},identity={assessmentId,outcomeId:`outcome-${index}`,atlasProductId,state:"STRONG_UNIQUE_ASIN",governedAsin:`B${String(index).padStart(9,"0")}`,canonicalResultId:resultId,resultDigest:String(index).padStart(64,"0")},result={canonicalResultId:resultId,sourceId:"DATAFORSEO_AMAZON",operation:"AMAZON_PRODUCTS",atlasProductId,resultDigest:identity.resultDigest,providerTaskId:`task-${index}`,sourceRightsProfileDigest:rightsDigest};products.set(atlasProductId,product);identities.set(assessmentId,identity);results.set(resultId,result);return{atlasProductId,assessmentId};};
const first=add(1);
const destinationRepository={
 getAll:async()=>structuredClone(destinations),
 retain:async destination=>{if(destinations.some(value=>value.destinationId===destination.destinationId))return{status:"DUPLICATE",destinationId:destination.destinationId};destinations.push(structuredClone(destination));return{status:"RETAINED",destinationId:destination.destinationId};}
};
const progression=new AmazonDestinationProgressionService({
 productRepository:{getById:async id=>products.get(id)},
 retailerRepository:{getById:async()=>({id:"RETAILER-0001",name:"Amazon",status:"active"})},
 identityRepository:{getEffectiveOutcomeByAssessmentId:async id=>identities.get(id)},
 resultRepository:{getCanonicalResultById:async id=>results.get(id)},
 rightsRegistry:{verifyLineage:()=>({verified:true})},
 destinationRepository
});
const preparation=await progression.prepare(first),preparations=new Map([[preparation.preparationId,preparation]]),repository=new FileAmazonDestinationReviewRepository({statePath}),workflow=new AmazonDestinationReviewWorkflowService({progressionService:progression,reviewRepository:repository,preparationResolver:async id=>preparations.get(id)??null});
await assert.rejects(()=>workflow.recordReview({preparationId:preparation.preparationId,decision:"APPROVE",reviewedBy:"operator",reviewedAt:"2026-10-07T12:00:00Z",confirmation:AMAZON_DESTINATION_REVIEW_CONFIRMATION}),/ATTESTATION_REQUIRED/);
const approved=await workflow.recordReview({preparationId:preparation.preparationId,decision:"APPROVE",reviewedBy:"operator",reviewedAt:"2026-10-07T12:00:00Z",approvalAttestation:AMAZON_DESTINATION_APPROVAL_ATTESTATION,confirmation:AMAZON_DESTINATION_REVIEW_CONFIRMATION});assert.equal(approved.status,"RECORDED");assert.equal(approved.destinationPersisted,false);assert.equal(destinations.length,0);
assert.equal((await workflow.recordReview({preparationId:preparation.preparationId,decision:"APPROVE",reviewedBy:"operator",reviewedAt:"2026-10-07T12:00:00Z",approvalAttestation:AMAZON_DESTINATION_APPROVAL_ATTESTATION,confirmation:AMAZON_DESTINATION_REVIEW_CONFIRMATION})).status,"DUPLICATE");
await assert.rejects(()=>workflow.recordReview({preparationId:preparation.preparationId,decision:"REJECT",reviewedBy:"operator",reviewedAt:"2026-10-07T12:01:00Z",rejectionReason:"WRONG_PRODUCT",confirmation:AMAZON_DESTINATION_REVIEW_CONFIRMATION}),/DECISION_CONFLICT/);
const persisted=await workflow.persist({reviewId:approved.review.reviewId,executedBy:"operator",confirmation:AMAZON_DESTINATION_PERSIST_CONFIRMATION});assert.equal(persisted.status,"DESTINATION_CREATED");assert.equal(destinations.length,1);assert.equal((await workflow.persist({reviewId:approved.review.reviewId,executedBy:"operator",confirmation:AMAZON_DESTINATION_PERSIST_CONFIRMATION})).status,"ALREADY_BOUND");
const second=add(2),secondPreparation=await progression.prepare(second);preparations.set(secondPreparation.preparationId,secondPreparation);const rejected=await workflow.recordReview({preparationId:secondPreparation.preparationId,decision:"REJECT",reviewedBy:"operator",reviewedAt:"2026-10-07T12:02:00Z",rejectionReason:"VARIANT_CONFLICT",confirmation:AMAZON_DESTINATION_REVIEW_CONFIRMATION});await assert.rejects(()=>workflow.persist({reviewId:rejected.review.reviewId,executedBy:"operator",confirmation:AMAZON_DESTINATION_PERSIST_CONFIRMATION}),/REVIEW_REJECTED/);
const third=add(3),thirdPreparation=await progression.prepare(third);preparations.set(thirdPreparation.preparationId,thirdPreparation);const thirdReview=await workflow.recordReview({preparationId:thirdPreparation.preparationId,decision:"APPROVE",reviewedBy:"operator",reviewedAt:"2026-10-07T12:03:00Z",approvalAttestation:AMAZON_DESTINATION_APPROVAL_ATTESTATION,confirmation:AMAZON_DESTINATION_REVIEW_CONFIRMATION});destinations.push({destinationId:"unrelated",materialFingerprint:"x",status:"ACTIVE",retailerId:"RETAILER-0002",atlasProductId:"other"});await assert.rejects(()=>workflow.persist({reviewId:thirdReview.review.reviewId,executedBy:"operator",confirmation:AMAZON_DESTINATION_PERSIST_CONFIRMATION}),/PREPARATION_STALE/);destinations.pop();
const fourth=add(4),fourthPreparation=await progression.prepare(fourth);preparations.set(fourthPreparation.preparationId,fourthPreparation);const fourthReview=await workflow.recordReview({preparationId:fourthPreparation.preparationId,decision:"APPROVE",reviewedBy:"operator",reviewedAt:"2026-10-07T12:04:00Z",approvalAttestation:AMAZON_DESTINATION_APPROVAL_ATTESTATION,confirmation:AMAZON_DESTINATION_REVIEW_CONFIRMATION});destinations.push({destinationId:"collision",materialFingerprint:"y",status:"ACTIVE",retailerId:"RETAILER-0001",atlasProductId:"other",retailerListingId:fourthPreparation.asin,destinationUrl:fourthPreparation.candidateUrl});await assert.rejects(()=>workflow.persist({reviewId:fourthReview.review.reviewId,executedBy:"operator",confirmation:AMAZON_DESTINATION_PERSIST_CONFIRMATION}),/CROSS_PRODUCT_COLLISION/);destinations.pop();
await assert.rejects(()=>workflow.recordReview({preparationId:"wrong",decision:"REJECT",reviewedBy:"operator",reviewedAt:"2026-10-07T12:02:00Z",rejectionReason:"WRONG_PRODUCT",confirmation:AMAZON_DESTINATION_REVIEW_CONFIRMATION}),/PREPARATION_NOT_FOUND/);
const restarted=new FileAmazonDestinationReviewRepository({statePath});assert.equal((await restarted.getById(approved.review.reviewId)).decision,"APPROVE");assert.equal((await restarted.getAll()).length,4);
for(let index=5;index<=202;index++){const input=add(index),prep=await progression.prepare(input),review=progression.createReview({preparation:prep,decision:"REJECT",reviewedBy:"operator",reviewedAt:"2026-10-07T12:05:00Z",rejectionReason:"OTHER_REVIEW_REQUIRED"});await restarted.record(review);}assert.equal((await restarted.getAll()).length,202);
await rm(root,{recursive:true,force:true});console.log("Amazon destination governed review workflow tests passed (review, persistence separation, replay, rejection, restart, and 200-product scale).");
