import assert from"node:assert/strict";import{mkdtemp,rm}from"node:fs/promises";import{tmpdir}from"node:os";import{join}from"node:path";import{BoundedExistingTaskProgressionService,NeutralBoundedPaidActionCoordinator,SqliteNeutralBoundedRepository,BOUNDED_FAILURE_CLASSES,BOUNDED_MEMBER_STATES}from"../index.js";
let cases=0;const eq=(a,b)=>{assert.equal(a,b);cases++},at="2026-09-15T12:00:00.000Z",expiry="2026-09-15T13:00:00.000Z";
const root=await mkdtemp(join(tmpdir(),"bounded-pending-progression-"));
const makeAdapter=({responses=new Map(),paidCalls={value:0},finalizations={value:0}}={})=>({
 async prepareMember({request}){return{memberKey:request.key,domainMemberId:request.key,source:request.source??"DATAFORSEO_AMAZON",operation:request.source==="DATAFORSEO_GOOGLE_SHOPPING"?"PRODUCTS":"AMAZON_PRODUCTS",taskCeilingUsd:.0015,paidTaskCreated:false,providerTaskId:null}},
 async revalidateMember(){return true},
 classifyFailure(error){return{classification:/SYSTEMIC|CONFLICT|LINEAGE/.test(String(error.message))?BOUNDED_FAILURE_CLASSES.SYSTEMIC:BOUNDED_FAILURE_CLASSES.MEMBER_LOCAL,state:"EXCEPTION",reason:String(error.message)}},
 async advanceMember({member,checkpoint}){let current=member;if(current.state===BOUNDED_MEMBER_STATES.READY){paidCalls.value++;current=checkpoint({state:BOUNDED_MEMBER_STATES.WAITING,paidTaskCreated:true,providerTaskId:`task:${member.memberKey}`,actualSpendUsd:.0015});return current;}const queue=responses.get(member.memberKey)??["PENDING"],next=queue.length>1?queue.shift():queue[0];if(next instanceof Error)throw next;if(next==="PENDING")return{...current,state:BOUNDED_MEMBER_STATES.WAITING};finalizations.value++;return{...current,state:BOUNDED_MEMBER_STATES.COMPLETED,outcome:next,canonicalResultId:`result:${member.memberKey}`}},
 summarize(run){return{runId:run.runId,state:run.state,completed:run.members.filter(x=>x.state===BOUNDED_MEMBER_STATES.COMPLETED).length,pending:run.members.filter(x=>x.state===BOUNDED_MEMBER_STATES.WAITING).length,exceptions:run.members.filter(x=>x.state===BOUNDED_MEMBER_STATES.EXCEPTION).length,systemicFailure:run.systemicFailure??null,members:run.members}}
});
const create=async({name,cohort,responses}={})=>{const path=join(root,`${name}.sqlite`),repository=new SqliteNeutralBoundedRepository({databasePath:path}),paidCalls={value:0},finalizations={value:0},adapter=makeAdapter({responses,paidCalls,finalizations}),coordinator=new NeutralBoundedPaidActionCoordinator({repository,domainAdapter:adapter,spendResolver:async()=>0,now:()=>at,dailySpendCeilingUsd:.05,policyVersion:"FIXTURE-1.0"}),plan=await coordinator.prepare({cycle:at,cohort}),authorization=await coordinator.authorize({planId:plan.value.planId,operator:"fixture",reason:"fixture",expiresAt:expiry}),started=await coordinator.start({authorizationId:authorization.value.authorizationId,startedBy:"fixture"});return{path,repository,adapter,coordinator,service:new BoundedExistingTaskProgressionService({coordinator,wait:async()=>{},now:()=>at}),started,paidCalls,finalizations}};
try{
 const immediate=await create({name:"immediate",cohort:[{key:"a"}],responses:new Map([["a",["STRONG_UNIQUE_ASIN"]]])}),a=await immediate.service.progress({runId:immediate.started.runId,maxAttempts:1,intervalMs:0});eq(a.progressionStatus,"TERMINAL");eq(a.completed,1);eq(immediate.paidCalls.value,1);eq(a.newPaidTasks,0);eq(a.newSpendUsd,0);
 const mixed=await create({name:"mixed",cohort:[{key:"a"},{key:"b"}],responses:new Map([["a",["STRONG_UNIQUE_ASIN"]],["b",["PENDING"]]])}),b=await mixed.service.progress({runId:mixed.started.runId,maxAttempts:1,intervalMs:0});eq(b.progressionStatus,"PENDING_BOUND_REACHED");eq(b.completed,1);eq(b.pending,1);eq(mixed.paidCalls.value,2);
 const later=await create({name:"later",cohort:[{key:"a"}],responses:new Map([["a",["PENDING","STRONG_UNIQUE_ASIN"]]])}),c=await later.service.progress({runId:later.started.runId,maxAttempts:2,intervalMs:0});eq(c.progressionAttempts,2);eq(c.completed,1);eq(later.finalizations.value,1);eq(later.paidCalls.value,1);
 const bounded=await create({name:"bounded",cohort:[{key:"a"}],responses:new Map([["a",["PENDING"]]])}),d=await bounded.service.progress({runId:bounded.started.runId,maxAttempts:3,intervalMs:0});eq(d.progressionStatus,"PENDING_BOUND_REACHED");eq(d.progressionAttempts,3);eq(bounded.paidCalls.value,1);
 const local=await create({name:"local",cohort:[{key:"a"},{key:"b"}],responses:new Map([["a",[new Error("IDENTITY_AMBIGUITY")]],["b",["STRONG_UNIQUE_ASIN"]]])}),e=await local.service.progress({runId:local.started.runId,maxAttempts:1,intervalMs:0});eq(e.state,"COMPLETED_WITH_EXCEPTIONS");eq(e.completed,1);eq(e.exceptions,1);
 for(const [name,message] of [["lineage","SYSTEMIC_LINEAGE_FAILURE"],["conflict","IMMUTABLE_RESULT_CONFLICT"]]){const fixture=await create({name,cohort:[{key:"a"}],responses:new Map([["a",[new Error(message)]]])}),result=await fixture.service.progress({runId:fixture.started.runId,maxAttempts:1,intervalMs:0});eq(result.progressionStatus,"SYSTEMIC_STOP");eq(result.systemicFailure,message);eq(fixture.paidCalls.value,1);fixture.repository.close();}
 const restart=await create({name:"restart",cohort:[{key:"a"}],responses:new Map([["a",["STRONG_UNIQUE_ASIN"]]])}),runId=restart.started.runId;restart.repository.close();const reopened=new SqliteNeutralBoundedRepository({databasePath:restart.path}),restartedCoordinator=new NeutralBoundedPaidActionCoordinator({repository:reopened,domainAdapter:restart.adapter,spendResolver:async()=>0,now:()=>at,dailySpendCeilingUsd:.05,policyVersion:"FIXTURE-1.0"}),restarted=new BoundedExistingTaskProgressionService({coordinator:restartedCoordinator,wait:async()=>{},now:()=>at}),f=await restarted.progress({runId,maxAttempts:1,intervalMs:0});eq(f.completed,1);eq(f.members[0].providerTaskId,"task:a");eq(restart.paidCalls.value,1);const replay=await restarted.progress({runId,maxAttempts:1,intervalMs:0});eq(replay.progressionStatus,"TERMINAL");eq(restart.finalizations.value,1);reopened.close();
 const sources=await create({name:"sources",cohort:[{key:"amazon",source:"DATAFORSEO_AMAZON"},{key:"google",source:"DATAFORSEO_GOOGLE_SHOPPING"}],responses:new Map([["amazon",["STRONG_UNIQUE_ASIN"]],["google",["IDENTITY_RESOLVED"]]])}),g=await sources.service.progress({runId:sources.started.runId,maxAttempts:1,intervalMs:0});eq(g.completed,2);eq(new Set(g.members.map(x=>x.source)).size,2);eq(sources.paidCalls.value,2);
 const missing=await create({name:"missing-task",cohort:[{key:"a"}],responses:new Map([["a",["PENDING"]]])}),missingMember=missing.repository.getRun(missing.started.runId).members[0];missing.repository.updateMember(missing.started.runId,{...missingMember,providerTaskId:null});const missingResult=await missing.service.progress({runId:missing.started.runId,maxAttempts:1,intervalMs:0});eq(missingResult.progressionStatus,"SYSTEMIC_STOP");eq(missingResult.systemicFailure,"BOUNDED_PENDING_TASK_LINEAGE_INVALID");eq(missing.paidCalls.value,1);missing.repository.close();
 const forbidden=await create({name:"forbidden-paid",cohort:[{key:"a"}],responses:new Map([["a",["PENDING"]]])}),forbiddenMember=forbidden.repository.getRun(forbidden.started.runId).members[0];forbidden.repository.updateMember(forbidden.started.runId,{...forbiddenMember,state:BOUNDED_MEMBER_STATES.READY});const forbiddenResult=await forbidden.service.progress({runId:forbidden.started.runId,maxAttempts:1,intervalMs:0});eq(forbiddenResult.progressionStatus,"SYSTEMIC_STOP");eq(forbiddenResult.systemicFailure,"BOUNDED_PENDING_NEW_PAID_TASK_FORBIDDEN");eq(forbidden.paidCalls.value,1);forbidden.repository.close();
 await assert.rejects(()=>sources.coordinator.progressExistingTasks({runId:"missing"}),/BOUNDED_RUN_NOT_FOUND/);cases++;
 for(const fixture of[immediate,mixed,later,bounded,local,sources])fixture.repository.close();
}finally{await rm(root,{recursive:true,force:true})}
console.log(`Bounded existing-task progression tests passed: ${cases} cases.`);
