import assert from "node:assert/strict";
import crypto from "node:crypto";
import {mkdtemp,rm} from "node:fs/promises";
import {join} from "node:path";
import {tmpdir} from "node:os";
import {BoundedRepeatObservationRunService,BOUNDED_REPEAT_RUN_AUTHORIZE_CONFIRMATION,BOUNDED_REPEAT_RUN_START_CONFIRMATION,BOUNDED_REPEAT_RUN_RESUME_CONFIRMATION,createAmazonRepeatObservationIdentity,createGoogleRepeatObservationIdentity,createProductionRepeatObservationService,defaultSourceRightsRegistry,DataForSeoTaskLedger,FileHistoricalBootstrapProviderResultRepository,ProductionRepeatObservationResultPipeline,SqliteRepeatObservationRepository} from "../index.js";

let cases=0;const at="2026-09-14T00:00:00.000Z",expires="2026-09-14T01:00:00.000Z",sha=v=>crypto.createHash("sha256").update(v).digest("hex"),root=await mkdtemp(join(tmpdir(),"hr-bounded-prod-"));
try{
 const consumed=new Set(),consumptionRepository={getAll:async()=>[...consumed].map(authorizationId=>({authorizationId}))},repository=new SqliteRepeatObservationRepository({databasePath:join(root,"repeat.sqlite"),consumptionRepository}),taskLedger=new DataForSeoTaskLedger(),resultRepository=new FileHistoricalBootstrapProviderResultRepository({statePath:join(root,"results.json")}),products=new Map([["ram-amazon",{identity:{atlasProductId:"ram-amazon"}}],["ram-google",{identity:{atlasProductId:"ram-google"}}]]),identityResolvers={DATAFORSEO_AMAZON:{resolve:async({atlasProduct})=>createAmazonRepeatObservationIdentity({atlasProductId:atlasProduct.identity.atlasProductId,state:"STRONG_UNIQUE_ASIN",governedAsin:"B0CQQVNCB6",sellersAuthorizationEligible:true,outcomeId:"amazon-outcome"})},DATAFORSEO_GOOGLE_SHOPPING:{resolve:async({atlasProduct})=>createGoogleRepeatObservationIdentity({atlasProductId:atlasProduct.identity.atlasProductId,state:"REUSED",providerIdentity:{productId:"google-product",dataDocId:"google-doc",gid:null},sourceEvidenceId:"google-evidence",contradictionStatus:"NONE"})}};
 let taskSequence=0;const taskOwner=source=>({execute:async({request})=>{if(consumed.has(request.authorizationId))return{status:"LIVE_AUTHORIZATION_ALREADY_CONSUMED"};consumed.add(request.authorizationId);const execution=request.plan.decisions[0].execution,taskId=`task-${++taskSequence}`;taskLedger.record(`key-${taskId}`,{...execution,taskId,sourceId:source,costUsd:source==="DATAFORSEO_AMAZON"?.0015:.001,createdStatus:20100,requestDigest:sha(`request-${taskId}`)});return{status:"COMPLETED"};}}),pending=new Set(["SELLERS"]),retrievalOwners={AMAZON_SELLERS:{retrieve:async({providerTaskId})=>({id:providerTaskId,cost:0,result:[{items:[{price:1}]}]})},SELLERS:{retrieve:async({providerTaskId})=>pending.has("SELLERS")?{status:"PENDING"}:{id:providerTaskId,cost:0,result:[{items:[{base_price:1}]}]}}},processed=[];
 const processingOwners=Object.fromEntries(["AMAZON_SELLERS","SELLERS"].map(operation=>[operation,{process:async({preparation,lineage})=>{processed.push(operation);assert.equal(lineage.parentRunAuthorizationId?.startsWith("mer_repeatrunauth_"),true);return{evidenceIds:[`evidence-${preparation.atlasProductId}`],duplicates:0};}}])),pipeline=new ProductionRepeatObservationResultPipeline({repeatRepository:repository,taskLedger,resultRepository,retrievalOwners,processingOwners,now:()=>at}),facts=[];
 const repeat=createProductionRepeatObservationService({stateRoot:root,databasePath:join(root,"repeat.sqlite"),repository,productRepository:{getById:async id=>products.get(id)},identityResolvers,rightsRegistry:defaultSourceRightsRegistry,consumptionRepository,taskOwners:{AMAZON_SELLERS:taskOwner("DATAFORSEO_AMAZON"),SELLERS:taskOwner("DATAFORSEO_GOOGLE_SHOPPING")},resultPipeline:pipeline,historicalAdmissionOwner:{assess:async({evidenceId})=>({evidenceId,historicalEligible:true,canonicalEligible:false,publicationEligible:false}),admit:async({evidenceId})=>(facts.push(evidenceId),{observationId:`history-${evidenceId}`})},now:()=>at}),bounded=new BoundedRepeatObservationRunService({repeatService:repeat,repository,spendResolver:async()=>0,now:()=>at});
 const planned=await bounded.prepareRun({observationCycle:at,cohort:[{atlasProductId:"ram-google",source:"DATAFORSEO_GOOGLE_SHOPPING"},{atlasProductId:"ram-amazon",source:"DATAFORSEO_AMAZON"}]});assert.equal(planned.status,"PREPARED");assert.equal(planned.value.ready.length,2);cases+=2;
 const authorized=await bounded.authorizeRun({runPlanId:planned.value.runPlanId,operator:"operator:fixture",reason:"fixture",expiresAt:expires,confirmation:BOUNDED_REPEAT_RUN_AUTHORIZE_CONFIRMATION});assert.equal(authorized.status,"AUTHORIZED");cases++;
 const started=await bounded.startRun({runAuthorizationId:authorized.value.runAuthorizationId,startedBy:"operator:fixture",confirmation:BOUNDED_REPEAT_RUN_START_CONFIRMATION});assert.equal(started.state,"WAITING_FOR_PROVIDER");assert.equal(started.paidTasksCreated,2);assert.equal(started.completed,1);assert.equal(started.pending,1);assert.equal(taskLedger.getAll().length,2);assert.deepEqual(processed,["AMAZON_SELLERS"]);cases+=6;
 pending.clear();const resumed=await bounded.resumeRun({runId:started.runId,resumedBy:"operator:fixture",confirmation:BOUNDED_REPEAT_RUN_RESUME_CONFIRMATION});assert.equal(resumed.state,"COMPLETED");assert.equal(resumed.completed,2);assert.equal(resumed.pending,0);assert.equal(resumed.paidTasksCreated,2);assert.equal(taskLedger.getAll().length,2);assert.deepEqual(processed.sort(),["AMAZON_SELLERS","SELLERS"]);assert.equal(facts.length,2);assert.equal(resumed.currentPriceWrites,0);assert.equal(resumed.publicationWrites,0);cases+=9;
 const replay=await bounded.resumeRun({runId:started.runId,resumedBy:"operator:fixture",confirmation:BOUNDED_REPEAT_RUN_RESUME_CONFIRMATION});assert.equal(replay.state,"COMPLETED");assert.equal(taskLedger.getAll().length,2);assert.equal(facts.length,2);cases+=3;
 repeat.close();
}finally{await rm(root,{recursive:true,force:true});}
console.log(`Bounded repeat production pipeline tests passed: ${cases} cases.`);
