import assert from "node:assert/strict";import{mkdtemp,rm}from"node:fs/promises";import{tmpdir}from"node:os";import{join}from"node:path";
import{ControlledAcquisitionExecutor,SqliteNeutralBoundedRepository,createBoundedChildAuthorityBinding,createBoundedSpendProgressionResolver,createNeutralParentAuthorityInput}from"../index.js";
let cases=0;const eq=(a,b)=>{assert.deepEqual(a,b);cases++},at="2026-09-15T02:40:00.000Z",expiry="2026-09-15T03:40:00.000Z";
async function fixture({snapshot=0,parentMaximum=.003,costs=[.001],current=snapshot+costs.reduce((a,b)=>a+b,0)}={}){const root=await mkdtemp(join(tmpdir(),"bounded-spend-")),repo=new SqliteNeutralBoundedRepository({databasePath:join(root,"state.sqlite")}),ready=[0,1,2].map(i=>({memberKey:`member-${i}`,domainMemberId:`domain-${i}`,source:"DATAFORSEO_GOOGLE_SHOPPING",operation:"PRODUCTS",taskCeilingUsd:.001})),plan={schemaVersion:"1.0",planId:"plan",bindingDigest:"a".repeat(64),cycle:at,ready,blocked:[],requested:[],cohortDigest:"b".repeat(64),maximumPaidTasks:3,maximumSpendUsd:parentMaximum},authorization={schemaVersion:"1.0",authorizationId:"parent",bindingDigest:"c".repeat(64),planId:plan.planId,planBindingDigest:plan.bindingDigest,automaticPaidRetries:0,expiresAt:expiry,maximumPaidTasks:3,maximumSpendUsd:parentMaximum};repo.recordPlan(plan);repo.recordAuthorization({...authorization,authorizedAt:at});repo.startRun({schemaVersion:"1.0",runId:"run",planId:plan.planId,authorizationId:authorization.authorizationId,state:"RUNNING",cycle:at,startedAt:at,members:ready.map(x=>({...x,state:"READY"}))});const runs=[];for(let i=0;i<costs.length;i++){const child=createBoundedChildAuthorityBinding({parentAuthorization:authorization,member:ready[i],childAuthorizationId:`child-${i}`,childAuthorizationDigest:String(i+1).repeat(64),expiresAt:expiry});repo.recordChildAuthority(child);repo.updateMember("run",{...ready[i],state:"WAITING_FOR_PROVIDER",providerTaskId:`task-${i}`,actualSpendUsd:costs[i]});runs.push({runId:`execution-${i}`,planId:`source-plan-${i}`,status:"COMPLETED",actualSpendUsd:costs[i],tasks:[{providerTaskId:`task-${i}`,outcome:"COMPLETED",actualCostUsd:costs[i]}]})}const member=ready[costs.length],authority=createNeutralParentAuthorityInput({parentAuthorization:authorization,plan,member}),request={createdAt:at,neutralParentAuthority:authority,plan:{spentTodayUsd:snapshot}},resolver=createBoundedSpendProgressionResolver({boundedRepository:repo,executionRepository:{getAll:async()=>structuredClone(runs)}});return{root,repo,ready,plan,authorization,member,authority,request,resolver,current,runs};}
async function close(x){x.repo.close();await rm(x.root,{recursive:true,force:true,maxRetries:5,retryDelay:20})}
for(const spec of[{costs:[.001],expected:.001},{costs:[.001,.001],expected:.002},{snapshot:.0065,costs:[.001],expected:.0075},{snapshot:.0065,costs:[.001,.001],expected:.0085}]){const x=await fixture(spec);try{const value=await x.resolver({request:x.request,operation:"PRODUCTS"});eq(value.attributableSpendUsd,spec.costs.reduce((a,b)=>a+b,0));eq(value.expectedCurrentSpendUsd,spec.expected);eq(value.runId,"run")}finally{await close(x)}}
const x=await fixture({costs:[.001]});try{const progression=await x.resolver({request:x.request,operation:"PRODUCTS"}),plan={schemaVersion:"1.0",planId:"source",policy:{enabled:true,automaticPaidRetries:0,maxPaidTasksPerRun:1,maxSpendPerRunUsd:.001,maxSpendPerDayUsd:.025},spentTodayUsd:0,approvedTaskCount:1,estimatedApprovedSpendUsd:.001,decisions:[{candidateId:"c",decision:"APPROVED",estimatedCostUsd:.001,execution:{kind:"PRODUCTS"}}]},make=current=>new ControlledAcquisitionExecutor({runLock:{runExclusive:async fn=>({status:"ACQUIRED",result:await fn()})},ledgerRepository:{findByPlanId:async()=>null,append:async run=>({status:"RECORDED",run})},transport:{execute:async()=>({costUsd:.001,providerTaskId:"new-task"})},currentDaySpendResolver:async()=>current,now:()=>at,runId:()=>"execution"});eq((await make(.001).execute(plan,{spendProgression:progression})).status,"COMPLETED");await assert.rejects(()=>make(.005).execute(plan,{spendProgression:progression}),/SNAPSHOT_DRIFT/);cases++;await assert.rejects(()=>make(.001).execute(plan,{spendProgression:{...progression,parentAuthorizationDigest:"x",expectedCurrentSpendUsd:.005}}),/SNAPSHOT_DRIFT/);cases++;await assert.rejects(()=>make(.025).execute(plan,{spendProgression:{...progression,expectedCurrentSpendUsd:.025,attributableSpendUsd:.025}}),/SNAPSHOT_DRIFT|DAILY_BUDGET/);cases++;await assert.rejects(()=>make(.001).execute({...plan,spentTodayUsd:0},{spendProgression:null}),/SNAPSHOT_DRIFT/);cases++;}finally{await close(x)}
for(const mutate of[value=>({...value,memberKey:"wrong"}),value=>({...value,boundedPlanId:"wrong"}),value=>({...value,parentAuthorizationDigest:"d".repeat(64)}),value=>({...value,sourceId:"DATAFORSEO_AMAZON"})]){const y=await fixture({costs:[.001]});try{await assert.rejects(()=>y.resolver({request:{...y.request,neutralParentAuthority:mutate(y.authority)},operation:"PRODUCTS"}));cases++}finally{await close(y)}}
const overMember=await fixture({costs:[.002]});try{await assert.rejects(()=>overMember.resolver({request:overMember.request,operation:"PRODUCTS"}),/MEMBER_CEILING/);cases++}finally{await close(overMember)}
const overParent=await fixture({parentMaximum:.001,costs:[.001]});try{await assert.rejects(()=>overParent.resolver({request:overParent.request,operation:"PRODUCTS"}),/PARENT_CEILING/);cases++}finally{await close(overParent)}
console.log(`Bounded spend progression tests passed: ${cases} cases.`);
