import assert from "node:assert/strict";
import {mkdtemp,readFile,rm,writeFile} from "node:fs/promises";
import {join} from "node:path";
import {tmpdir} from "node:os";
import {CANONICAL_ADMISSION_CONFIRMATION,CanonicalAdmissionExecutor,CanonicalAdmissionPrepareService,createCanonicalAdmissionAuthorization,FileCanonicalAdmissionAuthorizationRepository} from "../index.js";

const root=await mkdtemp(join(tmpdir(),"hardware-radar-e2q-"));
try{const binding={evidenceId:"dfev_fixture",historicalObservationId:"mer_hist_0123456789abcdef",atlasProductId:"ram_fixture",retailerId:"RETAILER-0002",provider:"DATAFORSEO",source:"DATAFORSEO_GOOGLE_SHOPPING",providerTaskId:"sellers-fixture",rawPayloadReference:"fixture:item:0",rightsProfileHash:"a".repeat(64),evidenceHash:"b".repeat(64),historicalObservationHash:"c".repeat(64)},assessment={schemaVersion:"1.0",assessmentType:"CANONICAL_OBSERVATION_ADMISSION",assessmentId:"mer_canassess_fixture",policyVersion:"DF004-E2P-1.0",candidateBinding:binding,historicalEligible:true,historicalAdmitted:true,canonicalEligible:true,canonicalAdmitted:false,reviewEligible:false,publicationEligible:false,publicationAuthority:false,reasons:[],blockers:[],mutationAuthorized:false,networkOperation:"NONE",paidTaskCreated:false,actualSpendUsd:0},statePath=join(root,"authorizations.json"),repository=new FileCanonicalAdmissionAuthorizationRepository({statePath,now:()=>"2026-08-30T12:05:00Z"});let current=structuredClone(assessment),assessCalls=0,admitCalls=0;const canonicalAdmissionService={assess:async({evidenceId})=>{assessCalls++;assert.equal(evidenceId,"dfev_fixture");return structuredClone(current);},admit:async({evidenceId,admittedBy})=>{admitCalls++;assert.equal(evidenceId,"dfev_fixture");assert.equal(admittedBy,"operator:execute");return {status:"CANONICAL_ADMITTED",observationId:"mer_obs_000000001"};}},prepare=new CanonicalAdmissionPrepareService({canonicalAdmissionService,authorizationRepository:repository,now:()=>"2026-08-30T12:00:00Z"});
 const authorization=await prepare.prepare({evidenceId:"dfev_fixture",requestedBy:"operator:prepare",reason:"Fixture candidate approved for explicit admission review."});assert.equal(authorization.authorizationType,"CANONICAL_OBSERVATION_ADMISSION");assert.equal(authorization.status,"PENDING_OPERATOR_APPROVAL");assert.equal(authorization.evidenceId,binding.evidenceId);assert.deepEqual(authorization.candidateBinding,binding);assert.match(authorization.candidateBindingDigest,/^[a-f0-9]{64}$/);assert.equal(authorization.singleUse,true);assert.equal(authorization.reviewApproved,false);assert.equal(authorization.publicationEligible,false);assert.equal(authorization.publicationAuthority,false);assert.equal(authorization.currentPriceAuthority,false);assert.equal(authorization.livePriceAuthority,false);assert.equal(authorization.publicPriceAuthority,false);assert.equal(authorization.networkOperation,"NONE");assert.equal(authorization.actualSpendUsd,0);assert.equal(Object.isFrozen(authorization),true);await assert.rejects(()=>prepare.prepare({evidenceId:"dfev_fixture",requestedBy:"operator",reason:"Substitution fixture.",retailerId:"RETAILER-9999"}),/CALLER_SUBSTITUTION_FORBIDDEN/);
 const exact=await prepare.prepare({evidenceId:"dfev_fixture",requestedBy:"operator:prepare",reason:"Fixture candidate approved for explicit admission review."});assert.deepEqual(exact,authorization);assert.equal(Object.keys(JSON.parse(await readFile(statePath,"utf8")).authorizations).length,1);
 const ineligible={...assessment,canonicalEligible:false,blockers:["FIXTURE_BLOCKED"]};await assert.rejects(()=>new CanonicalAdmissionPrepareService({canonicalAdmissionService:{assess:async()=>ineligible},authorizationRepository:repository,now:()=>"2026-08-30T12:00:00Z"}).prepare({evidenceId:"dfev_other",requestedBy:"operator",reason:"Invalid fixture."}),/NOT_AUTHORIZABLE/);
 const changed={...assessment,assessmentId:"mer_canassess_changed",candidateBinding:{...binding,retailerId:"RETAILER-9999"}},conflicting=createCanonicalAdmissionAuthorization({assessment:changed,requestedBy:"operator:prepare",reason:"Conflicting fixture.",preparedAt:"2026-08-30T12:00:00Z"});await assert.rejects(()=>repository.record(conflicting),/AUTHORIZATION_CONFLICT/);
 const executor=new CanonicalAdmissionExecutor({canonicalAdmissionService,authorizationRepository:repository,now:()=>"2026-08-30T12:05:00Z"});await assert.rejects(()=>executor.execute({authorizationId:authorization.authorizationId,executedBy:"operator:execute"}),/EXPLICIT_CONFIRMATION_REQUIRED/);await assert.rejects(()=>executor.execute({authorizationId:authorization.authorizationId,confirmation:CANONICAL_ADMISSION_CONFIRMATION,executedBy:"operator:execute",eligibility:{eligible:true}}),/CALLER_SUBSTITUTION_FORBIDDEN/);await assert.rejects(()=>executor.execute({authorizationId:"missing",confirmation:CANONICAL_ADMISSION_CONFIRMATION,executedBy:"operator:execute"}),/NOT_FOUND/);current={...assessment,candidateBinding:{...binding,providerTaskId:"substituted"}};await assert.rejects(()=>executor.execute({authorizationId:authorization.authorizationId,confirmation:CANONICAL_ADMISSION_CONFIRMATION,executedBy:"operator:execute"}),/BINDING_MISMATCH/);assert.equal(admitCalls,0);current=structuredClone(assessment);
 const expiredRepository=new FileCanonicalAdmissionAuthorizationRepository({statePath:join(root,"expired.json")}),expired=createCanonicalAdmissionAuthorization({assessment,requestedBy:"operator",reason:"Expiry fixture.",preparedAt:"2026-08-30T12:00:00Z",ttlMinutes:1});await expiredRepository.record(expired);await assert.rejects(()=>new CanonicalAdmissionExecutor({canonicalAdmissionService,authorizationRepository:expiredRepository,now:()=>"2026-08-30T12:01:00Z"}).execute({authorizationId:expired.authorizationId,confirmation:CANONICAL_ADMISSION_CONFIRMATION,executedBy:"operator:execute"}),/EXPIRED/);
 const malformedPath=join(root,"malformed.json");await writeFile(malformedPath,JSON.stringify({version:"1.0",authorizations:{bad:{authorizationId:"bad"}},byEvidence:{},consumptions:{}}));await assert.rejects(()=>new FileCanonicalAdmissionAuthorizationRepository({statePath:malformedPath}).getById("bad"),/STATE_INVALID/);
 const first=await executor.execute({authorizationId:authorization.authorizationId,confirmation:CANONICAL_ADMISSION_CONFIRMATION,executedBy:"operator:execute"});assert.equal(first.status,"CANONICAL_ADMITTED");assert.equal(first.canonicalAdmitted,true);assert.equal(first.reviewApproved,false);assert.equal(first.publicationEligible,false);assert.equal(first.publicationAuthority,false);assert.equal(first.currentPriceAuthority,false);assert.equal(first.livePriceAuthority,false);assert.equal(first.publicPriceAuthority,false);assert.equal(first.networkOperation,"NONE");assert.equal(first.actualSpendUsd,0);assert.equal(admitCalls,1);await assert.rejects(()=>repository.consume({authorizationId:authorization.authorizationId,candidateBindingDigest:"f".repeat(64),observationId:first.observationId,status:first.status}),/CONSUMPTION_CONFLICT/);const replay=await executor.execute({authorizationId:authorization.authorizationId,confirmation:CANONICAL_ADMISSION_CONFIRMATION,executedBy:"operator:execute"});assert.equal(replay.status,"ALREADY_CONSUMED");assert.equal(replay.observationId,first.observationId);assert.equal(replay.currentPriceAuthority,false);assert.equal(replay.livePriceAuthority,false);assert.equal(replay.publicPriceAuthority,false);assert.equal(admitCalls,1);assert.equal((await repository.getConsumption(authorization.authorizationId)).observationId,"mer_obs_000000001");assert.equal(assessCalls>=5,true);const prepareScript=await readFile(new URL("../../../scripts/mercury-canonical-admission-prepare.mjs",import.meta.url),"utf8"),executeScript=await readFile(new URL("../../../scripts/mercury-canonical-admission-execute.mjs",import.meta.url),"utf8");assert.match(prepareScript,/CanonicalAdmissionPrepareService/);assert.match(prepareScript,/NOT EXECUTED/);assert.match(executeScript,/CanonicalAdmissionExecutor/);assert.match(executeScript,/CANONICAL_ADMISSION_CONFIRMATION/);assert.doesNotMatch(prepareScript,/DataForSEO|fetch\(|https?:\/\//);assert.doesNotMatch(executeScript,/DataForSEO|fetch\(|https?:\/\//);
}finally{await rm(root,{recursive:true,force:true});}
console.log("Canonical admission operator governance tests passed (62 cases).");
