import assert from "node:assert/strict";
import {mkdtemp,readFile,rm,writeFile} from "node:fs/promises";
import {join} from "node:path";
import {tmpdir} from "node:os";
import {CANONICAL_ADMISSION_CONFIRMATION,CANONICAL_ADMISSION_SUPERSESSION_CONFIRMATION,CanonicalAdmissionExecutor,CanonicalAdmissionSupersessionService,createCanonicalAdmissionAuthorization,FileCanonicalAdmissionAuthorizationRepository} from "../index.js";

const root=await mkdtemp(join(tmpdir(),"hardware-radar-e2q1-"));
const binding=(overrides={})=>({evidenceId:"dfev_fixture",historicalObservationId:"mer_hist_fixture",atlasProductId:"ram_fixture",retailerId:"RETAILER-0002",provider:"DATAFORSEO",source:"DATAFORSEO_GOOGLE_SHOPPING",providerTaskId:"sellers-fixture",rawPayloadReference:"fixture:item:0",rightsProfileHash:"a".repeat(64),evidenceHash:"b".repeat(64),historicalObservationHash:"c".repeat(64),...overrides});
const assessment=(overrides={})=>({schemaVersion:"1.0",assessmentType:"CANONICAL_OBSERVATION_ADMISSION",assessmentId:"mer_canassess_fixture",policyVersion:"DF004-E2P-1.0",candidateBinding:binding(),historicalEligible:true,historicalAdmitted:true,canonicalEligible:true,canonicalAdmitted:false,reviewEligible:false,publicationEligible:false,publicationAuthority:false,reasons:[],blockers:[],mutationAuthorized:false,networkOperation:"NONE",paidTaskCreated:false,actualSpendUsd:0,...overrides});
const predecessor=(overrides={})=>({...createCanonicalAdmissionAuthorization({assessment:assessment(),requestedBy:"operator:original",reason:"Original operator review.",preparedAt:"2026-08-30T12:00:00Z",ttlMinutes:15}),...overrides});
const legacyState=authorization=>({version:"1.0",authorizations:{[authorization.authorizationId]:authorization},byEvidence:{[authorization.evidenceId]:authorization.authorizationId},consumptions:{}});
const save=async(file,value)=>writeFile(file,`${JSON.stringify(value,null,2)}\n`);
const service=({repository,current=assessment(),now="2026-08-30T12:20:00Z",calls={count:0}})=>new CanonicalAdmissionSupersessionService({authorizationRepository:repository,canonicalAdmissionService:{assess:async({evidenceId})=>{calls.count++;assert.equal(evidenceId,"dfev_fixture");return structuredClone(current);}},now:()=>now});
const request=(authorizationId,overrides={})=>({authorizationId,confirmation:CANONICAL_ADMISSION_SUPERSESSION_CONFIRMATION,requestedBy:"operator:successor",reason:"Prepare a fresh reviewable authorization after expiry.",...overrides});

try{
  const statePath=join(root,"legacy.json"),original=predecessor({authorizationId:"mer_canauth_952fbc71ad7acafe0abf0f66"}),originalBytes=`${JSON.stringify(legacyState(original),null,2)}\n`;await writeFile(statePath,originalBytes);let clock="2026-08-30T12:20:00Z",calls={count:0};const repository=new FileCanonicalAdmissionAuthorizationRepository({statePath,now:()=>clock});
  assert.deepEqual(await repository.getById(original.authorizationId),original);assert.equal(await readFile(statePath,"utf8"),originalBytes,"legacy reads must not eagerly rewrite state");
  const first=await service({repository,calls}).supersede(request(original.authorizationId));assert.equal(first.status,"SUPERSEDED");assert.notEqual(first.authorization.authorizationId,original.authorizationId);assert.equal(first.authorization.schemaVersion,"1.1");assert.equal(first.authorization.lineage.rootAuthorizationId,original.authorizationId);assert.equal(first.authorization.lineage.predecessorAuthorizationId,original.authorizationId);assert.equal(first.authorization.lineage.generation,1);assert.equal(first.authorization.lineage.bindingChange,"EXACT_BINDING");assert.equal(first.authorization.lineage.predecessorAssessmentId,original.assessmentId);assert.equal(first.authorization.lineage.predecessorCandidateBindingDigest,original.candidateBindingDigest);assert.equal(first.authorization.expiresAt,"2026-08-30T12:35:00.000Z");assert.equal(calls.count,1);assert.deepEqual(await repository.getById(original.authorizationId),original);assert.equal(await repository.getConsumption(original.authorizationId),null);assert.deepEqual((await repository.getActiveByEvidence(original.evidenceId)),first.authorization);assert.equal(first.authorization.reviewApproved,false);assert.equal(first.authorization.publicationEligible,false);assert.equal(first.authorization.publicationAuthority,false);assert.equal(first.authorization.currentPriceAuthority,false);assert.equal(first.authorization.livePriceAuthority,false);assert.equal(first.authorization.publicPriceAuthority,false);assert.equal(first.authorization.networkOperation,"NONE");assert.equal(first.authorization.actualSpendUsd,0);
  const stored=JSON.parse(await readFile(statePath,"utf8"));assert.deepEqual(stored.authorizations[original.authorizationId],original,"predecessor object must remain unchanged");assert.equal(stored.byEvidence[original.evidenceId],original.authorizationId,"legacy root index must retain its historical meaning");assert.equal(stored.activeAuthorizationByIntent[`CANONICAL_OBSERVATION_ADMISSION:${original.evidenceId}`],first.authorization.authorizationId);assert.equal(Object.keys(stored.supersessions).length,1);assert.equal(Object.keys(stored.authorizations).length,2);
  clock="2026-08-30T12:21:00Z";const replay=await service({repository,now:clock}).supersede(request(original.authorizationId));assert.equal(replay.status,"ALREADY_SUPERSEDED");assert.deepEqual(replay.authorization,first.authorization);assert.equal(Object.keys(JSON.parse(await readFile(statePath,"utf8")).authorizations).length,2);await assert.rejects(()=>service({repository,now:clock}).supersede(request(original.authorizationId,{reason:"A conflicting successor request."})),/SUPERSESSION_CONFLICT/);

  const changedPath=join(root,"changed.json"),changedOriginal=predecessor();await save(changedPath,legacyState(changedOriginal));const changedRepository=new FileCanonicalAdmissionAuthorizationRepository({statePath:changedPath,now:()=>"2026-08-30T12:20:00Z"}),changedAssessment=assessment({assessmentId:"mer_canassess_changed",candidateBinding:binding({rightsProfileHash:"d".repeat(64)})}),changed=await service({repository:changedRepository,current:changedAssessment}).supersede(request(changedOriginal.authorizationId));assert.equal(changed.authorization.lineage.bindingChange,"CHANGED_BINDING");assert.equal(changed.supersession.predecessorBindingDigest,changedOriginal.candidateBindingDigest);assert.equal(changed.supersession.successorBindingDigest,changed.authorization.candidateBindingDigest);assert.equal(changed.supersession.predecessorAssessmentId,changedOriginal.assessmentId);assert.equal(changed.supersession.successorAssessmentId,changedAssessment.assessmentId);

  const activePath=join(root,"active.json"),active=predecessor();await save(activePath,legacyState(active));await assert.rejects(()=>service({repository:new FileCanonicalAdmissionAuthorizationRepository({statePath:activePath,now:()=>"2026-08-30T12:10:00Z"}),now:"2026-08-30T12:10:00Z"}).supersede(request(active.authorizationId)),/NOT_EXPIRED/);
  const consumedPath=join(root,"consumed.json"),consumed=predecessor();await save(consumedPath,legacyState(consumed));const consumedRepository=new FileCanonicalAdmissionAuthorizationRepository({statePath:consumedPath,now:()=>"2026-08-30T12:20:00Z"});await consumedRepository.consume({authorizationId:consumed.authorizationId,candidateBindingDigest:consumed.candidateBindingDigest,observationId:"mer_obs_consumed",status:"CANONICAL_ADMITTED"});await assert.rejects(()=>service({repository:consumedRepository}).supersede(request(consumed.authorizationId)),/CONSUMED/);
  const blockedPath=join(root,"blocked.json"),blocked=predecessor();await save(blockedPath,legacyState(blocked));const blockedRepository=new FileCanonicalAdmissionAuthorizationRepository({statePath:blockedPath,now:()=>"2026-08-30T12:20:00Z"});await assert.rejects(()=>service({repository:blockedRepository,current:assessment({canonicalEligible:false,blockers:["CURRENT_POLICY_BLOCKED"]})}).supersede(request(blocked.authorizationId)),/NOT_AUTHORIZABLE/);await assert.rejects(()=>service({repository:blockedRepository,current:{assessmentType:"CANONICAL_OBSERVATION_ADMISSION"}}).supersede(request(blocked.authorizationId)),/NOT_AUTHORIZABLE/);await assert.rejects(()=>service({repository:blockedRepository}).supersede(request(blocked.authorizationId,{confirmation:"WRONG"})),/EXPLICIT_CONFIRMATION_REQUIRED/);

  clock="2026-08-30T12:36:00Z";const second=await service({repository,now:clock}).supersede(request(first.authorization.authorizationId,{reason:"Second linear successor after another expiry."}));assert.equal(second.authorization.lineage.generation,2);assert.equal(second.authorization.lineage.rootAuthorizationId,original.authorizationId);const linear=JSON.parse(await readFile(statePath,"utf8"));assert.equal(Object.keys(linear.authorizations).length,3);assert.equal(Object.keys(linear.supersessions).length,2);assert.equal(linear.activeAuthorizationByIntent[`CANONICAL_OBSERVATION_ADMISSION:${original.evidenceId}`],second.authorization.authorizationId);

  const malformedPath=join(root,"branching.json");const malformed=structuredClone(linear),event=structuredClone(Object.values(malformed.supersessions)[0]);event.supersessionId="mer_cansup_branch";event.successorAuthorizationId=second.authorization.authorizationId;malformed.supersessions[event.supersessionId]=event;await save(malformedPath,malformed);await assert.rejects(()=>new FileCanonicalAdmissionAuthorizationRepository({statePath:malformedPath}).getById(original.authorizationId),/STATE_INVALID/);

  const concurrentPath=join(root,"concurrent.json"),concurrentOriginal=predecessor();await save(concurrentPath,legacyState(concurrentOriginal));const repositoryA=new FileCanonicalAdmissionAuthorizationRepository({statePath:concurrentPath,now:()=>"2026-08-30T12:20:00Z"}),repositoryB=new FileCanonicalAdmissionAuthorizationRepository({statePath:concurrentPath,now:()=>"2026-08-30T12:20:00Z"}),attempts=await Promise.allSettled([service({repository:repositoryA}).supersede(request(concurrentOriginal.authorizationId)),service({repository:repositoryB}).supersede(request(concurrentOriginal.authorizationId))]);assert.equal(attempts.some(result=>result.status==="fulfilled"),true);const concurrentState=JSON.parse(await readFile(concurrentPath,"utf8"));assert.equal(Object.keys(concurrentState.supersessions).length,1);assert.equal(Object.keys(concurrentState.authorizations).length,2);

  const executePath=join(root,"execute.json"),executeOriginal=predecessor();await save(executePath,legacyState(executeOriginal));const executeRepository=new FileCanonicalAdmissionAuthorizationRepository({statePath:executePath,now:()=>"2026-08-30T12:20:00Z"}),prepared=await service({repository:executeRepository}).supersede(request(executeOriginal.authorizationId));let admissions=0;const executor=new CanonicalAdmissionExecutor({authorizationRepository:executeRepository,canonicalAdmissionService:{assess:async()=>assessment(),admit:async()=>{admissions++;return {status:"CANONICAL_ADMITTED",observationId:"mer_obs_fixture"};}},now:()=>"2026-08-30T12:21:00Z"});await assert.rejects(()=>executor.execute({authorizationId:prepared.authorization.authorizationId,confirmation:"WRONG",executedBy:"operator:execute"}),/EXPLICIT_CONFIRMATION_REQUIRED/);const executed=await executor.execute({authorizationId:prepared.authorization.authorizationId,confirmation:CANONICAL_ADMISSION_CONFIRMATION,executedBy:"operator:execute"});assert.equal(executed.status,"CANONICAL_ADMITTED");assert.equal(executed.reviewApproved,false);assert.equal(executed.publicationAuthority,false);assert.equal(executed.currentPriceAuthority,false);assert.equal(admissions,1);

  const script=await readFile(new URL("../../../scripts/mercury-canonical-admission-supersede.mjs",import.meta.url),"utf8");assert.match(script,/SUPERSEDE-EXPIRED-CANONICAL-AUTHORIZATION|CANONICAL_ADMISSION_SUPERSESSION_CONFIRMATION/);assert.match(script,/NOT EXECUTED/);assert.match(script,/CHANGED_BINDING|Binding relationship/);assert.doesNotMatch(script,/DataForSEO|fetch\(|https?:\/\//);
}finally{await rm(root,{recursive:true,force:true});}
console.log("Canonical admission authorization supersession tests passed (74 cases).");
