import assert from "node:assert/strict";
import {mkdtemp,readFile,rm,writeFile} from "node:fs/promises";
import {tmpdir} from "node:os";
import {join} from "node:path";
import {CertifiedMercuryOperationsExporter,createHistoricalObservation,writeCertifiedMercuryOperationsArtifact} from "../index.js";

const asOf="2026-08-25T12:00:00Z",productA={identity:{atlasProductId:"product_a",displayName:"Product A",brand:"Fixture",manufacturerPartNumber:"A",productType:"ram"},privateSecret:"must-not-export"},productB={identity:{atlasProductId:"product_b",displayName:"Product B",brand:"Fixture",manufacturerPartNumber:"B",productType:"ram"}},history=createHistoricalObservation({observationId:"mer_hist_aaaaaaaaaaaaaaaa",atlasProductId:"product_a",retailerId:"RETAILER-0002",marketplace:"example.com",observationTime:"2026-08-24T10:00:00Z",admittedAt:"2026-08-24T11:00:00Z",market:{sellerName:"Example",sourceUrl:"https://example.com/item",basePrice:10,totalPrice:10,shipping:null,tax:null,currency:"USD",condition:null,availability:"in_stock"},provenance:{retainedEvidenceId:"evidence-a",provider:"DATAFORSEO",source:"DATAFORSEO_GOOGLE_SHOPPING",rawPayloadReference:"fixture:export",acquisition:{productsTaskId:"products",productInfoTaskId:"info",sellersTaskId:"sellers"},identityReview:{productDecisionId:"product",productRemediationId:null,merchantDecisionId:"merchant",merchantRemediationId:null}},admittedBy:"operator:test",idempotencyKey:"fixture:export"});
const calls={},owner=(name,value,method="getAll")=>({[method]:async()=>{calls[name]=(calls[name]??0)+1;return structuredClone(value);}}),context={refreshPlans:[],authorizations:[],executionRuns:[],consumptionState:{schemaVersion:"1.0",consumed:[]},refreshResults:[],identityReuseAssessments:[]};
const dependencies=(reverse=false)=>({productRepository:owner("products",reverse?[productA,productB]:[productB,productA]),retailerRepository:owner("retailers",[]),evidenceRepository:owner("evidence",[]),historicalRepository:owner("history",[history]),identityDecisionRepository:{...owner("decisions",[]),getAllRemediations:async()=>{calls.remediations=(calls.remediations??0)+1;return[];}},canonicalObservationRepository:owner("observations",[{observationId:"mer_obs_fixture",atlasProductId:"product_a"}]),reviewRepository:owner("reviews",{reviewDecisionId:"review-fixture",observationId:"mer_obs_fixture",decision:"REVIEWED"},"getEffectiveDecision"),publicationRepository:owner("publications",{publicationDecisionId:"publication-fixture",observationId:"mer_obs_fixture",action:"WITHDRAW"},"getEffectiveDecision"),cadencePolicyRepository:owner("cadence",[],"getAllPolicies"),operationalContextProvider:{load:async input=>{calls.context=(calls.context??0)+1;assert.equal(input.asOf,asOf);return structuredClone(context);}}});
let bytes="";const artifactWriter=async(path,projection)=>{bytes=`${JSON.stringify(projection,null,2)}\n`;return path;},source=dependencies(),before=structuredClone({productA,productB,history,context}),first=await new CertifiedMercuryOperationsExporter({...source,artifactWriter}).export({asOf,outputPath:"fixture.json"}),firstBytes=bytes;bytes="";const second=await new CertifiedMercuryOperationsExporter({...dependencies(true),artifactWriter}).export({asOf,outputPath:"fixture.json"});
assert.equal(first.status,"EXPORTED");assert.equal(first.artifactPath,"fixture.json");assert.equal(first.projection.asOf,asOf);assert.equal(firstBytes,bytes);assert.deepEqual(first.projection,second.projection);assert.deepEqual(first.projection.products.map(x=>x.atlasProduct.atlasProductId),["product_a","product_b"]);assert.equal(first.projection.products[0].history.valueSemantics,"HISTORICAL_OBSERVATION");assert.equal(first.projection.products[0].history.currentPrice,false);assert.equal(first.projection.semantics.publicationAuthority,false);assert.equal(first.projection.products[0].history.latestTotalPrice,10);assert.equal(first.projection.products[1].history.observationCount,0);assert.equal(first.projection.products[0].promotion.state,"NOT_ASSESSED");assert.equal(first.sourceStateModified,false);assert.equal(first.networkOperation,"NONE");assert.equal(first.paidTaskCreated,false);assert.equal(first.actualSpendUsd,0);assert.deepEqual({productA,productB,history,context},before);for(const name of ["products","retailers","evidence","history","decisions","remediations","observations","cadence","context"])assert.ok(calls[name]>=1,`${name} owner used`);assert.doesNotMatch(firstBytes,/must-not-export/);assert.doesNotMatch(firstBytes,/password|apiKey|recipientAddress/i);
const emptyDependencies=dependencies();emptyDependencies.productRepository=owner("empty-products",[]);emptyDependencies.historicalRepository=owner("empty-history",[]);emptyDependencies.canonicalObservationRepository=owner("empty-observations",[]);let emptyProjection;emptyDependencies.artifactWriter=async(path,projection)=>{emptyProjection=projection;return path;};await new CertifiedMercuryOperationsExporter(emptyDependencies).export({asOf,outputPath:"empty.json"});assert.deepEqual(emptyProjection.products,[]);
assert.throws(()=>new CertifiedMercuryOperationsExporter({...dependencies(),productRepository:null}),/PRODUCT_OWNER_REQUIRED/);await assert.rejects(()=>new CertifiedMercuryOperationsExporter({...dependencies(),artifactWriter}).export({asOf:"ambient-time-not-allowed",outputPath:"x"}),/AS_OF_REQUIRED/);const malformed=dependencies();malformed.productRepository=owner("malformed",[{identity:{}}]);await assert.rejects(()=>new CertifiedMercuryOperationsExporter({...malformed,artifactWriter}).export({asOf,outputPath:"x"}),/ATLAS_INVALID/);const conflicting=dependencies();conflicting.productRepository=owner("conflicting",[productA,productA]);await assert.rejects(()=>new CertifiedMercuryOperationsExporter({...conflicting,artifactWriter}).export({asOf,outputPath:"x"}),/ATLAS_INVALID|ATLAS_ID_CONFLICT/);const badContext=dependencies();badContext.operationalContextProvider={load:async()=>({})};await assert.rejects(()=>new CertifiedMercuryOperationsExporter({...badContext,artifactWriter}).export({asOf,outputPath:"x"}),/CONTEXT_STATE_INVALID/);
const directory=await mkdtemp(join(tmpdir(),"fm008-"));try{const target=join(directory,"projection.json"),projection=first.projection;await writeCertifiedMercuryOperationsArtifact(target,projection);assert.deepEqual(JSON.parse(await readFile(target,"utf8")),projection);await writeFile(target,"ORIGINAL","utf8");const failingFs={mkdir:async()=>{},writeFile:async(file,value)=>writeFile(file,value),rename:async()=>{throw new Error("WRITE_FAILURE");},rm:async file=>rm(file,{force:true})};await assert.rejects(()=>writeCertifiedMercuryOperationsArtifact(target,projection,{fileSystem:failingFs,processId:123}),/WRITE_FAILURE/);assert.equal(await readFile(target,"utf8"),"ORIGINAL");await assert.rejects(()=>readFile(`${target}.tmp-123`,"utf8"),error=>error.code==="ENOENT");}finally{await rm(directory,{recursive:true,force:true});}
console.log("Certified Mercury operations exporter tests passed (24 cases).");
