import assert from "node:assert/strict";
import {createCertifiedMercuryCohortOperationsProjection} from "../index.js";
const asOf="2026-09-15T12:00:00.000Z",ids=["success","pending","review","unresolved","variant","multiple","systemic"];
const atlasProducts=ids.map(id=>({identity:{atlasProductId:`ram_${id}`,displayName:`${id} RAM`,manufacturerPartNumber:`MPN-${id}`}}));
const member=(id,state,outcome,extra={})=>({memberKey:id,atlasProductId:`ram_${id}`,source:"DATAFORSEO_AMAZON",operation:"PRODUCTS",state,outcome,...extra});
const members=[member("success","COMPLETED","STRONG_UNIQUE_ASIN"),member("pending","WAITING_FOR_PROVIDER",null,{providerTaskId:"task-pending",progression:{status:"STILL_PENDING",attemptCount:2,bounded:true}}),member("review","COMPLETED","INSUFFICIENT_ASIN_EVIDENCE",{assessmentId:"h051",providerResultId:"result-review",reviewEligibility:{eligible:true,owner:"H052_OPERATOR_REVIEW",reviewType:"H052",permittedDecisions:["ACCEPT","REJECT"],evidenceReferences:["h051","result-review"]}}),member("unresolved","COMPLETED","INSUFFICIENT_ASIN_EVIDENCE",{reviewEligibility:{eligible:false}}),member("variant","COMPLETED","ASIN_VARIANT_CONFLICT"),member("multiple","COMPLETED","MULTIPLE_COMPATIBLE_ASINS"),member("systemic","FAILED",null,{systemicFailure:true,systemicFailureReason:"LINEAGE_CONFLICT"})];
const cohort={cohortType:"PRODUCTS_IDENTITY_DISCOVERY",planId:"plan-1",runId:"run-1",cycle:"2026-09-15",requestedMembers:ids,readyCount:7,blockedCount:0,authorizationState:"CONSUMED",runState:"STOPPED",members,progression:{status:"SYSTEMIC_STOP",completedCount:1},automaticRetryCount:0,cost:{authorizedMaximumSpendUsd:.01,actualSpendUsd:.0065,currentUtcDaySpendUsd:.0065,dailyCeilingUsd:.025,remainingDailyCapacityUsd:.0185},safety:{lineageConflict:true},systemicFailure:true,systemicFailureReason:"LINEAGE_CONFLICT"};
const input=()=>({asOf,atlasProducts:structuredClone(atlasProducts),cohorts:[structuredClone(cohort)]});
const result=createCertifiedMercuryCohortOperationsProjection(input()),again=createCertifiedMercuryCohortOperationsProjection(input()),view=result.cohorts[0];
assert.deepEqual(result,again);assert.equal(Object.isFrozen(result),true);assert.equal(view.safety.systemicFailure,true);assert.equal(view.members[0].classification,"ROUTINE_SUCCESS");
const isolated={...cohort,systemicFailure:false,systemicFailureReason:null,safety:{},members};
const normal=createCertifiedMercuryCohortOperationsProjection({asOf,atlasProducts,cohorts:[isolated]}).cohorts[0],by=id=>normal.members.find(x=>x.memberKey===id);
assert.equal(by("success").classification,"ROUTINE_SUCCESS");
assert.equal(by("pending").classification,"PENDING_ROUTINE_WORK");assert.equal(by("pending").progression.status,"STILL_PENDING");
assert.equal(by("review").classification,"GOVERNED_REVIEW_AVAILABLE");assert.deepEqual(by("review").review.permittedDecisions,["ACCEPT","REJECT"]);assert.equal(by("review").review.actionExecutable,false);
assert.equal(by("unresolved").classification,"SAFELY_UNRESOLVED");assert.equal(by("unresolved").unresolvedIsLegitimate,true);
assert.equal(by("variant").classification,"EXPECTED_DOMAIN_EXCEPTION");assert.equal(by("variant").review.eligible,false);
assert.equal(by("multiple").classification,"EXPECTED_DOMAIN_EXCEPTION");assert.equal(by("multiple").review.eligible,false);
assert.equal(by("systemic").classification,"SYSTEMIC_ATTENTION");assert.equal(by("systemic").systemicFailureReason,"LINEAGE_CONFLICT");
assert.deepEqual(normal.cost,{authorizedMaximumSpendUsd:.01,actualSpendUsd:.0065,currentUtcDaySpendUsd:.0065,dailyCeilingUsd:.025,remainingDailyCapacityUsd:.0185});
assert.equal(normal.safety.lineageConflict,false);assert.equal(normal.safety.downstreamAuthorityLeakage,false);
assert.deepEqual(by("success").downstreamAuthority,{sellers:false,history:false,canonical:false,reviewMutation:false,publication:false,currentPrice:false,cheapest:false,picks:false});
assert.equal(by("success").atlasProduct.displayName,"success RAM");assert.equal(by("success").atlasProduct.manufacturerPartNumber,"MPN-success");
const repeat=createCertifiedMercuryCohortOperationsProjection({asOf,atlasProducts:[atlasProducts[0]],cohorts:[{cohortType:"REPEAT_OBSERVATION",planId:"repeat-plan",runId:"repeat-run",cycle:"cycle-2",requestedMembers:["success"],members:[member("success","COMPLETED","ADMITTED",{operation:"AMAZON_SELLERS",repeatObservation:{evidenceCount:1,historicalObservationCount:1}})],cost:{actualSpendUsd:.0015}}]}).cohorts[0];assert.equal(repeat.members[0].classification,"ROUTINE_SUCCESS");assert.deepEqual(repeat.members[0].repeatObservation,{evidenceCount:1,historicalObservationCount:1});
assert.deepEqual(createCertifiedMercuryCohortOperationsProjection({asOf,atlasProducts:[],cohorts:[]}).cohorts,[]);
const ordinary=createCertifiedMercuryCohortOperationsProjection({asOf,atlasProducts:[atlasProducts[0]],cohorts:[{cohortType:"PRODUCTS_IDENTITY_DISCOVERY",planId:"ordinary",requestedMembers:["success"],members:[member("success","COMPLETED","STRONG_UNIQUE_ASIN")]}]}).cohorts[0];assert.equal(ordinary.membership.exceptions,0);assert.equal(ordinary.safety.systemicFailure,false);
assert.equal(normal.membership.exceptions,5);assert.equal(normal.membership.pending,1);
assert.throws(()=>createCertifiedMercuryCohortOperationsProjection({asOf,atlasProducts,cohorts:[{...isolated,members:[{...members[0],atlasProductId:"ram_missing"}]}]}),/ATLAS_BINDING/);
assert.throws(()=>createCertifiedMercuryCohortOperationsProjection({asOf,atlasProducts,cohorts:[{...isolated,members:[{...members[2],reviewEligibility:{eligible:true,reviewType:"H052"}}]}]}),/REVIEW_OWNER/);
console.log("Certified Mercury cohort operations projection tests passed (15 certification groups).");
