import assert from "node:assert/strict";
import { mkdtemp, readFile, rm, writeFile } from "node:fs/promises";
import { join } from "node:path";
import { tmpdir } from "node:os";
import { ProductRepository, RetailerRepository } from "../../atlas/index.js";
import { classifyObservationStorage, CURATED_RAM_OFFER_CONFIRMATION, CuratedRamOfferAssessmentService, CuratedRamOfferExecutor, CuratedRamOfferPrepareService, FileCuratedRamOfferAuthorizationRepository, FileObservationAcceptanceRepository, RIGHTS_STATES, SourceRightsRegistry, provisionalObservation } from "../index.js";

const root = await mkdtemp(join(tmpdir(), "hardware-radar-curated-ram-")), readJson = async resource => JSON.parse(await readFile(resource, "utf8"));
try {
  const productRepository = new ProductRepository({ readJson }), retailerRepository = new RetailerRepository({ readJson });
  const allowed = RIGHTS_STATES.ALLOWED, profile = { sourceId: "FIXTURE_CURATED_RAM", schemaVersion: "1.0", acquisition: { api: RIGHTS_STATES.NOT_APPLICABLE, manual: allowed, import: RIGHTS_STATES.NOT_APPLICABLE }, live: { currentObservation: allowed, publicDisplay: allowed, comparison: allowed }, retention: { storageClass: "DURABLE", contentTtlMs: null, historical: allowed, durableAuditMetadata: allowed }, derivation: { analytics: allowed, historicalAnalytics: allowed }, presentation: { attribution: RIGHTS_STATES.NOT_APPLICABLE }, status: "SYNTHETIC_TEST_POLICY" }, profiles = { FIXTURE_CURATED_RAM: profile }, rightsRegistry = new SourceRightsRegistry({ sourceProfiles: profiles });
  const assessmentService = new CuratedRamOfferAssessmentService({ productRepository, retailerRepository, rightsRegistry }), observationPath = join(root, "observations.json"), acceptanceRepository = new FileObservationAcceptanceRepository({ statePath: observationPath, environment: "development", now: () => "2026-09-01T12:06:00Z", retentionPolicy: observation => classifyObservationStorage(observation, { registry: rightsRegistry }) }), authorizationRepository = new FileCuratedRamOfferAuthorizationRepository({ statePath: join(root, "authorizations.json"), now: () => "2026-09-01T12:06:00Z" });
  const candidate = { atlasProductId: "ram_corsair_cmk32gx5m2b6000z30", retailerId: "RETAILER-0002", sourceRightsProfileId: "FIXTURE_CURATED_RAM", sourceUrl: "https://platinummicro.com/products/example", marketplace: "platinummicro.com", observedAt: "2026-09-01T12:00:00Z", listedPrice: 588.99, currency: "USD", shipping: { known: false, amount: null, currency: null }, availability: "IN_STOCK", condition: "NEW", offerClass: "STANDALONE", priceClass: "UNCONDITIONAL", operatorSourceReference: "fixture:curated:one", requestedBy: "operator:fixture" };
  const prepare = new CuratedRamOfferPrepareService({ assessmentService, authorizationRepository, now: () => "2026-09-01T12:01:00Z" }), authorization = await prepare.prepare({ candidate }); assert.equal((await acceptanceRepository.getAll()).length, 0); assert.equal(authorization.candidateBinding.condition, "NEW"); assert.equal(authorization.actualSpendUsd, 0); assert.deepEqual(await prepare.prepare({ candidate }), authorization);
  const executor = new CuratedRamOfferExecutor({ assessmentService, authorizationRepository, acceptanceRepository, productRepository, retailerRepository, rightsRegistry, now: () => "2026-09-01T12:02:00Z" }); await assert.rejects(() => executor.execute({ authorizationId: authorization.authorizationId, confirmation: "WRONG", executedBy: candidate.requestedBy }), /CONFIRMATION/); await assert.rejects(() => executor.execute({ authorizationId: authorization.authorizationId, confirmation: CURATED_RAM_OFFER_CONFIRMATION, executedBy: "operator:other" }), /OPERATOR_SUBSTITUTION/);
  const result = await executor.execute({ authorizationId: authorization.authorizationId, confirmation: CURATED_RAM_OFFER_CONFIRMATION, executedBy: candidate.requestedBy }); assert.equal(result.status, "CURATED_RAM_OFFER_RECORDED"); assert.match(result.observationId, /^mer_obs_/); const stored = await acceptanceRepository.getByIdReadOnly(result.observationId); assert.equal(stored.offer.condition, "NEW"); assert.deepEqual(stored.offer.shipping, { costKnown: false, cost: null, currency: null, notes: null }); assert.equal(stored.offer.bundle.status, "STANDALONE"); assert.equal(stored.offer.conditionalPrice.status, "UNCONDITIONAL"); assert.equal(stored.compliance.licenseContext, "FIXTURE_CURATED_RAM"); assert.equal(stored.provenance.acquisition.retrievedBy, candidate.requestedBy); assert.equal(stored.provenance.acquisition.rawPayloadReference, candidate.operatorSourceReference); assert.equal((await executor.execute({ authorizationId: authorization.authorizationId, confirmation: CURATED_RAM_OFFER_CONFIRMATION, executedBy: candidate.requestedBy })).status, "ALREADY_CONSUMED"); assert.equal((await acceptanceRepository.getAll()).length, 1);
  for (const condition of [undefined, "", "OPEN_BOX", "MANUFACTURER_REFURBISHED", "SELLER_REFURBISHED", "USED"]) { const assessed = await assessmentService.assess({ ...candidate, operatorSourceReference: `fixture:condition:${condition ?? "missing"}`, condition }); assert.equal(assessed.eligible, true); assert.equal(assessed.binding.condition, condition?.trim() ? condition : "UNKNOWN"); const retailer = await retailerRepository.getById(candidate.retailerId), observation = provisionalObservation(assessed.binding, retailer, "2026-09-01T12:01:00Z"); assert.equal(observation.offer.condition, condition?.trim() ? condition : "UNKNOWN"); }
  for (const shipping of [{ known: true, amount: 0, currency: "USD" }, { known: true, amount: 12.5, currency: "USD" }, { known: false, amount: null, currency: null }]) { const assessed = await assessmentService.assess({ ...candidate, operatorSourceReference: `fixture:shipping:${shipping.amount}`, shipping }); assert.equal(assessed.eligible, true); const observation = provisionalObservation(assessed.binding, await retailerRepository.getById(candidate.retailerId), "2026-09-01T12:01:00Z"); assert.equal(observation.offer.shipping.costKnown, shipping.known); assert.equal(observation.offer.shipping.cost, shipping.amount); }
  assert.equal((await assessmentService.assess({ ...candidate, shipping: { known: false, amount: 0, currency: "USD" } })).eligible, false);
  for (const [offerClass, priceClass] of [["BUNDLE", "UNCONDITIONAL"], ["STANDALONE", "CONDITIONAL"]]) { const assessed = await assessmentService.assess({ ...candidate, operatorSourceReference: `fixture:${offerClass}:${priceClass}`, offerClass, priceClass }); assert.equal(assessed.eligible, true); const observation = provisionalObservation(assessed.binding, await retailerRepository.getById(candidate.retailerId), "2026-09-01T12:01:00Z"); assert.equal(observation.offer.bundle.isBundle, offerClass === "BUNDLE"); assert.equal(observation.offer.conditionalPrice.isConditional, priceClass === "CONDITIONAL"); }
  assert.equal((await assessmentService.assess({ ...candidate, offerClass: "UNKNOWN" })).eligible, false); assert.equal((await assessmentService.assess({ ...candidate, priceClass: "UNKNOWN" })).eligible, false);
  const missingRights = new CuratedRamOfferAssessmentService({ productRepository, retailerRepository, rightsRegistry: new SourceRightsRegistry({ sourceProfiles: {} }) }); assert.ok((await missingRights.assess(candidate)).blockers.includes("CURATED_RAM_RIGHTS_PROFILE_MISSING")); for (const state of [RIGHTS_STATES.BLOCKED, RIGHTS_STATES.CONDITIONAL, RIGHTS_STATES.CLARIFICATION_REQUIRED]) { const blockedProfile = structuredClone(profile); blockedProfile.live.publicDisplay = state; const blocked = await new CuratedRamOfferAssessmentService({ productRepository, retailerRepository, rightsRegistry: new SourceRightsRegistry({ sourceProfiles: { FIXTURE_CURATED_RAM: blockedProfile } }) }).assess(candidate); assert.ok(blocked.blockers.includes("CURATED_RAM_RIGHTS_NOT_EXPLICITLY_ALLOWED")); }
  assert.equal((await assessmentService.assess({ ...candidate, currency: "CAD" })).eligible, false); assert.equal((await assessmentService.assess({ ...candidate, sourceUrl: "https://example.com/item" })).eligible, false); assert.equal((await assessmentService.assess({ ...candidate, retailerId: "RETAILER-9999" })).eligible, false); assert.equal((await assessmentService.assess({ ...candidate, atlasProductId: "ram_missing" })).eligible, false);
  const bundleAssessment = await assessmentService.assess({ ...candidate, operatorSourceReference: "fixture:affiliate", affiliate: true }); assert.equal(bundleAssessment.eligible, true);
  const expiredRepo = new FileCuratedRamOfferAuthorizationRepository({ statePath: join(root, "expired.json") }), expired = await new CuratedRamOfferPrepareService({ assessmentService, authorizationRepository: expiredRepo, now: () => "2026-09-01T12:01:00Z" }).prepare({ candidate: { ...candidate, operatorSourceReference: "fixture:expired" }, ttlMinutes: 1 }); await assert.rejects(() => new CuratedRamOfferExecutor({ assessmentService, authorizationRepository: expiredRepo, acceptanceRepository, productRepository, retailerRepository, rightsRegistry, now: () => "2026-09-01T12:20:00Z" }).execute({ authorizationId: expired.authorizationId, confirmation: CURATED_RAM_OFFER_CONFIRMATION, executedBy: candidate.requestedBy }), /EXPIRED/);
  await writeFile(join(root, "malformed.json"), '{"version":"1.0","authorizations":{"bad":{}},"byIntent":{},"consumptions":{}}\n'); await assert.rejects(() => new FileCuratedRamOfferAuthorizationRepository({ statePath: join(root, "malformed.json") }).getById("bad"), /STATE_INVALID/);
  for (const key of ["historicalAdmission", "canonicalAdmission", "reviewDecision", "currentMarketQualification", "publicationDecision", "currentPriceAuthority", "cheapestAuthority", "pickAuthority", "recommendationAuthority", "paidTaskCreated"]) assert.equal(result[key], false); assert.equal(result.networkOperation, "NONE"); assert.equal(result.actualSpendUsd, 0);
  const prepareSource = await readFile(new URL("../../../scripts/mercury-curated-ram-offer-prepare.mjs", import.meta.url), "utf8"), executeSource = await readFile(new URL("../../../scripts/mercury-curated-ram-offer-execute.mjs", import.meta.url), "utf8"); assert.doesNotMatch(prepareSource + executeSource, /fetch\(|https?:\/\//); assert.match(prepareSource, /Observation created:\s+NO/);
  console.log("Curated RAM offer governance tests passed (68 cases).");
} finally { await rm(root, { recursive: true, force: true }); }
