import assert from "node:assert/strict";
import {mkdtemp,rm} from "node:fs/promises";
import {join} from "node:path";
import {tmpdir} from "node:os";
import {spawnSync} from "node:child_process";
import {AMAZON_PILOT_CONFIRMATION,FileAmazonHistoricalAcceptanceRepository,FileAmazonPilotRepository,defaultSourceRightsRegistry,prepareAmazonPilot,projectAmazonPilotState,selectAmazonPilotProducts,validateAmazonPilot} from "../index.js";

let cases=0;
const product=(id,kind="DDR5")=>({identity:{atlasProductId:id,brand:"Fixture",manufacturerPartNumber:`MPN-${id}`},governance:{lifecycleStatus:"ACTIVE",publicationStatus:"READY"},extension:{data:{capacity:{capacityGb:32},classification:{memoryType:kind,formFactor:kind==="SODIMM"?"SODIMM":"DIMM"},performance:{dataRateMtps:6000},physical:{color:"black"}}}});
const destination=id=>({destinationId:`dest-${id}`,atlasProductId:id,retailerId:"RETAILER-0001",marketplace:"amazon.com",destinationType:"PRODUCT_PAGE",retailerListingId:`B0${id.replace(/\D/g,"").padStart(8,"0").slice(-8)}`,binding:{scope:"EXACT_STANDALONE_PRODUCT"},status:"ACTIVE",supersedesDestinationId:null,materialFingerprint:"a".repeat(64)});
const products=Array.from({length:12},(_,i)=>product(`ram_${String(i).padStart(2,"0")}`,i%3===2?"SODIMM":i%3===1?"DDR4":"DDR5")),destinations=products.map(p=>destination(p.identity.atlasProductId));
const selection=selectAmazonPilotProducts({atlasProducts:products,destinations,historicalObservations:[],cohortSize:5});
assert.equal(selection.selectedProducts.length,5);assert.deepEqual(selection.selectedProducts.map(x=>x.atlasProductId),["ram_00","ram_01","ram_02","ram_03","ram_04"]);assert.equal(selection.categoryDiversity,"NATURAL");cases+=3;
const excluded=selectAmazonPilotProducts({atlasProducts:products,destinations,historicalObservations:[{atlasProductId:"ram_00",provenance:{source:"DATAFORSEO_AMAZON"}},{atlasProductId:"ram_01",provenance:{source:"DATAFORSEO_GOOGLE_SHOPPING"}}],activeLineages:["ram_02"],cohortSize:5});assert(!excluded.selectedProducts.some(x=>x.atlasProductId==="ram_00"||x.atlasProductId==="ram_02"));assert(excluded.selectedProducts.some(x=>x.atlasProductId==="ram_01"));cases+=2;
const input={asOf:"2026-09-13T12:00:00.000Z",selection,rightsProfile:defaultSourceRightsRegistry.require("DATAFORSEO_AMAZON"),currentUtcDaySpendUsd:.003},artifact=prepareAmazonPilot(input);
assert.deepEqual(artifact,prepareAmazonPilot(input));assert.equal(validateAmazonPilot(artifact),true);assert.equal(artifact.costEnvelope.maximumTasks,10);assert.equal(artifact.costEnvelope.maximumProviderSpendUsd,.015);assert.equal(artifact.costEnvelope.maximumActionsCurrentlyAffordable,4);assert.equal(artifact.authorizationState,"NOT_AUTHORIZED");assert.equal(artifact.executionAuthorized,false);assert.equal(artifact.providerSpendAuthorized,false);assert.equal(artifact.networkOperation,"NONE");assert.equal(artifact.actualSpendUsd,0);cases+=10;
const tenSelection=selectAmazonPilotProducts({atlasProducts:products,destinations,historicalObservations:[],cohortSize:10}),ten=prepareAmazonPilot({...input,selection:tenSelection});assert.equal(ten.selectedProducts.length,10);assert.equal(ten.costEnvelope.maximumTasks,20);assert.equal(ten.costEnvelope.maximumProviderSpendUsd,.03);cases+=3;
assert.throws(()=>prepareAmazonPilot({...input,rightsProfile:{...input.rightsProfile,acquisition:{api:"BLOCKED"}}}),/SOURCE_RIGHTS_BLOCKED/);cases++;
const mixed={ram_00:"PIPELINE_COMPLETED_RETAINED_ONLY",ram_01:"PIPELINE_COMPLETED_ADMITTED",ram_02:"PRODUCT_STOPPED_IDENTITY",ram_03:"PRODUCT_STOPPED_PROVIDER",ram_04:"PIPELINE_COMPLETED_RETAINED_ONLY"},complete=projectAmazonPilotState({artifact,productOutcomes:mixed});assert.equal(complete.status,"PILOT_COMPLETE");assert.equal(complete.products[0].outcome,"PIPELINE_COMPLETED_RETAINED_ONLY");cases+=2;
const pending=projectAmazonPilotState({artifact,productOutcomes:{ram_00:"PRODUCT_STOPPED_IDENTITY"}});assert.equal(pending.status,"PILOT_IN_PROGRESS");assert.equal(pending.nextPermittedAction,"ram_01");cases+=2;
const stopped=projectAmazonPilotState({artifact,productOutcomes:mixed,rightsAllowed:false});assert.equal(stopped.status,"PILOT_STOPPED");assert.equal(stopped.globalBlocker,"RIGHTS_REVOKED");cases+=2;
for(const field of ["publicationAuthority","currentDisplayAuthority","currentPriceAuthority","cheapestAuthority","pickAuthority"]){assert.equal(Object.hasOwn(artifact,field),false);cases++;}
const root=await mkdtemp(join(tmpdir(),"h056-"));try{const statePath=join(root,"pilot.json"),acceptancePath=join(root,"acceptance.json"),repo=new FileAmazonPilotRepository({statePath}),acceptanceRepo=new FileAmazonHistoricalAcceptanceRepository({statePath:acceptancePath});assert.equal((await repo.record(artifact)).status,"PREPARED");assert.equal((await repo.record(artifact)).status,"DUPLICATE");assert.deepEqual(await repo.getById(artifact.pilotPreparationId),artifact);for(const child of artifact.perProductAcceptanceArtifacts)assert.equal((await acceptanceRepo.record(child)).status,"PREPARED");cases+=8;const changed=structuredClone(artifact);changed.actualSpendUsd=1;await assert.rejects(()=>repo.record(changed),/ARTIFACT_INVALID|CONFLICT/);cases++;const inspect=spawnSync(process.execPath,["scripts/mercury-amazon-pilot-inspect.mjs",`--artifact-id=${artifact.pilotPreparationId}`,`--pilot-state=${statePath}`,`--acceptance-state=${acceptancePath}`],{cwd:process.cwd(),encoding:"utf8"});assert.equal(inspect.status,0,inspect.stderr);assert.match(inspect.stdout,/Provider calls:\s+0/);assert.match(inspect.stdout,/Actual spend:\s+\$0\.000/);assert.match(inspect.stdout,/acceptance mer_amzaccept_/);cases+=4;}finally{await rm(root,{recursive:true,force:true});}
assert.equal(AMAZON_PILOT_CONFIRMATION,"PREPARE-DATAFORSEO-AMAZON-PILOT");cases++;
console.log(`DataForSEO Amazon pilot preparation tests passed: ${cases} cases.`);
