import assert from "node:assert/strict";
import { mkdtemp, readFile, rm, writeFile } from "node:fs/promises";
import { join } from "node:path";
import { tmpdir } from "node:os";
import { spawnSync } from "node:child_process";
import { AMAZON_ACCEPTANCE_CONFIRMATION, FileAmazonHistoricalAcceptanceRepository, assessAmazonAcceptanceProductsOutcome, assessHistoricalOfferComparability, defaultSourceRightsRegistry, prepareAmazonHistoricalAcceptance, projectAmazonSellerRetention, selectAmazonHistoricalAcceptanceProduct, validateAmazonHistoricalAcceptance } from "../index.js";
let cases=0;
const product=id=>({identity:{atlasProductId:id,brand:"Fixture",manufacturerPartNumber:`MPN-${id}`},governance:{lifecycleStatus:"ACTIVE",publicationStatus:"READY"},extension:{data:{capacity:{capacityGb:32},classification:{memoryType:"DDR5",formFactor:"DIMM"},performance:{dataRateMtps:6000},physical:{color:"black"}}}}),destination=(id,listing="B0ABC12345")=>({destinationId:`dest-${id}`,atlasProductId:id,retailerId:"RETAILER-0001",marketplace:"amazon.com",retailerListingId:listing,status:"ACTIVE",supersedesDestinationId:null});
const products=[product("ram_z"),product("ram_a")],destinations=[destination("ram_z"),destination("ram_a")],selection=selectAmazonHistoricalAcceptanceProduct({atlasProducts:products,destinations,historicalObservations:[]});
assert.equal(selection.productFacts.atlasProductId,"ram_a");assert.equal(selection.corroboratingDestinationAsins[0],"B0ABC12345");cases+=2;
assert.equal(selectAmazonHistoricalAcceptanceProduct({atlasProducts:products,destinations,historicalObservations:[{atlasProductId:"ram_a",provenance:{source:"DATAFORSEO_AMAZON"}}]}).productFacts.atlasProductId,"ram_z");cases++;
assert.equal(selectAmazonHistoricalAcceptanceProduct({atlasProducts:products,destinations,historicalObservations:[{atlasProductId:"ram_a",provenance:{source:"DATAFORSEO_GOOGLE_SHOPPING"}}]}).productFacts.atlasProductId,"ram_a");cases++;
const input={asOf:"2026-09-12T12:00:00.000Z",selection,rightsProfile:defaultSourceRightsRegistry.require("DATAFORSEO_AMAZON"),currentUtcDaySpendUsd:.001},artifact=prepareAmazonHistoricalAcceptance(input);
assert.deepEqual(artifact,prepareAmazonHistoricalAcceptance(input));assert.equal(validateAmazonHistoricalAcceptance(artifact),true);assert.equal(artifact.executionAuthorized,false);assert.equal(artifact.providerSpendAuthorized,false);assert.equal(artifact.costEnvelope.maximumTasks,3);assert.equal(artifact.costEnvelope.maximumProviderSpendUsd,.0045);assert.equal(artifact.costEnvelope.remainingUtcDayCapacityUsd,.009);assert.equal(artifact.executionEligible,true);cases+=8;
const constrained=prepareAmazonHistoricalAcceptance({...input,currentUtcDaySpendUsd:.007});assert.equal(constrained.executionEligible,false);assert.equal(constrained.authorizationState,"NOT_AUTHORIZED");cases+=2;
assert.throws(()=>prepareAmazonHistoricalAcceptance({...input,rightsProfile:{...input.rightsProfile,acquisition:{...input.rightsProfile.acquisition,api:"BLOCKED"}}}),/SOURCE_RIGHTS_BLOCKED/);cases++;
const tampered=structuredClone(artifact);tampered.atlasProductId="substituted";assert.throws(()=>validateAmazonHistoricalAcceptance(tampered),/ARTIFACT_INVALID/);cases++;
assert.deepEqual(assessAmazonAcceptanceProductsOutcome({state:"STRONG_UNIQUE_ASIN",providerAnchor:{asin:"B0ABC12345"}}),{systemStatus:"PRODUCTS_PROCESSED",nextPermittedAction:"AUTHORIZE_AMAZON_SELLERS",governedAsin:"B0ABC12345"});cases++;
for(const state of ["MULTIPLE_COMPATIBLE_ASINS","ASIN_VARIANT_CONFLICT","INSUFFICIENT_ASIN_EVIDENCE"]){const outcome=assessAmazonAcceptanceProductsOutcome({state});assert.equal(outcome.nextPermittedAction,"STOP");assert.equal(outcome.asinEnrichmentAuthorized,false);cases+=2;}
const identity={state:"STRONG_UNIQUE_ASIN",providerAnchor:{asin:"B0ABC12345"},productsTaskId:"products-task"},immutable={sourceId:"DATAFORSEO_AMAZON",operation:"AMAZON_SELLERS",providerTaskId:"sellers-task",canonicalResultId:"mer_providerresult_fixture",resultDigest:"b".repeat(64),sourceRightsProfileDigest:"c".repeat(64)};
const thirdParty=projectAmazonSellerRetention({sellerItem:{data_asin:"B0ABC12345",seller_name:"Independent Seller",seller_url:"https://seller.example/item",price:50,currency:"USD",condition:"new"},atlasProductId:"ram_a",identityAssessment:identity,sellersTaskId:"sellers-task",immutableResult:immutable,observedAt:"2026-09-12T12:00:00Z",rawPayloadReference:"fixture:third-party"});assert.equal(thirdParty.merchantResolution.outcome,"DISCOVERED");assert.equal(thirdParty.eligibility.historicalAnalyticsEligible,false);cases+=2;
const conditional=projectAmazonSellerRetention({sellerItem:{data_asin:"B0ABC12345",seller_name:"Amazon.com",seller_url:"https://amazon.com/dp/B0ABC12345",price:50,currency:"USD",condition:"new",applicable_vouchers:["membership required"]},atlasProductId:"ram_a",identityAssessment:identity,sellersTaskId:"sellers-task",immutableResult:immutable,observedAt:"2026-09-12T12:00:00Z",rawPayloadReference:"fixture:conditional"});const comparison=assessHistoricalOfferComparability({record:{candidate:conditional.candidate}});assert.equal(comparison.historicalStandaloneEligible,false);assert(comparison.reasons.some(reason=>reason.includes("CONDITIONAL")));cases+=2;
const root=await mkdtemp(join(tmpdir(),"h049-"));try{const repository=new FileAmazonHistoricalAcceptanceRepository({statePath:join(root,"artifacts.json")});assert.equal((await repository.record(artifact)).status,"PREPARED");assert.equal((await repository.record(artifact)).status,"DUPLICATE");assert.deepEqual(await repository.getById(artifact.acceptanceArtifactId),artifact);cases+=3;const conflict=structuredClone(artifact);conflict.executionEligible=false;await assert.rejects(()=>repository.record(conflict),/ARTIFACT_INVALID|CONFLICT/);cases++;
const history=join(root,"history.json"),ledger=join(root,"ledger.json"),state=join(root,"cli-artifacts.json");await writeFile(history,'{"version":"1.0","sequence":0,"records":{},"idempotency":{}}\n');await writeFile(ledger,'{"schemaVersion":"1.0","runs":[]}\n');const run=spawnSync(process.execPath,["scripts/mercury-amazon-acceptance-prepare.mjs","--as-of=2026-09-12T12:00:00.000Z",`--confirm=${AMAZON_ACCEPTANCE_CONFIRMATION}`,`--historical-state=${history}`,`--execution-ledger=${ledger}`,`--acceptance-state=${state}`],{cwd:process.cwd(),encoding:"utf8"});assert.equal(run.status,0,run.stderr);assert.match(run.stdout,/Provider calls:\s+0/);assert.match(run.stdout,/Actual spend:\s+\$0\.000/);cases+=3;const stored=JSON.parse(await readFile(state,"utf8"));assert.equal(stored.artifacts.length,1);assert.equal(stored.artifacts[0].sourceId,"DATAFORSEO_AMAZON");assert.equal(stored.artifacts[0].authorizationState,"NOT_AUTHORIZED");cases+=3;const inspect=spawnSync(process.execPath,["scripts/mercury-amazon-acceptance-inspect.mjs",`--artifact-id=${stored.artifacts[0].acceptanceArtifactId}`,`--acceptance-state=${state}`],{cwd:process.cwd(),encoding:"utf8"});assert.equal(inspect.status,0,inspect.stderr);assert.match(inspect.stdout,/Next permitted action:\s+OPERATOR_REVIEW/);cases+=2;}finally{await rm(root,{recursive:true,force:true});}
assert.equal(Object.hasOwn(artifact,"currentDisplayAuthority"),false);assert.equal(Object.hasOwn(artifact,"publicationAuthority"),false);cases+=2;
console.log(`DataForSEO Amazon acceptance preparation tests passed: ${cases} cases.`);
