import assert from "node:assert/strict";
import {mkdtemp,readFile,rm} from "node:fs/promises";
import {join} from "node:path";
import {tmpdir} from "node:os";
import {DataForSeoAmazonHistoricalRetentionService,FileDataForSeoMarketEvidenceRepository,FileHistoricalObservationRepository,HistoricalObservationAdmissionService,HistoricalObservationPortfolio,assessDataForSeoEvidencePromotion,assessHistoricalOfferComparability,createProductIdentityReviewDecision,createMerchantIdentityReviewDecision} from "../index.js";
let cases=0;const root=await mkdtemp(join(tmpdir(),"h048-")),atlasProductId="ram_fixture",asin="B0ABC12345",task="amazon-sellers-task",rights="a".repeat(64),now="2026-09-12T12:00:00Z";
const identity={state:"STRONG_UNIQUE_ASIN",providerAnchor:{asin},productsTaskId:"amazon-products-task"},immutable={sourceId:"DATAFORSEO_AMAZON",operation:"AMAZON_SELLERS",providerTaskId:task,canonicalResultId:"mer_providerresult_amazonfixture",resultDigest:"b".repeat(64),sourceRightsProfileDigest:rights};
const base={sellerItem:{asin,seller_name:"Amazon",seller_url:"https://www.amazon.com",price:59.99,regular_price:69.99,currency:"USD",condition:"new",condition_description:"New standalone memory kit",delivery_price:null},atlasProductId,identityAssessment:identity,sellersTaskId:task,immutableResult:immutable,observedAt:now,rawPayloadReference:"fixture:h048:amazon:sellers:0"};
try{
 const evidenceRepository=new FileDataForSeoMarketEvidenceRepository({statePath:join(root,"evidence.json"),now:()=>now}),retention=new DataForSeoAmazonHistoricalRetentionService({evidenceRepository});
 const thirdParty=await retention.retain({...base,sellersTaskId:"amazon-third-party",immutableResult:{...immutable,providerTaskId:"amazon-third-party",canonicalResultId:"result-third-party",resultDigest:"e".repeat(64)},rawPayloadReference:"fixture:h048:third-party",sellerItem:{...base.sellerItem,seller_name:"Independent Seller",seller_url:"https://www.amazon.com/sp?seller=fixture"}});assert.equal(thirdParty.projection.merchantResolution.outcome,"DISCOVERED");cases++;
 const retained=await retention.retain(base),record=await evidenceRepository.getById(retained.evidenceId);assert.equal(record.candidate.marketEvidence.source,"DATAFORSEO_AMAZON");assert.equal(record.candidate.marketEvidence.providerIdentity.asin,asin);assert.equal(record.candidate.marketEvidence.pricing.shippingPrice,null);assert.equal(record.candidate.marketEvidence.offer.condition,"new");cases+=4;
 for(const [suffix,value] of [["zero",0],["positive",5.5]]){const result=await retention.retain({...base,sellersTaskId:`amazon-sellers-${suffix}`,immutableResult:{...immutable,providerTaskId:`amazon-sellers-${suffix}`,canonicalResultId:`result-${suffix}`,resultDigest:(suffix==="zero"?"c":"d").repeat(64)},rawPayloadReference:`fixture:h048:${suffix}`,sellerItem:{...base.sellerItem,delivery_price:value}});assert.equal((await evidenceRepository.getById(result.evidenceId)).candidate.marketEvidence.pricing.shippingPrice,value);cases++;}
 const productDecision=createProductIdentityReviewDecision({atlasProductId,previousState:"PROBABLE",requestedState:"VERIFIED",decisionOutcome:"APPROVED",reviewedAt:now,reviewedBy:"operator:test",reason:"Fixture identity verification.",supportingEvidenceReferences:[record.evidenceId],contradictionStatus:"NONE",audit:{source:"FIXTURE",requestId:"h048-product",preparedAt:now}}),merchantDecision=createMerchantIdentityReviewDecision({discoveredMerchantName:"Amazon",canonicalMerchantName:"Amazon",canonicalDomain:"amazon.com",merchantId:"RETAILER-0001",merchantActive:true,previousState:"DISCOVERED",requestedState:"REGISTERED",decisionOutcome:"APPROVED",reviewedAt:now,reviewedBy:"operator:test",reason:"Fixture governed Amazon retailer binding.",supportingEvidenceReferences:[record.evidenceId],contradictionStatus:"NONE",audit:{source:"FIXTURE",requestId:"h048-merchant",preparedAt:now}}),amazonRetailer=JSON.parse(await readFile("packages/atlas/retailers/RETAILER-0001-amazon.json","utf8")),decisions=[productDecision,merchantDecision],retailers=[amazonRetailer];
 const assessment=assessDataForSeoEvidencePromotion({records:[record],identityReviewDecisions:decisions,atlasRetailers:retailers});assert.equal(assessment.state,"HISTORICAL_ELIGIBLE",JSON.stringify(assessment));assert.equal(assessment.canonicalEligible,false);cases+=2;
 const historicalRepository=new FileHistoricalObservationRepository({statePath:join(root,"history.json")}),service=new HistoricalObservationAdmissionService({evidenceRepository,decisionRepository:{getAll:async()=>decisions,getAllRemediations:async()=>[]},productRepository:{getById:async id=>id===atlasProductId?{identity:{atlasProductId}}:null},retailerRepository:{getAll:async()=>retailers},historicalRepository,acquisitionChainResolver:async()=>retained.projection.acquisitionChain,now:()=>"2026-09-12T12:01:00Z"}),admitted=await service.admit({evidenceId:record.evidenceId,admittedBy:"operator:test"});assert.equal(admitted.status,"ADMITTED");assert.equal(admitted.observation.provenance.source,"DATAFORSEO_AMAZON");assert.equal(admitted.observation.market.condition,"new");assert.equal(admitted.observation.market.shipping,null);cases+=4;assert.equal((await service.admit({evidenceId:record.evidenceId,admittedBy:"operator:test"})).status,"DUPLICATE");cases++;
 const portfolio=await new HistoricalObservationPortfolio({productRepository:{getAll:async()=>[{identity:{atlasProductId},governance:{lifecycleStatus:"ACTIVE",publicationStatus:"READY"}}]},historicalRepository,evidenceRepository,cadencePolicyRepository:{getAllPolicies:async()=>[]}}).query({asOf:"2026-09-12T13:00:00Z"});assert.equal(portfolio.products.find(value=>value.atlasProductId===atlasProductId).history.observationCount,1);cases++;
 for(const [details,reason] of [["Coupon required","HISTORICAL_OFFER_CONDITIONAL_NOT_COMPARABLE"],["Bundle with motherboard","HISTORICAL_OFFER_BUNDLE_NOT_COMPARABLE"]]){const blocked=structuredClone(record);blocked.candidate.marketEvidence.offer.details=details;assert.equal(assessHistoricalOfferComparability({record:blocked}).reasons[0],reason);cases++;}await assert.rejects(()=>retention.retain({...base,identityAssessment:{state:"MULTIPLE_COMPATIBLE_ASINS"}}),/IDENTITY_NOT_STRONG/);cases++;assert.equal(admitted.observation.governance.publicationEligible,false);assert.equal(admitted.observation.governance.canonicalEligible,false);cases+=2;
 const unresolved=assessDataForSeoEvidencePromotion({records:[await evidenceRepository.getById(thirdParty.evidenceId)],identityReviewDecisions:[],atlasRetailers:retailers});assert.notEqual(unresolved.state,"HISTORICAL_ELIGIBLE");assert.equal((await historicalRepository.getAll()).length,1);cases+=2;
 const unknown=await retention.retain({...base,sellersTaskId:"amazon-null-condition",immutableResult:{...immutable,providerTaskId:"amazon-null-condition",canonicalResultId:"result-null-condition",resultDigest:"f".repeat(64)},rawPayloadReference:"fixture:h048:null-condition",sellerItem:{...base.sellerItem,condition:null,condition_description:null}});assert.equal((await evidenceRepository.getById(unknown.evidenceId)).candidate.marketEvidence.offer.condition,null);cases++;
 await assert.rejects(()=>retention.retain({...base,sellerItem:{...base.sellerItem,price:61}}),/ACQUISITION_EVIDENCE_CONFLICT/);cases++;
 const denied=new HistoricalObservationAdmissionService({evidenceRepository,decisionRepository:{getAll:async()=>decisions,getAllRemediations:async()=>[]},productRepository:{getById:async()=>({identity:{atlasProductId}})},retailerRepository:{getAll:async()=>retailers},historicalRepository:new FileHistoricalObservationRepository({statePath:join(root,"denied.json")}),acquisitionChainResolver:async()=>retained.projection.acquisitionChain,rightsRegistry:{require:()=>({sourceId:"DATAFORSEO_AMAZON",acquisition:{api:"ALLOWED"},retention:{historical:"BLOCKED",durableAuditMetadata:"ALLOWED"},derivation:{historicalAnalytics:"ALLOWED"}})}});await assert.rejects(()=>denied.admit({evidenceId:record.evidenceId,admittedBy:"operator:test"}),/HISTORICAL_SOURCE_RIGHTS_DENIED/);cases++;
}finally{await rm(root,{recursive:true,force:true});}console.log(`DataForSEO Amazon historical admission tests passed: ${cases} cases.`);
