import assert from "node:assert/strict";
import {mkdtemp,rm} from "node:fs/promises";
import {join} from "node:path";
import {tmpdir} from "node:os";
import crypto from "node:crypto";
import {DataForSeoAmazonMerchantApiClient,DataForSeoTaskLedger,DataForSeoAmazonAcquisitionService,buildAmazonProductsRequest,buildAmazonAsinRequest,buildAmazonSellersRequest,DATAFORSEO_AMAZON_TASK_COST_USD,DATAFORSEO_AMAZON_ACCEPTANCE_ENVELOPE,createDataForSeoAmazonProviderResult,FileHistoricalBootstrapProviderResultRepository,DataForSeoAmazonResultRetrievalService,createAmazonProductsIdentityAdapter,normalizeAmazonCanonicalResult,createProductionDataForSeoTaskOwner,createProductionDataForSeoRetrievalOwner,AMAZON_ASIN_IDENTITY_STATES} from "../index.js";

let cases=0;const at="2026-09-12T04:00:00Z",intent=`mer_histbootintent_${"a".repeat(24)}`,rights="b".repeat(64),product={identity:{atlasProductId:"ram_fixture",manufacturerPartNumber:"CMK32GX4M2E3200C16",brand:"Corsair"},extension:{data:{capacity:{capacityGb:32,moduleCount:2},classification:{memoryType:"DDR4",formFactor:"DIMM"},performance:{dataRateMtps:3200},physical:{color:"Black",rgbLighting:false}}}};
const p=buildAmazonProductsRequest({atlasProduct:product}),a=buildAmazonAsinRequest({atlasProductId:"ram_fixture",dataAsin:"B0ABC12345"}),s=buildAmazonSellersRequest({atlasProductId:"ram_fixture",dataAsin:"B0ABC12345"});
assert.equal(p.providerPayload.keyword,"CMK32GX4M2E3200C16");assert.equal(a.providerPayload.asin,"B0ABC12345");assert.equal(s.providerPayload.asin,"B0ABC12345");cases+=3;
for(const request of [p,a,s]){assert.deepEqual(Object.keys(request.providerPayload).sort(),request.operation==="AMAZON_PRODUCTS"?["keyword","language_name","location_name","priority"]:["asin","language_name","location_name","priority"]);assert(!JSON.stringify(request.providerPayload).includes("ram_fixture"));assert(!JSON.stringify(request.providerPayload).includes("paidActionIntent"));}cases++;
assert.equal(DATAFORSEO_AMAZON_TASK_COST_USD,.0015);assert.deepEqual(DATAFORSEO_AMAZON_ACCEPTANCE_ENVELOPE,{maximumTasks:3,maximumProviderSpendUsd:.0045,perTaskCostCeilingUsd:.0015,automaticPaidRetries:0});cases++;

const calls=[],transport=async request=>(calls.push(structuredClone(request)),{status_code:20000,tasks:[{id:`task-${calls.length}`,status_code:20100,cost:.0015,result:[{items:[]}]}]}),client=new DataForSeoAmazonMerchantApiClient({login:"fixture",password:"fixture",transport});
await client.postAmazonProductsTask(p.providerPayload);await client.postAmazonAsinTask(a.providerPayload);await client.postAmazonSellersTask(s.providerPayload);await client.getAmazonProductsResult("task-1");await client.getAmazonAsinResult("task-2");await client.getAmazonSellersResult("task-3");
assert.deepEqual(calls.map(x=>new URL(x.url).pathname),["/v3/merchant/amazon/products/task_post","/v3/merchant/amazon/asin/task_post","/v3/merchant/amazon/sellers/task_post","/v3/merchant/amazon/products/task_get/advanced/task-1","/v3/merchant/amazon/asin/task_get/advanced/task-2","/v3/merchant/amazon/sellers/task_get/advanced/task-3"]);assert.equal(calls[0].body[0].atlasProductId,undefined);cases++;

const ledger=new DataForSeoTaskLedger(),fake={postAmazonProductsTask:async()=>({id:"amazon-task",cost:.0015,status_code:20100})},service=new DataForSeoAmazonAcquisitionService({client:fake,ledger});await service.createAmazonProductsTask({atlasProduct:product,paidActionIntentId:intent,checkpointId:"amazon-cp",productIndex:0,sourceRightsProfileDigest:rights});const task=ledger.getAll()[0];assert.equal(task.sourceId,"DATAFORSEO_AMAZON");assert.equal(task.kind,"AMAZON_PRODUCTS");assert.equal(task.atlasProductId,"ram_fixture");assert.equal(task.checkpointId,"amazon-cp");assert.equal(task.sourceRightsProfileDigest,rights);assert.match(task.requestDigest,/^[a-f0-9]{64}$/);assert.equal(task.costUsd,.0015);cases++;

const root=await mkdtemp(join(tmpdir(),"h047-"));try{const repository=new FileHistoricalBootstrapProviderResultRepository({statePath:join(root,"results.json")}),base={providerTaskId:"amazon-task",paidActionIntentId:intent,checkpointId:"amazon-cp",atlasProductId:"ram_fixture",productIndex:0,sourceRightsProfileDigest:rights,requestDigest:task.requestDigest,retrievedAt:at},results={AMAZON_PRODUCTS:{id:"amazon-task",result:[{items:[{data_asin:"B0ABC12345",title:"Corsair CMK32GX4M2E3200C16 32GB DDR4",url:"https://amazon.com/dp/B0ABC12345",currency:"USD"}]}]},AMAZON_ASIN:{id:"asin-task",result:[{items:[{data_asin:"B0ABC12345",parent_asin:"B0PARENT12",product_asins:["B0CHILD123"],brand:"Corsair",title:"Corsair RAM"}]}]},AMAZON_SELLERS:{id:"seller-task",result:[{items:[{asin:"B0ABC12345",seller_name:"Amazon.com",price:59.99,regular_price:69.99,currency:"USD",condition:null,delivery_price:null},{asin:"B0ABC12345",seller_name:"Third Party",price:60,currency:"USD",condition:"new",delivery_price:0}]}]}};
 const stored=[];for(const [operation,operationResult] of Object.entries(results)){const taskId=operationResult.id,record=createDataForSeoAmazonProviderResult({...base,operation,providerTaskId:taskId,paidActionIntentId:`mer_histbootintent_${crypto.createHash("sha256").update(operation).digest("hex").slice(0,24)}`,operationResult});stored.push(await repository.record(record));assert.equal((await repository.record(record)).canonicalResultId,record.canonicalResultId);}assert.equal(stored.length,3);cases++;
 const normalized=normalizeAmazonCanonicalResult(stored[2]);assert.equal(normalized[0].condition,null);assert.equal(normalized[0].deliveryPrice,null);assert.equal(normalized[1].condition,"new");assert.equal(normalized[1].deliveryPrice,0);cases++;
 await assert.rejects(()=>repository.record({...stored[0],operationResult:{changed:true}}),/RESULT_CONFLICT/);cases++;
 const adapter=createAmazonProductsIdentityAdapter(),strong=adapter.process({canonicalResult:stored[0],atlasProduct:product});assert.equal(strong.status,AMAZON_ASIN_IDENTITY_STATES.STRONG_UNIQUE_ASIN);assert.equal(strong.sellersReadiness,"SELLERS_READY");assert.equal(strong.governedAsinAnchor.asin,"B0ABC12345");cases++;
 const recordFor=items=>createDataForSeoAmazonProviderResult({...base,operation:"AMAZON_PRODUCTS",providerTaskId:`task-${crypto.createHash("sha256").update(JSON.stringify(items)).digest("hex").slice(0,8)}`,operationResult:{result:[{items}]}}),candidate=(id,title)=>({data_asin:id,title,url:`https://amazon.com/dp/${id}`});
 assert.equal(adapter.process({canonicalResult:recordFor([candidate("B0ABC12345","Corsair CMK32GX4M2E3200C16 32GB DDR4"),candidate("B0XYZ98765","Corsair CMK32GX4M2E3200C16 32GB DDR4")]),atlasProduct:product}).status,AMAZON_ASIN_IDENTITY_STATES.MULTIPLE_COMPATIBLE_ASINS);cases++;
 assert.equal(adapter.process({canonicalResult:recordFor([candidate("B0ABC12345","Corsair CMK32GX4M2E3200C16 64GB DDR4")]),atlasProduct:product}).status,AMAZON_ASIN_IDENTITY_STATES.ASIN_VARIANT_CONFLICT);cases++;
 assert.equal(adapter.process({canonicalResult:recordFor([candidate("B0ABC12345","Corsair CMK32GX4M2E3200C16 bundle with motherboard")]),atlasProduct:product}).status,AMAZON_ASIN_IDENTITY_STATES.BUNDLE_ASIN);cases++;
 assert.equal(adapter.process({canonicalResult:recordFor([candidate("B0ABC12345","Corsair renewed CMK32GX4M2E3200C16")]),atlasProduct:product}).status,AMAZON_ASIN_IDENTITY_STATES.RENEWED_OR_USED_ASIN);cases++;
 assert.throws(()=>adapter.process({canonicalResult:{...stored[0],sourceId:"DATAFORSEO_GOOGLE_SHOPPING"},atlasProduct:product}),/AMAZON_PRODUCTS_RESULT_REQUIRED/);assert.throws(()=>normalizeAmazonCanonicalResult({...stored[2],sourceId:"AMAZON_CREATORS_API"}),/SOURCE_MISMATCH/);cases++;
 const retrievalLedger={getAll:async()=>[{...task,taskId:"pending",checkpointId:"cp",sourceRightsProfileDigest:rights}]},pending=new DataForSeoAmazonResultRetrievalService({taskLedger:retrievalLedger,acquisitionService:{getAmazonProductsResult:async()=>({id:"pending",result:[]})},resultRepository:repository,now:()=>at});assert.equal((await pending.retrieve({providerTaskId:"pending"})).status,"PENDING");cases++;
 const failed=new DataForSeoAmazonResultRetrievalService({taskLedger:retrievalLedger,acquisitionService:{getAmazonProductsResult:async()=>({status:"PROVIDER_FAILED"})},resultRepository:repository,now:()=>at});assert.equal((await failed.retrieve({providerTaskId:"pending"})).status,"FAILED");cases++;
 const availableLedger={getAll:async()=>[{...task,taskId:"fresh",checkpointId:"cp",sourceRightsProfileDigest:rights}]},availableService={getAmazonProductsResult:async()=>({id:"fresh",result:[{items:[candidate("B0ABC12345","Corsair CMK32GX4M2E3200C16 32GB DDR4")]}]})},retrieval=new DataForSeoAmazonResultRetrievalService({taskLedger:availableLedger,acquisitionService:availableService,resultRepository:repository,now:()=>at}),first=await retrieval.retrieve({providerTaskId:"fresh"}),second=await retrieval.retrieve({providerTaskId:"fresh"});assert.equal(first.status,"AVAILABLE");assert.equal(second.canonicalResult.canonicalResultId,first.canonicalResult.canonicalResultId);cases++;
 const conflicting=new DataForSeoAmazonResultRetrievalService({taskLedger:availableLedger,acquisitionService:{getAmazonProductsResult:async()=>({id:"fresh",result:[{items:[]}]})},resultRepository:repository,now:()=>at});await assert.rejects(()=>conflicting.retrieve({providerTaskId:"fresh"}),/RESULT_CONFLICT/);cases++;
}finally{await rm(root,{recursive:true,force:true});}

const executions=[],consumed=new Set(),executionRepository={getAll:async()=>structuredClone(executions),findByPlanId:async id=>executions.find(x=>x.planId===id)??null,append:async run=>(executions.push(structuredClone(run)),{status:"RECORDED",run})},consumptionRepository={isConsumed:async id=>consumed.has(id),consume:async({authorizationId})=>consumed.has(authorizationId)?{status:"ALREADY_CONSUMED"}:(consumed.add(authorizationId),{status:"CONSUMED"})},runLock={runExclusive:async fn=>({status:"ACQUIRED",result:await fn()})},mock={createAmazonProductsTask:async()=>({taskId:"paid-amazon",costUsd:.0015,createdStatus:20100})};
const execution={kind:"AMAZON_PRODUCTS",source:"DATAFORSEO_AMAZON",provider:"DATAFORSEO",atlasProduct:product,paidActionIntentId:intent},plan={schemaVersion:"1.0",planId:"amazon-plan",plannedAt:at,policy:{enabled:true,maxPaidTasksPerRun:1,maxSpendPerRunUsd:.0015,maxSpendPerDayUsd:.01,automaticPaidRetries:0},spentTodayUsd:0,approvedTaskCount:1,estimatedApprovedSpendUsd:.0015,decisions:[{candidateId:"ram_fixture",estimatedCostUsd:.0015,decision:"APPROVED",execution}]},request={requestId:"amazon-auth",planId:plan.planId,plan,expiresAt:"2026-09-12T04:15:00Z",maxSpendUsd:.0015,maxPaidTasks:1},owner=createProductionDataForSeoTaskOwner({operation:"AMAZON_PRODUCTS",stateRoot:join(tmpdir(),"unused"),acquisitionService:mock,executionRepository,consumptionRepository,runLock,now:()=>at});assert.equal((await owner.execute({request})).status,"COMPLETED");assert.equal((await owner.execute({request})).status,"LIVE_AUTHORIZATION_ALREADY_CONSUMED");assert.equal(executions[0].actualSpendUsd,.0015);cases++;
const retrievalOwner=createProductionDataForSeoRetrievalOwner({operation:"AMAZON_ASIN",acquisitionService:{getAmazonAsinResult:async id=>({id,result:[{}]})}});assert.equal((await retrievalOwner.retrieve({providerTaskId:"task"})).id,"task");cases++;
assert.equal(executions.reduce((sum,row)=>sum+row.actualSpendUsd,0),.0015);cases++;
const googleExecution={kind:"PRODUCTS",source:"DATAFORSEO_GOOGLE_SHOPPING",provider:"DATAFORSEO",keyword:"MPN"},googlePlan={...plan,planId:"google-plan",spentTodayUsd:.0015,estimatedApprovedSpendUsd:.001,policy:{...plan.policy,maxSpendPerRunUsd:.001},decisions:[{candidateId:"google",estimatedCostUsd:.001,decision:"APPROVED",execution:googleExecution}]},googleOwner=createProductionDataForSeoTaskOwner({operation:"PRODUCTS",acquisitionService:{createProductsTask:async()=>({taskId:"paid-google",costUsd:.001,createdStatus:20100})},executionRepository,consumptionRepository,runLock,now:()=>at});await googleOwner.execute({request:{requestId:"google-auth",planId:"google-plan",plan:googlePlan,expiresAt:"2026-09-12T04:15:00Z",maxSpendUsd:.001,maxPaidTasks:1}});assert.equal(executions.reduce((sum,row)=>sum+row.actualSpendUsd,0),.0025);assert.deepEqual(executions.map(row=>row.tasks[0].providerTaskId),["paid-amazon","paid-google"]);cases++;
console.log(`DataForSEO Amazon transport tests passed: ${cases} cases.`);
