import assert from "node:assert/strict";
import {AmazonPilotProjectionService,defaultSourceRightsRegistry,prepareAmazonPilot,selectAmazonPilotProducts} from "../index.js";
let cases=0;
const product=i=>({
  identity:{atlasProductId:`ram_${i}`,brand:"Fixture",manufacturerPartNumber:`MPN-${i}`},
  governance:{lifecycleStatus:"ACTIVE",publicationStatus:"READY"},
  extension:{data:{capacity:{capacityGb:32},classification:{memoryType:"DDR5",formFactor:"DIMM"},performance:{dataRateMtps:6000},physical:{color:"black"}}}
});
const destination=i=>({destinationId:`dest-${i}`,atlasProductId:`ram_${i}`,retailerId:"RETAILER-0001",marketplace:"amazon.com",destinationType:"PRODUCT_PAGE",retailerListingId:`B00000000${i}`,binding:{scope:"EXACT_STANDALONE_PRODUCT"},status:"ACTIVE",supersedesDestinationId:null,materialFingerprint:"a".repeat(64)});
const selection=selectAmazonPilotProducts({atlasProducts:[1,2,3,4,5].map(product),destinations:[1,2,3,4,5].map(destination),historicalObservations:[],cohortSize:5}),artifact=prepareAmazonPilot({asOf:"2026-09-13T05:00:00Z",selection,rightsProfile:defaultSourceRightsRegistry.require("DATAFORSEO_AMAZON"),currentUtcDaySpendUsd:.003}),ids=artifact.perProductAcceptanceArtifacts.map(x=>x.acceptanceArtifactId);
const task=(i,kind,n)=>({checkpointId:ids[i],kind,taskId:`task-${i}-${kind}`,costUsd:.0015}),tasks=[task(0,"AMAZON_PRODUCTS"),task(0,"AMAZON_SELLERS"),task(1,"AMAZON_PRODUCTS"),task(1,"AMAZON_SELLERS")],results=new Map(tasks.map(x=>[x.taskId,{providerTaskId:x.taskId}])),outcomes=new Map([[ids[0],{state:"STRONG_UNIQUE_ASIN",governedAsin:"B000000001"}],[ids[1],{state:"STRONG_UNIQUE_ASIN",governedAsin:"B000000002"}]]),evidence=tasks.filter(x=>x.kind==="AMAZON_SELLERS").flatMap((x,i)=>[1,2,3].map(n=>({evidenceId:`ev-${i}-${n}`,candidate:{marketEvidence:{provenance:{sourceTaskId:x.taskId}}}}))),writes={count:0};
const make=({taskRows=tasks,resultRows=results,outcomeRows=outcomes,evidenceRows=evidence,historyRows=[],spend=.009}={})=>new AmazonPilotProjectionService({actionRepository:{getAuthorizationsForAction:async(id,op)=>taskRows.some(x=>x.checkpointId===id&&x.kind===op)?[{}]:[],getEffectiveOutcomeForArtifact:async id=>outcomeRows.get(id)??null},taskLedger:{getAll:async()=>structuredClone(taskRows)},resultRepository:{findByTask:async id=>structuredClone(resultRows.get(id)??null)},evidenceRepository:{getAll:async()=>structuredClone(evidenceRows)},historicalRepository:{getAll:async()=>structuredClone(historyRows)},spendResolver:async()=>spend});
const state=await make().project({artifact,evaluationTime:"2026-09-13T06:00:00Z"});assert.deepEqual(state.products.map(x=>x.state),["COMPLETED_RETAINED_ONLY","COMPLETED_RETAINED_ONLY","NOT_STARTED","NOT_STARTED","NOT_STARTED"]);assert.equal(state.paidTasksUsed,4);assert.deepEqual(state.taskCounts,{AMAZON_PRODUCTS:2,AMAZON_SELLERS:2,AMAZON_ASIN:0});assert.equal(state.pilotSpendUsd,.006);assert.equal(state.configuredUtcDaySpendCeilingUsd,.025);assert.equal(state.utcDaySpendUsd,.009);assert.equal(state.remainingUtcDayCapacityUsd,.016);assert.equal(state.status,"PILOT_IN_PROGRESS");assert.equal(state.nextOperatorAction,"AUTHORIZE_PRODUCTS:ram_3");assert.equal(state.products[0].governedAsin,"B000000001");cases+=10;
const pendingTasks=[task(0,"AMAZON_PRODUCTS")],pending=await make({taskRows:pendingTasks,resultRows:new Map(),outcomeRows:new Map(),evidenceRows:[],spend:.0015}).project({artifact,evaluationTime:"2026-09-13T06:00:00Z"});assert.equal(pending.products[0].state,"PRODUCTS_RESULT_PENDING");cases++;
const available=await make({taskRows:pendingTasks,resultRows:new Map([[pendingTasks[0].taskId,{}]]),outcomeRows:new Map(),evidenceRows:[],spend:.0015}).project({artifact,evaluationTime:"2026-09-13T06:00:00Z"});assert.equal(available.products[0].state,"PRODUCTS_RESULT_AVAILABLE");cases++;
const blocked=await make({taskRows:pendingTasks,resultRows:new Map([[pendingTasks[0].taskId,{}]]),outcomeRows:new Map([[ids[0],{state:"MULTIPLE_COMPATIBLE_ASINS"}]]),evidenceRows:[],spend:.0015}).project({artifact,evaluationTime:"2026-09-13T06:00:00Z"});assert.equal(blocked.products[0].state,"PRODUCTS_IDENTITY_BLOCKED");cases++;
const review=await make({taskRows:pendingTasks,resultRows:new Map([[pendingTasks[0].taskId,{}]]),outcomeRows:new Map([[ids[0],{state:"STRONG_UNIQUE_ASIN",governedAsin:"B000000001"}]]),evidenceRows:[],spend:.0015}).project({artifact,evaluationTime:"2026-09-13T06:00:00Z"});assert.equal(review.products[0].state,"SELLERS_REVIEW_REQUIRED");cases++;
const admittedHistory=[{observationId:"hist-1",provenance:{retainedEvidenceId:"ev-0-1"}}],admitted=await make({historyRows:admittedHistory}).project({artifact,evaluationTime:"2026-09-13T06:00:00Z"});assert.equal(admitted.products[0].state,"COMPLETED_ADMITTED");cases++;
const reassessed=await make({outcomeRows:new Map([[ids[0],{state:"STRONG_UNIQUE_ASIN",governedAsin:"B000000009"}],[ids[1],outcomes.get(ids[1])]])}).project({artifact,evaluationTime:"2026-09-13T06:00:00Z"});assert.equal(reassessed.products[0].governedAsin,"B000000009");cases++;
await assert.rejects(()=>make({taskRows:[...tasks,{...tasks[0],taskId:"conflict"}]}).project({artifact,evaluationTime:"2026-09-13T06:00:00Z"}),/TASK_CONFLICT/);cases++;
const reordered=await make({taskRows:[...tasks].reverse(),evidenceRows:[...evidence].reverse()}).project({artifact,evaluationTime:"2026-09-13T06:00:00Z"});assert.deepEqual(reordered.products,state.products);assert.equal(writes.count,0);assert.equal(state.writesPerformed,0);cases+=3;
console.log(`DataForSEO Amazon pilot projection tests passed: ${cases} cases.`);
