import assert from "node:assert/strict";
import { mkdtemp, readFile, rm } from "node:fs/promises";
import os from "node:os";
import path from "node:path";
import { AMAZON_ACCEPTANCE_ACTION_CONFIRMATIONS, AmazonAcceptanceExecutionService, FileAmazonAcceptanceActionRepository, defaultSourceRightsRegistry, prepareAmazonHistoricalAcceptance, selectAmazonHistoricalAcceptanceProduct } from "../index.js";

let cases=0,now="2026-09-12T16:00:00.000Z",spend=0,calls=0;const executed=new Set();
const product={identity:{atlasProductId:"ram_successor_fixture",brand:"Corsair",manufacturerPartNumber:"CMH32GX5M2B6000C38"},governance:{lifecycleStatus:"ACTIVE",publicationStatus:"READY"},extension:{data:{capacity:{capacityGb:32,moduleCount:2},classification:{memoryType:"DDR5",formFactor:"DIMM"},performance:{dataRateMtps:6000},physical:{color:"black"}}}};
const selection=selectAmazonHistoricalAcceptanceProduct({atlasProducts:[product],destinations:[{destinationId:"d",atlasProductId:product.identity.atlasProductId,retailerId:"RETAILER-0001",marketplace:"amazon.com",retailerListingId:"B0CQQVNCB6",status:"ACTIVE"}],historicalObservations:[]});
const artifact=prepareAmazonHistoricalAcceptance({asOf:now,selection,rightsProfile:defaultSourceRightsRegistry.require("DATAFORSEO_AMAZON"),currentUtcDaySpendUsd:0});
const root=await mkdtemp(path.join(os.tmpdir(),"hr-h050a-"));
try{
 const statePath=path.join(root,"actions.json"),actionRepository=new FileAmazonAcceptanceActionRepository({statePath}),consumptions=[],tasks=[];
 const owner={execute:async({request})=>{if(executed.has(request.requestId))return{status:"LIVE_AUTHORIZATION_ALREADY_CONSUMED"};executed.add(request.requestId);calls++;return{status:"COMPLETED"};}};const service=new AmazonAcceptanceExecutionService({artifactRepository:{getById:async id=>id===artifact.acceptanceArtifactId?artifact:null},actionRepository,productRepository:{getById:async()=>product},rightsRegistry:defaultSourceRightsRegistry,spendResolver:async()=>spend,taskOwners:{AMAZON_PRODUCTS:owner,AMAZON_SELLERS:owner},retrievalServices:{},resultRepository:{findByTask:async()=>null},taskLedger:{getAll:async()=>structuredClone(tasks)},consumptionRepository:{getAll:async()=>structuredClone(consumptions)},now:()=>now});
 const authorize=(operation,expiresAt,operator="operator:first",reason="first")=>service.authorize({artifactId:artifact.acceptanceArtifactId,operation,operator,reason,expiresAt,confirmation:operation==="AMAZON_PRODUCTS"?AMAZON_ACCEPTANCE_ACTION_CONFIRMATIONS.AUTHORIZE_PRODUCTS:AMAZON_ACCEPTANCE_ACTION_CONFIRMATIONS.AUTHORIZE_SELLERS});
 const first=(await authorize("AMAZON_PRODUCTS","2026-09-12T16:05:00.000Z")).value,original=await readFile(statePath,"utf8");assert.equal(calls,0);cases+=2;
 await assert.rejects(()=>authorize("AMAZON_PRODUCTS","2026-09-12T16:10:00.000Z","operator:second","active"),/AUTHORIZATION_ACTIVE/);cases++;
 now="2026-09-12T16:06:00.000Z";spend=.002;const secondInput=()=>authorize("AMAZON_PRODUCTS","2026-09-12T16:20:00.000Z","operator:second","successor"),second=(await secondInput()).value;assert.notEqual(second.authorizationId,first.authorizationId);assert.equal(second.predecessorAuthorizationId,first.authorizationId);assert.equal(second.plan.spentTodayUsd,.002);assert.deepEqual((await actionRepository.getAuthorization(first.authorizationId)),first);assert.equal(calls,0);cases+=5;
 assert.equal((await secondInput()).status,"DUPLICATE");assert.equal((await actionRepository.getAuthorizationsForAction(artifact.acceptanceArtifactId,"AMAZON_PRODUCTS")).length,2);cases+=2;
 await assert.rejects(()=>service.execute({artifactId:artifact.acceptanceArtifactId,authorizationId:first.authorizationId,operation:"AMAZON_PRODUCTS",confirmation:AMAZON_ACCEPTANCE_ACTION_CONFIRMATIONS.EXECUTE_PRODUCTS}),/NOT_AUTHORIZED/);assert.equal((await service.execute({artifactId:artifact.acceptanceArtifactId,authorizationId:second.authorizationId,operation:"AMAZON_PRODUCTS",confirmation:AMAZON_ACCEPTANCE_ACTION_CONFIRMATIONS.EXECUTE_PRODUCTS})).status,"COMPLETED");assert.equal((await service.execute({artifactId:artifact.acceptanceArtifactId,authorizationId:second.authorizationId,operation:"AMAZON_PRODUCTS",confirmation:AMAZON_ACCEPTANCE_ACTION_CONFIRMATIONS.EXECUTE_PRODUCTS})).status,"LIVE_AUTHORIZATION_ALREADY_CONSUMED");assert.equal(calls,1);cases+=4;
 await assert.rejects(()=>authorize("AMAZON_PRODUCTS","2026-09-12T16:30:00.000Z","operator:third","active successor"),/AUTHORIZATION_ACTIVE/);cases++;
 const concurrentRoot=path.join(root,"concurrent.json"),concurrentRepository=new FileAmazonAcceptanceActionRepository({statePath:concurrentRoot});await concurrentRepository.recordAuthorization(first);const a={...second,authorizationId:"successor-a",operator:"a"},b={...second,authorizationId:"successor-b",operator:"b"};const settled=await Promise.allSettled([concurrentRepository.recordAuthorization(a,{asOf:now,expectedPredecessorIds:[first.authorizationId]}),concurrentRepository.recordAuthorization(b,{asOf:now,expectedPredecessorIds:[first.authorizationId]})]);assert.equal(settled.filter(x=>x.status==="fulfilled").length,1);assert.equal((await concurrentRepository.getAuthorizationsForAction(artifact.acceptanceArtifactId,"AMAZON_PRODUCTS")).length,2);cases+=2;
 const consumedRoot=path.join(root,"consumed.json"),consumedRepo=new FileAmazonAcceptanceActionRepository({statePath:consumedRoot});await consumedRepo.recordAuthorization(first);const consumedService=new AmazonAcceptanceExecutionService({artifactRepository:{getById:async()=>artifact},actionRepository:consumedRepo,productRepository:{getById:async()=>product},rightsRegistry:defaultSourceRightsRegistry,spendResolver:async()=>0,taskOwners:{},retrievalServices:{},resultRepository:{findByTask:async()=>null},taskLedger:{getAll:async()=>[]},consumptionRepository:{getAll:async()=>[{authorizationId:first.authorizationId,planId:first.plan.planId}]},now:()=>now});await assert.rejects(()=>consumedService.authorize({artifactId:artifact.acceptanceArtifactId,operation:"AMAZON_PRODUCTS",operator:"operator:test",reason:"blocked",expiresAt:"2026-09-12T16:20:00.000Z",confirmation:AMAZON_ACCEPTANCE_ACTION_CONFIRMATIONS.AUTHORIZE_PRODUCTS}),/ALREADY_USED/);cases++;
 const taskService=new AmazonAcceptanceExecutionService({artifactRepository:{getById:async()=>artifact},actionRepository:consumedRepo,productRepository:{getById:async()=>product},rightsRegistry:defaultSourceRightsRegistry,spendResolver:async()=>0,taskOwners:{},retrievalServices:{},resultRepository:{findByTask:async()=>null},taskLedger:{getAll:async()=>[{checkpointId:artifact.acceptanceArtifactId,kind:"AMAZON_PRODUCTS",taskId:"task"}]},consumptionRepository:{getAll:async()=>[]},now:()=>now});await assert.rejects(()=>taskService.authorize({artifactId:artifact.acceptanceArtifactId,operation:"AMAZON_PRODUCTS",operator:"operator:test",reason:"blocked",expiresAt:"2026-09-12T16:20:00.000Z",confirmation:AMAZON_ACCEPTANCE_ACTION_CONFIRMATIONS.AUTHORIZE_PRODUCTS}),/ALREADY_USED/);cases++;
 const state=JSON.parse(await readFile(statePath,"utf8"));assert.deepEqual(state.authorizations[0],first);assert.equal(state.authorizations.length,2);assert.notEqual(original,await readFile(statePath,"utf8"));cases+=3;
 const sellerRepository=new FileAmazonAcceptanceActionRepository({statePath:path.join(root,"sellers.json")}),sellerOutcome={outcomeId:"o",artifactId:artifact.acceptanceArtifactId,state:"STRONG_UNIQUE_ASIN",governedAsin:"B0CQQVNCB6"};await sellerRepository.recordOutcome(sellerOutcome);const sellerService=new AmazonAcceptanceExecutionService({artifactRepository:{getById:async()=>artifact},actionRepository:sellerRepository,productRepository:{getById:async()=>product},rightsRegistry:defaultSourceRightsRegistry,spendResolver:async()=>0,taskOwners:{},retrievalServices:{},resultRepository:{findByTask:async()=>null},taskLedger:{getAll:async()=>[]},consumptionRepository:{getAll:async()=>[]},now:()=>now});const sellerFirst=(await sellerService.authorize({artifactId:artifact.acceptanceArtifactId,operation:"AMAZON_SELLERS",operator:"operator:first",reason:"first",expiresAt:"2026-09-12T16:07:00.000Z",confirmation:AMAZON_ACCEPTANCE_ACTION_CONFIRMATIONS.AUTHORIZE_SELLERS})).value;now="2026-09-12T16:08:00.000Z";const sellerSecond=(await sellerService.authorize({artifactId:artifact.acceptanceArtifactId,operation:"AMAZON_SELLERS",operator:"operator:second",reason:"successor",expiresAt:"2026-09-12T16:20:00.000Z",confirmation:AMAZON_ACCEPTANCE_ACTION_CONFIRMATIONS.AUTHORIZE_SELLERS})).value;assert.equal(sellerSecond.predecessorAuthorizationId,sellerFirst.authorizationId);cases++;
 const changedRights={require:()=>({...defaultSourceRightsRegistry.require("DATAFORSEO_AMAZON"),status:"CHANGED"})};const rightsBlocked=new AmazonAcceptanceExecutionService({artifactRepository:{getById:async()=>artifact},actionRepository,productRepository:{getById:async()=>product},rightsRegistry:changedRights,spendResolver:async()=>0,taskOwners:{},retrievalServices:{},resultRepository:{findByTask:async()=>null},taskLedger:{getAll:async()=>[]},consumptionRepository:{getAll:async()=>[]},now:()=>now});await assert.rejects(()=>rightsBlocked.authorize({artifactId:artifact.acceptanceArtifactId,operation:"AMAZON_PRODUCTS",operator:"operator:test",reason:"rights",expiresAt:"2026-09-12T16:30:00.000Z",confirmation:AMAZON_ACCEPTANCE_ACTION_CONFIRMATIONS.AUTHORIZE_PRODUCTS}),/RIGHTS_CHANGED/);cases++;
 console.log(`DataForSEO Amazon acceptance authorization successor tests passed: ${cases} cases.`);
}finally{await rm(root,{recursive:true,force:true});}
