import assert from "node:assert/strict";
import { mkdtemp, readFile, rm } from "node:fs/promises";
import { join } from "node:path";
import { tmpdir } from "node:os";
import { AmazonAcceptanceExecutionService, AMAZON_PRODUCTS_REASSESSMENT_CONFIRMATION, FileAmazonAcceptanceActionRepository, createAmazonProductsIdentityReassessment, createDataForSeoAmazonProviderResult, defaultSourceRightsRegistry, prepareAmazonHistoricalAcceptance, selectAmazonHistoricalAcceptanceProduct, validateAmazonProductsReassessmentLineage } from "../index.js";

let cases = 0;
const at = "2026-09-13T03:00:00.000Z";
const product = id => ({ identity: { atlasProductId: id, brand: "Corsair", manufacturerPartNumber: "CMH32GX5M2B6000C38" }, governance: { lifecycleStatus: "ACTIVE", publicationStatus: "READY" }, extension: { data: { capacity: { capacityGb: 32, moduleCount: 2 }, classification: { memoryType: "DDR5", formFactor: "DIMM" }, performance: { dataRateMtps: 6000, primaryTimings: "38-44-44-96" }, physical: { color: "Black", rgbLighting: true } } } });
const realItems = [
 ["B0CQQVNCB6","CORSAIR Vengeance RGB DDR5 RAM 32GB (2x16GB) 6000MHz CL38 Black (CMH32GX5M2B6000C38)"],
 ["B0DZ935RX9","Corsair Vengeance RGB 32GB DDR5-6000 CL36 CMH32GX5M2M6000Z36"],
 ["B09RX4N6JZ","CORSAIR DOMINATOR RGB DDR5 RAM 64GB CMT64GX5M2B5200C40"],
 ["B0BFGB2D2Z","G.SKILL Flare X5 DDR5 32GB F5-6000J3636F16GX2-FX5"],
 ["B0BHVFDK3L","CORSAIR VENGEANCE RGB DDR5 64GB CMH64GX5M2B5200Z40K"],
 ["B0DX4WXDRZ","G.SKILL Flare X5 DDR5 64GB F5-6000J2836G32GX2-FX5"],
 ["B0CTHXMYL8","Crucial Pro 32GB DDR5 CP2K16G60C36U5B"],
 ["B0FDQ9VJDJ","KLEVV CRAS V RGB DDR5 32GB KD5AGUA80-64B300G"],
 ["B0B2X1QBYW","G.SKILL Ripjaws S5 DDR5 64GB F5-6000J3040G32GX2-RS5K"],
 ["B0F753191W","G.SKILL G5 DDR5 128GB F5-6000R3036G32GQ4-G5"]
].map(([data_asin,title])=>({data_asin,title}));

const root = await mkdtemp(join(tmpdir(), "h052-"));
try {
 const atlasProduct=product("ram_fixture"),selection=selectAmazonHistoricalAcceptanceProduct({atlasProducts:[atlasProduct],destinations:[{destinationId:"d",atlasProductId:"ram_fixture",retailerId:"RETAILER-0001",marketplace:"amazon.com",retailerListingId:"B0CQQVNCB6",status:"ACTIVE"}],historicalObservations:[]}),artifact=prepareAmazonHistoricalAcceptance({asOf:at,selection,rightsProfile:defaultSourceRightsRegistry.require("DATAFORSEO_AMAZON"),currentUtcDaySpendUsd:0});
 const task={taskId:"amazon-products-task",kind:"AMAZON_PRODUCTS",checkpointId:artifact.acceptanceArtifactId,atlasProductId:artifact.atlasProductId,sourceId:"DATAFORSEO_AMAZON"},canonicalResult=createDataForSeoAmazonProviderResult({operation:"AMAZON_PRODUCTS",providerTaskId:task.taskId,paidActionIntentId:"intent",checkpointId:artifact.acceptanceArtifactId,atlasProductId:artifact.atlasProductId,productIndex:0,sourceRightsProfileDigest:artifact.sourceRightsProfileDigest,requestDigest:"a".repeat(64),operationResult:{result:[{items:realItems}]},retrievedAt:at}),original={schemaVersion:"1.0",outcomeId:"mer_amzoutcome_original",artifactId:artifact.acceptanceArtifactId,authorizationId:"auth",canonicalResultId:canonicalResult.canonicalResultId,resultDigest:canonicalResult.resultDigest,state:"ASIN_VARIANT_CONFLICT",assessmentId:"mer_amzasin_original",governedAsin:null,nextPermittedAction:"STOP",sellersAuthorizationEligible:false,asinEnrichmentAuthorized:false,providerCallPerformed:false,actualSpendUsd:0};
 const statePath=join(root,"actions.json"),actionRepository=new FileAmazonAcceptanceActionRepository({statePath});await actionRepository.recordOutcome(original);const before=(await actionRepository.getOutcomeById(original.outcomeId)),tasks=[task],history=[];
 const service=new AmazonAcceptanceExecutionService({artifactRepository:{getById:async id=>id===artifact.acceptanceArtifactId?artifact:null},actionRepository,productRepository:{getById:async id=>id===atlasProduct.identity.atlasProductId?atlasProduct:null},rightsRegistry:defaultSourceRightsRegistry,spendResolver:async()=>0,taskOwners:{},retrievalServices:{},resultRepository:{findByTask:async id=>id===task.taskId?canonicalResult:null},taskLedger:{getAll:async()=>structuredClone(tasks)},consumptionRepository:{getAll:async()=>[]},historicalRepository:{getAll:async()=>structuredClone(history)},now:()=>at});
 await assert.rejects(()=>service.reassessProducts({artifactId:artifact.acceptanceArtifactId,operator:"operator:test",reason:"H051 correction",confirmation:"wrong"}),/CONFIRMATION/);cases++;
 const first=await service.reassessProducts({artifactId:artifact.acceptanceArtifactId,operator:"operator:test",reason:"H051 correction",confirmation:AMAZON_PRODUCTS_REASSESSMENT_CONFIRMATION});assert.equal(first.status,"RECORDED");assert.equal(first.reassessment.newState,"STRONG_UNIQUE_ASIN");assert.equal(first.reassessment.governedAsin,"B0CQQVNCB6");assert.equal(first.effectiveOutcome.sellersAuthorizationEligible,true);assert.equal(first.providerCalls,0);assert.equal(first.actualSpendUsd,0);cases+=6;
 assert.deepEqual(await actionRepository.getOutcomeById(original.outcomeId),before);assert.equal((await actionRepository.getReassessmentsForOutcome(original.outcomeId)).length,1);cases+=2;
 const replay=await service.reassessProducts({artifactId:artifact.acceptanceArtifactId,operator:"operator:test",reason:"H051 correction",confirmation:AMAZON_PRODUCTS_REASSESSMENT_CONFIRMATION});assert.equal(replay.status,"DUPLICATE");assert.equal(replay.reassessment.reassessmentId,first.reassessment.reassessmentId);cases+=2;
 const simultaneous=await Promise.all([service.reassessProducts({artifactId:artifact.acceptanceArtifactId,operator:"operator:test",reason:"H051 correction",confirmation:AMAZON_PRODUCTS_REASSESSMENT_CONFIRMATION}),service.reassessProducts({artifactId:artifact.acceptanceArtifactId,operator:"operator:test",reason:"H051 correction",confirmation:AMAZON_PRODUCTS_REASSESSMENT_CONFIRMATION})]);assert.equal(new Set(simultaneous.map(x=>x.reassessment.reassessmentId)).size,1);cases++;
 await assert.rejects(()=>service.reassessProducts({artifactId:artifact.acceptanceArtifactId,operator:"operator:other",reason:"different",confirmation:AMAZON_PRODUCTS_REASSESSMENT_CONFIRMATION}),/CONFLICT/);cases++;
 assert.equal(["publicationAuthority","currentPriceAuthority","cheapestAuthority","pickAuthority","affiliateAuthority"].some(key=>key in first.reassessment),false);assert.equal(first.reassessment.providerExecutionAuthorized,false);assert.equal(first.reassessment.providerSpendAuthorized,false);cases+=3;
 const injected=await service.reassessProducts({artifactId:artifact.acceptanceArtifactId,operator:"operator:test",reason:"H051 correction",confirmation:AMAZON_PRODUCTS_REASSESSMENT_CONFIRMATION,asin:"B0INJECT01"});assert.equal(injected.reassessment.governedAsin,"B0CQQVNCB6");cases++;
 const badResult=structuredClone(canonicalResult);badResult.resultDigest="b".repeat(64);assert.throws(()=>validateAmazonProductsReassessmentLineage({artifact,originalOutcome:original,canonicalResult:badResult,atlasProduct}),/LINEAGE/);cases++;
 const wrongProduct=product("ram_other");assert.throws(()=>createAmazonProductsIdentityReassessment({artifact,originalOutcome:original,canonicalResult,atlasProduct:wrongProduct,operator:"o",reason:"r",createdAt:at}),/LINEAGE/);cases++;
 const wrongSource=structuredClone(canonicalResult);wrongSource.sourceId="DATAFORSEO_GOOGLE_SHOPPING";assert.throws(()=>validateAmazonProductsReassessmentLineage({artifact,originalOutcome:original,canonicalResult:wrongSource,atlasProduct}),/LINEAGE/);cases++;
 const ambiguousResult=createDataForSeoAmazonProviderResult({operation:"AMAZON_PRODUCTS",providerTaskId:"ambiguous",paidActionIntentId:"intent2",checkpointId:artifact.acceptanceArtifactId,atlasProductId:artifact.atlasProductId,productIndex:0,sourceRightsProfileDigest:artifact.sourceRightsProfileDigest,requestDigest:"c".repeat(64),operationResult:{result:[{items:[realItems[0],{...realItems[0],data_asin:"B0EXACT002"}]}]},retrievedAt:at}),ambiguousOriginal={...original,outcomeId:"ambiguous-outcome",canonicalResultId:ambiguousResult.canonicalResultId,resultDigest:ambiguousResult.resultDigest};const ambiguous=createAmazonProductsIdentityReassessment({artifact,originalOutcome:ambiguousOriginal,canonicalResult:ambiguousResult,atlasProduct,operator:"o",reason:"r",createdAt:at});assert.equal(ambiguous.newState,"MULTIPLE_COMPATIBLE_ASINS");assert.equal(ambiguous.sellersAuthorizationEligible,false);cases+=2;
 const conflictResult=createDataForSeoAmazonProviderResult({operation:"AMAZON_PRODUCTS",providerTaskId:"conflict",paidActionIntentId:"intent3",checkpointId:artifact.acceptanceArtifactId,atlasProductId:artifact.atlasProductId,productIndex:0,sourceRightsProfileDigest:artifact.sourceRightsProfileDigest,requestDigest:"d".repeat(64),operationResult:{result:[{items:[{...realItems[0],title:"CORSAIR Vengeance RGB DDR5 RAM 64GB 6000MHz CL38 (CMH32GX5M2B6000C38)"}]}]},retrievedAt:at}),conflictOriginal={...original,outcomeId:"conflict-outcome",canonicalResultId:conflictResult.canonicalResultId,resultDigest:conflictResult.resultDigest};assert.equal(createAmazonProductsIdentityReassessment({artifact,originalOutcome:conflictOriginal,canonicalResult:conflictResult,atlasProduct,operator:"o",reason:"r",createdAt:at}).newState,"ASIN_VARIANT_CONFLICT");cases++;
 const otherProduct=product("ram_other"),otherArtifact={...artifact,atlasProductId:"ram_other",acceptanceArtifactId:"artifact-other"},otherResult={...canonicalResult,checkpointId:"artifact-other",atlasProductId:"ram_other"},otherOriginal={...original,outcomeId:"other-outcome",artifactId:"artifact-other",canonicalResultId:otherResult.canonicalResultId,resultDigest:otherResult.resultDigest};assert.equal(createAmazonProductsIdentityReassessment({artifact:otherArtifact,originalOutcome:otherOriginal,canonicalResult:otherResult,atlasProduct:otherProduct,operator:"o",reason:"r",createdAt:at}).atlasProductId,"ram_other");cases++;
 const sellersRepo=new FileAmazonAcceptanceActionRepository({statePath:join(root,"sellers.json")});await sellersRepo.recordOutcome(original);await sellersRepo.recordAuthorization({authorizationId:"seller-auth",artifactId:artifact.acceptanceArtifactId,operation:"AMAZON_SELLERS",expiresAt:"2026-09-13T04:00:00Z",authorizedAt:at,predecessorAuthorizationId:null});const sellersService=new AmazonAcceptanceExecutionService({...service,actionRepository:sellersRepo});await assert.rejects(()=>sellersService.reassessProducts({artifactId:artifact.acceptanceArtifactId,operator:"o",reason:"r",confirmation:AMAZON_PRODUCTS_REASSESSMENT_CONFIRMATION}),/SELLERS_ALREADY_EXISTS/);cases++;
 const historyRepo=new FileAmazonAcceptanceActionRepository({statePath:join(root,"history-actions.json")});await historyRepo.recordOutcome(original);const historyService=new AmazonAcceptanceExecutionService({...service,actionRepository:historyRepo,historicalRepository:{getAll:async()=>[{provenance:{acquisitionChain:{productsTaskId:task.taskId}}}]}});await assert.rejects(()=>historyService.reassessProducts({artifactId:artifact.acceptanceArtifactId,operator:"o",reason:"r",confirmation:AMAZON_PRODUCTS_REASSESSMENT_CONFIRMATION}),/HISTORY_ALREADY_EXISTS/);cases++;
 const bytes=JSON.parse(await readFile(statePath,"utf8"));assert.deepEqual(bytes.outcomes,[original]);assert.equal(bytes.reassessments.length,1);cases+=2;
} finally { await rm(root,{recursive:true,force:true}); }
console.log(`DataForSEO Amazon Products reassessment tests passed: ${cases} cases.`);
