import assert from "node:assert/strict";
import { mkdtemp, rm } from "node:fs/promises";
import { join } from "node:path";
import { tmpdir } from "node:os";
import { AMAZON_ACCEPTANCE_ACTION_CONFIRMATIONS, AmazonAcceptanceExecutionService, FileAmazonAcceptanceActionRepository, createAmazonProductsIdentityReassessment, createDataForSeoAmazonProviderResult, defaultSourceRightsRegistry, prepareAmazonHistoricalAcceptance, projectEffectiveAmazonProductsOutcome, selectAmazonHistoricalAcceptanceProduct } from "../index.js";

let cases=0;
const now="2026-09-13T04:00:00.000Z",product={identity:{atlasProductId:"ram_h053_fixture",brand:"Corsair",manufacturerPartNumber:"CMH32GX5M2B6000C38"},governance:{lifecycleStatus:"ACTIVE",publicationStatus:"READY"},extension:{data:{capacity:{capacityGb:32,moduleCount:2},classification:{memoryType:"DDR5",formFactor:"DIMM"},performance:{dataRateMtps:6000,primaryTimings:"38-44-44-96"},physical:{color:"Black",rgbLighting:true}}}},selection=selectAmazonHistoricalAcceptanceProduct({atlasProducts:[product],destinations:[{destinationId:"destination",atlasProductId:product.identity.atlasProductId,retailerId:"RETAILER-0001",marketplace:"amazon.com",retailerListingId:"B0CQQVNCB6",status:"ACTIVE"}],historicalObservations:[]}),artifact=prepareAmazonHistoricalAcceptance({asOf:now,selection,rightsProfile:defaultSourceRightsRegistry.require("DATAFORSEO_AMAZON"),currentUtcDaySpendUsd:0}),productsTask={taskId:"products-task",kind:"AMAZON_PRODUCTS",checkpointId:artifact.acceptanceArtifactId,sourceId:"DATAFORSEO_AMAZON"},result=createDataForSeoAmazonProviderResult({operation:"AMAZON_PRODUCTS",providerTaskId:productsTask.taskId,paidActionIntentId:"products-intent",checkpointId:artifact.acceptanceArtifactId,atlasProductId:artifact.atlasProductId,productIndex:0,sourceRightsProfileDigest:artifact.sourceRightsProfileDigest,requestDigest:"a".repeat(64),operationResult:{result:[{items:[{data_asin:"B0CQQVNCB6",title:"Corsair Vengeance RGB DDR5 32GB 6000MHz CL38 Black CMH32GX5M2B6000C38"},{data_asin:"B0UNREL001",title:"G.SKILL DDR5 64GB F5-6000J3038F32GX2"}]}]},retrievedAt:now}),original={schemaVersion:"1.0",outcomeId:"original-outcome",artifactId:artifact.acceptanceArtifactId,authorizationId:"products-auth",canonicalResultId:result.canonicalResultId,resultDigest:result.resultDigest,state:"ASIN_VARIANT_CONFLICT",assessmentId:"original-assessment",governedAsin:null,nextPermittedAction:"STOP",sellersAuthorizationEligible:false,asinEnrichmentAuthorized:false,providerCallPerformed:false,actualSpendUsd:0},reassessment=createAmazonProductsIdentityReassessment({artifact,originalOutcome:original,canonicalResult:result,atlasProduct:product,operator:"operator:test",reason:"H051 correction",createdAt:now,corroboratingDestinationAsins:artifact.corroboratingDestinationAsins});

const root=await mkdtemp(join(tmpdir(),"h053-"));
try{
 const repo=new FileAmazonAcceptanceActionRepository({statePath:join(root,"actions.json")});await repo.recordOutcome(original);await repo.recordReassessment(reassessment);const tasks=[productsTask],service=new AmazonAcceptanceExecutionService({artifactRepository:{getById:async id=>id===artifact.acceptanceArtifactId?artifact:null},actionRepository:repo,productRepository:{getById:async id=>id===product.identity.atlasProductId?product:null},rightsRegistry:defaultSourceRightsRegistry,spendResolver:async()=>.0015,taskOwners:{},retrievalServices:{},resultRepository:{findByTask:async()=>result},taskLedger:{getAll:async()=>structuredClone(tasks)},consumptionRepository:{getAll:async()=>[]},historicalRepository:{getAll:async()=>[]},now:()=>now});
 const effective=await repo.getEffectiveOutcomeForArtifact(artifact.acceptanceArtifactId);assert.equal(effective.effectiveRecordType,"PRODUCTS_REASSESSMENT");assert.equal(effective.state,"STRONG_UNIQUE_ASIN");assert.equal(effective.governedAsin,"B0CQQVNCB6");assert.equal(effective.sellersAuthorizationEligible,true);assert.equal((await repo.getOutcomeById(original.outcomeId)).state,"ASIN_VARIANT_CONFLICT");cases+=5;
 const prepared=await service.authorize({artifactId:artifact.acceptanceArtifactId,operation:"AMAZON_SELLERS",operator:"operator:test",reason:"fixture readiness",expiresAt:"2026-09-13T04:15:00.000Z",confirmation:AMAZON_ACCEPTANCE_ACTION_CONFIRMATIONS.AUTHORIZE_SELLERS,asin:"B0INJECT01"}),auth=prepared.value,execution=auth.plan.decisions[0].execution;assert.equal(prepared.status,"RECORDED");assert.equal(execution.dataAsin,"B0CQQVNCB6");assert.equal(execution.source,"DATAFORSEO_AMAZON");assert.equal(execution.kind,"AMAZON_SELLERS");assert.equal(auth.maxTaskPriceUsd,.0015);assert.equal(auth.actualSpendUsd,0);assert.equal(auth.providerCallPerformed,false);cases+=7;
 assert.equal(["publicationAuthority","currentPriceAuthority","cheapestAuthority","pickAuthority","affiliateAuthority"].some(key=>key in auth),false);cases++;
 await assert.rejects(()=>service.authorize({artifactId:artifact.acceptanceArtifactId,operation:"AMAZON_SELLERS",operator:"operator:other",reason:"conflict",expiresAt:"2026-09-13T04:16:00.000Z",confirmation:AMAZON_ACCEPTANCE_ACTION_CONFIRMATIONS.AUTHORIZE_SELLERS}),/AUTHORIZATION_ACTIVE/);cases++;
 assert.throws(()=>projectEffectiveAmazonProductsOutcome(original,[reassessment,{...reassessment,reassessmentId:"competing"}]),/CONFLICT/);cases++;
 const blockedRepo=new FileAmazonAcceptanceActionRepository({statePath:join(root,"blocked.json")});await blockedRepo.recordOutcome(original);const blockedService=new AmazonAcceptanceExecutionService({...service,actionRepository:blockedRepo});await assert.rejects(()=>blockedService.authorize({artifactId:artifact.acceptanceArtifactId,operation:"AMAZON_SELLERS",operator:"operator:test",reason:"blocked",expiresAt:"2026-09-13T04:15:00.000Z",confirmation:AMAZON_ACCEPTANCE_ACTION_CONFIRMATIONS.AUTHORIZE_SELLERS}),/IDENTITY_NOT_STRONG/);cases++;
 const taskRepo=new FileAmazonAcceptanceActionRepository({statePath:join(root,"task.json")});await taskRepo.recordOutcome(original);await taskRepo.recordReassessment(reassessment);const taskService=new AmazonAcceptanceExecutionService({...service,actionRepository:taskRepo,taskLedger:{getAll:async()=>[productsTask,{taskId:"seller-task",kind:"AMAZON_SELLERS",checkpointId:artifact.acceptanceArtifactId,sourceId:"DATAFORSEO_AMAZON"}]}});await assert.rejects(()=>taskService.authorize({artifactId:artifact.acceptanceArtifactId,operation:"AMAZON_SELLERS",operator:"operator:test",reason:"duplicate",expiresAt:"2026-09-13T04:15:00.000Z",confirmation:AMAZON_ACCEPTANCE_ACTION_CONFIRMATIONS.AUTHORIZE_SELLERS}),/ALREADY_USED/);cases++;
}finally{await rm(root,{recursive:true,force:true});}
console.log(`DataForSEO Amazon Sellers reassessment-readiness tests passed: ${cases} cases.`);
