import assert from"node:assert/strict";import{performance}from"node:perf_hooks";import{selectScaleRampCanary,projectProductionScaleRampCanary}from"../index.js";
const base=(id,i=0)=>({atlasProductId:id,manufacturer:["Corsair","Crucial","G.SKILL","Kingston","TeamGroup"][i%5],memoryGeneration:i%4?"DDR5":"DDR4",formFactor:i%3?"DIMM":"SO_DIMM",capacityGb:[8,16,32,64][i%4],moduleCount:i%3?2:1}),input=(candidates,size=3,extra={})=>({stageId:"scale-100",stageCohortDigest:"a".repeat(64),source:"DATAFORSEO_AMAZON",operation:"AMAZON_PRODUCTS",requestedCanarySize:size,candidates,...extra});let cases=0;
const rows=Array.from({length:12},(_,i)=>base(`ram_${String(i).padStart(2,"0")}`,i)),a=selectScaleRampCanary(input(rows)),b=selectScaleRampCanary(input([...rows].reverse()));assert.deepEqual(a,b);assert.equal(a.authority,"NONE");assert.equal(a.selectedMembers.length,3);cases+=3;
for(const field of["affiliateCommission","retailerPreference","expectedProviderSuccess","priorYield"]){assert.throws(()=>selectScaleRampCanary(input([{...rows[0],[field]:1}],1)),/CANDIDATE_INPUT_INVALID/);cases++}
assert.throws(()=>selectScaleRampCanary(input([rows[0],rows[0]],1)),/DUPLICATE/);assert.throws(()=>selectScaleRampCanary(input([{...rows[0],manufacturer:""}],1)),/MANUFACTURER/);assert.throws(()=>selectScaleRampCanary(input(rows,0)),/SIZE/);assert.throws(()=>selectScaleRampCanary(input(rows,13)),/EXCEEDS/);assert.equal(selectScaleRampCanary(input(rows,12)).selectedMembers.length,12);cases+=5;
assert.throws(()=>selectScaleRampCanary(input(rows,3,{policyVersion:"2.0"})),/VERSION_UNSUPPORTED/);assert.notEqual(selectScaleRampCanary(input(rows)).candidatePoolDigest,selectScaleRampCanary(input([...rows,base("ram_new",13)])).candidatePoolDigest);assert.notEqual(selectScaleRampCanary(input(rows,3)).selectedMemberDigest,selectScaleRampCanary(input(rows,4)).selectedMemberDigest);cases+=3;
const google=selectScaleRampCanary({...input(rows),source:"DATAFORSEO_GOOGLE_SHOPPING",operation:"SELLERS"});assert.notEqual(google.candidatePoolDigest,a.candidatePoolDigest);cases++;
const imbalanced=[...Array.from({length:20},(_,i)=>({...base(`ram_big_${i}`,1),manufacturer:"Large"})),base("ram_single",2)];assert.equal(selectScaleRampCanary(input(imbalanced,2)).selectedMembers.some(x=>x.atlasProductId==="ram_single"),true);assert.equal(selectScaleRampCanary(input(rows.filter(x=>x.manufacturer==="Corsair"),1)).strataSummary.length>=1,true);cases+=2;
for(const size of[10,100,1000,10000]){const fixture=Array.from({length:size},(_,i)=>base(`ram_scale_${size}_${String(i).padStart(5,"0")}`,i)),start=performance.now(),first=selectScaleRampCanary(input(fixture,Math.min(10,size))),elapsed=performance.now()-start,replay=selectScaleRampCanary(input(fixture,Math.min(10,size)));assert.equal(first.selectedMemberDigest,replay.selectedMemberDigest);console.log(`Scale-ramp selector ${size}: strata=${first.strataSummary.length} selected=${first.selectedMembers.length} elapsedMs=${elapsed.toFixed(2)}`);cases++}
const products=new Map(rows.map(x=>[x.atlasProductId,{identity:{atlasProductId:x.atlasProductId,brand:x.manufacturer},extension:{data:{classification:{memoryType:x.memoryGeneration,formFactor:x.formFactor},capacity:{capacityGb:x.capacityGb,moduleCount:x.moduleCount}}}}]));
const artifact={status:"REVIEW_ONLY",cohortId:"fixture",atlasProductIds:rows.map(x=>x.atlasProductId)},productRepository={getById:async id=>products.get(id)},readinessOwner={assess:async({atlasProductId})=>({readinessState:atlasProductId==="ram_00"?"REVIEW_REQUIRED":"READY_FOR_DISCOVERY"})},destinationRecords=rows.slice(1).map(x=>({atlasProductId:x.atlasProductId,retailerId:"RETAILER-0001"}));const fs=await import("node:fs/promises"),os=await import("node:os"),path=await import("node:path"),root=await fs.mkdtemp(path.join(os.tmpdir(),"canary-selector-")),file=path.join(root,"stage.json");try{await fs.writeFile(file,JSON.stringify(artifact));const projected=await projectProductionScaleRampCanary({stageArtifactPath:file,source:"DATAFORSEO_AMAZON",operation:"AMAZON_PRODUCTS",requestedCanarySize:3,asOf:"2026-09-16T00:00:00.000Z",productRepository,readinessOwner,destinationRecords});assert.equal(projected.candidateCount,11);assert.equal(projected.selectedMembers.some(x=>x.atlasProductId==="ram_00"),false);cases+=2}finally{await fs.rm(root,{recursive:true,force:true})}
console.log(`Deterministic scale-ramp canary selector tests passed (${cases} cases).`);
