import assert from "node:assert/strict";
import {mkdtemp,rm} from "node:fs/promises";
import {join} from "node:path";
import {tmpdir} from "node:os";
import crypto from "node:crypto";
import {NeutralBoundedPaidActionCoordinator,ProductsIdentityDiscoveryDomainAdapter,SqliteNeutralBoundedRepository} from "../index.js";

let cases=0;const eq=(a,b)=>{assert.deepEqual(a,b);cases++};
const cycle="2026-09-15T02:29:36.569Z",expiry="2026-09-15T02:54:29.003Z",now="2026-09-15T04:00:00.000Z";
async function fixture({available=false,cached=false,failed=false}={}){
 const root=await mkdtemp(join(tmpdir(),"disposition-continuation-")),repository=new SqliteNeutralBoundedRepository({databasePath:join(root,"bounded.sqlite")}),products=["ram_corsair_cmh32gx5m2b6400c36","ram_corsair_cmh32gx5m2e6000c36w","ram_corsair_cmk16gx5m2b5200z40"],members=products.map((atlasProductId,index)=>({memberKey:`DATAFORSEO_GOOGLE_SHOPPING:${atlasProductId}:${index}`,domainMemberId:`domain-${index}`,atlasProductId,source:"DATAFORSEO_GOOGLE_SHOPPING",operation:"PRODUCTS",taskCeilingUsd:.001,identityStateDigest:"a".repeat(64),rightsDigest:"b".repeat(64),state:"READY",paidTaskCreated:false,providerTaskId:null})),plan={schemaVersion:"1.0",planId:"plan",bindingDigest:"c".repeat(64),cohortDigest:"d".repeat(64),cycle,ready:members,blocked:[],requested:members,maximumPaidTasks:3,maximumSpendUsd:.003},parent={schemaVersion:"1.0",authorizationId:"parent",planId:"plan",planBindingDigest:plan.bindingDigest,bindingDigest:"e".repeat(64),authorizedAt:cycle,expiresAt:expiry,automaticPaidRetries:0};repository.recordPlan(plan);repository.recordAuthorization(parent);
 const children=members.map((member,index)=>({parentAuthorizationId:"parent",parentAuthorizationDigest:parent.bindingDigest,planId:"plan",memberKey:member.memberKey,domainMemberId:member.domainMemberId,source:member.source,operation:member.operation,maximumTaskCostUsd:.001,childAuthorizationId:`child-${index}`,childAuthorizationDigest:"f".repeat(64),automaticPaidRetries:0,expiresAt:expiry,bindingDigest:`${index}`.repeat(64)}));for(const child of children)repository.recordChildAuthority(child);
 const runMembers=members.map((member,index)=>({...member,state:index===0?"WAITING":"EXCEPTION",authorizationId:children[index].childAuthorizationId,childAuthorityBinding:children[index],paidTaskCreated:index===0,providerTaskId:index===0?"09150240-2304-0179-0000-1a3ea3892cdb":null,actualSpendUsd:index===0?.001:0,exception:index===0?null:"ACQUISITION_DAILY_SPEND_SNAPSHOT_DRIFT"}));repository.startRun({schemaVersion:"1.0",runId:"run",planId:"plan",authorizationId:"parent",cycle,state:"WAITING_FOR_PROVIDER",startedAt:cycle,members:runMembers});
 const stable=value=>Array.isArray(value)?`[${value.map(stable).join(",")}]`:value&&typeof value==="object"?`{${Object.keys(value).sort().map(key=>`${JSON.stringify(key)}:${stable(value[key])}`).join(",")}}`:JSON.stringify(value),digest=value=>crypto.createHash("sha256").update(stable(value)).digest("hex");for(let index=1;index<3;index++){const member=runMembers[index],child=children[index],material={assessmentBindingDigest:`assessment-${index}`,dispositionState:"EXPIRED_CONSUMED_WITHOUT_TASK",disposedAt:now,operator:"operator:fixture",reason:"fixture disposition"},bindingDigest=digest(material);repository.recordChildDisposition({schemaVersion:"1.0",policyVersion:"MERCURY-TASKLESS-CHILD-DISPOSITION-1.0",dispositionId:`mer_tasklessdisp_${bindingDigest.slice(0,24)}`,...material,state:"EXPIRED_CONSUMED_WITHOUT_TASK",childAuthorizationId:child.childAuthorizationId,memberKey:member.memberKey,domainMemberId:member.domainMemberId,atlasProductId:member.atlasProductId,source:member.source,operation:member.operation,paidAuthority:false,providerExecutionAuthority:false,retryAuthority:false,replacementAuthority:false,sellersAuthority:false,downstreamAuthority:false,bindingDigest});}
 let executeCalls=0,resolveCalls=0,retrievalCalls=0,finalizeCalls=0;const owner={prepare:async()=>({}),authorize:async()=>({}),execute:async()=>{executeCalls++;throw new Error("EXECUTE_FORBIDDEN")},resolveTask:async({member})=>{resolveCalls++;return member.memberKey===members[0].memberKey?{providerTaskId:"09150240-2304-0179-0000-1a3ea3892cdb",actualSpendUsd:.001}:null},retrieve:async()=>{if(cached)return{status:"AVAILABLE",canonicalResult:{canonicalResultId:"cached-result"}};retrievalCalls++;if(failed)return{status:"FAILED"};return available?{status:"AVAILABLE",canonicalResult:{canonicalResultId:"result"}}:{status:"PENDING"}},finalize:async()=>{finalizeCalls++;return{state:"IDENTITY_RESOLVED",assessmentId:"assessment",providerResultId:"result"}}};
 const adapter=new ProductsIdentityDiscoveryDomainAdapter({productRepository:{getById:async()=>({})},readinessOwner:{assess:async()=>({})},rightsRegistry:{require:()=>({})},sourceOwners:{DATAFORSEO_GOOGLE_SHOPPING:owner,DATAFORSEO_AMAZON:owner},boundedRepository:repository}),coordinator=new NeutralBoundedPaidActionCoordinator({repository,domainAdapter:adapter,spendResolver:async()=>.001,now:()=>now,policyVersion:"MERCURY-PRODUCTS-IDENTITY-DISCOVERY-1.0"});return{root,repository,coordinator,counters:()=>({executeCalls,resolveCalls,retrievalCalls,finalizeCalls}),runBefore:repository.getRun("run")};
}

const fixtures=[];try{
 let f=await fixture();fixtures.push(f);let result=await f.coordinator.resume({runId:"run",resumedBy:"fixture"});eq(result.state,"WAITING_FOR_PROVIDER");eq(f.counters(),{executeCalls:0,resolveCalls:0,retrievalCalls:1,finalizeCalls:0});result=await f.coordinator.resume({runId:"run",resumedBy:"fixture"});eq(result.state,"WAITING_FOR_PROVIDER");eq(f.counters(),{executeCalls:0,resolveCalls:0,retrievalCalls:2,finalizeCalls:0});eq(f.repository.getRun("run").members.slice(1).map(x=>[x.state,x.exception]),f.runBefore.members.slice(1).map(x=>[x.state,x.exception]));
 f=await fixture({available:true});fixtures.push(f);result=await f.coordinator.resume({runId:"run",resumedBy:"fixture"});eq(result.state,"COMPLETED_WITH_EXCEPTIONS");eq(result.identitiesResolved,1);eq(f.counters(),{executeCalls:0,resolveCalls:0,retrievalCalls:1,finalizeCalls:1});eq(f.repository.getRun("run").members[0].providerTaskId,"09150240-2304-0179-0000-1a3ea3892cdb");eq(f.repository.getRun("run").members.slice(1).every(x=>x.state==="EXCEPTION"),true);
 f=await fixture({cached:true});fixtures.push(f);await f.coordinator.resume({runId:"run",resumedBy:"fixture"});eq(f.counters(),{executeCalls:0,resolveCalls:0,retrievalCalls:0,finalizeCalls:1});
 f=await fixture({failed:true});fixtures.push(f);result=await f.coordinator.resume({runId:"run",resumedBy:"fixture"});eq(result.state,"COMPLETED_WITH_EXCEPTIONS");eq(f.repository.getRun("run").members.every(x=>x.state==="EXCEPTION"),true);eq(f.counters().executeCalls,0);
}finally{for(const f of fixtures){f.repository.close();await rm(f.root,{recursive:true,force:true,maxRetries:5,retryDelay:50});}}
console.log(`Disposition-aware existing-task continuation tests passed: ${cases} cases.`);
