import assert from "node:assert/strict";
import {mkdtemp,readFile,rm} from "node:fs/promises";
import {tmpdir} from "node:os";
import {join} from "node:path";
import {CertifiedMercuryOperationsExporter,ProductionForgeCohortOperationsProvider,SqliteNeutralBoundedRepository} from "../index.js";
import {CertifiedMercuryOperationsPanel} from "../../../apps/forge/components/CertifiedMercuryOperationsPanel.js";

class Element{constructor(){this.textContent="";this.className="";this.children=[];this.files=[];}addEventListener(){}replaceChildren(...children){this.children=children;}querySelector(selector){return this.map[selector];}}
const at="2026-09-15T12:00:00.000Z",later="2026-09-15T13:00:00.000Z",rootPath=await mkdtemp(join(tmpdir(),"forge-p1b-e2e-"));
try{
 const databasePath=join(rootPath,"bounded.sqlite"),repository=new SqliteNeutralBoundedRepository({databasePath}),definitions=[
  ["ram_routine","COMPLETED","STRONG_UNIQUE_ASIN",false,null],
  ["ram_review","COMPLETED","INSUFFICIENT_ASIN_EVIDENCE",true,null],
  ["ram_unresolved","COMPLETED","KNOWN_UNRESOLVED",false,null],
  ["ram_systemic","FAILED","FAILED",false,"REPOSITORY_INTEGRITY_FAILURE"]
 ],ready=definitions.map(([atlasProductId])=>({memberKey:`${atlasProductId}:DATAFORSEO_AMAZON`,domainMemberId:atlasProductId,atlasProductId,source:"DATAFORSEO_AMAZON",operation:"PRODUCTS",taskCeilingUsd:.0015}));
 repository.recordPlan({planId:"plan-e2e",bindingDigest:"a".repeat(64),cycle:at,requested:ready,ready,blocked:[],maximumSpendUsd:.006});repository.recordAuthorization({authorizationId:"auth-e2e",planId:"plan-e2e",authorizedAt:at,expiresAt:later,bindingDigest:"b".repeat(64)});repository.startRun({runId:"run-e2e",planId:"plan-e2e",authorizationId:"auth-e2e",state:"STOPPED",systemicFailure:true,systemicFailureReason:"REPOSITORY_INTEGRITY_FAILURE",members:definitions.map(([atlasProductId,state,outcome,h052ReviewAvailable,systemicFailureReason],index)=>({...ready[index],state,outcome,h052ReviewAvailable,systemicFailureReason,systemicFailure:Boolean(systemicFailureReason),assessmentId:h052ReviewAvailable?"h051-e2e":null,providerResultId:`result-${index}`,providerTaskId:`task-${index}`,actualSpendUsd:.0015}))});repository.close();
 const products=definitions.map(([atlasProductId])=>({identity:{atlasProductId,displayName:atlasProductId,brand:"Fixture",manufacturerPartNumber:atlasProductId.toUpperCase(),productType:"ram"}})),owner=value=>({getAll:async()=>structuredClone(value)}),outputPath=join(rootPath,"certified.json"),exported=await new CertifiedMercuryOperationsExporter({productRepository:owner(products),retailerRepository:owner([]),evidenceRepository:owner([]),historicalRepository:owner([]),identityDecisionRepository:{...owner([]),getAllRemediations:async()=>[]},canonicalObservationRepository:owner([]),reviewRepository:{getEffectiveDecision:async()=>null},publicationRepository:{getEffectiveDecision:async()=>null},cadencePolicyRepository:{getAllPolicies:async()=>[]},operationalContextProvider:{load:async()=>({refreshPlans:[],authorizations:[],executionRuns:[],consumptionState:{schemaVersion:"1.0",consumed:[]},refreshResults:[],identityReuseAssessments:[]})},cohortOperationsProvider:new ProductionForgeCohortOperationsProvider({boundedDatabasePath:databasePath})}).export({asOf:at,outputPath});
 const artifact=JSON.parse(await readFile(outputPath,"utf8")),cohort=artifact.cohortOperations.cohorts[0];assert.equal(exported.artifactPath,outputPath);assert.equal(artifact.schemaVersion,"1.1");assert.equal(cohort.members.length,4);assert.deepEqual(cohort.members.map(member=>member.classification),["GOVERNED_REVIEW_AVAILABLE","ROUTINE_SUCCESS","SYSTEMIC_ATTENTION","SAFELY_UNRESOLVED"]);assert.equal(cohort.members.find(member=>member.review.eligible).review.type,"H052");assert.equal(cohort.cost.actualSpendUsd,.006);assert.ok(cohort.members.every(member=>Object.values(member.downstreamAuthority).every(value=>value===false)));
 const root=new Element();root.map={"#certifiedMercuryProjectionFile":new Element(),"#certifiedMercuryProjectionStatus":new Element(),"#certifiedMercuryProjectionSummary":new Element(),"#certifiedMercuryProjectionCohortStatus":new Element(),"#certifiedMercuryProjectionCohorts":new Element(),"#certifiedMercuryProjectionProducts":new Element(),"#certifiedMercuryProjectionDetails":new Element()};globalThis.document={createElement:()=>new Element()};new CertifiedMercuryOperationsPanel(root).render(artifact);assert.equal(root.map["#certifiedMercuryProjectionCohorts"].children.length,1);assert.match(root.map["#certifiedMercuryProjectionCohorts"].children[0].textContent,/H052/);assert.match(root.map["#certifiedMercuryProjectionCohorts"].children[0].textContent,/Systemic YES/);assert.match(root.map["#certifiedMercuryProjectionCohorts"].children[0].textContent,/No downstream authority/);
 console.log("Forge cohort operations end-to-end tests passed (12 cases).");
}finally{await rm(rootPath,{recursive:true,force:true,maxRetries:5,retryDelay:100}).catch(error=>{if(error?.code!=="EBUSY")throw error;});}
