import assert from "node:assert/strict";
import {mkdtemp,rm} from "node:fs/promises";
import {tmpdir} from "node:os";
import {join} from "node:path";
import {BOUNDED_MEMBER_STATES,FileDataForSeoPrepareArtifactRepository,NeutralBoundedPaidActionCoordinator,ProductsIdentityDiscoveryDomainAdapter,ProductsIdentityDiscoveryService,PRODUCTS_DISCOVERY_CONFIRMATIONS,PRODUCTS_DISCOVERY_STATES,SqliteNeutralBoundedRepository,createBoundedChildAuthorityBinding,createDataForSeoPrepareArtifact,neutralBoundedDigest} from "../index.js";

const at="2026-09-14T12:00:00.000Z",expiresAt="2026-09-14T13:00:00.000Z",product={identity:{atlasProductId:"ram_fixture_recovery",manufacturerPartNumber:"MPN-RECOVERY"}};
let cases=0;const eq=(actual,expected)=>{assert.deepEqual(actual,expected);cases++;};
function childFor(member,authorization){const material={member:member.domainMemberId,parent:authorization.authorizationId},authorizationId=`child:${neutralBoundedDigest(material).slice(0,20)}`,plan={planId:`plan:${member.domainMemberId}`,approvedTaskCount:1,estimatedApprovedSpendUsd:.001};return{authorizationId,authorizationDigest:neutralBoundedDigest(material),expiresAt:authorization.expiresAt,authorizationRequest:{schemaVersion:"1.1",requestId:authorizationId,createdAt:at,expiresAt:authorization.expiresAt,maxSpendUsd:.001,maxPaidTasks:1,automaticPaidRetries:0,plan}};}
function artifactFor(member,authorization,child,binding){return createDataForSeoPrepareArtifact({operation:"PRODUCTS",atlasProductId:member.atlasProductId,boundedChildAuthority:{...binding,planDigest:authorization.planBindingDigest,atlasProductId:member.atlasProductId,rightsDigest:member.rightsDigest},prepareArtifact:child.authorizationRequest.plan,authorizationRequest:child.authorizationRequest,preparedAt:child.authorizationRequest.createdAt});}
async function fixture(name,{existingTask=false,amazon=false}={}){const root=await mkdtemp(join(tmpdir(),`google-child-${name}-`)),repository=new SqliteNeutralBoundedRepository({databasePath:join(root,"bounded.sqlite")}),artifacts=new FileDataForSeoPrepareArtifactRepository({statePath:join(root,"prepare-artifacts.json")}),tasks=new Map(),calls={authorize:0,execute:0};let authorization;
 const owner={prepare:async({rightsProfile})=>({rightsDigest:rightsProfile.bindingDigest,requestIdentity:"MPN-RECOVERY",sourcePayload:{keyword:"MPN-RECOVERY"}}),authorize:async({member,parentAuthorization})=>{calls.authorize++;const child=childFor(member,parentAuthorization);return amazon?{...child,durableAuthority:true}:child;},execute:async({member,authorizationRequest})=>{calls.execute++;if(!amazon)eq(authorizationRequest.requestId,childFor(member,authorization).authorizationId);tasks.set(member.memberKey,{providerTaskId:`task:${member.domainMemberId}`,actualSpendUsd:amazon?.0015:.001});return{status:"COMPLETED"};},resolveTask:async({member})=>tasks.get(member.memberKey)??null,retrieve:async()=>({status:"AVAILABLE",canonicalResult:{canonicalResultId:"result:fixture"}}),finalize:async()=>({state:amazon?"STRONG_UNIQUE_ASIN":"IDENTITY_RESOLVED",assessmentId:"assessment:fixture"})};
 const source=amazon?"DATAFORSEO_AMAZON":"DATAFORSEO_GOOGLE_SHOPPING",adapter=new ProductsIdentityDiscoveryDomainAdapter({productRepository:{getById:async id=>id===product.identity.atlasProductId?product:null},readinessOwner:{assess:async()=>({state:PRODUCTS_DISCOVERY_STATES.READY,bindingDigest:"c".repeat(64)})},rightsRegistry:{require:()=>({bindingDigest:"d".repeat(64)})},sourceOwners:{DATAFORSEO_GOOGLE_SHOPPING:owner,DATAFORSEO_AMAZON:owner},boundedRepository:repository,childAuthorizationArtifactRepository:artifacts,now:()=>at}),coordinator=new NeutralBoundedPaidActionCoordinator({repository,domainAdapter:adapter,spendResolver:async()=>0,now:()=>at,dailySpendCeilingUsd:.025,policyVersion:"MERCURY-PRODUCTS-IDENTITY-DISCOVERY-1.0"}),service=new ProductsIdentityDiscoveryService({coordinator}),prepared=await service.prepare({cycle:at,cohort:[{atlasProductId:product.identity.atlasProductId,sourceId:source}]}),authorized=await service.authorize({planId:prepared.value.planId,operator:"fixture",reason:"recovery",expiresAt,confirmation:PRODUCTS_DISCOVERY_CONFIRMATIONS.AUTHORIZE});authorization=authorized.value;const member=prepared.value.ready[0];if(existingTask)tasks.set(member.memberKey,{providerTaskId:`task:${member.domainMemberId}`,actualSpendUsd:.001});return{root,repository,artifacts,calls,service,authorization,member};}
async function close(value){value.repository.close();await rm(value.root,{recursive:true,force:true}).catch(()=>{});}
function startRun(value,runId,member){value.repository.startRun({schemaVersion:"1.0",runId,planId:value.authorization.planId,authorizationId:value.authorization.authorizationId,cycle:at,state:"RUNNING",startedAt:at,members:[{...member,exception:null}]});}
async function persistChild(value){const child=childFor(value.member,value.authorization),binding=createBoundedChildAuthorityBinding({parentAuthorization:value.authorization,member:value.member,childAuthorizationId:child.authorizationId,childAuthorizationDigest:child.authorizationDigest,expiresAt:child.expiresAt}),artifact=await value.artifacts.record(artifactFor(value.member,value.authorization,child,binding)),reference={...binding,authorizationArtifactId:artifact.prepareArtifactId,authorizationArtifactDigest:artifact.bindingDigest};return{child,binding,artifact,reference};}

for(const size of[10,100,1000,10000]){const authorization={authorizationId:`auth:scale:${size}`,bindingDigest:"a".repeat(64),planId:`plan:scale:${size}`,planBindingDigest:"b".repeat(64),expiresAt},ids=new Set();for(let index=0;index<size;index++){const atlasProductId=`ram_scale_${size}_${index}`,member={memberKey:`member:${size}:${index}`,domainMemberId:`domain:${size}:${index}`,source:"DATAFORSEO_GOOGLE_SHOPPING",operation:"PRODUCTS",taskCeilingUsd:.001,atlasProductId,rightsDigest:"d".repeat(64)},child=childFor(member,authorization),binding=createBoundedChildAuthorityBinding({parentAuthorization:authorization,member,childAuthorizationId:child.authorizationId,childAuthorizationDigest:child.authorizationDigest,expiresAt});ids.add(artifactFor(member,authorization,child,binding).prepareArtifactId);}eq(ids.size,size);}

const before=await fixture("before");try{const x=await persistChild(before);eq((await before.artifacts.record(x.artifact)).prepareArtifactId,x.artifact.prepareArtifactId);eq((await before.artifacts.getByBoundedMember(before.authorization.authorizationId,before.member.memberKey)).bindingDigest,x.artifact.bindingDigest);await assert.rejects(()=>before.artifacts.record({...x.artifact,bindingDigest:"f".repeat(64)}),/PREPARE_ARTIFACT_CONFLICT/);cases++;startRun(before,"run:before",{...before.member,state:BOUNDED_MEMBER_STATES.READY,childAuthorityBinding:null});const resumed=await before.service.resume({runId:"run:before",resumedBy:"fixture",confirmation:PRODUCTS_DISCOVERY_CONFIRMATIONS.RESUME});eq(resumed.state,"COMPLETED");eq(before.calls.authorize,0);eq(before.calls.execute,1);eq(before.repository.getChildAuthority(before.authorization.authorizationId,before.member.memberKey).authorizationArtifactId,x.artifact.prepareArtifactId);}finally{await close(before);}

const after=await fixture("after");try{const x=await persistChild(after);after.repository.recordChildAuthority({...x.reference,childAuthorizationId:x.child.authorizationId});startRun(after,"run:after",{...after.member,state:BOUNDED_MEMBER_STATES.AUTHORIZED,authorizationId:x.child.authorizationId,childAuthorityBinding:x.reference});eq((await after.service.resume({runId:"run:after",resumedBy:"fixture",confirmation:PRODUCTS_DISCOVERY_CONFIRMATIONS.RESUME})).state,"COMPLETED");eq(after.calls.execute,1);eq((await after.service.resume({runId:"run:after",resumedBy:"fixture",confirmation:PRODUCTS_DISCOVERY_CONFIRMATIONS.RESUME})).state,"COMPLETED");eq(after.calls.execute,1);}finally{await close(after);}

const existing=await fixture("existing",{existingTask:true});try{const x=await persistChild(existing);existing.repository.recordChildAuthority({...x.reference,childAuthorizationId:x.child.authorizationId});startRun(existing,"run:existing",{...existing.member,state:BOUNDED_MEMBER_STATES.AUTHORIZED,authorizationId:x.child.authorizationId,childAuthorityBinding:x.reference});eq((await existing.service.resume({runId:"run:existing",resumedBy:"fixture",confirmation:PRODUCTS_DISCOVERY_CONFIRMATIONS.RESUME})).state,"COMPLETED");eq(existing.calls.execute,0);}finally{await close(existing);}

const missing=await fixture("missing");try{startRun(missing,"run:missing",{...missing.member,state:BOUNDED_MEMBER_STATES.AUTHORIZED,authorizationId:"child:missing",childAuthorityBinding:null});await assert.rejects(()=>missing.service.resume({runId:"run:missing",resumedBy:"fixture",confirmation:PRODUCTS_DISCOVERY_CONFIRMATIONS.RESUME}),/BOUNDED_RESUME_NEW_PAID_TASK_FORBIDDEN/);cases++;eq(missing.calls.execute,0);}finally{await close(missing);}

const amazon=await fixture("amazon",{amazon:true});try{const result=await amazon.service.start({authorizationId:amazon.authorization.authorizationId,startedBy:"fixture",confirmation:PRODUCTS_DISCOVERY_CONFIRMATIONS.START});eq(result.state,"COMPLETED");eq(amazon.calls.execute,1);eq(result.sellersTasksCreated,0);eq(result.publicationAuthority,false);eq(result.currentPriceAuthority,false);}finally{await close(amazon);}
console.log(`Google Products child authorization recovery tests passed: ${cases} cases.`);
