import assert from "node:assert/strict";
import { mkdtemp, readFile, rm } from "node:fs/promises";
import os from "node:os";
import path from "node:path";
import { createProductInfoEnrichmentAuthorizationRequest, FileProductInfoResultRepository, ProductInfoResultRetrievalService } from "../index.js";

const atlasProduct=JSON.parse(await readFile(new URL("../../atlas/products/ram/ddr5/HR-RAM-DDR5-000002-crucial-crucial-pro-cp2k16g56c46u5.json",import.meta.url),"utf8"));
const ids={productId:"4796965035927175117",dataDocId:"9225099931765836490",gid:"4027682025249817743"},taskId="product-info-task",sourceTaskId="products-task";
const proposal={proposalId:"proposal",status:"PENDING_OPERATOR_REVIEW",sourceTaskId,atlasProductId:atlasProduct.identity.atlasProductId,operation:"PRODUCT_INFO",estimatedCostUsd:.001,maxPaidTasks:1,automaticPaidRetries:0,providerIdentity:ids,providerSelectionLineage:{equivalenceAssessmentId:"assessment",equivalenceGroupDigest:"group",selectionDecisionId:"selection",sourceProductsReviewId:"review"},governanceBinding:{canonicalMpn:atlasProduct.identity.manufacturerPartNumber,providerRequest:{locationName:"United States",languageName:"English"}}};
const authorization=createProductInfoEnrichmentAuthorizationRequest({proposal,createdAt:"2026-09-03T00:00:00Z"}),taskLedger=[{kind:"PRODUCTS",taskId:sourceTaskId},{kind:"PRODUCT_INFO",taskId}],executionRuns=[{runId:"run",planId:authorization.planId,status:"COMPLETED",attemptedTasks:1,completedTasks:1,failedTasks:0,tasks:[{outcome:"COMPLETED",providerTaskId:taskId}]}],authorizationConsumptions=[{authorizationId:authorization.requestId,planId:authorization.planId,consumedAt:"2026-09-03T00:01:00Z"}];
const specs=[{specification_name:"Manufacturer Part Number",specification_value:"CP2K16G56C46U5"},{specification_name:"Brand",specification_value:"Crucial"},{specification_name:"Memory Type",specification_value:"DDR5"},{specification_name:"Capacity",specification_value:"32 GB"},{specification_name:"Number of Modules",specification_value:"2"},{specification_name:"Capacity per Module",specification_value:"16 GB"},{specification_name:"Memory Speed",specification_value:"5600 MT/s"},{specification_name:"Form Factor",specification_value:"DIMM"}],item=(changes={})=>({title:"Crucial Pro CP2K16G56C46U5 32GB DDR5 5600",product_id:ids.productId,data_docid:ids.dataDocId,gid:ids.gid,brand:"Crucial",specifications:specs,...changes}),result=value=>({id:taskId,status_code:20000,cost:0,result:[{items:value}]}),base={taskId,productInfoAuthorization:authorization,productInfoProposal:proposal,taskLedger,executionRuns,authorizationConsumptions,atlasProduct};
const root=await mkdtemp(path.join(os.tmpdir(),"hr-product-info-result-"));
try{
 let calls=0;const repository=new FileProductInfoResultRepository({statePath:path.join(root,"results.json")}),service=new ProductInfoResultRetrievalService({retriever:async requested=>{calls++;assert.equal(requested,taskId);return result([item()]);},resultRepository:repository,now:()=>"2026-09-03T00:02:00Z"});
 await assert.rejects(()=>service.retrieve({...base,taskId:""}),/TASK_ID_REQUIRED/);assert.equal(calls,0);
 await assert.rejects(()=>service.retrieve({...base,taskId:"unknown"}));assert.equal(calls,0);
 await assert.rejects(()=>service.retrieve({...base,taskLedger:taskLedger.map(value=>value.taskId===taskId?{...value,kind:"SELLERS"}:value)}),/OPERATION_MISMATCH/);assert.equal(calls,0);
 for(const changed of [{executionRuns:[]},{authorizationConsumptions:[]},{productInfoProposal:{...proposal,proposalId:"wrong"}},{productInfoAuthorization:{...authorization,proposalId:"wrong"}}])await assert.rejects(()=>service.retrieve({...base,...changed}));assert.equal(calls,0);
 const received=await service.retrieve(base);assert.equal(received.status,"RESULT_RECEIVED");assert.equal(received.sellersReadiness,"READY_FOR_SELLERS");assert.equal(received.result.providerIdentity.dataDocId,ids.dataDocId);assert.equal(received.result.downstreamAuthority.sellersExecution,false);assert.equal(received.actualSpendUsd,0);assert.equal(calls,1);
 const replay=await service.retrieve(base);assert.equal(replay.status,"DUPLICATE");assert.equal(replay.result.resultId,received.result.resultId);assert.equal((JSON.parse(await readFile(path.join(root,"results.json"),"utf8"))).results.length,1);
 const pending=new ProductInfoResultRetrievalService({retriever:async()=>{throw new Error("DATAFORSEO_TASK_ERROR:40602");},resultRepository:new FileProductInfoResultRepository({statePath:path.join(root,"pending.json")})});assert.equal((await pending.retrieve(base)).status,"PROVIDER_PENDING");
 const noResult=new ProductInfoResultRetrievalService({retriever:async()=>result([]),resultRepository:new FileProductInfoResultRepository({statePath:path.join(root,"empty.json")})});assert.equal((await noResult.retrieve(base)).status,"NO_RESULT");
 const malformed=new ProductInfoResultRetrievalService({retriever:async()=>({id:taskId,result:[{}]}),resultRepository:new FileProductInfoResultRepository({statePath:path.join(root,"malformed.json")})});await assert.rejects(()=>malformed.retrieve(base),/MALFORMED/);
 const drift=new ProductInfoResultRetrievalService({retriever:async()=>result([item({data_docid:"other"})]),resultRepository:new FileProductInfoResultRepository({statePath:path.join(root,"drift.json")})});await assert.rejects(()=>drift.retrieve(base),/DRIFT/);
 const contradicted=new ProductInfoResultRetrievalService({retriever:async()=>result([item({brand:"Kingston",specifications:specs.map(value=>value.specification_name==="Brand"?{...value,specification_value:"Kingston"}:value)})]),resultRepository:new FileProductInfoResultRepository({statePath:path.join(root,"contradicted.json")}),now:()=>"2026-09-03T00:02:00Z"}),reviewRequired=await contradicted.retrieve(base);assert.equal(reviewRequired.status,"PRODUCT_INFO_REVIEW_REQUIRED");assert.deepEqual(reviewRequired.result.validation.reasons,["BRAND_CONFLICT"]);assert.equal(reviewRequired.sellersReadiness,"NOT_ESTABLISHED");assert.equal(reviewRequired.result.downstreamAuthority.sellersExecution,false);
 const conflict=new ProductInfoResultRetrievalService({retriever:async()=>result([item({title:"changed material"})]),resultRepository:repository,now:()=>"2026-09-03T00:03:00Z"});await assert.rejects(()=>conflict.retrieve(base),/REPLAY_CONFLICT/);
 const script=await readFile(new URL("../../../scripts/dataforseo-live-product-info-result-once.mjs",import.meta.url),"utf8"),pkg=JSON.parse(await readFile(new URL("../../../package.json",import.meta.url),"utf8"));assert.match(script,/--task-id/);assert.match(script,/PRODUCT_INFO_TASK_ID_REQUIRED/);assert.doesNotMatch(script,/08210619-2304-0455-0000-6f9d1fa692ed/);assert.match(pkg.scripts["acquisition:enrichment:result:retrieve"],/--use-system-ca/);
 console.log("Governed Product Info result retrieval tests passed.");
}finally{await rm(root,{recursive:true,force:true});}
