import assert from "node:assert/strict";
import {assessHistoricalRefreshCycleStatus} from "../index.js";

const atlasProductId="ram_corsair_cmk32gx5m2b6000z30",providerIdentity={productId:null,dataDocId:"3844868436216882408",gid:null};
const plan={schemaVersion:"1.0",refreshPlanId:"histrefresh_fixture",operation:"SELLERS",status:"PENDING_OPERATOR_REVIEW",atlasProductId,providerIdentity,existingIdentity:{retailerId:"RETAILER-0002"},previous:{observationId:"mer_hist_original",observationTime:"2026-08-21T16:31:45.604Z",evidenceId:"evidence-original",providerTaskId:"task-original"}};
const authorization={requestId:"histrefreshauth_fixture",authorizationType:"HISTORICAL_REFRESH_SELLERS",refreshPlanId:plan.refreshPlanId,planId:"execution-plan",atlasProductId,retailerId:"RETAILER-0002",providerIdentity,createdAt:"2026-08-24T00:03:00Z",expiresAt:"2026-08-24T00:18:00Z",plan:{planId:"execution-plan"}};
const run={runId:"run-fixture",planId:"execution-plan",status:"COMPLETED",finishedAt:"2026-08-24T00:07:43Z",tasks:[{outcome:"COMPLETED",providerTaskId:"task-refresh"}]};
const consumption={schemaVersion:"1.0",consumed:[{authorizationId:authorization.requestId,planId:authorization.planId,consumedAt:"2026-08-24T00:04:00Z"}]};
const reuse={status:"APPLICABLE",reuseAssessmentId:"histidreuse_fixture",sourceEvidenceId:"evidence-original",targetEvidenceId:"evidence-refresh",assessedAt:"2026-08-24T00:08:00Z"};
const result={refreshPlanId:plan.refreshPlanId,authorizationId:authorization.requestId,providerTaskId:"task-refresh",retrievalStatus:"COMPLETED",sellerResultCount:1,retained:1,acquisitionOutcome:"SELLER_OBSERVATIONS_PROCESSED",evidence:[{evidenceId:"evidence-refresh"}],identityReuse:[reuse]};
const observation=(id,evidenceId,time,task,acquisition={})=>({observationId:id,atlasProductId,retailerId:"RETAILER-0002",observationTime:time,admittedAt:time,market:{basePrice:588.99,totalPrice:588.99},provenance:{retainedEvidenceId:evidenceId,acquisition:{sellersTaskId:task,...acquisition}}});
const original=observation("mer_hist_original","evidence-original","2026-08-21T16:31:45.604Z","task-original"),refresh=observation("mer_hist_refresh","evidence-refresh","2026-08-24 00:07:42 +00:00","task-refresh",{type:"HISTORICAL_REFRESH",refreshPlanId:plan.refreshPlanId});
const base={atlasProductId,asOf:"2026-08-25T00:00:00Z",historicalObservations:[original,refresh],evidenceRecords:[{evidenceId:"evidence-original"},{evidenceId:"evidence-refresh",retainedAt:"2026-08-24T00:08:00Z"}],refreshPlans:[plan],authorizations:[authorization],executionRuns:[run],consumptionState:consumption,refreshResults:[result],promotionAssessments:[]};

const before=structuredClone(base),complete=assessHistoricalRefreshCycleStatus(base);
assert.equal(complete.stage,"COMPLETE");assert.match(complete.refreshCycleId,/^histcycle_[a-f0-9]{24}$/);assert.equal(complete.cycle.refreshPlanId,plan.refreshPlanId);assert.equal(complete.cycle.authorizationId,authorization.requestId);assert.equal(complete.cycle.providerTaskId,"task-refresh");assert.deepEqual(complete.cycle.retainedEvidenceIds,["evidence-refresh"]);assert.deepEqual(complete.cycle.reuseAssessmentIds,["histidreuse_fixture"]);assert.deepEqual(complete.cycle.admittedHistoricalObservationIds,["mer_hist_refresh"]);assert.equal(complete.nextAction.name,"PREPARE_NEW_REFRESH");assert.equal(complete.nextAction.zeroSpend,true);assert.equal(complete.nextAction.potentialPaidOperation,"SELLERS");assert.equal(complete.nextAction.maximumFutureSpendUsd,.001);assert.equal(complete.paidTaskCreated,false);assert.equal(complete.actualSpendUsd,0);assert.equal(complete.unattendedLive,"DISABLED");assert.equal(complete.recurrence.policyDefined,false);assert.equal(complete.recurrence.automaticCadence,null);assert.equal(complete.recurrence.freshnessThreshold,null);assert.equal(complete.recurrence.currentPriceSemantics,false);assert.equal(complete.latestHistoricalObservation.observationId,"mer_hist_refresh");assert.deepEqual(assessHistoricalRefreshCycleStatus(base),complete);assert.deepEqual(base,before);
const state=overrides=>assessHistoricalRefreshCycleStatus({...base,historicalObservations:[original],...overrides});
assert.equal(state({refreshPlans:[],authorizations:[],executionRuns:[],consumptionState:{schemaVersion:"1.0",consumed:[]},refreshResults:[]}).stage,"READY_FOR_PREPARE");
assert.equal(state({authorizations:[],executionRuns:[],consumptionState:{schemaVersion:"1.0",consumed:[]},refreshResults:[]}).nextAction.name,"PREPARE_AUTHORIZATION");
const awaitingPaid=state({asOf:"2026-08-24T00:10:00Z",executionRuns:[],consumptionState:{schemaVersion:"1.0",consumed:[]},refreshResults:[]});assert.equal(awaitingPaid.stage,"AWAITING_PAID_EXECUTION");assert.equal(awaitingPaid.nextAction.requiresExplicitSpendAuthorization,true);
assert.equal(state({executionRuns:[],consumptionState:{schemaVersion:"1.0",consumed:[]},refreshResults:[]}).nextAction.name,"PREPARE_NEW_AUTHORIZATION");
assert.equal(state({executionRuns:[],refreshResults:[]}).stage,"BLOCKED");assert.equal(state({refreshResults:[]}).nextAction.name,"RETRIEVE_RESULT");assert.equal(state({refreshResults:[{...result,evidence:[],retained:0,identityReuse:[]}]}).nextAction.name,"RETAIN_EVIDENCE");assert.equal(state({}).nextAction.name,"ASSESS_PROMOTION");
const eligible=state({promotionAssessments:[{refreshPlanId:plan.refreshPlanId,state:"HISTORICAL_ELIGIBLE",historicalEligible:true,canonicalEligible:false,publicationEligible:false}]});assert.equal(eligible.stage,"HISTORICAL_ELIGIBLE");assert.equal(eligible.nextAction.name,"ADMIT_HISTORICAL_EVIDENCE");
for(const status of ["REVIEW_REQUIRED","BLOCKED"]){const reviewed=state({refreshResults:[{...result,identityReuse:[{...reuse,status,reuseAssessmentId:status==="REVIEW_REQUIRED"?null:reuse.reuseAssessmentId}]}]});assert.equal(reviewed.stage,status);assert.equal(reviewed.nextAction.name,"OPERATOR_REVIEW_REQUIRED");}
const noSellers=state({refreshResults:[{...result,sellerResultCount:0,retained:0,acquisitionOutcome:"NO_SELLER_OBSERVATIONS",evidence:[],identityReuse:[]}]});assert.equal(noSellers.stage,"NO_SELLER_OBSERVATIONS");assert.equal(noSellers.nextAction.name,"AWAIT_RECURRENCE_POLICY");
const failed=state({executionRuns:[{...run,status:"FAILED",tasks:[{outcome:"FAILED"}]}],refreshResults:[]});assert.equal(failed.stage,"PAID_EXECUTION_FAILED");assert.ok(failed.blockingReasons.includes("PAID_EXECUTION_FAILED_NO_AUTOMATIC_RETRY"));
const collision=state({refreshResults:[result,{...result,refreshPlanId:"other-plan"}]});assert.equal(collision.stage,"BLOCKED");assert.ok(collision.blockingReasons.includes("PROVIDER_TASK_REUSED_ACROSS_CYCLES"));assert.throws(()=>assessHistoricalRefreshCycleStatus({...base,asOf:"not-a-date"}),/AS_OF_INVALID/);
console.log("Historical refresh cycle status tests passed.");
