import assert from "node:assert/strict";
import crypto from "node:crypto";
import {mkdtemp,rm} from "node:fs/promises";
import {tmpdir} from "node:os";
import {join} from "node:path";
import {createDataForSeoPrepareArtifact,FileDataForSeoPrepareArtifactRepository,createHistoricalBootstrapPreparedActionResolver,HistoricalBootstrapPaidTaskHandoff,projectHistoricalBootstrapCheckpoint,HISTORICAL_BOOTSTRAP_CHECKPOINT_VERSION} from "../index.js";

const stable=v=>Array.isArray(v)?`[${v.map(stable).join(",")}]`:v&&typeof v==="object"?`{${Object.keys(v).sort().map(k=>`${JSON.stringify(k)}:${stable(v[k])}`).join(",")}}`:JSON.stringify(v),hash=v=>crypto.createHash("sha256").update(stable(v)).digest("hex");
const at="2026-09-11T14:00:00.000Z",artifactId="bootstrap",checkpointId="cp",source="DATAFORSEO_GOOGLE_SHOPPING",rights="d".repeat(64);
function checkpoint(product="p1",operation="PRODUCTS",reference=null){const binding={artifactId,artifactDigest:"a".repeat(64),asOf:at,sourceId:source,sourceRightsProfileDigest:rights,acquisitionPortfolioReference:{portfolioCycleId:"mer_acqportfolio_"+"e".repeat(24),bindingDigest:"f".repeat(64)},products:[product],taskCap:9,spendCapUsd:.009,utcDayCapUsd:.01},events=[{sequence:1,type:"CHECKPOINT_PREPARED",at,productIndex:0,atlasProductId:product,stage:"PRODUCTS"}];if(reference)events.push({sequence:2,type:"PREPARE_BOUND",at,productIndex:0,atlasProductId:product,operation,...reference,preparedFromEventSequence:1});return{schemaVersion:"1.0",checkpointId,policyVersion:HISTORICAL_BOOTSTRAP_CHECKPOINT_VERSION,binding,bindingDigest:hash(binding),createdAt:at,events}}
const root=await mkdtemp(join(tmpdir(),"hr-h032-artifacts-"));
try{
 const repository=new FileDataForSeoPrepareArtifactRepository({statePath:join(root,"prepare.json")}),records=[];
 for(let i=0;i<3;i++){const intent=`mer_histbootintent_${String(i+1).repeat(24)}`,request={requestId:`auth-${i}`,plan:{decisions:[{decision:"APPROVED",execution:{kind:"PRODUCTS"}}]}},record=createDataForSeoPrepareArtifact({operation:"PRODUCTS",atlasProductId:`p${i}`,productIndex:i,paidActionIntentId:intent,bootstrapCheckpointId:checkpointId,bootstrapArtifactId:artifactId,sourceRightsProfileDigest:rights,originatingCheckpointSequence:1,prepareArtifact:request,authorizationRequest:request,preparedAt:at});records.push(await repository.record(record))}
 assert.equal(new Set(records.map(x=>x.prepareArtifactId)).size,3);assert.deepEqual(await repository.record(records[0]),records[0]);await assert.rejects(()=>repository.record({...records[0],preparedAt:"2026-09-11T14:01:00Z"}),/PREPARE_ARTIFACT_CONFLICT/);
 for(const [index,operation] of ["PRODUCTS","PRODUCT_INFO","SELLERS"].entries()){const intent=`mer_histbootintent_${String(index+4).repeat(24)}`,request={requestId:`auth-${operation}`,plan:{decisions:[{decision:"APPROVED",execution:{kind:operation}}]}},record=createDataForSeoPrepareArtifact({operation,atlasProductId:"escalation",productIndex:0,paidActionIntentId:intent,bootstrapCheckpointId:checkpointId,bootstrapArtifactId:artifactId,sourceRightsProfileDigest:rights,originatingCheckpointSequence:1,prepareArtifact:{proposalId:`proposal-${operation}`},authorizationRequest:request,preparedAt:at});await repository.record(record);assert.ok(await repository.getById(record.prepareArtifactId))}
 const artifact=records[0],reference={paidActionIntentId:artifact.paidActionIntentId,continuationAuthorizationId:"cont",prepareArtifactId:artifact.prepareArtifactId,prepareArtifactBindingDigest:artifact.bindingDigest,authorizationRequestId:artifact.authorizationRequestId,proposalDigest:artifact.proposalDigest,sourceRightsProfileDigest:rights},cp=checkpoint("p0","PRODUCTS",reference),continuation={eventSequence:1,nextOperation:"PRODUCTS",paidActionIntentId:artifact.paidActionIntentId,sourceRightsProfileDigest:rights},resolver=createHistoricalBootstrapPreparedActionResolver({prepareRepository:repository});
 assert.equal((await resolver.resolve({checkpoint:cp,continuation})).authorizationRequest.requestId,"auth-0");
 await assert.rejects(()=>resolver.resolve({checkpoint:{...cp,events:cp.events.map((e,i)=>i===1?{...e,prepareArtifactBindingDigest:"0".repeat(64)}:e)},continuation}),/DIGEST_MISMATCH/);
 await assert.rejects(()=>resolver.resolve({checkpoint:cp,continuation:{...continuation,eventSequence:2}}),/STALE_PREPARE_ARTIFACT/);
 await assert.rejects(()=>resolver.resolve({checkpoint:checkpoint("p0","PRODUCTS",{...reference,prepareArtifactId:"missing"}),continuation}),/NOT_FOUND/);
 let consumed=0,providerCalls=0;const durable={...continuation,checkpointId,atlasProductId:"p0",productIndex:0,sourceId:source,confirmation:"EXECUTE",continuationAuthorizationId:"cont",expiresAt:"2026-09-11T15:00:00Z"},handoff=new HistoricalBootstrapPaidTaskHandoff({continuationRepository:{getById:async()=>durable,consume:async()=>{consumed++;return{status:"CONSUMED"}}},checkpointRepository:{append:async()=>{throw Error("CHECKPOINT_MUTATED")}},preparedActionResolver:{resolve:async()=>{throw Error("PREPARE_ARTIFACT_NOT_FOUND")}},rightsRegistry:{get:()=>({acquisition:{api:"ALLOWED"}})},spendResolver:async()=>0,taskSpecificOwner:{execute:async()=>{providerCalls++}},now:()=>"2026-09-11T14:01:00Z"});
 await assert.rejects(()=>handoff.execute({checkpoint:cp,authorizationId:"cont",confirmation:"EXECUTE",executedBy:"operator:test"}),/PREPARE_ARTIFACT_NOT_FOUND/);assert.equal(consumed,0);assert.equal(providerCalls,0);
 assert.equal(projectHistoricalBootstrapCheckpoint({checkpoint:cp}).cohortState,"PREPARED_FOR_AUTHORIZATION");
 console.log("Historical bootstrap artifact resolution tests passed (17 cases).");
}finally{await rm(root,{recursive:true,force:true})}
