import assert from "node:assert/strict";
import {execFileSync} from "node:child_process";
import {mkdtemp,readFile,rm,writeFile} from "node:fs/promises";
import {fileURLToPath} from "node:url";
import {join} from "node:path";
import {tmpdir} from "node:os";
import {ProductRepository,RetailerRepository} from "../../atlas/index.js";
import {FileDataForSeoMarketEvidenceRepository,FileHistoricalObservationRepository,FileIdentityReviewDecisionRepository,HistoricalObservationAdmissionService,createMerchantIdentityReviewDecision,createProductIdentityReviewDecision} from "../index.js";

const root=await mkdtemp(join(tmpdir(),"hardware-radar-e2j-"));const readJson=async resource=>JSON.parse(await readFile(fileURLToPath(resource),"utf8"));
const candidate={candidateVersion:"1.0",candidateType:"MERCURY_MARKET_OBSERVATION",marketEvidence:{evidenceVersion:"1.0",provider:"DATAFORSEO",source:"DATAFORSEO_GOOGLE_SHOPPING",sourceMethod:"API",seller:{name:"Platinummicro",domain:"platinummicro.com",url:"https://platinummicro.com/item"},pricing:{basePrice:588.99,shippingPrice:null,tax:null,totalPrice:588.99,currency:"USD"},offer:{condition:null,details:"Corsair CMK32GX5M2B6000Z30",availability:"in_stock"},productEvidence:{title:"Corsair CMK32GX5M2B6000Z30",dataDocId:"3844868436216882408",productId:null,gid:null},provenance:{sourceTaskId:"08211631-2304-0183-0000-2f47e4410471",observedAt:"2026-08-21T16:31:45.604Z",rawPayloadReference:"fixture:e2j"}},identity:{outcome:"PROBABLE",atlasProductId:"ram_corsair_cmk32gx5m2b6000z30",externalProductId:null,candidateAtlasProductIds:[],evidence:[]},governance:{requiresReview:true,canonicalObservationEligible:false,automaticPublicationEligible:false}};
const merchant={resolutionVersion:"1.0",outcome:"DISCOVERED",retailerId:null,merchantKey:"domain:platinummicro.com",sellerName:"Platinummicro",canonicalDomain:"platinummicro.com",suppliedDomain:"platinummicro.com",urlDomain:"platinummicro.com",requiresRegistration:true,evidence:[],reason:"ATLAS_RETAILER_NOT_FOUND"};const eligibility={eligibilityVersion:"1.0",status:"REVIEW_REQUIRED",canonicalObservationEligible:false,rawEvidenceRetentionEligible:true,historicalAnalyticsEligible:false,retailerId:null,requiresReview:true,reasons:["MERCHANT_REGISTRATION_REQUIRED"]};
try{
 const evidencePath=join(root,"evidence.json"),decisionPath=join(root,"decisions.json"),historyPath=join(root,"history.json");const evidenceRepository=new FileDataForSeoMarketEvidenceRepository({statePath:evidencePath,now:()=>"2026-08-22T06:28:10.013Z"});const retained=await evidenceRepository.retain({candidate,merchantResolution:merchant,eligibility});const record=await evidenceRepository.getById(retained.evidenceId);const retainedBefore=structuredClone(record);const decisionRepository=new FileIdentityReviewDecisionRepository({statePath:decisionPath,now:()=>"2026-08-22T10:10:00Z"});
 const product=await decisionRepository.recordDecision(createProductIdentityReviewDecision({atlasProductId:candidate.identity.atlasProductId,previousState:"PROBABLE",requestedState:"VERIFIED",decisionOutcome:"APPROVED",reviewedAt:"2026-08-22T10:05:00Z",reviewedBy:"operator:test",reason:"Product identity reviewed.",supportingEvidenceReferences:[record.evidenceId],contradictionStatus:"NONE",audit:{source:"OPERATOR_REVIEW",requestId:"product-review-fixture",preparedAt:"2026-08-22T10:01:00Z"}}));const registered=await decisionRepository.recordDecision(createMerchantIdentityReviewDecision({discoveredMerchantName:"Platinummicro",canonicalMerchantName:"Platinummicro",canonicalDomain:"platinummicro.com",merchantId:"RETAILER-0002",merchantActive:true,previousState:"DISCOVERED",requestedState:"REGISTERED",decisionOutcome:"APPROVED",reviewedAt:"2026-08-22T10:08:00Z",reviewedBy:"operator:test",reason:"Atlas merchant mapping reviewed.",supportingEvidenceReferences:[record.evidenceId],contradictionStatus:"NONE",audit:{source:"OPERATOR_REVIEW",requestId:"merchant-review-platinummicro.com",preparedAt:"2026-08-22T10:02:00Z"}}));const decisionsBefore=structuredClone(await decisionRepository.getAll());
 const productRepository=new ProductRepository({readJson});const retailerRepository=new RetailerRepository({readJson});const atlasBefore=structuredClone({products:await productRepository.getAll(),retailers:await retailerRepository.getAll()});const chain={productsTaskId:"08210233-2304-0179-0000-4ad9784a612c",productInfoTaskId:"08210619-2304-0455-0000-6f9d1fa692ed",sellersTaskId:"08211631-2304-0183-0000-2f47e4410471"};const historicalRepository=new FileHistoricalObservationRepository({statePath:historyPath});const service=new HistoricalObservationAdmissionService({evidenceRepository,decisionRepository,productRepository,retailerRepository,historicalRepository,acquisitionChainResolver:async()=>chain,now:()=>"2026-08-23T12:00:00Z"});
 const admitted=await service.admit({evidenceId:record.evidenceId,admittedBy:"operator:test"});assert.equal(admitted.status,"ADMITTED");assert.match(admitted.observationId,/^mer_hist_[a-f0-9]{16}$/);const observation=admitted.observation;assert.equal(observation.atlasProductId,candidate.identity.atlasProductId);assert.equal(observation.retailerId,"RETAILER-0002");assert.equal(observation.market.basePrice,588.99);assert.equal(observation.market.totalPrice,588.99);assert.equal(observation.market.shipping,null);assert.equal(observation.market.tax,null);assert.equal(observation.market.condition,null);assert.equal(observation.market.currency,"USD");assert.equal(observation.observationTime,"2026-08-21T16:31:45.604Z");assert.equal(observation.admittedAt,"2026-08-23T12:00:00Z");assert.equal(observation.provenance.retainedEvidenceId,record.evidenceId);assert.deepEqual(observation.provenance.acquisition,chain);assert.equal(observation.provenance.identityReview.productDecisionId,product.identityReviewDecisionId);assert.equal(observation.provenance.identityReview.merchantDecisionId,registered.identityReviewDecisionId);assert.equal(observation.governance.canonicalEligible,false);assert.equal(observation.governance.publicationEligible,false);assert.equal(Object.isFrozen(observation),true);assert.equal(Object.isFrozen(observation.market),true);assert.throws(()=>{observation.market.basePrice=1;},TypeError);
 const replay=await service.admit({evidenceId:record.evidenceId,admittedBy:"operator:test"});assert.equal(replay.status,"DUPLICATE");assert.equal(replay.observationId,admitted.observationId);assert.equal((await historicalRepository.getAll()).length,1);assert.deepEqual(await evidenceRepository.getById(record.evidenceId),retainedBefore);assert.deepEqual(await decisionRepository.getAll(),decisionsBefore);assert.deepEqual({products:await productRepository.getAll(),retailers:await retailerRepository.getAll()},atlasBefore);
 const emptyDecisions={getAll:async()=>[],getAllRemediations:async()=>[]};const failService=new HistoricalObservationAdmissionService({evidenceRepository,decisionRepository:emptyDecisions,productRepository,retailerRepository,historicalRepository:new FileHistoricalObservationRepository({statePath:join(root,"fail.json")}),acquisitionChainResolver:async()=>chain});await assert.rejects(()=>failService.admit({evidenceId:record.evidenceId,admittedBy:"operator:test"}),/NOT_ELIGIBLE/);
 const productOnly={getAll:async()=>[product],getAllRemediations:async()=>[]};const discoveredService=new HistoricalObservationAdmissionService({evidenceRepository,decisionRepository:productOnly,productRepository,retailerRepository,historicalRepository:new FileHistoricalObservationRepository({statePath:join(root,"discovered.json")}),acquisitionChainResolver:async()=>chain});await assert.rejects(()=>discoveredService.admit({evidenceId:record.evidenceId,admittedBy:"operator:test"}),/NOT_ELIGIBLE/);
 const merchantOnly={getAll:async()=>[registered],getAllRemediations:async()=>[]};const probableService=new HistoricalObservationAdmissionService({evidenceRepository,decisionRepository:merchantOnly,productRepository,retailerRepository,historicalRepository:new FileHistoricalObservationRepository({statePath:join(root,"probable.json")}),acquisitionChainResolver:async()=>chain});await assert.rejects(()=>probableService.admit({evidenceId:record.evidenceId,admittedBy:"operator:test"}),/NOT_ELIGIBLE/);
 const unknownRetailer={getAll:async()=>[product,{...registered,merchantId:"RETAILER-9999"}],getAllRemediations:async()=>[]};const unknownRetailerService=new HistoricalObservationAdmissionService({evidenceRepository,decisionRepository:unknownRetailer,productRepository,retailerRepository,historicalRepository:new FileHistoricalObservationRepository({statePath:join(root,"unknown-retailer.json")}),acquisitionChainResolver:async()=>chain});await assert.rejects(()=>unknownRetailerService.admit({evidenceId:record.evidenceId,admittedBy:"operator:test"}),/NOT_ELIGIBLE/);
 for(const [label,mutate] of [["price",r=>{r.candidate.marketEvidence.pricing.basePrice="588.99";}],["currency",r=>{r.candidate.marketEvidence.pricing.currency="usd";}],["provenance",r=>{r.candidate.marketEvidence.provenance.rawPayloadReference=null;}]]){const malformed=structuredClone(record);mutate(malformed);const malformedEvidence={getById:async()=>malformed};const malformedService=new HistoricalObservationAdmissionService({evidenceRepository:malformedEvidence,decisionRepository,productRepository,retailerRepository,historicalRepository:new FileHistoricalObservationRepository({statePath:join(root,`malformed-${label}.json`)}),acquisitionChainResolver:async()=>chain});await assert.rejects(()=>malformedService.admit({evidenceId:record.evidenceId,admittedBy:"operator:test"}),/NOT_ELIGIBLE|INVALID/);}
 const missingEvidence={...evidenceRepository,getById:async()=>null};const missingService=new HistoricalObservationAdmissionService({evidenceRepository:missingEvidence,decisionRepository,productRepository,retailerRepository,historicalRepository,acquisitionChainResolver:async()=>chain});await assert.rejects(()=>missingService.admit({evidenceId:"missing",admittedBy:"operator:test"}),/EVIDENCE_NOT_FOUND/);
 const badChainService=new HistoricalObservationAdmissionService({evidenceRepository,decisionRepository,productRepository,retailerRepository,historicalRepository:new FileHistoricalObservationRepository({statePath:join(root,"bad-chain.json")}),acquisitionChainResolver:async()=>({...chain,sellersTaskId:"substituted"})});await assert.rejects(()=>badChainService.admit({evidenceId:record.evidenceId,admittedBy:"operator:test"}),/CHAIN_MISMATCH/);
 const badProductRepository={getById:async()=>({identity:{atlasProductId:"substituted_product"}})};const badProductService=new HistoricalObservationAdmissionService({evidenceRepository,decisionRepository,productRepository:badProductRepository,retailerRepository,historicalRepository:new FileHistoricalObservationRepository({statePath:join(root,"bad-product.json")}),acquisitionChainResolver:async()=>chain});await assert.rejects(()=>badProductService.admit({evidenceId:record.evidenceId,admittedBy:"operator:test"}),/ATLAS_PRODUCT_MISMATCH/);
 const chainPath=join(root,"chain.json"),cliHistory=join(root,"cli-history.json");await writeFile(chainPath,JSON.stringify(chain),"utf8");const cli=execFileSync(process.execPath,["scripts/mercury-historical-observation-admit.mjs",`--evidence-id=${record.evidenceId}`,"--admitted-by=operator:test",`--evidence-state=${evidencePath}`,`--decision-state=${decisionPath}`,`--historical-state=${cliHistory}`,`--chain-state=${chainPath}`],{cwd:process.cwd(),encoding:"utf8"});assert.match(cli,/Historical admission:\s+ADMITTED/);assert.match(cli,/Canonical eligible:\s+false/);assert.match(cli,/Publication eligible:\s+false/);assert.match(cli,/Paid task created:\s+NO/);assert.match(cli,/Actual spend:\s+\$0\.000/);
}finally{await rm(root,{recursive:true,force:true});}
console.log("Historical observation admission tests passed.");
