import assert from "node:assert/strict";
import {execFileSync} from "node:child_process";
import {mkdtemp,readFile,rm} from "node:fs/promises";
import {join} from "node:path";
import {tmpdir} from "node:os";
import {createHistoricalObservation,createHistoricalObservationId,FileHistoricalObservationRepository,HistoricalObservationIntelligence} from "../index.js";

const root=await mkdtemp(join(tmpdir(),"hardware-radar-e2k-"));
const make=({evidenceId,time,admittedAt,basePrice,totalPrice=basePrice,currency="USD",retailerId="RETAILER-0002",shipping=null,tax=null,condition=null}={})=>createHistoricalObservation({observationId:createHistoricalObservationId(evidenceId),atlasProductId:"ram_corsair_cmk32gx5m2b6000z30",retailerId,marketplace:retailerId==="RETAILER-0002"?"platinummicro.com":"example.com",observationTime:time,admittedAt,market:{sellerName:retailerId==="RETAILER-0002"?"Platinummicro":"Example",sourceUrl:"https://example.com/item",basePrice,totalPrice,shipping,tax,currency,condition,availability:"in_stock"},provenance:{retainedEvidenceId:evidenceId,provider:"FIXTURE",source:"FIXTURE",rawPayloadReference:`fixture:${evidenceId}`,acquisition:{productsTaskId:`products-${evidenceId}`,productInfoTaskId:`info-${evidenceId}`,sellersTaskId:`sellers-${evidenceId}`},identityReview:{productDecisionId:"product",productRemediationId:null,merchantDecisionId:"merchant",merchantRemediationId:null}},admittedBy:"operator:test",idempotencyKey:`E2J_HISTORICAL_ADMISSION:${evidenceId}`});
try{
 const empty=new HistoricalObservationIntelligence({repository:{getAll:async()=>[]}});const noData=await empty.query({atlasProductId:"unknown_product"});assert.equal(noData.observationCount,0);assert.equal(noData.trendState,"NO_DATA");assert.equal(noData.priceChangeAvailable,false);assert.equal(noData.latestBasePrice,null);
 const productionLike=make({evidenceId:"dfev_4a1ca776de2706f9473653f3",time:"2026-08-21T16:31:45.604Z",admittedAt:"2026-08-23T12:00:00Z",basePrice:588.99,totalPrice:588.99});const original=structuredClone(productionLike);const oneService=new HistoricalObservationIntelligence({repository:{getAll:async()=>[productionLike]}});const one=await oneService.query({atlasProductId:productionLike.atlasProductId});assert.equal(one.observationCount,1);assert.equal(one.latestBasePrice,588.99);assert.equal(one.latestTotalPrice,588.99);assert.equal(one.lowestBasePrice,588.99);assert.equal(one.highestBasePrice,588.99);assert.equal(one.firstObservationTime,"2026-08-21T16:31:45.604Z");assert.equal(one.latestObservationTime,one.firstObservationTime);assert.equal(one.retailerCount,1);assert.deepEqual(one.retailerIds,["RETAILER-0002"]);assert.equal(one.trendState,"INSUFFICIENT_HISTORY");assert.equal(one.changeFromFirst,null);assert.equal(one.changeFromPrevious,null);assert.equal(one.chronologicalObservations[0].shipping,null);assert.equal(one.chronologicalObservations[0].tax,null);assert.equal(one.chronologicalObservations[0].condition,null);assert.equal(one.chronologicalObservations[0].totalPrice,588.99);assert.deepEqual(productionLike,original);assert.equal(Object.isFrozen(one),true);assert.deepEqual(await oneService.query({atlasProductId:productionLike.atlasProductId}),one);
 const first=make({evidenceId:"dfev_first",time:"2026-01-01T00:00:00Z",admittedAt:"2026-01-04T00:00:00Z",basePrice:100,totalPrice:115,retailerId:"RETAILER-0002"});const middle=make({evidenceId:"dfev_middle",time:"2026-01-02T00:00:00Z",admittedAt:"2026-01-01T00:00:00Z",basePrice:90,totalPrice:105,retailerId:"RETAILER-0001"});const latest=make({evidenceId:"dfev_latest",time:"2026-01-03T00:00:00Z",admittedAt:"2026-01-02T00:00:00Z",basePrice:110,totalPrice:125,retailerId:"RETAILER-0002"});const service=new HistoricalObservationIntelligence({repository:{getAll:async()=>[latest,first,middle]}});const up=await service.query({atlasProductId:first.atlasProductId});assert.deepEqual(up.chronologicalObservations.map(x=>x.observationId),[first.observationId,middle.observationId,latest.observationId]);assert.equal(up.latestRetailerId,"RETAILER-0002");assert.equal(up.retailerCount,2);assert.deepEqual(up.retailerIds,["RETAILER-0001","RETAILER-0002"]);assert.equal(up.trendState,"UP");assert.equal(up.changeFromFirst.basePrice,10);assert.equal(up.changeFromFirst.totalPrice,10);assert.equal(up.changeFromFirst.basePricePercentage,10);assert.equal(up.changeFromPrevious.basePrice,20);assert.equal(up.lowestBasePrice,90);assert.equal(up.highestBasePrice,110);
 const filtered=await service.query({atlasProductId:first.atlasProductId,retailerId:"RETAILER-0001"});assert.equal(filtered.observationCount,1);const ranged=await service.query({atlasProductId:first.atlasProductId,from:"2026-01-02T00:00:00Z",to:"2026-01-03T00:00:00Z"});assert.equal(ranged.observationCount,2);await assert.rejects(()=>service.query({atlasProductId:first.atlasProductId,from:"2026-01-04T00:00:00Z",to:"2026-01-01T00:00:00Z"}),/DATE_RANGE_INVALID/);
 const downLatest=make({evidenceId:"dfev_down",time:"2026-01-05T00:00:00Z",admittedAt:"2026-01-05T01:00:00Z",basePrice:80});assert.equal((await new HistoricalObservationIntelligence({repository:{getAll:async()=>[first,downLatest]}}).query({atlasProductId:first.atlasProductId})).trendState,"DOWN");const flatLatest=make({evidenceId:"dfev_flat",time:"2026-01-05T00:00:00Z",admittedAt:"2026-01-05T01:00:00Z",basePrice:100});assert.equal((await new HistoricalObservationIntelligence({repository:{getAll:async()=>[first,flatLatest]}}).query({atlasProductId:first.atlasProductId})).trendState,"FLAT");
 const eur=make({evidenceId:"dfev_eur",time:"2026-01-06T00:00:00Z",admittedAt:"2026-01-06T01:00:00Z",basePrice:95,currency:"EUR"});const mixed=await new HistoricalObservationIntelligence({repository:{getAll:async()=>[first,eur]}}).query({atlasProductId:first.atlasProductId});assert.equal(mixed.trendState,"NON_COMPARABLE");assert.deepEqual(mixed.currencies,["EUR","USD"]);assert.equal(mixed.changeFromFirst,null);assert.equal(mixed.lowestBasePrice,null);assert.equal(mixed.perCurrency.length,2);
 await assert.rejects(()=>new HistoricalObservationIntelligence({repository:{getAll:async()=>[{...first,market:{...first.market,basePrice:"bad"}}]}}).query({atlasProductId:first.atlasProductId}),/STATE_INVALID/);await assert.rejects(()=>new HistoricalObservationIntelligence({repository:{getAll:async()=>[first,first]}}).query({atlasProductId:first.atlasProductId}),/DUPLICATE/);
 const historyPath=join(root,"history.json");const repository=new FileHistoricalObservationRepository({statePath:historyPath});await repository.accept(productionLike,productionLike.metadata.idempotencyKey);const beforeBytes=await readFile(historyPath,"utf8");const cli=execFileSync(process.execPath,["scripts/mercury-history-query.mjs",`--state=${historyPath}`,`--atlas-product=${productionLike.atlasProductId}`],{cwd:process.cwd(),encoding:"utf8"});assert.match(cli,/Observations:\s+1/);assert.match(cli,/Latest base price:\s+\$588\.99/);assert.match(cli,/Trend:\s+INSUFFICIENT_HISTORY/);assert.match(cli,/Change from previous:\s+NOT_AVAILABLE/);assert.match(cli,/Paid task created:\s+NO/);assert.match(cli,/Actual spend:\s+\$0\.000/);assert.equal(await readFile(historyPath,"utf8"),beforeBytes);
}finally{await rm(root,{recursive:true,force:true});}
console.log("Historical observation intelligence tests passed.");
