import assert from "node:assert/strict";
import {mkdir,mkdtemp,readFile,rm,writeFile} from "node:fs/promises";
import {tmpdir} from "node:os";
import {join,resolve} from "node:path";
import {execFileSync} from "node:child_process";
import {assertHistoricalAdmissionAuthorization,composeInitialAcquisitionPromotionAssessment,HISTORICAL_ADMISSION_CONFIRMATION,HistoricalAdmissionExecutor,HistoricalAdmissionPrepareService,RIGHTS_STATES} from "../index.js";
import {createHistoricalOperatorRuntime} from "../../../scripts/mercury-historical-admission-runtime.mjs";

const evidenceId="dfev_bb40abbb467a6497b88a3e2d",productId="ram_crucial_cp2k16g56c46u5",retailerId="RETAILER-0003",observationId="mer_hist_c4f418b1e82a5cf6",now="2026-09-02T00:00:00.000Z",root=await mkdtemp(join(tmpdir(),"hr-b013a-"));
const source=name=>resolve(name),copy=async(from,to)=>writeFile(to,await readFile(source(from))),paths={evidence:join(root,"evidence.json"),decisions:join(root,"decisions.json"),history:join(root,"history.json"),authorizations:join(root,"authorizations.json"),retention:join(root,"retention.json"),proposal:join(root,"proposal.json"),refreshResult:join(root,"missing-refresh-result.json"),refreshPlan:join(root,"missing-refresh-plan.json")};
await Promise.all([copy(".forge-review/acquisition/dataforseo-market-evidence.json",paths.evidence),copy(".forge-review/identity-review/identity-review-decisions.json",paths.decisions),copy(".forge-review/acquisition/sellers-df003-retention-latest.json",paths.retention),copy(".forge-review/acquisition/sellers-enrichment-proposal.json",paths.proposal)]);
const args=new Map([["--evidence-state",paths.evidence],["--decision-state",paths.decisions],["--historical-state",paths.history],["--authorization-state",paths.authorizations],["--retention-state",paths.retention],["--sellers-proposal",paths.proposal],["--refresh-result-state",paths.refreshResult],["--refresh-plan-state",paths.refreshPlan]]),runtime=createHistoricalOperatorRuntime(args,{now:()=>now}),prepare=new HistoricalAdmissionPrepareService({...runtime,now:()=>now}),executor=new HistoricalAdmissionExecutor({...runtime,now:()=>"2026-09-02T00:01:00.000Z"});
try{
  const evidenceBefore=await readFile(paths.evidence,"utf8"),decisionsBefore=await readFile(paths.decisions,"utf8"),assessment=await runtime.historicalAdmissionService.assess({evidenceId});
  assert.equal(assessment.promotionAssessment.productIdentity,"VERIFIED");assert.equal(assessment.promotionAssessment.merchantIdentity,"REGISTERED");assert.equal(assessment.promotionAssessment.state,"HISTORICAL_ELIGIBLE");assert.equal(assessment.candidateBinding.productProjectionId.startsWith("mer_initid_"),true);assert.equal(assessment.candidateBinding.merchantDecisionId,"mer_idrev_000000003");
  assert.deepEqual(assessment.expectedObservation,{observationId,atlasProductId:productId,retailerId,marketplace:"memoryc.com",observationTime:"2026-09-01T18:02:36.223Z",market:{sellerName:"MemoryC",sourceUrl:"https://www.memoryc.com/46255-crucial-cp2k16g56c46u5-memory-module-32-gb-2-x-16-gb-ddr5-5600-mhz.html?fc=US&srsltid=AfmBOop1gdGxFXr4komwbrZE6vUtrMaOEnoW1w_6Sv_ZDHAqDjmUmYTpubc",basePrice:663.79,totalPrice:663.79,shipping:null,tax:null,currency:"USD",condition:null,availability:"in_stock"},provenance:{retainedEvidenceId:evidenceId,provider:"DATAFORSEO",source:"DATAFORSEO_GOOGLE_SHOPPING",rawPayloadReference:"dataforseo:sellers:09011802-2304-0183-0000-b27c074679a9:item:5",acquisition:{productsTaskId:"09011702-2304-0179-0000-c977c7e8a824",productInfoTaskId:"09011739-2304-0455-0000-2f32c707dfc6",sellersTaskId:"09011802-2304-0183-0000-b27c074679a9"},identityReview:{productDecisionId:null,productRemediationId:null,merchantDecisionId:"mer_idrev_000000003",merchantRemediationId:null}}});
  assert.match(assessment.candidateBinding.rightsProfileHash,/^[a-f0-9]{64}$/);assert.equal(assessment.candidateBinding.rightsSourceId,"DATAFORSEO_GOOGLE_SHOPPING");
  const authorization=await prepare.prepare({evidenceId,requestedBy:"operator:fixture",reason:"Fixture MemoryC historical admission review."});assert.equal(authorization.candidateBinding.historicalObservationId,observationId);assert.equal(authorization.candidateBinding.atlasProductId,productId);assert.equal(authorization.candidateBinding.retailerId,retailerId);await assert.rejects(()=>readFile(paths.history,"utf8"),error=>error.code==="ENOENT");
  for(const [field,value] of [["evidenceId","dfev_substituted"],["atlasProductId","ram_substituted"],["retailerId","RETAILER-9999"],["merchantDecisionId","mer_idrev_substituted"],["historicalObservationId","mer_hist_ffffffffffffffff"]]){const changed=structuredClone(assessment);changed.candidateBinding[field]=value;await assert.rejects(async()=>assertHistoricalAdmissionAuthorization({authorization,assessment:changed,now:"2026-09-02T00:01:00Z"}),/BINDING_MISMATCH/);}
  assert.deepEqual(await prepare.prepare({evidenceId,requestedBy:"operator:fixture",reason:"Fixture MemoryC historical admission review."}),authorization);await assert.rejects(()=>prepare.prepare({evidenceId,requestedBy:"operator:other",reason:"Conflicting intent."}),/AUTHORIZATION_CONFLICT/);await assert.rejects(()=>prepare.prepare({evidenceId:"missing",requestedBy:"operator:fixture",reason:"Missing."}),/EVIDENCE_NOT_FOUND/);
  await assert.rejects(()=>executor.execute({authorizationId:authorization.authorizationId,confirmation:"WRONG",executedBy:"operator:fixture"}),/EXPLICIT_CONFIRMATION_REQUIRED/);await assert.rejects(()=>executor.execute({authorizationId:authorization.authorizationId,confirmation:HISTORICAL_ADMISSION_CONFIRMATION,executedBy:"operator:fixture",retailerId}),/CALLER_SUBSTITUTION_FORBIDDEN/);
  const originalRights=runtime.historicalAdmissionService.rightsRegistry;runtime.historicalAdmissionService.rightsRegistry={require:()=>{throw new Error("missing")}};await assert.rejects(()=>runtime.historicalAdmissionService.assess({evidenceId}),/SOURCE_RIGHTS_MISSING/);runtime.historicalAdmissionService.rightsRegistry={require:()=>({...originalRights.require("DATAFORSEO_GOOGLE_SHOPPING"),retention:{...originalRights.require("DATAFORSEO_GOOGLE_SHOPPING").retention,historical:RIGHTS_STATES.BLOCKED}})};await assert.rejects(()=>runtime.historicalAdmissionService.assess({evidenceId}),/SOURCE_RIGHTS_DENIED/);runtime.historicalAdmissionService.rightsRegistry=originalRights;
  const originalDecisionRepository=runtime.historicalAdmissionService.decisionRepository;runtime.historicalAdmissionService.decisionRepository={...originalDecisionRepository,getAll:async()=>[] ,getAllRemediations:async()=>[]};await assert.rejects(()=>runtime.historicalAdmissionService.assess({evidenceId}),/NOT_ELIGIBLE/);runtime.historicalAdmissionService.decisionRepository=originalDecisionRepository;
  const product=await runtime.historicalAdmissionService.productRepository.getById(productId),allEvidence=await runtime.historicalAdmissionService.evidenceRepository.getAll(),retentionAudit=JSON.parse(await readFile(paths.retention,"utf8")),proposalEnvelope=JSON.parse(await readFile(paths.proposal,"utf8"));assert.throws(()=>composeInitialAcquisitionPromotionAssessment({records:allEvidence,requestedAtlasProductId:productId,retentionAudit,sellersProposalEnvelope:proposalEnvelope,atlasProduct:{...product,governance:{...product.governance,lifecycleStatus:"INACTIVE"}}}),/PROJECTION|LIFECYCLE|ACTIVE|READY|INVALID/);
  const admitted=await executor.execute({authorizationId:authorization.authorizationId,confirmation:HISTORICAL_ADMISSION_CONFIRMATION,executedBy:"operator:fixture"});assert.equal(admitted.status,"ADMITTED");assert.equal(admitted.observationId,observationId);assert.equal(admitted.canonicalEligible,false);assert.equal(admitted.publicationAuthority,false);assert.equal(admitted.currentPriceAuthority,false);const replay=await executor.execute({authorizationId:authorization.authorizationId,confirmation:HISTORICAL_ADMISSION_CONFIRMATION,executedBy:"operator:fixture"});assert.equal(replay.status,"ALREADY_CONSUMED");const history=JSON.parse(await readFile(paths.history,"utf8"));assert.equal(Object.keys(history.records).length,1);assert.equal(history.records[observationId].market.condition,null);assert.equal(history.records[observationId].market.shipping,null);assert.equal(history.records[observationId].governance.canonicalEligible,false);assert.equal(history.records[observationId].governance.publicationEligible,false);assert.equal(await readFile(paths.evidence,"utf8"),evidenceBefore);assert.equal(await readFile(paths.decisions,"utf8"),decisionsBefore);
  const cliHistory=join(root,"cli-history.json"),cliAuthorization=join(root,"cli-authorization.json"),shared=[`--evidence-state=${paths.evidence}`,`--decision-state=${paths.decisions}`,`--retention-state=${paths.retention}`,`--sellers-proposal=${paths.proposal}`,`--refresh-result-state=${paths.refreshResult}`,`--refresh-plan-state=${paths.refreshPlan}`],prepareOutput=execFileSync(process.execPath,["scripts/mercury-historical-admission-prepare.mjs",`--evidence-id=${evidenceId}`,"--requested-by=operator:cli-fixture","--reason=Fixture CLI governed historical admission.",`--historical-state=${cliHistory}`,`--authorization-state=${cliAuthorization}`,...shared],{cwd:process.cwd(),encoding:"utf8"}),cliAuthorizationId=prepareOutput.match(/Authorization ID:\s+(mer_histauth_[a-f0-9]{24})/)?.[1];assert.match(prepareOutput,/Historical admission:\s+NOT EXECUTED/);assert.match(prepareOutput,/Actual spend:\s+\$0\.000/);assert.ok(cliAuthorizationId);const executeOutput=execFileSync(process.execPath,["scripts/mercury-historical-admission-execute.mjs",`--authorization-id=${cliAuthorizationId}`,`--confirm=${HISTORICAL_ADMISSION_CONFIRMATION}`,"--executed-by=operator:cli-fixture",`--historical-state=${cliHistory}`,`--authorization-state=${cliAuthorization}`,...shared],{cwd:process.cwd(),encoding:"utf8"});assert.match(executeOutput,/Execution status:\s+ADMITTED/);assert.match(executeOutput,/Current Price authority:\s+NO/);
  const driftRoot=join(root,"drift"),driftPaths={...paths,history:join(driftRoot,"history.json"),authorizations:join(driftRoot,"authorizations.json"),retention:join(driftRoot,"retention.json")};await mkdir(driftRoot,{recursive:true});await copy(".forge-review/acquisition/sellers-df003-retention-latest.json",driftPaths.retention);const driftArgs=new Map([...args].map(([key,value])=>[key,key==="--historical-state"?driftPaths.history:key==="--authorization-state"?driftPaths.authorizations:key==="--retention-state"?driftPaths.retention:value])),driftRuntime=createHistoricalOperatorRuntime(driftArgs,{now:()=>now}),driftAuth=await new HistoricalAdmissionPrepareService({...driftRuntime,now:()=>now}).prepare({evidenceId,requestedBy:"operator:fixture",reason:"Drift fixture."}),retention=JSON.parse(await readFile(driftPaths.retention,"utf8"));retention.governance.lineage.productInfoValidationDigest="f".repeat(64);await writeFile(driftPaths.retention,JSON.stringify(retention));await assert.rejects(()=>new HistoricalAdmissionExecutor({...driftRuntime,now:()=>"2026-09-02T00:01:00Z"}).execute({authorizationId:driftAuth.authorizationId,confirmation:HISTORICAL_ADMISSION_CONFIRMATION,executedBy:"operator:fixture"}),/PROJECTION|BINDING|RETENTION|VALIDATION/);
  console.log("B-013A governed E2J historical admission tests passed (34 cases).");
}finally{await rm(root,{recursive:true,force:true});}
