import assert from "node:assert/strict";
import {execFileSync} from "node:child_process";
import {mkdtemp,rm,writeFile} from "node:fs/promises";
import {join} from "node:path";
import {tmpdir} from "node:os";
import {createHistoricalObservation,FileDataForSeoMarketEvidenceRepository,FileHistoricalObservationRepository} from "../index.js";

const root=await mkdtemp(join(tmpdir(),"hardware-radar-e2n-cli-")),atlasProductId="ram_corsair_cmk32gx5m2b6000z30",providerIdentity={productId:null,dataDocId:"3844868436216882408",gid:null};
try{
 const evidencePath=join(root,"evidence.json"),historyPath=join(root,"history.json"),evidenceRepository=new FileDataForSeoMarketEvidenceRepository({statePath:evidencePath,now:()=>"2026-08-24T00:08:00Z"});
 const candidate={candidateVersion:"1.0",candidateType:"MERCURY_MARKET_OBSERVATION",marketEvidence:{evidenceVersion:"1.0",provider:"DATAFORSEO",source:"DATAFORSEO_GOOGLE_SHOPPING",sourceMethod:"API",seller:{name:"Platinummicro",domain:"platinummicro.com",url:"https://platinummicro.com/item"},pricing:{basePrice:588.99,shippingPrice:null,tax:null,totalPrice:588.99,currency:"USD"},offer:{condition:null,availability:"in_stock"},productEvidence:{title:"Corsair",...providerIdentity},provenance:{sourceTaskId:"task-refresh",observedAt:"2026-08-24T00:07:42Z",rawPayloadReference:"fixture:task-refresh"}},identity:{outcome:"PROBABLE",atlasProductId,externalProductId:null,candidateAtlasProductIds:[],evidence:[]},governance:{requiresReview:true,canonicalObservationEligible:false,automaticPublicationEligible:false}},merchantResolution={resolutionVersion:"1.0",outcome:"DISCOVERED",retailerId:null,merchantKey:"domain:platinummicro.com",sellerName:"Platinummicro",canonicalDomain:"platinummicro.com",suppliedDomain:"platinummicro.com",urlDomain:"platinummicro.com",requiresRegistration:true,evidence:[],reason:"ATLAS_RETAILER_NOT_FOUND"},eligibility={eligibilityVersion:"1.0",status:"REVIEW_REQUIRED",canonicalObservationEligible:false,rawEvidenceRetentionEligible:true,historicalAnalyticsEligible:false,retailerId:null,requiresReview:true,reasons:["MERCHANT_REGISTRATION_REQUIRED"]};
 const retained=await evidenceRepository.retain({candidate,merchantResolution,eligibility}),historyRepository=new FileHistoricalObservationRepository({statePath:historyPath}),observation=createHistoricalObservation({observationId:"mer_hist_bbbbbbbbbbbbbbbb",atlasProductId,retailerId:"RETAILER-0002",marketplace:"platinummicro.com",observationTime:"2026-08-24 00:07:42 +00:00",admittedAt:"2026-08-24T01:00:00Z",market:{sellerName:"Platinummicro",sourceUrl:"https://platinummicro.com/item",basePrice:588.99,totalPrice:588.99,shipping:null,tax:null,currency:"USD",condition:null,availability:"in_stock"},provenance:{retainedEvidenceId:retained.evidenceId,provider:"DATAFORSEO",source:"DATAFORSEO_GOOGLE_SHOPPING",rawPayloadReference:"fixture:task-refresh",acquisition:{type:"HISTORICAL_REFRESH",sellersTaskId:"task-refresh",refreshPlanId:"histrefresh_fixture",authorizationId:"histrefreshauth_fixture",identityReuseAssessmentId:"histidreuse_fixture",sourceEvidenceId:"evidence-original",providerIdentity},identityReview:{productDecisionId:"product",productRemediationId:null,merchantDecisionId:"merchant",merchantRemediationId:null}},admittedBy:"operator:test",idempotencyKey:`E2J_HISTORICAL_ADMISSION:${retained.evidenceId}`});await historyRepository.accept(observation,observation.metadata.idempotencyKey);
 const plan={schemaVersion:"1.0",refreshPlanId:"histrefresh_fixture",operation:"SELLERS",status:"PENDING_OPERATOR_REVIEW",atlasProductId,providerIdentity,existingIdentity:{retailerId:"RETAILER-0002"},previous:{observationId:"mer_hist_original",evidenceId:"evidence-original",providerTaskId:"task-original"}},authorization={requestId:"histrefreshauth_fixture",authorizationType:"HISTORICAL_REFRESH_SELLERS",refreshPlanId:"histrefresh_fixture",planId:"execution-plan",atlasProductId,retailerId:"RETAILER-0002",providerIdentity,createdAt:"2026-08-24T00:03:00Z",expiresAt:"2026-08-24T00:18:00Z",plan:{planId:"execution-plan"}},execution={schemaVersion:"1.0",runs:[{runId:"run",planId:"execution-plan",status:"COMPLETED",finishedAt:"2026-08-24T00:07:43Z",tasks:[{outcome:"COMPLETED",providerTaskId:"task-refresh"}]}]},consumption={schemaVersion:"1.0",consumed:[{authorizationId:"histrefreshauth_fixture",planId:"execution-plan"}]},result={refreshPlanId:"histrefresh_fixture",authorizationId:"histrefreshauth_fixture",providerTaskId:"task-refresh",retrievalStatus:"COMPLETED",retained:1,acquisitionOutcome:"SELLER_OBSERVATIONS_PROCESSED",evidence:[{evidenceId:retained.evidenceId}],identityReuse:[{status:"APPLICABLE",reuseAssessmentId:"histidreuse_fixture",targetEvidenceId:retained.evidenceId}]};const files={plan:join(root,"plan.json"),authorization:join(root,"authorization.json"),execution:join(root,"execution.json"),consumption:join(root,"consumption.json"),result:join(root,"result.json")};for(const [key,value] of Object.entries({plan,authorization,execution,consumption,result}))await writeFile(files[key],JSON.stringify(value));
 const output=execFileSync(process.execPath,["scripts/mercury-history-refresh-status.mjs",`--atlas-product=${atlasProductId}`,"--as-of=2026-08-25T00:00:00Z",`--history-state=${historyPath}`,`--evidence-state=${evidencePath}`,`--plan-state=${files.plan}`,`--authorization-state=${files.authorization}`,`--execution-state=${files.execution}`,`--consumption-state=${files.consumption}`,`--result-state=${files.result}`],{cwd:process.cwd(),encoding:"utf8"});assert.match(output,/Current cycle:\s+COMPLETE/);assert.match(output,/Next action:\s+PREPARE_NEW_REFRESH/);assert.match(output,/Latest observed price:\s+\$588\.99/);assert.doesNotMatch(output,/Current price/i);assert.match(output,/Unattended LIVE:\s+DISABLED/);assert.match(output,/Paid task created:\s+NO/);assert.match(output,/Actual spend:\s+\$0\.000/);
}finally{await rm(root,{recursive:true,force:true});}
console.log("Historical refresh cycle status CLI tests passed.");
