import assert from "node:assert/strict";
import {HistoricalBootstrapProductionComposition,STAGE_A_BOOTSTRAP_ARTIFACT_ID,prepareHistoricalBootstrap} from "../index.js";
const p=(id,memory,form)=>({identity:{atlasProductId:id,brand:"Fixture",manufacturerPartNumber:id},governance:{lifecycleStatus:"ACTIVE",publicationStatus:"READY"},extension:{data:{classification:{memoryType:memory,formFactor:form}}}}),products=[p("p5","DDR5","DIMM"),p("p4","DDR4","DIMM"),p("ps","DDR5","SO_DIMM")],work=products.map(x=>({atlasProductId:x.identity.atlasProductId,providerIdentityState:"ABSENT",plannedStagePath:["PRODUCTS","PRODUCT_INFO","SELLERS"],maximumRemainingPaidTasks:3,maximumRemainingSpendUsd:.003})),artifact=prepareHistoricalBootstrap({asOf:"2026-09-11T12:00:00.000Z",atlasProducts:products,acquisitionPortfolio:{provider:"DATAFORSEO",sourceId:"DATAFORSEO_GOOGLE_SHOPPING",portfolioCycleId:"p",bindingDigest:"a".repeat(64),authorizationState:"NOT_AUTHORIZED",providerSpendAuthorized:false,eligibleProducts:work,costEnvelope:{perTaskCostCeilingUsd:.001,utcDaySpendCeilingUsd:.01}},destinations:products.map((x,i)=>({destinationId:`d${i}`,atlasProductId:x.identity.atlasProductId,status:"ACTIVE"})),historicalObservations:[],evidenceRecords:[],rightsProfile:{retention:{historical:"ALLOWED",durableAuditMetadata:"ALLOWED"},derivation:{historicalAnalytics:"ALLOWED"}}});
const owner=(method)=>({[method]:async()=>null}),composition=new HistoricalBootstrapProductionComposition({artifactRepository:{getById:async()=>artifact},authorizationRepository:{getById:async()=>null,consume:async()=>({status:"CONSUMED"})},productsOwner:owner("createTask"),productInfoOwner:owner("createTask"),sellersOwner:owner("createTask"),retrievalOwner:owner("retrieve"),identityOwner:owner("resolve"),retentionOwner:owner("retain"),comparabilityOwner:owner("assess"),admissionOwner:owner("admit"),spendOwner:{forUtcDay:async()=>.004}});
// The fixture's deterministic id is intentionally different; substitution remains blocked.
await assert.rejects(()=>composition.inspect({artifactId:"other",asOf:"2026-09-11T12:00:00Z"}),/SUBSTITUTION/);
assert.deepEqual(composition.ownerBindings(),{PRODUCTS:"productsOwner.createTask",PRODUCT_INFO:"productInfoOwner.createTask",SELLERS:"sellersOwner.createTask",RETRIEVAL:"retrievalOwner.retrieve",IDENTITY:"identityOwner.resolve",DF003:"retentionOwner.retain",COMPARABILITY:"comparabilityOwner.assess",E2J:"admissionOwner.admit",SPEND:"spendOwner.forUtcDay"});
assert.throws(()=>new HistoricalBootstrapProductionComposition({}),/ARTIFACT_OWNER_REQUIRED/);
console.log("Historical bootstrap production composition tests passed (3 cases).");
