import assert from "node:assert/strict";
import os from "node:os";
import path from "node:path";
import {mkdtemp,rm} from "node:fs/promises";
import {FileSingleWriterRunLock} from "../runtime/FileSingleWriterRunLock.js";
import {createHistoricalFactReplayAuthorization,FileHistoricalFactReplayAuthorizationRepository,HistoricalFactReplayAuthorizationService,HistoricalFactReplayExecutionService,historicalFactReplayAuthorizationConfirmation,historicalFactReplayExecutionConfirmation,HistoricalFactReplayPreparationService} from "../index.js";

const root=await mkdtemp(path.join(os.tmpdir(),"hr-histfact-exec-"));let cases=0;
try{
  const records=Array.from({length:20},(_,i)=>({evidenceId:`evidence-${String(i+1).padStart(2,"0")}`,candidate:{identity:{atlasProductId:`ram-${i+1}`},marketEvidence:{source:i<11?"DATAFORSEO_AMAZON":"DATAFORSEO_GOOGLE_SHOPPING",seller:{name:"Seller",domain:null,url:null},pricing:{basePrice:100+i,totalPrice:100+i,shippingPrice:null,tax:null,currency:"USD"},offer:{condition:null,availability:"IN_STOCK"},provenance:{observedAt:"2026-09-13T00:00:00.000Z"}}},merchantResolution:{outcome:"DISCOVERED"}}));
  const makeAssessment=record=>{const n=record.evidenceId.slice(-2),binding={evidenceId:record.evidenceId,atlasProductId:record.candidate.identity.atlasProductId,historicalObservationId:`mer_hist_${n}`,expectedObservationHash:`observation-hash-${n}`,rightsProfileHash:"rights",acquisition:{taskId:`task-${n}`}};return{factLevelHistoricalEligible:true,canonicalEligible:false,currentPriceEligible:false,cheapestEligible:false,pickEligible:false,publicationEligible:false,candidateBinding:binding,expectedObservation:{observationId:binding.historicalObservationId}};};
  const prep=new HistoricalFactReplayPreparationService({evidenceRepository:{getAll:async()=>structuredClone(records)},historicalRepository:{getAll:async()=>[]},assessmentResolver:async record=>makeAssessment(record)}),plan=await prep.prepare({asOf:"2026-09-13T18:02:35.149Z"});assert.equal(plan.counts.newFacts,20);assert.equal(plan.sourceCohorts.find(x=>x.sourceId==="DATAFORSEO_AMAZON").newFactCount,11);assert.equal(plan.sourceCohorts.find(x=>x.sourceId==="DATAFORSEO_GOOGLE_SHOPPING").newFactCount,9);cases+=3;
  const authRepo=new FileHistoricalFactReplayAuthorizationRepository({statePath:path.join(root,"authorizations.json"),now:()=>"2026-09-13T18:10:00.000Z"}),planLoader=async id=>{if(id!==plan.replayPlanId)throw new Error("HISTORICAL_FACT_REPLAY_PLAN_ID_MISMATCH");return structuredClone(plan);},authorize=new HistoricalFactReplayAuthorizationService({planLoader,authorizationRepository:authRepo,now:()=>"2026-09-13T18:05:00.000Z"});
  await assert.rejects(()=>authorize.authorize({planId:"wrong",operator:"human:fixture",reason:"test",expiresAt:"2026-09-13T19:00:00.000Z",confirmation:historicalFactReplayAuthorizationConfirmation("wrong")}),/PLAN_ID_MISMATCH/);cases++;
  const confirmation=historicalFactReplayAuthorizationConfirmation(plan.replayPlanId),authorization=await authorize.authorize({planId:plan.replayPlanId,operator:"human:fixture",reason:"bounded fixture replay",expiresAt:"2026-09-13T19:00:00.000Z",confirmation}),replayed=await authorize.authorize({planId:plan.replayPlanId,operator:"human:fixture",reason:"bounded fixture replay",expiresAt:"2026-09-13T19:00:00.000Z",confirmation});assert.equal(replayed.authorizationId,authorization.authorizationId);cases+=2;
  await assert.rejects(()=>authorize.authorize({planId:plan.replayPlanId,operator:"human:other",reason:"conflict",expiresAt:"2026-09-13T19:00:00.000Z",confirmation}),/AUTHORIZATION_CONFLICT/);cases++;
  let writes=0;const admitted=new Set(),admissionService={admit:async({evidenceId})=>{if(admitted.has(evidenceId))return{status:"DUPLICATE",evidenceId,observationId:`mer_hist_${evidenceId.slice(-2)}`};admitted.add(evidenceId);writes++;return{status:"ADMITTED",evidenceId,observationId:`mer_hist_${evidenceId.slice(-2)}`};}},assessments=new Map(records.map(record=>[record.evidenceId,makeAssessment(record)])),executor=new HistoricalFactReplayExecutionService({planLoader,authorizationRepository:authRepo,assessmentResolver:async({evidenceId})=>structuredClone(assessments.get(evidenceId)),admissionService,executionLock:new FileSingleWriterRunLock({lockPath:path.join(root,"execute.lock")}),now:()=>"2026-09-13T18:10:00.000Z"});
  await assert.rejects(()=>executor.execute({authorizationId:authorization.authorizationId,confirmation:"WRONG",executedBy:"human:fixture"}),/CONFIRMATION_INVALID/);assert.equal(writes,0);cases+=2;
  const executionConfirmation=historicalFactReplayExecutionConfirmation(authorization.authorizationId),changed=structuredClone(assessments.get(records[0].evidenceId));changed.candidateBinding.rightsProfileHash="changed";assessments.set(records[0].evidenceId,changed);await assert.rejects(()=>executor.execute({authorizationId:authorization.authorizationId,confirmation:executionConfirmation,executedBy:"human:fixture"}),/CANDIDATE_BINDING_CHANGED/);assert.equal(writes,0);cases+=2;assessments.set(records[0].evidenceId,makeAssessment(records[0]));
  const concurrent=await Promise.allSettled([executor.execute({authorizationId:authorization.authorizationId,confirmation:executionConfirmation,executedBy:"human:fixture"}),executor.execute({authorizationId:authorization.authorizationId,confirmation:executionConfirmation,executedBy:"human:fixture"})]),first=concurrent.find(value=>value.status==="fulfilled")?.value,busy=concurrent.find(value=>value.status==="rejected")?.reason;assert.equal(first.status,"EXECUTED");assert.match(String(busy),/EXECUTION_BUSY/);assert.equal(writes,20);assert.equal(first.currentPriceEligible,false);assert.equal(first.cheapestEligible,false);assert.equal(first.pickEligible,false);assert.equal(first.publicationEligible,false);assert.equal(first.providerCalls,0);assert.equal(first.providerSpendUsd,0);cases+=8;
  const third=await executor.execute({authorizationId:authorization.authorizationId,confirmation:executionConfirmation,executedBy:"human:fixture"});assert.equal(third.status,"ALREADY_CONSUMED");assert.equal(writes,20);cases+=2;
  const tampered=structuredClone(plan);tampered.bindingDigest="0".repeat(64);const badAuth=createHistoricalFactReplayAuthorization({plan,operator:"human:x",reason:"x",preparedAt:"2026-09-13T18:05:00.000Z",expiresAt:"2026-09-13T19:00:00.000Z"});assert.ok(badAuth.authorizationId);await assert.rejects(()=>new HistoricalFactReplayAuthorizationService({planLoader:async()=>tampered,authorizationRepository:{record:async()=>{}},now:()=>"2026-09-13T18:05:00.000Z"}).authorize({planId:plan.replayPlanId,operator:"human:x",reason:"x",expiresAt:"2026-09-13T19:00:00.000Z",confirmation}),/PLAN_INVALID/);cases+=2;
  assert.equal(confirmation,`AUTHORIZE-HISTORICAL-FACT-REPLAY-${plan.replayPlanId}`);cases++;
  console.log(`Historical fact replay execution tests passed (${cases} cases).`);
}finally{await rm(root,{recursive:true,force:true,maxRetries:5,retryDelay:20});}
