import assert from "node:assert/strict";
import {mkdtemp,rm,writeFile} from "node:fs/promises";
import {join} from "node:path";
import {tmpdir} from "node:os";
import {FileHistoricalBootstrapProviderResultRepository,createHistoricalBootstrapPrepareDispatcher,createProductionProductInfoPrepareOwner,createProductionSellersPrepareOwner} from "../index.js";

const at="2026-09-11T20:00:00.000Z",rights="a".repeat(64),checkpointId="mer_histbootcp_fixture",artifactId="mer_histbootstrap_"+"b".repeat(24),atlasProductId="ram_fixture",intent="mer_histbootintent_"+"c".repeat(24),executionRepository={getAll:async()=>[]};
const root=await mkdtemp(join(tmpdir(),"hr-h040-"));
try{
 const repository=new FileHistoricalBootstrapProviderResultRepository({statePath:join(root,"results.json")}),latestPi=join(root,"latest-pi.json"),latestSellers=join(root,"latest-sellers.json");
 const proposalA={schemaVersion:"1.0",proposalId:"enrich_a",status:"PENDING_OPERATOR_REVIEW",createdAt:at,sourceTaskId:"products-a",atlasProductId,operation:"PRODUCT_INFO",estimatedCostUsd:.001,maxPaidTasks:1,automaticPaidRetries:0,providerIdentity:{dataDocId:"doc-a"},candidate:{title:"A",score:100,exactMpnMatch:true},authorizationCreated:false},proposalB={...proposalA,proposalId:"enrich_b",sourceTaskId:"products-b",providerIdentity:{dataDocId:"doc-b"}};
 await writeFile(latestPi,JSON.stringify({sourceTaskId:"products-b",atlasProductId,proposal:proposalB,resolution:{recommendationStatus:"RECOMMENDED",recommendedCandidate:{item:{dataDocId:"doc-b"}}},paidTaskCreated:false,actualSpendUsd:0}));
 const piOwner=createProductionProductInfoPrepareOwner({proposalEnvelopePath:latestPi,executionRepository,now:()=>at});assert.equal((await piOwner.prepare()).prepareArtifact.proposalId,"enrich_b");
 const piRef=await repository.recordProgressionProposal({proposal:proposalA,nextOperation:"PRODUCT_INFO",checkpointId,atlasProductId,productIndex:0,resultReferenceId:"result-products-a",sourceRightsProfileDigest:rights,providerSelectionReference:"selection-a"});assert.equal((await repository.recordProgressionProposal({proposal:proposalA,nextOperation:"PRODUCT_INFO",checkpointId,atlasProductId,productIndex:0,resultReferenceId:"result-products-a",sourceRightsProfileDigest:rights,providerSelectionReference:"selection-a"})).proposalReferenceId,piRef.proposalReferenceId);
 const fakeProgression={progressionId:"progression-pi",progressionDigest:"d".repeat(64),resultReferenceId:"result-products-a",progression:{nextOperation:"PRODUCT_INFO",nextProposalId:piRef.proposalReferenceId,nextProposalDigest:piRef.proposalDigest}},resolver={getProgressionById:async()=>fakeProgression,resolveProgressionProposal:input=>repository.resolveProgressionProposal(input)},checkpoint={events:[{type:"RESULT_REVIEWED",productIndex:0,nextStageReference:{artifactId:"progression-pi",digest:"d".repeat(64)}}]},projection={checkpointId,artifactId,atlasProductId,productIndex:0,eventSequence:4,nextPaidOperation:"PRODUCT_INFO",sourceRightsProfileDigest:rights},authorization={checkpointId,atlasProductId,nextOperation:"PRODUCT_INFO",sourceRightsProfileDigest:rights,paidActionIntentId:intent};
 const prepared=await createHistoricalBootstrapPrepareDispatcher({owners:{PRODUCT_INFO:piOwner},proposalRepository:resolver}).prepare({checkpoint,projection,authorization});assert.equal(prepared.prepareArtifact.proposalId,"enrich_a");assert.equal(prepared.authorizationRequest.providerIdentity.dataDocId,"doc-a");
 await assert.rejects(()=>repository.resolveProgressionProposal({proposalReferenceId:piRef.proposalReferenceId,nextOperation:"PRODUCT_INFO",checkpointId,atlasProductId:"other",productIndex:0,sourceRightsProfileDigest:rights,resultReferenceId:"result-products-a"}),/LINEAGE_CONFLICT/);await assert.rejects(()=>repository.resolveProgressionProposal({proposalReferenceId:piRef.proposalReferenceId,nextOperation:"SELLERS",checkpointId,atlasProductId,productIndex:0,sourceRightsProfileDigest:rights,resultReferenceId:"result-products-a"}),/LINEAGE_CONFLICT/);await assert.rejects(()=>repository.resolveProgressionProposal({proposalReferenceId:piRef.proposalReferenceId,nextOperation:"PRODUCT_INFO",checkpointId:"other",atlasProductId,productIndex:0,sourceRightsProfileDigest:rights,resultReferenceId:"result-products-a"}),/LINEAGE_CONFLICT/);await assert.rejects(()=>repository.resolveProgressionProposal({proposalReferenceId:piRef.proposalReferenceId,nextOperation:"PRODUCT_INFO",checkpointId,atlasProductId,productIndex:0,sourceRightsProfileDigest:"e".repeat(64),resultReferenceId:"result-products-a"}),/LINEAGE_CONFLICT/);
 const corruptPath=join(root,"corrupt.json"),corrupt={version:"1.0",results:{},references:{},byTaskIntent:{},progressions:{},proposals:{[piRef.proposalReferenceId]:{...piRef,proposal:{...piRef.proposal,sourceTaskId:"tampered"}}}};await writeFile(corruptPath,JSON.stringify(corrupt));await assert.rejects(()=>new FileHistoricalBootstrapProviderResultRepository({statePath:corruptPath}).resolveProgressionProposal({proposalReferenceId:piRef.proposalReferenceId,nextOperation:"PRODUCT_INFO",checkpointId,atlasProductId,productIndex:0,sourceRightsProfileDigest:rights,resultReferenceId:"result-products-a"}),/LINEAGE_CONFLICT/);
 const sellersA={schemaVersion:"1.0",identityLineageType:"PRODUCT_INFO_VALIDATED",proposalId:"sellerenrich_a",status:"PENDING_OPERATOR_REVIEW",createdAt:at,operation:"SELLERS",atlasProductId,sourceProductsTaskId:"products-a",sourceProductInfoTaskId:"pi-a",sourceProductInfoAuthorizationId:"pi-auth-a",sourceProductInfoProposalId:"enrich_a",providerIdentity:{dataDocId:"doc-a"},evidence:{title:"A",specifications:[],sellerCount:1},governanceBinding:{sourceRightsDigest:rights,provider:"DATAFORSEO",source:"DATAFORSEO_GOOGLE_SHOPPING",locationName:"United States",languageName:"English"},estimatedCostUsd:.001,maxPaidTasks:1,automaticPaidRetries:0,authorizationCreated:false},sellersB={...sellersA,proposalId:"sellerenrich_b",sourceProductsTaskId:"products-b",providerIdentity:{dataDocId:"doc-b"}};
 await writeFile(latestSellers,JSON.stringify({proposal:sellersB,paidTaskCreated:false,actualSpendUsd:0}));const sellersOwner=createProductionSellersPrepareOwner({proposalEnvelopePath:latestSellers,executionRepository,now:()=>at});assert.equal((await sellersOwner.prepare()).prepareArtifact.proposalId,"sellerenrich_b");
 const sellerRef=await repository.recordProgressionProposal({proposal:sellersA,nextOperation:"SELLERS",checkpointId,atlasProductId,productIndex:0,resultReferenceId:"result-products-direct",sourceRightsProfileDigest:rights,providerSelectionReference:"review-a"}),sellerProgression={progressionId:"progression-sellers",progressionDigest:"3".repeat(64),resultReferenceId:"result-products-direct",progression:{nextOperation:"SELLERS",nextProposalId:sellerRef.proposalReferenceId,nextProposalDigest:sellerRef.proposalDigest}},sellerCheckpoint={events:[{type:"RESULT_REVIEWED",productIndex:0,nextStageReference:{artifactId:"progression-sellers",digest:"3".repeat(64)}}]},sellerProjection={...projection,nextPaidOperation:"SELLERS"},sellerAuthorization={...authorization,nextOperation:"SELLERS"};
 const sellerPrepared=await createHistoricalBootstrapPrepareDispatcher({owners:{SELLERS:sellersOwner},proposalRepository:{getProgressionById:async()=>sellerProgression,resolveProgressionProposal:input=>repository.resolveProgressionProposal(input)}}).prepare({checkpoint:sellerCheckpoint,projection:sellerProjection,authorization:sellerAuthorization});assert.equal(sellerPrepared.prepareArtifact.proposalId,"sellerenrich_a");assert.equal(sellerPrepared.authorizationRequest.providerIdentity.dataDocId,"doc-a");
 await assert.rejects(()=>repository.recordProgressionProposal({proposal:{...sellersA,providerIdentity:{dataDocId:"conflict"}},nextOperation:"SELLERS",checkpointId,atlasProductId,productIndex:0,resultReferenceId:"result-products-direct",sourceRightsProfileDigest:rights,providerSelectionReference:"review-a"}),/CONFLICT/);
 const second=await repository.recordProgressionProposal({proposal:{...sellersA,proposalId:"sellerenrich_second",atlasProductId:"ram_second"},nextOperation:"SELLERS",checkpointId,atlasProductId:"ram_second",productIndex:1,resultReferenceId:"result-products-second",sourceRightsProfileDigest:rights});assert.notEqual(second.proposalReferenceId,sellerRef.proposalReferenceId);assert.equal(prepared.providerCalls,0);assert.equal(sellerPrepared.providerCalls,0);assert.equal(prepared.actualSpendUsd,0);assert.equal(sellerPrepared.actualSpendUsd,0);
 console.log("Historical bootstrap immutable proposal handoff tests passed (24 cases).");
}finally{await rm(root,{recursive:true,force:true})}
