import assert from "node:assert/strict";
import crypto from "node:crypto";
import {mkdtemp,rm} from "node:fs/promises";
import {tmpdir} from "node:os";
import {join} from "node:path";
import {
 FileAcquisitionCheckpointRepository,FileDataForSeoPrepareArtifactRepository,
 FileHistoricalBootstrapProviderResultRepository,ProductsCheckpointReviewService,
 assessHistoricalBootstrapExecutionEligibility,createDataForSeoPrepareArtifact,
 createDirectProductsSellersProposal,createHistoricalBootstrapCheckpoint,
 createHistoricalBootstrapPreparedActionResolver,createHistoricalBootstrapProviderResult,
 createProductsIdentityProgressionOwner,historicalBootstrapBindingDigest,historicalBootstrapRightsProfileDigest,
 prepareDurableHistoricalBootstrapContinuation,prepareHistoricalBootstrap,
 projectHistoricalBootstrapCheckpoint
} from "../index.js";

const at="2026-09-11T16:00:00.000Z",portfolioId="mer_acqportfolio_"+"e".repeat(24);
const rightsProfile={acquisition:{api:"ALLOWED"},retention:{historical:"ALLOWED",durableAuditMetadata:"ALLOWED"},derivation:{historicalAnalytics:"ALLOWED"}},rights=historicalBootstrapRightsProfileDigest(rightsProfile);
const product=(id,memoryType,formFactor)=>({identity:{atlasProductId:id,brand:"Corsair",manufacturerPartNumber:"CMK32GX5M2B6000Z30"},governance:{lifecycleStatus:"ACTIVE",publicationStatus:"READY"},extension:{data:{classification:{memoryType,formFactor},capacity:{capacityGb:32,moduleCount:2,capacityPerModuleGb:16},performance:{dataRateMtps:6000,casLatency:30},physical:{color:"BLACK",rgbLighting:false}}}});
const products=[product("fixture_ddr5","DDR5","DIMM"),product("fixture_ddr4","DDR4","DIMM"),product("fixture_sodimm","DDR5","SO_DIMM")],eligibleProducts=products.map(row=>({atlasProductId:row.identity.atlasProductId,providerIdentityState:"ABSENT",plannedStagePath:["PRODUCTS","PRODUCT_INFO","SELLERS"],maximumRemainingPaidTasks:3,maximumRemainingSpendUsd:.003})),portfolio={provider:"DATAFORSEO",sourceId:"DATAFORSEO_GOOGLE_SHOPPING",portfolioCycleId:portfolioId,bindingDigest:"a".repeat(64),sourceRightsProfileDigest:rights,authorizationState:"NOT_AUTHORIZED",providerSpendAuthorized:false,eligibleProducts,costEnvelope:{perTaskCostCeilingUsd:.001,utcDaySpendCeilingUsd:.01}},destinations=products.map((row,index)=>({destinationId:`destination_${index}`,atlasProductId:row.identity.atlasProductId,status:"ACTIVE"}));
const artifact=prepareHistoricalBootstrap({asOf:at,atlasProducts:products,acquisitionPortfolio:portfolio,destinations,historicalObservations:[],evidenceRecords:[],rightsProfile}),checkpoint=createHistoricalBootstrapCheckpoint({artifact,createdAt:at}),projection=projectHistoricalBootstrapCheckpoint({checkpoint});
assert.equal(assessHistoricalBootstrapExecutionEligibility(artifact).eligible,true);assert.equal(projection.sourceRightsProfileDigest,rights);assert.equal(projection.acquisitionPortfolioReference.portfolioCycleId,portfolioId);
const stable=value=>Array.isArray(value)?`[${value.map(stable).join(",")}]`:value&&typeof value==="object"?`{${Object.keys(value).sort().map(key=>`${JSON.stringify(key)}:${stable(value[key])}`).join(",")}}`:JSON.stringify(value),extra=artifact.selected.slice(0,2).map((row,index)=>({...row,atlasProductId:`fixture_extra_${index}`})),largerDraft={...artifact,selected:[...artifact.selected,...extra],costEnvelope:{...artifact.costEnvelope,maximumPaidTasks:15,maximumProviderSpendUsd:.015}},largerBinding=historicalBootstrapBindingDigest(largerDraft),largerArtifact={...largerDraft,bindingDigest:largerBinding,bootstrapPreparationId:`mer_histbootstrap_${crypto.createHash("sha256").update(stable({bindingDigest:largerBinding})).digest("hex").slice(0,24)}`},largerCheckpoint=createHistoricalBootstrapCheckpoint({artifact:largerArtifact,createdAt:at});
assert.equal(assessHistoricalBootstrapExecutionEligibility(largerArtifact).eligible,true);assert.equal(largerCheckpoint.binding.products.length,5);
const continuation=prepareDurableHistoricalBootstrapContinuation({projection,operation:"PRODUCTS",authorizedBy:"operator:fixture",reason:"H038 fixture",authorizedAt:at,expiresAt:"2026-09-11T17:00:00.000Z",currentUtcDaySpendUsd:0});
assert.equal(continuation.sourceRightsProfileDigest,rights);assert.notEqual(prepareDurableHistoricalBootstrapContinuation({...{projection:{...projection,sourceRightsProfileDigest:"b".repeat(64)},operation:"PRODUCTS",authorizedBy:"operator:fixture",reason:"H038 fixture",authorizedAt:at,expiresAt:"2026-09-11T17:00:00.000Z",currentUtcDaySpendUsd:0}}).authorizationBindingHash,continuation.authorizationBindingHash);

const root=await mkdtemp(join(tmpdir(),"hr-h038-"));
try{
 const prepareRepository=new FileDataForSeoPrepareArtifactRepository({statePath:join(root,"prepare.json")}),request={requestId:"authorization-fixture",plan:{decisions:[{decision:"APPROVED",execution:{kind:"PRODUCTS"}}]}},prepareArtifact=await prepareRepository.record(createDataForSeoPrepareArtifact({operation:"PRODUCTS",atlasProductId:projection.atlasProductId,productIndex:0,paidActionIntentId:continuation.paidActionIntentId,bootstrapCheckpointId:checkpoint.checkpointId,bootstrapArtifactId:artifact.bootstrapPreparationId,sourceRightsProfileDigest:rights,originatingCheckpointSequence:1,prepareArtifact:request,authorizationRequest:request,preparedAt:at})),reference={paidActionIntentId:continuation.paidActionIntentId,continuationAuthorizationId:continuation.continuationAuthorizationId,prepareArtifactId:prepareArtifact.prepareArtifactId,prepareArtifactBindingDigest:prepareArtifact.bindingDigest,authorizationRequestId:prepareArtifact.authorizationRequestId,proposalDigest:prepareArtifact.proposalDigest,sourceRightsProfileDigest:rights},preparedCheckpoint={...checkpoint,events:[...checkpoint.events,{sequence:2,type:"PREPARE_BOUND",at,productIndex:0,atlasProductId:projection.atlasProductId,operation:"PRODUCTS",...reference,preparedFromEventSequence:1}]},resolver=createHistoricalBootstrapPreparedActionResolver({prepareRepository});
 assert.equal((await resolver.resolve({checkpoint:preparedCheckpoint,continuation})).prepareArtifact.sourceRightsProfileDigest,rights);
 await assert.rejects(()=>resolver.resolve({checkpoint:preparedCheckpoint,continuation:{...continuation,sourceRightsProfileDigest:"b".repeat(64)}}),/RIGHTS_LINEAGE_CONFLICT/);
 const providerResult={id:"products-task",result:[{items:[{title:"Corsair 32GB DDR5 6000 CL30 CMK32GX5M2B6000Z30 Black",data_docid:"doc-1"}]}]},resultRepository=new FileHistoricalBootstrapProviderResultRepository({statePath:join(root,"results.json")}),result=await resultRepository.record(createHistoricalBootstrapProviderResult({operation:"PRODUCTS",providerTaskId:"products-task",paidActionIntentId:continuation.paidActionIntentId,checkpointId:checkpoint.checkpointId,atlasProductId:projection.atlasProductId,productIndex:0,sourceRightsProfileDigest:rights,operationResult:providerResult,retrievedAt:at}));
 assert.equal(result.sourceRightsProfileDigest,rights);assert.throws(()=>createHistoricalBootstrapProviderResult({operation:"PRODUCTS",providerTaskId:"products-task",paidActionIntentId:continuation.paidActionIntentId,checkpointId:checkpoint.checkpointId,atlasProductId:projection.atlasProductId,productIndex:0,operationResult:providerResult,retrievedAt:at}),/RESULT_INVALID/);
 const identity=await createProductsIdentityProgressionOwner().resolve({atlasProduct:products[0],providerTaskId:"products-task",providerResult}),reviewRepository=new FileAcquisitionCheckpointRepository({rootPath:join(root,"reviews")}),reviewOwner=new ProductsCheckpointReviewService({repository:reviewRepository,now:()=>at}),task={portfolioCycleId:portfolioId,checkpointId:checkpoint.checkpointId,atlasProductId:projection.atlasProductId,query:products[0].identity.manufacturerPartNumber,providerTaskId:"products-task",sourceRightsDigest:rights},reviewResult=await reviewOwner.record({task,result:providerResult,assessment:identity.reviewAssessment}),review=reviewResult.review;
 assert.equal(identity.status,"STRONG_UNIQUE");assert.equal(review.sourceRightsDigest,rights);assert.equal((await reviewOwner.record({task,result:providerResult,assessment:identity.reviewAssessment})).status,"DUPLICATE");
 await assert.rejects(()=>reviewOwner.record({task:{...task,sourceRightsDigest:"b".repeat(64)},result:providerResult,assessment:identity.reviewAssessment}),/MATERIAL_CONFLICT/);
 const sellers=createDirectProductsSellersProposal({atlasProduct:products[0],productsReview:review,sourceRightsDigest:rights,createdAt:at});assert.equal(sellers.governanceBinding.sourceRightsDigest,rights);assert.equal(sellers.identityLineageType,"DIRECT_PRODUCTS_STRONG_IDENTITY");
 assert.equal(result.paidTaskCreated??false,false);assert.equal(sellers.authorizationCreated,false);
}finally{await rm(root,{recursive:true,force:true})}
console.log("Historical bootstrap rights propagation tests passed (26 cases).");
