import assert from "node:assert/strict";
import {mkdtemp,rm} from "node:fs/promises";
import {tmpdir} from "node:os";
import {join} from "node:path";
import crypto from "node:crypto";
import {FileHistoricalBootstrapCheckpointRepository,FileHistoricalBootstrapContinuationRepository,HistoricalBootstrapPaidTaskHandoff,prepareDurableHistoricalBootstrapContinuation,projectHistoricalBootstrapCheckpoint,reconstructHistoricalBootstrapPaidIntent,HISTORICAL_BOOTSTRAP_CHECKPOINT_VERSION} from "../index.js";
const stable=v=>Array.isArray(v)?`[${v.map(stable).join(",")}]`:v&&typeof v==="object"?`{${Object.keys(v).sort().map(k=>`${JSON.stringify(k)}:${stable(v[k])}`).join(",")}}`:JSON.stringify(v),h=v=>crypto.createHash("sha256").update(stable(v)).digest("hex");
const binding={artifactId:"mer_histbootstrap_71c280422c057da3b248a43b",artifactDigest:"a".repeat(64),asOf:"2026-09-11T12:00:00.000Z",sourceId:"DATAFORSEO_GOOGLE_SHOPPING",sourceRightsProfileDigest:"d".repeat(64),acquisitionPortfolioReference:{portfolioCycleId:"mer_acqportfolio_"+"e".repeat(24),bindingDigest:"f".repeat(64)},products:["p1","p2","p3"],taskCap:9,spendCapUsd:.009,utcDayCapUsd:.01},cp={schemaVersion:"1.0",checkpointId:"cp",policyVersion:HISTORICAL_BOOTSTRAP_CHECKPOINT_VERSION,binding,bindingDigest:h(binding),createdAt:"2026-09-11T12:00:00Z",events:[{sequence:1,type:"CHECKPOINT_PREPARED",at:"2026-09-11T12:00:00Z",productIndex:0,atlasProductId:"p1",stage:"PRODUCTS"}]},p=projectHistoricalBootstrapCheckpoint({checkpoint:cp}),make=()=>prepareDurableHistoricalBootstrapContinuation({projection:{...p,artifactDigest:binding.artifactDigest},operation:"PRODUCTS",authorizedBy:"operator:test",reason:"fixture",authorizedAt:"2026-09-11T12:01:00Z",expiresAt:"2026-09-11T12:15:00Z",currentUtcDaySpendUsd:0});
const root=await mkdtemp(join(tmpdir(),"hr-h023-"));try{
 const continuations=new FileHistoricalBootstrapContinuationRepository({statePath:join(root,"auth.json")}),checkpoints=new FileHistoricalBootstrapCheckpointRepository({statePath:join(root,"cp.json")});await checkpoints.create(cp);const auth=await continuations.record(make());assert.equal((await continuations.record(make())).continuationAuthorizationId,auth.continuationAuthorizationId);assert.match(auth.paidActionIntentId,/^mer_histbootintent_/);assert.equal(reconstructHistoricalBootstrapPaidIntent({checkpoint:cp,authorization:auth}).state,"AUTHORIZED_NOT_CONSUMED");
 const cpPrepared=await checkpoints.append("cp",{eventId:`prepare:${auth.paidActionIntentId}`,type:"PREPARE_BOUND",at:"2026-09-11T12:01:30Z",productIndex:0,atlasProductId:"p1",operation:"PRODUCTS",paidActionIntentId:auth.paidActionIntentId,continuationAuthorizationId:auth.continuationAuthorizationId,prepareArtifactId:"prepare-1",prepareArtifactBindingDigest:"b".repeat(64),authorizationRequestId:"task-auth-1",proposalDigest:"c".repeat(64),preparedFromEventSequence:1});let calls=0;const preparedActionResolver={resolve:async()=>({authorizationRequest:{requestId:"task-auth-1"}})},revoked=new HistoricalBootstrapPaidTaskHandoff({continuationRepository:continuations,checkpointRepository:checkpoints,preparedActionResolver,rightsRegistry:{get:()=>({profileDigest:"f".repeat(64),acquisition:{api:"DENIED"}})},spendResolver:async()=>0,taskSpecificOwner:{execute:async()=>{calls++;}},now:()=>"2026-09-11T12:02:00Z"});
 await assert.rejects(()=>revoked.execute({checkpoint:cpPrepared,authorizationId:auth.continuationAuthorizationId,confirmation:auth.confirmation}),/BLOCKED_RIGHTS/);assert.equal(await continuations.getConsumption(auth.continuationAuthorizationId),null);
 const handoff=new HistoricalBootstrapPaidTaskHandoff({continuationRepository:continuations,checkpointRepository:checkpoints,preparedActionResolver,rightsRegistry:{get:()=>({profileDigest:"f".repeat(64),acquisition:{api:"ALLOWED"}})},spendResolver:async()=>0,taskSpecificOwner:{execute:async()=>{calls++;return{providerTaskId:"task-1",taskAuthorizationId:"task-auth-1",executionRunId:"run-1",actualSpendUsd:.001}}},now:()=>"2026-09-11T12:02:00Z"});
 const first=await handoff.execute({checkpoint:cpPrepared,authorizationId:auth.continuationAuthorizationId,confirmation:auth.confirmation,executedBy:"operator:test"});assert.equal(first.status,"PAID_TASK_CREATED");assert.equal(auth.sourceRightsProfileDigest,binding.sourceRightsProfileDigest);assert.equal(calls,1);assert.equal(projectHistoricalBootstrapCheckpoint({checkpoint:await checkpoints.getById("cp")}).cohortState,"WAITING_FOR_RESULT");const replay=await handoff.execute({checkpoint:cpPrepared,authorizationId:auth.continuationAuthorizationId,confirmation:auth.confirmation,executedBy:"operator:test"});assert.equal(replay.status,"ALREADY_CONSUMED");assert.equal(calls,1);
 const consumption=await continuations.getConsumption(auth.continuationAuthorizationId);assert.equal(reconstructHistoricalBootstrapPaidIntent({checkpoint:cp,authorization:auth,consumption}).state,"CONSUMED_WITHOUT_PAID_TASK");assert.equal(reconstructHistoricalBootstrapPaidIntent({checkpoint:cp,authorization:auth,consumption,taskRecords:[{paidActionIntentId:auth.paidActionIntentId,providerTaskId:"task-1"}]}).state,"PAID_TASK_DURABLE_CHECKPOINT_RECONCILIATION_REQUIRED");assert.throws(()=>reconstructHistoricalBootstrapPaidIntent({checkpoint:cp,authorization:auth,taskRecords:[{paidActionIntentId:auth.paidActionIntentId,providerTaskId:"a"},{paidActionIntentId:auth.paidActionIntentId,providerTaskId:"b"}]}),/PAID_ACTION_INTENT_CONFLICT/);
 const blocked=new HistoricalBootstrapPaidTaskHandoff({continuationRepository:continuations,checkpointRepository:checkpoints,preparedActionResolver,rightsRegistry:{get:()=>({acquisition:{api:"ALLOWED"}})},spendResolver:async()=>.01,taskSpecificOwner:{execute:async()=>{throw Error("CALLED")}},now:()=>"2026-09-11T12:02:00Z"});await assert.rejects(()=>blocked.execute({checkpoint:cpPrepared,authorizationId:auth.continuationAuthorizationId,confirmation:auth.confirmation,executedBy:"x"}),/BUDGET_BLOCKED/);await assert.rejects(()=>handoff.execute({checkpoint:cp,authorizationId:auth.continuationAuthorizationId,confirmation:auth.confirmation,executedBy:"x"}),/PREPARE_REFERENCE_REQUIRED/);assert.throws(()=>new HistoricalBootstrapPaidTaskHandoff({continuationRepository:continuations,checkpointRepository:checkpoints,rightsRegistry:{get:()=>({})},spendResolver:async()=>0,taskSpecificOwner:{execute:async()=>{}}}),/DEPENDENCIES_REQUIRED/);console.log("Historical bootstrap continuation tests passed (20 cases).");
}finally{await rm(root,{recursive:true,force:true})}
