import assert from "node:assert/strict";
import {createHistoricalRefreshCadencePolicy,evaluateHistoricalRefreshCadence} from "../index.js";

const atlasProductId="ram_corsair_cmk32gx5m2b6000z30",latest={observationId:"mer_hist_latest",observationTime:"2026-08-24 00:07:42 +00:00",admittedAt:"2026-08-25T00:00:00Z",retailerId:"RETAILER-0002",basePrice:588.99},nextAction={name:"PREPARE_NEW_REFRESH",potentialPaidOperation:"SELLERS",maximumFutureSpendUsd:.001},cycle={atlasProductId,stage:"COMPLETE",nextAction,latestHistoricalObservation:latest},day=24*60*60*1000,policy=createHistoricalRefreshCadencePolicy({policyId:"fixture-daily",enabled:true,minimumIntervalMs:day,atlasProductIds:[atlasProductId],rationale:"Test fixture only."}),at=offset=>new Date(Date.parse(latest.observationTime)+offset).toISOString();
const missing=evaluateHistoricalRefreshCadence({atlasProductId,cycleStatus:cycle,policy:null,asOf:at(day)});assert.equal(missing.dueState,"POLICY_NOT_CONFIGURED");assert.equal(missing.due,null);assert.deepEqual(missing.reasons,["REFRESH_POLICY_NOT_CONFIGURED"]);
const disabledPolicy=createHistoricalRefreshCadencePolicy({policyId:"disabled",enabled:false,atlasProductIds:[atlasProductId]}),disabled=evaluateHistoricalRefreshCadence({atlasProductId,cycleStatus:cycle,policy:disabledPolicy,asOf:at(day)});assert.equal(disabled.dueState,"DISABLED");assert.equal(disabled.due,false);
const before=evaluateHistoricalRefreshCadence({atlasProductId,cycleStatus:cycle,policy,asOf:at(day-1)}),threshold=evaluateHistoricalRefreshCadence({atlasProductId,cycleStatus:cycle,policy,asOf:at(day)}),after=evaluateHistoricalRefreshCadence({atlasProductId,cycleStatus:cycle,policy,asOf:at(day+1)});assert.equal(before.dueState,"NOT_DUE");assert.equal(before.due,false);assert.equal(threshold.dueState,"DUE");assert.equal(threshold.due,true);assert.equal(after.dueState,"DUE");assert.equal(threshold.elapsedSinceObservationMs,day);assert.equal(threshold.nextEligibleRefreshTime,at(day));assert.deepEqual(evaluateHistoricalRefreshCadence({atlasProductId,cycleStatus:cycle,policy,asOf:at(day)}),threshold);assert.equal(threshold.latestObservationTime,latest.observationTime);assert.notEqual(threshold.latestObservationTime,latest.admittedAt);
const isoCycle={...cycle,latestHistoricalObservation:{...latest,observationTime:"2026-08-24T00:07:42.000Z"}},isoResult=evaluateHistoricalRefreshCadence({atlasProductId,cycleStatus:isoCycle,policy,asOf:"2026-08-25T00:07:42.000Z"});assert.equal(isoResult.dueState,"DUE");assert.equal(Date.parse(isoResult.latestObservationTime),Date.parse(latest.observationTime));assert.equal(threshold.nextEligibleRefreshTime,"2026-08-25T00:07:42.000Z");
const wrong=createHistoricalRefreshCadencePolicy({policyId:"wrong",enabled:true,minimumIntervalMs:day,atlasProductIds:["other_product"]});assert.equal(evaluateHistoricalRefreshCadence({atlasProductId,cycleStatus:cycle,policy:wrong,asOf:at(day)}).dueState,"BLOCKED");const retailerScoped=createHistoricalRefreshCadencePolicy({policyId:"retailer",enabled:true,minimumIntervalMs:day,atlasProductIds:[atlasProductId],retailerIds:["RETAILER-0001"]});assert.equal(evaluateHistoricalRefreshCadence({atlasProductId,cycleStatus:cycle,policy:retailerScoped,asOf:at(day)}).dueState,"BLOCKED");
for(const stage of ["AWAITING_RESULT_RETRIEVAL","AWAITING_HISTORICAL_ADMISSION","HISTORICAL_ELIGIBLE","REVIEW_REQUIRED","BLOCKED","PAID_EXECUTION_FAILED","AUTHORIZATION_PREPARED"]){const value=evaluateHistoricalRefreshCadence({atlasProductId,cycleStatus:{...cycle,stage},policy,asOf:at(day*2)});assert.equal(value.dueState,"BLOCKED",stage);assert.equal(value.due,false);}
const noSellers=evaluateHistoricalRefreshCadence({atlasProductId,cycleStatus:{...cycle,stage:"NO_SELLER_OBSERVATIONS"},policy,asOf:at(day)});assert.equal(noSellers.dueState,"DUE");assert.deepEqual(noSellers.reasons,["REFRESH_INTERVAL_ELAPSED"]);
for(const trend of ["FLAT","UP","DOWN"]){for(const basePrice of [1,588.99,9999]){const value=evaluateHistoricalRefreshCadence({atlasProductId,cycleStatus:{...cycle,latestHistoricalObservation:{...latest,basePrice},trend},policy,asOf:at(day)});assert.equal(value.dueState,"DUE");assert.equal(value.nextEligibleRefreshTime,threshold.nextEligibleRefreshTime);}}
assert.equal(threshold.potentialFutureTask,"SELLERS");assert.equal(threshold.maximumFutureSpendUsd,.001);assert.equal(threshold.automaticExecution,false);assert.equal(threshold.unattendedLive,false);assert.equal(threshold.paidActionExecuted,false);assert.equal(threshold.paidTaskCreated,false);assert.equal(threshold.actualSpendUsd,0);assert.throws(()=>createHistoricalRefreshCadencePolicy({policyId:"bad",enabled:true,atlasProductIds:[atlasProductId]}),/INTERVAL_REQUIRED/);assert.throws(()=>evaluateHistoricalRefreshCadence({atlasProductId,cycleStatus:cycle,policy,asOf:"invalid"}),/INPUT_INVALID/);
console.log("Historical refresh cadence policy tests passed.");
