import assert from "node:assert/strict";
import {mkdtemp,readFile,rm,writeFile} from "node:fs/promises";
import {execFile} from "node:child_process";
import {promisify} from "node:util";
import os from "node:os";
import path from "node:path";
import {createHistoricalRefreshAuthorizationRequest,assertHistoricalRefreshAuthorizationBinding,assertHistoricalRefreshConfirmation,historicalRefreshPlanDigest,HISTORICAL_REFRESH_CONFIRMATION,createLiveAcquisitionAuthorization,evaluateLiveAcquisitionAuthorization,SingleUseAuthorizedLiveAcquisitionExecutor,DataForSeoAcquisitionService,DataForSeoTaskLedger,FileDataForSeoTaskLedger,FileLiveAuthorizationConsumptionRepository,FileAcquisitionExecutionLedgerRepository,FileSingleWriterRunLock,ControlledAcquisitionExecutor} from "../index.js";

const refreshPlan=Object.freeze({schemaVersion:"1.0",refreshPlanId:"histrefresh_fixture",operation:"SELLERS",status:"PENDING_OPERATOR_REVIEW",atlasProductId:"ram_fixture",providerIdentity:{productId:null,dataDocId:"3844868436216882408",gid:null},existingIdentity:{productState:"VERIFIED",productDecisionId:"product-decision",merchantState:"REGISTERED",merchantDecisionId:"merchant-decision",retailerId:"RETAILER-0002"},minimumSafePath:{productsRequired:false,productInfoPaidTaskRequired:false,governedProductInfoProvenanceReused:true,sellersPaidTaskRequired:true,directSellersEligible:true},previous:{observationId:"histobs_previous",observationTime:"2026-08-22T00:00:00Z",evidenceId:"dfev_previous",providerTaskId:"sellers_previous"},spendPolicy:{maxPaidTasks:1,maxSpendUsd:.001,maxSpendPerDayUsd:.01,automaticPaidRetries:0,singleUseAuthorizationRequired:true,newAuthorizationRequired:true},paidTaskCreated:false,actualSpendUsd:0,historicalAdmissionPerformed:false,canonicalPromotionAuthorized:false,publicationAuthorized:false});
const sourceValidation={valid:true,refreshPlanId:refreshPlan.refreshPlanId,refreshPlanDigest:historicalRefreshPlanDigest(refreshPlan)};const createdAt="2026-08-23T12:00:00.000Z";assert.throws(()=>createHistoricalRefreshAuthorizationRequest({refreshPlan,createdAt}),/CURRENT_SOURCE_VALIDATION_REQUIRED/);const request=createHistoricalRefreshAuthorizationRequest({refreshPlan,sourceValidation,createdAt});
assert.equal(request.authorizationType,"HISTORICAL_REFRESH_SELLERS");assert.equal(request.operation,"SELLERS");assert.equal(request.refreshPlanId,refreshPlan.refreshPlanId);assert.equal(request.atlasProductId,"ram_fixture");assert.equal(request.retailerId,"RETAILER-0002");assert.deepEqual(request.providerIdentity,refreshPlan.providerIdentity);assert.deepEqual(request.previous,refreshPlan.previous);assert.equal(request.maxPaidTasks,1);assert.equal(request.maxSpendUsd,.001);assert.equal(request.automaticPaidRetries,0);assert.equal(request.singleUse,true);assert.equal(request.expiresAt,"2026-08-23T12:15:00.000Z");assert.equal(request.status,"PENDING_OPERATOR_APPROVAL");assert.match(request.refreshPlanDigest,/^[a-f0-9]{64}$/);assert.equal(request.refreshPlanDigest,historicalRefreshPlanDigest(refreshPlan));assertHistoricalRefreshAuthorizationBinding({request,refreshPlan});assert.equal(HISTORICAL_REFRESH_CONFIRMATION,"SPEND-REFRESH-0.001");
assert.throws(()=>assertHistoricalRefreshAuthorizationBinding({request:{...request,currentSourceValidated:undefined},refreshPlan}),/AUTHORIZATION_NOT_PENDING/);assertHistoricalRefreshConfirmation(HISTORICAL_REFRESH_CONFIRMATION);assert.throws(()=>assertHistoricalRefreshConfirmation(),/EXPLICIT_CONFIRMATION_REQUIRED/);assert.throws(()=>assertHistoricalRefreshConfirmation("YES"),/EXPLICIT_CONFIRMATION_REQUIRED/);
assert.equal(request.plan.approvedTaskCount,1);assert.equal(request.plan.estimatedApprovedSpendUsd,.001);assert.equal(request.plan.policy.maxPaidTasksPerRun,1);assert.equal(request.plan.policy.maxSpendPerRunUsd,.001);assert.equal(request.plan.policy.maxSpendPerDayUsd,.01);assert.equal(request.plan.policy.automaticPaidRetries,0);assert.equal(request.plan.decisions[0].execution.kind,"SELLERS");assert.equal(request.plan.decisions[0].execution.acquisitionCycleId,refreshPlan.refreshPlanId);

for(const mutate of [
 x=>x.refreshPlanId="other",x=>x.atlasProductId="other",x=>x.existingIdentity.retailerId="RETAILER-9999",x=>x.providerIdentity.dataDocId="other",x=>x.previous.evidenceId="other",x=>x.previous.providerTaskId="other",x=>x.operation="PRODUCT_INFO",x=>x.spendPolicy.maxPaidTasks=2,x=>x.spendPolicy.maxSpendUsd=.002,x=>x.spendPolicy.automaticPaidRetries=1,x=>x.existingIdentity.productState="PROBABLE",x=>x.existingIdentity.merchantState="DISCOVERED"
]){const changed=structuredClone(refreshPlan);mutate(changed);assert.throws(()=>assertHistoricalRefreshAuthorizationBinding({request,refreshPlan:changed}));}
for(const mutate of [x=>x.plan.decisions[0].execution.kind="PRODUCT_INFO",x=>x.plan.decisions[0].execution.dataDocId="other",x=>x.plan.decisions[0].execution.acquisitionCycleId="other",x=>x.maxPaidTasks=2,x=>x.maxSpendUsd=.002,x=>x.automaticPaidRetries=1,x=>x.singleUse=false]){const changed=structuredClone(request);mutate(changed);assert.throws(()=>assertHistoricalRefreshAuthorizationBinding({request:changed,refreshPlan}));}

const auth=createLiveAcquisitionAuthorization({authorizationId:request.requestId,authorized:true,planId:request.planId,authorizedAt:"2026-08-23T12:01:00Z",expiresAt:request.expiresAt,maxSpendUsd:.001,maxPaidTasks:1});assert.equal(evaluateLiveAcquisitionAuthorization({plan:request.plan,authorization:auth,now:"2026-08-23T12:14:59Z"}).status,"LIVE_AUTHORIZED");assert.equal(evaluateLiveAcquisitionAuthorization({plan:request.plan,authorization:auth,now:request.expiresAt}).status,"LIVE_BLOCKED_EXPIRED");
assert.equal(evaluateLiveAcquisitionAuthorization({plan:request.plan,authorization:{...auth,planId:"other"},now:"2026-08-23T12:02:00Z"}).status,"LIVE_BLOCKED_PLAN_MISMATCH");
assert.throws(()=>createHistoricalRefreshAuthorizationRequest({refreshPlan,sourceValidation,createdAt,spentTodayUsd:.01}),/DAILY_BUDGET_EXCEEDED/);assert.doesNotThrow(()=>createHistoricalRefreshAuthorizationRequest({refreshPlan,sourceValidation,createdAt,spentTodayUsd:.009}));

let paidCalls=0;const consumed=new Set();const executions=[];const single=new SingleUseAuthorizedLiveAcquisitionExecutor({executor:{execute:async plan=>{paidCalls++;executions.push(structuredClone(plan));return {status:"COMPLETED",run:{actualSpendUsd:.001,tasks:[{providerTaskId:"new-sellers-task"}]}};}},consumptionRepository:{isConsumed:async id=>consumed.has(id),consume:async({authorizationId,planId,consumedAt})=>consumed.has(authorizationId)?{status:"ALREADY_CONSUMED"}:(consumed.add(authorizationId),{status:"CONSUMED",authorizationId,planId,consumedAt})},now:()=>"2026-08-23T12:02:00Z"});
const first=await single.execute({plan:request.plan,authorization:auth});assert.equal(first.status,"COMPLETED");assert.equal(first.authorizationConsumed,true);assert.equal(paidCalls,1);assert.equal(executions[0].decisions[0].execution.kind,"SELLERS");const replay=await single.execute({plan:request.plan,authorization:auth});assert.equal(replay.status,"LIVE_AUTHORIZATION_ALREADY_CONSUMED");assert.equal(paidCalls,1);

let posted=0;const taskLedger=new DataForSeoTaskLedger();const client={postSellersTask:async()=>{posted++;return {id:`task-${posted}`,cost:.001,status_code:20100};}};const acquisition=new DataForSeoAcquisitionService({client,ledger:taskLedger});const base={dataDocId:"3844868436216882408"};const oldTask=await acquisition.createSellersTask(base);const refreshTask=await acquisition.createSellersTask({...base,acquisitionCycleId:refreshPlan.refreshPlanId});assert.notEqual(oldTask.requestKey,refreshTask.requestKey);assert.equal(posted,2);await assert.rejects(()=>acquisition.createSellersTask({...base,acquisitionCycleId:refreshPlan.refreshPlanId}),/DUPLICATE_PAID_TASK/);

const root=await mkdtemp(path.join(os.tmpdir(),"hr-e2l1-"));try{const before=structuredClone(refreshPlan);assert.deepEqual(refreshPlan,before);const taskFile=path.join(root,"tasks.json"),executionFile=path.join(root,"executions.json"),consumptionFile=path.join(root,"consumptions.json");let durableCalls=0;const durableService=new DataForSeoAcquisitionService({client:{postSellersTask:async()=>{durableCalls++;return {id:"new-refresh-task",cost:.001,status_code:20100};}},ledger:new FileDataForSeoTaskLedger(taskFile)});const controlled=new ControlledAcquisitionExecutor({runLock:new FileSingleWriterRunLock({lockPath:path.join(root,"run.lock")}),ledgerRepository:new FileAcquisitionExecutionLedgerRepository({filePath:executionFile}),transport:{execute:async execution=>{assert.equal(execution.kind,"SELLERS");const task=await durableService.createSellersTask(execution);return {providerTaskId:task.taskId,costUsd:task.costUsd,status:task.createdStatus};}},now:()=>"2026-08-23T12:02:00Z",runId:()=>"refresh-run"});const durableSingle=new SingleUseAuthorizedLiveAcquisitionExecutor({executor:controlled,consumptionRepository:new FileLiveAuthorizationConsumptionRepository({filePath:consumptionFile}),now:()=>"2026-08-23T12:02:00Z"});assert.equal((await durableSingle.execute({plan:request.plan,authorization:auth})).status,"COMPLETED");assert.equal((await durableSingle.execute({plan:request.plan,authorization:auth})).status,"LIVE_AUTHORIZATION_ALREADY_CONSUMED");assert.equal(durableCalls,1);const taskState=JSON.parse(await readFile(taskFile,"utf8"));assert.equal(taskState.length,1);assert.equal(taskState[0].kind,"SELLERS");assert.equal(taskState[0].taskId,"new-refresh-task");const executionState=JSON.parse(await readFile(executionFile,"utf8"));assert.equal(executionState.runs.length,1);assert.equal(executionState.runs[0].attemptedTasks,1);assert.equal(executionState.runs[0].completedTasks,1);assert.equal(executionState.runs[0].actualSpendUsd,.001);const consumptionState=JSON.parse(await readFile(consumptionFile,"utf8"));assert.equal(consumptionState.consumed.length,1);assert.equal(consumptionState.consumed[0].authorizationId,request.requestId);
const liveScript=await readFile(new URL("../../../scripts/mercury-history-refresh-live-execute-once.mjs",import.meta.url),"utf8");assert.match(liveScript,/assertHistoricalRefreshConfirmation/);assert.match(liveScript,/createSellersTask/);assert.doesNotMatch(liveScript,/getSellersResult/);assert.doesNotMatch(liveScript,/historical.*admit/i);const planFile=path.join(root,"plan.json"),ledgerFile=path.join(root,"ledger.json"),outFile=path.join(root,"authorization.json");await writeFile(planFile,JSON.stringify(refreshPlan));await writeFile(ledgerFile,JSON.stringify({schemaVersion:"1.0",runs:[]}));await assert.rejects(()=>promisify(execFile)(process.execPath,[new URL("../../../scripts/mercury-history-refresh-live-prepare.mjs",import.meta.url).pathname.slice(process.platform==="win32"?1:0),`--refresh-plan=${planFile}`,`--execution-ledger=${ledgerFile}`,`--out=${outFile}`,"--fixture-mode=true"]),/TEST_REFRESH_STATE_PATH_REQUIRED/);await assert.rejects(()=>promisify(execFile)(process.execPath,[new URL("../../../scripts/mercury-history-refresh-live-prepare.mjs",import.meta.url).pathname.slice(process.platform==="win32"?1:0),"--plan-state=.forge-review/acquisition/historical-refresh-plan.json","--authorization-state=.forge-review/acquisition/historical-refresh-authorization-request.json","--result-state=x","--evidence-state=x","--historical-state=x","--decision-state=x","--sellers-authorization=x","--execution-ledger=x","--fixture-mode=true"]),/TEST_PRODUCTION_REFRESH_STATE_WRITE_BLOCKED/);assert.equal(paidCalls,1);}finally{await rm(root,{recursive:true,force:true});}
console.log("Historical refresh authorization tests passed.");
