import assert from "node:assert/strict";
import { HistoricalFactReplayPreparationService, validateHistoricalFactReplayPlan } from "../index.js";

const record = (id, source, price = 100, currency = "USD", product = "ram_fixture") => ({ evidenceId:id, candidate:{ identity:{outcome:product?"CONFIRMED":"AMBIGUOUS",atlasProductId:product}, marketEvidence:{source,seller:{name:"Observed Seller",domain:null,url:null},pricing:{basePrice:price,totalPrice:price,shippingPrice:null,tax:null,currency},offer:{condition:null,availability:null},provenance:{observedAt:"2026-09-13T00:00:00.000Z"}}},merchantResolution:{outcome:"DISCOVERED"} });
const expected = value => ({ observationId:`mer_hist_${value.evidenceId.slice(-16).padStart(16,"0")}`,atlasProductId:"ram_fixture",observationTime:value.candidate.marketEvidence.provenance.observedAt,market:{sellerName:"Observed Seller",sourceUrl:null,basePrice:value.candidate.marketEvidence.pricing.basePrice,totalPrice:value.candidate.marketEvidence.pricing.totalPrice,shipping:null,tax:null,currency:value.candidate.marketEvidence.pricing.currency,condition:null,availability:null},provenance:{retainedEvidenceId:value.evidenceId,provider:"DATAFORSEO",source:value.candidate.marketEvidence.source,rawPayloadReference:`fixture:${value.evidenceId}`} });
const assessment = value => ({ assessmentId:`assessment:${value.evidenceId}`,factLevelHistoricalEligible:true,factAssessment:{reasons:[]},promotionAssessment:{productIdentity:"VERIFIED",merchantIdentity:"DISCOVERED"},comparabilityAssessment:{classification:"UNKNOWN_COMPARABILITY"},candidateBinding:{atlasProductId:"ram_fixture",historicalObservationId:expected(value).observationId,expectedObservationHash:`hash:${value.evidenceId}`},expectedObservation:expected(value),canonicalEligible:false,currentPriceEligible:false,cheapestEligible:false,pickEligible:false,publicationEligible:false });

const amazonGood=record("amazon-good","DATAFORSEO_AMAZON"),amazonMissingPrice=record("amazon-empty","DATAFORSEO_AMAZON",null,null),googleDuplicate=record("google-duplicate","DATAFORSEO_GOOGLE_SHOPPING"),googleUnresolved=record("google-unresolved","DATAFORSEO_GOOGLE_SHOPPING",90,"USD",null),rightsChanged=record("google-rights","DATAFORSEO_GOOGLE_SHOPPING"),lineageChanged=record("google-lineage","DATAFORSEO_GOOGLE_SHOPPING"),records=[amazonGood,amazonMissingPrice,googleDuplicate,googleUnresolved,rightsChanged,lineageChanged],duplicateObservation=expected(googleDuplicate);
const resolver=async value=>{if(value.evidenceId===amazonMissingPrice.evidenceId)throw new Error("HISTORICAL_FACT_ITEM_PRICE_INVALID");if(value.evidenceId===googleUnresolved.evidenceId)throw new Error("HISTORICAL_FACT_PRODUCT_NOT_VERIFIED");if(value.evidenceId===rightsChanged.evidenceId)throw new Error("HISTORICAL_SOURCE_RIGHTS_DENIED");if(value.evidenceId===lineageChanged.evidenceId)throw new Error("HISTORICAL_ACQUISITION_CHAIN_MISMATCH");return assessment(value);};
const service=new HistoricalFactReplayPreparationService({evidenceRepository:{getAll:async()=>structuredClone(records)},historicalRepository:{getAll:async()=>[structuredClone(duplicateObservation)]},assessmentResolver:resolver}),input={asOf:"2026-09-13T20:00:00.000Z"},first=await service.prepare(input),replay=await service.prepare(input);
assert.deepEqual(replay,first);assert.equal(validateHistoricalFactReplayPlan(first).valid,true);assert.equal(first.counts.newFacts,1);assert.equal(first.counts.duplicates,1);assert.equal(first.counts.blocked,4);assert.equal(first.newFacts[0].evidenceId,amazonGood.evidenceId);assert.equal(first.inventory.find(value=>value.evidenceId===googleDuplicate.evidenceId).classification,"DUPLICATE_EXISTING_FACT");assert.equal(first.inventory.find(value=>value.evidenceId===amazonGood.evidenceId).comparabilityClassification,"UNKNOWN_COMPARABILITY");assert.equal(first.inventory.find(value=>value.evidenceId===amazonGood.evidenceId).shipping,null);assert.equal(first.inventory.find(value=>value.evidenceId===amazonGood.evidenceId).condition,null);assert.equal(first.authority.executionAuthorized,false);assert.equal(first.authority.currentPriceEligible,false);assert.equal(first.authority.cheapestEligible,false);assert.equal(first.authority.pickEligible,false);assert.equal(first.authority.publicationEligible,false);assert.equal(first.authority.providerCallsRequired,0);assert.equal(first.authority.providerSpendUsd,0);
const conflict=structuredClone(duplicateObservation);conflict.market.basePrice=101;const conflictingService=new HistoricalFactReplayPreparationService({evidenceRepository:{getAll:async()=>[structuredClone(googleDuplicate)]},historicalRepository:{getAll:async()=>[conflict]},assessmentResolver:async value=>assessment(value)});await assert.rejects(()=>conflictingService.prepare(input),/HISTORICAL_FACT_REPLAY_CONFLICT/);
console.log("Historical fact replay preparation tests passed (15 cases).");
