import assert from "node:assert/strict";
import crypto from "node:crypto";
import {execFileSync} from "node:child_process";
import {mkdtemp,rm,writeFile} from "node:fs/promises";
import {join} from "node:path";
import {tmpdir} from "node:os";
import {
  FileDataForSeoMarketEvidenceRepository,FileIdentityReviewDecisionRepository,IdentityReviewService,
  createProductIdentityReviewDecision,createMerchantIdentityReviewDecision,projectIdentityReviewState,
  assessDataForSeoEvidencePromotion
} from "../index.js";

const candidate={candidateVersion:"1.0",candidateType:"MERCURY_MARKET_OBSERVATION",marketEvidence:{evidenceVersion:"1.0",provider:"DATAFORSEO",source:"DATAFORSEO_GOOGLE_SHOPPING",sourceMethod:"API",seller:{name:"Platinummicro",domain:"platinummicro.com",url:"https://platinummicro.com/item"},pricing:{basePrice:588.99,shippingPrice:null,tax:null,totalPrice:588.99,currency:"USD"},offer:{condition:null,details:"Corsair CMK32GX5M2B6000Z30",availability:"in_stock"},productEvidence:{title:"Corsair CMK32GX5M2B6000Z30",dataDocId:"3844868436216882408",productId:null,gid:null},provenance:{sourceTaskId:"remediation-task",observedAt:"2026-08-21T16:31:45.604Z",rawPayloadReference:"fixture:remediation"}},identity:{outcome:"PROBABLE",atlasProductId:"ram_corsair_cmk32gx5m2b6000z30",externalProductId:null,candidateAtlasProductIds:[],evidence:[]},governance:{requiresReview:true,canonicalObservationEligible:false,automaticPublicationEligible:false}};
const merchant={resolutionVersion:"1.0",outcome:"DISCOVERED",retailerId:null,merchantKey:"domain:platinummicro.com",sellerName:"Platinummicro",canonicalDomain:"platinummicro.com",suppliedDomain:"platinummicro.com",urlDomain:"platinummicro.com",requiresRegistration:true,evidence:[],reason:"ATLAS_RETAILER_NOT_FOUND"};
const eligibility={eligibilityVersion:"1.0",status:"REVIEW_REQUIRED",canonicalObservationEligible:false,rawEvidenceRetentionEligible:true,historicalAnalyticsEligible:false,retailerId:null,requiresReview:true,reasons:["MERCHANT_REGISTRATION_REQUIRED"]};
const root=await mkdtemp(join(tmpdir(),"hardware-radar-audit-remediation-"));
try{
  const evidencePath=join(root,"evidence.json");const decisionPath=join(root,"decisions.json");const evidenceRepository=new FileDataForSeoMarketEvidenceRepository({statePath:evidencePath,now:()=>"2026-08-22T10:00:00Z"});const retained=await evidenceRepository.retain({candidate,merchantResolution:merchant,eligibility});const record=await evidenceRepository.getById(retained.evidenceId);const retainedOriginal=structuredClone(record);
  const defective={schemaVersion:"1.0",subjectType:"PRODUCT_IDENTITY",atlasProductId:candidate.identity.atlasProductId,previousState:"PROBABLE",requestedState:"VERIFIED",decisionOutcome:"APPROVED",reviewedAt:"2026-08-22T10:05:00Z",reviewedBy:"<YOUR_OPERATOR_LABEL>",reason:"Original product evidence review.",supportingEvidenceReferences:[record.evidenceId],contradictionStatus:"NONE",audit:{source:"IDENTITY_REVIEW_APPROVAL_CLI",requestId:"product-review-fixture",preparedAt:"2026-08-22T10:01:00Z"},retainedEvidenceModified:false,promotionAuthorized:false,identityReviewDecisionId:"mer_idrev_000000001",sequence:1,recordedAt:"2026-08-22T10:06:00Z"};
  await writeFile(decisionPath,JSON.stringify({version:"1.0",sequence:1,decisions:{[defective.identityReviewDecisionId]:defective},bySubject:{[`PRODUCT_IDENTITY:${candidate.identity.atlasProductId}`]:[defective.identityReviewDecisionId]},idempotency:{}}),"utf8");
  assert.throws(()=>createProductIdentityReviewDecision({...defective,identityReviewDecisionId:undefined,sequence:undefined,recordedAt:undefined}),/non-placeholder operator identity/);
  assert.throws(()=>createMerchantIdentityReviewDecision({subjectType:"MERCHANT_IDENTITY",discoveredMerchantName:"X",canonicalMerchantName:"X",canonicalDomain:"example.com",merchantId:"RETAILER-0002",merchantActive:true,previousState:"DISCOVERED",requestedState:"REGISTERED",decisionOutcome:"APPROVED",reviewedAt:"2026-08-22T10:05:00Z",reviewedBy:"<ANY_TEMPLATE>",reason:"x",supportingEvidenceReferences:[record.evidenceId],contradictionStatus:"NONE",audit:{source:"test",requestId:"x",preparedAt:"2026-08-22T10:01:00Z"}}),/non-placeholder operator identity/);
  const repository=new FileIdentityReviewDecisionRepository({statePath:decisionPath,requireExisting:true,now:()=>"2026-08-22T10:10:00Z"});const service=new IdentityReviewService({evidenceRepository,decisionRepository:repository});const decisions=await repository.getAll();const originalDecision=structuredClone(decisions[0]);
  const before=projectIdentityReviewState({record,decisions,remediations:[]});assert.equal(before.product.state,"PROBABLE");assert.equal(before.merchant.state,"DISCOVERED");const beforeAssessment=assessDataForSeoEvidencePromotion({records:[record],identityReviewDecisions:decisions,identityReviewRemediations:[]});assert.equal(beforeAssessment.state,"REVIEW_REQUIRED");assert.equal(beforeAssessment.productIdentity,"PROBABLE");assert.equal(beforeAssessment.historicalEligible,false);
  const input={decisionId:defective.identityReviewDecisionId,confirmationToken:"REMEDIATE-IDENTITY-REVIEW-AUDIT",correctedReviewedBy:"operator:actual",reason:"Replace accidental template reviewer with the operator who performed the original review.",remediatedAt:"2026-08-22T10:11:00Z",remediatedBy:"operator:actual"};const remediation=await service.remediateReviewerAudit(input);assert.equal(remediation.identityReviewRemediationId,"mer_idrem_000000001");assert.equal(remediation.originalDecisionId,defective.identityReviewDecisionId);assert.equal(remediation.originalReviewedBy,"<YOUR_OPERATOR_LABEL>");assert.equal(remediation.correctedReviewedBy,"operator:actual");assert.equal(remediation.originalDecisionHash,crypto.createHash("sha256").update(JSON.stringify(originalDecision)).digest("hex"));
  assert.deepEqual(await repository.getById(defective.identityReviewDecisionId),originalDecision);assert.deepEqual(await evidenceRepository.getById(record.evidenceId),retainedOriginal);assert.equal((await repository.getAllRemediations()).length,1);
  const after=projectIdentityReviewState({record,decisions:await repository.getAll(),remediations:await repository.getAllRemediations()});assert.equal(after.product.state,"VERIFIED");assert.equal(after.merchant.state,"DISCOVERED");assert.equal(after.remediationId,undefined);assert.equal(after.product.remediationId,remediation.identityReviewRemediationId);
  const afterAssessment=assessDataForSeoEvidencePromotion({records:[record],identityReviewDecisions:await repository.getAll(),identityReviewRemediations:await repository.getAllRemediations()});assert.equal(afterAssessment.productIdentity,"VERIFIED");assert.equal(afterAssessment.merchantIdentity,"DISCOVERED");assert.equal(afterAssessment.state,"REVIEW_REQUIRED");assert.equal(afterAssessment.historicalEligible,false);assert.equal(afterAssessment.canonicalEligible,false);assert.equal(afterAssessment.publicationEligible,false);
  const replay=await service.remediateReviewerAudit({...input,remediatedAt:"2026-08-22T10:12:00Z"});assert.equal(replay.identityReviewRemediationId,remediation.identityReviewRemediationId);assert.equal((await repository.getAllRemediations()).length,1);await assert.rejects(()=>service.remediateReviewerAudit({...input,reason:"Conflicting correction.",remediatedAt:"2026-08-22T10:13:00Z"}),/REMEDIATION_CONFLICT/);

  const cliRoot=join(root,"cli");const cliEvidence=join(cliRoot,"evidence.json");const cliDecision=join(cliRoot,"decisions.json");const cliEvidenceRepository=new FileDataForSeoMarketEvidenceRepository({statePath:cliEvidence});const cliRetained=await cliEvidenceRepository.retain({candidate,merchantResolution:merchant,eligibility});const cliDefective={...defective,supportingEvidenceReferences:[cliRetained.evidenceId]};await writeFile(cliDecision,JSON.stringify({version:"1.0",sequence:1,decisions:{[cliDefective.identityReviewDecisionId]:cliDefective},bySubject:{[`PRODUCT_IDENTITY:${candidate.identity.atlasProductId}`]:[cliDefective.identityReviewDecisionId]},idempotency:{}}),"utf8");const output=execFileSync(process.execPath,["scripts/mercury-identity-review-audit-remediate.mjs",`--decision-state=${cliDecision}`,`--evidence-state=${cliEvidence}`,`--decision-id=${cliDefective.identityReviewDecisionId}`,"--confirm=REMEDIATE-IDENTITY-REVIEW-AUDIT","--reviewed-by=operator:fixture","--reason=Fixture audit correction"],{cwd:process.cwd(),encoding:"utf8"});assert.match(output,/Remediation ID:\s+mer_idrem_000000001/);assert.match(output,/Original changed:\s+NO/);assert.match(output,/Promotion authorized:\s+NO/);assert.match(output,/Actual spend:\s+\$0\.000/);
}finally{await rm(root,{recursive:true,force:true});}
console.log("Identity review audit remediation tests passed.");
