import assert from "node:assert/strict";
import {mkdtemp,rm} from "node:fs/promises";
import {tmpdir} from "node:os";
import {join} from "node:path";
import {ImmutableProviderResultReprocessingService,IMMUTABLE_RESULT_REPROCESSING_CONFIRMATION_PREFIX,normalizeAmazonSellersResultRows,SqliteRepeatObservationRepository} from "../index.js";

let cases=0;const ok=value=>{assert.ok(value);cases++;},eq=(a,b)=>{assert.deepEqual(a,b);cases++;};
const resultId="mer_providerresult_fixture",preparedObservationId="mer_repeatprep_fixture",runId="mer_repeatrun_fixture",result={canonicalResultId:resultId,resultDigest:"d".repeat(64),providerTaskId:"task-fixture",paidActionIntentId:"intent-fixture",acquisitionReferenceId:preparedObservationId,atlasProductId:"ram_fixture",sourceId:"DATAFORSEO_AMAZON",operation:"AMAZON_SELLERS",sourceRightsProfileDigest:"r".repeat(64),operationResult:{id:"task-fixture",cost:0,result:[{asin:"B0ABC12345",datetime:"2026-09-16T01:00:00.000Z",items:[{asin:"B0ABC12345",seller_name:"Fixture",seller_url:"https://amazon.com/sp",price:{current:486.96,currency:"USD"},delivery_info:{delivery_price:{current:10.04,regular:null,max_value:null,currency:"USD",is_price_range:false,displayed_price:"$10.04"}}}]}]}};
class AuditRepository{constructor(){this.actions=new Map();this.runs=[structuredClone(originalRun)];}findRunsByPreparedObservationId(id){return this.runs.filter(run=>run.members.some(member=>member.preparedObservationId===id)).map(value=>structuredClone(value));}recordReprocessingAction(value){const prior=this.actions.get(value.canonicalResultId);if(prior){if(JSON.stringify(prior.action)!==JSON.stringify(value))throw new Error("IMMUTABLE_RESULT_REPROCESSING_ACTION_CONFLICT");return{status:"DUPLICATE",value:structuredClone(prior.action)}}this.actions.set(value.canonicalResultId,{action:structuredClone(value),events:[]});return{status:"RECORDED",value:structuredClone(value)}}appendReprocessingEvent(actionId,event){const row=[...this.actions.values()].find(value=>value.action.actionId===actionId);if(!row)throw new Error("ACTION_NOT_FOUND");const prior=row.events.find(value=>value.eventId===event.eventId);if(prior)return structuredClone(prior);const value={...structuredClone(event),sequence:row.events.length+1};row.events.push(value);return structuredClone(value)}getReprocessingActionByResult(id){const row=this.actions.get(id);return row?structuredClone({...row.action,events:row.events}):null}}
const originalRun={runId,state:"COMPLETED_WITH_EXCEPTIONS",members:[{memberKey:preparedObservationId,preparedObservationId,state:"EXCEPTION",exception:"DATAFORSEO_AMAZON_MONEY_INVALID",providerTaskId:"task-fixture",evidenceIds:[],historicalObservationIds:[]}]};
function fixture(overrides={}){const repository=overrides.repository??new AuditRepository(),evidence=new Set(overrides.existingEvidence??[]),history=new Set(overrides.existingHistory??[]),calls={process:0,assess:0,admit:0,provider:0,paid:0},currentResult=overrides.result===undefined?result:overrides.result,processEvidenceIds=overrides.processEvidenceIds??["dfev_fixture"],repeatService={async resolveResultContext(input){if(overrides.contextError)throw new Error(overrides.contextError);if(input.preparedObservationId!==preparedObservationId||input.canonicalResultId!==resultId)throw new Error("LINEAGE_CONFLICT");return{canonicalResult:currentResult}},async validateCurrent(){if(overrides.rightsError)throw new Error(overrides.rightsError);return{state:"CURRENT"}},async processRetain(){calls.process++;if(overrides.processError)throw new Error(overrides.processError);const rows=normalizeAmazonSellersResultRows(currentResult);eq(rows[0].sellerItem.deliveryPrice,10.04);for(const id of processEvidenceIds)evidence.add(id);return{evidenceIds:processEvidenceIds,duplicates:calls.process>1?processEvidenceIds.length:0}},async assessAdmitFact({evidenceId,action}){if(action==="ASSESS"){calls.assess++;if(overrides.historyIneligible||overrides.ineligibleIds?.includes(evidenceId))throw new Error("HISTORICAL_ADMISSION_NOT_ELIGIBLE:HISTORICAL_FACT_ITEM_PRICE_INVALID");return{historicalEligible:true}}calls.admit++;history.add(`hist_${evidenceId}`);return{status:history.has(`hist_${evidenceId}`)?"DUPLICATE":"ADMITTED",observationId:`hist_${evidenceId}`}}},processors=overrides.processors??{"DATAFORSEO_AMAZON:AMAZON_SELLERS":{sourceId:"DATAFORSEO_AMAZON",operation:"AMAZON_SELLERS",version:"DATAFORSEO-AMAZON-SELLERS-D1-1.0",eligibleExceptions:["DATAFORSEO_AMAZON_MONEY_INVALID"],process:input=>repeatService.processRetain(input)}};return{repository,evidence,history,calls,service:new ImmutableProviderResultReprocessingService({repeatService,resultRepository:{getCanonicalResultById:async id=>id===resultId?currentResult:null},repository,processors,now:()=>"2026-09-16T12:00:00.000Z"})}}
const input={canonicalResultId:resultId,operator:"operator:fixture",reason:"Certified reusable normalizer correction",confirmation:`${IMMUTABLE_RESULT_REPROCESSING_CONFIRMATION_PREFIX}${resultId}`};

const f=fixture(),before=structuredClone(f.repository.runs),assessment=await f.service.assess({canonicalResultId:resultId});eq(assessment.eligible,true);eq(assessment.originalException,"DATAFORSEO_AMAZON_MONEY_INVALID");eq(assessment.providerCalls,0);eq(assessment.paidTasks,0);const first=await f.service.reprocess(input);eq(first.status,"REPROCESSED");eq(first.evidenceIds,["dfev_fixture"]);eq(first.historicalObservationIds,["hist_dfev_fixture"]);eq(first.downstreamAuthority,false);eq(f.calls.provider,0);eq(f.calls.paid,0);eq(f.repository.runs,before);eq(f.repository.getReprocessingActionByResult(resultId).events.map(x=>x.type),["STARTED","SUCCEEDED"]);
const replay=await f.service.reprocess(input);eq(replay.status,"ALREADY_EFFECTIVE");eq(f.calls.process,1);eq(f.evidence.size,1);eq(f.history.size,1);
const restarted=new ImmutableProviderResultReprocessingService({repeatService:f.service.repeatService,resultRepository:f.service.resultRepository,repository:f.repository,processors:f.service.processors,now:()=>"2026-09-17T00:00:00.000Z"});eq((await restarted.reprocess(input)).status,"ALREADY_EFFECTIVE");
await assert.rejects(()=>f.service.reprocess({...input,confirmation:"WRONG"}),/CONFIRMATION_REQUIRED/);cases++;await assert.rejects(()=>f.service.reprocess({...input,operator:"other"}),/ACTION_CONFLICT|ALREADY/);cases++;
await assert.rejects(()=>fixture({result:null}).service.assess({canonicalResultId:resultId}),/RESULT_NOT_FOUND/);cases++;
await assert.rejects(()=>fixture({contextError:"RESULT_LINEAGE_CONFLICT"}).service.assess({canonicalResultId:resultId}),/LINEAGE_CONFLICT/);cases++;
const successfulRepo=new AuditRepository();successfulRepo.runs[0].members[0]={...successfulRepo.runs[0].members[0],state:"COMPLETED",exception:null};await assert.rejects(()=>fixture({repository:successfulRepo}).service.assess({canonicalResultId:resultId}),/OUTCOME_INELIGIBLE/);cases++;
await assert.rejects(()=>fixture({processors:{}}).service.assess({canonicalResultId:resultId}),/PROCESSOR_INELIGIBLE/);cases++;
await assert.rejects(()=>fixture({rightsError:"REPEAT_OBSERVATION_RIGHTS_CHANGED"}).service.assess({canonicalResultId:resultId}),/RIGHTS_CHANGED/);cases++;
const still=fixture({processError:"DATAFORSEO_AMAZON_MONEY_INVALID"});await assert.rejects(()=>still.service.reprocess(input),/MONEY_INVALID/);cases++;eq(still.repository.getReprocessingActionByResult(resultId).events.at(-1).type,"STILL_UNPROCESSABLE");eq(still.evidence.size,0);
const conflict=fixture({processError:"ACQUISITION_EVIDENCE_CONFLICT"});await assert.rejects(()=>conflict.service.reprocess(input),/EVIDENCE_CONFLICT/);cases++;eq(conflict.repository.getReprocessingActionByResult(resultId).events.at(-1).type,"CONFLICT");
const ineligible=fixture({historyIneligible:true});await assert.rejects(()=>ineligible.service.reprocess(input),/NO_ELIGIBLE_HISTORY/);cases++;eq(ineligible.history.size,0);eq(ineligible.repository.getReprocessingActionByResult(resultId).events.at(-1).type,"STILL_UNPROCESSABLE");
const partial=fixture({processEvidenceIds:["dfev_invalid","dfev_valid"],ineligibleIds:["dfev_invalid"]}),partialResult=await partial.service.reprocess(input);eq(partialResult.status,"REPROCESSED");eq(partialResult.skippedEvidence.map(x=>x.evidenceId),["dfev_invalid"]);eq(partialResult.historicalObservationIds,["hist_dfev_valid"]);
const ordered=fixture({processEvidenceIds:["dfev_valid_1","dfev_invalid","dfev_valid_2"],ineligibleIds:["dfev_invalid"],existingEvidence:["dfev_valid_1","dfev_invalid","dfev_valid_2"],existingHistory:["hist_dfev_valid_1"]}),orderedResult=await ordered.service.reprocess(input);eq(orderedResult.evidenceIds.length,3);eq(orderedResult.skippedEvidence.length,1);eq(orderedResult.historicalObservationIds.length,2);eq(ordered.evidence.size,3);eq(ordered.history.size,2);
const concurrent=fixture();const pair=await Promise.all([concurrent.service.reprocess(input),concurrent.service.reprocess(input)]);eq(pair.map(x=>x.status),["REPROCESSED","ALREADY_EFFECTIVE"]);eq(concurrent.calls.process,1);eq(concurrent.repository.getReprocessingActionByResult(resultId).events.length,2);
ok(!JSON.stringify(f.repository.getReprocessingActionByResult(resultId)).includes("publicationAuthority"));
const root=await mkdtemp(join(tmpdir(),"immutable-reprocess-"));try{const databasePath=join(root,"repeat.sqlite"),repo=new SqliteRepeatObservationRepository({databasePath}),action={schemaVersion:"1.0",actionId:"action-1",canonicalResultId:"result-1",bindingDigest:"b".repeat(64),operator:"operator",reason:"fixture"};eq(repo.recordReprocessingAction(action).status,"RECORDED");eq(repo.recordReprocessingAction(action).status,"DUPLICATE");repo.appendReprocessingEvent(action.actionId,{eventId:"event-1",type:"STARTED",at:"2026-09-16T00:00:00Z"});eq(repo.appendReprocessingEvent(action.actionId,{eventId:"event-1",type:"STARTED",at:"2026-09-16T00:00:00Z"}).sequence,1);repo.close();const reopened=new SqliteRepeatObservationRepository({databasePath}),durable=reopened.getReprocessingActionByResult("result-1");eq(durable.actionId,"action-1");eq(durable.events.length,1);await assert.rejects(async()=>reopened.recordReprocessingAction({...action,reason:"conflict"}),/ACTION_CONFLICT/);cases++;reopened.close();}finally{await rm(root,{recursive:true,force:true});}
console.log(`Immutable provider-result reprocessing tests passed: ${cases} cases.`);
