import assert from "node:assert/strict";
import {mkdir,mkdtemp,readFile,rm,writeFile} from "node:fs/promises";
import {tmpdir} from "node:os";
import {join,resolve} from "node:path";
import {CANONICAL_ADMISSION_CONFIRMATION,CanonicalAdmissionExecutor,CanonicalAdmissionPrepareService} from "../index.js";
import {createCanonicalOperatorRuntime} from "../../../scripts/mercury-canonical-admission-runtime.mjs";

const evidenceId="dfev_bb40abbb467a6497b88a3e2d",historyId="mer_hist_c4f418b1e82a5cf6",productId="ram_crucial_cp2k16g56c46u5",retailerId="RETAILER-0003",root=await mkdtemp(join(tmpdir(),"hr-b014a-")),copy=async(from,to)=>{await mkdir(resolve(to,".."),{recursive:true});await writeFile(to,await readFile(resolve(from)));};
async function fixture(name){const base=join(root,name),paths={evidence:join(base,"evidence.json"),history:join(base,"history.json"),decisions:join(base,"decisions.json"),observations:join(base,"observations.json"),authorizations:join(base,"authorizations.json"),retention:join(base,"retention.json"),proposal:join(base,"proposal.json"),refreshResult:join(base,"missing-refresh.json"),refreshPlan:join(base,"missing-plan.json")};await Promise.all([copy(".forge-review/acquisition/dataforseo-market-evidence.json",paths.evidence),copy(".forge-review/mercury/historical-observations.json",paths.history),copy(".forge-review/identity-review/identity-review-decisions.json",paths.decisions),copy(".forge-review/acquisition/sellers-df003-retention-latest.json",paths.retention),copy(".forge-review/acquisition/sellers-enrichment-proposal.json",paths.proposal)]);const args=new Map([["--evidence-state",paths.evidence],["--historical-state",paths.history],["--decision-state",paths.decisions],["--observation-state",paths.observations],["--authorization-state",paths.authorizations],["--retention-state",paths.retention],["--sellers-proposal",paths.proposal],["--refresh-result-state",paths.refreshResult],["--refresh-plan-state",paths.refreshPlan]]);return {paths,runtime:createCanonicalOperatorRuntime(args)};}
try{
  const {paths,runtime}=await fixture("valid"),assessment=await runtime.canonicalAdmissionService.assess({evidenceId});assert.equal(assessment.policyVersion,"DF004-E2P-1.0");assert.equal(assessment.historicalAdmitted,true);assert.equal(assessment.historicalEligible,true);assert.equal(assessment.canonicalEligible,true);assert.deepEqual(assessment.blockers,[]);assert.equal(assessment.identityProjection.product.state,"VERIFIED");assert.equal(assessment.identityProjection.product.governedAcquisitionProjectionId.startsWith("mer_initid_"),true);assert.equal(assessment.identityProjection.merchant.state,"REGISTERED");assert.equal(assessment.candidateBinding.historicalObservationId,historyId);assert.equal(assessment.candidateBinding.atlasProductId,productId);assert.equal(assessment.candidateBinding.retailerId,retailerId);assert.equal(assessment.candidateBinding.merchantDecisionId,"mer_idrev_000000003");assert.match(assessment.candidateBinding.rightsProfileHash,/^[a-f0-9]{64}$/);
  const prepare=new CanonicalAdmissionPrepareService(runtime),authorization=await prepare.prepare({evidenceId,requestedBy:"operator:fixture",reason:"Fixture governed initial-acquisition canonical admission."});assert.equal(authorization.candidateBinding.productProjectionId,assessment.candidateBinding.productProjectionId);await assert.rejects(()=>readFile(paths.observations,"utf8"),error=>error.code==="ENOENT");const executed=await new CanonicalAdmissionExecutor(runtime).execute({authorizationId:authorization.authorizationId,confirmation:CANONICAL_ADMISSION_CONFIRMATION,executedBy:"operator:fixture"});assert.equal(executed.status,"CANONICAL_ADMITTED");assert.equal(executed.reviewApproved,false);assert.equal(executed.publicationAuthority,false);assert.equal(executed.currentPriceAuthority,false);const state=JSON.parse(await readFile(paths.observations,"utf8")),observation=state.records[executed.observationId].payload;assert.equal(observation.atlasProductId,productId);assert.equal(observation.retailerId,retailerId);assert.equal(observation.marketplace,"memoryc.com");assert.equal(observation.offer.price,663.79);assert.equal(observation.offer.currency,"USD");assert.equal(observation.offer.availability,"IN_STOCK");assert.equal(observation.offer.condition,"UNKNOWN");assert.deepEqual(observation.offer.shipping,{costKnown:false,cost:null,currency:null,notes:null});assert.equal(observation.observationTime,"2026-09-01T18:02:36.223Z");assert.equal(observation.provenance.acquisition.requestId,"09011802-2304-0183-0000-b27c074679a9");assert.equal(observation.provenance.transformation.adapterId,"mer_adapter_dataforseo_google_shopping");assert.equal(observation.offer.affiliate.isAffiliateLink,false);assert.equal((await new CanonicalAdmissionExecutor(runtime).execute({authorizationId:authorization.authorizationId,confirmation:CANONICAL_ADMISSION_CONFIRMATION,executedBy:"operator:fixture"})).status,"ALREADY_CONSUMED");
  for(const [name,mutate,reason] of [["product",h=>{h.records[historyId].atlasProductId="ram_substituted";},"CANONICAL_HISTORICAL_IDENTITY_SUBSTITUTION"],["retailer",h=>{h.records[historyId].retailerId="RETAILER-9999";},"CANONICAL_HISTORICAL_IDENTITY_SUBSTITUTION"],["merchant",h=>{h.records[historyId].provenance.identityReview.merchantDecisionId="mer_idrev_substituted";},"CANONICAL_MERCHANT_DECISION_SUBSTITUTION"],["lineage",h=>{h.records[historyId].provenance.acquisition.productInfoTaskId="substituted";},"CANONICAL_INITIAL_ACQUISITION_LINEAGE_SUBSTITUTION"]]){const item=await fixture(name),history=JSON.parse(await readFile(item.paths.history,"utf8"));mutate(history);await writeFile(item.paths.history,JSON.stringify(history));const blocked=await item.runtime.canonicalAdmissionService.assess({evidenceId});assert.equal(blocked.canonicalEligible,false);assert.ok(blocked.blockers.includes(reason));}
  const digest=await fixture("digest"),proposal=JSON.parse(await readFile(digest.paths.proposal,"utf8"));proposal.proposal.validationDigest="f".repeat(64);await writeFile(digest.paths.proposal,JSON.stringify(proposal));await assert.rejects(()=>digest.runtime.canonicalAdmissionService.assess({evidenceId}),/PROJECTION|PROPOSAL|VALIDATION|BINDING/);
  console.log("B-014A governed initial-acquisition E2P/E2Q tests passed (42 cases).");
}finally{await rm(root,{recursive:true,force:true});}
