import assert from "node:assert/strict";
import {readFile} from "node:fs/promises";
import {createScheduledDryRunConfig,evaluateHistoricalRefreshCadence,HistoricalRefreshCadencePolicyRepository} from "../index.js";

const atlasProductId="ram_corsair_cmk32gx5m2b6000z30",policy=await new HistoricalRefreshCadencePolicyRepository().getPolicy();assert.equal(policy.schemaVersion,"1.0");assert.equal(policy.policyType,"HISTORICAL_REFRESH_CADENCE");assert.equal(policy.policyId,"mer_histrefresh_cadence_ram_corsair_cmk32gx5m2b6000z30_v1");assert.equal(policy.enabled,true);assert.equal(policy.minimumIntervalMs,86400000);assert.deepEqual(policy.atlasProductIds,[atlasProductId]);assert.equal(policy.retailerIds,null);assert.equal(policy.automaticExecution,false);assert.equal(policy.metadata.schedulerWakeFrequencyIndependent,true);assert.equal(policy.metadata.publicFreshnessPolicy,false);
const latest={observationId:"mer_hist_8c6f5725db93e83f",observationTime:"2026-08-24 00:07:42 +00:00",admittedAt:"2030-01-01T00:00:00Z",retailerId:"RETAILER-0002",basePrice:588.99},nextAction={name:"PREPARE_NEW_REFRESH",potentialPaidOperation:"SELLERS",maximumFutureSpendUsd:.001},cycle={atlasProductId,stage:"COMPLETE",nextAction,latestHistoricalObservation:latest},evaluate=(asOf,overrides={})=>evaluateHistoricalRefreshCadence({atlasProductId,cycleStatus:{...cycle,...overrides},policy,asOf});assert.equal(Date.parse(latest.observationTime),Date.parse("2026-08-24T00:07:42Z"));const early=evaluate("2026-08-24T02:00:00Z"),lastMillisecond=evaluate("2026-08-25T00:07:41.999Z"),threshold=evaluate("2026-08-25T00:07:42Z"),after=evaluate("2026-08-25T00:07:42.001Z");assert.equal(early.dueState,"NOT_DUE");assert.equal(early.elapsedSinceObservationMs,6738000);assert.equal(early.nextEligibleRefreshTime,"2026-08-25T00:07:42.000Z");assert.deepEqual(early.reasons,["REFRESH_INTERVAL_NOT_ELAPSED"]);assert.equal(lastMillisecond.dueState,"NOT_DUE");assert.equal(threshold.dueState,"DUE");assert.deepEqual(threshold.reasons,["REFRESH_INTERVAL_ELAPSED"]);assert.equal(after.dueState,"DUE");assert.equal(threshold.latestObservationTime,latest.observationTime);assert.notEqual(threshold.latestObservationTime,latest.admittedAt);
for(const trend of ["FLAT","UP","DOWN"]){for(const basePrice of [1,588.99,1000])assert.equal(evaluateHistoricalRefreshCadence({atlasProductId,cycleStatus:{...cycle,trend,latestHistoricalObservation:{...latest,basePrice}},policy,asOf:"2026-08-25T00:07:42Z"}).dueState,"DUE");}for(const stage of ["AWAITING_RESULT_RETRIEVAL","AWAITING_HISTORICAL_ADMISSION","REVIEW_REQUIRED","PAID_EXECUTION_FAILED","BLOCKED"]){assert.equal(evaluate("2026-08-26T00:07:42Z",{stage}).dueState,"BLOCKED");}assert.equal(evaluate("2026-08-25T00:07:42Z",{stage:"NO_SELLER_OBSERVATIONS"}).dueState,"DUE");assert.equal(evaluateHistoricalRefreshCadence({atlasProductId:"unrelated_product",cycleStatus:{...cycle,atlasProductId:"unrelated_product"},policy,asOf:"2026-08-25T00:07:42Z"}).dueState,"BLOCKED");assert.equal(threshold.paidActionExecuted,false);assert.equal(threshold.paidTaskCreated,false);assert.equal(threshold.actualSpendUsd,0);assert.equal(threshold.automaticExecution,false);assert.equal(threshold.unattendedLive,false);
const scheduled=await readFile(new URL("../../../scripts/mercury-scheduled-dry-run.mjs",import.meta.url),"utf8");assert.match(scheduled,/ACQUISITION_INTERVAL_MINUTES\|\|360/);assert.equal(createScheduledDryRunConfig({intervalMinutes:360}).paidTransportReachable,false);
console.log("Initial production historical refresh cadence tests passed.");
