import assert from "node:assert/strict";
import { mkdtemp, readFile, rm, writeFile } from "node:fs/promises";
import os from "node:os";
import path from "node:path";
import { canonicalizeBrand, assessDataForSeoProductEvidenceAgainstAtlas } from "../resolution/dataforseo/DataForSeoAtlasResolver.js";
import { FileProductInfoResultRepository, PRODUCT_INFO_BRAND_ALIAS_POLICY_VERSION, reassessProductInfoResult } from "../index.js";
const product=JSON.parse(await readFile(new URL("../../atlas/products/ram/ddr4/HR-RAM-DDR4-000015-kingston-valueram-kvr32n22d8-32.json",import.meta.url),"utf8")),brand=JSON.parse(await readFile(new URL("../../atlas/brands/kingston.json",import.meta.url),"utf8")),options={canonicalBrand:brand.displayName,aliases:brand.aliases};
assert.equal(canonicalizeBrand("Kingston",options),"Kingston");assert.equal(canonicalizeBrand(" Kingston Technology ",options),"Kingston");assert.equal(canonicalizeBrand("KINGSTON TECHNOLOGY",options),"Kingston");assert.equal(canonicalizeBrand("Corsair",options),"Corsair");assert.equal(canonicalizeBrand("Kingston Technologies",options),"Kingston Technologies");assert.equal(canonicalizeBrand("Kingston FURY",options),"Kingston FURY");assert.equal(canonicalizeBrand("Kingston FURY Beast",options),"Kingston FURY Beast");assert.equal(canonicalizeBrand("Kingston ValueRAM",options),"Kingston ValueRAM");assert.equal(product.identity.productFamily,"ValueRAM");assert.equal(product.identity.series,null);assert.equal(product.identity.manufacturerPartNumber,"KVR32N22D8/32");
const evidence={title:"Kingston Kingston 32gb 3200mhz Ddr4 Kvr32n22d8/32 Pc Ram",product_id:"5649044417192187385",data_docid:"9051792382139329246",gid:"7067396201028698670",specifications:[{specification_name:"Brand",specification_value:"Kingston Technology"},{specification_name:"Type",specification_value:"DDR4"},{specification_name:"Capacity",specification_value:"32 GB"},{specification_name:"Speed",specification_value:"3,200 MHz"}]},before=assessDataForSeoProductEvidenceAgainstAtlas(evidence,product),after=assessDataForSeoProductEvidenceAgainstAtlas(evidence,product,{brandAliases:brand.aliases});assert.deepEqual(before.contradictions,["BRAND_CONFLICT"]);assert.deepEqual(after.contradictions,[]);assert.equal(after.status,"COMPATIBLE_WITH_UNKNOWNS");
const prior={schemaVersion:"1.0",resultId:"prior",providerTaskId:"task",executionRunId:"run",authorizationId:"auth",proposalId:"proposal",selectionDecisionId:"selection",atlasProductId:product.identity.atlasProductId,providerIdentity:{productId:evidence.product_id,dataDocId:evidence.data_docid,gid:evidence.gid},retrievedEvidence:{title:evidence.title,productId:evidence.product_id,dataDocId:evidence.data_docid,gid:evidence.gid,brand:null,specifications:evidence.specifications},validation:{status:"REVIEW_REQUIRED",reasons:["BRAND_CONFLICT"]},sellersReadiness:"NOT_ESTABLISHED",materialDigest:"original-digest",status:"PRODUCT_INFO_REVIEW_REQUIRED"},snapshot=structuredClone(prior),reassessment=reassessProductInfoResult({priorResult:prior,atlasProduct:product,brandRecord:brand,assessedAt:"2026-09-04T02:00:00Z"});assert.deepEqual(prior,snapshot);assert.equal(reassessment.brandPolicyVersion,PRODUCT_INFO_BRAND_ALIAS_POLICY_VERSION);assert.deepEqual(reassessment.atlasValidation.contradictions,[]);assert.equal(reassessment.resultStatus,"PRODUCT_INFO_VALIDATED");assert.equal(reassessment.sellersReadiness,"READY_FOR_SELLERS");assert.equal(reassessment.downstreamAuthority.sellersExecution,false);
const root=await mkdtemp(path.join(os.tmpdir(),"hr-brand-alias-"));try{const state=path.join(root,"results.json");await writeFile(state,JSON.stringify({schemaVersion:"1.0",results:[prior]}));const repository=new FileProductInfoResultRepository({statePath:state});assert.equal((await repository.recordReassessment(reassessment)).status,"RECORDED");assert.equal((await repository.recordReassessment(reassessment)).status,"DUPLICATE");const stored=JSON.parse(await readFile(state,"utf8"));assert.deepEqual(stored.results[0],prior);assert.equal(stored.reassessments.length,1);}finally{await rm(root,{recursive:true,force:true});}
console.log("Kingston brand alias normalization tests passed.");
