import assert from "node:assert/strict";
import { mkdtemp, rm } from "node:fs/promises";
import os from "node:os";
import path from "node:path";
import { defaultSourceRightsRegistry, SourceRightsRegistry, sourceRightsProfileDigest } from "../rights/SourceRightsRegistry.js";
import { createRetailerDestination } from "../destinations/RetailerDestination.js";
import { manualCurrentPriceDigest, prepareManualCurrentPriceObservation } from "../current-display/ManualCurrentPricePreparation.js";
import { assessManualCurrentPriceHistoricalEligibility, createManualCurrentPriceHistoricalObservation, ManualCurrentPriceHistoryService } from "../current-display/ManualCurrentPriceHistory.js";
import { FileHistoricalObservationRepository } from "../historical-admission/persistence/FileHistoricalObservationRepository.js";

let cases=0;const eq=(a,b)=>{assert.deepEqual(a,b);cases++;};const ok=value=>{assert.equal(value,true);cases++;};
const at="2026-09-19T17:00:00.000Z";
const product={identity:{atlasProductId:"ram_fixture_manual_history",productType:"ram",brand:"Fixture",manufacturerPartNumber:"FIX-H",displayName:"Fixture History RAM"},governance:{lifecycleStatus:"ACTIVE",publicationStatus:"READY"}};
const retailer={id:"RETAILER-0001",name:"Amazon",slug:"amazon",websiteUrl:"https://amazon.com",status:"active"};
const destination=createRetailerDestination({atlasProductId:product.identity.atlasProductId,retailerId:retailer.id,marketplace:"amazon.com",destinationType:"PRODUCT_PAGE",destinationUrl:"https://amazon.com/dp/B000000001",retailerListingId:"B000000001",binding:{manufacturerPartNumber:"FIX-H",method:"OPERATOR_EXACT_PRODUCT_REVIEW",scope:"EXACT_STANDALONE_PRODUCT",evidenceReferences:["fixture"]},provenance:{sourceType:"OPERATOR_INSPECTED_PUBLIC_PAGE"},reviewedBy:"fixture",reviewedAt:at,status:"ACTIVE",createdAt:at,createdBy:"fixture"});
const rights=defaultSourceRightsRegistry.require("AMAZON_MANUAL_PUBLISHER_OBSERVATION");
const preparation=prepareManualCurrentPriceObservation({input:{atlasProductId:product.identity.atlasProductId,destinationId:destination.destinationId,itemPriceUsd:90,currency:"USD",availability:"AVAILABLE",observedAt:"2026-09-19T16:30:00.000Z",observedBy:"operator",evidenceReference:"operator:amazon:fixture"},product,retailer,destination,rightsProfile:rights,preparedAt:at});
const assessment=assessManualCurrentPriceHistoricalEligibility({preparation,product,retailer,destination,rightsProfile:rights});ok(assessment.eligible);eq(assessment.reasons,[]);
const record=createManualCurrentPriceHistoricalObservation({preparation,product,retailer,destination,rightsProfile:rights,admittedAt:at,admittedBy:"operator"});
eq(record.schemaVersion,"1.1");eq(record.market.basePrice,90);eq(record.market.totalPrice,null);eq(record.market.shipping,null);eq(record.market.tax,null);eq(record.market.condition,null);eq(record.market.sellerName,null);eq(record.comparability.standaloneEligible,true);eq(record.provenance.acquisition.type,"MANUAL_PUBLISHER_OBSERVATION");eq(record.governance.canonicalEligible,false);eq(record.governance.publicationEligible,false);
const temp=await mkdtemp(path.join(os.tmpdir(),"manual-history-"));try{const repository=new FileHistoricalObservationRepository({statePath:path.join(temp,"history.json")});const service=new ManualCurrentPriceHistoryService({historicalRepository:repository,rightsRegistry:defaultSourceRightsRegistry,now:()=>at});eq((await service.admit({preparation,product,retailer,destination,admittedBy:"operator"})).status,"ADMITTED");eq((await service.admit({preparation,product,retailer,destination,admittedBy:"operator"})).status,"DUPLICATE");eq((await repository.getAll()).length,1);}finally{await rm(temp,{recursive:true,force:true});}
const later=prepareManualCurrentPriceObservation({input:{...preparation.binding,itemPriceUsd:88,observedAt:"2026-09-19T16:45:00.000Z",destinationId:destination.destinationId,atlasProductId:product.identity.atlasProductId,currency:"USD",availability:"AVAILABLE",observedBy:"operator",evidenceReference:"operator:amazon:later"},product,retailer,destination,rightsProfile:rights,preparedAt:at});
assert.notEqual(later.preparationId,preparation.preparationId);cases++;
const blockedRights=structuredClone(rights);blockedRights.retention.historical="BLOCKED";eq(assessManualCurrentPriceHistoricalEligibility({preparation,product,retailer,destination,rightsProfile:blockedRights}).eligible,false);
const bundled=structuredClone(destination);bundled.binding.scope="BUNDLE";eq(assessManualCurrentPriceHistoricalEligibility({preparation,product,retailer,destination:bundled,rightsProfile:rights}).eligible,false);

// Rights-policy evolution preserves original lineage while current claim-specific authority governs admission.
const original=defaultSourceRightsRegistry.verifyLineage("AMAZON_MANUAL_PUBLISHER_OBSERVATION","4f28476c3868ee7b4da9508eab850461a6986de0e001226669001db18bd11522").profile;
const legacyBinding={...structuredClone(preparation.binding),sourceRightsProfileDigest:sourceRightsProfileDigest(original),observedAt:"2025-01-01T00:00:00.000Z"};
const legacyPreparation={...structuredClone(preparation),preparationId:"mer_manualpriceprep_111111111111111111111111",binding:legacyBinding,bindingDigest:manualCurrentPriceDigest(legacyBinding)};
const lineage=defaultSourceRightsRegistry.verifyLineage(legacyBinding.sourceId,legacyBinding.sourceRightsProfileDigest);
const evolved=assessManualCurrentPriceHistoricalEligibility({preparation:legacyPreparation,product,retailer,destination,rightsProfile:rights,originalRightsLineage:lineage});ok(evolved.eligible);eq(evolved.originalRightsLineageState,"HISTORICAL_PROFILE");eq(evolved.originalPreparationRightsDigest,legacyBinding.sourceRightsProfileDigest);eq(evolved.admissionRightsProfileDigest,sourceRightsProfileDigest(rights));
const evolvedRecord=createManualCurrentPriceHistoricalObservation({preparation:legacyPreparation,product,retailer,destination,rightsProfile:rights,originalRightsLineage:lineage,admittedAt:at,admittedBy:"operator"});eq(evolvedRecord.observationTime,legacyBinding.observedAt);eq(evolvedRecord.admittedAt,at);eq(evolvedRecord.provenance.acquisition.originalPreparationRightsDigest,legacyBinding.sourceRightsProfileDigest);eq(evolvedRecord.provenance.acquisition.admissionRightsProfileDigest,sourceRightsProfileDigest(rights));
const revoked=structuredClone(rights);revoked.retention.historical="BLOCKED";eq(assessManualCurrentPriceHistoricalEligibility({preparation:legacyPreparation,product,retailer,destination,rightsProfile:revoked,originalRightsLineage:lineage}).reasons.includes("CURRENT_HISTORY_RIGHT_NOT_ALLOWED"),true);
eq(assessManualCurrentPriceHistoricalEligibility({preparation:legacyPreparation,product,retailer,destination,rightsProfile:rights,originalRightsLineage:{verified:false,state:"UNVERIFIABLE"}}).reasons.includes("ORIGINAL_RIGHTS_LINEAGE_UNVERIFIABLE"),true);
const otherSource=structuredClone(rights);otherSource.sourceId="OTHER_SOURCE";eq(assessManualCurrentPriceHistoricalEligibility({preparation:legacyPreparation,product,retailer,destination,rightsProfile:otherSource,originalRightsLineage:lineage}).reasons.includes("SOURCE_IDENTITY_MISMATCH"),true);
const unrelated=structuredClone(rights);unrelated.presentation.attribution="CONDITIONAL";ok(assessManualCurrentPriceHistoricalEligibility({preparation:legacyPreparation,product,retailer,destination,rightsProfile:unrelated,originalRightsLineage:lineage}).eligible);
const unrelatedRecord=createManualCurrentPriceHistoricalObservation({preparation:legacyPreparation,product,retailer,destination,rightsProfile:unrelated,originalRightsLineage:lineage,admittedAt:at,admittedBy:"operator"});eq(unrelatedRecord.observationId,evolvedRecord.observationId);
const comparisonBlocked=structuredClone(rights);comparisonBlocked.live.comparison="BLOCKED";ok(assessManualCurrentPriceHistoricalEligibility({preparation:legacyPreparation,product,retailer,destination,rightsProfile:comparisonBlocked,originalRightsLineage:lineage}).eligible);
const inactiveDestination=structuredClone(destination);inactiveDestination.status="INACTIVE";ok(assessManualCurrentPriceHistoricalEligibility({preparation:legacyPreparation,product,retailer,destination:inactiveDestination,rightsProfile:rights,originalRightsLineage:lineage}).eligible);
const noHistoryRegistry=new SourceRightsRegistry({sourceProfiles:{[rights.sourceId]:revoked},historicalSourceProfiles:[original]});eq(noHistoryRegistry.verifyLineage(legacyBinding.sourceId,legacyBinding.sourceRightsProfileDigest).verified,true);
console.log(`Manual current-price history tests passed: ${cases} cases.`);
