import assert from "node:assert/strict";
import { mkdtemp, rm, writeFile } from "node:fs/promises";
import os from "node:os";
import path from "node:path";
import { createRetailerDestination } from "../destinations/RetailerDestination.js";
import { defaultSourceRightsRegistry } from "../rights/SourceRightsRegistry.js";
import { FileManualCurrentPricePreparationRepository, parseManualCurrentPriceWorkbook, prepareManualCurrentPriceObservation, readManualCurrentPriceWorkbookRow, selectManualCurrentPriceWorkbookObservation } from "../current-display/index.js";

let cases=0;const eq=(a,b)=>{assert.equal(a,b);cases++};const ok=value=>{assert.equal(value,true);cases++};
const xml=value=>String(value).replace(/&/g,"&amp;").replace(/</g,"&lt;").replace(/>/g,"&gt;");
const column=index=>{let value="";for(let number=index+1;number;number=Math.floor((number-1)/26))value=String.fromCharCode((number-1)%26+65)+value;return value};
const rowXml=(number,values)=>`<row r="${number}">${values.map((value,index)=>value==null?"":typeof value==="number"?`<c r="${column(index)}${number}"><v>${value}</v></c>`:`<c r="${column(index)}${number}" t="inlineStr"><is><t>${xml(value)}</t></is></c>`).join("")}</row>`;
const zip=entries=>{
  const locals=[],centrals=[];let offset=0;
  for(const [name,content] of Object.entries(entries)){const filename=Buffer.from(name),data=Buffer.from(content),local=Buffer.alloc(30);local.writeUInt32LE(0x04034b50,0);local.writeUInt16LE(20,4);local.writeUInt32LE(data.length,18);local.writeUInt32LE(data.length,22);local.writeUInt16LE(filename.length,26);locals.push(local,filename,data);const central=Buffer.alloc(46);central.writeUInt32LE(0x02014b50,0);central.writeUInt16LE(20,4);central.writeUInt16LE(20,6);central.writeUInt32LE(data.length,20);central.writeUInt32LE(data.length,24);central.writeUInt16LE(filename.length,28);central.writeUInt32LE(offset,42);centrals.push(central,filename);offset+=local.length+filename.length+data.length}
  const directory=Buffer.concat(centrals),eocd=Buffer.alloc(22);eocd.writeUInt32LE(0x06054b50,0);eocd.writeUInt16LE(Object.keys(entries).length,8);eocd.writeUInt16LE(Object.keys(entries).length,10);eocd.writeUInt32LE(directory.length,12);eocd.writeUInt32LE(offset,16);return Buffer.concat([...locals,directory,eocd]);
};
const headers=["Atlas Product ID","Brand","Product Name","MPN","DDR","Form Factor","Capacity GB","Module Count","Capacity Per Module GB","Newegg URL","Newegg Listing ID","Newegg Destination ID","Newegg Destination Status","Newegg Legacy Research URL","Newegg Current Item Price","Newegg Currency","Newegg Availability","Newegg Observed Date","Newegg Observed Time","Newegg Timezone","Newegg Observed At","Newegg Shipping","Newegg Condition","Newegg Seller","Newegg Evidence Notes","Newegg Reviewed By","Newegg Ready for Import","Amazon URL","Amazon ASIN / Listing ID","Amazon Destination ID","Amazon Destination Status","Amazon Legacy Research URL","Amazon Current Item Price","Amazon Currency","Amazon Availability","Amazon Observed Date","Amazon Observed Time","Amazon Timezone","Amazon Observed At","Amazon Shipping","Amazon Condition","Amazon Seller","Amazon Evidence Notes","Amazon Reviewed By","Amazon Ready for Import","Amazon Production Authority","Rakuten Newegg Affiliate Link","Rakuten Link Status","Rakuten Link Checked Date","Rakuten Link Checked Time","Rakuten Link Timezone","Rakuten Link Checked At","Rakuten Link Notes","Record Reviewed By"];
const product={identity:{atlasProductId:"ram_fixture_workbook",productType:"ram",brand:"Fixture",manufacturerPartNumber:"FIX-WB",displayName:"Fixture Workbook RAM"},governance:{lifecycleStatus:"ACTIVE",publicationStatus:"READY"},extension:{data:{classification:{memoryType:"DDR5",formFactor:"DIMM"},capacity:{capacityGb:32,moduleCount:2,capacityPerModuleGb:16}}}};
const retailers={AMAZON:{id:"RETAILER-0001",name:"Amazon",slug:"amazon",websiteUrl:"https://amazon.com",status:"active"},NEWEGG:{id:"RETAILER-0004",name:"Newegg",slug:"newegg",websiteUrl:"https://newegg.com",status:"active"}};
const destination=(retailer,marketplace,url,listing)=>createRetailerDestination({atlasProductId:product.identity.atlasProductId,retailerId:retailer.id,marketplace,destinationType:"PRODUCT_PAGE",destinationUrl:url,retailerListingId:listing,binding:{manufacturerPartNumber:"FIX-WB",method:"OPERATOR_EXACT_PRODUCT_REVIEW",scope:"EXACT_STANDALONE_PRODUCT",evidenceReferences:["fixture"]},provenance:{sourceType:"OPERATOR_INSPECTED_PUBLIC_PAGE"},reviewedBy:"fixture",reviewedAt:"2026-09-19T10:00:00Z",status:"ACTIVE",createdAt:"2026-09-19T10:00:00Z",createdBy:"fixture"});
const destinations={AMAZON:destination(retailers.AMAZON,"amazon.com","https://amazon.com/dp/B000000001","B000000001"),NEWEGG:destination(retailers.NEWEGG,"newegg.com","https://newegg.com/p/N82E00000001","N82E00000001")};
const values=[product.identity.atlasProductId,"Fixture",product.identity.displayName,"FIX-WB","DDR5","DIMM",32,2,16,destinations.NEWEGG.destinationUrl,"N82E00000001",destinations.NEWEGG.destinationId,"CANONICAL_REVIEWED_DESTINATION",null,99,"USD","AVAILABLE",46284,"11:53am","America/Jamaica","11:53am",0,"NEW","NEWEGG","fixture-newegg",null,"YES",destinations.AMAZON.destinationUrl,"B000000001",destinations.AMAZON.destinationId,"CANONICAL_REVIEWED_DESTINATION",null,109,"USD","AVAILABLE","2026-09-19","11:56 AM","America/Jamaica","11:56am","UNKNOWN","NEW","AMAZON","fixture-amazon",null,"YES","NONE","https://click.example.invalid/newegg","READY","19/9/2026","12:03PM","America/Jamaica","12:03PM","fixture-route","OPERATOR_A"];
const worksheet=`<?xml version="1.0" encoding="UTF-8"?><worksheet xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main"><sheetData>${rowXml(4,headers)}${rowXml(5,values)}</sheetData></worksheet>`;
const archive=zip({"xl/workbook.xml":`<workbook xmlns:r="http://schemas.openxmlformats.org/officeDocument/2006/relationships"><sheets><sheet name="Price Research" sheetId="1" r:id="rId1"/></sheets></workbook>`,"xl/_rels/workbook.xml.rels":`<Relationships><Relationship Id="rId1" Target="worksheets/sheet1.xml"/></Relationships>`,"xl/worksheets/sheet1.xml":worksheet});
const [parsed]=parseManualCurrentPriceWorkbook(archive);eq(parsed.atlasProductId,product.identity.atlasProductId);eq(parsed.recordReviewedBy,"OPERATOR_A");eq(parsed.amazonObservation.observedTime,"11:56 AM");eq(parsed.neweggObservation.observedDate,46284);
const amazonSelection=selectManualCurrentPriceWorkbookObservation({row:parsed,retailer:"AMAZON"}),neweggSelection=selectManualCurrentPriceWorkbookObservation({row:parsed,retailer:"NEWEGG"});eq(amazonSelection.preparationInput.observedAt,"2026-09-19T11:56:00-05:00");eq(neweggSelection.preparationInput.observedAt,"2026-09-19T11:53:00-05:00");eq(amazonSelection.preparationInput.observedBy,"OPERATOR_A");eq(neweggSelection.preparationInput.observedBy,"OPERATOR_A");assert.notEqual(amazonSelection.preparationInput.destinationId,neweggSelection.preparationInput.destinationId);cases++;
const preparedAt="2026-09-19T17:00:00.000Z";
const prepare=(retailer,selection)=>prepareManualCurrentPriceObservation({input:selection.preparationInput,product,retailer:retailers[retailer],destination:destinations[retailer],rightsProfile:defaultSourceRightsRegistry.require(`${retailer}_MANUAL_PUBLISHER_OBSERVATION`),preparedAt});
const amazon=prepare("AMAZON",amazonSelection),newegg=prepare("NEWEGG",neweggSelection);eq(amazon.binding.retailer,"AMAZON");eq(newegg.binding.retailer,"NEWEGG");eq(amazon.authorizationState,"NOT_AUTHORIZED");eq(newegg.authorizationState,"NOT_AUTHORIZED");eq(amazon.publicationAuthority,false);eq(newegg.publicationAuthority,false);assert.notEqual(amazon.preparationId,newegg.preparationId);cases++;
const temp=await mkdtemp(path.join(os.tmpdir(),"manual-workbook-compose-"));try{const workbookPath=path.join(temp,"fixture.xlsx");await writeFile(workbookPath,archive);const loaded=await readManualCurrentPriceWorkbookRow({workbookPath,atlasProductId:product.identity.atlasProductId});eq(loaded.recordReviewedBy,"OPERATOR_A");const repository=new FileManualCurrentPricePreparationRepository({filePath:path.join(temp,"preparations.json")});eq((await repository.record(amazon)).status,"CREATED");eq((await repository.record(amazon)).status,"EXISTING");eq((await repository.record(newegg)).status,"CREATED");eq((await repository.getAll()).length,2);eq((await repository.getById(amazon.preparationId)).bindingDigest,amazon.bindingDigest)}finally{await rm(temp,{recursive:true,force:true})}
const missing=structuredClone(parsed);missing.recordReviewedBy=null;assert.throws(()=>selectManualCurrentPriceWorkbookObservation({row:missing,retailer:"AMAZON"}),/OPERATOR_PROVENANCE_REQUIRED/);cases++;
const override=structuredClone(parsed);override.neweggObservation.reviewedBy="OPERATOR_B";eq(selectManualCurrentPriceWorkbookObservation({row:override,retailer:"NEWEGG"}).preparationInput.observedBy,"OPERATOR_B");eq(selectManualCurrentPriceWorkbookObservation({row:override,retailer:"AMAZON"}).preparationInput.observedBy,"OPERATOR_A");ok(parsed.rakutenRouting.checkedAt!==parsed.neweggObservation.observedAt);
console.log(`Manual current-price workbook composition tests passed: ${cases} cases.`);
