import assert from "node:assert/strict";
import {mkdtemp,rm,writeFile} from "node:fs/promises";
import {join} from "node:path";
import {tmpdir} from "node:os";
import {performance} from "node:perf_hooks";
import {FileHistoricalBootstrapProviderResultRepository,createHistoricalBootstrapProviderResult} from "../portfolio/FileHistoricalBootstrapProviderResultRepository.js";
import {NeutralGoogleProductsFinalizationService,validateNeutralGoogleProductsFinalization} from "../bounded/NeutralGoogleProductsFinalization.js";
import {GovernedProviderIdentityResolver} from "../acquisition/portfolio/ProductionAcquisitionPortfolio.js";
import {ProductsIdentityDiscoveryReadinessOwner} from "../bounded/ProductsIdentityDiscoveryReadinessOwner.js";
import {neutralBoundedDigest} from "../bounded/NeutralBoundedPaidActionCoordinator.js";

const at="2026-09-14T12:00:00.000Z",product={identity:{atlasProductId:"ram_fixture",manufacturerPartNumber:"MPN-1"}},rights={sourceId:"DATAFORSEO_GOOGLE_SHOPPING",acquisition:{api:"ALLOWED"},retention:{historical:"ALLOWED",durableAuditMetadata:"ALLOWED"}},rightsDigest=neutralBoundedDigest(rights);
const plan={planId:"mer_productsplan_fixture",bindingDigest:"a".repeat(64)},authorization={authorizationId:"mer_productsauth_fixture",bindingDigest:"b".repeat(64),planId:plan.planId,planBindingDigest:plan.bindingDigest},member={memberKey:"member-1",domainMemberId:"domain-1",atlasProductId:product.identity.atlasProductId,source:"DATAFORSEO_GOOGLE_SHOPPING",operation:"PRODUCTS",rightsDigest,authorizationId:"liveauth_fixture",providerTaskId:"task-1"},run={runId:"mer_productsrun_fixture",planId:plan.planId,authorizationId:authorization.authorizationId,members:[member]},child={childAuthorizationId:member.authorizationId,childAuthorizationDigest:"c".repeat(64),authorizationArtifactId:"mer_prepare_fixture",authorizationArtifactDigest:"d".repeat(64)},artifact={prepareArtifactId:child.authorizationArtifactId,bindingDigest:child.authorizationArtifactDigest,authorizationRequestId:child.childAuthorizationId},bounded={getPlan:id=>id===plan.planId?plan:null,getRun:id=>id===run.runId?run:null,getAuthorization:id=>id===authorization.authorizationId?authorization:null,getChildAuthority:()=>child},progression={status:"STRONG_UNIQUE",routing:{providerAnchor:{productId:"product-1",dataDocId:"doc-1",gid:"gid-1"}},prepared:{resolution:{recommendationStatus:"STRONG"}}};
let cases=0;const root=await mkdtemp(join(tmpdir(),"neutral-google-finalization-"));try{const repository=new FileHistoricalBootstrapProviderResultRepository({statePath:join(root,"results.json")}),canonical=createHistoricalBootstrapProviderResult({operation:"PRODUCTS",sourceId:"DATAFORSEO_GOOGLE_SHOPPING",providerTaskId:member.providerTaskId,paidActionIntentId:"intent-1",acquisitionReferenceId:plan.planId,atlasProductId:member.atlasProductId,sourceRightsProfileDigest:rightsDigest,operationResult:{result:[{items:[]}]},retrievedAt:at});await repository.record(canonical);const service=new NeutralGoogleProductsFinalizationService({boundedRepository:bounded,childArtifactRepository:{getById:async()=>artifact},taskLedger:{getAll:async()=>[{taskId:member.providerTaskId,kind:"PRODUCTS",sourceId:member.source,atlasProductId:member.atlasProductId}]},resultRepository:repository,productRepository:{getById:async()=>product},progressionOwner:{resolve:async()=>progression},rightsRegistry:{require:()=>rights},now:()=>at});
const first=await service.finalize({planId:plan.planId,runId:run.runId,memberKey:member.memberKey});assert.equal(first.status,"FINALIZED");assert.equal(first.finalization.state,"IDENTITY_RESOLVED");assert.deepEqual(first.finalization.providerIdentity,{productId:"product-1",dataDocId:"doc-1",gid:"gid-1"});assert.equal(validateNeutralGoogleProductsFinalization(first.finalization),true);assert.ok(Object.values(first.finalization.downstreamAuthority).every(v=>v===false));cases+=5;
const replay=await service.finalize({planId:plan.planId,runId:run.runId,memberKey:member.memberKey});assert.equal(replay.status,"DUPLICATE");assert.equal(replay.finalization.finalizationId,first.finalization.finalizationId);cases+=2;
const resolver=new GovernedProviderIdentityResolver({historicalRepository:{getAll:async()=>[]},evidenceRepository:{getById:async()=>null},neutralFinalizationRepository:repository}),resolved=await resolver.resolve(member.atlasProductId);assert.equal(resolved.status,"REUSABLE");assert.equal(resolved.productId,"product-1");cases+=2;
const readiness=new ProductsIdentityDiscoveryReadinessOwner({productRepository:{getById:async()=>product},rightsRegistry:{require:()=>rights},googleIdentityResolver:resolver,amazonArtifactRepository:{getAll:async()=>[]},amazonActionRepository:{getEffectiveOutcomeForArtifact:async()=>null}}),ready=await readiness.assess({atlasProductId:member.atlasProductId,sourceId:member.source,asOf:at});assert.equal(ready.state,"ALREADY_RESOLVED");cases++;
assert.equal((await new NeutralGoogleProductsFinalizationService({boundedRepository:bounded,childArtifactRepository:{getById:async()=>artifact},taskLedger:{getAll:async()=>[{taskId:member.providerTaskId,kind:"PRODUCTS",sourceId:member.source}]},resultRepository:{findByTask:async()=>null,recordNeutralProductsFinalization:value=>repository.recordNeutralProductsFinalization(value),getNeutralProductsFinalization:(...args)=>repository.getNeutralProductsFinalization(...args)},productRepository:{getById:async()=>product},progressionOwner:{resolve:async()=>progression},rightsRegistry:{require:()=>rights}}).finalize({planId:plan.planId,runId:run.runId,memberKey:member.memberKey})).status,"PENDING");cases++;
await assert.rejects(()=>new NeutralGoogleProductsFinalizationService({boundedRepository:bounded,childArtifactRepository:{getById:async()=>({...artifact,bindingDigest:"x"})},taskLedger:{getAll:async()=>[]},resultRepository:repository,productRepository:{getById:async()=>product},progressionOwner:{resolve:async()=>progression},rightsRegistry:{require:()=>rights}}).finalize({planId:plan.planId,runId:run.runId,memberKey:member.memberKey}),/CHILD_ARTIFACT/);cases++;
for(const state of["ESCALATION_REQUIRED","BLOCKED_IDENTITY"]){const otherRoot=join(root,state+".json"),repo=new FileHistoricalBootstrapProviderResultRepository({statePath:otherRoot});await repo.record(canonical);const s=new NeutralGoogleProductsFinalizationService({boundedRepository:bounded,childArtifactRepository:{getById:async()=>artifact},taskLedger:{getAll:async()=>[{taskId:member.providerTaskId,kind:"PRODUCTS",sourceId:member.source}]},resultRepository:repo,productRepository:{getById:async()=>product},progressionOwner:{resolve:async()=>({...progression,status:state,prepared:{resolution:{recommendationStatus:state==="BLOCKED_IDENTITY"?"AMBIGUOUS":"REVIEW"}}})},rightsRegistry:{require:()=>rights},now:()=>at}),v=await s.finalize({planId:plan.planId,runId:run.runId,memberKey:member.memberKey});assert.equal(v.finalization.state,state==="ESCALATION_REQUIRED"?"REVIEW_REQUIRED":"AMBIGUOUS");cases++;}
const scalePath=join(root,"scale.json");for(const size of[10,100,1000,10000]){const records={valid:first.finalization};for(let i=0;i<size;i++)records[`unrelated-${i}`]={atlasProductId:`ram_${i}`,sourceId:"OTHER"};await writeFile(scalePath,JSON.stringify({version:"1.0",results:{},references:{},byTaskIntent:{},progressions:{},proposals:{},neutralProductsFinalizations:records}));const repo=new FileHistoricalBootstrapProviderResultRepository({statePath:scalePath}),start=performance.now(),rows=await repo.getNeutralProductsFinalizationsForProduct(member.atlasProductId);assert.equal(rows.length,1);console.log(`Neutral Google finalization lookup ${size}: ${(performance.now()-start).toFixed(2)} ms`);cases++;}
}finally{await rm(root,{recursive:true,force:true})}console.log(`Neutral Google Products finalization tests passed (${cases} cases).`);
