import assert from "node:assert/strict";
import {BOUNDED_FAILURE_CLASSES,NeutralBoundedPaidActionCoordinator,createBoundedChildAuthorityBinding} from "../index.js";

const clone=value=>structuredClone(value),same=(left,right)=>JSON.stringify(left)===JSON.stringify(right);
class MemoryRepository{
  constructor(){this.plans=new Map();this.authorizations=new Map();this.runs=new Map();}
  record(map,key,value,status,conflict){const prior=map.get(key);if(prior){if(!same(prior,value))throw new Error(conflict);return{status:"DUPLICATE",value:clone(prior)};}map.set(key,clone(value));return{status,value:clone(value)};}
  recordPlan(value){return this.record(this.plans,value.planId,value,"PREPARED","PLAN_CONFLICT");}getPlan(id){return clone(this.plans.get(id)??null);}
  recordAuthorization(value){const active=[...this.authorizations.values()].find(row=>row.planId===value.planId&&Date.parse(value.authorizedAt)<Date.parse(row.expiresAt));const prior=this.authorizations.get(value.authorizationId);if(!prior&&active)throw new Error("AUTHORIZATION_ACTIVE");return this.record(this.authorizations,value.authorizationId,value,"AUTHORIZED","AUTHORIZATION_CONFLICT");}getAuthorization(id){return clone(this.authorizations.get(id)??null);}findAuthorizationsByPlan(id){return[...this.authorizations.values()].filter(value=>value.planId===id).map(clone);}
  startRun(value){const prior=[...this.runs.values()].find(row=>row.planId===value.planId);if(prior){if(prior.authorizationId!==value.authorizationId)throw new Error("RUN_START_CONFLICT");return{status:"DUPLICATE",value:clone(prior)};}this.runs.set(value.runId,clone(value));return{status:"STARTED",value:clone(value)};}getRun(id){return clone(this.runs.get(id)??null);}findRunByPlan(id){return clone([...this.runs.values()].find(value=>value.planId===id)??null);}updateMember(runId,member){const run=this.runs.get(runId),index=run.members.findIndex(value=>value.memberKey===member.memberKey);run.members[index]=clone(member);}updateRun(value){this.runs.set(value.runId,clone(value));return this.getRun(value.runId);}
}

let cases=0;const eq=(actual,expected)=>{assert.deepEqual(actual,expected);cases++;},at="2026-09-14T12:00:00.000Z";
const createFixture=({waiting=false,systemicAt=null,localAt=null}={})=>{const repository=new MemoryRepository(),calls=[],domainAdapter={
  async prepareMember({request}){if(request.blocked)throw new Error("DOMAIN_BLOCKED");return{memberKey:request.key,domainMemberId:`domain:${request.key}`,source:request.source??"FIXTURE_SOURCE",operation:request.operation??"FIXTURE_OPERATION",taskCeilingUsd:request.cost??.001};},
  async revalidateMember({member}){calls.push(["revalidate",member.memberKey]);},
  async advanceMember({member,authorization,createChildBinding}){calls.push(["advance",member.memberKey]);if(member.memberKey===systemicAt)throw new Error("DOMAIN_SYSTEMIC_FAILURE");if(member.memberKey===localAt)throw new Error("DOMAIN_LOCAL_FAILURE");if(waiting&&!member.waited)return{state:"WAITING_FOR_PROVIDER",waited:true};const childId=`child:${member.memberKey}`,childDigest="b".repeat(64),childAuthorityBinding=createChildBinding({parentAuthorization:authorization,member,childAuthorizationId:childId,childAuthorizationDigest:childDigest,expiresAt:authorization.expiresAt});return{state:"COMPLETED",childAuthorityBinding,paidTaskCreated:true,actualSpendUsd:member.taskCeilingUsd};},
  classifyFailure(error){return{classification:String(error.message).includes("SYSTEMIC")?BOUNDED_FAILURE_CLASSES.SYSTEMIC:BOUNDED_FAILURE_CLASSES.MEMBER_LOCAL,state:"DOMAIN_BLOCKED",reason:String(error.message)};},
  summarize(run){return{runId:run.runId,state:run.state,completed:run.members.filter(value=>value.state==="COMPLETED").length,pending:run.members.filter(value=>value.state==="WAITING_FOR_PROVIDER").length,failed:run.members.filter(value=>value.state==="EXCEPTION").length,members:run.members};}
},coordinator=new NeutralBoundedPaidActionCoordinator({repository,domainAdapter,now:()=>at,spendResolver:async()=>.002,dailySpendCeilingUsd:.025,policyVersion:"FIXTURE-1.0"});return{repository,calls,coordinator};};

const fixture=createFixture(),cohort=[{key:"opaque:a",cost:.001},{key:"opaque:b",cost:.002},{key:"opaque:blocked",blocked:true}],plan=await fixture.coordinator.prepare({cycle:at,cohort});eq(plan.value.ready.length,2);eq(plan.value.blocked.length,1);eq(plan.value.maximumSpendUsd,.003);eq(plan.value.ready.map(value=>value.memberKey),["opaque:a","opaque:b"]);eq((await fixture.coordinator.prepare({cycle:at,cohort})).status,"DUPLICATE");
const authorization=await fixture.coordinator.authorize({planId:plan.value.planId,operator:"operator",reason:"fixture",expiresAt:"2026-09-14T13:00:00.000Z"});eq(authorization.value.memberSetDigest,plan.value.cohortDigest);eq(authorization.value.memberCeilings.length,2);eq(Object.hasOwn(authorization.value,"historicalFactAdmissionAuthorized"),false);eq((await fixture.coordinator.authorize({planId:plan.value.planId,operator:"operator",reason:"fixture",expiresAt:"2026-09-14T13:00:00.000Z"})).status,"DUPLICATE");
await assert.rejects(()=>fixture.coordinator.authorize({planId:plan.value.planId,operator:"competitor",reason:"changed",expiresAt:"2026-09-14T13:00:00.000Z"}),/AUTHORIZATION_ACTIVE/);cases++;
const completed=await fixture.coordinator.start({authorizationId:authorization.value.authorizationId,startedBy:"operator"});eq(completed.state,"COMPLETED");eq(completed.completed,2);eq(completed.members.every(value=>value.childAuthorityBinding.parentAuthorizationDigest===authorization.value.bindingDigest),true);eq((await fixture.coordinator.start({authorizationId:authorization.value.authorizationId,startedBy:"operator"})).state,"COMPLETED");
const binding=completed.members[0].childAuthorityBinding;eq(createBoundedChildAuthorityBinding({parentAuthorization:authorization.value,member:plan.value.ready[0],childAuthorizationId:binding.childAuthorizationId,childAuthorizationDigest:binding.childAuthorizationDigest,expiresAt:binding.expiresAt}).bindingDigest,binding.bindingDigest);eq(createBoundedChildAuthorityBinding({parentAuthorization:authorization.value,member:plan.value.ready[0],childAuthorizationId:binding.childAuthorizationId,childAuthorizationDigest:"c".repeat(64),expiresAt:binding.expiresAt}).bindingDigest===binding.bindingDigest,false);assert.throws(()=>createBoundedChildAuthorityBinding({parentAuthorization:authorization.value,member:plan.value.ready[0],childAuthorizationId:binding.childAuthorizationId,childAuthorizationDigest:"c".repeat(64),expiresAt:"2026-09-14T14:00:00.000Z"}),/AUTHORITY_INVALID/);cases++;

const concurrency=createFixture(),concurrencyPlan=await concurrency.coordinator.prepare({cycle:at,cohort:[{key:"opaque:race"}]}),concurrencyAuthorization=await concurrency.coordinator.authorize({planId:concurrencyPlan.value.planId,operator:"operator",reason:"race",expiresAt:"2026-09-14T13:00:00.000Z"}),concurrent=await Promise.all([concurrency.coordinator.start({authorizationId:concurrencyAuthorization.value.authorizationId,startedBy:"one"}),concurrency.coordinator.start({authorizationId:concurrencyAuthorization.value.authorizationId,startedBy:"two"})]);eq(new Set(concurrent.map(value=>value.runId)).size,1);eq(concurrency.calls.filter(value=>value[0]==="advance").length,1);

const pendingFixture=createFixture({waiting:true}),pendingPlan=await pendingFixture.coordinator.prepare({cycle:at,cohort:[{key:"opaque:wait"}]}),pendingAuthorization=await pendingFixture.coordinator.authorize({planId:pendingPlan.value.planId,operator:"operator",reason:"wait",expiresAt:"2026-09-14T13:00:00.000Z"}),pending=await pendingFixture.coordinator.start({authorizationId:pendingAuthorization.value.authorizationId,startedBy:"operator"});eq(pending.state,"WAITING_FOR_PROVIDER");eq((await pendingFixture.coordinator.resume({runId:pending.runId,resumedBy:"operator"})).state,"COMPLETED");
const localFixture=createFixture({localAt:"opaque:bad"}),localPlan=await localFixture.coordinator.prepare({cycle:at,cohort:[{key:"opaque:bad"},{key:"opaque:good"}]}),localAuthorization=await localFixture.coordinator.authorize({planId:localPlan.value.planId,operator:"operator",reason:"local",expiresAt:"2026-09-14T13:00:00.000Z"});eq((await localFixture.coordinator.start({authorizationId:localAuthorization.value.authorizationId,startedBy:"operator"})).state,"COMPLETED_WITH_EXCEPTIONS");
const systemicFixture=createFixture({systemicAt:"opaque:00-system"}),systemicPlan=await systemicFixture.coordinator.prepare({cycle:at,cohort:[{key:"opaque:00-system"},{key:"opaque:01-later"}]}),systemicAuthorization=await systemicFixture.coordinator.authorize({planId:systemicPlan.value.planId,operator:"operator",reason:"system",expiresAt:"2026-09-14T13:00:00.000Z"});eq((await systemicFixture.coordinator.start({authorizationId:systemicAuthorization.value.authorizationId,startedBy:"operator"})).state,"FAILED");eq(systemicFixture.calls.some(value=>value[1]==="opaque:01-later"&&value[0]==="advance"),false);

for(const size of[10,100,1000,10000]){const scale=createFixture(),rows=Array.from({length:size},(_,index)=>({key:`opaque:${String(index).padStart(5,"0")}`,cost:0})),prepared=await scale.coordinator.prepare({cycle:at,cohort:rows});eq(prepared.value.ready.length,size);eq(prepared.value.maximumPaidTasks,size);eq(prepared.value.maximumSpendUsd,0);}
console.log(`Neutral bounded paid-action coordinator tests passed: ${cases} cases.`);
