import assert from "node:assert/strict";
import {mkdtemp,rm} from "node:fs/promises";
import {tmpdir} from "node:os";
import {join} from "node:path";
import {createAcquisitionBudgetPolicy,createAcquisitionPlan,createManualLiveAuthorizationRequest,createNeutralDerivedProductsAuthorizationRequest,createNeutralParentAuthorityInput,validateNeutralParentAuthorityInput,SqliteNeutralBoundedRepository,createAmazonAcceptanceActionAuthorization,prepareAmazonHistoricalAcceptance,selectAmazonHistoricalAcceptanceProduct,defaultSourceRightsRegistry} from "../index.js";

let cases=0;const eq=(a,b)=>{assert.deepEqual(a,b);cases++;},at="2026-09-14T12:00:00.000Z",expires="2026-09-14T13:00:00.000Z";
const member={memberKey:"member:1",domainMemberId:"domain:1",source:"DATAFORSEO_GOOGLE_SHOPPING",operation:"PRODUCTS",taskCeilingUsd:.001},plan={planId:"bounded-plan",bindingDigest:"b".repeat(64),ready:[member]},parent={authorizationId:"bounded-auth",bindingDigest:"a".repeat(64),planId:plan.planId,planBindingDigest:plan.bindingDigest,automaticPaidRetries:0,expiresAt:expires},authority=createNeutralParentAuthorityInput({parentAuthorization:parent,plan,member});
const validate=value=>validateNeutralParentAuthorityInput({authority:value,parentAuthorization:parent,plan,member,expectedSourceId:member.source,expectedOperation:"PRODUCTS",maximumTaskCostUsd:.001,asOf:at});
eq(validate(authority),true);for(const [change,pattern] of[[{parentAuthorizationDigest:"c".repeat(64)},/BINDING/],[{sourceId:"WRONG"},/BINDING|SOURCE/],[{operation:"SELLERS"},/BINDING|OPERATION/],[{maximumTaskCostUsd:.002},/BINDING|CEILING/]]){assert.throws(()=>validate({...authority,...change}),pattern);cases++;}assert.throws(()=>validateNeutralParentAuthorityInput({authority,parentAuthorization:parent,plan,member,expectedSourceId:member.source,expectedOperation:"PRODUCTS",maximumTaskCostUsd:.001,asOf:expires}),/EXPIRED/);cases++;
const boundedRepository={getAuthorization:id=>id===parent.authorizationId?parent:null,getPlan:id=>id===plan.planId?plan:null,getPlanMember:(id,key)=>id===plan.planId&&key===member.memberKey?member:null},policy=createAcquisitionBudgetPolicy({enabled:true,maxPaidTasksPerRun:1,maxSpendPerRunUsd:.001,maxSpendPerDayUsd:.025,automaticPaidRetries:0}),googlePlan=createAcquisitionPlan({candidates:[{candidateId:"candidate",priority:"NORMAL",estimatedCostUsd:.001,execution:{kind:"PRODUCTS",provider:"DATAFORSEO",source:member.source,keyword:"MPN",locationName:"United States",languageName:"English"}}],policy,spentTodayUsd:0,plannedAt:at}),manual=createManualLiveAuthorizationRequest({plan:googlePlan,createdAt:at}),derived=createNeutralDerivedProductsAuthorizationRequest({plan:googlePlan,neutralParentAuthority:authority,boundedRepository,createdAt:at});eq(manual.status,"PENDING_OPERATOR_APPROVAL");eq(derived.status,"LIVE_AUTHORIZED");eq(derived.authorityOrigin,"NEUTRAL_BOUNDED_PARENT");eq(derived.plan,googlePlan);eq(createNeutralDerivedProductsAuthorizationRequest({plan:googlePlan,neutralParentAuthority:authority,boundedRepository,createdAt:at}).requestId,derived.requestId);assert.throws(()=>createNeutralDerivedProductsAuthorizationRequest({plan:googlePlan,neutralParentAuthority:authority,boundedRepository:{...boundedRepository,getAuthorization:()=>null},createdAt:at}),/NOT_FOUND/);cases++;

const product={identity:{atlasProductId:"ram_fixture",brand:"Corsair",manufacturerPartNumber:"CMH32GX5M2B6000C38"},governance:{lifecycleStatus:"ACTIVE",publicationStatus:"READY"},extension:{data:{capacity:{capacityGb:32,moduleCount:2},classification:{memoryType:"DDR5",formFactor:"DIMM"},performance:{dataRateMtps:6000},physical:{color:"black"}}}},selection=selectAmazonHistoricalAcceptanceProduct({atlasProducts:[product],destinations:[{destinationId:"d",atlasProductId:"ram_fixture",retailerId:"RETAILER-0001",marketplace:"amazon.com",retailerListingId:"B0CQQVNCB6",status:"ACTIVE"}],historicalObservations:[]}),artifact=prepareAmazonHistoricalAcceptance({asOf:at,selection,rightsProfile:defaultSourceRightsRegistry.require("DATAFORSEO_AMAZON"),currentUtcDaySpendUsd:0}),am={memberKey:"amazon:1",domainMemberId:artifact.acceptanceArtifactId,source:"DATAFORSEO_AMAZON",operation:"AMAZON_PRODUCTS",taskCeilingUsd:.0015},ap={planId:"amazon-plan",bindingDigest:"d".repeat(64),ready:[am]},apa={...parent,planId:ap.planId,planBindingDigest:ap.bindingDigest},aa=createNeutralParentAuthorityInput({parentAuthorization:apa,plan:ap,member:am}),amazonRepository={getAuthorization:id=>id===apa.authorizationId?apa:null,getPlan:id=>id===ap.planId?ap:null,getPlanMember:(id,key)=>id===ap.planId&&key===am.memberKey?am:null},base={artifact,operation:"AMAZON_PRODUCTS",atlasProduct:product,operator:"operator",reason:"fixture",authorizedAt:at,expiresAt:expires,currentUtcDaySpendUsd:0},explicit=createAmazonAcceptanceActionAuthorization(base),amazon=createAmazonAcceptanceActionAuthorization({...base,operator:"machine:bounded-auth",neutralParentAuthority:aa,boundedRepository:amazonRepository});eq(explicit.schemaVersion,"1.0");eq(amazon.schemaVersion,"1.1");eq(amazon.authorityOrigin,"NEUTRAL_BOUNDED_PARENT");eq(amazon.artifactId,artifact.acceptanceArtifactId);eq(createAmazonAcceptanceActionAuthorization({...base,operator:"machine:bounded-auth",neutralParentAuthority:aa,boundedRepository:amazonRepository}).authorizationId,amazon.authorizationId);assert.throws(()=>createAmazonAcceptanceActionAuthorization({...base,neutralParentAuthority:{...aa,sourceId:"WRONG"},boundedRepository:amazonRepository}),/NEUTRAL_PARENT/);cases++;

const root=await mkdtemp(join(tmpdir(),"bounded-neutral-"));try{const repo=new SqliteNeutralBoundedRepository({databasePath:join(root,"mercury.sqlite")});for(const size of[10,100,1000,10000]){const ready=Array.from({length:size},(_,i)=>({memberKey:`m:${size}:${i}`,domainMemberId:`d:${size}:${i}`,source:"SOURCE",operation:"OPERATION",taskCeilingUsd:0})),value={schemaVersion:"1.0",planId:`plan:${size}`,bindingDigest:"e".repeat(64),cycle:at,ready,blocked:[],requested:ready,cohortDigest:"f".repeat(64),maximumPaidTasks:size,maximumSpendUsd:0,preparedAt:at,authorizationState:"NOT_AUTHORIZED",providerSpendAuthorized:false};eq(repo.recordPlan(value).status,"PREPARED");eq(repo.getPlanMember(value.planId,ready.at(-1).memberKey).domainMemberId,ready.at(-1).domainMemberId);eq(repo.recordPlan(value).status,"DUPLICATE");}const value=repo.getPlan("plan:10"),auth={authorizationId:"auth:10",planId:value.planId,authorizedAt:at,expiresAt:expires,bindingDigest:"1".repeat(64)};eq(repo.recordAuthorization(auth).status,"AUTHORIZED");eq(repo.recordAuthorization(auth).status,"DUPLICATE");const run={runId:"run:10",planId:value.planId,authorizationId:auth.authorizationId,state:"RUNNING",members:value.ready.map(x=>({...x,state:"READY"}))};eq(repo.startRun(run).status,"STARTED");eq(repo.getRunMember(run.runId,value.ready[0].memberKey).state,"READY");const child={parentAuthorizationId:auth.authorizationId,memberKey:value.ready[0].memberKey,childAuthorizationId:"child:10",bindingDigest:"2".repeat(64)};eq(repo.recordChildAuthority(child).status,"RECORDED");eq(repo.recordChildAuthority(child).status,"DUPLICATE");eq(repo.getChildAuthority(auth.authorizationId,child.memberKey),child);repo.close();}finally{await rm(root,{recursive:true,force:true});}
console.log(`Neutral Products prerequisites tests passed: ${cases} cases.`);
