import assert from "node:assert/strict";
import {NeweggRoutineProductionCommand,NEWEGG_ROUTINE_COMMAND_STAGES,createPrivateForgeOperationsEnvelope,PrivateForgeOperationsTransport,InMemoryPrivateForgeOperationsStore,createPrivateForgeOperationsHttpHandler} from "../index.js";

const bindingDigest="a".repeat(64),clock=()=>"2026-10-04T20:00:00.000Z";
class Repo{constructor(run=null){this.run=run;}async loadActive(){return this.run&&!["SUCCESS_RELEASE_READY","SUCCESS_NO_CHANGE"].includes(this.run.status)?structuredClone(this.run):null;}async save(run){this.run=structuredClone(run);}}
const projection={schemaVersion:"1.0",projectionType:"NEWEGG_ROUTINE_OPERATIONS",asOf:clock(),status:"SUCCESS",schedule:{state:"DUE"},readOnly:true,mutationAuthorized:false,networkOperation:"NONE",affiliateRevalidation:false,releaseAuthority:false};
const token="fixture-private-token-1234567890",store=new InMemoryPrivateForgeOperationsStore(),transport=new PrivateForgeOperationsTransport({store,accessToken:token,now:clock});
const calls=[],owners=Object.fromEntries(NEWEGG_ROUTINE_COMMAND_STAGES.map(stage=>[stage,{execute:async({mode})=>{calls.push(stage);if(stage==="ACQUISITION")return {providerCalls:mode==="PRODUCTION"?1:0,fullDownloads:mode==="PRODUCTION"?1:0,deltaDownloads:0,retries:0};if(stage==="FORGE_PROJECTION")return projection;if(stage==="FORGE_TRANSPORT")return transport.publish(createPrivateForgeOperationsEnvelope({projection,createdAt:clock()}));return {status:"PASS",productCount:200};}}]));
const repo=new Repo(),command=new NeweggRoutineProductionCommand({runRepository:repo,overlapOwner:{assess:async()=>({state:"DUE"})},stageOwners:owners,now:clock});
const success=await command.execute({mode:"FIXTURE",input:{bindingDigest}});assert.equal(success.outcome,"SUCCESS_RELEASE_READY");assert.deepEqual(calls,NEWEGG_ROUTINE_COMMAND_STAGES);assert.equal(success.providerCalls,0);assert.equal(success.releaseAuthority,false);assert.equal((await transport.readLatest({accessToken:token})).projectionDigest.length,64);await assert.rejects(()=>transport.readLatest({accessToken:"wrong"}),/ACCESS_DENIED/);
const replayRepo=new Repo({...repo.run,status:"RUNNING",completedStages:NEWEGG_ROUTINE_COMMAND_STAGES.slice(0,-1)}),replayCalls=[],replayOwners={...owners,FORGE_TRANSPORT:{execute:async()=>{replayCalls.push("FORGE_TRANSPORT");return {status:"REPLAY"};}}};const replay=await new NeweggRoutineProductionCommand({runRepository:replayRepo,overlapOwner:{assess:async()=>({state:"DUE"})},stageOwners:replayOwners,now:clock}).execute({mode:"RETAINED_EVIDENCE",input:{bindingDigest}});assert.equal(replay.outcome,"SUCCESS_NO_CHANGE");assert.deepEqual(replayCalls,["FORGE_TRANSPORT"]);
const blocked=await new NeweggRoutineProductionCommand({runRepository:new Repo({...repo.run,status:"RUNNING",bindingDigest:"b".repeat(64)}),overlapOwner:{assess:async()=>({state:"DUE"})},stageOwners:owners,now:clock}).execute({mode:"PRODUCTION",input:{bindingDigest}});assert.equal(blocked.outcome,"BLOCKED_ACTIVE_RUN");assert.equal(blocked.exitCode,2);assert.equal(blocked.providerCalls,0);
for(const [stage,outcome] of [["ACQUISITION","PROVIDER_FAILURE"],["VALIDATION","INTEGRITY_FAILURE"],["CURRENT","CURRENT_FAILURE"],["HISTORY","HISTORY_FAILURE"],["QA","QA_FAILURE"],["CERTIFICATION","CERTIFICATION_FAILURE"],["FORGE_TRANSPORT","FORGE_TRANSPORT_FAILURE"]]){const localOwners=Object.fromEntries(NEWEGG_ROUTINE_COMMAND_STAGES.map(value=>[value,{execute:async()=>{if(value===stage)throw new Error("fixture");return {status:"PASS"};}}]));const result=await new NeweggRoutineProductionCommand({runRepository:new Repo(),overlapOwner:{assess:async()=>({state:"DUE"})},stageOwners:localOwners,now:clock}).execute({mode:"FIXTURE",input:{bindingDigest}});assert.equal(result.outcome,outcome);}
const stale=createPrivateForgeOperationsEnvelope({projection,createdAt:"2026-10-04T19:00:00Z",maximumAgeSeconds:10}),staleStore=new InMemoryPrivateForgeOperationsStore();await staleStore.put(stale.projectionDigest,stale);await assert.rejects(()=>new PrivateForgeOperationsTransport({store:staleStore,accessToken:token,now:clock}).readLatest({accessToken:token}),/STALE/);const corrupt=structuredClone(createPrivateForgeOperationsEnvelope({projection,createdAt:clock()}));corrupt.projection.status="CORRUPT";assert.throws(()=>transport.validate(corrupt),/CORRUPT/);
assert.equal(projection.mutationAuthorized,false);assert.equal(repo.run.providerEnvelope.fullDownloadsMaximum,1);assert.equal(repo.run.providerEnvelope.deltaDownloadsMaximum,0);assert.equal(repo.run.providerEnvelope.automaticRetries,0);assert.equal(repo.run.affiliateRevalidation,false);assert.equal(repo.run.stageResults.RETENTION_ASSESSMENT.productCount,200);
const handler=createPrivateForgeOperationsHttpHandler({transport}),response=()=>({headers:{},setHeader(k,v){this.headers[k]=v;},end(value){this.body=value;}}),denied=response();await handler({method:"GET",url:"/internal/forge/newegg-routine",headers:{}},denied);assert.equal(denied.statusCode,401);assert.equal(denied.headers["X-Robots-Tag"],"noindex, nofollow");const allowed=response();await handler({method:"GET",url:"/internal/forge/newegg-routine",headers:{authorization:`Bearer ${token}`}},allowed);assert.equal(allowed.statusCode,200);assert.equal(JSON.parse(allowed.body).projection.readOnly,true);const publicPath=response();await handler({method:"GET",url:"/ram/terminal/",headers:{authorization:`Bearer ${token}`}},publicPath);assert.equal(publicPath.statusCode,404);
console.log("Newegg routine production command and private Forge transport tests passed: 33 cases.");
