import assert from "node:assert/strict";
import {mkdtemp,rm} from "node:fs/promises";
import {tmpdir} from "node:os";
import {join} from "node:path";
import {ProductionForgeCohortOperationsProvider,SqliteNeutralBoundedRepository,SqliteRepeatObservationRepository} from "../index.js";
const root=await mkdtemp(join(tmpdir(),"forge-cohort-owner-")),at="2026-09-15T12:00:00.000Z",later="2026-09-15T13:00:00.000Z";
try{
 const boundedPath=join(root,"bounded.sqlite"),bounded=new SqliteNeutralBoundedRepository({databasePath:boundedPath}),ready={memberKey:"ram_one:DATAFORSEO_AMAZON",domainMemberId:"ram_one",atlasProductId:"ram_one",source:"DATAFORSEO_AMAZON",operation:"PRODUCTS",taskCeilingUsd:.0015},plan={planId:"plan",bindingDigest:"a".repeat(64),cycle:at,requested:[ready],ready:[ready],blocked:[],maximumSpendUsd:.0015};bounded.recordPlan(plan);bounded.recordAuthorization({authorizationId:"auth",planId:"plan",authorizedAt:at,expiresAt:later,bindingDigest:"b".repeat(64)});bounded.startRun({runId:"run",planId:"plan",authorizationId:"auth",state:"COMPLETED",members:[{...ready,state:"COMPLETED",outcome:"INSUFFICIENT_ASIN_EVIDENCE",h052ReviewAvailable:true,assessmentId:"h051",providerResultId:"result"}]});bounded.close();
 const repeatPath=join(root,"repeat.sqlite"),repeat=new SqliteRepeatObservationRepository({databasePath:repeatPath});repeat.recordRunPlan({runPlanId:"repeat-plan",bindingDigest:"c".repeat(64),observationCycle:"cycle",members:[{atlasProductId:"ram_two"}]});repeat.recordRunAuthorization({runAuthorizationId:"repeat-auth",runPlanId:"repeat-plan",authorizedAt:at,expiresAt:later,bindingDigest:"d".repeat(64)});repeat.startRun({runId:"repeat-run",runPlanId:"repeat-plan",runAuthorizationId:"repeat-auth",state:"COMPLETED",members:[{preparedObservationId:"prepared",atlasProductId:"ram_two",source:"DATAFORSEO_GOOGLE_SHOPPING",operation:"SELLERS",state:"COMPLETED",outcome:"ADMITTED"}]});repeat.close();
 const cohorts=await new ProductionForgeCohortOperationsProvider({boundedDatabasePath:boundedPath,repeatDatabasePath:repeatPath}).load();assert.equal(cohorts.length,2);assert.equal(cohorts[0].members[0].reviewEligibility.owner,"H052_OPERATOR_REVIEW");assert.equal(cohorts[1].cohortType,"REPEAT_OBSERVATION");assert.equal(cohorts[1].members[0].atlasProductId,"ram_two");assert.equal(cohorts[0].cost.actualSpendUsd,0);assert.equal((await new ProductionForgeCohortOperationsProvider({boundedDatabasePath:join(root,"missing.sqlite")}).load()).length,0);console.log("Production Forge cohort operations provider tests passed (6 cases).");
}finally{await rm(root,{recursive:true,force:true,maxRetries:5,retryDelay:100}).catch(error=>{if(error?.code!=="EBUSY")throw error;});}
