import assert from "node:assert/strict";
import crypto from "node:crypto";
import {mkdtemp,rm} from "node:fs/promises";
import {tmpdir} from "node:os";
import {join} from "node:path";
import {PRODUCTS_DISCOVERY_CONFIRMATIONS,SqliteNeutralBoundedRepository,createProductionProductsIdentityDiscoveryService,defaultSourceRightsRegistry} from "../index.js";
import {parseIdentityDiscoveryArgs,runIdentityDiscoveryCommand} from "../../../scripts/mercury-products-identity-discovery-runtime.mjs";
let cases=0;const eq=(a,b)=>{assert.deepEqual(a,b);cases++};
const stable=x=>Array.isArray(x)?`[${x.map(stable).join(",")}]`:x&&typeof x==="object"?`{${Object.keys(x).sort().map(k=>`${JSON.stringify(k)}:${stable(x[k])}`).join(",")}}`:JSON.stringify(x);
const hash=x=>crypto.createHash("sha256").update(stable(x)).digest("hex"),at="2026-09-14T12:00:00.000Z",expires="2026-09-14T13:00:00.000Z",ids=["ram_factory_one","ram_factory_two"];
const products=ids.map((id,i)=>({identity:{atlasProductId:id,brand:"Corsair",manufacturerPartNumber:`MPN${i}`}})),productRepository={getById:async id=>products.find(x=>x.identity.atlasProductId===id)??null};
const root=await mkdtemp(join(tmpdir(),"products-discovery-factory-")),repository=new SqliteNeutralBoundedRepository({databasePath:join(root,"bounded.sqlite")});
try{
 let spend=.006,calls=0,pending=true;
 const owner={prepare:async({rightsProfile})=>({rightsDigest:hash(rightsProfile),requestIdentity:"request"}),authorize:async({member,parentAuthorization})=>({authorizationId:`child-${member.domainMemberId}`,authorizationDigest:"c".repeat(64),expiresAt:parentAuthorization.expiresAt,durableAuthority:true}),execute:async()=>({status:"COMPLETED"}),resolveTask:async({member})=>({providerTaskId:`task-${member.domainMemberId}`,actualSpendUsd:member.taskCeilingUsd}),retrieve:async()=>{calls++;return pending?{status:"PENDING"}:{status:"AVAILABLE",canonicalResult:{}}},finalize:async()=>({state:"IDENTITY_RESOLVED",assessmentId:"assessment"})};
 const runtime=createProductionProductsIdentityDiscoveryService({stateRoot:root,productRepository,boundedRepository:repository,rightsRegistry:defaultSourceRightsRegistry,readinessOwner:{assess:async()=>({state:"READY_FOR_DISCOVERY",readinessBindingDigest:"b".repeat(64)})},sourceOwners:{DATAFORSEO_GOOGLE_SHOPPING:owner,DATAFORSEO_AMAZON:owner},spendResolver:async()=>spend,now:()=>at});
 eq(typeof runtime.readinessOwner.assess,"function");
 const terminalResultRepository={getNeutralProductsFinalizationsForProduct:async()=>[{state:"NO_USABLE_IDENTITY",finalizationId:"mer_googleidfinal_terminal",bindingDigest:"d".repeat(64)}]};
 const terminalRuntime=createProductionProductsIdentityDiscoveryService({stateRoot:root,productRepository,boundedRepository:repository,rightsRegistry:defaultSourceRightsRegistry,historicalRepository:{getAll:async()=>[]},evidenceRepository:{getById:async()=>null},resultRepository:terminalResultRepository,amazonArtifactRepository:{getAll:async()=>[]},amazonActionRepository:{getEffectiveOutcomeForArtifact:async()=>null},sourceOwners:{DATAFORSEO_GOOGLE_SHOPPING:owner,DATAFORSEO_AMAZON:owner},spendResolver:async()=>spend,now:()=>at});
 const terminalReadiness=await terminalRuntime.readinessOwner.assess({atlasProductId:ids[0],sourceId:"DATAFORSEO_GOOGLE_SHOPPING",asOf:at});eq(terminalReadiness.readinessState,"REVIEW_REQUIRED");eq(terminalReadiness.reasons,["NO_USABLE_IDENTITY"]);
 const cohort=ids.map(atlasProductId=>({atlasProductId,sourceId:"DATAFORSEO_AMAZON"})),prepared=await runtime.service.prepare({cycle:at,cohort});
 eq(prepared.value.maximumPaidTasks,2);eq(prepared.value.maximumSpendUsd,.003);
 const authorized=await runtime.service.authorize({planId:prepared.value.planId,operator:"fixture",reason:"fixture",expiresAt:expires,confirmation:PRODUCTS_DISCOVERY_CONFIRMATIONS.AUTHORIZE});eq(authorized.value.currentUtcDaySpendUsd,.006);
	 spend=.073;await assert.rejects(()=>runtime.service.start({authorizationId:authorized.value.authorizationId,startedBy:"fixture",confirmation:PRODUCTS_DISCOVERY_CONFIRMATIONS.START}),/BOUNDED_AGGREGATE_BUDGET_INVALID/);cases++;
 spend=.006;const started=await runtime.service.start({authorizationId:authorized.value.authorizationId,startedBy:"fixture",confirmation:PRODUCTS_DISCOVERY_CONFIRMATIONS.START});eq(started.state,"WAITING_FOR_PROVIDER");eq(started.sellersTasksCreated,0);eq(started.evidenceWritten,0);eq(started.historyWritten,0);
 pending=false;const resumed=await runtime.service.resume({runId:started.runId,resumedBy:"fixture",confirmation:PRODUCTS_DISCOVERY_CONFIRMATIONS.RESUME});eq(resumed.state,"COMPLETED");eq(resumed.paidTasksCreated,2);eq(resumed.publicationAuthority,false);eq(resumed.currentPriceAuthority,false);eq((await runtime.service.resume({runId:started.runId,resumedBy:"fixture",confirmation:PRODUCTS_DISCOVERY_CONFIRMATIONS.RESUME})).state,"COMPLETED");eq(calls,4);
 const args={prepare:["--cohort-file=x",`--discovery-cycle=${at}`],inspect:["--discovery-plan-id=p"],authorize:["--discovery-plan-id=p","--operator=o","--reason=r",`--expires-at=${expires}`,`--confirm=${PRODUCTS_DISCOVERY_CONFIRMATIONS.AUTHORIZE}`],start:["--authorization-id=a","--executed-by=o",`--confirm=${PRODUCTS_DISCOVERY_CONFIRMATIONS.START}`],resume:["--run-id=r","--resumed-by=o",`--confirm=${PRODUCTS_DISCOVERY_CONFIRMATIONS.RESUME}`],"assess-taskless-disposition":["--run-id=r","--member-key=m"],"dispose-taskless":["--run-id=r","--member-key=m","--operator=o","--reason=r","--confirm=DISPOSE-EXPIRED-CONSUMED-TASKLESS-CHILD"]};
 for(const[action,values]of Object.entries(args))eq(parseIdentityDiscoveryArgs(action,values).size,values.length);assert.throws(()=>parseIdentityDiscoveryArgs("prepare",[...args.prepare,"--product=x"]),/NOT_ALLOWED/);cases++;
 const commandCalls=[],fake={service:{prepare:async x=>(commandCalls.push("prepare"),x),inspect:async x=>(commandCalls.push("inspect"),x),authorize:async x=>(commandCalls.push("authorize"),x),start:async x=>(commandCalls.push("start"),x),resume:async x=>(commandCalls.push("resume"),x)},assessTasklessDisposition:async x=>(commandCalls.push("assess"),x),disposeTasklessChild:async x=>(commandCalls.push("dispose"),x)};
 await runIdentityDiscoveryCommand("prepare",["--cohort-file=fixture.json",`--discovery-cycle=${at}`],{runtime:fake,readJson:async()=>[{atlasProductId:"ram_x",sourceId:"DATAFORSEO_AMAZON"}]});for(const action of["inspect","authorize","start","resume","assess-taskless-disposition","dispose-taskless"])await runIdentityDiscoveryCommand(action,args[action],{runtime:fake});eq(commandCalls,["prepare","inspect","authorize","start","resume","assess","dispose"]);
 const productionArtifacts=[],productionRepository=new SqliteNeutralBoundedRepository({databasePath:join(root,"production-destinations.sqlite")}),productionArtifactRepository={getAll:async()=>structuredClone(productionArtifacts),getById:async id=>structuredClone(productionArtifacts.find(value=>value.acceptanceArtifactId===id)??null),record:async value=>{productionArtifacts.push(structuredClone(value));return{status:"PREPARED",artifact:value};}};
 try{const productionRuntime=createProductionProductsIdentityDiscoveryService({stateRoot:join(root,"production"),acquisitionRoot:join(root,"production-acquisition"),mercuryRoot:join(root,"production-mercury"),boundedRepository:productionRepository,amazonArtifactRepository:productionArtifactRepository,spendResolver:async()=>.001,now:()=>at}),cohort=[{atlasProductId:"ram_corsair_cmk32gx5m2b6000z30",sourceId:"DATAFORSEO_AMAZON"},{atlasProductId:"ram_crucial_cp2k16g56c46u5",sourceId:"DATAFORSEO_AMAZON"}],destinationPrepared=await productionRuntime.service.prepare({cycle:at,cohort});eq(destinationPrepared.value.ready.length,2);eq(destinationPrepared.value.blocked.length,0);eq(destinationPrepared.value.maximumSpendUsd,.003);eq(productionArtifacts.map(value=>[value.atlasProductId,value.destinationId,value.corroboratingDestinationAsins]),[["ram_corsair_cmk32gx5m2b6000z30","mer_dest_d569896c0d7559fc2d71b03e",["B0CBRJ63RT"]],["ram_crucial_cp2k16g56c46u5","mer_dest_6b7758415fcb4bec859927e3",["B0C2B7W1W4"]]]);assert.ok(productionArtifacts.every(value=>value.authorizationState==="NOT_AUTHORIZED"&&value.paidTaskCreated===false&&value.actualSpendUsd===0));cases++;}finally{productionRepository.close();}
}finally{repository.close();await rm(root,{recursive:true,force:true,maxRetries:5,retryDelay:50})}
console.log(`Production Products identity discovery tests passed: ${cases} cases.`);
