import assert from "node:assert/strict";
import {mkdtemp,rm,writeFile} from "node:fs/promises";
import os from "node:os";
import path from "node:path";
import {ProductionForgeAmazonDestinationReviewProvider} from "../operations/ProductionForgeAmazonDestinationReviewProvider.js";
import {CertifiedMercuryOperationsPanel} from "../../../apps/forge/components/CertifiedMercuryOperationsPanel.js";

const directory=await mkdtemp(path.join(os.tmpdir(),"forge-amazon-destination-")),statePath=path.join(directory,"queue.json");
const preparation=index=>({preparationId:`prep-${String(index).padStart(3,"0")}`,bindingDigest:`digest-${index}`,atlasProductId:`ram-${index}`,manufacturerPartNumber:`MPN-${index}`,asin:`B000000${index}`,candidateUrl:`https://amazon.com/dp/B000000${index}`,identityState:"STRONG_UNIQUE_ASIN",assessmentId:`assessment-${index}`,canonicalResultId:`result-${index}`,providerTaskId:`task-${index}`,sourceRightsProfileDigest:`rights-${index}`,collision:{productDestinationId:null,listingDestinationId:null,urlDestinationId:null,crossProductDestinationId:null},qualification:"ACTIONABILITY_REVIEW_REQUIRED",requiredReviewMethod:"OPERATOR_EXACT_PRODUCT_REVIEW"});
const source={schemaVersion:"1.0",artifactType:"AMAZON_DESTINATION_OPERATOR_REVIEW_QUEUE",policyVersion:"fixture-1",preparations:Array.from({length:5},(_,index)=>preparation(index+1)),networkOperation:"NONE",canonicalDestinationCreated:false};
await writeFile(statePath,JSON.stringify(source));
const current=new Map(source.preparations.map(item=>[item.atlasProductId,{...item,qualification:"ACTIONABILITY_REVIEW_REQUIRED"}])),reviews=new Map(),service={prepare:async({atlasProductId})=>structuredClone(current.get(atlasProductId))},products={getById:async atlasProductId=>({identity:{atlasProductId,brand:"Fixture"}})},reviewRepository={getByPreparationId:async id=>reviews.get(id)??null},provider=new ProductionForgeAmazonDestinationReviewProvider({preparationPath:statePath,progressionService:service,productRepository:products,reviewRepository});
let projection=await provider.load();assert.equal(projection.items.length,5);assert.equal(projection.counts.AWAITING_OPERATOR_REVIEW,5);assert.equal(projection.counts.APPROVED,0);assert.equal(projection.counts.REJECTED,0);assert.equal(projection.readOnly,true);assert.equal(projection.mutationAuthorized,false);assert.equal(projection.destinationPersistenceAuthority,false);assert.equal(projection.networkOperation,"NONE");assert.equal(projection.actualSpendUsd,0);assert.equal(JSON.stringify(projection).includes("password"),false);
source.preparations.push(preparation(6));current.set("ram-6",{...preparation(6),qualification:"ACTIONABILITY_REVIEW_REQUIRED"});await writeFile(statePath,JSON.stringify(source));projection=await provider.load();assert.equal(projection.items.length,6);assert.equal(projection.counts.AWAITING_OPERATOR_REVIEW,6);reviews.set("prep-004",{reviewId:"review-4",decision:"APPROVE"});reviews.set("prep-005",{reviewId:"review-5",decision:"REJECT"});projection=await provider.load();assert.equal(projection.counts.APPROVED,1);assert.equal(projection.counts.REJECTED,1);
current.set("ram-1",{...preparation(1),bindingDigest:"changed",qualification:"ACTIONABILITY_REVIEW_REQUIRED"});current.set("ram-2",{...preparation(2),qualification:"ALREADY_BOUND"});service.prepare=async({atlasProductId})=>{if(atlasProductId==="ram-3")throw new Error("RIGHTS_BLOCKED");return structuredClone(current.get(atlasProductId));};projection=await provider.load();assert.equal(projection.counts.STALE,1);assert.equal(projection.counts.ALREADY_BOUND,1);assert.equal(projection.counts.BLOCKED,1);assert.equal(projection.counts.APPROVED,1);assert.equal(projection.counts.REJECTED,1);

class Element{constructor(){this.textContent="";this.className="";this.children=[];this.files=[];}addEventListener(){}replaceChildren(...children){this.children=children;}append(...children){this.children.push(...children);}querySelector(selector){return this.map[selector];}}
const root=new Element();root.map={"#certifiedMercuryProjectionFile":new Element(),"#certifiedMercuryProjectionStatus":new Element(),"#certifiedMercuryProjectionSummary":new Element(),"#certifiedMercuryProjectionAmazonDestinationReviewStatus":new Element(),"#certifiedMercuryProjectionAmazonDestinationReviews":new Element(),"#certifiedMercuryProjectionProducts":new Element(),"#certifiedMercuryProjectionDetails":new Element()};globalThis.document={createElement:()=>new Element()};
new CertifiedMercuryOperationsPanel(root).render({schemaVersion:"1.1",projectionType:"CERTIFIED_MERCURY_OPERATIONS_PROJECTION",readOnly:true,mutationAuthorized:false,networkOperation:"NONE",asOf:"2026-10-07T00:00:00.000Z",semantics:{canonicalOperationalView:true,historicalValueSemantics:"HISTORICAL_OBSERVATION",currentPrice:false,livePrice:false,publicPrice:false,publicationAuthority:false},summary:{},products:[],amazonDestinationReviewOperations:projection});assert.equal(root.map["#certifiedMercuryProjectionAmazonDestinationReviews"].children.length,6);assert.match(root.map["#certifiedMercuryProjectionAmazonDestinationReviewStatus"].textContent,/stale 1/);assert.equal(root.map["#certifiedMercuryProjectionAmazonDestinationReviews"].children[0].children[1].rel,"noopener noreferrer");assert.match(root.map["#certifiedMercuryProjectionAmazonDestinationReviews"].children[0].children[0].textContent,/no approval or mutation/i);
source.preparations=Array.from({length:200},(_,index)=>preparation(index+1));reviews.clear();for(const item of source.preparations)current.set(item.atlasProductId,{...item,qualification:"ACTIONABILITY_REVIEW_REQUIRED"});service.prepare=async({atlasProductId})=>structuredClone(current.get(atlasProductId));await writeFile(statePath,JSON.stringify(source));projection=await provider.load();assert.equal(projection.items.length,200);assert.equal(projection.counts.AWAITING_OPERATOR_REVIEW,200);
await rm(directory,{recursive:true,force:true});console.log("Production Forge Amazon destination review provider tests passed (22 cases).");
