import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
import {selectProductScopedInitialAcquisitionCandidate,createAcquisitionBudgetPolicy,createAcquisitionPlan,createManualLiveAuthorizationRequest} from '../index.js';

const makeProduct=(id,mpn,governance={lifecycleStatus:'ACTIVE',publicationStatus:'READY'})=>({identity:{atlasProductId:id,manufacturerPartNumber:mpn,recordRevision:2},governance});
const makeCandidate=(id,mpn,lastObservedAt=null)=>({candidateId:`atlas:${id}:products`,atlasProductId:id,priority:'NORMAL',estimatedCostUsd:.001,lastObservedAt,rationale:'fixture',execution:{kind:'PRODUCTS',keyword:mpn,locationName:'United States',languageName:'English'}});
const examples=[['ram_crucial_cp2k16g56c46u5','CP2K16G56C46U5'],['ram_teamgroup_ctced532g6000hc30dc01','CTCED532G6000HC30DC01'],['ram_g_skill_f4_3200c16d_32gvk','F4-3200C16D-32GVK'],['ram_kingston_kvr32n22d8_32','KVR32N22D8/32'],['ram_crucial_ct16g56c46s5','CT16G56C46S5'],['ram_g_skill_f5_5600s4040a16gx2_rs','F5-5600S4040A16GX2-RS']];
for(const [id,mpn] of examples){const selected=selectProductScopedInitialAcquisitionCandidate({atlasProductId:id,product:makeProduct(id,mpn),candidates:[makeCandidate('ram_unrelated','OTHER'),makeCandidate(id,mpn)]});assert.equal(selected.atlasProductId,id);assert.equal(selected.execution.keyword,mpn);assert.equal(selected.execution.provider,'DATAFORSEO');assert.equal(selected.execution.source,'DATAFORSEO_GOOGLE_SHOPPING');assert.equal(selected.atlasBinding.manufacturerPartNumber,mpn);assert(Object.isFrozen(selected));}
const [id,mpn]=examples[0],product=makeProduct(id,mpn),candidate=makeCandidate(id,mpn);
assert.throws(()=>selectProductScopedInitialAcquisitionCandidate({atlasProductId:'bad id',product,candidates:[candidate]}),/SELECTOR_INVALID/);
assert.throws(()=>selectProductScopedInitialAcquisitionCandidate({atlasProductId:id,product:null,candidates:[candidate]}),/NOT_FOUND_OR_SUBSTITUTED/);
assert.throws(()=>selectProductScopedInitialAcquisitionCandidate({atlasProductId:id,product:makeProduct(id,mpn,{lifecycleStatus:'DRAFT',publicationStatus:'PENDING'}),candidates:[candidate]}),/NOT_ACTIVE_READY/);
assert.throws(()=>selectProductScopedInitialAcquisitionCandidate({atlasProductId:id,product,candidates:[]}),/CANDIDATE_NOT_FOUND/);
assert.throws(()=>selectProductScopedInitialAcquisitionCandidate({atlasProductId:id,product,candidates:[candidate,candidate]}),/CANDIDATE_AMBIGUOUS/);
assert.throws(()=>selectProductScopedInitialAcquisitionCandidate({atlasProductId:id,product,candidates:[{...candidate,candidateId:'atlas:substituted:products'}]}),/PRODUCT_SUBSTITUTION/);
assert.throws(()=>selectProductScopedInitialAcquisitionCandidate({atlasProductId:id,product,candidates:[{...candidate,execution:{...candidate.execution,keyword:'SUBSTITUTED'}}]}),/MPN_SUBSTITUTION/);
assert.throws(()=>selectProductScopedInitialAcquisitionCandidate({atlasProductId:id,product,candidates:[makeCandidate(id,mpn,'2026-09-01T00:00:00Z')]}),/REQUIRES_HISTORICAL_REFRESH/);
const selected=selectProductScopedInitialAcquisitionCandidate({atlasProductId:id,product,candidates:[candidate]}),policy=createAcquisitionBudgetPolicy({enabled:true,maxPaidTasksPerRun:1,maxSpendPerRunUsd:.001,maxSpendPerDayUsd:.01,automaticPaidRetries:0}),input={candidates:[selected],policy,spentTodayUsd:0,plannedAt:'2026-09-01T18:00:00Z'},a=createAcquisitionPlan(input),b=createAcquisitionPlan(input);assert.deepEqual(a,b);assert.equal(a.decisions.length,1);assert.equal(a.decisions[0].candidateId,`atlas:${id}:products`);assert.equal(a.approvedTaskCount,1);assert.equal(a.estimatedApprovedSpendUsd,.001);const auth=createManualLiveAuthorizationRequest({plan:a,createdAt:'2026-09-01T18:01:00Z'});assert.equal(auth.plan.decisions.length,1);assert.equal(auth.maxPaidTasks,1);assert.equal(auth.maxSpendUsd,.001);assert.equal(auth.automaticPaidRetries,0);assert.equal(auth.plan.decisions[0].execution.keyword,mpn);
const scheduled=await readFile(new URL('../../../scripts/mercury-scheduled-dry-run.mjs',import.meta.url),'utf8'),prepare=await readFile(new URL('../../../scripts/mercury-live-prepare.mjs',import.meta.url),'utf8');assert.match(scheduled,/ScheduledDryRunRunner/);assert.match(scheduled,/intervalMinutes:Number\(process\.env\.HARDWARE_RADAR_ACQUISITION_INTERVAL_MINUTES\|\|360\)/);assert.match(scheduled,/Current candidates:/);assert.match(scheduled,/Persisted approved:/);assert.match(scheduled,/Network operation:\s+NONE/);assert.match(prepare,/selectorArgs\.length>1/);assert.match(prepare,/planningCandidates=selected\?\[selected\]:candidates/);assert.doesNotMatch(prepare,/transport\.execute|DataForSeoAcquisitionService/);
console.log('Product-scoped initial acquisition tests passed.');
