import assert from "node:assert/strict";
import {copyFile,mkdtemp,readFile,readdir,rename,rm,writeFile,mkdir} from "node:fs/promises";
import os from "node:os";
import path from "node:path";
import {ProductRepository,RetailerRepository} from "../../atlas/index.js";
import {AMAZON_DESTINATION_APPROVAL_ATTESTATION,AMAZON_DESTINATION_PERSIST_CONFIRMATION,AMAZON_DESTINATION_REVIEW_CONFIRMATION,ProductionFlatRetailerDestinationRepository,createRetailerDestination} from "../destinations/index.js";
import {FileSingleWriterRunLock} from "../runtime/FileSingleWriterRunLock.js";
import {createAmazonDestinationReviewRuntime} from "../../../scripts/mercury-amazon-destination-review-runtime.mjs";

const root=await mkdtemp(path.join(os.tmpdir(),"production-flat-destination-")),productionPath=new URL("../destinations/production-destinations.json",import.meta.url),queuePath=new URL("../../../.forge-review/mercury/amazon-destination-review-preparations.json",import.meta.url),readJson=async resource=>JSON.parse(await readFile(resource,"utf8")),products=new ProductRepository({readJson}),retailers=new RetailerRepository({readJson}),paths=[];
const fixture=async name=>{const dir=path.join(root,name),destination=path.join(dir,"destinations.json"),queue=path.join(dir,"preparations.json"),reviews=path.join(dir,"reviews.json");await mkdir(dir,{recursive:true});await copyFile(productionPath,destination);await copyFile(queuePath,queue);paths.push(dir);return{dir,destination,queue,reviews};};
const argsFor=value=>new Map([["--destination-state",value.destination],["--preparation-state",value.queue],["--review-state",value.reviews]]),load=async file=>JSON.parse(await readFile(file,"utf8"));
try{
 const main=await fixture("factory"),runtime=await createAmazonDestinationReviewRuntime(argsFor(main)),queue=await load(main.queue),preparations=[];for(const stored of queue.preparations){const current=await runtime.progressionService.prepare({atlasProductId:stored.atlasProductId,assessmentId:stored.assessmentId});assert.equal(current.preparationId,stored.preparationId);preparations.push(current);}assert.equal(preparations.length,5);assert.equal((await runtime.destinationRepository.getAll()).length,220);
 const approve=preparationId=>runtime.service.recordReview({preparationId,decision:"APPROVE",reviewedBy:"fixture:operator",reviewedAt:"2026-10-07T18:00:00.000Z",approvalAttestation:AMAZON_DESTINATION_APPROVAL_ATTESTATION,confirmation:AMAZON_DESTINATION_REVIEW_CONFIRMATION}),first=await approve(preparations[0].preparationId),second=await approve(preparations[1].preparationId);assert.equal(first.status,"RECORDED");assert.equal((await load(main.destination)).records.length,221);const persisted=await runtime.service.persist({reviewId:first.review.reviewId,executedBy:"fixture:operator",confirmation:AMAZON_DESTINATION_PERSIST_CONFIRMATION});assert.equal(persisted.status,"DESTINATION_CREATED");assert.equal((await load(main.destination)).records.length,222);await assert.rejects(()=>runtime.service.persist({reviewId:second.review.reviewId,executedBy:"fixture:operator",confirmation:AMAZON_DESTINATION_PERSIST_CONFIRMATION}),/PREPARATION_STALE/);
 const restarted=await createAmazonDestinationReviewRuntime(argsFor(main)),replay=await restarted.service.persist({reviewId:first.review.reviewId,executedBy:"fixture:operator",confirmation:AMAZON_DESTINATION_PERSIST_CONFIRMATION});assert.equal(replay.status,"ALREADY_BOUND");assert.equal((await load(main.destination)).records.length,222);assert.equal((await restarted.reviewRepository.getById(first.review.reviewId)).decision,"APPROVE");

 const collisionFixture=await fixture("collision"),collisionRuntime=await createAmazonDestinationReviewRuntime(argsFor(collisionFixture)),firstStored=queue.preparations[0],otherStored=queue.preparations[1],otherProduct=await products.getById(otherStored.atlasProductId),collision=createRetailerDestination({atlasProductId:otherStored.atlasProductId,retailerId:"RETAILER-0001",marketplace:"amazon.com",destinationType:"PRODUCT_PAGE",destinationUrl:firstStored.candidateUrl,retailerListingId:firstStored.asin,binding:{manufacturerPartNumber:otherProduct.identity.manufacturerPartNumber,method:"OPERATOR_EXACT_PRODUCT_REVIEW",scope:"EXACT_STANDALONE_PRODUCT",evidenceReferences:["fixture:cross-product"]},provenance:{sourceType:"OPERATOR_INSPECTED_PUBLIC_PAGE"},reviewedBy:"fixture:operator",reviewedAt:"2026-10-07T18:01:00.000Z",status:"ACTIVE",supersedesDestinationId:null,retirementReason:null,createdAt:"2026-10-07T18:01:00.000Z",createdBy:"fixture:operator"});await collisionRuntime.destinationRepository.retain(collision);await assert.rejects(()=>collisionRuntime.progressionService.prepare({atlasProductId:firstStored.atlasProductId,assessmentId:firstStored.assessmentId}),/CROSS_PRODUCT_COLLISION/);

 const supersessionFixture=await fixture("supersession"),supersessionRepository=new ProductionFlatRetailerDestinationRepository({statePath:supersessionFixture.destination,productRepository:products,retailerRepository:retailers}),source=await load(supersessionFixture.destination),predecessor=source.records[0],successor=createRetailerDestination({atlasProductId:predecessor.atlasProductId,retailerId:predecessor.retailerId,marketplace:predecessor.marketplace,destinationType:predecessor.destinationType,destinationUrl:`https://${predecessor.marketplace}/dp/TESTSUCCESSOR`,retailerListingId:"TESTSUCCESSOR",binding:{...predecessor.binding,evidenceReferences:[...predecessor.binding.evidenceReferences,"fixture:supersession"]},provenance:predecessor.provenance,reviewedBy:"fixture:operator",reviewedAt:"2026-10-07T18:02:00.000Z",status:"ACTIVE",supersedesDestinationId:predecessor.destinationId,retirementReason:null,createdAt:"2026-10-07T18:02:00.000Z",createdBy:"fixture:operator"});assert.equal((await supersessionRepository.retain(successor)).status,"RETAINED");assert.equal((await supersessionRepository.getAll()).length,220);

 const interrupted=await fixture("interrupted"),interruptedBefore=await readFile(interrupted.destination,"utf8"),baseFiles={readFile,writeFile,rm,mkdir,rename:async()=>{throw new Error("FIXTURE_RENAME_INTERRUPTED");}},interruptedRepository=new ProductionFlatRetailerDestinationRepository({statePath:interrupted.destination,productRepository:products,retailerRepository:retailers,fileOperations:baseFiles});await assert.rejects(()=>interruptedRepository.retain(collision),/FIXTURE_RENAME_INTERRUPTED/);assert.equal(await readFile(interrupted.destination,"utf8"),interruptedBefore);assert.equal((await readdir(interrupted.dir)).some(name=>name.includes(".tmp-")),false);

 const concurrent=await fixture("concurrent"),lock=new FileSingleWriterRunLock({lockPath:`${concurrent.destination}.lock`,heartbeatIntervalMs:100,staleAfterMs:1000}),held=await lock.acquire(),concurrentRepository=new ProductionFlatRetailerDestinationRepository({statePath:concurrent.destination,productRepository:products,retailerRepository:retailers,runLock:lock});await assert.rejects(()=>concurrentRepository.retain(collision),/REPOSITORY_BUSY/);await lock.release(held.owner.ownerId);assert.equal((await load(concurrent.destination)).records.length,221);

 const changedDuringCommit=await fixture("changed-during-commit"),changedSource=await readFile(changedDuringCommit.destination,"utf8");let reads=0;const conflictingFiles={readFile:async(...args)=>{reads+=1;if(reads===4)await writeFile(changedDuringCommit.destination,`${changedSource.trimEnd()}\n\n`,"utf8");return readFile(...args);},writeFile,rename,rm,mkdir},conflictingRepository=new ProductionFlatRetailerDestinationRepository({statePath:changedDuringCommit.destination,productRepository:products,retailerRepository:retailers,fileOperations:conflictingFiles});await assert.rejects(()=>conflictingRepository.retain(collision),/CONCURRENT_MUTATION/);assert.equal((await load(changedDuringCommit.destination)).records.length,221);assert.equal((await readdir(changedDuringCommit.dir)).some(name=>name.includes(".tmp-")),false);

 const malformed=await fixture("malformed");await writeFile(malformed.destination,JSON.stringify({schemaVersion:"1.0",records:{}}));const malformedRepository=new ProductionFlatRetailerDestinationRepository({statePath:malformed.destination,productRepository:products,retailerRepository:retailers});await assert.rejects(()=>malformedRepository.getAll(),/RETAILER_DESTINATION_SOURCE_INVALID:SCHEMA/);
 assert.equal((await load(productionPath)).records.length,221);
 console.log("Production flat retailer destination repository tests passed (factory, five reviews, approval, persistence, restart, replay, collision, supersession, stale, interrupted write, serialization, concurrent mutation, malformed source). ");
}finally{await rm(root,{recursive:true,force:true});}
