import assert from "node:assert/strict";
import {mkdtemp,rm,writeFile} from "node:fs/promises";
import os from "node:os";
import path from "node:path";
import {ProductionForgeAmazonDestinationReviewProvider} from "../operations/ProductionForgeAmazonDestinationReviewProvider.js";
import {CertifiedMercuryOperationsPanel} from "../../../apps/forge/components/CertifiedMercuryOperationsPanel.js";

const directory=await mkdtemp(path.join(os.tmpdir(),"forge-amazon-destination-")),statePath=path.join(directory,"queue.json");
const preparation=index=>({preparationId:`prep-${String(index).padStart(3,"0")}`,bindingDigest:`digest-${index}`,atlasProductId:`ram-${index}`,manufacturerPartNumber:`MPN-${index}`,asin:`B000000${index}`,candidateUrl:`https://amazon.com/dp/B000000${index}`,identityState:"STRONG_UNIQUE_ASIN",assessmentId:`assessment-${index}`,canonicalResultId:`result-${index}`,providerTaskId:`task-${index}`,sourceRightsProfileDigest:`rights-${index}`,collision:{productDestinationId:null,listingDestinationId:null,urlDestinationId:null,crossProductDestinationId:null},qualification:"ACTIONABILITY_REVIEW_REQUIRED",requiredReviewMethod:"OPERATOR_EXACT_PRODUCT_REVIEW"});
const source={schemaVersion:"1.0",artifactType:"AMAZON_DESTINATION_OPERATOR_REVIEW_QUEUE",policyVersion:"fixture-1",preparations:Array.from({length:5},(_,index)=>preparation(index+1)),networkOperation:"NONE",canonicalDestinationCreated:false};
await writeFile(statePath,JSON.stringify(source));
const current=new Map(source.preparations.map(item=>[item.atlasProductId,{...item,qualification:"ACTIONABILITY_REVIEW_REQUIRED"}])),reviews=new Map(),service={prepare:async({atlasProductId})=>structuredClone(current.get(atlasProductId)),async revalidatePreparation(stored){const fresh=await this.prepare({atlasProductId:stored.atlasProductId});if(fresh.bindingDigest!==stored.bindingDigest)throw new Error("AMAZON_DESTINATION_PREPARATION_STALE");return{status:"CURRENT",current:fresh};}},products={getById:async atlasProductId=>({identity:{atlasProductId,productType:"ram",brand:"Fixture",displayName:"Fixture 32 GB kit",series:null,modelName:"Fixture RAM",manufacturerPartNumber:atlasProductId},extension:{data:{classification:{memoryType:"DDR5",formFactor:"DIMM",buffering:"UNBUFFERED",eccType:"ON_DIE_ONLY",isKit:true},capacity:{capacityGb:32,moduleCount:2,capacityPerModuleGb:16},performance:{dataRateMtps:6000,casLatency:30,primaryTimings:"30-36-36-76"},electrical:{ratedVoltage:1.35},physical:{rgbLighting:false}}}})},reviewRepository={getByPreparationId:async id=>reviews.get(id)??null},provider=new ProductionForgeAmazonDestinationReviewProvider({preparationPath:statePath,progressionService:service,productRepository:products,reviewRepository});
let projection=await provider.load();assert.equal(projection.items.length,5);assert.equal(projection.counts.AWAITING_OPERATOR_REVIEW,5);assert.equal(projection.counts.APPROVED,0);assert.equal(projection.counts.REJECTED,0);assert.equal(projection.readOnly,true);assert.equal(projection.mutationAuthorized,false);assert.equal(projection.destinationPersistenceAuthority,false);assert.equal(projection.networkOperation,"NONE");assert.equal(projection.actualSpendUsd,0);assert.equal(JSON.stringify(projection).includes("password"),false);
assert.deepEqual(projection.items[0].productReviewContext,{category:"RAM",brand:"Fixture",canonicalProductName:"Fixture 32 GB kit",series:null,modelName:"Fixture RAM",manufacturerPartNumber:"ram-1",memoryGeneration:"DDR5",formFactor:"DIMM",totalCapacityGb:32,moduleCount:2,capacityPerModuleGb:16,ratedSpeedMtps:6000,casLatency:30,primaryTimings:"30-36-36-76",ratedVoltage:1.35,ecc:null,onDieEcc:true,buffering:"UNBUFFERED",rgb:false,kitSemantics:"KIT"});assert.equal(projection.items[0].asin,"B0000001");assert.equal(projection.items[0].operatorHandoff.actionExecutable,false);assert.equal(projection.items[0].operatorHandoff.rejectionReasons.length,6);
source.preparations.push(preparation(6));current.set("ram-6",{...preparation(6),qualification:"ACTIONABILITY_REVIEW_REQUIRED"});await writeFile(statePath,JSON.stringify(source));projection=await provider.load();assert.equal(projection.items.length,6);assert.equal(projection.counts.AWAITING_OPERATOR_REVIEW,6);reviews.set("prep-004",{reviewId:"review-4",decision:"APPROVE"});reviews.set("prep-005",{reviewId:"review-5",decision:"REJECT"});projection=await provider.load();assert.equal(projection.counts.APPROVED,1);assert.equal(projection.counts.REJECTED,1);
current.set("ram-1",{...preparation(1),bindingDigest:"changed",qualification:"ACTIONABILITY_REVIEW_REQUIRED"});current.set("ram-2",{...preparation(2),qualification:"ALREADY_BOUND"});service.prepare=async({atlasProductId})=>{if(atlasProductId==="ram-3")throw new Error("RIGHTS_BLOCKED");return structuredClone(current.get(atlasProductId));};projection=await provider.load();assert.equal(projection.counts.STALE,1);assert.equal(projection.counts.ALREADY_BOUND,1);assert.equal(projection.counts.BLOCKED,1);assert.equal(projection.counts.APPROVED,1);assert.equal(projection.counts.REJECTED,1);

class Element{constructor(){this.textContent="";this.className="";this.children=[];this.files=[];this.dataset={};this.value="";this.checked=false;this.disabled=false;this.listeners={};}addEventListener(name,listener){this.listeners[name]=listener;}replaceChildren(...children){this.children=children;}append(...children){this.children.push(...children);}querySelector(selector){return this.map?.[selector];}trigger(name){this.listeners[name]?.();}}
const root=new Element();root.map={"#certifiedMercuryProjectionFile":new Element(),"#certifiedMercuryProjectionStatus":new Element(),"#certifiedMercuryProjectionSummary":new Element(),"#certifiedMercuryProjectionAmazonDestinationReviewStatus":new Element(),"#certifiedMercuryProjectionAmazonDestinationReviews":new Element(),"#certifiedMercuryProjectionProducts":new Element(),"#certifiedMercuryProjectionDetails":new Element()};globalThis.document={createElement:()=>new Element()};
let copied="";Object.defineProperty(globalThis,"navigator",{value:{clipboard:{writeText:value=>{copied=value;}}},configurable:true});new CertifiedMercuryOperationsPanel(root).render({schemaVersion:"1.1",projectionType:"CERTIFIED_MERCURY_OPERATIONS_PROJECTION",readOnly:true,mutationAuthorized:false,networkOperation:"NONE",asOf:"2026-10-07T00:00:00.000Z",semantics:{canonicalOperationalView:true,historicalValueSemantics:"HISTORICAL_OBSERVATION",currentPrice:false,livePrice:false,publicPrice:false,publicationAuthority:false},summary:{},products:[],amazonDestinationReviewOperations:projection});assert.equal(root.map["#certifiedMercuryProjectionAmazonDestinationReviews"].children.length,6);assert.match(root.map["#certifiedMercuryProjectionAmazonDestinationReviewStatus"].textContent,/stale 1/);const card=root.map["#certifiedMercuryProjectionAmazonDestinationReviews"].children.find(value=>value.className.includes("review-approved")),productSection=card.children[1],identitySection=card.children[2],checklistSection=card.children[3],details=card.children[5];assert.match(productSection.children.map(value=>value.textContent).join(" "),/PRODUCT TO MATCH/);assert.match(JSON.stringify(projection.items[0]),/B0000001/);assert.equal(identitySection.children.at(-1).rel,"noopener noreferrer");assert.equal(identitySection.children.at(-1).textContent,"OPEN AMAZON PRODUCT PAGE");assert.equal(details.children[0].textContent,"Technical details");assert.equal(checklistSection.children.at(-1).textContent,"CHECKLIST INCOMPLETE");const awaitingCard=root.map["#certifiedMercuryProjectionAmazonDestinationReviews"].children.find(value=>value.className.includes("review-awaiting_operator_review")),awaitingChecks=awaitingCard.children[3].children.slice(1,-1).map(label=>label.children[0]),awaitingHandoff=awaitingCard.children[4],reviewer=awaitingHandoff.children[4].children[0],approval=awaitingHandoff.children[5],reason=awaitingHandoff.children[6],reject=awaitingHandoff.children[7];assert.equal(approval.disabled,true);reviewer.value="fixture:operator";reviewer.trigger("input");assert.equal(reject.disabled,false);reason.value="WRONG_PRODUCT";reject.trigger("click");assert.match(copied,/--decision=REJECT/);assert.match(copied,/WRONG_PRODUCT/);awaitingChecks.forEach(check=>{check.checked=true;check.trigger("change");});assert.equal(awaitingCard.children[3].children.at(-1).textContent,"REVIEW CHECKLIST COMPLETE");assert.equal(approval.disabled,false);approval.trigger("click");assert.match(copied,/I-ATTEST-EXACT-AMAZON-PRODUCT-PAGE-REVIEW/);assert.doesNotMatch(copied,/destination:persist/);assert.equal(reviews.size,2);
source.preparations=Array.from({length:200},(_,index)=>preparation(index+1));reviews.clear();for(const item of source.preparations)current.set(item.atlasProductId,{...item,qualification:"ACTIONABILITY_REVIEW_REQUIRED"});service.prepare=async({atlasProductId})=>structuredClone(current.get(atlasProductId));await writeFile(statePath,JSON.stringify(source));projection=await provider.load();assert.equal(projection.items.length,200);assert.equal(projection.counts.AWAITING_OPERATOR_REVIEW,200);
await rm(directory,{recursive:true,force:true});console.log("Production Forge Amazon destination review provider tests passed (22 cases).");
