import assert from "node:assert/strict";
import {mkdtemp,readFile,rm,writeFile} from "node:fs/promises";
import {join} from "node:path";
import {tmpdir} from "node:os";
import {createProductionProductsPrepareOwner,createProductionProductInfoPrepareOwner,createProductionSellersPrepareOwner,FileDataForSeoPrepareArtifactRepository,HistoricalBootstrapCheckpointService,projectHistoricalBootstrapCheckpoint,prepareDurableHistoricalBootstrapContinuation} from "../index.js";

const root=await mkdtemp(join(tmpdir(),"hr-h030-")),at="2026-09-11T14:00:00.000Z",intent="mer_histbootintent_"+"a".repeat(24),trusted={paidActionIntentId:intent,bootstrapCheckpointId:"cp1",bootstrapArtifactId:"artifact1",originatingCheckpointSequence:1,productIndex:0},executionRepository={getAll:async()=>[]};
try{
 const product={identity:{atlasProductId:"ram_fixture",manufacturerPartNumber:"MPN-1",recordRevision:1},governance:{lifecycleStatus:"ACTIVE",publicationStatus:"READY"}},atlas={products:{getAll:async()=>[product],getById:async()=>product}},productsPath=join(root,"products.json"),prepareArtifactRepository=new FileDataForSeoPrepareArtifactRepository({statePath:join(root,"prepare-artifacts.json")}),products=createProductionProductsPrepareOwner({atlas,executionRepository,prepareArtifactRepository,authorizationRequestPath:productsPath,now:()=>at}),ordinary=await products.prepare({atlasProductId:"ram_fixture"}),boot=await products.prepare({atlasProductId:"ram_fixture",trustedMetadata:trusted});
 assert.equal(ordinary.authorizationRequest.plan.decisions[0].execution.paidActionIntentId,undefined);assert.equal(boot.authorizationRequest.plan.decisions[0].execution.paidActionIntentId,intent);assert.equal(boot.reference.bootstrapCheckpointId,"cp1");assert.match(boot.reference.prepareArtifactId,/^mer_prepare_/);assert.equal((await prepareArtifactRepository.getById(boot.reference.prepareArtifactId)).authorizationRequestId,boot.authorizationRequest.requestId);assert.equal(boot.providerCalls,0);assert.equal(JSON.parse(await readFile(productsPath,"utf8")).requestId,boot.authorizationRequest.requestId);
 await assert.rejects(()=>products.prepare({atlasProductId:"ram_fixture",trustedMetadata:{...trusted,evil:"x"}}),/TRUSTED_METADATA_INVALID/);
 const piProposal={proposalId:"pi1",status:"PENDING_OPERATOR_REVIEW",operation:"PRODUCT_INFO",sourceTaskId:"task-products",atlasProductId:"ram_fixture",providerIdentity:{dataDocId:"doc1"},estimatedCostUsd:.001,maxPaidTasks:1,automaticPaidRetries:0},piEnvelope={sourceTaskId:"task-products",atlasProductId:"ram_fixture",proposal:piProposal,resolution:{recommendationStatus:"RECOMMENDED",recommendedCandidate:{item:{dataDocId:"doc1"}}},paidTaskCreated:false,actualSpendUsd:0},piPath=join(root,"pi.json");await writeFile(piPath,JSON.stringify(piEnvelope));const piOwner=createProductionProductInfoPrepareOwner({proposalEnvelopePath:piPath,executionRepository,now:()=>at}),piOrdinary=await piOwner.prepare(),pi=await piOwner.prepare({trustedMetadata:trusted});assert.equal(piOrdinary.authorizationRequest.paidActionIntentId,undefined);assert.equal(pi.authorizationRequest.paidActionIntentId,intent);assert.deepEqual(pi.authorizationRequest.bootstrapBinding,{checkpointId:"cp1",artifactId:"artifact1"});
 const sellerProposal={proposalId:"sp1",status:"PENDING_OPERATOR_REVIEW",operation:"SELLERS",atlasProductId:"ram_fixture",sourceProductsTaskId:"task-products",sourceProductInfoTaskId:"task-pi",sourceProductInfoAuthorizationId:"pi-auth",providerIdentity:{dataDocId:"doc1"},estimatedCostUsd:.001,maxPaidTasks:1,automaticPaidRetries:0},sellerPath=join(root,"seller.json");await writeFile(sellerPath,JSON.stringify({proposal:sellerProposal,paidTaskCreated:false,actualSpendUsd:0}));const sellerOwner=createProductionSellersPrepareOwner({proposalEnvelopePath:sellerPath,executionRepository,now:()=>at}),sellerOrdinary=await sellerOwner.prepare(),sellers=await sellerOwner.prepare({trustedMetadata:trusted});assert.equal(sellerOrdinary.authorizationRequest.paidActionIntentId,undefined);assert.equal(sellers.authorizationRequest.paidActionIntentId,intent);assert.deepEqual(sellers.authorizationRequest.bootstrapBinding,{checkpointId:"cp1",artifactId:"artifact1"});
 const binding={artifactId:"artifact1",artifactDigest:"a".repeat(64),asOf:at,sourceId:"DATAFORSEO_GOOGLE_SHOPPING",products:["ram_fixture"],taskCap:9,spendCapUsd:.009,utcDayCapUsd:.01},crypto=(await import("node:crypto")).default,stable=v=>Array.isArray(v)?`[${v.map(stable).join(",")}]`:v&&typeof v==="object"?`{${Object.keys(v).sort().map(k=>`${JSON.stringify(k)}:${stable(v[k])}`).join(",")}}`:JSON.stringify(v),checkpoint={schemaVersion:"1.0",checkpointId:"cp1",policyVersion:"MERCURY-HISTORY-022-1.0",binding,bindingDigest:crypto.createHash("sha256").update(stable(binding)).digest("hex"),createdAt:at,events:[{sequence:1,type:"CHECKPOINT_PREPARED",at,productIndex:0,atlasProductId:"ram_fixture",stage:"PRODUCTS"}]},projection=projectHistoricalBootstrapCheckpoint({checkpoint}),authorization=prepareDurableHistoricalBootstrapContinuation({projection,operation:"PRODUCTS",authorizedBy:"operator:test",reason:"fixture",authorizedAt:at,expiresAt:"2026-09-11T14:15:00Z",currentUtcDaySpendUsd:0}),prepared=await products.prepare({atlasProductId:"ram_fixture",trustedMetadata:{...trusted,paidActionIntentId:authorization.paidActionIntentId}}),events=[];
 const service=new HistoricalBootstrapCheckpointService({repository:{append:async(_id,event)=>({...checkpoint,events:[...checkpoint.events,{...event,sequence:2}]})},rightsRegistry:{get:()=>({acquisition:{api:"ALLOWED"}})},spendResolver:async()=>0,now:()=>at}),bound=await service.recordPreparedAction({checkpoint,authorization,prepared}),after=projectHistoricalBootstrapCheckpoint({checkpoint:bound});events.push(...bound.events);assert.equal(after.cohortState,"PREPARED_FOR_AUTHORIZATION");assert.equal(after.prepareReference.prepareArtifactId,prepared.reference.prepareArtifactId);assert.equal("plan" in after.prepareReference,false);
 await assert.rejects(()=>service.recordPreparedAction({checkpoint,authorization,prepared:{...prepared,reference:{...prepared.reference,atlasProductId:"other"}}}),/LINEAGE_CONFLICT/);await assert.rejects(()=>service.recordPreparedAction({checkpoint,authorization,prepared:{...prepared,reference:{...prepared.reference,prepareArtifactBindingDigest:"0".repeat(64)}}}),/DIGEST_MISMATCH/);
 console.log("Production DataForSEO PREPARE owner tests passed (18 cases).");
}finally{await rm(root,{recursive:true,force:true})}
