import assert from "node:assert/strict";
import crypto from "node:crypto";
import {mkdtemp,readFile,rm,writeFile} from "node:fs/promises";
import os from "node:os";
import path from "node:path";
import {createGovernedSelectedProductEnrichmentProposal,createManualProviderSelectionDecision,createProductInfoEnrichmentAuthorizationRequest,createProviderDocumentEquivalenceAssessment,deriveProviderDocumentEquivalenceGroups,extractReviewedProductEnrichmentProposal,FileProviderIdentityGovernanceRepository,prepareManualProviderSelection,projectProductsCheckpoint} from "../index.js";

const atlasProduct={identity:{atlasProductId:"ram_fixture",brand:"Kingston",manufacturerPartNumber:"KVR32N22D8/32",recordRevision:2},governance:{lifecycleStatus:"ACTIVE",publicationStatus:"READY",engineeringValidationStatus:"VALIDATED"},extension:{data:{classification:{memoryType:"DDR4",formFactor:"DIMM",moduleType:"UDIMM"},capacity:{capacityGb:32,moduleCount:1,capacityPerModuleGb:32},performance:{dataRateMtps:3200,casLatency:22},physical:{color:null,rgbLighting:false}}}};
const candidate=(title,dataDocId,productId=null,gid=null,extra={})=>({outcome:"RECOMMENDED",score:93,exactMpnMatch:true,contradictions:[],item:{title,dataDocId,productId,gid,...extra}});
const members=[candidate("Kingston KVR32N22D8/32 32GB DDR4-3200 1x32GB UDIMM CL22","doc-a","product-a","gid-a"),candidate("Kingston KVR32N22D8/32 32GB DDR4-3200 Memory","doc-b",null,"gid-b")];
const review={reviewId:"mer_productsreview_fixture",atlasProductId:"ram_fixture",providerTaskId:"products-task",identityState:"CONTRADICTED",materialDigest:"review-digest",resultIdentity:{recommendationStatus:"AMBIGUOUS",candidates:members}};
const at="2026-09-04T02:00:00.000Z";

const assessment=createProviderDocumentEquivalenceAssessment({atlasProduct,productsReview:review,assessedAt:at});
assert.equal(assessment.assessmentResult,"EQUIVALENCE_GROUPS_ESTABLISHED");assert.equal(assessment.groups.length,1);assert.equal(assessment.groups[0].members.length,2);assert.equal(assessment.selectedProviderIdentity,null);assert.notEqual(assessment.groups[0].members[0].providerIdentity.dataDocId,assessment.groups[0].members[1].providerIdentity.dataDocId);assert.equal(assessment.actualSpendUsd,0);assert.equal(assessment.grantsMarketAuthority,false);
const reordered=createProviderDocumentEquivalenceAssessment({atlasProduct,productsReview:{...review,resultIdentity:{...review.resultIdentity,candidates:[...members].reverse()}},assessedAt:at});
assert.equal(reordered.materialFingerprint,assessment.materialFingerprint);assert.equal(reordered.groups[0].groupDigest,assessment.groups[0].groupDigest);
for(const bad of [candidate("Replacement for Kingston KVR32N22D8/32 32GB DDR4","rep"),candidate("Used Kingston KVR32N22D8/32 32GB DDR4","used"),candidate("Kingston KVR32N22D8/32 32GB DDR4 motherboard bundle","bundle"),{...members[0],exactMpnMatch:false}, {...members[0],contradictions:["CAPACITY_CONFLICT"]}])assert.equal(deriveProviderDocumentEquivalenceGroups({atlasProduct,candidates:[bad]}).groups.filter(group=>group.length>1).length,0);
assert.equal(deriveProviderDocumentEquivalenceGroups({atlasProduct,candidates:[candidate("Kingston KVR32N22D8/32 32GB DDR4-3200 Black","black"),candidate("Kingston KVR32N22D8/32 32GB DDR4-3200 White","white")]}).groups.length,2);
const unknown=deriveProviderDocumentEquivalenceGroups({atlasProduct,candidates:[candidate("Kingston KVR32N22D8/32 32GB DDR4-3200","unknown")]}).assessed[0].evidence;assert.equal(unknown.condition,null);assert.equal(unknown.color,null);

const selected=assessment.groups[0].members[0].providerIdentity,request=prepareManualProviderSelection({assessment,selectedProviderIdentity:selected,preparedAt:at});
assert.equal(request.status,"PENDING_OPERATOR_CONFIRMATION");assert.match(request.confirmationRequired,/^SELECT-PROVIDER-/);assert.throws(()=>prepareManualProviderSelection({assessment,selectedProviderIdentity:{dataDocId:"outside"},preparedAt:at}),/OUTSIDE/);
assert.throws(()=>prepareManualProviderSelection({assessment,selectedProviderIdentity:selected,preparedAt:"<ISO_UTC>"}),/PREPARED_AT_INVALID/);assert.throws(()=>prepareManualProviderSelection({assessment:{...assessment,assessmentResult:"INVALID"},selectedProviderIdentity:selected,preparedAt:at}),/ASSESSMENT_INVALID/);
const decision=createManualProviderSelectionDecision({assessment,request,confirmation:request.confirmationRequired,operator:"operator:fixture",reason:"Select an exact equivalent document for downstream lineage.",selectedAt:at});
assert.equal(decision.decision,"SELECTED_PROVIDER_IDENTITY_FOR_DOWNSTREAM_LINEAGE");assert.equal(decision.eligibleProviderIdentities.length,2);assert.equal(decision.grantsPublicationAuthority,false);assert.equal(decision.grantsMarketAuthority,false);assert.throws(()=>createManualProviderSelectionDecision({assessment,request,confirmation:"WRONG",operator:"operator",reason:"reason",selectedAt:at}),/CONFIRMATION/);assert.throws(()=>createManualProviderSelectionDecision({assessment,request,confirmation:request.confirmationRequired,operator:"<OPERATOR>",reason:"reason",selectedAt:at}),/OPERATOR/);

const root=await mkdtemp(path.join(os.tmpdir(),"provider-governance-"));try{const statePath=path.join(root,"state.json"),repo=new FileProviderIdentityGovernanceRepository({statePath});assert.equal((await repo.persistAssessment(assessment)).status,"RECORDED");assert.equal((await repo.persistAssessment(assessment)).status,"DUPLICATE");assert.equal((await repo.persistRequest(request)).status,"RECORDED");assert.equal((await repo.persistDecision(decision)).status,"RECORDED");assert.equal((await repo.persistDecision(decision)).status,"DUPLICATE");const bytes=await readFile(statePath,"utf8");await assert.rejects(()=>repo.persistDecision({...decision,selectionDecisionId:"other",selectedProviderIdentity:assessment.groups[0].members[1].providerIdentity,fingerprint:"different"}),/CONFLICT/);assert.equal(await readFile(statePath,"utf8"),bytes);assert.deepEqual((await repo.getDecisionForAssessment(assessment.equivalenceAssessmentId)).selectedProviderIdentity,selected);const corrupt=JSON.parse(bytes);corrupt.assessments[assessment.equivalenceAssessmentId].canonicalMpn="OTHER";await writeFile(statePath,JSON.stringify(corrupt));await assert.rejects(()=>repo.getAssessment(assessment.equivalenceAssessmentId),/STATE_INVALID/);}finally{await rm(root,{recursive:true,force:true});}

const checkpoint={checkpointId:"checkpoint",products:[{atlasProductId:"ram_fixture"}]},projection=projectProductsCheckpoint({checkpoint,reviews:[{...review,checkpointId:"checkpoint"}],providerSelections:[decision]});assert.equal(projection.products[0].state,"READY_FOR_PRODUCT_INFO");
const stable=value=>Array.isArray(value)?`[${value.map(stable).join(',')}]`:value&&typeof value==='object'?`{${Object.keys(value).sort().map(key=>`${JSON.stringify(key)}:${stable(value[key])}`).join(',')}}`:JSON.stringify(value),fixtureAtlasDigest=crypto.createHash('sha256').update(stable({atlasProductId:"ram_fixture",manufacturerPartNumber:"KVR32N22D8/32",recordRevision:2,lifecycleStatus:"ACTIVE",publicationStatus:"READY",engineeringValidationStatus:"VALIDATED"})).digest('hex');
const checkpointProduct={atlasProductId:"ram_fixture",manufacturerPartNumber:"KVR32N22D8/32",atlasProductDigest:fixtureAtlasDigest},governedReview={...review,sourceRightsDigest:"rights-digest"},spend={currentUtcDaySpendUsd:.007,programSpendUsd:.007,remainingUtcDayCapacityUsd:.003,remainingProgramCapacityUsd:.022};
const proposal=createGovernedSelectedProductEnrichmentProposal({atlasProduct,productsReview:governedReview,equivalenceAssessment:assessment,selectionDecision:decision,checkpointProduct,sourceRightsDigest:"rights-digest",spend,createdAt:at});assert.deepEqual(proposal.providerIdentity,selected);assert.equal(proposal.providerSelectionLineage.equivalenceAssessmentId,assessment.equivalenceAssessmentId);assert.equal(proposal.governanceBinding.atlasProductDigest,fixtureAtlasDigest);assert.deepEqual(proposal.governanceBinding.providerRequest,{operation:"PRODUCT_INFO",...selected,locationName:"United States",languageName:"English"});assert.equal(proposal.paidExecutionAuthority,false);const authorization=createProductInfoEnrichmentAuthorizationRequest({proposal,createdAt:at,spentTodayUsd:.007});assert.deepEqual(authorization.providerSelectionLineage,proposal.providerSelectionLineage);assert.deepEqual(authorization.governanceBinding,proposal.governanceBinding);assert.equal(authorization.status,"PENDING_OPERATOR_APPROVAL");
assert.equal(extractReviewedProductEnrichmentProposal({sourceTaskId:proposal.sourceTaskId,atlasProductId:proposal.atlasProductId,proposal,providerSelectionDecision:decision,paidTaskCreated:false,actualSpendUsd:0}),proposal);
assert.throws(()=>createGovernedSelectedProductEnrichmentProposal({atlasProduct,productsReview:governedReview,equivalenceAssessment:assessment,selectionDecision:decision,checkpointProduct:{...checkpointProduct,atlasProductDigest:null},sourceRightsDigest:"rights-digest",spend,createdAt:at}),/GOVERNANCE_BINDING_INVALID/);

for(let index=0;index<5;index++){const weakReview={...review,reviewId:`weak-${index}`,atlasProductId:`weak-${index}`,resultIdentity:{recommendationStatus:"AMBIGUOUS",candidates:[{...members[0],exactMpnMatch:false,score:30}]}};const weakProduct={...atlasProduct,identity:{...atlasProduct.identity,atlasProductId:`weak-${index}`}};assert.equal(createProviderDocumentEquivalenceAssessment({atlasProduct:weakProduct,productsReview:weakReview,assessedAt:at}).groups.length,0);}
assert.equal(review.identityState,"CONTRADICTED");assert.equal(decision.actualSpendUsd,0);
for(const script of ["mercury-provider-equivalence-assess.mjs","mercury-provider-selection-prepare.mjs","mercury-provider-selection-execute.mjs","mercury-provider-selection-inspect.mjs","mercury-selected-product-info-prepare.mjs"]){const source=await readFile(new URL(`../../../scripts/${script}`,import.meta.url),"utf8");assert.doesNotMatch(source,/fetch\(|loadDataForSeoCredentials|\.env|createProductsTask|createProductInfoTask|createSellersTask/);}
console.log("Provider identity governance tests passed.");
