import assert from "node:assert/strict";
import {mkdtemp,rm} from "node:fs/promises";
import os from "node:os";
import path from "node:path";
import {createCurrentDisplaySnapshot,FileCurrentDisplaySnapshotRepository,projectLegacyCurrentOffer,createCurrentOfferProjection} from "../current-display/index.js";
import {createOperatorVerifiedLegacyOfferBinding,executeRakutenLegacyOfferRecovery,prepareRakutenLegacyOfferRecovery} from "../current-refresh/index.js";
let cases=0;const eq=(a,b)=>{assert.deepEqual(a,b);cases++;};
const preparedAt="2026-10-02T15:20:55.817Z",observedAt="2026-10-02T10:51:03.000Z";
const base=(id,price,seller,source,time="2026-10-01T02:00:00Z")=>({atlasProductId:id,retailer:"NEWEGG",retailerId:"RETAILER-0004",marketplace:"newegg.com",priceUsd:price,currency:"USD",availability:"AVAILABLE",condition:"NEW",shippingUsd:null,feesUsd:null,researchUrl:"https://newegg.com/p/FIXTURE",destinationId:`mer_dest_${(id.endsWith("a")?"a":"b").repeat(24)}`,matchStatus:"FIXTURE",sourceRow:1,observedAt:time,sellerName:seller,sourceIdentity:{adapterId:"fixture",sourceId:source,rightsProfileId:source,historicalRetentionAllowed:!source.includes("RAKUTEN")},itemPriceEligible:true,comparisonEligible:true,comparisonReasons:[],deliveredCostEligible:false,deliveredCostReasons:["UNKNOWN"]});
const crucial="ram_fixture_a",gskill="ram_fixture_b",legacy=projectLegacyCurrentOffer(base(crucial,430.6,"TECH_JUNKIE","MANUAL")),manualGskill=createCurrentOfferProjection({offer:base(gskill,586.98,"NEWEGG","MANUAL"),listingIdentity:"N82E16820374494"});
const source=createCurrentDisplaySnapshot({schemaVersion:"1.1",observedAt:"2026-10-01T02:15:00Z",importedAt:"2026-10-01T02:15:00Z",source:{workbook:"fixture",sheet:"fixture",digest:"a".repeat(64)},offers:[legacy,manualGskill]});
const binding=createOperatorVerifiedLegacyOfferBinding({sourceSnapshot:source,atlasProductId:crucial,legacyOfferIdentity:legacy.offerIdentity,listingIdentity:"9SIB3T1KSA7837",sellerName:"TECH_JUNKIE",verifiedBy:"operator:fixture",recordedAt:preparedAt,evidenceReferences:["fixture"]}),state={stateId:`rakuten_catalog_${"c".repeat(24)}`,stateDigest:"c".repeat(64)};
const incoming=(id,price,listing)=>({...base(id,price,null,"RAKUTEN_NEWEGG_PRODUCT_CATALOG",observedAt),listingIdentity:listing,conditionProvenance:{evidenceState:"CONTEXTUALLY_DERIVED"}});
const recovery=prepareRakutenLegacyOfferRecovery({sourceSnapshot:source,binding,incomingCrucial:incoming(crucial,439.12,"9SIB3T1KSA7837"),incomingGSkill:incoming(gskill,588.08,"9SIA1K6KCT0998"),retainedRakutenState:state,retainedDeltaDigest:"d".repeat(64),preparedAt,unresolvedMultiItem:{classification:"IDENTITY_REVIEW_REQUIRED"},sourceWithdrawal:{canonicalOfferRemoved:false}});
const root=await mkdtemp(path.join(os.tmpdir(),"current-recovery-execute-"));try{const snapshots=new FileCurrentDisplaySnapshotRepository({statePath:path.join(root,"current.json")});await snapshots.replace(source);const confirmation=`EXECUTE-RAKUTEN-CURRENT-RECOVERY:${recovery.plan.planId}:${recovery.plan.preparationIds.join(":")}`,input={plan:recovery.plan,preparations:recovery.preparations,currentSnapshotRepository:snapshots,retainedRakutenState:state,authorizedPlanId:recovery.plan.planId,authorizedPreparationIds:recovery.plan.preparationIds,confirmation};const first=await executeRakutenLegacyOfferRecovery(input);eq(first.status,"EXECUTED");eq(first.offerCount,3);let loaded=(await new FileCurrentDisplaySnapshotRepository({statePath:path.join(root,"current.json")}).getState()).current;eq(loaded.snapshotId,recovery.plan.proposedSnapshotId);eq(loaded.offers.filter(x=>x.atlasProductId===crucial).length,1);eq(loaded.offers.find(x=>x.atlasProductId===crucial).seller.sellerName,"TECH_JUNKIE");eq(loaded.offers.filter(x=>x.atlasProductId===gskill).length,2);const replay=await executeRakutenLegacyOfferRecovery({...input,currentSnapshotRepository:new FileCurrentDisplaySnapshotRepository({statePath:path.join(root,"current.json")})});eq(replay.status,"ALREADY_EXECUTED");eq((await snapshots.getState()).current.snapshotId,loaded.snapshotId);await assert.rejects(()=>executeRakutenLegacyOfferRecovery({...input,authorizedPreparationIds:[recovery.plan.preparationIds[0],"wrong"]}),/AUTHORIZATION_SCOPE_INVALID/);cases++;}finally{await rm(root,{recursive:true,force:true});}
console.log(`Rakuten legacy offer recovery execution tests passed: ${cases} cases.`);
