import assert from "node:assert/strict";
import { prepareRakutenFullCurrentRefresh, prepareRakutenFullCurrentRefreshPlan } from "../current-refresh/index.js";

const offer=(identity,price,overrides={})=>({offerIdentity:identity,identityMode:"EVIDENCE_GROUNDED",atlasProductId:"ram_fixture",retailerId:"RETAILER-0004",destinationId:"mer_dest_fixture",priceUsd:price,...overrides});
const source={schemaVersion:"1.1",snapshotId:"mer_display_source",materialFingerprint:"a".repeat(64),offers:[offer("mer_offer_legacy",100,{identityMode:"LEGACY_PRODUCT_CHANNEL"}),offer("mer_offer_unchanged",80,{atlasProductId:"ram_other"})]},proposed={schemaVersion:"1.1",snapshotId:"mer_display_proposed",materialFingerprint:"b".repeat(64),offers:[offer("mer_offer_evidence",100),offer("mer_offer_unchanged",80,{atlasProductId:"ram_other"})]},catalog={stateId:"rakuten_catalog_fixture",stateDigest:"c".repeat(64),catalogDigest:"d".repeat(64),artifact:{digest:"e".repeat(64),headerTimestamp:"2026-10-02T10:54:14.000Z",remoteModifiedAt:"2026-10-02T14:59:55.000Z"},recordCount:1065223},result={mode:"DRY_RUN",summary:{routineCurrentUpdates:1},rowAssessments:[],outcomes:[],exceptions:[]};
const plan=prepareRakutenFullCurrentRefreshPlan({sourceSnapshot:source,proposedSnapshot:proposed,catalogManifest:catalog,result,preparedAt:"2026-10-02T17:53:23.647Z"});
assert.equal(plan.diff.added.length,0);assert.equal(plan.diff.withdrawn.length,0);assert.equal(plan.diff.updated.length,1);assert.equal(plan.diff.updated[0].progression,"LEGACY_TO_EVIDENCE_GROUNDED");assert.equal(plan.diff.unchanged.length,1);assert.equal(plan.authority,"NONE");assert.equal(plan.currentMutationAuthorized,false);assert.equal(plan.historyEligibility,false);assert.equal(plan.sourceCatalog.headerTimestamp,"2026-10-02T10:54:14.000Z");assert.equal(plan.sourceCatalog.remoteModifiedAt,"2026-10-02T14:59:55.000Z");
const preparation=prepareRakutenFullCurrentRefresh({plan});assert.equal(preparation.members.length,1);assert.equal(preparation.members[0].change,"UPDATE");assert.equal(preparation.networkOperation,"NONE");assert.equal(preparation.currentMutationAuthorized,false);assert.equal(preparation.historyEligibility,false);assert.equal(preparation.providerCalls,0);assert.equal(preparation.actualSpendUsd,0);
console.log("Rakuten fresh FULL Current plan tests passed: 18 cases.");
