import assert from "node:assert/strict";
import { gzipSync } from "node:zlib";
import { EventEmitter } from "node:events";
import { mkdtemp, readFile, readdir, rm, writeFile } from "node:fs/promises";
import os from "node:os";
import path from "node:path";
import { classifyNativeSftpFailure, classifyRakutenFeedFile, compareRakutenRemoteTimestamp, createRakutenSftpConnectionAccounting, loadRakutenSftpConfig, NativeSftpSession, normalizeRakutenRemoteEntry, RakutenProductCatalogSftpTransport, readRakutenSftpHostTrust, redactRakutenSftpError, selectRakutenNeweggMainDelta, summarizeRakutenSftpDiscovery } from "../current-display/index.js";
import { fixtureFeedText, sanitizedCases } from "./fixtures/rakuten-newegg/sanitized-feed-fixtures.js";

let cases=0;
const secret="fixture-password-never-log", username="fixture-user";
const config=loadRakutenSftpConfig({RAKUTEN_SFTP_USERNAME:username,RAKUTEN_SFTP_PASSWORD:secret});
assert.deepEqual({protocol:config.protocol,host:config.host,port:config.port,connections:config.concurrency},{protocol:"SFTP",host:"aftp.linksynergy.com",port:22,connections:1});
assert.doesNotMatch(JSON.stringify(config),new RegExp(`${secret}|${username}`)); cases++;
assert.throws(()=>loadRakutenSftpConfig({}),/SFTP_CONFIG_MISSING/); assert.throws(()=>loadRakutenSftpConfig({RAKUTEN_SFTP_USERNAME:"u",RAKUTEN_SFTP_PASSWORD:"p",RAKUTEN_SFTP_CONNECTIONS:"6"}),/CONNECTION_LIMIT/); assert.throws(()=>loadRakutenSftpConfig({RAKUTEN_SFTP_USERNAME:"u",RAKUTEN_SFTP_PASSWORD:"p",RAKUTEN_SFTP_HOST:"wrong.example"}),/CONFIG_INVALID/); cases++;
const redacted=redactRakutenSftpError(new Error(`auth ${username} password=${secret}`),[username,secret]); assert.doesNotMatch(redacted.message,new RegExp(`${secret}|${username}`)); cases++;
assert.equal(classifyNativeSftpFailure(Object.assign(new Error("Authentication failed"),{level:"client-authentication"})),"SFTP_AUTH_FAILED");assert.equal(classifyNativeSftpFailure(Object.assign(new Error(),{code:"ETIMEDOUT"})),"SFTP_CONNECT_TIMEOUT");assert.equal(classifyNativeSftpFailure(Object.assign(new Error(),{code:"ECONNREFUSED"})),"SFTP_CONNECT_REFUSED");assert.equal(classifyNativeSftpFailure(Object.assign(new Error(),{code:"ENOTFOUND"})),"SFTP_DNS_FAILED");assert.equal(classifyNativeSftpFailure(new Error("key rejected"),{hostMismatch:true}),"SFTP_HOST_VERIFICATION_FAILED");cases++;

const keyBlob=type=>{const name=Buffer.from(type),length=Buffer.alloc(4);length.writeUInt32BE(name.length);return Buffer.concat([length,name,Buffer.from("fixture-key-material")]);};
const trustedKey=keyBlob("ssh-ed25519"),changedKey=keyBlob("ssh-rsa");
class FakeClient extends EventEmitter{
 constructor({key=trustedKey,connectError=null,sftpError=null,sftp={},closeEvent="close"}={}){super();this.key=key;this.connectError=connectError;this.sftpError=sftpError;this.sftpValue=sftp;this.closeEvent=closeEvent;this.connectCalls=0;this.endCalls=0;this.destroyCalls=0;this.options=null;}
 connect(options){this.connectCalls++;this.options=options;queueMicrotask(()=>{if(this.connectError)return this.emit("error",this.connectError);if(!options.hostVerifier(this.key))return this.emit("error",new Error("host rejected"));this.emit("ready");});}
 sftp(callback){queueMicrotask(()=>callback(this.sftpError,this.sftpValue));}
 end(){this.endCalls++;if(this.closeEvent)queueMicrotask(()=>this.emit(this.closeEvent));}
 destroy(){this.destroyCalls++;this.emit("close");}
}
const nativeRoot=await mkdtemp(path.join(os.tmpdir(),"hr native sftp "));
try{
 const knownHosts=path.join(nativeRoot,"known_hosts"),missingTrust=path.join(nativeRoot,"missing_known_hosts");
 await writeFile(knownHosts,`aftp.linksynergy.com ssh-ed25519 ${trustedKey.toString("base64")}\n`);
 const trust=await readRakutenSftpHostTrust({knownHostsPath:knownHosts,host:config.host,port:22});assert.equal(trust.status,"TRUSTED");assert.equal(trust.digests.length,1);cases++;
 const attrs={size:5,mtime:1788915600,isDirectory:()=>false,isFile:()=>true},downloaded=Buffer.from([0,1,2,3,255]),fakeSftp={endCalls:0,end(){this.endCalls++;},readdir:(remote,callback)=>callback(null,[{filename:"fixture.gz",longname:"-rw-r--r-- fixture.gz",attrs}]),stat:(remote,callback)=>callback(null,attrs),fastGet:(remote,local,callback)=>writeFile(local,downloaded).then(()=>callback(),callback)};
 const client=new FakeClient({sftp:fakeSftp}),session=new NativeSftpSession({config,knownHostsPath:knownHosts,clientFactory:()=>client});await session.connect();assert.equal(client.connectCalls,1);assert.equal(client.options.password,secret);assert.equal(client.options.username,username);assert.equal(JSON.stringify(client.options).includes(secret),true);const listed=await session.list("/44583/");assert.equal(listed[0].filename,"fixture.gz");assert.equal(listed[0].remoteTimestampSourceSeconds,1788915600);assert.equal(listed[0].modifiedAt,"2026-09-09T01:00:00.000Z");const stated=await session.stat("/44583/fixture.gz");assert.deepEqual(stated,listed[0]);const local=path.join(nativeRoot,"binary.gz");await session.download("/44583/fixture.gz",local);assert.deepEqual(await readFile(local),downloaded);await session.close();assert.equal(fakeSftp.endCalls,1);assert.equal(client.endCalls,1);assert.deepEqual(session.connectionAccounting(),{connectionsOpened:1,connectionsReady:1,connectionsClosedGracefully:1,connectionsDestroyedAsFallback:0,connectionsFailedBeforeReady:0,cleanupAttempts:1,cleanupFailures:0,activeConnectionsAtStart:0,activeConnectionsAtEnd:0,peakLocalConcurrentConnections:1});cases++;
 const rootNames=["44583","ADDITIONAL","GLOBAL","44583_4746097_mp.txt.gz","44583_4746097_mp_delta.txt.gz","44583_4746097_mp_deltatemplate.txt.gz","44583_4746097_mp_template.txt.gz"],rootSftp={readdir:(remote,callback)=>callback(null,rootNames.map((filename,index)=>({filename,longname:`fixture ${filename}`,attrs:{size:index<3?0:100,mtime:1788915600,mode:index<3?0o040755:0o100644,isDirectory(){return (this.mode&0o170000)===0o040000;},isFile(){return (this.mode&0o170000)===0o100000;}}})))};const rootClient=new FakeClient({sftp:rootSftp}),rootSession=new NativeSftpSession({config,knownHostsPath:knownHosts,clientFactory:()=>rootClient});await rootSession.connect();const normalizedRoot=(await rootSession.list("/")).map(entry=>normalizeRakutenRemoteEntry(entry,"/"));await rootSession.close();assert.equal(normalizedRoot.filter(item=>item.fileType==="DIRECTORY").length,3);assert.equal(normalizedRoot.filter(item=>item.fileType==="REGULAR_FILE").length,4);assert.equal(selectRakutenNeweggMainDelta(normalizedRoot).filename,"44583_4746097_mp_delta.txt.gz");cases++;
 const modeOnlySftp={readdir:(remote,callback)=>callback(null,[{filename:"mode-only.txt",attrs:{mode:0o100644,size:1,mtime:0}},{filename:"mode-directory",attrs:{mode:0o040755}},{filename:"no-attrs"}])},modeClient=new FakeClient({sftp:modeOnlySftp}),modeSession=new NativeSftpSession({config,knownHostsPath:knownHosts,clientFactory:()=>modeClient});await modeSession.connect();const modeEntries=(await modeSession.list("/")).map(entry=>normalizeRakutenRemoteEntry(entry,"/"));await modeSession.close();assert.equal(modeEntries[0].fileType,"REGULAR_FILE");assert.equal(modeEntries[0].remoteTimestampUtc,"1970-01-01T00:00:00.000Z");assert.equal(modeEntries[1].fileType,"DIRECTORY");assert.equal(modeEntries[1].remoteTimestampUtc,null);assert.equal(modeEntries[2].fileType,"OTHER");cases++;
 const mismatch=new FakeClient({key:changedKey});await assert.rejects(()=>new NativeSftpSession({config,knownHostsPath:knownHosts,clientFactory:()=>mismatch}).connect(),/SFTP_HOST_VERIFICATION_FAILED/);assert.equal(mismatch.endCalls,1);cases++;
 await assert.rejects(()=>new NativeSftpSession({config,knownHostsPath:missingTrust,trustOnFirstUse:false,clientFactory:()=>new FakeClient()}).connect(),/SFTP_HOST_VERIFICATION_REQUIRED/);cases++;
 const tofuClient=new FakeClient(),tofu=new NativeSftpSession({config,knownHostsPath:missingTrust,trustOnFirstUse:true,clientFactory:()=>tofuClient});await tofu.connect();await tofu.close();const migrated=await readRakutenSftpHostTrust({knownHostsPath:missingTrust,host:config.host,port:22});assert.equal(migrated.status,"TRUSTED");cases++;
 const authClient=new FakeClient({connectError:Object.assign(new Error(`Authentication failed password=${secret}`),{level:"client-authentication"})}),authSession=new NativeSftpSession({config,knownHostsPath:knownHosts,clientFactory:()=>authClient});await assert.rejects(()=>authSession.connect(),/SFTP_AUTH_FAILED/);assert.equal(authClient.endCalls,1);assert.equal(authSession.connectionAccounting().connectionsFailedBeforeReady,1);assert.equal(authSession.connectionAccounting().activeConnectionsAtEnd,0);cases++;
 const hangingClient=new FakeClient({sftp:fakeSftp,closeEvent:null}),hanging=new NativeSftpSession({config,knownHostsPath:knownHosts,clientFactory:()=>hangingClient,cleanupTimeoutMs:5});await hanging.connect();const firstClose=await hanging.close(),secondClose=await hanging.close();assert.equal(hangingClient.endCalls,1);assert.equal(hangingClient.destroyCalls,1);assert.equal(firstClose.connectionsDestroyedAsFallback,1);assert.deepEqual(secondClose,firstClose);assert.equal(firstClose.activeConnectionsAtEnd,0);cases++;
 const failingSftp={readdir:(remote,callback)=>callback(new Error("remote status 4")),stat:(remote,callback)=>callback(new Error("stat failed")),fastGet:(remote,local,callback)=>callback(new Error("download failed"))};
 for(const [method,args,code] of [["list",["/"],"SFTP_LIST_FAILED"],["stat",["/x"],"SFTP_LIST_FAILED"],["download",["/x",path.join(nativeRoot,"x")],"SFTP_DOWNLOAD_FAILED"]]){const failureClient=new FakeClient({sftp:failingSftp}),failureSession=new NativeSftpSession({config,knownHostsPath:knownHosts,clientFactory:()=>failureClient});await failureSession.connect();await assert.rejects(()=>failureSession[method](...args),new RegExp(code));await failureSession.close();assert.equal(failureClient.endCalls,1);assert.equal(failureSession.connectionAccounting().activeConnectionsAtEnd,0);}cases++;
 for(const [status,category] of [[2,"PATH_NOT_FOUND"],[3,"PERMISSION_DENIED"],[4,"SERVER_FAILURE"],[8,"UNKNOWN_LIST_FAILURE"]]){const statusSftp={readdir:(remote,callback)=>callback(Object.assign(new Error("unsafe server text"),{code:status}))},statusClient=new FakeClient({sftp:statusSftp}),statusSession=new NativeSftpSession({config,knownHostsPath:knownHosts,clientFactory:()=>statusClient});await statusSession.connect();await assert.rejects(()=>statusSession.list("/"),cause=>cause.code==="SFTP_LIST_FAILED"&&cause.sftpStatusCode===status&&cause.sftpStatusCategory===category&&!cause.message.includes("server text"));await statusSession.close();}cases++;
 const routineRegistry={active:1},routineAccounting=createRakutenSftpConnectionAccounting({registry:routineRegistry});assert.throws(()=>routineAccounting.reserve(),/SFTP_LOCAL_CONNECTION_ACTIVE/);assert.equal(routineRegistry.active,1);
 const capRegistry={active:5},capAccounting=createRakutenSftpConnectionAccounting({registry:capRegistry,routineLimit:5,hardLimit:5});assert.throws(()=>capAccounting.reserve(),/SFTP_CONNECTION_HARD_LIMIT_REACHED/);assert.equal(capRegistry.active,5);cases++;
}finally{await rm(nativeRoot,{recursive:true,force:true});}

const metadata=(filename,size=100)=>({filename,size,remoteTimestampSourceSeconds:1788915600,modifiedAt:"2026-09-09T01:00:00.000Z",isDirectory:false,isFile:true});
assert.equal(classifyRakutenFeedFile({remotePath:"/44583/a_mp_delta.txt.gz",filename:"a_mp_delta.txt.gz"}),"DELTA");
assert.equal(classifyRakutenFeedFile({remotePath:"/44583/a_mp.txt.gz",filename:"a_mp.txt.gz"}),"FULL");
assert.equal(classifyRakutenFeedFile({remotePath:"/44583/a_mp_template.txt.gz",filename:"a_mp_template.txt.gz"}),"TEMPLATE");
assert.equal(classifyRakutenFeedFile({remotePath:"/44583/a_mp_deltatemplate.txt.gz",filename:"a_mp_deltatemplate.txt.gz"}),"DELTA_TEMPLATE");
assert.equal(classifyRakutenFeedFile({remotePath:"/ADDITIONAL/44583/a_mp_delta.txt.gz",filename:"a_mp_delta.txt.gz"}),"ADDITIONAL");
assert.equal(classifyRakutenFeedFile({remotePath:"/GLOBAL/a_mp_delta.txt.gz",filename:"a_mp_delta.txt.gz"}),"GLOBAL"); cases++;
assert.throws(()=>selectRakutenNeweggMainDelta([]),/NOT_FOUND/); cases++;
const realisticRootRaw=[{filename:"44583",size:null,modifiedAt:null,isDirectory:true,isFile:false},{filename:"ADDITIONAL",size:null,modifiedAt:null,isDirectory:true,isFile:false},{filename:"GLOBAL",size:null,modifiedAt:null,isDirectory:true,isFile:false},{filename:".",size:null,modifiedAt:null,isDirectory:true,isFile:false},{filename:"..",size:null,modifiedAt:null,isDirectory:true,isFile:false},{filename:"feed-link",size:null,modifiedAt:null,isDirectory:false,isFile:false},{filename:"operator note.txt",size:5,modifiedAt:null,isDirectory:false,isFile:true},metadata("44583_4746097_mp.txt.gz"),metadata("44583_4746097_mp_delta.txt.gz"),metadata("44583_4746097_mp_deltatemplate.txt.gz"),metadata("44583_4746097_mp_template.txt.gz")];
const realisticRoot=realisticRootRaw.map(entry=>normalizeRakutenRemoteEntry(entry,"/")),realisticSelected=selectRakutenNeweggMainDelta(realisticRoot);assert.equal(realisticSelected.filename,"44583_4746097_mp_delta.txt.gz");assert.equal(realisticSelected.publisherSid,"4746097");assert.equal(realisticSelected.remotePath,"/44583_4746097_mp_delta.txt.gz");assert.equal(realisticSelected.remoteTimestampSourceSeconds,1788915600);assert.equal(realisticSelected.remoteTimestampUtc,"2026-09-09T01:00:00.000Z");assert.equal(realisticSelected.format,"TXT");assert.equal(realisticSelected.compression,"GZIP");assert.deepEqual(summarizeRakutenSftpDiscovery(realisticRoot),{logicalDirectory:"ROOT",entriesObserved:11,directoriesObserved:3,regularFilesObserved:5,otherEntries:1,ignoredSpecialEntries:2,malformedEntries:0,recognizedFeedFiles:4,mainDeltaCandidates:1,targetMid:"44583",recognizedEntries:["44583","ADDITIONAL","GLOBAL","44583_4746097_mp.txt.gz","44583_4746097_mp_delta.txt.gz","44583_4746097_mp_deltatemplate.txt.gz","44583_4746097_mp_template.txt.gz"]});cases++;
assert.equal(compareRakutenRemoteTimestamp({currentTimestamp:"2026-09-09T01:00:00-05:00",previousTimestamp:"2026-09-09T06:00:00Z"}),"UNCHANGED");assert.equal(compareRakutenRemoteTimestamp({currentTimestamp:"2026-09-09T06:00:01Z",previousTimestamp:"2026-09-09T06:00:00Z"}),"NEWER");assert.equal(compareRakutenRemoteTimestamp({currentTimestamp:"2026-09-09T05:59:59Z",previousTimestamp:"2026-09-09T06:00:00Z"}),"OLDER_OR_REGRESSED");assert.equal(compareRakutenRemoteTimestamp({currentTimestamp:"malformed",previousTimestamp:"2026-09-09T06:00:00Z"}),"UNKNOWN");assert.equal(compareRakutenRemoteTimestamp({currentEntry:{filename:"same.gz",size:999,remoteTimestampUtc:"2026-09-09T06:00:01Z"},previousEntry:{filename:"same.gz",size:1,remoteTimestampUtc:"2026-09-09T06:00:00Z"}}),"NEWER");assert.equal(compareRakutenRemoteTimestamp({currentEntry:{filename:"new-name.gz",size:999,remoteTimestampUtc:"2026-09-09T06:00:00Z"},previousEntry:{filename:"old-name.gz",size:1,remoteTimestampUtc:"2026-09-09T06:00:00Z"}}),"UNCHANGED");assert.throws(()=>normalizeRakutenRemoteEntry({...metadata("44583_4746097_mp_delta.txt.gz"),modifiedAt:null},"/"),/SFTP_LIST_ENTRY_INVALID/);cases++;
const feedNamedOther=normalizeRakutenRemoteEntry({...metadata("44583_9000001_mp_delta.txt.gz"),isFile:false},"/");assert.equal(feedNamedOther.fileType,"OTHER");assert.throws(()=>selectRakutenNeweggMainDelta([feedNamedOther]),/SFTP_FILE_NOT_FOUND/);assert.throws(()=>normalizeRakutenRemoteEntry({filename:null,size:1},"/"),/SFTP_LIST_ENTRY_INVALID/);assert.throws(()=>normalizeRakutenRemoteEntry({...metadata("safe.txt"),attributeShapeValid:false},"/"),/SFTP_LIST_ENTRY_INVALID/);cases++;
const alternateSid=realisticRoot.map(item=>item.filename.includes("4746097")?normalizeRakutenRemoteEntry({...metadata(item.filename.replace("4746097","9000001"))},"/"):item);assert.equal(selectRakutenNeweggMainDelta(alternateSid).publisherSid,"9000001");cases++;
for(const code of ["SFTP_FILE_NOT_FOUND","SFTP_FILE_AMBIGUOUS","SFTP_LIST_FAILED"]){const safe=redactRakutenSftpError(new Error(code));assert.equal(safe.code,code);assert.equal(safe.message,code);}assert.equal(redactRakutenSftpError(new Error("unsafe raw failure")).code,"SFTP_OPERATION_FAILED");cases++;

const root=await mkdtemp(path.join(os.tmpdir(),"hr-rakuten-sftp-")), staging=path.join(root,".forge-review","rakuten-sftp");
const bytes=gzipSync(Buffer.from(fixtureFeedText({rows:[sanitizedCases.insertedRam,sanitizedCases.updatedRam,sanitizedCases.deletedRam]})));
const listings={"/":realisticRootRaw.map(item=>item.filename==="44583_4746097_mp_delta.txt.gz"?metadata(item.filename,bytes.length):item),"/44583/":[],"/ADDITIONAL/44583/":[metadata("44583_7000000_mp_delta.txt.gz")],"/GLOBAL/":[metadata("global.txt.gz")]};
const tracker={connections:0,closes:0,downloads:0,listCalls:[]};
const factory=({payload=bytes,failConnect=false,listingsOverride=listings,listError=null,listErrors={}}={})=>({connectionAccounting})=>{let closed=false;return {secrets:[username,secret],connect:async()=>{connectionAccounting.reserve();tracker.connections++;if(failConnect)throw new Error(`bad ${secret}`);connectionAccounting.markReady();},list:async dir=>{tracker.listCalls.push(dir);if(listErrors[dir])throw listErrors[dir];if(listError)throw listError;return structuredClone(listingsOverride[dir]??[]);},download:async(remote,local)=>{tracker.downloads++;assert.equal(remote,"/44583_4746097_mp_delta.txt.gz");await writeFile(local,payload);},close:async()=>{if(closed)return;closed=true;tracker.closes++;if(connectionAccounting.beginCleanup())connectionAccounting.release();},connectionAccounting:()=>connectionAccounting.snapshot()};};
const pathFailure=(category,statusCode)=>Object.assign(new Error("SFTP_LIST_FAILED"),{code:"SFTP_LIST_FAILED",sftpStatusCategory:category,sftpStatusCode:statusCode});
try{
 const inspectTransport=new RakutenProductCatalogSftpTransport({sessionFactory:factory(),stagingRoot:staging});
 const inspected=await inspectTransport.inspect(); assert.equal(inspected.status,"INSPECTED");assert.deepEqual(inspected.directoryListings.map(item=>item.outcome),["SUCCESS","SUCCESS","SUCCESS","SUCCESS"]);assert.equal(inspected.selected.feedFamily,"DELTA");assert.equal(inspected.selected.filename,"44583_4746097_mp_delta.txt.gz");assert.equal(inspected.discovery.mainDeltaCandidates,1); assert.equal(inspected.downloaded,false); assert.equal(tracker.downloads,0); assert.equal(inspected.connectionsUsed,1);assert.deepEqual(inspected.connectionAccounting,{connectionsOpened:1,connectionsReady:1,connectionsClosedGracefully:1,connectionsDestroyedAsFallback:0,connectionsFailedBeforeReady:0,cleanupAttempts:1,cleanupFailures:0,activeConnectionsAtStart:0,activeConnectionsAtEnd:0,peakLocalConcurrentConnections:1}); cases++;
 const optionalCases=[{path:"/GLOBAL/",failure:pathFailure("SERVER_FAILURE",4)},{path:"/ADDITIONAL/44583/",failure:pathFailure("PATH_NOT_FOUND",2)},{path:"/44583/",failure:pathFailure("PERMISSION_DENIED",3)}];for(const scenario of optionalCases){const beforeConnections=tracker.connections,result=await new RakutenProductCatalogSftpTransport({sessionFactory:factory({listErrors:{[scenario.path]:scenario.failure}}),stagingRoot:staging}).inspect(),outcome=result.directoryListings.find(item=>item.remotePath===scenario.path);assert.equal(result.status,"SFTP_INSPECTION_PARTIAL");assert.equal(result.selected.filename,"44583_4746097_mp_delta.txt.gz");assert.equal(result.selected.remoteTimestampUtc,"2026-09-09T01:00:00.000Z");assert.equal(outcome.outcome,scenario.failure.sftpStatusCategory);assert.equal(outcome.sftpStatusCode,scenario.failure.sftpStatusCode);assert.equal(tracker.connections,beforeConnections+1);assert.equal(result.connectionAccounting.connectionsOpened,1);assert.equal(result.connectionAccounting.activeConnectionsAtEnd,0);}cases++;
 const multiplePartial=await new RakutenProductCatalogSftpTransport({sessionFactory:factory({listErrors:{"/44583/":pathFailure("SERVER_FAILURE",4),"/ADDITIONAL/44583/":pathFailure("PATH_NOT_FOUND",2),"/GLOBAL/":pathFailure("PERMISSION_DENIED",3)}}),stagingRoot:staging}).inspect();assert.equal(multiplePartial.status,"SFTP_INSPECTION_PARTIAL");assert.equal(multiplePartial.directoryListings.filter(item=>item.outcome!=="SUCCESS").length,3);assert.equal(multiplePartial.selected.filename,"44583_4746097_mp_delta.txt.gz");assert.equal(multiplePartial.connectionAccounting.connectionsOpened,1);cases++;
 const callsBeforeRootFailure=tracker.listCalls.length;await assert.rejects(()=>new RakutenProductCatalogSftpTransport({sessionFactory:factory({listErrors:{"/":pathFailure("SERVER_FAILURE",4)}}),stagingRoot:staging}).inspect(),error=>error.code==="SFTP_ROOT_LIST_FAILED"&&error.directoryListings.length===1&&error.directoryListings[0].logicalPath==="ROOT"&&error.directoryListings[0].outcome==="SERVER_FAILURE"&&error.connectionAccounting.connectionsOpened===1&&error.connectionAccounting.activeConnectionsAtEnd===0);assert.deepEqual(tracker.listCalls.slice(callsBeforeRootFailure),["/"]);cases++;
 const missingListings={...listings,"/":realisticRootRaw.filter(item=>!item.filename.includes("_mp_delta.txt.gz"))};await assert.rejects(()=>new RakutenProductCatalogSftpTransport({sessionFactory:factory({listingsOverride:missingListings}),stagingRoot:staging}).inspect(),error=>error.code==="SFTP_FILE_NOT_FOUND"&&error.connectionAccounting.activeConnectionsAtEnd===0&&error.discovery.mainDeltaCandidates===0);cases++;
 const ambiguousListings={...listings,"/":[...listings["/"],metadata("44583_9000001_mp_delta.txt.gz")]};await assert.rejects(()=>new RakutenProductCatalogSftpTransport({sessionFactory:factory({listingsOverride:ambiguousListings}),stagingRoot:staging}).inspect(),error=>error.code==="SFTP_FILE_AMBIGUOUS"&&error.connectionAccounting.activeConnectionsAtEnd===0&&error.discovery.mainDeltaCandidates===2);cases++;
 const malformedListings={...listings,"/":[...listings["/"],{filename:null,size:1,modifiedAt:"2026-09-09T01:00:00Z",isFile:true}]};await assert.rejects(()=>new RakutenProductCatalogSftpTransport({sessionFactory:factory({listingsOverride:malformedListings}),stagingRoot:staging}).inspect(),error=>error.code==="SFTP_LIST_ENTRY_INVALID"&&error.connectionAccounting.activeConnectionsAtEnd===0&&error.discovery.entriesObserved===12&&error.discovery.malformedEntries===1);cases++;
 await assert.rejects(()=>new RakutenProductCatalogSftpTransport({sessionFactory:factory({listError:Object.assign(new Error("SFTP_LIST_FAILED"),{code:"SFTP_LIST_FAILED"})}),stagingRoot:staging}).inspect(),error=>error.code==="SFTP_ROOT_LIST_FAILED"&&error.connectionAccounting.activeConnectionsAtEnd===0);await assert.rejects(()=>new RakutenProductCatalogSftpTransport({sessionFactory:factory({listError:new Error("unsafe remote detail")}),stagingRoot:staging}).inspect(),error=>error.code==="SFTP_ROOT_LIST_FAILED"&&!error.message.includes("remote detail")&&error.connectionAccounting.activeConnectionsAtEnd===0);cases++;
 const downloaded=await new RakutenProductCatalogSftpTransport({sessionFactory:factory(),stagingRoot:staging}).downloadAndValidate();
 assert.equal(downloaded.status,"DOWNLOADED_AND_VALIDATED"); assert.equal(downloaded.productRows,3); assert.equal(downloaded.trailerRows,3); assert.deepEqual(downloaded.modifications,{I:1,U:1,D:1}); assert.deepEqual(downloaded.fieldCounts,[39]); assert.equal(downloaded.selected.remoteTimestampUtc,"2026-09-09T01:00:00.000Z");assert.equal(downloaded.headerTimestamp,"2026-09-08T12:00:00.000Z");assert.notEqual(downloaded.selected.remoteTimestampUtc,downloaded.headerTimestamp); assert.deepEqual(await readFile(downloaded.localPath),bytes); assert.equal((await readdir(staging)).some(name=>name.includes(".partial-")),false); cases++;
 const badRoot=path.join(root,".forge-review","bad"),closesBeforeIntegrity=tracker.closes; await assert.rejects(()=>new RakutenProductCatalogSftpTransport({sessionFactory:factory({payload:Buffer.from("bad")}),stagingRoot:badRoot}).downloadAndValidate(),error=>error.connectionAccounting.activeConnectionsAtEnd===0); assert.equal(tracker.closes,closesBeforeIntegrity+1);assert.equal((await readdir(badRoot)).some(name=>name.includes(".partial-")),false); cases++;
 assert.throws(()=>new RakutenProductCatalogSftpTransport({sessionFactory:factory(),stagingRoot:staging,connectionConcurrency:6}),/CONNECTION_LIMIT/); assert.throws(()=>new RakutenProductCatalogSftpTransport({sessionFactory:factory(),stagingRoot:staging,connectionConcurrency:2}),/TRANSPORT_CONFIG/); assert.throws(()=>new RakutenProductCatalogSftpTransport({sessionFactory:factory(),stagingRoot:path.join(root,"public","feeds")}),/STAGING_PATH/); cases++;
 let attempts=0;assert.throws(()=>new RakutenProductCatalogSftpTransport({sessionFactory:()=>({}),stagingRoot:staging,maxAttempts:2}),/TRANSPORT_CONFIG/);const noRetryFactory=({connectionAccounting})=>({secrets:[secret],connect:async()=>{connectionAccounting.reserve();attempts++;throw new Error(secret);},close:async()=>{if(connectionAccounting.beginCleanup())connectionAccounting.release();},connectionAccounting:()=>connectionAccounting.snapshot()});const noRetry=new RakutenProductCatalogSftpTransport({sessionFactory:noRetryFactory,stagingRoot:staging});await assert.rejects(()=>noRetry.inspect(),error=>!error.message.includes(secret)&&error.connectionAccounting.activeConnectionsAtEnd===0);assert.equal(attempts,1);cases++;
 assert.equal(tracker.connections,tracker.closes); assert.ok(tracker.connections>=2); cases++;
}finally{await rm(root,{recursive:true,force:true});}

const source=await readFile(new URL("../current-display/RakutenProductCatalogSftpTransport.js",import.meta.url),"utf8");
assert.doesNotMatch(source,/CurrentDisplaySnapshotRepository|PublicCurrentRetailProjection|historical-observations|affiliate/i); assert.doesNotMatch(source,/fetch\(|http:|ftp:/i); cases++;
const sessionSource=await readFile(new URL("../current-display/NativeSftpSession.js",import.meta.url),"utf8");
assert.match(sessionSource,/hostVerifier/);assert.match(sessionSource,/password:this\.config\.password/);assert.doesNotMatch(sessionSource,/SSH_ASKPASS|OpenSsh|sftp\.exe|CurrentDisplaySnapshotRepository|PublicCurrentRetailProjection|historical-observations|affiliate/i); cases++;
const transportSource=await readFile(new URL("../current-display/RakutenProductCatalogSftpTransport.js",import.meta.url),"utf8");assert.doesNotMatch(transportSource,/CurrentRetailRefreshOrchestrator|processingConcurrency|lastProcessedRemoteTimestamp/);const cliSource=await readFile(new URL("../../../scripts/rakuten-sftp-transport.mjs",import.meta.url),"utf8");assert.match(cliSource,/Connection accounting:/);assert.match(cliSource,/Remote timestamp \(UTC\):/);assert.doesNotMatch(cliSource,/RAKUTEN_SFTP_USERNAME|RAKUTEN_SFTP_PASSWORD/);cases++;
console.log(`RAKUTEN-SFTP-008 directory isolation tests passed: ${cases} cases.`);
