import assert from "node:assert/strict";
import { spawn } from "node:child_process";
import { gzipSync } from "node:zlib";
import { mkdtemp, readFile, rm, writeFile } from "node:fs/promises";
import os from "node:os";
import path from "node:path";
import { fileURLToPath, pathToFileURL } from "node:url";
import { createRakutenSftpAcquisitionLease, createRakutenSftpConnectionAccounting, NativeSftpSession, RakutenProductCatalogSftpTransport, selectRakutenNeweggAuthoritativeLineage } from "../current-display/index.js";
import { fixtureFeedText, fixtureRow } from "./fixtures/rakuten-newegg/sanitized-feed-fixtures.js";

let cases=0;const check=(value,message)=>{assert.ok(value,message);cases+=1;},equal=(a,b)=>{assert.deepEqual(a,b);cases+=1;};
const root=await mkdtemp(path.join(os.tmpdir(),"hr-rakuten-safety-")),leasePath=path.join(root,".forge-review","rakuten-sftp","acquisition.lock");
const moduleUrl=pathToFileURL(path.resolve(path.dirname(fileURLToPath(import.meta.url)),"../current-display/RakutenSftpAcquisitionLease.js")).href;
try{
 const first=createRakutenSftpAcquisitionLease({leasePath,operationId:"first"}),acquired=await first.acquire();equal(acquired.leaseAcquired,true);check((await readFile(path.join(leasePath,"owner.json"),"utf8")).includes("first"));
 await assert.rejects(()=>createRakutenSftpAcquisitionLease({leasePath,operationId:"second"}).acquire(),/RAKUTEN_SFTP_ACQUISITION_ALREADY_ACTIVE/);cases++;
 equal((await first.release()).leaseReleased,true);const second=createRakutenSftpAcquisitionLease({leasePath,operationId:"second"});equal((await second.acquire()).leaseAcquired,true);await second.release();cases++;
 const dead=createRakutenSftpAcquisitionLease({leasePath,operationId:"dead",pid:999999,hostname:os.hostname(),isProcessAlive:()=>false});await writeFile(path.join(root,"seed.json"),"{}");await (await import("node:fs/promises")).mkdir(leasePath,{recursive:true});await writeFile(path.join(leasePath,"owner.json"),JSON.stringify({pid:999999,hostname:os.hostname(),operationId:"old",token:"old"}));equal((await dead.acquire()).staleLeaseRecovered,true);await dead.release();
 await (await import("node:fs/promises")).mkdir(leasePath,{recursive:true});await writeFile(path.join(leasePath,"owner.json"),JSON.stringify({pid:123,hostname:"another-host",operationId:"unknown",token:"x"}));await assert.rejects(()=>createRakutenSftpAcquisitionLease({leasePath,operationId:"ambiguous"}).acquire(),/OWNERSHIP_UNRESOLVED/);cases++;await rm(leasePath,{recursive:true,force:true});

 const childCode=`import {createRakutenSftpAcquisitionLease} from ${JSON.stringify(moduleUrl)};const lease=createRakutenSftpAcquisitionLease({leasePath:process.argv[1],operationId:process.argv[2]});try{await lease.acquire();process.stdout.write('ACQUIRED\\n');setTimeout(async()=>{await lease.release();process.exit(0)},1500)}catch(e){process.stdout.write(e.code+'\\n');process.exit(2)}`;
 const launch=id=>spawn(process.execPath,["--input-type=module","-e",childCode,leasePath,id],{stdio:["ignore","pipe","pipe"]});
 const output=child=>new Promise(resolve=>child.stdout.once("data",data=>resolve(String(data).trim()))),childA=launch("A");equal(await output(childA),"ACQUIRED");const childB=launch("B");equal(await output(childB),"RAKUTEN_SFTP_ACQUISITION_ALREADY_ACTIVE");await new Promise(resolve=>childA.once("exit",resolve));const childC=launch("C");equal(await output(childC),"ACQUIRED");await new Promise(resolve=>childC.once("exit",resolve));cases++;

 let closed=0,destroyed=0;const hungClient={end(){},destroy(){destroyed++;},once(event,handler){if(event==="close")this.closeHandler=handler;},removeListener(){},on(){}};const hungSftp={readdir(){},end(){},once(){},removeListener(){}};const accounting=createRakutenSftpConnectionAccounting({registry:{active:0}});accounting.reserve();accounting.markReady();const session=new NativeSftpSession({config:{protocol:"SFTP",concurrency:1},knownHostsPath:path.join(root,"known_hosts"),clientFactory:()=>hungClient,connectionAccounting:accounting,cleanupTimeoutMs:5});session.client=hungClient;session.sftp=hungSftp;await assert.rejects(()=>session.list("/",{timeoutMs:5}),cause=>cause.code==="SFTP_LIST_TIMEOUT"&&cause.listFailure.classification==="SFTP_LIST_TIMEOUT"&&cause.listFailure.timedOut===true&&cause.listFailure.cancelled===false);cases++;await session.close();equal(destroyed,1);equal(session.connectionAccounting().activeConnectionsAtEnd,0);check(session.connectionAccounting().connectionsDestroyedAsFallback===1);
 const cancelAccounting=createRakutenSftpConnectionAccounting({registry:{active:0}});cancelAccounting.reserve();cancelAccounting.markReady();const cancelSession=new NativeSftpSession({config:{protocol:"SFTP",concurrency:1},knownHostsPath:path.join(root,"known_hosts2"),clientFactory:()=>hungClient,connectionAccounting:cancelAccounting,cleanupTimeoutMs:5});cancelSession.client=hungClient;cancelSession.sftp=hungSftp;const controller=new AbortController(),pending=cancelSession.list("/",{signal:controller.signal,timeoutMs:1000});controller.abort();await assert.rejects(()=>pending,cause=>cause.code==="SFTP_LIST_CANCELLED"&&cause.listFailure.classification==="SFTP_LIST_CANCELLED"&&cause.listFailure.timedOut===false&&cause.listFailure.cancelled===true);cases++;await cancelSession.close();equal(cancelSession.connectionAccounting().activeConnectionsAtEnd,0);

 const fullName="44583_4746097_mp.txt.gz",deltaName="44583_4746097_mp_delta.txt.gz",fullBytes=gzipSync(fixtureFeedText({rows:[fixtureRow({}, {delta:false})]})),deltaBytes=gzipSync(fixtureFeedText({rows:[fixtureRow()]}));
 const entry=(filename,modifiedAt,size)=>({filename,remoteTimestampSourceSeconds:Date.parse(modifiedAt)/1000,modifiedAt,size,isDirectory:false,isFile:true}),listings={"/":[entry(fullName,"2026-09-01T00:00:00.000Z",fullBytes.length),entry(deltaName,"2026-09-02T00:00:00.000Z",deltaBytes.length)],"/44583/":[],"/ADDITIONAL/44583/":[],"/GLOBAL/":[]};
 const normalized=(await import("../current-display/index.js")).normalizeRakutenRemoteEntry;const lineage=selectRakutenNeweggAuthoritativeLineage(listings["/"].map(value=>normalized(value,"/")));equal(lineage.files.map(value=>value.feedFamily),["FULL","DELTA"]);assert.throws(()=>selectRakutenNeweggAuthoritativeLineage([normalized(listings["/"][1],"/")]),/FULL_NOT_FOUND/);cases++;
 const order=[],downloadOptions=[];let connects=0,closes=0,activeDownloads=0,peakDownloads=0,parsingAfterClose=false;const sessionFactory=({connectionAccounting})=>({secrets:["fixture-user","fixture-secret"],connect:async()=>{connectionAccounting.reserve();connectionAccounting.markReady();connects++;},list:async directory=>structuredClone(listings[directory]??[]),download:async(remote,local,options)=>{activeDownloads++;peakDownloads=Math.max(peakDownloads,activeDownloads);order.push(remote);downloadOptions.push(options);const bytes=remote.endsWith("_delta.txt.gz")?deltaBytes:fullBytes;await writeFile(local,bytes);activeDownloads--;return {bytesTransferred:bytes.length,reportedRemoteBytes:bytes.length,completionObserved:true};},close:async()=>{if(connectionAccounting.beginCleanup()){connectionAccounting.release();closes++;}parsingAfterClose=true;},connectionAccounting:()=>connectionAccounting.snapshot()});
 const leaseEvents=[],transport=new RakutenProductCatalogSftpTransport({sessionFactory,stagingRoot:path.join(root,".forge-review","staging"),acquisitionLeaseFactory:()=>({acquire:async()=>{leaseEvents.push("acquire");return {leaseAcquired:true,leaseContention:false,staleLeaseRecovered:false};},release:async()=>{leaseEvents.push(parsingAfterClose?"release-after-close":"release-before-close");return {leaseReleased:true};}})}),result=await transport.downloadAuthoritativeSequence();
 equal(connects,1);equal(closes,1);equal(peakDownloads,1);equal(order,[`/${fullName}`,`/${deltaName}`]);equal(downloadOptions.map(value=>value.downloadTimeoutMs),[1800000,1800000]);equal(result.filesDownloaded,2);equal(result.downloadsSequential,true);equal(result.localProcessingStartedAfterNetworkClose,true);equal(result.lineage.orderedFiles,[fullName,deltaName]);equal(leaseEvents,["acquire","release-after-close"]);equal(result.connectionAccounting.peakLocalConcurrentConnections,1);equal(result.actualSpendUsd,0);check(!JSON.stringify(result).includes("fixture-secret"));
 let attempts=0;const failureRoot=path.join(root,".forge-review","failure"),failureTransport=new RakutenProductCatalogSftpTransport({sessionFactory:({connectionAccounting})=>({secrets:["fixture-user","fixture-secret"],connect:async()=>{connectionAccounting.reserve();connectionAccounting.markReady();attempts++;},list:async directory=>structuredClone(listings[directory]??[]),download:async(remote,local)=>{if(remote.endsWith("_delta.txt.gz"))throw Object.assign(new Error("SFTP_DOWNLOAD_STALLED"),{code:"SFTP_DOWNLOAD_STALLED",transfer:{bytesTransferred:7,percentCompleteEstimate:7}});await writeFile(local,fullBytes);return {};},close:async()=>{if(connectionAccounting.beginCleanup())connectionAccounting.release();},connectionAccounting:()=>connectionAccounting.snapshot()}),stagingRoot:failureRoot});await assert.rejects(()=>failureTransport.downloadAuthoritativeSequence(),error=>error.code==="SFTP_DOWNLOAD_STALLED"&&error.authoritativeSequenceComplete===false&&error.connectionAccounting.activeConnectionsAtEnd===0&&error.lineage.full===fullName&&error.lineage.sequenceLength===2&&error.lineage.deltas[0]===deltaName&&error.attemptedFile.filename===deltaName&&error.attemptedFile.classification==="DELTA"&&error.attemptedFile.reportedRemoteBytes===deltaBytes.length&&error.transfer.bytesTransferred===7&&!JSON.stringify(error).includes("fixture-secret"));cases++;equal(attempts,1);check(!(await (await import("node:fs/promises")).readdir(failureRoot)).some(name=>name.includes(".partial-")));
 const timeoutRoot=path.join(root,".forge-review","timeout"),timeoutTransport=new RakutenProductCatalogSftpTransport({sessionFactory:({connectionAccounting})=>({connect:async()=>{connectionAccounting.reserve();connectionAccounting.markReady();},list:async directory=>structuredClone(listings[directory]??[]),download:async()=>{throw Object.assign(new Error("SFTP_DOWNLOAD_TIMEOUT"),{code:"SFTP_DOWNLOAD_TIMEOUT",transfer:{bytesTransferred:80,percentCompleteEstimate:80}});},close:async()=>{if(connectionAccounting.beginCleanup())connectionAccounting.release();},connectionAccounting:()=>connectionAccounting.snapshot()}),stagingRoot:timeoutRoot});await assert.rejects(()=>timeoutTransport.downloadAuthoritativeSequence(),error=>error.code==="SFTP_DOWNLOAD_TIMEOUT"&&error.lineage.full===fullName&&error.attemptedFile.filename===fullName&&error.attemptedFile.classification==="FULL"&&error.authoritativeSequenceComplete===false);cases++;check(!(await (await import("node:fs/promises")).readdir(timeoutRoot)).some(name=>name.includes(".partial-")));
 const unsupportedBytes=gzipSync(`HDR|44583|PRIVATE ADVERTISER|29/09/2026 10:11:12\n${fixtureRow({}, {delta:false})}\nTRL|1`),diagnosticListings={...listings,"/":[entry(fullName,"2026-09-01T00:00:00.000Z",unsupportedBytes.length)]},diagnosticRoot=path.join(root,".forge-review","diagnostic"),diagnosticTransport=new RakutenProductCatalogSftpTransport({sessionFactory:({connectionAccounting})=>({secrets:["fixture-user","fixture-secret"],connect:async()=>{connectionAccounting.reserve();connectionAccounting.markReady();},list:async directory=>structuredClone(diagnosticListings[directory]??[]),download:async(_remote,local)=>{await writeFile(local,unsupportedBytes);return {bytesTransferred:unsupportedBytes.length,completionObserved:true};},close:async()=>{if(connectionAccounting.beginCleanup())connectionAccounting.release();},connectionAccounting:()=>connectionAccounting.snapshot()}),stagingRoot:diagnosticRoot});await assert.rejects(()=>diagnosticTransport.downloadAuthoritativeSequence(),error=>{const hdr=error.integrity.unsupportedTimestampDiagnostic.hdr,semantic=hdr.timestampSemanticFailure,syntax=hdr.timestampSyntax,serialized=JSON.stringify(error);return error.code==="SFTP_HDR_TIMESTAMP_INVALID"&&error.lineage.full===fullName&&error.lineage.sequenceLength===1&&error.attemptedFile.filename===fullName&&error.attemptedFile.classification==="FULL"&&error.transfer.completionObserved===true&&semantic.failureComponent==="MONTH"&&semantic.failureReason==="MONTH_OUT_OF_RANGE"&&semantic.observedNumericValue===29&&syntax.firstDateComponent===29&&syntax.secondDateComponent===9&&syntax.yearComponent===2026&&!("hourComponent" in syntax)&&!("minuteComponent" in syntax)&&!("secondComponent" in syntax)&&error.integrity.unsupportedTimestampDiagnostic.gzip.reachedEof===true&&error.integrity.unsupportedTimestampDiagnostic.trailer.productCountMatches===true&&!serialized.includes("29/09/2026 10:11:12")&&!serialized.includes("PRIVATE ADVERTISER")&&!serialized.includes("fixture-secret");});cases++;check(!(await (await import("node:fs/promises")).readdir(diagnosticRoot)).some(name=>name.includes(".partial-")));
 const lifecycle=[];const fakeLease=()=>({acquire:async()=>{lifecycle.push("lease-acquired");return {leaseAcquired:true,leaseContention:false,staleLeaseRecovered:false};},release:async()=>{lifecycle.push("lease-released");return {leaseReleased:true};}});
 const failing=(kind)=>new RakutenProductCatalogSftpTransport({stagingRoot:path.join(root,".forge-review",`failure-${kind}`),acquisitionLeaseFactory:fakeLease,sessionFactory:({connectionAccounting})=>({secrets:["not-a-real-user","not-a-real-password"],connect:async()=>{connectionAccounting.reserve();if(kind==="connect")throw new Error("SFTP_CONNECT_FAILED");connectionAccounting.markReady();},list:async()=>{throw new Error(kind==="timeout"?"SFTP_LIST_TIMEOUT":"SFTP_LIST_FAILED");},close:async()=>{lifecycle.push("session-closed");if(connectionAccounting.beginCleanup())connectionAccounting.release();},connectionAccounting:()=>connectionAccounting.snapshot()})});
 for(const kind of ["connect","list","timeout"]){lifecycle.length=0;await assert.rejects(()=>failing(kind).inspect());equal(lifecycle,["lease-acquired","session-closed","lease-released"]);}check(!JSON.stringify(lifecycle).includes("not-a-real-password"));
}finally{await rm(root,{recursive:true,force:true});}
console.log(`RAKUTEN-SFTP single-session safety hardening tests passed: ${cases} cases.`);
