import assert from "node:assert/strict";
import {createHash} from "node:crypto";
import {mkdtemp,rm} from "node:fs/promises";
import {tmpdir} from "node:os";
import {join} from "node:path";
import {createCurrentDisplaySnapshot,createCurrentOfferProjection,FileCurrentDisplaySnapshotRepository} from "../current-display/index.js";
import { executeRakutenFullCurrentRefresh, prepareRakutenFullCurrentRefresh, prepareRakutenFullCurrentRefreshPlan, validateRakutenFullCurrentRefreshPlan, validateRakutenFullCurrentRefreshPreparation } from "../current-refresh/index.js";

const offer=(identity,price,overrides={})=>({offerIdentity:identity,identityMode:"EVIDENCE_GROUNDED",atlasProductId:"ram_fixture",retailerId:"RETAILER-0004",destinationId:"mer_dest_fixture",priceUsd:price,...overrides});
const source={schemaVersion:"1.1",snapshotId:"mer_display_source",materialFingerprint:"a".repeat(64),offers:[offer("mer_offer_legacy",100,{identityMode:"LEGACY_PRODUCT_CHANNEL"}),offer("mer_offer_unchanged",80,{atlasProductId:"ram_other"})]},proposed={schemaVersion:"1.1",snapshotId:"mer_display_proposed",materialFingerprint:"b".repeat(64),offers:[offer("mer_offer_evidence",100),offer("mer_offer_unchanged",80,{atlasProductId:"ram_other"})]},catalog={stateId:"rakuten_catalog_fixture",stateDigest:"c".repeat(64),catalogDigest:"d".repeat(64),artifact:{digest:"e".repeat(64),headerTimestamp:"2026-10-02T10:54:14.000Z",remoteModifiedAt:"2026-10-02T14:59:55.000Z"},recordCount:1065223},result={mode:"DRY_RUN",summary:{routineCurrentUpdates:1},rowAssessments:[],outcomes:[],exceptions:[]};
const plan=prepareRakutenFullCurrentRefreshPlan({sourceSnapshot:source,proposedSnapshot:proposed,catalogManifest:catalog,result,preparedAt:"2026-10-02T17:53:23.647Z"});
assert.equal(plan.diff.added.length,0);assert.equal(plan.diff.withdrawn.length,0);assert.equal(plan.diff.updated.length,1);assert.equal(plan.diff.updated[0].progression,"LEGACY_TO_EVIDENCE_GROUNDED");assert.equal(plan.diff.unchanged.length,1);assert.equal(plan.authority,"NONE");assert.equal(plan.currentMutationAuthorized,false);assert.equal(plan.historyEligibility,false);assert.equal(plan.sourceCatalog.headerTimestamp,"2026-10-02T10:54:14.000Z");assert.equal(plan.sourceCatalog.remoteModifiedAt,"2026-10-02T14:59:55.000Z");
const preparation=prepareRakutenFullCurrentRefresh({plan});assert.equal(preparation.members.length,1);assert.equal(preparation.members[0].change,"UPDATE");assert.equal(preparation.networkOperation,"NONE");assert.equal(preparation.currentMutationAuthorized,false);assert.equal(preparation.historyEligibility,false);assert.equal(preparation.providerCalls,0);assert.equal(preparation.actualSpendUsd,0);
assert.equal(validateRakutenFullCurrentRefreshPlan(plan),true);assert.equal(validateRakutenFullCurrentRefreshPreparation(preparation,{plan}),true);

const raw=(price,observedAt)=>({atlasProductId:"ram_fixture",retailer:"NEWEGG",retailerId:"RETAILER-0004",marketplace:"US",priceUsd:price,currency:"USD",availability:"AVAILABLE",condition:"NEW",shippingUsd:null,feesUsd:null,researchUrl:null,destinationId:"mer_dest_aaaaaaaaaaaaaaaaaaaaaaaa",matchStatus:"EXACT",sourceRow:1,observedAt,sellerName:null,sourceIdentity:{adapterId:"rakuten_fixture",sourceId:"RAKUTEN_NEWEGG_PRODUCT_CATALOG",historicalRetentionAllowed:false},comparisonEligible:true,comparisonReasons:[],itemPriceEligible:true,deliveredCostEligible:false,deliveredCostReasons:["UNKNOWN_SHIPPING"]});
const beforeOffer=createCurrentOfferProjection({offer:raw(100,"2026-10-01T10:00:00.000Z"),listingIdentity:"ITEM1"}),afterOffer=createCurrentOfferProjection({offer:raw(90,"2026-10-02T10:54:14.000Z"),listingIdentity:"ITEM1"});
const realSource=createCurrentDisplaySnapshot({schemaVersion:"1.1",observedAt:"2026-10-01T10:00:00.000Z",importedAt:"2026-10-01T10:00:00.000Z",source:{workbook:"fixture",sheet:"before",digest:"1".repeat(64)},offers:[beforeOffer]}),item={atlasProductId:"ram_fixture",retailerId:"RETAILER-0004",retailer:"NEWEGG",destinationId:"mer_dest_aaaaaaaaaaaaaaaaaaaaaaaa",destinationUrl:"https://example.com/newegg",retailerListingId:"ITEM1",marketplace:"US",asOf:"2026-10-02T12:00:00.000Z",sourceAdapterId:"mer_adapter_fixture",sourceMode:"AUTOMATED_PRIMARY"},outcomes=[{operationId:1,...item,status:"REFRESHED"}],stable=value=>Array.isArray(value)?`[${value.map(stable).join(",")}]`:value&&typeof value==="object"?`{${Object.keys(value).sort().map(key=>`${JSON.stringify(key)}:${stable(value[key])}`).join(",")}}`:JSON.stringify(value),hash=value=>createHash("sha256").update(stable(value)).digest("hex"),portfolioDigest=hash({asOf:item.asOf,items:[item]}),portfolioId=`mer_curportfolio_${portfolioDigest.slice(0,24)}`,runDigest=hash({portfolioId,asOf:item.asOf,outcomes}),realProposed=createCurrentDisplaySnapshot({schemaVersion:"1.1",observedAt:item.asOf,importedAt:item.asOf,source:{workbook:`fixture-current-retail-refresh:${portfolioId}`,sheet:"Source-neutral fixture refresh",digest:runDigest},offers:[afterOffer]});
const realResult={...result,outcomes},realPlan=prepareRakutenFullCurrentRefreshPlan({sourceSnapshot:realSource,proposedSnapshot:realProposed,catalogManifest:catalog,result:realResult,preparedAt:item.asOf}),realPreparation=prepareRakutenFullCurrentRefresh({plan:realPlan}),root=await mkdtemp(join(tmpdir(),"rakuten-full-execution-"));
try{const repository=new FileCurrentDisplaySnapshotRepository({statePath:join(root,"current.json")});await repository.replace(realSource);const confirm=`EXECUTE-RAKUTEN-FULL-CURRENT:${realPlan.planId}:${realPreparation.preparationId}`,executed=await executeRakutenFullCurrentRefresh({plan:realPlan,preparation:realPreparation,currentSnapshotRepository:repository,authorizedPlanId:realPlan.planId,authorizedPreparationId:realPreparation.preparationId,confirmation:confirm});assert.equal(executed.status,"EXECUTED");assert.equal(executed.historyRecordsDelta,0);assert.equal((await repository.getState()).current.snapshotId,realProposed.snapshotId);const replay=await executeRakutenFullCurrentRefresh({plan:realPlan,preparation:realPreparation,currentSnapshotRepository:repository,authorizedPlanId:realPlan.planId,authorizedPreparationId:realPreparation.preparationId,confirmation:confirm});assert.equal(replay.status,"ALREADY_EXECUTED");assert.equal((await repository.getState()).current.offers.length,1);await assert.rejects(()=>executeRakutenFullCurrentRefresh({plan:realPlan,preparation:realPreparation,currentSnapshotRepository:repository,authorizedPlanId:realPlan.planId,authorizedPreparationId:realPreparation.preparationId,confirmation:"WRONG"}),/CONFIRMATION_INVALID/);}finally{await rm(root,{recursive:true,force:true});}
console.log("Rakuten fresh FULL Current plan tests passed: 28 cases.");
