import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";
import { Mercury } from "../Mercury.js";
import { MarketPublicationService, MAX_COMPARISON_OFFERS } from "../publication/MarketPublicationService.js";
import { makeObservation } from "./helpers/reviewFixture.mjs";

const baseProduct = JSON.parse(await readFile(new URL("../../atlas/products/ram/ddr5/HR-RAM-DDR5-000001-corsair-vengeance-32gb-6000-cl30.json", import.meta.url), "utf8"));
const baseRetailer = JSON.parse(await readFile(new URL("../../atlas/retailers/RETAILER-0002-platinummicro.json", import.meta.url), "utf8"));
const service = new MarketPublicationService({ mercury: new Mercury() }), generatedAt = "2026-08-31T12:30:00Z";
const product = (id, memoryType, formFactor, applicationClass) => { const value = structuredClone(baseProduct); value.identity.atlasProductId = id; value.extension.data.classification = { ...value.extension.data.classification, memoryType, formFactor, applicationClass }; return value; };
const retailer = ({ id = "RETAILER-0002", status = "active", regions = ["US"], currencies = ["USD"], affiliate = false } = {}) => ({ ...structuredClone(baseRetailer), id, status, regions, supportedCurrencies: currencies, affiliateProgram: { ...baseRetailer.affiliateProgram, available: affiliate } });
const products = [product("ram_ddr5_desktop", "DDR5", "DIMM", "DESKTOP"), product("ram_ddr4_desktop", "DDR4", "DIMM", "DESKTOP"), product("ram_ddr4_laptop", "DDR4", "SO_DIMM", "LAPTOP"), product("ram_ddr5_laptop", "DDR5", "SO_DIMM", "LAPTOP")];
function candidate(index, { productId = "ram_ddr5_desktop", retailerValue = retailer(), price = 100 + index, observedAt = `2026-08-31T12:${String(index).padStart(2, "0")}:00Z`, shipping = { costKnown: false, cost: null, currency: null }, qualified = true, affiliate = false, bundle = null, conditionalPrice = null, currency = "USD" } = {}) {
  const observationId = `mer_obs_${String(100 + index).padStart(9, "0")}`, observation = makeObservation(observationId, { sourceMethod: "API", licenseContext: "DATAFORSEO_GOOGLE_SHOPPING", observedAt });
  Object.assign(observation, { atlasProductId: productId, retailerId: retailerValue.id, marketplace: "platinummicro.com" }); Object.assign(observation.offer, { price, currency, shipping, affiliate: { isAffiliateLink: affiliate, network: affiliate ? "fixture" : null, trackingCodePresent: affiliate }, ...(bundle ? { bundle } : {}), ...(conditionalPrice ? { conditionalPrice } : {}) });
  return { observation, product: products.find(value => value.identity.atlasProductId === productId), retailer: retailerValue, currentMarketQualification: { observationId, qualified, freshness: { status: "CURRENT" }, confidence: { status: "HIGH" } } };
}
const many = [candidate(1, { price: 110 }), candidate(2, { price: 100 }), candidate(3, { price: 105 }), candidate(4, { price: 115 }), candidate(5, { price: 120 }), candidate(6, { price: 125 }), candidate(7, { price: 130 }), candidate(2, { price: 100 })];
const snapshot = await service.createSnapshot({ observations: [], qualifiedCandidates: many, products, retailers: [baseRetailer], generatedAt });
assert.equal(MAX_COMPARISON_OFFERS, 5); assert.equal(snapshot.scopes.ddr5.cheapest.price, 100); assert.deepEqual(snapshot.scopes.ddr5.alternatives.map(value => value.price), [105, 110, 115, 120]); assert.equal(snapshot.scopes.ddr5.coverage.eligibleObservations, 7); assert.equal(snapshot.scopes.ddr5.coverage.displayedOffers, 5); assert.equal(new Set([snapshot.scopes.ddr5.cheapest, ...snapshot.scopes.ddr5.alternatives].map(value => value.observationId)).size, 5);
const replay = await service.createSnapshot({ observations: [], qualifiedCandidates: many, products, retailers: [baseRetailer], generatedAt }); assert.deepEqual(replay, snapshot);
const one = await service.createSnapshot({ observations: [], qualifiedCandidates: [candidate(8, { shipping: { costKnown: false, cost: null, currency: null } })], products, retailers: [baseRetailer], generatedAt }); assert.equal(one.scopes.ddr5.alternatives.length, 0); assert.equal(one.scopes.ddr5.cheapest.shipping.known, false); assert.equal(one.scopes.ddr5.cheapest.shipping.amount, null); assert.equal(one.scopes.ddr5.cheapest.listedPrice, one.scopes.ddr5.cheapest.price); assert.equal(one.scopes.ddr5.cheapest.priceBasis, "LISTED_PRICE"); assert.equal("totalPrice" in one.scopes.ddr5.cheapest, false);
const free = await service.createSnapshot({ observations: [], qualifiedCandidates: [candidate(9, { shipping: { costKnown: true, cost: 0, currency: "USD" } })], products, retailers: [baseRetailer], generatedAt }); assert.deepEqual(free.scopes.ddr5.cheapest.shipping, { known: true, amount: 0, currency: "USD" });
const paid = await service.createSnapshot({ observations: [], qualifiedCandidates: [candidate(10, { shipping: { costKnown: true, cost: 12.5, currency: "USD" } })], products, retailers: [baseRetailer], generatedAt }); assert.equal(paid.scopes.ddr5.cheapest.shipping.amount, 12.5);
const scopedCandidates = [candidate(11), candidate(12, { productId: "ram_ddr4_desktop" }), candidate(13, { productId: "ram_ddr4_laptop" }), candidate(14, { productId: "ram_ddr5_laptop" })], scoped = await service.createSnapshot({ observations: [], qualifiedCandidates: scopedCandidates, products, retailers: [baseRetailer], generatedAt }); assert.equal(scoped.scopes.ddr5.coverage.eligibleObservations, 1); assert.equal(scoped.scopes.ddr4.coverage.eligibleObservations, 1); assert.equal(scoped.scopes.sodimm.coverage.eligibleObservations, 2); assert.equal(scoped.scopes.overall.coverage.eligibleObservations, 4); assert.deepEqual(scoped.scopes.sodimm.alternatives.map(value => value.memoryType), ["DDR5"]);
for (const blocked of [candidate(15, { qualified: false }), candidate(16, { retailerValue: retailer({ status: "inactive" }) }), candidate(17, { retailerValue: retailer({ regions: ["CA"] }) }), candidate(18, { retailerValue: retailer({ currencies: ["CAD"] }) }), candidate(19, { currency: "EUR" }), candidate(20, { bundle: { isBundle: true } }), candidate(21, { conditionalPrice: { isConditional: true } })]) { const result = await service.createSnapshot({ observations: [], qualifiedCandidates: [blocked], products, retailers: [blocked.retailer], generatedAt }); assert.equal(result.scopes.overall.status, "INSUFFICIENT_DATA"); }
const unaffiliated = await service.createSnapshot({ observations: [], qualifiedCandidates: [candidate(22, { price: 90 }), candidate(23, { price: 95 })], products, retailers: [baseRetailer], generatedAt }), affiliated = await service.createSnapshot({ observations: [], qualifiedCandidates: [candidate(22, { price: 90, affiliate: true }), candidate(23, { price: 95 })], products, retailers: [baseRetailer], generatedAt }); assert.deepEqual(affiliated, unaffiliated);
for (const offer of [snapshot.scopes.ddr5.cheapest, ...snapshot.scopes.ddr5.alternatives]) for (const forbidden of ["reviewDecisionId", "publicationDecisionId", "authorizationId", "rightsProfileHash", "operatorNotes"]) assert.equal(forbidden in offer, false);
console.log("RAM comparison snapshot projection tests passed (48 cases).");
