import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";
import { ProductRepository, RetailerRepository, createRamCatalogProjection } from "../../atlas/index.js";
import { createPublicRetailerDestinationProjection, loadRetailerDestinationSource } from "../destinations/RetailerDestinationSource.js";
import { createEmptyPublicCurrentRetailProjection } from "../current-display/PublicCurrentRetailProjection.js";
import { createRamTerminalPublicIntelligence } from "../historical-admission/RamTerminalPublicIntelligence.js";
import { createPublicChronologicalPriceSeries } from "../historical-admission/PublicChronologicalPriceSeries.js";
import { createRamPublicIntelligencePortfolioManifest, certifyRamPublicIntelligencePortfolio, portfolioFileDigest, validateRamPublicIntelligencePortfolio } from "../publication/RamPublicIntelligenceReleasePortfolio.js";

const at = "2026-10-01T00:00:00.000Z";
const readJson = async file => JSON.parse(await readFile(file, "utf8"));
const products = await new ProductRepository({ readJson }).getAll();
const retailers = await new RetailerRepository({ readJson }).getAll();
const catalog = createRamCatalogProjection(products);
const source = await loadRetailerDestinationSource({ sourcePath: "packages/mercury/destinations/production-destinations.json", products, retailers });
const destinations = createPublicRetailerDestinationProjection({ source, retailers });
const current = createEmptyPublicCurrentRetailProjection({ asOf: at });
const history = { getAll: async () => [] };
const terminal = await createRamTerminalPublicIntelligence({ catalog, currentRetail: current, historicalRepository: history, asOf: at });
const chronology = await createPublicChronologicalPriceSeries({ catalog, retailers, historicalRepository: history });
const text = value => `${JSON.stringify(value, null, 2)}\n`;
const fileTexts = { catalog: text(catalog), current: text(current), terminal: text(terminal), staleCurrent: text(current), staleTerminal: text(terminal), chronology: text(chronology), destinations: text(destinations) };
const files = Object.fromEntries(Object.entries(fileTexts).map(([name, value]) => [name, { file: `${name}.json`, digestSha256: portfolioFileDigest(value), bytes: Buffer.byteLength(value) }]));
const manifest = createRamPublicIntelligencePortfolioManifest({ preparedAt: at, preparedBy: "fixture", inputs: { atlasManifest: "a".repeat(64) }, routes: { total: 122, staticRoutes: 14, editorialArticleRoutes: 5, productRoutes: 103, snapshotRoutes: 0 }, files, counts: { products: 103, freshCurrentProducts: 0, freshCurrentOffers: 0, staleCurrentOffers: 0, comparableHistoryObservations: 0, historyProducts: 0, timestampGroups: 0, governedDestinations: destinations.length }, currentValidUntil: null });
const report = validateRamPublicIntelligencePortfolio({ manifest, fileTexts, evaluatedAt: at });
assert.equal(report.valid, true, report.errors.join(","));
assert.equal(report.authorityModel, "SPLIT_DURABLE_AND_CURRENT");
assert.equal(report.currentMode, "EXPIRED_DURABLE_ONLY");
assert.equal(report.durableMode, "AVAILABLE");
assert.equal(manifest.releaseAuthority, false);
assert.equal(manifest.deploymentAuthority, false);
assert.equal(manifest.snapshotIncluded, false);
const certification = certifyRamPublicIntelligencePortfolio({ manifest, fileTexts, evaluatedAt: at, certifiedBy: "fixture" });
assert.equal(certification.status, "CERTIFIED");
assert.equal(certification.releaseAuthority, false);
assert.equal(validateRamPublicIntelligencePortfolio({ manifest, fileTexts: { ...fileTexts, catalog: fileTexts.catalog.replace("Corsair", "Tampered") }, evaluatedAt: at }).valid, false);
assert.equal(validateRamPublicIntelligencePortfolio({ manifest: { ...manifest, snapshotIncluded: true }, fileTexts, evaluatedAt: at }).valid, false);
console.log("Mercury RAM public-intelligence release portfolio contract passed.");
