import assert from "node:assert/strict";
import {mkdtemp,readFile,rm,writeFile} from "node:fs/promises";
import {join} from "node:path";
import {tmpdir} from "node:os";
import {FileDataForSeoPrepareArtifactRepository,FileLiveAuthorizationConsumptionRepository,SqliteRepeatObservationRepository,RepeatObservationService,createAmazonRepeatObservationIdentity,createGoogleRepeatObservationIdentity,defaultSourceRightsRegistry,REPEAT_OBSERVATION_AUTHORIZE_CONFIRMATION,REPEAT_OBSERVATION_EXECUTE_CONFIRMATION} from "../index.js";
const root=await mkdtemp(join(tmpdir(),"repeat-persistence-")),state=join(root,"repeat.sqlite"),legacyState=join(root,"prepared.json"),consumptionPath=join(root,"consumptions.json"),at="2026-09-14T00:00:00.000Z";
try{
 const consumptions=new FileLiveAuthorizationConsumptionRepository({filePath:consumptionPath}),repository=new SqliteRepeatObservationRepository({databasePath:state,consumptionRepository:consumptions});let calls=0;
 const amazonIdentity=id=>createAmazonRepeatObservationIdentity({atlasProductId:id,state:"STRONG_UNIQUE_ASIN",governedAsin:"B0BXHC74WD",sellersAuthorizationEligible:true,outcomeId:`out-${id}`});
 const googleIdentity=id=>createGoogleRepeatObservationIdentity({atlasProductId:id,state:"APPLICABLE",providerIdentity:{productId:"p",dataDocId:"d",gid:"g"},identityReuseAssessmentId:`reuse-${id}`,contradictionStatus:"NONE"});
 let executionQueue=Promise.resolve();const execute=({request})=>{const run=async()=>{const consumed=await consumptions.consume({authorizationId:request.authorizationId,planId:request.planId,consumedAt:at});if(consumed.status!=="CONSUMED")return{status:"LIVE_AUTHORIZATION_ALREADY_CONSUMED"};calls++;return{status:"COMPLETED",taskCount:1};};const result=executionQueue.then(run,run);executionQueue=result.catch(()=>{});return result;},owners={AMAZON_SELLERS:{execute},SELLERS:{execute}};
 const service=new RepeatObservationService({productRepository:{getById:async id=>({identity:{atlasProductId:id}})},identityResolvers:{DATAFORSEO_AMAZON:{resolve:async({atlasProduct})=>amazonIdentity(atlasProduct.identity.atlasProductId)},DATAFORSEO_GOOGLE_SHOPPING:{resolve:async({atlasProduct})=>googleIdentity(atlasProduct.identity.atlasProductId)}},rightsRegistry:defaultSourceRightsRegistry,repository,taskOwners:owners,now:()=>at});
 const ap=await service.prepare({atlasProductId:"ram-amazon",source:"DATAFORSEO_AMAZON",observationCycle:at}),gp=await service.prepare({atlasProductId:"ram-google",source:"DATAFORSEO_GOOGLE_SHOPPING",observationCycle:at});assert.equal(ap.status,"PREPARED");assert.equal(gp.status,"PREPARED");assert.equal((await service.prepare({atlasProductId:"ram-amazon",source:"DATAFORSEO_AMAZON",observationCycle:at})).status,"DUPLICATE");assert.equal((await repository.getPreparation(ap.value.preparedObservationId)).operation,"AMAZON_SELLERS");assert.equal((await repository.getPreparation(gp.value.preparedObservationId)).operation,"SELLERS");
 const input={preparedObservationId:ap.value.preparedObservationId,operator:"fixture",reason:"repeat",expiresAt:"2026-09-14T00:15:00.000Z",confirmation:REPEAT_OBSERVATION_AUTHORIZE_CONFIRMATION},authorization=await service.authorize(input);assert.equal(authorization.status,"AUTHORIZED");assert.equal((await service.authorize(input)).status,"DUPLICATE");
 const competing=await Promise.allSettled([service.authorize({...input,operator:"other"}),service.authorize({...input,reason:"other"})]);assert.equal(competing.filter(x=>x.status==="rejected").length,2);assert.match(competing[0].reason.message,/ACTIVE/);
 const executions=await Promise.all([service.execute({authorizationId:authorization.value.authorizationId,executedBy:"fixture",confirmation:REPEAT_OBSERVATION_EXECUTE_CONFIRMATION}),service.execute({authorizationId:authorization.value.authorizationId,executedBy:"fixture",confirmation:REPEAT_OBSERVATION_EXECUTE_CONFIRMATION})]);assert.equal(executions.filter(x=>x.status==="COMPLETED").length,1);assert.equal(executions.filter(x=>x.status==="LIVE_AUTHORIZATION_ALREADY_CONSUMED").length,1);assert.equal(calls,1);assert.equal((await consumptions.getAll()).length,1);
 const legacy={version:"1.0",artifacts:{legacy:{prepareArtifactId:"legacy",value:"unchanged"}},byIntent:{}};await writeFile(legacyState,`${JSON.stringify(legacy,null,2)}\n`);const legacyRepo=new FileDataForSeoPrepareArtifactRepository({statePath:legacyState});assert.deepEqual(await legacyRepo.getById("legacy"),legacy.artifacts.legacy);assert.deepEqual(JSON.parse(await readFile(legacyState,"utf8")),legacy);
 await assert.rejects(repository.recordPreparation({...ap.value,operation:"PRODUCTS"}),/PREPARATION_INVALID/);await assert.rejects(repository.recordAuthorization({...authorization.value,preparedObservationId:gp.value.preparedObservationId}),/BINDING_INVALID/);
 repository.close();console.log("Repeat observation indexed persistence tests passed: 18 invariants.");
}finally{await rm(root,{recursive:true,force:true});}
