import assert from "node:assert/strict";
import {mkdtemp,readFile,rm} from "node:fs/promises";
import {tmpdir} from "node:os";
import {join} from "node:path";
import {createAmazonRepeatObservationIdentity,createGoogleRepeatObservationIdentity,createProductionRepeatObservationService,defaultSourceRightsRegistry,REPEAT_OBSERVATION_AUTHORIZE_CONFIRMATION,REPEAT_OBSERVATION_EXECUTE_CONFIRMATION} from "../index.js";

let cases=0;const ok=(value,message)=>{assert.ok(value,message);cases++;},equal=(a,b)=>{assert.equal(a,b);cases++;};
const root=await mkdtemp(join(tmpdir(),"repeat-production-")),at="2026-09-14T00:00:00.000Z",products=new Map(),identities=new Map(),consumed=new Set(),calls=[];
for(let i=0;i<10000;i++)products.set(`ram_${i}`,{identity:{atlasProductId:`ram_${i}`}});
const automatic=createAmazonRepeatObservationIdentity({atlasProductId:"ram_0",state:"STRONG_UNIQUE_ASIN",governedAsin:"B0BXHC74WD",sellersAuthorizationEligible:true,outcomeId:"out-0"}),confirmed=createAmazonRepeatObservationIdentity({atlasProductId:"ram_1",state:"STRONG_OPERATOR_CONFIRMED_ASIN",governedAsin:"B0CQQVNCB6",sellersAuthorizationEligible:true,confirmationId:"confirmation-1"}),google=createGoogleRepeatObservationIdentity({atlasProductId:"ram_2",state:"APPLICABLE",providerIdentity:{productId:"product-2",dataDocId:"doc-2",gid:"gid-2"},identityReuseAssessmentId:"reuse-2",contradictionStatus:"NONE"});
identities.set("ram_0",automatic);identities.set("ram_1",confirmed);identities.set("ram_2",google);
const identityResolvers={DATAFORSEO_AMAZON:{resolve:async({atlasProduct})=>identities.get(atlasProduct.identity.atlasProductId)},DATAFORSEO_GOOGLE_SHOPPING:{resolve:async({atlasProduct})=>identities.get(atlasProduct.identity.atlasProductId)}},taskOwner=operation=>({execute:async({request})=>{if(consumed.has(request.authorizationId))return{status:"LIVE_AUTHORIZATION_ALREADY_CONSUMED",authorizationConsumed:false};consumed.add(request.authorizationId);calls.push(request.plan.decisions[0].execution);return{status:"COMPLETED",authorizationConsumed:true,execution:{run:{attemptedTasks:1,actualSpendUsd:request.maxSpendUsd}}};}}),retrieved=[],processed=[],facts=[];
const service=createProductionRepeatObservationService({databasePath:join(root,"repeat.sqlite"),stateRoot:root,productRepository:{getById:async id=>products.get(id)},identityResolvers,rightsRegistry:defaultSourceRightsRegistry,executionRepository:{getAll:async()=>[]},consumptionRepository:{getAll:async()=>[...consumed].map(authorizationId=>({authorizationId}))},taskOwners:{AMAZON_SELLERS:taskOwner("AMAZON_SELLERS"),SELLERS:taskOwner("SELLERS")},retrievalOwners:{AMAZON_SELLERS:{retrieve:async x=>(retrieved.push(x),x)}},processingOwners:{AMAZON_SELLERS:{process:async x=>(processed.push(x),x)}},historicalAdmissionOwner:{assess:async x=>(facts.push(["ASSESS",x]),x),admit:async x=>(facts.push(["ADMIT",x]),x)},taskResolver:async()=>({providerTaskId:"provider-task"}),now:()=>at});
try{
 equal(service.databasePath,join(root,"repeat.sqlite"));ok(service.repository,"SQLite injected");
 const prepared=await service.prepare({atlasProductId:"ram_0",source:"DATAFORSEO_AMAZON",observationCycle:at});equal(prepared.status,"PREPARED");equal(prepared.value.operation,"AMAZON_SELLERS");equal(prepared.value.taskCostUsd,.0015);equal(prepared.value.authorizationState,"NOT_AUTHORIZED");
 const replay=await service.prepare({atlasProductId:"ram_0",source:"DATAFORSEO_AMAZON",observationCycle:at});equal(replay.status,"DUPLICATE");equal(replay.value.preparedObservationId,prepared.value.preparedObservationId);
 const later=await service.prepare({atlasProductId:"ram_0",source:"DATAFORSEO_AMAZON",observationCycle:"2026-09-15T00:00:00.000Z"});ok(later.value.preparedObservationId!==prepared.value.preparedObservationId);
 const confirmedPrepared=await service.prepare({atlasProductId:"ram_1",source:"DATAFORSEO_AMAZON",observationCycle:at});equal(confirmedPrepared.value.reusableIdentity.identityState,"STRONG_OPERATOR_CONFIRMED_ASIN");
 const googlePrepared=await service.prepare({atlasProductId:"ram_2",source:"DATAFORSEO_GOOGLE_SHOPPING",observationCycle:at});equal(googlePrepared.value.operation,"SELLERS");equal(googlePrepared.value.taskCostUsd,.001);
 await assert.rejects(()=>service.prepare({atlasProductId:"ram_0",source:"DATAFORSEO_AMAZON",observationCycle:at,asin:"BAD"}),/INPUT_INVALID/);cases++;
 const auth=await service.authorize({preparedObservationId:prepared.value.preparedObservationId,operator:"operator:test",reason:"fixture",expiresAt:"2026-09-14T01:00:00.000Z",confirmation:REPEAT_OBSERVATION_AUTHORIZE_CONFIRMATION});equal(auth.status,"AUTHORIZED");equal(auth.value.dailySpendCeilingUsd,.025);equal(auth.value.maxSpendUsd,.0015);
 const authReplay=await service.authorize({preparedObservationId:prepared.value.preparedObservationId,operator:"operator:test",reason:"fixture",expiresAt:"2026-09-14T01:00:00.000Z",confirmation:REPEAT_OBSERVATION_AUTHORIZE_CONFIRMATION});equal(authReplay.status,"DUPLICATE");
 await assert.rejects(()=>service.authorize({preparedObservationId:prepared.value.preparedObservationId,operator:"other",reason:"compete",expiresAt:"2026-09-14T02:00:00.000Z",confirmation:REPEAT_OBSERVATION_AUTHORIZE_CONFIRMATION}),/ACTIVE/);cases++;
 await assert.rejects(()=>service.authorize({preparedObservationId:prepared.value.preparedObservationId,operator:"x",reason:"x",expiresAt:"2026-09-14T02:00:00.000Z",confirmation:REPEAT_OBSERVATION_AUTHORIZE_CONFIRMATION,source:"BAD"}),/INPUT_INVALID/);cases++;
 const executed=await service.execute({authorizationId:auth.value.authorizationId,executedBy:"operator:test",confirmation:REPEAT_OBSERVATION_EXECUTE_CONFIRMATION});equal(executed.status,"COMPLETED");equal(calls.length,1);equal(calls[0].kind,"AMAZON_SELLERS");equal(calls[0].dataAsin,"B0BXHC74WD");
 const again=await service.execute({authorizationId:auth.value.authorizationId,executedBy:"operator:test",confirmation:REPEAT_OBSERVATION_EXECUTE_CONFIRMATION});equal(again.status,"LIVE_AUTHORIZATION_ALREADY_CONSUMED");equal(calls.length,1);
 await assert.rejects(()=>service.execute({authorizationId:auth.value.authorizationId,executedBy:"x",confirmation:REPEAT_OBSERVATION_EXECUTE_CONFIRMATION,product:"ram_9"}),/INPUT_INVALID/);cases++;
 await service.retrieve({preparedObservationId:prepared.value.preparedObservationId});equal(retrieved[0].providerTaskId,"provider-task");await service.processRetain({preparedObservationId:prepared.value.preparedObservationId,canonicalResultId:"result"});equal(processed.length,1);await service.assessAdmitFact({evidenceId:"evidence",action:"ASSESS",admittedBy:null});equal(facts[0][0],"ASSESS");
 const beforeCalls=calls.length;identities.set("ram_1",createAmazonRepeatObservationIdentity({atlasProductId:"ram_1",state:"STRONG_OPERATOR_CONFIRMED_ASIN",governedAsin:"B0DIFFER01",sellersAuthorizationEligible:true,confirmationId:"changed"}));const driftAuth=await service.authorize({preparedObservationId:confirmedPrepared.value.preparedObservationId,operator:"operator:test",reason:"drift",expiresAt:"2026-09-14T01:00:00.000Z",confirmation:REPEAT_OBSERVATION_AUTHORIZE_CONFIRMATION});await assert.rejects(()=>service.execute({authorizationId:driftAuth.value.authorizationId,executedBy:"operator:test",confirmation:REPEAT_OBSERVATION_EXECUTE_CONFIRMATION}),/IDENTITY_CHANGED/);cases++;equal(calls.length,beforeCalls);
 for(const size of [10,100,1000,10000]){const selected=[...products.keys()].slice(0,size);equal(selected.length,size);}ok(!calls.some(x=>["PRODUCTS","AMAZON_PRODUCTS"].includes(x.kind)));equal(retrieved.length,1);equal(processed.length,1);equal(facts.length,1);
 const source=await readFile(new URL("../repeat-observation/ProductionRepeatObservation.js",import.meta.url),"utf8");ok(!source.includes("ram_corsair_"));
}finally{service.close();await rm(root,{recursive:true,force:true});}
console.log(`Repeat observation production composition tests passed: ${cases} cases.`);
