import assert from "node:assert/strict";
import {mkdtemp,readFile,rm,writeFile} from "node:fs/promises";
import crypto from "node:crypto";
import os from "node:os";
import path from "node:path";
import {createHistoricalObservation,createRetainedCommerceCandidate,createRetainedCommerceHistoryPlan,prepareRetainedCommerceHistory,assertRetainedCommercePreparationCurrent,FileHistoricalObservationRepository,retainedCommerceDigest,validateHistoricalObservation,RetainedCommerceHistoryExecutionService,RETAINED_COMMERCE_HISTORY_EXECUTE_CONFIRMATION} from "../index.js";
const d="a".repeat(64),r="b".repeat(64),at="2026-10-01T12:25:49.000Z";
const input={providerId:"RAKUTEN_ADVERTISING",sourceId:"RAKUTEN_NEWEGG_PRODUCT_CATALOG",feedFamily:"RAKUTEN_MAIN:44583:4746097",artifactDigest:d,eventType:"FULL",validatedObservedAt:at,sourceProductId:"provider-product",sourceListingId:"N82E16800000001",atlasProductId:"ram_fixture",retailerId:"RETAILER-0004",selectedPriceSemantic:"SALE_PRICE",conditionProvenance:"CONTEXTUALLY_DERIVED",sourceRightsProfileId:"RAKUTEN_NEWEGG_PRODUCT_CATALOG",sourceRightsProfileDigest:r,basePrice:100,currency:"USD",condition:"NEW",availability:"in_stock",sellerName:null};
const candidate=createRetainedCommerceCandidate(input),later=createRetainedCommerceCandidate({...input,validatedObservedAt:"2026-10-02T10:54:14.000Z"});
assert.notEqual(candidate.historicalObservationId,later.historicalObservationId);assert.equal(candidate.basePrice,later.basePrice);
assert.equal(createRetainedCommerceCandidate(input).candidateDigest,candidate.candidateDigest);
const plan=createRetainedCommerceHistoryPlan({historyHash:d,historySequence:410,historyCount:410,rightsProfileDigest:r,candidates:[later,candidate],projectedImpact:{newRecords:2}}),replay=createRetainedCommerceHistoryPlan({historyHash:d,historySequence:410,historyCount:410,rightsProfileDigest:r,candidates:[candidate,later],projectedImpact:{newRecords:2}});assert.deepEqual(plan,replay);assert.equal(plan.authority,"NONE");
const prep=prepareRetainedCommerceHistory({plan});assert.equal(prep.historyMutationAuthorized,false);assert.equal(assertRetainedCommercePreparationCurrent({plan,preparation:prep,currentHistoryHash:d,currentHistorySequence:410,currentRightsProfileDigest:r,candidates:[candidate,later]}),true);
assert.throws(()=>assertRetainedCommercePreparationCurrent({plan,preparation:prep,currentHistoryHash:"c".repeat(64),currentHistorySequence:410,currentRightsProfileDigest:r,candidates:[candidate,later]}),/HISTORY_STALE/);
assert.throws(()=>assertRetainedCommercePreparationCurrent({plan,preparation:prep,currentHistoryHash:d,currentHistorySequence:410,currentRightsProfileDigest:"c".repeat(64),candidates:[candidate,later]}),/RIGHTS_STALE/);
assert.throws(()=>assertRetainedCommercePreparationCurrent({plan,preparation:prep,currentHistoryHash:d,currentHistorySequence:410,currentRightsProfileDigest:r,candidates:[{...candidate,artifactDigest:"c".repeat(64)},later]}),/ARTIFACT_OR_CANDIDATE_STALE/);
assert.throws(()=>createRetainedCommerceCandidate({...input,artifactDigest:"bad"}),/CANDIDATE_INVALID/);assert.throws(()=>createRetainedCommerceCandidate({...input,eventType:"DELETE"}),/CANDIDATE_INVALID/);
const acquisition={type:"RETAINED_COMMERCE_FEED",providerId:candidate.providerId,sourceId:candidate.sourceId,feedFamily:candidate.feedFamily,artifactDigest:candidate.artifactDigest,eventType:candidate.eventType,validatedObservedAt:candidate.validatedObservedAt,sourceProductId:candidate.sourceProductId,sourceListingId:candidate.sourceListingId,atlasProductId:candidate.atlasProductId,retailerId:candidate.retailerId,selectedPriceSemantic:candidate.selectedPriceSemantic,conditionProvenance:candidate.conditionProvenance,sourceRightsProfileId:candidate.sourceRightsProfileId,sourceRightsProfileDigest:candidate.sourceRightsProfileDigest};
const observation=createHistoricalObservation({factLevel:true,observationId:candidate.historicalObservationId,atlasProductId:candidate.atlasProductId,retailerId:candidate.retailerId,marketplace:"newegg.com",observationTime:candidate.validatedObservedAt,admittedAt:"2026-10-03T00:00:00.000Z",market:{basePrice:100,totalPrice:null,shipping:null,tax:null,currency:"USD",condition:"NEW",availability:"in_stock",sourceUrl:null,sellerName:null},provenance:{retainedEvidenceId:candidate.retainedEvidenceId,provider:candidate.providerId,source:candidate.sourceId,rawPayloadReference:candidate.rawPayloadReference,acquisition},observedMerchant:{sellerName:null,suppliedDomain:null,resolutionState:"UNRESOLVED",canonicalRetailerId:"RETAILER-0004",canonicalMerchantName:"Newegg",canonicalDomain:"newegg.com",decisionId:null},comparability:{policyVersion:"fixture",classification:"STANDALONE_COMPARABLE",reasons:[],standaloneEligible:true},admittedBy:"fixture",idempotencyKey:candidate.retainedEvidenceId});assert.equal(validateHistoricalObservation(observation).valid,true);
const root=await mkdtemp(path.join(os.tmpdir(),"retained-commerce-"));try{const file=path.join(root,"history.json"),repo=new FileHistoricalObservationRepository({statePath:file});await repo.accept(observation,observation.metadata.idempotencyKey);const restarted=new FileHistoricalObservationRepository({statePath:file});assert.deepEqual(await restarted.getById(observation.observationId),observation);assert.match(await readFile(file,"utf8"),/RETAINED_COMMERCE_FEED/);const invalid=structuredClone(observation);invalid.market.basePrice=-1;await assert.rejects(repo.acceptBatch([{record:invalid,idempotencyKey:invalid.metadata.idempotencyKey}]),/HISTORICAL_OBSERVATION_INVALID/);assert.equal((await repo.getAll()).length,1);const laterObservation=createHistoricalObservation({factLevel:true,observationId:later.historicalObservationId,atlasProductId:later.atlasProductId,retailerId:later.retailerId,marketplace:"newegg.com",observationTime:later.validatedObservedAt,admittedAt:"2026-10-03T00:00:01.000Z",market:structuredClone(observation.market),provenance:{...structuredClone(observation.provenance),retainedEvidenceId:later.retainedEvidenceId,rawPayloadReference:later.rawPayloadReference,acquisition:{...structuredClone(observation.provenance.acquisition),validatedObservedAt:later.validatedObservedAt}},observedMerchant:structuredClone(observation.observedMerchant),comparability:structuredClone(observation.comparability),admittedBy:"fixture",idempotencyKey:later.retainedEvidenceId});await assert.rejects(repo.acceptBatch([{record:observation,idempotencyKey:observation.metadata.idempotencyKey},{record:laterObservation,idempotencyKey:laterObservation.metadata.idempotencyKey}]),/BATCH_PARTIAL_CONFLICT/);assert.equal((await repo.getAll()).length,1);}finally{await rm(root,{recursive:true,force:true});}
const executionRoot=await mkdtemp(path.join(os.tmpdir(),"retained-commerce-execution-"));try{const file=path.join(executionRoot,"history.json"),initial=`${JSON.stringify({version:"1.0",sequence:0,records:{},idempotency:{}},null,2)}\n`;await writeFile(file,initial);const executionPlan=createRetainedCommerceHistoryPlan({historyHash:crypto.createHash("sha256").update(initial).digest("hex"),historySequence:0,historyCount:0,rightsProfileDigest:r,candidates:[candidate,later],projectedImpact:{newRecords:2}}),executionPrep=prepareRetainedCommerceHistory({plan:executionPlan}),reader=async()=>{const bytes=await readFile(file),state=JSON.parse(bytes);return{hash:crypto.createHash("sha256").update(bytes).digest("hex"),sequence:state.sequence,count:Object.keys(state.records).length};},repo=new FileHistoricalObservationRepository({statePath:file}),service=new RetainedCommerceHistoryExecutionService({historicalRepository:repo,historyStateReader:reader,now:()=>"2026-10-03T12:00:00.000Z"});const result=await service.execute({plan:executionPlan,preparation:executionPrep,confirmation:RETAINED_COMMERCE_HISTORY_EXECUTE_CONFIRMATION,executedBy:"fixture",currentRightsProfileDigest:r,candidates:[candidate,later]});assert.deepEqual({status:result.status,admitted:result.admitted,finalCount:result.finalCount,finalSequence:result.finalSequence},{status:"EXECUTED",admitted:2,finalCount:2,finalSequence:2});const replayResult=await service.execute({plan:executionPlan,preparation:executionPrep,confirmation:RETAINED_COMMERCE_HISTORY_EXECUTE_CONFIRMATION,executedBy:"fixture",currentRightsProfileDigest:r,candidates:[candidate,later]});assert.equal(replayResult.status,"ALREADY_EXECUTED");assert.equal((await repo.getAll()).length,2);}finally{await rm(executionRoot,{recursive:true,force:true});}
assert.equal(retainedCommerceDigest({x:1}),retainedCommerceDigest({x:1}));
console.log("Retained commerce History lineage/PREPARE tests passed.");
