import assert from "node:assert/strict";
import crypto from "node:crypto";
import {mkdtemp,rm} from "node:fs/promises";
import {join} from "node:path";
import {tmpdir} from "node:os";
import {createAmazonRepeatObservationIdentity,createGoogleRepeatObservationIdentity,createRepeatObservationPreparation,createRepeatObservationAuthorization,createReusableIdentityAcquisitionLineage,validateReusableIdentityAcquisitionLineage,createGovernedReusableIdentityProjection,validateGovernedReusableIdentityProjection,defaultSourceRightsRegistry,DataForSeoTaskLedger,FileHistoricalBootstrapProviderResultRepository,createHistoricalBootstrapProviderResult,ProductionRepeatObservationResultPipeline,DataForSeoAmazonHistoricalRetentionService,DataForSeoAcquisitionResultProcessor,SellersResultDf003RetentionService,FileDataForSeoMarketEvidenceRepository,FileHistoricalObservationRepository,HistoricalObservationAdmissionService} from "../index.js";

let cases=0;const at="2026-09-14T00:00:00.000Z",later="2026-09-14T00:01:00.000Z",product="ram_fixture",sha=v=>crypto.createHash("sha256").update(v).digest("hex"),rights=source=>defaultSourceRightsRegistry.require(source);
function prepared(source,state="automatic"){
 const reusableIdentity=source==="DATAFORSEO_AMAZON"?createAmazonRepeatObservationIdentity({atlasProductId:product,state:state==="operator"?"STRONG_OPERATOR_CONFIRMED_ASIN":"STRONG_UNIQUE_ASIN",governedAsin:"B0CQQVNCB6",sellersAuthorizationEligible:true,confirmationId:state==="operator"?"confirm-1":undefined,outcomeId:"outcome-1"}):createGoogleRepeatObservationIdentity({atlasProductId:product,state:"REUSED",providerIdentity:{productId:"google-product",dataDocId:"google-doc",gid:null},sourceEvidenceId:"source-evidence",contradictionStatus:"NONE"});
 const preparation=createRepeatObservationPreparation({atlasProductId:product,source,observationCycle:at,reusableIdentity,rightsProfile:rights(source)}),authorization=createRepeatObservationAuthorization({preparation,operator:"fixture",reason:"fixture",authorizedAt:at,expiresAt:"2026-09-14T01:00:00.000Z",currentUtcDaySpendUsd:0});return{preparation,authorization};
}
function taskFor(preparation,authorization,id="provider-task"){return{requestKey:`key-${id}`,kind:preparation.operation,taskId:id,costUsd:preparation.taskCostUsd,createdStatus:20100,sourceId:preparation.source,atlasProductId:preparation.atlasProductId,asin:preparation.reusableIdentity.asin??null,requestDigest:sha("request"),paidActionIntentId:preparation.paidActionIntentId,acquisitionCycleId:preparation.acquisitionCycleId,preparedObservationId:preparation.preparedObservationId,reusableIdentityDigest:preparation.reusableIdentity.identityDigest,sourceRightsProfileDigest:preparation.sourceRightsProfileDigest,repeatAuthorizationId:authorization.authorizationId};}
function resultFor(preparation,task,operationResult={id:task.taskId,cost:0,result:[{items:[]}]}){return createHistoricalBootstrapProviderResult({operation:task.kind,sourceId:task.sourceId,providerTaskId:task.taskId,paidActionIntentId:task.paidActionIntentId,acquisitionReferenceId:preparation.preparedObservationId,atlasProductId:task.atlasProductId,sourceRightsProfileDigest:task.sourceRightsProfileDigest,requestIdentityDigest:task.requestDigest,operationResult,retrievedAt:later});}

for(const [source,state] of [["DATAFORSEO_AMAZON","automatic"],["DATAFORSEO_AMAZON","operator"],["DATAFORSEO_GOOGLE_SHOPPING","automatic"]]){const{preparation,authorization}=prepared(source,state),task=taskFor(preparation,authorization),result=resultFor(preparation,task),lineage=createReusableIdentityAcquisitionLineage({preparation,authorization,task,canonicalResult:result});assert.equal(validateReusableIdentityAcquisitionLineage(lineage).valid,true);assert.equal(lineage.atlasProductId,product);assert.equal(lineage.providerTaskId,task.taskId);cases+=3;}
{
 const{preparation,authorization}=prepared("DATAFORSEO_AMAZON"),task=taskFor(preparation,authorization),result=resultFor(preparation,task),lineage=createReusableIdentityAcquisitionLineage({preparation,authorization,task,canonicalResult:result});
 for(const bad of [{...lineage,reusableIdentityType:"AMBIGUOUS"},{...lineage,providerIdentity:{asin:"BAD"}},{...lineage,paidActionIntentId:"mer_repeatintent_"+"f".repeat(24)},{...lineage,acquisitionCycleId:"mer_repeatcycle_"+"f".repeat(24)},{...lineage,sourceRightsProfileDigest:"f".repeat(64)}])assert.equal(validateReusableIdentityAcquisitionLineage(bad).valid,false);cases+=5;
 assert.throws(()=>createReusableIdentityAcquisitionLineage({preparation,authorization,task:{...task,taskId:"other"},canonicalResult:result}),/TASK_BINDING|RESULT_BINDING/);cases++;
 const projection=createGovernedReusableIdentityProjection({lineage,evidenceId:"evidence-1",rawPayloadReference:`dataforseo:amazon:sellers:${task.taskId}:item:0`});assert.equal(validateGovernedReusableIdentityProjection(projection).valid,true);assert.equal(projection.effectiveProductState,"VERIFIED");cases+=2;
}
{
 const ledger=new DataForSeoTaskLedger(),amazon=prepared("DATAFORSEO_AMAZON"),valid=taskFor(amazon.preparation,amazon.authorization);ledger.record(valid.requestKey,valid);assert.equal(ledger.getByPaidActionIntentId(valid.paidActionIntentId).length,1);cases++;
 const bootstrap={kind:"SELLERS",taskId:"bootstrap-task",paidActionIntentId:"mer_histbootintent_"+"a".repeat(24)};ledger.record("bootstrap",bootstrap);assert.equal(ledger.get("bootstrap").taskId,"bootstrap-task");cases++;
 assert.throws(()=>ledger.record("unknown",{...valid,taskId:"unknown",paidActionIntentId:"unknown"}),/INTENT_INVALID/);cases++;
 assert.throws(()=>ledger.record("wrong-kind",{...valid,taskId:"wrong",kind:"PRODUCTS"}),/REPEAT_INTENT_LINEAGE_INVALID/);cases++;
 assert.throws(()=>ledger.record(valid.requestKey,valid),/DUPLICATE_PAID_TASK/);cases++;
 assert.throws(()=>ledger.record("rebound",{...valid,taskId:"changed"}),/PAID_ACTION_INTENT_CONFLICT/);cases++;
}

const root=await mkdtemp(join(tmpdir(),"hr-repeat-lineage-"));
try{
 const pair=prepared("DATAFORSEO_AMAZON"),task=taskFor(pair.preparation,pair.authorization),taskLedger=new DataForSeoTaskLedger();taskLedger.record(task.requestKey,task);const resultRepository=new FileHistoricalBootstrapProviderResultRepository({statePath:join(root,"results.json")}),repeatRepository={getPreparation:async id=>id===pair.preparation.preparedObservationId?pair.preparation:null,getAuthorization:async id=>id===pair.authorization.authorizationId?pair.authorization:null};let retrieval={status:"PENDING"},calls=0,processed=0;
 const pipeline=new ProductionRepeatObservationResultPipeline({repeatRepository,taskLedger,resultRepository,retrievalOwners:{AMAZON_SELLERS:{retrieve:async()=>{calls++;return retrieval;}}},processingOwners:{AMAZON_SELLERS:{process:async({lineage})=>{processed++;assert.equal(validateReusableIdentityAcquisitionLineage(lineage).valid,true);return{evidenceIds:["evidence-1"],duplicates:0};}}},now:()=>later});
 assert.equal((await pipeline.retrieveMember({preparedObservationId:pair.preparation.preparedObservationId})).status,"PENDING");cases++;retrieval={status:"PROVIDER_FAILED"};assert.equal((await pipeline.retrieveMember({preparedObservationId:pair.preparation.preparedObservationId})).status,"FAILED");cases++;
 retrieval={id:task.taskId,cost:0,result:[{asin:"B0CQQVNCB6",datetime:later,items:[]}]};const available=await pipeline.retrieveMember({preparedObservationId:pair.preparation.preparedObservationId});assert.equal(available.status,"AVAILABLE");assert.match(available.canonicalResultId,/^mer_providerresult_/);cases+=2;const before=calls,replay=await pipeline.retrieveMember({preparedObservationId:pair.preparation.preparedObservationId});assert.equal(replay.canonicalResultId,available.canonicalResultId);assert.equal(calls,before);cases+=2;
 const retained=await pipeline.processRetainMember({preparedObservationId:pair.preparation.preparedObservationId,canonicalResultId:available.canonicalResultId});assert.deepEqual(retained.evidenceIds,["evidence-1"]);assert.equal(processed,1);cases+=2;
 const ambiguousLedger={getAll:()=>[task,{...task,requestKey:"other",taskId:"other-task"}]},ambiguous=new ProductionRepeatObservationResultPipeline({repeatRepository,taskLedger:ambiguousLedger,resultRepository,retrievalOwners:{},processingOwners:{}});await assert.rejects(()=>ambiguous.resolveTask(pair.preparation),/AMBIGUOUS/);cases++;

 const evidenceRepository=new FileDataForSeoMarketEvidenceRepository({statePath:join(root,"evidence.json"),now:()=>later}),historyRepository=new FileHistoricalObservationRepository({statePath:join(root,"history.json")}),canonical=await resultRepository.getCanonicalResultById(available.canonicalResultId),lineage=createReusableIdentityAcquisitionLineage({preparation:pair.preparation,authorization:pair.authorization,task,canonicalResult:canonical}),retention=new DataForSeoAmazonHistoricalRetentionService({evidenceRepository}),sellerItem={data_asin:"B0CQQVNCB6",seller_name:"Unregistered Seller",seller_url:"https://amazon.com/item",price:{current:99.99,currency:"USD"},condition:"New"},retainedAmazon=await retention.retain({sellerItem,atlasProductId:product,identityAssessment:null,sellersTaskId:task.taskId,immutableResult:canonical,observedAt:later,rawPayloadReference:`dataforseo:amazon:sellers:${task.taskId}:item:0`,reusableIdentityLineage:lineage});assert.equal(retainedAmazon.status,"RETAINED");cases++;
 const governance=async({record})=>({acquisitionChain:lineage,reusableIdentityAcquisitionProjections:[createGovernedReusableIdentityProjection({lineage,evidenceId:record.evidenceId,rawPayloadReference:record.candidate.marketEvidence.provenance.rawPayloadReference})]}),admission=new HistoricalObservationAdmissionService({evidenceRepository,decisionRepository:{getAll:async()=>[],getAllRemediations:async()=>[]},productRepository:{getById:async id=>id===product?{identity:{atlasProductId:product}}:null},retailerRepository:{getAll:async()=>[]},historicalRepository:historyRepository,acquisitionChainResolver:async()=>{throw new Error("INITIAL_NOT_ALLOWED");},reusableIdentityGovernanceResolver:governance,now:()=>"2026-09-14T00:02:00.000Z"}),assessment=await admission.assess({evidenceId:retainedAmazon.evidenceId});assert.equal(assessment.historicalEligible,true);assert.equal(assessment.canonicalEligible,false);assert.equal(assessment.publicationEligible,false);assert.equal(assessment.expectedObservation.retailerId,null);cases+=4;
 const admitted=await admission.admit({evidenceId:retainedAmazon.evidenceId,admittedBy:"machine:fixture"});assert.equal(admitted.status,"ADMITTED");assert.equal(admitted.observation.provenance.acquisition.type,"REUSABLE_IDENTITY_REPEAT");cases+=2;assert.equal((await admission.admit({evidenceId:retainedAmazon.evidenceId,admittedBy:"machine:fixture"})).status,"DUPLICATE");cases++;
 const google=prepared("DATAFORSEO_GOOGLE_SHOPPING"),googleTask=taskFor(google.preparation,google.authorization,"google-task"),googleResult=resultFor(google.preparation,googleTask,{id:"google-task",cost:0,result:[{product_id:"google-product",data_docid:"google-doc",gid:null,title:"Fixture RAM",items:[{type:"shops_list",seller_name:"Fixture Seller",domain:"example.com",url:"https://example.com/ram",base_price:89.99,total_price:89.99,shipping_price:null,tax:null,currency:"USD",product_condition:null,product_availability:"in_stock"}]}]}),googleLineage=createReusableIdentityAcquisitionLineage({preparation:google.preparation,authorization:google.authorization,task:googleTask,canonicalResult:googleResult}),googleEvidence=new FileDataForSeoMarketEvidenceRepository({statePath:join(root,"google-evidence.json"),now:()=>later}),googleProcessor=new DataForSeoAcquisitionResultProcessor({atlasResolver:{resolve:async()=>{throw new Error("DISCOVERY_MUST_NOT_RUN");}},evidenceRepository:googleEvidence,retailers:[]}),googleRetention=new SellersResultDf003RetentionService({resultProcessor:googleProcessor}),googleRetained=await googleRetention.retain({sellersResult:googleResult.operationResult,productInfoResult:null,sellersTaskId:googleTask.taskId,productInfoTaskId:null,observedAt:later,providerIdentity:googleLineage.providerIdentity,candidateId:google.preparation.preparedObservationId,governedAcquisition:{identityLineageType:"REUSABLE_IDENTITY_REPEAT_LINEAGE",createProjection:({rawPayloadReference})=>createGovernedReusableIdentityProjection({lineage:googleLineage,evidenceId:null,rawPayloadReference})}});assert.equal(googleRetained.retained,1);assert.equal(googleRetained.integrations[0].productIdentityOutcome,"CONFIRMED");assert.equal(googleRetained.integrations[0].merchantIdentityOutcome,"DISCOVERED");cases+=3;
 const googleRecord=(await googleEvidence.getAll())[0],googleHistory=new FileHistoricalObservationRepository({statePath:join(root,"google-history.json")}),googleAdmission=new HistoricalObservationAdmissionService({evidenceRepository:googleEvidence,decisionRepository:{getAll:async()=>[],getAllRemediations:async()=>[]},productRepository:{getById:async id=>id===product?{identity:{atlasProductId:product}}:null},retailerRepository:{getAll:async()=>[]},historicalRepository:googleHistory,acquisitionChainResolver:async()=>{throw new Error("INITIAL_NOT_ALLOWED");},reusableIdentityGovernanceResolver:async()=>({acquisitionChain:googleLineage,reusableIdentityAcquisitionProjections:[createGovernedReusableIdentityProjection({lineage:googleLineage,evidenceId:googleRecord.evidenceId,rawPayloadReference:googleRecord.candidate.marketEvidence.provenance.rawPayloadReference})]}),now:()=>"2026-09-14T00:02:00.000Z"}),googleAssessment=await googleAdmission.assess({evidenceId:googleRecord.evidenceId});assert.equal(googleAssessment.historicalEligible,true);assert.equal(googleAssessment.expectedObservation.retailerId,null);cases+=2;
 const conflict=structuredClone(canonical);conflict.operationResult.result[0].items=[{price:{current:101}}];conflict.resultDigest=sha(JSON.stringify(conflict.operationResult));await assert.rejects(()=>resultRepository.record(conflict),/CONFLICT/);cases++;
}finally{await rm(root,{recursive:true,force:true});}

console.log(`Reusable identity acquisition lineage tests passed: ${cases} cases.`);
