import assert from "node:assert/strict";
import { mkdtemp, rm } from "node:fs/promises";
import os from "node:os";
import path from "node:path";
import { createRetailerDestination } from "../destinations/RetailerDestination.js";
import { FileHistoricalObservationRepository } from "../historical-admission/persistence/FileHistoricalObservationRepository.js";
import { defaultSourceRightsRegistry } from "../rights/SourceRightsRegistry.js";
import { createCurrentDisplaySnapshot, FileCurrentDisplaySnapshotRepository, FileManualCurrentPricePreparationRepository, FileManualCurrentPriceSnapshotExecutionRepository, ManualCurrentPriceHistoryService, ManualCurrentPriceSnapshotExecutionService, prepareManualCurrentPriceObservation, RoutineManualCurrentPriceProcessingService } from "../current-display/index.js";

let cases=0;const eq=(a,b)=>{assert.deepEqual(a,b);cases++},ok=v=>{assert.equal(v,true);cases++};
const preparedAt="2026-09-20T04:00:00.000Z",processedAt="2026-09-20T05:00:00.000Z";
const retailers={"RETAILER-0001":{id:"RETAILER-0001",name:"Amazon",websiteUrl:"https://amazon.com",status:"active"},"RETAILER-0004":{id:"RETAILER-0004",name:"Newegg",websiteUrl:"https://newegg.com",status:"active"}};
const source=id=>id==="RETAILER-0001"?"AMAZON_MANUAL_PUBLISHER_OBSERVATION":"NEWEGG_MANUAL_PUBLISHER_OBSERVATION";
const products=Array.from({length:4},(_,index)=>({identity:{atlasProductId:`ram_fixture_routine_${index+1}`,productType:"ram",brand:"Fixture",manufacturerPartNumber:`ROUTINE-${index+1}`,displayName:`Routine ${index+1}`},governance:{lifecycleStatus:"ACTIVE",publicationStatus:"READY"},extension:{data:{classification:{memoryType:"DDR5",formFactor:"DIMM"},capacity:{capacityGb:32,moduleCount:2,capacityPerModuleGb:16}}}}));
const destinations=[];for(const product of products)for(const retailerId of Object.keys(retailers)){const amazon=retailerId==="RETAILER-0001",listing=amazon?`B000RT${product.identity.atlasProductId.at(-1)}`:`N82RT${product.identity.atlasProductId.at(-1)}`;destinations.push(createRetailerDestination({atlasProductId:product.identity.atlasProductId,retailerId,marketplace:amazon?"amazon.com":"newegg.com",destinationType:"PRODUCT_PAGE",destinationUrl:amazon?`https://amazon.com/dp/${listing}`:`https://newegg.com/p/${listing}`,retailerListingId:listing,binding:{manufacturerPartNumber:product.identity.manufacturerPartNumber,method:"OPERATOR_EXACT_PRODUCT_REVIEW",scope:"EXACT_STANDALONE_PRODUCT",evidenceReferences:["fixture"]},provenance:{sourceType:"OPERATOR_INSPECTED_PUBLIC_PAGE"},reviewedBy:"fixture",reviewedAt:preparedAt,status:"ACTIVE",createdAt:preparedAt,createdBy:"fixture"}));}

async function fixture(){const dir=await mkdtemp(path.join(os.tmpdir(),"routine-manual-")),preparationRepository=new FileManualCurrentPricePreparationRepository({filePath:path.join(dir,"preparations.json")}),snapshotRepository=new FileCurrentDisplaySnapshotRepository({statePath:path.join(dir,"snapshots.json")}),executionRepository=new FileManualCurrentPriceSnapshotExecutionRepository({filePath:path.join(dir,"executions.json")}),historicalRepository=new FileHistoricalObservationRepository({statePath:path.join(dir,"history.json")});const productResolver=async id=>products.find(x=>x.identity.atlasProductId===id),retailerResolver=async id=>retailers[id],destinationResolver=async id=>destinations.find(x=>x.destinationId===id);const snapshotExecutionService=new ManualCurrentPriceSnapshotExecutionService({preparationRepository,snapshotRepository,executionRepository,productResolver,retailerResolver,destinationResolver,rightsResolver:async id=>defaultSourceRightsRegistry.require(id),now:()=>processedAt}),historyService=new ManualCurrentPriceHistoryService({historicalRepository,rightsRegistry:defaultSourceRightsRegistry,now:()=>processedAt}),service=new RoutineManualCurrentPriceProcessingService({preparationRepository,snapshotExecutionService,executionRepository,snapshotRepository,historyService,productResolver,retailerResolver,destinationResolver,now:()=>processedAt});return{dir,preparationRepository,snapshotRepository,executionRepository,historicalRepository,service,close:()=>rm(dir,{recursive:true,force:true})};}
function preparation(productIndex,retailerId,price,{shippingUsd=0,condition="NEW",seller="Fixture Seller",observedAt="2026-09-20T03:00:00.000Z",submitted=true}={}){const product=products[productIndex],retailer=retailers[retailerId],destination=destinations.find(x=>x.atlasProductId===product.identity.atlasProductId&&x.retailerId===retailerId);return prepareManualCurrentPriceObservation({input:{atlasProductId:product.identity.atlasProductId,destinationId:destination.destinationId,itemPriceUsd:price,currency:"USD",availability:"AVAILABLE",condition,shippingUsd,seller,researchUrl:destination.destinationUrl,observedAt,observedBy:"operator",evidenceReference:`manual-workbook:${product.identity.atlasProductId}:${retailerId}:${observedAt}`,operatorEvidence:{acquisitionMode:"MANUAL",rawCondition:condition??"UNKNOWN",rawShipping:shippingUsd??"UNKNOWN",rawSeller:seller??"UNKNOWN",submittedForProcessing:submitted,rawReadyForImport:submitted?"YES":"NO"}},product,retailer,destination,rightsProfile:defaultSourceRightsRegistry.require(source(retailerId)),preparedAt});}

{
 const f=await fixture();try{
  const cohort=[preparation(0,"RETAILER-0004",100),preparation(1,"RETAILER-0004",120,{shippingUsd:12.99}),preparation(2,"RETAILER-0004",140),preparation(2,"RETAILER-0001",150,{shippingUsd:null}),preparation(3,"RETAILER-0004",160),preparation(3,"RETAILER-0001",170)];for(const p of cohort)await f.preparationRepository.record(p);
  const result=await f.service.processCohort({preparationIds:cohort.map(x=>x.preparationId),processedAt,processedBy:"fixture"});eq(result.attempted,6);eq(result.routineProgressed,6);eq(result.currentUpdated,6);eq(result.historyRetained,6);eq(result.comparisonsAvailable,2);eq((await f.historicalRepository.getAll()).length,6);eq((await f.executionRepository.getState()).authorizations.length,6);eq((await f.executionRepository.getState()).executions.length,6);
  const state=await f.snapshotRepository.getState();eq(state.current.offers.length,6);const known=state.current.offers.find(x=>x.priceUsd===100);eq(known.condition,"NEW");eq(known.shippingUsd,0);eq(known.sellerName,"Fixture Seller");ok(known.researchUrl.startsWith("https://"));eq(known.operatorEvidence.acquisitionMode,"MANUAL");const positive=state.current.offers.find(x=>x.priceUsd===120);eq(positive.shippingUsd,12.99);const unknown=state.current.offers.find(x=>x.priceUsd===150);eq(unknown.shippingUsd,null);
  const replay=await f.service.processCohort({preparationIds:cohort.map(x=>x.preparationId),processedAt,processedBy:"fixture"});eq(replay.alreadyProcessed,6);eq((await f.historicalRepository.getAll()).length,6);eq((await f.executionRepository.getState()).executions.length,6);
 }finally{await f.close();}
}
{
 const f=await fixture();try{const valid=preparation(0,"RETAILER-0004",100),notSubmitted=preparation(1,"RETAILER-0004",120,{submitted:false}),conflict=preparation(2,"RETAILER-0004",140);for(const p of [valid,notSubmitted,conflict])await f.preparationRepository.record(p);const automated={atlasProductId:products[2].identity.atlasProductId,retailer:"NEWEGG",retailerId:"RETAILER-0004",marketplace:"newegg.com",priceUsd:139,currency:"USD",availability:"AVAILABLE",condition:"NEW",shippingUsd:null,feesUsd:null,researchUrl:conflict.binding.researchUrl,destinationId:conflict.binding.destinationId,matchStatus:"GOVERNED_AUTOMATED_EXACT_PRODUCT",sourceRow:1,observedAt:"2026-09-20T03:10:00.000Z",sourceIdentity:{adapterId:"fixture",sourceId:"RAKUTEN_NEWEGG_PRODUCT_CATALOG",rightsProfileId:"RAKUTEN_NEWEGG_PRODUCT_CATALOG",historicalRetentionAllowed:false},itemPriceEligible:true,comparisonEligible:true,comparisonReasons:[],deliveredCostEligible:false,deliveredCostReasons:["SHIPPING_COST_UNKNOWN","FEES_UNKNOWN"]};await f.snapshotRepository.replace(createCurrentDisplaySnapshot({observedAt:preparedAt,importedAt:preparedAt,source:{workbook:"fixture",sheet:"fixture",digest:"a".repeat(64)},offers:[automated]}));const result=await f.service.processCohort({preparationIds:[notSubmitted.preparationId,valid.preparationId,conflict.preparationId,"mer_manualpriceprep_000000000000000000000000"],processedAt,processedBy:"fixture"});eq(result.routineProgressed,2);eq(result.reviewRequired,3);eq(result.failedSafe,0);eq(result.currentUpdated,1);eq(result.historyRetained,2);ok(result.results.find(x=>x.preparationId===conflict.preparationId).exceptions.includes("CURRENT_SOURCE_CONFLICT_REVIEW_REQUIRED"));
 }finally{await f.close();}
}
{
 const f=await fixture();try{const stale=preparation(3,"RETAILER-0004",160,{observedAt:"2026-09-18T17:30:00.000Z"}),staleAt="2026-09-20T06:00:00.000Z";await f.preparationRepository.record(stale);const assessment=await f.service.assess({preparationId:stale.preparationId,asOf:staleAt});eq(assessment.classification,"STALE_FOR_CURRENT_BUT_HISTORY_ELIGIBLE");const result=await f.service.processOne({preparationId:stale.preparationId,processedAt:staleAt,processedBy:"fixture"});eq(result.status,"HISTORY_RETAINED_CURRENT_STALE");eq(result.current.status,"STALE_NOT_CURRENT");eq(result.history.status,"RETAINED");eq((await f.snapshotRepository.getState()).current,null);eq((await f.historicalRepository.getAll()).length,1);
 }finally{await f.close();}
}
{
 const f=await fixture();try{const incompatible=preparation(0,"RETAILER-0004",100,{condition:"USED"});await f.preparationRepository.record(incompatible);const assessment=await f.service.assess({preparationId:incompatible.preparationId,asOf:processedAt});eq(assessment.classification,"REVIEW_REQUIRED");ok(assessment.current.reasons.length>0);}finally{await f.close();}
}
console.log(`Routine manual current-price processing tests passed: ${cases} cases.`);
