import assert from "node:assert/strict";
import {mkdtemp,readFile,rm} from "node:fs/promises";
import {join} from "node:path";
import {tmpdir} from "node:os";
import {performance} from "node:perf_hooks";
import {NeutralBoundedPaidActionCoordinator,SqliteNeutralBoundedRepository} from "../bounded/index.js";
import {scaleRampCanaryDigest,selectScaleRampCanary,selectorProposalCohort,validateScaleRampSelectorProposal} from "../scale-ramp/index.js";
import {parseIdentityDiscoveryArgs,runIdentityDiscoveryCommand} from "../../../scripts/mercury-products-identity-discovery-runtime.mjs";

let cases=0;const eq=(a,b)=>{assert.deepEqual(a,b);cases++},hex="a".repeat(64),cycle="2026-09-18T00:00:00.000Z";
const candidates=size=>Array.from({length:size},(_,i)=>({atlasProductId:`ram_fixture_${String(i).padStart(4,"0")}`,manufacturer:["Corsair","Crucial","G.SKILL","Kingston","TeamGroup"][i%5],memoryGeneration:i%3?"DDR5":"DDR4",formFactor:i%4?"DIMM":"SO_DIMM",capacityGb:[8,16,32,64][i%4],moduleCount:i%5?2:1}));
const proposal=size=>({...selectScaleRampCanary({stageId:"stage-fixture",stageCohortDigest:hex,source:"DATAFORSEO_AMAZON",operation:"AMAZON_PRODUCTS",requestedCanarySize:size,candidates:candidates(size+4)}),stagePolicyId:"MERCURY_FIXTURE_SLICE",stagePolicyVersion:"1.0"});
const adapter={prepareMember:async({request})=>({memberKey:`${request.sourceId}:${request.atlasProductId}`,domainMemberId:`domain:${request.atlasProductId}`,atlasProductId:request.atlasProductId,source:request.sourceId,operation:"AMAZON_PRODUCTS",taskCeilingUsd:.0015}),revalidateMember:async()=>{},advanceMember:async()=>{},classifyFailure:error=>({classification:"MEMBER_LOCAL_FAILURE",state:"REVIEW_REQUIRED",reason:String(error.message)}),summarize:run=>run};
const root=await mkdtemp(join(tmpdir(),"selector-prepare-"));
try{
 const valid=proposal(8),provenance=validateScaleRampSelectorProposal(valid,{reference:"fixture.json"}),cohort=selectorProposalCohort(provenance);
 eq(cohort.length,8);eq(cohort.map(x=>x.atlasProductId),valid.selectedMembers.map(x=>x.atlasProductId));eq(provenance.source,"DATAFORSEO_AMAZON");eq(provenance.operation,"AMAZON_PRODUCTS");eq(provenance.proposalId,`mer_scaleproposal_${provenance.proposalDigest.slice(0,24)}`);
 for(const mutation of[
   value=>({...value,authority:"PAID"}),value=>({...value,prepareAuthorized:true}),value=>({...value,executionAuthorized:true}),value=>({...value,policyVersion:"2.0"}),value=>({...value,source:"DATAFORSEO_GOOGLE_SHOPPING"}),value=>({...value,operation:"PRODUCTS"}),value=>({...value,candidatePoolDigest:"b".repeat(64)}),value=>({...value,selectedMemberDigest:"b".repeat(64)}),value=>({...value,requestedCanarySize:7}),value=>({...value,selectedMembers:[...value.selectedMembers,value.selectedMembers[0]]}),value=>({...value,providerTaskId:"forbidden"})
 ])assert.throws(()=>validateScaleRampSelectorProposal(mutation(valid)));cases++;
 const repo=new SqliteNeutralBoundedRepository({databasePath:join(root,"state.sqlite")}),coordinator=new NeutralBoundedPaidActionCoordinator({repository:repo,domainAdapter:adapter,spendResolver:async()=>0,now:()=>cycle,dailySpendCeilingUsd:.05,policyVersion:"MERCURY-PRODUCTS-IDENTITY-DISCOVERY-1.0",idPrefixes:{plan:"plan",authorization:"auth",run:"run"}});
 const direct=await coordinator.prepare({cycle,cohort,selectionProvenance:provenance});eq(direct.value.selectionInputType,"SELECTOR_PROPOSAL");eq(direct.value.selectionProvenance.proposalDigest,provenance.proposalDigest);eq(direct.value.authorizationState,"NOT_AUTHORIZED");eq(direct.value.providerSpendAuthorized,false);eq((await coordinator.inspect({planId:direct.value.planId})).selectorMembershipEquivalent,true);eq((await coordinator.prepare({cycle,cohort,selectionProvenance:provenance})).status,"DUPLICATE");
 repo.close();const reopened=new SqliteNeutralBoundedRepository({databasePath:join(root,"state.sqlite")});eq(reopened.getPlan(direct.value.planId).selectionProvenance,provenance);reopened.close();
 const legacyRepo=new SqliteNeutralBoundedRepository({databasePath:join(root,"legacy.sqlite")}),legacyCoordinator=new NeutralBoundedPaidActionCoordinator({repository:legacyRepo,domainAdapter:adapter,spendResolver:async()=>0,now:()=>cycle,dailySpendCeilingUsd:.05,policyVersion:"MERCURY-PRODUCTS-IDENTITY-DISCOVERY-1.0"}),legacy=await legacyCoordinator.prepare({cycle,cohort});eq(legacy.value.selectionInputType,"LEGACY_COHORT_INPUT");eq((await legacyCoordinator.inspect({planId:legacy.value.planId})).selectionProvenance,null);assert.notEqual(legacy.value.bindingDigest,direct.value.bindingDigest);cases++;legacyRepo.close();
 const driftRepo=new SqliteNeutralBoundedRepository({databasePath:join(root,"drift.sqlite")}),driftAdapter={...adapter,prepareMember:async({request})=>{if(request.atlasProductId===cohort[0].atlasProductId)throw new Error("PRODUCTS_DISCOVERY_NOT_READY:ALREADY_RESOLVED");return adapter.prepareMember({request})}},driftCoordinator=new NeutralBoundedPaidActionCoordinator({repository:driftRepo,domainAdapter:driftAdapter,spendResolver:async()=>0,now:()=>cycle,dailySpendCeilingUsd:.05,policyVersion:"MERCURY-PRODUCTS-IDENTITY-DISCOVERY-1.0"}),drift=await driftCoordinator.prepare({cycle,cohort,selectionProvenance:provenance});eq(drift.value.requested.length,8);eq(drift.value.ready.length,7);eq(drift.value.blocked.length,1);eq(drift.value.selectionProvenance.selectedAtlasProductIds,valid.selectedMembers.map(x=>x.atlasProductId));driftRepo.close();
 const scale=[];for(const size of[8,24,100,1000]){const started=performance.now(),p=proposal(size),binding=validateScaleRampSelectorProposal(p),rows=selectorProposalCohort(binding);eq(rows.length,size);scale.push({size,elapsedMs:Number((performance.now()-started).toFixed(2)),digest:binding.proposalDigest});}assert.equal(new Set(scale.map(x=>x.digest)).size,4);cases++;
 const fakeCalls=[],fake={service:{prepare:async input=>(fakeCalls.push(input),{status:"PREPARED",value:input})}};await runIdentityDiscoveryCommand("prepare",[`--selector-proposal-file=fixture.json`,`--discovery-cycle=${cycle}`],{runtime:fake,readJson:async()=>valid});eq(fakeCalls[0].selectionProvenance.proposalDigest,provenance.proposalDigest);eq(fakeCalls[0].cohort,cohort);eq(parseIdentityDiscoveryArgs("prepare",[`--selector-proposal-file=x`,`--discovery-cycle=${cycle}`]).size,2);await assert.rejects(()=>runIdentityDiscoveryCommand("prepare",[`--cohort-file=a`,`--selector-proposal-file=b`,`--discovery-cycle=${cycle}`],{runtime:fake,readJson:async()=>valid}),/PREPARE_SOURCE_REQUIRED/);cases++;
 const historical=JSON.parse(await readFile("config/mercury/scale-ramp/100-product-first-amazon-products-canary-review.json","utf8")),historicalCohort=JSON.parse(await readFile("config/mercury/scale-ramp/100-product-first-amazon-products-canary-cohort.json","utf8")),historicalBinding=validateScaleRampSelectorProposal(historical);eq(historical.selectedMemberDigest,"0a17e9ba2e71b1adf8f7f29a4896effe01ac991756dc338c5a2ba86bd8534eb1");eq(selectorProposalCohort(historicalBinding).map(x=>x.atlasProductId).sort(),historicalCohort.map(x=>x.atlasProductId).sort());
 console.log(`Selector proposal direct-PREPARE tests passed: ${cases} cases. Scale: ${JSON.stringify(scale)}`);
}finally{await rm(root,{recursive:true,force:true,maxRetries:5,retryDelay:50});}
