import assert from 'node:assert/strict';import {mkdtemp,rm} from 'node:fs/promises';import {tmpdir} from 'node:os';import {join} from 'node:path';
import {createAcquisitionBudgetPolicy,createScheduledDryRunConfig,isScheduledDryRunDue,FileScheduledDryRunAuditRepository,ScheduledDryRunRunner,FileSingleWriterRunLock} from '../index.js';
const dir=await mkdtemp(join(tmpdir(),'hr-e1-'));try{
 const config=createScheduledDryRunConfig({timeZone:'America/Jamaica',intervalMinutes:60});assert.equal(config.mode,'DRY_RUN');assert.equal(config.paidTransportReachable,false);assert.throws(()=>createScheduledDryRunConfig({timeZone:'Mars/Kingston'}),/IANA/);assert.throws(()=>createScheduledDryRunConfig({intervalMinutes:59}),/at least 60/);
 assert.equal(isScheduledDryRunDue({lastRunAt:null,now:'2026-08-18T00:00:00Z',config}),true);assert.equal(isScheduledDryRunDue({lastRunAt:'2026-08-18T00:00:00Z',now:'2026-08-18T00:30:00Z',config}),false);
 let times=['2026-08-18T00:00:00Z','2026-08-18T00:00:01Z','2026-08-18T00:00:02Z'];const now=()=>times.shift()??'2026-08-18T00:00:03Z';const lock=new FileSingleWriterRunLock({lockPath:join(dir,'lock'),heartbeatIntervalMs:1000,staleAfterMs:5000});const repo=new FileScheduledDryRunAuditRepository({filePath:join(dir,'audit.json')});const runner=new ScheduledDryRunRunner({lock,auditRepository:repo,config,now});const policy=createAcquisitionBudgetPolicy({enabled:true});
 const r=await runner.run({policy,candidates:[{candidateId:'corsair',priority:'HIGH',estimatedCostUsd:.001,execution:{kind:'SELLERS'}}]});assert.equal(r.status,'COMPLETED');assert.equal(r.mode,'DRY_RUN');assert.equal(r.attemptedPaidTasks,0);assert.equal(r.actualSpendUsd,0);const state=await repo.read();assert.equal(state.runs.length,1);assert.equal(state.runs[0].simulation.attemptedPaidTasks,0);const restartedRepo=new FileScheduledDryRunAuditRepository({filePath:join(dir,'audit.json')});assert.equal((await restartedRepo.read()).runs.length,1);
 const held=await lock.acquire();const blockedRunner=new ScheduledDryRunRunner({lock,auditRepository:repo,config,now:()=> '2026-08-18T02:00:00Z'});const blocked=await blockedRunner.run({policy,candidates:[]});assert.equal(blocked.status,'SKIPPED_LOCKED');await lock.release(held.owner.ownerId);assert.equal((await repo.read()).runs.length,1);
 const notDue=await runner.run({policy,candidates:[]});assert.equal(notDue.status,'SKIPPED_NOT_DUE');assert.equal((await repo.read()).runs.length,1);
 assert.throws(()=>new ScheduledDryRunRunner({lock,auditRepository:repo,config:{mode:'LIVE',paidTransportReachable:true}}),/STRUCTURALLY_DRY_RUN/);
 console.log('Scheduled dry-run operation tests passed.');
}finally{await rm(dir,{recursive:true,force:true})}
