import assert from "node:assert/strict";
import crypto from "node:crypto";
import { execFileSync } from "node:child_process";
import { mkdtemp, readFile, rm, writeFile } from "node:fs/promises";
import { join } from "node:path";
import { tmpdir } from "node:os";
import {
  DataForSeoAcquisitionResultProcessor,
  FileDataForSeoMarketEvidenceRepository,
  SellersResultDf003RetentionService,
  assessDataForSeoEvidencePromotion,
  composeInitialAcquisitionPromotionAssessment,
  createGovernedInitialAcquisitionIdentityProjection,
  createMerchantIdentityReviewDecision,
  createSellersEnrichmentAuthorizationRequest,
  resolveDataForSeoMerchantIdentity,
  validateSellersRetentionLineage,
  validateSellersRetentionResults
} from "../index.js";
import { validateRetailer, validateRetailerRepository } from "../../atlas/index.js";

const ids={productId:"4796965035927175117",dataDocId:"9225099931765836490",gid:"4027682025249817743"};
const proposal={schemaVersion:"1.0",proposalId:"sellerenrich_2bf037679693b6adae4815ea",status:"PENDING_OPERATOR_REVIEW",createdAt:"2026-09-01T17:58:20.488Z",operation:"SELLERS",atlasProductId:"ram_crucial_cp2k16g56c46u5",sourceProductsTaskId:"09011702-2304-0179-0000-c977c7e8a824",sourceProductInfoTaskId:"09011739-2304-0455-0000-2f32c707dfc6",sourceProductInfoAuthorizationId:"enrichauth_54aa607cf7baf70a24e54c0a",sourceProductInfoProposalId:"enrich_de39dafdbbad923d0cbb2dc6",sourceProductInfoExecutionRunId:"acqrun_4090bfb8-e98c-4ec5-b545-05e681e2ad31",providerIdentity:ids,evidence:{title:"Crucial Pro 32GB DDR5",specifications:[],sellerCount:1},estimatedCostUsd:.001,maxPaidTasks:1,automaticPaidRetries:0,authorizationCreated:false,validation:{schemaVersion:"1.0",status:"VALIDATED",lineage:{schemaVersion:"1.0",status:"VALIDATED",productInfoTaskId:"09011739-2304-0455-0000-2f32c707dfc6",productInfoAuthorizationId:"enrichauth_54aa607cf7baf70a24e54c0a",productInfoPlanId:"enrichplan_0e6b13bfb42214a01f591d14",productInfoProposalId:"enrich_de39dafdbbad923d0cbb2dc6",atlasProductId:"ram_crucial_cp2k16g56c46u5",sourceProductsTaskId:"09011702-2304-0179-0000-c977c7e8a824",executionRunId:"acqrun_4090bfb8-e98c-4ec5-b545-05e681e2ad31",providerIdentity:ids},providerIdentity:{status:"VALIDATED"},atlas:{atlasProductId:"ram_crucial_cp2k16g56c46u5",status:"COMPATIBLE_WITH_UNKNOWNS",contradictions:[]}}};
proposal.validationDigest=crypto.createHash("sha256").update(JSON.stringify(proposal.validation)).digest("hex");
const authorization=createSellersEnrichmentAuthorizationRequest({proposal,createdAt:"2026-09-01T18:01:04.518Z",spentTodayUsd:.002});
assert.equal(authorization.requestId,"sellerauth_685b971d63777a6c3854b314");
assert.equal(authorization.planId,"sellerplan_f601af2808675fdb6f548480");
const sellersTaskId="09011802-2304-0183-0000-b27c074679a9",productInfoTaskId=proposal.sourceProductInfoTaskId,candidateId=`sellers:${proposal.atlasProductId}:${proposal.proposalId}`;
const taskLedger=[{requestKey:"products",kind:"PRODUCTS",taskId:proposal.sourceProductsTaskId,costUsd:.001,createdStatus:20100,sourceId:"DATAFORSEO_GOOGLE_SHOPPING"},{requestKey:"product-info",kind:"PRODUCT_INFO",taskId:productInfoTaskId,costUsd:.001,createdStatus:20100,sourceId:"DATAFORSEO_GOOGLE_SHOPPING"},{requestKey:"sellers",kind:"SELLERS",taskId:sellersTaskId,costUsd:.001,createdStatus:20100,sourceId:"DATAFORSEO_GOOGLE_SHOPPING"}];
const executionRuns=[{schemaVersion:"1.0",runId:"acqrun_669db492-b577-4e97-92df-e1965c607435",planId:authorization.planId,status:"COMPLETED",plannedTasks:1,attemptedTasks:1,completedTasks:1,failedTasks:0,tasks:[{candidateId,outcome:"COMPLETED",providerTaskId:sellersTaskId}]}];
const authorizationConsumptions=[{authorizationId:authorization.requestId,planId:authorization.planId,consumedAt:"2026-09-01T18:02:26.845Z"}];
const lineageInput={sellersTaskId,productInfoTaskId,sellersAuthorization:authorization,sellersProposal:proposal,taskLedger,executionRuns,authorizationConsumptions};
const lineage=validateSellersRetentionLineage(lineageInput);
assert.equal(lineage.status,"VALIDATED");assert.equal(lineage.sellersExecutionRunId,executionRuns[0].runId);assert.equal(lineage.atlasProductId,proposal.atlasProductId);

const sellerItem={type:"shops_list",seller_name:"Fixture Memory",domain:"fixture-memory.example",url:"https://fixture-memory.example/crucial",base_price:99.99,shipping_price:null,tax:null,total_price:99.99,currency:"USD",product_condition:null,product_availability:"in_stock",details:"Crucial CP2K16G56C46U5"};
const productInfoItem={title:"Crucial Pro CP2K16G56C46U5 32GB DDR5 5600",product_id:ids.productId,data_docid:ids.dataDocId,gid:ids.gid,specifications:[]};
const sellersResult={id:sellersTaskId,cost:0,result:[{title:productInfoItem.title,product_id:ids.productId,data_docid:ids.dataDocId,gid:ids.gid,items:[sellerItem]}]};
const productInfoResult={id:productInfoTaskId,cost:0,result:[{items:[productInfoItem]}]};
const governed=validateSellersRetentionResults({lineage,sellersResult,productInfoResult});
assert.equal(governed.status,"VALIDATED");assert.ok(governed.providerIdentity.comparisons.every(entry=>entry.authorizationToProductInfo==="MATCH"&&entry.authorizationToSellers==="MATCH"));
const atlasProduct=JSON.parse(await readFile(new URL("../../atlas/products/ram/ddr5/HR-RAM-DDR5-000002-crucial-crucial-pro-cp2k16g56c46u5.json",import.meta.url),"utf8"));
const rawPayloadReference=`dataforseo:sellers:${sellersTaskId}:item:0`;
const initialProjection=createGovernedInitialAcquisitionIdentityProjection({governance:governed,sellersProposal:proposal,atlasProduct,sellerItem,rawPayloadReference});
assert.equal(initialProjection.df003Outcome,"CONFIRMED");assert.equal(initialProjection.effectiveProductState,"VERIFIED");assert.equal(initialProjection.atlasProductId,proposal.atlasProductId);assert.equal(initialProjection.sellerAssessment.status,"COMPATIBLE_WITH_UNKNOWNS");

const lineageFailures=[
  ["unknown task",{sellersTaskId:"unknown"}],
  ["duplicate task",{taskLedger:[...taskLedger,{...taskLedger[2],requestKey:"duplicate"}]}],
  ["wrong task operation",{taskLedger:taskLedger.map(entry=>entry.taskId===sellersTaskId?{...entry,kind:"PRODUCT_INFO"}:entry)}],
  ["wrong authorization",{authorizationConsumptions:[{authorizationId:"wrong",planId:authorization.planId}]}],
  ["unconsumed",{authorizationConsumptions:[]}],
  ["wrong Product Info task",{productInfoTaskId:"other"}],
  ["duplicate execution",{executionRuns:[...executionRuns,{...executionRuns[0],runId:"duplicate"}]}],
  ["failed execution",{executionRuns:[{...executionRuns[0],status:"FAILED"}]}],
  ["conflicting completed task",{executionRuns:[{...executionRuns[0],attemptedTasks:2,completedTasks:2,tasks:[...executionRuns[0].tasks,{candidateId:"other",outcome:"COMPLETED",providerTaskId:"other"}]}]}]
];
for(const [name,change] of lineageFailures)assert.throws(()=>validateSellersRetentionLineage({...lineageInput,...change}),undefined,name);
const wrongProposal={...proposal,atlasProductId:"wrong"};assert.throws(()=>validateSellersRetentionLineage({...lineageInput,sellersProposal:wrongProposal}),undefined,"wrong Atlas product");
const wrongProducts={...proposal,sourceProductsTaskId:"wrong"};assert.throws(()=>validateSellersRetentionLineage({...lineageInput,sellersProposal:wrongProducts}),undefined,"wrong PRODUCTS lineage");
const wrongPlan=structuredClone(authorization);wrongPlan.planId="wrong";assert.throws(()=>validateSellersRetentionLineage({...lineageInput,sellersAuthorization:wrongPlan}),undefined,"wrong plan");
const wrongProposalId=structuredClone(authorization);wrongProposalId.proposalId="wrong";assert.throws(()=>validateSellersRetentionLineage({...lineageInput,sellersAuthorization:wrongProposalId}),undefined,"wrong proposal");

for(const [name,change,pattern] of [
  ["wrong seller envelope",{sellersResult:{...sellersResult,id:"wrong"}},/TASK_MISMATCH/],
  ["wrong Product Info envelope",{productInfoResult:{...productInfoResult,id:"wrong"}},/TASK_MISMATCH/],
  ["malformed sellers",{sellersResult:{id:sellersTaskId,cost:0,result:[]}},/MALFORMED/],
  ["malformed Product Info",{productInfoResult:{id:productInfoTaskId,cost:0,result:[{items:[]}]}},/MALFORMED/],
  ["non-zero sellers retrieval",{sellersResult:{...sellersResult,cost:.001}},/ZERO_COST/],
  ["productId drift",{productInfoResult:{...productInfoResult,result:[{items:[{...productInfoItem,product_id:"other"}]}]}},/PRODUCTID_DRIFT/],
  ["dataDocId drift",{productInfoResult:{...productInfoResult,result:[{items:[{...productInfoItem,data_docid:"other"}]}]}},/DATADOCID_DRIFT/],
  ["gid drift",{productInfoResult:{...productInfoResult,result:[{items:[{...productInfoItem,gid:"other"}]}]}},/GID_DRIFT/],
  ["seller product context drift",{sellersResult:{...sellersResult,result:[{...sellersResult.result[0],data_docid:"other"}]}},/DATADOCID_DRIFT/]
])assert.throws(()=>validateSellersRetentionResults({lineage,sellersResult,productInfoResult,...change}),pattern,name);

const projectionFailure=(change,pattern)=>assert.throws(()=>createGovernedInitialAcquisitionIdentityProjection({governance:governed,sellersProposal:proposal,atlasProduct,sellerItem,rawPayloadReference,...change}),pattern);
projectionFailure({atlasProduct:{...atlasProduct,identity:{...atlasProduct.identity,atlasProductId:"wrong"}}},/ATLAS_PRODUCT/);
projectionFailure({atlasProduct:{...atlasProduct,governance:{...atlasProduct.governance,lifecycleStatus:"DRAFT"}}},/ACTIVE_READY/);
projectionFailure({atlasProduct:{...atlasProduct,governance:{...atlasProduct.governance,publicationStatus:"PENDING"}}},/ACTIVE_READY/);
for(const field of ["sourceProductsTaskId","productInfoTaskId","sellersTaskId"]){const changed=structuredClone(governed);changed.lineage[field]="wrong";projectionFailure({governance:changed},/BINDING|EVIDENCE/);}
for(const field of ["productId","dataDocId","gid"]){const changed=structuredClone(governed);changed.lineage.providerIdentity[field]="wrong";projectionFailure({governance:changed},/PROVIDER|PROJECTION/);}
const contradictedProposal=structuredClone(proposal);contradictedProposal.validation.atlas.status="CONTRADICTION";contradictedProposal.validation.atlas.contradictions=["MPN_CONFLICT"];contradictedProposal.validationDigest=crypto.createHash("sha256").update(JSON.stringify(contradictedProposal.validation)).digest("hex");projectionFailure({sellersProposal:contradictedProposal},/PRODUCT_INFO_CONTRADICTION/);
for(const conflictingSeller of [{...sellerItem,manufacturer_part_number:"OTHER-MPN"},{...sellerItem,details:"Crucial 16GB DDR5"},{...sellerItem,details:"Crucial 32GB DDR4"},{...sellerItem,details:"Crucial 32GB 1x32GB DDR5"}])projectionFailure({sellerItem:conflictingSeller},/SELLER_CONTRADICTION/);
projectionFailure({sellersProposal:{...proposal,validationDigest:"malformed"}},/PROPOSAL_BINDING/);
projectionFailure({governance:{...governed,status:"UNVALIDATED"}},/GOVERNANCE_REQUIRED/);

const sparseSellers={...sellersResult,result:[{title:productInfoItem.title,items:[sellerItem]}]};
assert.equal(validateSellersRetentionResults({lineage,sellersResult:sparseSellers,productInfoResult}).providerIdentity.comparisons[0].authorizationToSellers,"UNKNOWN");

const root=await mkdtemp(join(tmpdir(),"hr-b008a-"));
try{
  const evidenceRepository=new FileDataForSeoMarketEvidenceRepository({statePath:join(root,"evidence.json"),now:()=>"2026-09-01T18:03:00Z"});
  const atlasResolver={resolve:async()=>({outcome:"PROBABLE",atlasProductId:proposal.atlasProductId,externalProductId:null,evidence:[],candidateAtlasProductIds:[],automaticMercuryEligible:false})};
  const processor=new DataForSeoAcquisitionResultProcessor({atlasResolver,evidenceRepository,retailers:[]});
  const retention=new SellersResultDf003RetentionService({resultProcessor:processor});
  const input={sellersResult,productInfoResult,sellersTaskId,productInfoTaskId,observedAt:"2026-09-01T18:02:36.223Z",providerIdentity:ids,candidateId,governedAcquisition:{createProjection:({sellerItem,rawPayloadReference})=>createGovernedInitialAcquisitionIdentityProjection({governance:governed,sellersProposal:proposal,atlasProduct,sellerItem,rawPayloadReference})}};
  const result=await retention.retain(input);assert.equal(result.retained,1);assert.equal(result.actualSpendUsd,0);assert.equal(result.integrations[0].merchantIdentityOutcome,"DISCOVERED");
  const stored=(await evidenceRepository.getAll())[0];assert.equal(stored.candidate.identity.outcome,"CONFIRMED");assert.equal(stored.candidate.identity.atlasProductId,proposal.atlasProductId);assert.equal(stored.candidate.marketEvidence.provenance.sourceTaskId,sellersTaskId);assert.equal(stored.candidate.marketEvidence.offer.condition,null);assert.equal(stored.candidate.marketEvidence.pricing.shippingPrice,null);assert.equal(result.integrations[0].historicalOutcome,"NOT_ELIGIBLE");
  assert.equal((await retention.retain(input)).duplicates,1);assert.equal((await evidenceRepository.getAll()).length,1);
  await assert.rejects(()=>retention.retain({...input,productInfoResult:{...productInfoResult,result:[{items:[{...productInfoItem,gid:"drift"}]}]}}),/DF003_PRODUCT_INFO_IDENTITY_MISMATCH/);
  const contradiction={...sellersResult,result:[{...sellersResult.result[0],items:[{...sellerItem,url:"https://other.example/item"}]}]};const before=structuredClone(await evidenceRepository.getAll());await assert.rejects(()=>retention.retain({...input,sellersResult:contradiction}),/ACQUISITION_EVIDENCE_CONFLICT/);assert.deepEqual(await evidenceRepository.getAll(),before);
  const retainedAmbiguous=structuredClone(stored);retainedAmbiguous.candidate.identity={outcome:"AMBIGUOUS",atlasProductId:null,externalProductId:ids.productId,candidateAtlasProductIds:[proposal.atlasProductId,"ram_crucial_ct32g56c46u5"],evidence:[]};retainedAmbiguous.candidate.governance={requiresReview:true,canonicalObservationEligible:false,automaticPublicationEligible:false};retainedAmbiguous.eligibilityAtRetention={...stored.eligibilityAtRetention,status:"REVIEW_REQUIRED",canonicalObservationEligible:false,historicalAnalyticsEligible:false,retailerId:null,requiresReview:true,reasons:["MERCHANT_REGISTRATION_REQUIRED"]};const immutable=structuredClone(retainedAmbiguous),reassessmentProjection=createGovernedInitialAcquisitionIdentityProjection({governance:governed,sellersProposal:proposal,atlasProduct,record:retainedAmbiguous});const reassessed=assessDataForSeoEvidencePromotion({records:[retainedAmbiguous],initialAcquisitionIdentityProjections:[reassessmentProjection]});assert.equal(reassessed.state,"REVIEW_REQUIRED");assert.equal(reassessed.productIdentity,"VERIFIED");assert.equal(reassessed.merchantIdentity,"DISCOVERED");assert.equal(reassessed.historicalEligible,false);assert.equal(reassessed.identityProjections[0].product.decisionId,null);assert.equal(reassessed.identityProjections[0].product.governedAcquisitionProjectionId,reassessmentProjection.projectionId);assert.ok(!reassessed.reasons.some(value=>value.code==="PRODUCT_IDENTITY_NOT_VERIFIED"));assert.deepEqual(retainedAmbiguous,immutable);
  const sellers=["Microless.com","AAAwave","Grooves-Inc.com","directmacro.com","ServerOrbit.com","MemoryC.com","Hard Disk Direct","NextWarehouse.com","Micro Center","CompSource"];
  const cohort=sellers.map((name,index)=>{const value=structuredClone(retainedAmbiguous);value.evidenceId=`dfev_crucial_${String(index).padStart(2,"0")}`;value.idempotencyKey=`crucial-${index}`;value.candidate.marketEvidence.seller={...value.candidate.marketEvidence.seller,name,domain:`seller-${index}.example`,url:`https://seller-${index}.example/item`};value.candidate.marketEvidence.provenance.rawPayloadReference=`dataforseo:sellers:${sellersTaskId}:item:${index}`;value.candidate.marketEvidence.pricing.shippingPrice=[0,2].includes(index)?10+index:null;value.candidate.marketEvidence.offer.availability=index>=8?"out_of_stock":"in_stock";return value;});
  cohort[5].candidate.marketEvidence.seller={...cohort[5].candidate.marketEvidence.seller,domain:"www.memoryc.com",url:"https://www.memoryc.com/item"};cohort[5].merchantResolution={...cohort[5].merchantResolution,merchantKey:"domain:memoryc.com",sellerName:"MemoryC.com",canonicalDomain:"memoryc.com",suppliedDomain:"memoryc.com",urlDomain:"memoryc.com"};
  const retentionAudit={schemaVersion:"1.0",operation:"SELLERS_RESULT_DF003_RETENTION",sellersTaskId,productInfoTaskId,integrations:cohort.map(record=>({evidenceId:record.evidenceId})),governance:governed,atlasProductId:proposal.atlasProductId};
  const cohortSnapshot=structuredClone(cohort);const composition=composeInitialAcquisitionPromotionAssessment({records:cohort,requestedAtlasProductId:proposal.atlasProductId,retentionAudit,sellersProposalEnvelope:{schemaVersion:"1.0",proposal},atlasProduct});assert.equal(composition.mode,"GOVERNED_INITIAL_ACQUISITION_BINDING");assert.equal(composition.records.length,10);assert.equal(composition.initialAcquisitionIdentityProjections.length,10);assert.ok(composition.initialAcquisitionIdentityProjections.every(value=>value.atlasProductId===proposal.atlasProductId&&value.df003Outcome==="CONFIRMED"));
  for(const [index,record] of composition.records.entries()){const assessment=assessDataForSeoEvidencePromotion({records:[record],initialAcquisitionIdentityProjections:[composition.initialAcquisitionIdentityProjections[index]]});assert.equal(assessment.productIdentity,"VERIFIED");assert.equal(assessment.merchantIdentity,"DISCOVERED");assert.equal(assessment.state,"REVIEW_REQUIRED");assert.equal(assessment.historicalEligible,false);assert.equal(record.candidate.marketEvidence.offer.condition,null);assert.equal(record.candidate.marketEvidence.pricing.shippingPrice,[0,2].includes(index)?10+index:null);assert.equal(record.candidate.marketEvidence.offer.availability,index>=8?"out_of_stock":"in_stock");}
  assert.deepEqual(cohort,cohortSnapshot);
  const legacy=composeInitialAcquisitionPromotionAssessment({records:[stored],requestedAtlasProductId:proposal.atlasProductId});assert.equal(legacy.mode,"GENERIC_RESOLVER");assert.equal(legacy.records.length,1);assert.equal(legacy.initialAcquisitionIdentityProjections.length,0);
  assert.throws(()=>composeInitialAcquisitionPromotionAssessment({records:cohort,requestedAtlasProductId:proposal.atlasProductId,retentionAudit:{...retentionAudit,integrations:[...retentionAudit.integrations,{evidenceId:cohort[0].evidenceId}]},sellersProposalEnvelope:{proposal},atlasProduct}),/BINDING_CONFLICT/);
  assert.throws(()=>composeInitialAcquisitionPromotionAssessment({records:cohort,requestedAtlasProductId:proposal.atlasProductId,retentionAudit:{...retentionAudit,integrations:retentionAudit.integrations.slice(1)},sellersProposalEnvelope:{proposal},atlasProduct}),/EVIDENCE_SET_CONFLICT/);
  assert.throws(()=>composeInitialAcquisitionPromotionAssessment({records:cohort,requestedAtlasProductId:proposal.atlasProductId,retentionAudit,sellersProposalEnvelope:{proposal:{...proposal,validationDigest:"invalid"}},atlasProduct}),/PROPOSAL_BINDING/);
  const drift=structuredClone(cohort);drift[0].candidate.marketEvidence.productEvidence.productId="drift";assert.throws(()=>composeInitialAcquisitionPromotionAssessment({records:drift,requestedAtlasProductId:proposal.atlasProductId,retentionAudit,sellersProposalEnvelope:{proposal},atlasProduct}),/PROVIDER_IDENTITY_CONFLICT/);
  assert.throws(()=>composeInitialAcquisitionPromotionAssessment({records:cohort,requestedAtlasProductId:proposal.atlasProductId,retentionAudit,sellersProposalEnvelope:{proposal},atlasProduct:{...atlasProduct,governance:{...atlasProduct.governance,lifecycleStatus:"DRAFT"}}}),/ACTIVE_READY/);
  const conflict=structuredClone(cohort);conflict[0].candidate.marketEvidence.offer.details="Crucial 32GB DDR4 1x32GB";assert.throws(()=>composeInitialAcquisitionPromotionAssessment({records:conflict,requestedAtlasProductId:proposal.atlasProductId,retentionAudit,sellersProposalEnvelope:{proposal},atlasProduct}),/SELLER_CONTRADICTION/);
  const evidenceState=join(root,"cohort-evidence.json"),decisionState=join(root,"cohort-decisions.json"),retentionState=join(root,"cohort-retention.json"),proposalState=join(root,"cohort-proposal.json");await writeFile(evidenceState,JSON.stringify({version:"1.0",records:Object.fromEntries(cohort.map(record=>[record.evidenceId,record])),idempotency:{}}),"utf8");await writeFile(decisionState,JSON.stringify({version:"1.0",sequence:0,decisions:{},bySubject:{},idempotency:{},remediationSequence:0,remediations:{},remediationByDecision:{},remediationIdempotency:{}}),"utf8");await writeFile(retentionState,JSON.stringify(retentionAudit),"utf8");await writeFile(proposalState,JSON.stringify({schemaVersion:"1.0",proposal}),"utf8");
  const output=execFileSync(process.execPath,["scripts/mercury-evidence-promotion-assess.mjs",`--state=${evidenceState}`,`--decision-state=${decisionState}`,`--atlas-product=${proposal.atlasProductId}`,`--retention-state=${retentionState}`,`--sellers-proposal=${proposalState}`],{cwd:process.cwd(),encoding:"utf8",stdio:["ignore","pipe","pipe"]});assert.match(output,/Evidence count:\s+10/);assert.match(output,/Product identity:\s+VERIFIED/);assert.match(output,/Merchant identity:\s+DISCOVERED/);assert.match(output,/Composition mode:\s+GOVERNED_INITIAL_ACQUISITION_BINDING/);assert.match(output,/"identitySource":"GOVERNED_INITIAL_ACQUISITION_BINDING"/);assert.match(output,/"merchantReason":"ATLAS_RETAILER_NOT_FOUND"/);assert.match(output,/Paid task created:\s+NO/);assert.match(output,/Actual spend:\s+\$0\.000/);
  const memoryCRetailer={id:"RETAILER-0003",name:"MemoryC",slug:"memoryc",websiteUrl:"https://www.memoryc.com",status:"active",regions:["US"],supportedCurrencies:["USD"],affiliateProgram:{available:false,status:"unknown",network:null,disclosureRequired:true},metadata:{createdAt:"2026-09-01T00:00:00Z",updatedAt:"2026-09-01T00:00:00Z",sourceReferences:["https://www.memoryc.com/help/company_info.html","https://www.memoryc.com/contact.html","https://www.memoryc.com/help/conditions.html"]}};
  const existingRetailers=await Promise.all(["RETAILER-0001-amazon.json","RETAILER-0002-platinummicro.json"].map(async name=>JSON.parse(await readFile(new URL(`../../atlas/retailers/${name}`,import.meta.url),"utf8"))));assert.equal(validateRetailer(memoryCRetailer).valid,true);assert.equal(validateRetailerRepository([...existingRetailers,memoryCRetailer]).valid,true);for(const domain of ["memoryc.com","www.memoryc.com"]){const marketEvidence=structuredClone(cohort[5].candidate.marketEvidence);marketEvidence.seller.domain=domain;marketEvidence.seller.url=`https://${domain}/item`;const resolution=resolveDataForSeoMerchantIdentity({marketEvidence,retailers:[memoryCRetailer]});assert.equal(resolution.outcome,"RESOLVED");assert.equal(resolution.retailerId,"RETAILER-0003");assert.equal(resolution.canonicalDomain,"memoryc.com");}
  const memoryCRecord=cohort[5],memoryCProjection=composition.initialAcquisitionIdentityProjections[5],memoryCBefore=structuredClone(memoryCRecord),merchantDecision=createMerchantIdentityReviewDecision({identityReviewDecisionId:"mer_idrev_memoryc_fixture",sequence:1,recordedAt:"2026-09-01T20:00:01Z",discoveredMerchantName:"MemoryC.com",canonicalMerchantName:"MemoryC",canonicalDomain:"memoryc.com",merchantId:"RETAILER-0003",merchantActive:true,previousState:"DISCOVERED",requestedState:"REGISTERED",decisionOutcome:"APPROVED",reviewedAt:"2026-09-01T20:00:00Z",reviewedBy:"operator:fixture",reason:"Authoritative MemoryC identity and exact canonical domain fixture reviewed.",supportingEvidenceReferences:[memoryCRecord.evidenceId],contradictionStatus:"NONE",audit:{source:"OPERATOR_REVIEW_FIXTURE",requestId:"memoryc-registration-fixture",preparedAt:"2026-09-01T19:59:00Z"}});
  const registered=assessDataForSeoEvidencePromotion({records:[memoryCRecord],identityReviewDecisions:[merchantDecision],atlasRetailers:[memoryCRetailer],initialAcquisitionIdentityProjections:[memoryCProjection]});assert.equal(registered.productIdentity,"VERIFIED");assert.equal(registered.identityProjections[0].product.decisionId,null);assert.equal(registered.merchantIdentity,"REGISTERED");assert.equal(registered.state,"HISTORICAL_ELIGIBLE");assert.equal(registered.historicalEligible,true);assert.equal(registered.canonicalEligible,false);assert.equal(registered.publicationEligible,false);assert.equal(memoryCRecord.candidate.marketEvidence.offer.condition,null);assert.equal(memoryCRecord.candidate.marketEvidence.pricing.shippingPrice,null);assert.equal(memoryCRecord.candidate.marketEvidence.offer.availability,"in_stock");assert.deepEqual(memoryCRecord,memoryCBefore);for(const field of ["observable","publiclyComparable","recommendable","affiliateEnabled","rights"])assert.equal(memoryCRetailer[field],undefined);
  for(const domain of ["memoryc.example","memoryc.com.example","shop.memoryc.com"]){const marketEvidence=structuredClone(memoryCRecord.candidate.marketEvidence);marketEvidence.seller.domain=domain;marketEvidence.seller.url=`https://${domain}/item`;assert.equal(resolveDataForSeoMerchantIdentity({marketEvidence,retailers:[memoryCRetailer]}).outcome,"DISCOVERED");}
  assert.equal(resolveDataForSeoMerchantIdentity({marketEvidence:memoryCRecord.candidate.marketEvidence,retailers:[memoryCRetailer,{...memoryCRetailer,id:"RETAILER-9999"}]}).outcome,"CONFLICT");assert.equal(resolveDataForSeoMerchantIdentity({marketEvidence:memoryCRecord.candidate.marketEvidence,retailers:[]}).outcome,"DISCOVERED");const domainConflict=structuredClone(memoryCRecord.candidate.marketEvidence);domainConflict.seller.url="https://example.com/item";assert.equal(resolveDataForSeoMerchantIdentity({marketEvidence:domainConflict,retailers:[memoryCRetailer]}).outcome,"CONFLICT");const inactive=assessDataForSeoEvidencePromotion({records:[memoryCRecord],identityReviewDecisions:[merchantDecision],atlasRetailers:[{...memoryCRetailer,status:"inactive"}],initialAcquisitionIdentityProjections:[memoryCProjection]});assert.equal(inactive.state,"BLOCKED");assert.equal(inactive.historicalEligible,false);const merchantOnly=assessDataForSeoEvidencePromotion({records:[memoryCRecord],identityReviewDecisions:[merchantDecision],atlasRetailers:[memoryCRetailer]});assert.equal(merchantOnly.historicalEligible,false);assert.notEqual(merchantOnly.productIdentity,"VERIFIED");assert.equal(validateRetailer({...memoryCRetailer,websiteUrl:"not-a-url"}).valid,false);
}finally{await rm(root,{recursive:true,force:true});}
console.log("B-009A/B-010A/MemoryC retailer-readiness fixture tests passed (79 cases).");
