import assert from 'node:assert/strict';import {mkdtemp,rm} from 'node:fs/promises';import {join} from 'node:path';import {tmpdir} from 'node:os';
import {calculateGovernedSpendForUtcDay,createProductInfoEnrichmentAuthorizationRequest,createSellersEnrichmentAuthorizationRequest,createAcquisitionBudgetPolicy,createAcquisitionPlan,ControlledAcquisitionExecutor,FileAcquisitionExecutionLedgerRepository,FileSingleWriterRunLock} from '../index.js';
const at='2026-09-01T18:00:00Z',run=(kind,cost,startedAt='2026-09-01T12:00:00Z',extra={})=>({runId:`${kind}-${startedAt}`,planId:`plan-${kind}-${startedAt}`,startedAt,actualSpendUsd:cost,operation:kind,...extra});
const mixed=[run('PRODUCTS',.001),run('PRODUCT_INFO',.001),run('SELLERS',.001),run('HISTORICAL_REFRESH_SELLERS',.001),run('OLD',.5,'2026-08-31T23:59:59Z'),run('DRY',.5,'2026-09-01T10:00:00Z',{mode:'DRY_RUN'})];
assert.equal(calculateGovernedSpendForUtcDay(mixed,at),.004);assert.equal(calculateGovernedSpendForUtcDay(mixed,'2026-08-31T23:59:59Z'),.5);assert.throws(()=>calculateGovernedSpendForUtcDay([{startedAt:'bad',actualSpendUsd:.001}],at),/INVALID_ACQUISITION_EXECUTION_RECORD/);assert.throws(()=>calculateGovernedSpendForUtcDay([{startedAt:at,actualSpendUsd:-1}],at),/INVALID_ACQUISITION_EXECUTION_RECORD/);
const productProposal={status:'PENDING_OPERATOR_REVIEW',operation:'PRODUCT_INFO',proposalId:'enrich',sourceTaskId:'products',atlasProductId:'ram_crucial',estimatedCostUsd:.001,maxPaidTasks:1,automaticPaidRetries:0,providerIdentity:{productId:'p',dataDocId:'d',gid:'g'}},sellerProposal={status:'PENDING_OPERATOR_REVIEW',operation:'SELLERS',proposalId:'seller',atlasProductId:'ram_crucial',sourceProductsTaskId:'products',sourceProductInfoTaskId:'info',sourceProductInfoAuthorizationId:'auth',estimatedCostUsd:.001,maxPaidTasks:1,automaticPaidRetries:0,providerIdentity:{productId:'p',dataDocId:'d',gid:'g'}};
const product=createProductInfoEnrichmentAuthorizationRequest({proposal:productProposal,createdAt:at,spentTodayUsd:.001});assert.equal(product.plan.spentTodayUsd,.001);assert.equal(product.plan.spentTodayUsd+product.plan.estimatedApprovedSpendUsd,.002);const sellers=createSellersEnrichmentAuthorizationRequest({proposal:sellerProposal,createdAt:at,spentTodayUsd:.002});assert.equal(sellers.plan.spentTodayUsd,.002);assert.equal(sellers.plan.spentTodayUsd+sellers.plan.estimatedApprovedSpendUsd,.003);assert.doesNotThrow(()=>createProductInfoEnrichmentAuthorizationRequest({proposal:productProposal,createdAt:at,spentTodayUsd:.009}));assert.throws(()=>createProductInfoEnrichmentAuthorizationRequest({proposal:productProposal,createdAt:at,spentTodayUsd:.01}),/DAILY_BUDGET_EXCEEDED/);assert.throws(()=>createSellersEnrichmentAuthorizationRequest({proposal:sellerProposal,createdAt:at,spentTodayUsd:.01}),/DAILY_BUDGET_EXCEEDED/);
const dir=await mkdtemp(join(tmpdir(),'hr-b006a-'));try{let calls=0;const ledger=new FileAcquisitionExecutionLedgerRepository({filePath:join(dir,'ledger.json')}),lock=new FileSingleWriterRunLock({lockPath:join(dir,'lock')});await ledger.append({...run('PRODUCTS',.001),schemaVersion:'1.0',status:'COMPLETED'});const policy=createAcquisitionBudgetPolicy({enabled:true,maxPaidTasksPerRun:1,maxSpendPerRunUsd:.001,maxSpendPerDayUsd:.01,automaticPaidRetries:0}),plan=createAcquisitionPlan({policy,plannedAt:at,spentTodayUsd:.001,candidates:[{candidateId:'info',priority:'NORMAL',estimatedCostUsd:.001,execution:{kind:'PRODUCT_INFO'}}]}),executor=new ControlledAcquisitionExecutor({runLock:lock,ledgerRepository:ledger,transport:{execute:async()=>{calls++;return{costUsd:.001}}},now:()=>at});await ledger.append({...run('OTHER',.001,'2026-09-01T17:00:00Z'),schemaVersion:'1.0',status:'COMPLETED'});await assert.rejects(()=>executor.execute(plan),/DAILY_SPEND_SNAPSHOT_DRIFT/);assert.equal(calls,0);assert.equal((await ledger.getAll()).length,2);}finally{await rm(dir,{recursive:true,force:true});}
console.log('Shared current-day Mercury spend governance tests passed.');
