import assert from "node:assert/strict";
import registry from "../rights/SourceRightsRegistry.js";
assert.equal(registry.get("AMAZON_CREATORS_API").retention.contentTtlMs, 3600000);
assert.equal(registry.get("BEST_BUY_PRODUCTS_API").live.comparison, "CLARIFICATION_REQUIRED");
const rakuten = registry.get("RAKUTEN_NEWEGG_PRODUCT_CATALOG");
assert.equal(rakuten.processing.ephemeral, "ALLOWED");
assert.equal(rakuten.retention.current, "ALLOWED");
assert.equal(rakuten.live.publicDisplay, "ALLOWED");
assert.equal(rakuten.live.comparison, "ALLOWED");
assert.equal(rakuten.retention.historical, "BLOCKED");
assert.equal(rakuten.derivation.analytics, "BLOCKED");
assert.equal(rakuten.derivation.recommendation, "BLOCKED");
assert.equal(rakuten.distribution.api, "BLOCKED");
assert.equal(registry.get("DOES_NOT_EXIST"), null);
console.log("Source rights registry tests passed.");
