import assert from "node:assert/strict";
import registry, { sourceRightsProfileDigest } from "../rights/SourceRightsRegistry.js";
assert.equal(registry.get("AMAZON_CREATORS_API").retention.contentTtlMs, 3600000);
assert.equal(registry.get("BEST_BUY_PRODUCTS_API").live.comparison, "CLARIFICATION_REQUIRED");
const rakuten = registry.get("RAKUTEN_NEWEGG_PRODUCT_CATALOG");
assert.equal(rakuten.processing.ephemeral, "ALLOWED");
assert.equal(rakuten.retention.current, "ALLOWED");
assert.equal(rakuten.live.publicDisplay, "ALLOWED");
assert.equal(rakuten.live.comparison, "ALLOWED");
assert.equal(rakuten.retention.historical, "ALLOWED");
assert.equal(rakuten.retention.previouslyCollectedAfterRelationshipEnds, "ALLOWED");
assert.equal(rakuten.derivation.analytics, "ALLOWED");
assert.equal(rakuten.derivation.historicalAnalytics, "ALLOWED");
assert.equal(rakuten.derivation.recommendation, "ALLOWED");
assert.equal(rakuten.distribution.api, "BLOCKED");
assert.equal(rakuten.retention.contentTtlMs, 129600000);
assert.equal(rakuten.provenance.retailerId, "RETAILER-0004");
assert.equal(rakuten.provenance.advertiser, "NEWEGG");
assert.equal(rakuten.provenance.feedFamily, "PRODUCT_CATALOG");
assert.equal(rakuten.provenance.futureAcquisitionAfterRelationshipEnds, "NOT_AUTHORIZED");
assert.equal(rakuten.provenance.rawPayloadPolicy, "EXISTING_BOUNDED_PROVIDER_POLICY_UNCHANGED");
assert.ok(rakuten.provenance.unsupported.includes("UNRELATED_RAKUTEN_ADVERTISERS"));
const priorRakuten=registry.historicalSourceProfiles.find(profile=>profile.sourceId==="RAKUTEN_NEWEGG_PRODUCT_CATALOG");
assert.equal(priorRakuten.retention.historical,"BLOCKED");
assert.equal(registry.verifyLineage(priorRakuten.sourceId,sourceRightsProfileDigest(priorRakuten)).state,"HISTORICAL_PROFILE");
assert.equal(registry.get("DATAFORSEO_AMAZON").retention.historical, "ALLOWED");
assert.equal(registry.get("AMAZON_CREATORS_API").retention.historical, "BLOCKED");
assert.equal(registry.get("DOES_NOT_EXIST"), null);
console.log("Source rights registry tests passed.");
