import { createMercuryTemplate } from "./ForgeTemplates.js";
import { DerivedFieldService } from "./DerivedFieldService.js";

import { AtlasProductBuilder } from "./AtlasProductBuilder.js";
import { ForgeIdGenerator } from "./ForgeIdGenerator.js";
import { ForgeValidator } from "./ForgeValidator.js";
import {PublicationReadinessEngine} from "./PublicationReadinessEngine.js";


export class ForgeGenerator {
    constructor() {
        this.idGenerator = new ForgeIdGenerator();
        this.validator = new ForgeValidator();
        this.atlasBuilder = new AtlasProductBuilder();

        this.derivedFieldService =
        new DerivedFieldService();

        this.publicationReadinessEngine =
            new PublicationReadinessEngine();
    }

    generateProduct(input) {
    const derivedInput =
        this.derivedFieldService.apply(input);

    const validation =
        this.validator.validateInput(
            derivedInput
        );

    const publication =
        this.publicationReadinessEngine.evaluate(
            validation
        );

    if (
        publication.status ===
        PublicationReadinessEngine.STATUS.BLOCKED
    ) {
        return this.createFailedResult({
            validation,
            publication
        });
    }

    const now = new Date().toISOString();
    const dateOnly = now.slice(0, 10);

    const productId =
        this.idGenerator.generateProductId(
            derivedInput.category,
            derivedInput.subcategory,
            derivedInput.productNumber
        );

    const observationId =
        this.idGenerator.generateLegacyPriceObservationId(
            dateOnly,
            derivedInput.observationNumber
        );

    const atlasProduct =
        this.atlasBuilder.build({
            input: derivedInput,
            productId,
            timestamp: now,
            validation,
            publication
        });


    const mercuryObservation =
        this.createLegacyMercuryPreview({
            input: derivedInput,
            productId,
            observationId,
            timestamp: now
        });

    const slug =
        this.createSlug(
            derivedInput.productName
        );

    return {
        atlasProduct,
        mercuryObservation,

        atlasFilename:
            `${productId}-${slug}.json`,

        mercuryFilename:
            `${observationId}.json`,

        validation,
        publication,

        warnings:
            validation.warnings
    };
}

    createLegacyMercuryPreview({
        input,
        productId,
        observationId,
        timestamp
    }) {
        const mercuryObservation =
            createMercuryTemplate();

        mercuryObservation.id = observationId;
        mercuryObservation.productId = productId;
        mercuryObservation.retailerId =
            input.retailerId;
        mercuryObservation.observedAt = timestamp;
        mercuryObservation.price = input.price;
        mercuryObservation.currency = input.currency;
        mercuryObservation.availability =
            input.availability;
        mercuryObservation.condition =
            input.condition;
        mercuryObservation.sellerType =
            input.sellerType;
        mercuryObservation.sourceUrl =
            input.retailerUrl;

        mercuryObservation.verification.verifiedAt =
            timestamp;

        mercuryObservation.verification.notes =
            "Legacy Forge Mercury preview only. Not a canonical Mercury observation.";

        mercuryObservation.metadata.createdAt =
            timestamp;

        mercuryObservation.metadata.updatedAt =
            timestamp;

        mercuryObservation.metadata.notes =
            "Legacy Mercury preview generated by Forge v0.2. Canonical ingestion must use the Mercury adapter pipeline.";

        return mercuryObservation;
    }

    createFailedResult({
        validation,
        publication
    }) {
        return {
            atlasProduct: null,
            mercuryObservation: null,
            atlasFilename: null,
            mercuryFilename: null,

            validation,
            publication,

            warnings:
                validation?.warnings ?? []
        };
    }

    createSlug(value) {
        return String(value)
            .trim()
            .toLowerCase()
            .replaceAll(/[^a-z0-9]+/g, "-")
            .replaceAll(/^-+|-+$/g, "");
    }
}