import {createProductInterestSignal} from "../ProductInterestSignal.js";
import {validateFirstPartyProductInterestEvent} from "../FirstPartyProductInterestEvent.js";
import {createFirstPartyInterestSignalId,firstPartyInterestEventFingerprint} from "../FirstPartyProductInterestCollectionRepository.js";
import {BEACON_RETENTION_STATES,createBeaconEvidenceRetentionPolicy,evaluateBeaconEvidenceRetention} from "./BeaconEvidenceRetentionPolicy.js";
const freeze=value=>{if(value&&typeof value==="object"&&!Object.isFrozen(value)){Object.freeze(value);for(const child of Object.values(value))freeze(child);}return value;};
function recordIdentity(raw,index){return typeof raw?.event?.eventId==="string"&&raw.event.eventId.trim()?raw.event.eventId:`INVALID_RECORD_${String(index).padStart(6,"0")}`;}
function validateRecord(raw){const event=validateFirstPartyProductInterestEvent(raw?.event),signal=createProductInterestSignal(raw?.signal);if(!raw||typeof raw!=="object"||Array.isArray(raw)||Object.keys(raw).some(key=>!["event","materialFingerprint","signal"].includes(key))||raw.materialFingerprint!==firstPartyInterestEventFingerprint(event)||signal.signalId!==createFirstPartyInterestSignalId(event.eventId)||signal.provenance?.eventId!==event.eventId||signal.provenance?.retailerId!==event.retailerId||signal.atlasProductId!==event.atlasProductId||signal.observedAt!==event.occurredAt||typeof signal.metadata?.recordedAt!=="string")throw new Error();return {eventId:event.eventId,recordedAt:signal.metadata.recordedAt};}
export function assessBeaconInterestRetention({records,policy,asOf}={}){if(!Array.isArray(records))throw new TypeError("BEACON_RETENTION_RECORDS_INVALID");const validatedPolicy=createBeaconEvidenceRetentionPolicy(policy);if(typeof asOf!=="string"||!Number.isFinite(Date.parse(asOf)))throw new TypeError("BEACON_RETENTION_AS_OF_REQUIRED");const seen=new Set(),evaluations=records.map((raw,index)=>{const fallback=recordIdentity(raw,index);try{const record=validateRecord(raw);if(seen.has(record.eventId))throw new Error();seen.add(record.eventId);return freeze({recordId:record.eventId,...evaluateBeaconEvidenceRetention({recordedAt:record.recordedAt,policy:validatedPolicy,asOf})});}catch{return freeze({recordId:fallback,state:BEACON_RETENTION_STATES.BLOCKED,recordedAt:null,eligibleAt:null,reason:"RETENTION_RECORD_INVALID"});}}).sort((a,b)=>a.recordId.localeCompare(b.recordId)),valid=evaluations.filter(x=>x.state!==BEACON_RETENTION_STATES.BLOCKED),times=valid.map(x=>x.recordedAt).sort(),eligibleRecordIds=evaluations.filter(x=>x.state===BEACON_RETENTION_STATES.DELETE_ELIGIBLE).map(x=>x.recordId),nextTimes=evaluations.filter(x=>x.state===BEACON_RETENTION_STATES.RETAIN).map(x=>x.eligibleAt).sort();return freeze({schemaVersion:"1.0",assessmentType:"BEACON_INTEREST_RETENTION_ASSESSMENT",policyId:validatedPolicy.policyId,evidenceClass:validatedPolicy.evidenceClass,asOf,totalRecords:records.length,retainedCount:evaluations.filter(x=>x.state===BEACON_RETENTION_STATES.RETAIN).length,deleteEligibleCount:eligibleRecordIds.length,blockedCount:evaluations.filter(x=>x.state===BEACON_RETENTION_STATES.BLOCKED).length,oldestRecordedAt:times[0]??null,newestRecordedAt:times.at(-1)??null,nextDeletionEligibilityTime:nextTimes[0]??null,eligibleRecordIds,evaluations,deletionExecuted:false,automaticDeletion:false,cadenceInfluence:"NONE",paidTaskCreated:false,actualSpendUsd:0});}
export default assessBeaconInterestRetention;
