export const INGESTION_STATUSES = Object.freeze({
  ACCEPTED: "ACCEPTED", DUPLICATE: "DUPLICATE", INVALID_INPUT: "INVALID_INPUT",
  BLOCKED_SOURCE_METHOD: "BLOCKED_SOURCE_METHOD", BLOCKED_COMPLIANCE: "BLOCKED_COMPLIANCE",
  ADAPTER_FAILURE: "ADAPTER_FAILURE", IDENTITY_FAILURE: "IDENTITY_FAILURE", VALIDATION_FAILURE: "VALIDATION_FAILURE"
});
export function ingestionResult(status, details = {}) { return Object.freeze({ status, accepted: status === INGESTION_STATUSES.ACCEPTED, ...details }); }
